### ISSUE TITLE
Actionbar & title option for packets.txt

### ISSUE THREAD

**Issue by JackSlacks** [kangarko/ChatControl-Pro#10]
Hello there.

Would be neat if you could add the option to send actionbar & title messages in packets.txt rules.

Example:
```
match ^You don't have permission!
then actionbar You don't have permission!
then deny
```

**Comment by EvilOlaf** [comment]
You could use a 3rd party plugin like TitleManager in combination with the `then console` action which has been added recently. This should work as well.

**Comment by JackSlacks** [comment]
That could work, but I think it would be more efficient without having to execute commands in console for 3rd party plugin.

**Comment by EvilOlaf** [comment]
True. Just in case you need this feature faster than the dev can code it :P

**Comment by kangarko** [comment]
I already coded a plugin AnimeX for such purposes (but there's no support for ChatControl integration). Since they share common library I shall consider implementing it.
