### ISSUE TITLE
Chat.txt rules do not work in Russian

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#100]
I bought premium version and I'm almost fully satisfied but got one problem.. Rules from chat.txt file won't work in other languages such as Russian :C While I placed few of English words to test out, they work..
Screenshots:
http://i.imgur.com/00dWgOi.png
http://i.imgur.com/hIKbSeA.png (here I wrote admin give me op, and it was canceled, and then I wrote it on Russian and it didn't.)

Here are some symbols if it is a bug and you want to fix them.. "Админ дай мне админку"

**Comment by kangarko** [comment]
Try setting the following in settings.yml;

**Translate_Diacritical_Marks** to **false**
**Anti_Spam.Similarity_Check.Ignore_Special_Characters** to **false**

**Comment by AndGK** [comment]
@kangarko It works, thanks, but in the explanation string it says it would've work if it was on true :D

**Comment by kangarko** [comment]
It depends on what you are looking for. The diacritical marks are mainly used for latin alphabet where we translate e.g. č ť ž to c t z to improve the filters, while it breaks on other alphabets.
