### ISSUE TITLE
PlayerMentionEvent question

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1000]
Could we get a PlayerMentionEvent, whereby, if a player is mentioned it triggers the event. Or can a way to run a command when a user is mentioned, be added?

If this is added there would need to be a way to get the player who mentioned a player, and a player who was mentioned.

**Comment by RogerPlaysMC** [comment]
You could just as easily listen to commands, and if the first part of the split string is /m or /msg, get the sender and the second argument would be the receiver.

**Comment by LogGits** [comment]
Nice one, however, I'm talking about when u type another users name in chat and it dings and changes colour of users name to yellow (aka the mention/soundnotify system)

**Comment by kangarko** [comment]
I will add this, thanks

**Comment by kangarko** [comment]
Pulled to roadmap
