### ISSUE TITLE
{group} for display name isn't working

### ISSUE THREAD

**Issue by EmanuelSimard** [kangarko/ChatControl-Pro#1002]
Works fine on all our servers, for some reason it isn't one this specific one. Are we missing a plugin to make it work or something so that it shows the display name of a group?

**Comment by EmanuelSimard** [comment]
{pl_group} works but not {group} which should work.. Works fine on other servers just not on our creative server...

**Comment by kangarko** [comment]
The {pl_group} variable is replaced in ChatControl directly. It requires the Vault plugin and a group in a permission plugin. Not sure about the group variable, it is not used.
