### ISSUE TITLE
Chat formatting priority

### ISSUE THREAD

**Issue by yooteri56** [kangarko/ChatControl-Pro#1003]
I'm having some issues with chat formatting: I have to give to my staff with '*' the permission "-chatcontrol.groups.vip"

    Staff:
      Message: "&6[STAFF] "
      Sender_Permission: "chatcontrol.groups.staff"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&6Staff"
    Vip: 
      Message: "&6[VIP] "
      Sender_Permission: "chatcontrol.groups.vip"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&6This player is VIP"
          - "&6Check out &e/web &6to obtain VIP"
    Player: 
      Message: "{player}:"                 
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&7Message issued: &b{timestamp}"
          - "&7Click to send a PM"
      Click_Event: 
        Action: SUGGEST_COMMAND
        Value: "/tell {player} "

I would suggest to add a priority for every format. Can you?

**Comment by kangarko** [comment]
What is the problem?

**Comment by LuisGVE** [comment]
@kangarko Its obviously, he want chat priority option for differente formats with conditions

**Comment by kangarko** [comment]
This can be achieved within permission plugin by giving negative permissions up the rank.
