### ISSUE TITLE
Rule match multiple lines

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1004]
When a rule is caught and the original message was written over multiple lines, like in a book the notification for staff is written in the chat. (I think it's a book, but the rule match don't say so:
Rule match (global) for ...)
The first line appears in gray like I have setup.
```
chatcontrol.notify.swear &8[&cCURSE {ruleID}&8] &c{player}&f: &7{message}
```
The second line and beyond are black. Idk why, this has been for as long as I can remember. But this is a bit difficult to see. Is it possible to have this corrected?

**Comment by kangarko** [comment]
Very odd, however what is even more strange than simply joining the lines still resulted in semi-blank message. I will consult this and return to it later.
