### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by En0tS** [kangarko/ChatControl-Pro#1006]
Please add ability to start/end conversation with /tell [player] like in UltimateChat.

**Comment by kangarko** [comment]
We already have this:

![a](https://i.imgur.com/8j5FXwi.png)

**Comment by kangarko** [comment]
Or type @kangarko Your message is here....

**Comment by En0tS** [comment]
I know, but it's not that, exactly /tell [player] without message to start/end conversation.

**Comment by En0tS** [comment]
@kangarko So?

**Comment by kangarko** [comment]
Thank you for suggesting, will look into it. I am actually releasing a totally new product not related to Spigot this year, but I am leaving it open when I get time to it it will get added, as it is not so hard to implement ;)

**Comment by En0tS** [comment]
Thanks!
