### ISSUE TITLE
Problem with rules.

### ISSUE THREAD

**Issue by En0tS** [kangarko/ChatControl-Pro#1007]
Rules with char "Ё" or "ё" don't works and when plugin catches some swear, this char got replaced by "Е" or "е". Examle:

message: ёЁё
output in chat: ёЁё

message: ёЁё хуй
output in chat еЕе ***

message: ёЁё хуёво
output in chat: ёЁё хуёво

rule:
#Ху(ец|и|й|йци|ю|я|ёво|ёк).
match ([Хх]+[Уу]+([Ее]+[Цц]+|[Ии]+|[Йй]+([Цц]+[Ии]+)?|[ю]+|[я]+|[Ёё]+[Вв]+[Оо]+|[Ёё]+[Кк]+))
handle as swear

**Comment by En0tS** [comment]
Update: char 'Й' and 'й' detected by rules, but get replaced by 'И' and 'и' when catched by rule.
message: Йй хуй
output in chat: Ии ***

rule:
#Ху(ец|и|й|йци|ю|я|ёво|ёк).
match ([ХхXx]+[^а-яА-Я]*[Ууy]+([^а-яА-Я]*[ЁёЕеEe]+[^а-яА-Я]*[Цц]+|[^а-яА-Я]*[ИиUu]+|[^а-яА-Я]*[Йй]+([^а-яА-Я]*[Цц]+[^а-яА-Я]*[ИиUu]+)?|[^а-яА-Я]*[ю]+|[^а-яА-Я]*[я]+|[^а-яА-Я]*[ЁёЕеEe]+[^а-яА-Я]*[ВвB]+[^а-яА-Я]*[ОоOo]+|[^а-яА-Я]*[ЁёЕеEe]+[^а-яА-Я]*[КкKk]+))
#before strip \s*
handle as swear

Also this chars are not replaced by rules that don't handle as swear:

rule:
match \s\1{1}
then replace

message: Йй                  Ёё    Йй
output in chat: Йй Ёё Йй

**Comment by kangarko** [comment]
Hey,

please set Anti_Spam.Similarity_Check.Ignore_Special_Characters to false and Translate_Diacritical_Marks to false in settings.yml, then, all special characters will be matched and not replaced.
