### ISSUE TITLE
Event rule question

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1009]
`#ignore event signs|book|item`
Is apparently improper usage. What is the correct way to block these ignore these?

**Comment by kangarko** [comment]
Sorry for the delay, what do you mean? What is the error in the console or something not working?

**Comment by LogGits** [comment]
Doesn't seem to work as intended, try this in `rules.txt` without permission `test.test`:
```yaml
# Replaces 'bag'
ignore event signs|book|item
match \b(b+(\W|\d|_)*a+(\W|\d|_)*g+(\W|\d|_)*)\w*
ignore perm test.test
then replace backpack
```

**Comment by kangarko** [comment]
Thanks, fixed.

**Comment by LogGits** [comment]
Thanks a tonne this is now working ❤️
