### ISSUE TITLE
Rule replaces characters in commands i don't want to

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#101]
So here's the default rule of yours for replacing characters from "aaaaaaaa" to "aa":
`# Restrict one character to max. two repeats
# example: aaaaaaaaaa to aa
# Commented out by default, might cause unwanted catches.
match (.)(?=\1\1+)
then replace`

I don't want this rule to work in commands, how do i do so?

**Comment by EvilOlaf** [comment]
Remove the rule from your rules.txt and add it to your chat.txt
Then reload the config.

**Comment by AndGK** [comment]
@EvilOlaf Thanks a lot :) Also do you know how to hide some of the rules I don't want to from console? Example:http://i.imgur.com/XiCe5S1.png

**Comment by EvilOlaf** [comment]
AFAIK you cannot hide individual rules from console.
However you can disable debug mode in your `settings.yml` to hide all those messages.

**Comment by AndGK** [comment]
Thanks a lot :)

**Comment by EvilOlaf** [comment]
You're welcome

**Comment by kangarko** [comment]
As per 7.0.0 you can use operator "dont verbose" to hide individual rules even if you have Verbose_Rules enabled in settings.yml
