### ISSUE TITLE
Discord messages wont be logged to console anymore

### ISSUE THREAD

**Issue by momoservertw** [kangarko/ChatControl-Pro#1012]
Sending message to server has no problem.
But it will not receive any message in the console.

Console_Filter.Enabled: false
Console_Filter.Filter_System_Out: false
Formatter: HIGHEST
![image](https://user-images.githubusercontent.com/38014059/49690023-093c1000-fb65-11e8-86e6-d371d53c069b.png)

Spigot version: git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) (1.12.2, latest)
CHC version: 7.10.6 (latest)
CHC channel: global (bungee: true)
DiscordSRV: 1.16.4 (latest)

**Comment by kangarko** [comment]
Apology for the delay, we are on it however got delayed due to holidays, will return to you in few days.

**Comment by kangarko** [comment]
Continued on https://github.com/kangarko/ChatControl-Pro/issues/1010
