### ISSUE TITLE
ID Unset

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1015]
For every rule without an ID assigned to it, ID UNSET appears on the console.
That forces everyone to either use ID's to structure it or accepts this useless spam. But I have quite a few rules are just for auto correction purposes. So sometimes the ID is pretty useless imho.

Suggestion: Only show ID "IDSET" if an ID is set and leave ID UNSET behind.

**Comment by kangarko** [comment]
That was literally the simplest updated I've done in a long time, sure!
