### ISSUE TITLE
Player's user prefixes showing up next to group prefix as "null"

### ISSUE THREAD

**Issue by NerdyBirder** [kangarko/ChatControl-Pro#1017]
We recently set up ChatControl in a new server and can't seem to get rid of this "null" showing up from each player's user prefix that we don't want to set up. We are running version 7.10.6 and are using BungeePerms as our permissions plugin.

https://pastebin.com/1gUnVfNE (formatting.yml)
https://pastebin.com/TA8kfLFf (settings.yml)
https://pastebin.com/5QNqeBcU (channels.yml)

https://pasteboard.co/HQWK95M.png picture of chat

**Comment by kangarko** [comment]
Closing due to no answer, if you still have issues please comment below.

**Comment by NerdyBirder** [comment]
sorry for not responding early. I should have closed this issue because it is based on Bungeeperms and not chatcontrol. Thank you for responding and trying to help even though i was no answering back.
