### ISSUE TITLE
Loooong text minify?

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1021]
Is there a feature in ChatControl Pro where I can turn text like `Teeeeeeeeest` into `Teest` (configurable max duplicate character length) automatically in a sentence?

**Comment by kangarko** [comment]
Yes :)

Just see the default chat.txt file:

![a](https://i.imgur.com/PijVdfr.png)

**Comment by LogGits** [comment]
Thanks, i found out `(.)\1{3}` works abit better. With the default one, it has a falsepositive with the word `wow`.
