### ISSUE TITLE
ChatControl 7.10.9 encountered a lPt1

### ISSUE THREAD

**Issue by glorying16** [kangarko/ChatControl-Pro#1022]
What in the world did I do? lol

```
------------------------------------[ 16.12.2018 00:06:02 ]-----------------------------------
ChatControl 7.10.9 encountered a lPt1
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_191
Plugins: LuckPerms v4.3.29, WorldEdit v7.0.0-beta-04;17f52cb, LogBlock v1.13.2-SNAPSHOT (build #385), PlaceholderAPI v2.9.2, Winter v1.5.6, WorldBorder v1.9.0, Votifier v2.4.1, WorldGuard v7.0.0-beta01;01dfebe, ProtocolLib v4.4.0, VotingPlugin v5.17.1, CommandHook v1.0.1, ImageOnMap v3.1, DragonEggRespawn v1.0, AntiCommandSuggestions v1.1-SNAPSHOT, Vault v1.7.1-b91, ServerListPlus v3.5.0-SNAPSHOT, GriefPrevention v16.11.5, Essentials v2.15.0.57, BiomeFinder v1.2.9, DiscordSRV v1.16.4, BetterRTP v2.7.6, EnjinMinecraftPlugin v3.5.3, PremiumVanish v2.4.1, ChatControl v7.10.9, CMI v8.2.4.0
----------------------------------------------------------------------------------------------

More Information: 
Warn set named 'null' does not exist. Available: me.kangarko.chatcontrol.final. .bn$transient@2ee9c5e1
lPt1 Report / Warn set named 'null' does not exist. Available: me.kangarko.chatcontrol.final. .bn$transient@2ee9c5e1
	 at me.kangarko.chatcontrol.final. .cOM6.const(SourceFile:22)
	 at me.kangarko.chatcontrol.final. .bn.const(SourceFile:242)
	 at me.kangarko.chatcontrol.final. .bn.const(SourceFile:225)
	 at me.kangarko.chatcontrol.final. .aY.const(SourceFile:135)
	 at me.kangarko.chatcontrol.final. .aY.onPlayerCommand(SourceFile:40)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
----------------------------------------------------------------------------------------------
```

**Comment by glorying16** [comment]
It does repeat this error in console...
`20.12 06:23:30 [Server] INFO [ChatControl] ChatControl 7.10.9 encountered a lPt1! Please check your error.log and report this issue with the information in that file.
20.12 06:23:30 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to ChatControl v7.10.9
20.12 06:23:30 [Server] INFO org.bukkit.event.EventException: null
20.12 06:23:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1633) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
20.12 06:23:30 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
20.12 06:23:30 [Server] INFO Caused by: me.kangarko.chatcontrol.final. .lPt1: Report / Warn set named 'null' does not exist. Available: me.kangarko.chatcontrol.final. .bn$transient@24654ddf
20.12 06:23:30 [Server] INFO at me.kangarko.chatcontrol.final. .cOM6.const(SourceFile:22) ~[ChatControl-7.10.9.jar:?]
20.12 06:23:30 [Server] INFO at me.kangarko.chatcontrol.final. .bn.const(SourceFile:242) ~[ChatControl-7.10.9.jar:?]
20.12 06:23:30 [Server] INFO at me.kangarko.chatcontrol.final. .bn.const(SourceFile:225) ~[ChatControl-7.10.9.jar:?]
20.12 06:23:30 [Server] INFO at me.kangarko.chatcontrol.final. .aY.const(SourceFile:135) ~[ChatControl-7.10.9.jar:?]
20.12 06:23:30 [Server] INFO at me.kangarko.chatcontrol.final. .aY.onPlayerCommand(SourceFile:40) ~[ChatControl-7.10.9.jar:?]
20.12 06:23:30 [Server] INFO at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source) ~[?:?]
20.12 06:23:30 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
20.12 06:23:30 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
20.12 06:23:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
20.12 06:23:30 [Server] INFO ... 16 more`

**Comment by kangarko** [comment]
Find Ignore_Chatdisplay option in handlers.yml and remove it completely if it is empty, the same for "ignore chatdisplay in all files in rules/ folder.

**Comment by glorying16** [comment]
I dont have Ignore_Chatdisplay. 

```
# !-----------------------------------------------------------------------------------------!
#                             Welcome to Handlers Configuration
#
#   A handler stores multiple instruction of what should happend when
#   the message is caught by a rule.
# 
#   This reduces repetitive code and makes things more human and future proof.
#
#   For configuration, see:
#   - https://github.com/kangarko/ChatControl-Pro/wiki/Handlers
#
#   Remember, you can remove or edit all handlers below, and create your own ones!
#
# !-----------------------------------------------------------------------------------------!

# -----------------------------------------------------------------------------------------
# The default advertisement handler.
# ----------------------------------------------------------------------------------------- 
advertisement:
  #
  # Ignore players with a proper permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.ad"
  #
  # Do not filter ads in the following commands:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  #
  # Warn the player.
  #
  Player_Warn_Message: "&7Please do not advertise other websites or IP adresses."
  #
  # Notice online staff members.
  #
  Staff_Alert: "chatcontrol.notify.ad Ad_Info"
  #
  # Deny the message entirely.
  #
  Block_Message: true
  #
  # Log the violation so you can check it if you are offline.
  #
  Write_To_File: logs/advertisements.log

# -----------------------------------------------------------------------------------------
# The default swear-words handler.
# ----------------------------------------------------------------------------------------- 
swear:
  #
  # Ignore players with permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.swear"
  #
  # Do not filter commands below:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  #
  # Warn the player.
  #
  Player_Warn_Message: "&cSwearing is prohibited on this server."
  #
  # Notice online staff.
  #
  Staff_Alert: "chatcontrol.notify.swear &8[&7Swear/ID {ruleID}&8] &7{player}: &f{message}"
  #
  # Replace the swear word with a censor.
  # If you only specify @prolong, the replacement will be automatically stretched to match word's length
  # assuming it only contains one letter, in this example a star.
  #
  #Replace_Word: "@prolong *"
  #
  # Log the violation so you can check it if you are offline.
  #
  Write_To_File: logs/swears.log

racism:
  #
  # Ignore players with permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.racism"
  #
  # Do not filter commands below:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  #
  # Warn the player.
  #
  Player_Warn_Message: "&cUse of this word will get you banned. This is your ONLY warning."
  #
  # Notice online staff.
  #
  Staff_Alert: "chatcontrol.notify.racism &8[&7Swear/ID {ruleID}&8] &7{player}: &f{message}"
  #
  Block_Message: true
  Warn_Points: racism 15
  #
  # Log the violation so you can check it if you are offline.
  #
  Write_To_File: logs/racism.log
```

**Comment by kangarko** [comment]
I have corrected the message in the next version.

Most likely your warning set in "Warn_Points: racism 15", named racism, no longer exist. Remove that line completely.
