### ISSUE TITLE
Death message dev question

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1023]
I was going to make my own simple deathmessage limiter because people spam chat with death messages unwillingly, however, I started having issues. 

Is ChatControl using `event.setDeathMessage(message);` or just sending all players a message? Is there a ChatControl DeathMessageEvent that is cancellable/settable?  I'm having a tough time disabling this message, even using monitor and ignoring cancelled event (i know I'm not supposed to use monitor for this purpose, it just resolves another issue I'm having).

What is the best way of cancelling/changing this message?

**Comment by kangarko** [comment]
Thanks, added DeathMessageEvent.

**Comment by LogGits** [comment]
@kangarko Thanks for this addition. Could you also add a way to get `event.getDeathMessage()` and `event.getDeathMessage()`. Many thanks for the addition 👍

**Comment by kangarko** [comment]
Hey, I expanded the API ;)

Sorry I don't know why it's not cancelled, we're also cancelling it the official way (maybe set the message to "" ?):

![a](https://i.imgur.com/KJZyHMi.png)

**Comment by LogGits** [comment]
I tried this to no avail

**Comment by kangarko** [comment]
Alright, I understand that it is not working for you - will take a look.

**Comment by jascotty2** [comment]
I threw together a test plugin to test the API event, and cancelling the event does stop the death message. Is it not working in a specific version?

Test code:
`
package ccdeathtest;

import me.kangarko.chatcontrol.api.event.DeathMessageEvent;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.PlayerDeathEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class CCDeathTest extends JavaPlugin implements Listener {

	
	@Override
	public void onEnable() {
		getServer().getPluginManager().registerEvents(this, this);
	}
	
	@EventHandler
	public void onCCDeath(DeathMessageEvent event) {
		event.setCancelled(true);
		System.out.println("Recieved DeathMessageEvent " + event.getMessage());
	}
	
	@EventHandler(priority=EventPriority.MONITOR)
	public void onDeath(PlayerDeathEvent event) {
		System.out.println("Recieved PlayerDeathEvent " + event.getDeathMessage());
	}
}

`

**Comment by kangarko** [comment]
Maybe it was the "priority" issue in your plugin? Try setting it up to MONITOR as Jacob showed.

Closing, comment below if issues continue.

**Comment by LogGits** [comment]
Unfortunately the Issue persists. I tried using MONITOR before highest and that didnt work. I tested the code that you provided and it works as you intended. However, when i try to incorporate it into my own plugin I get the following issue:
(`Methods.addDelay` adds the player uuid to a list of uuids then removes them after a certain amount of time)
```java
    @EventHandler(priority = EventPriority.MONITOR)
    public void onDeathCHC(DeathMessageEvent event) {
        Player p = event.getPlayer();
        if (deathCounter.contains(p.getUniqueId())) {
            event.setCancelled(true);
            Bukkit.broadcastMessage(
                    p.getName() + " is in death counter + CANCELLED:" + event.isCancelled());
        } else {
            Bukkit.broadcastMessage(
                    p.getName() + " is NOT in death counter + CANCELLED:" + event.isCancelled());
            Methods.addDelay(Variables.deathCounter, p, 600);
        }
    }
```
if i die via lava this is the Outcome:
https://gyazo.com/565082e4dac1ebdbd3f14477288ccf92

Any thoughts?

**Comment by kangarko** [comment]
@LogGits I moved a line of code, test using the next version coming up tonight please

**Comment by LogGits** [comment]
On the latest version 7.11.8 it still does this (using the exact same code):
https://gyazo.com/d0ab2438ea27190b66842fcd28863f2d

**Comment by jascotty2** [comment]
@LogGits your DeathMessageEvent listener should be listening at NORMAL or similar - In my example, I'm listening to PlayerDeathEvent at MONITOR to print out the result after all plugins have had a chance to edit the event.

It is possible that you have something else printing out the vanilla death messages, but you do say that the test code provided works, so I can only assume that it is a programming error in your plugin.

**Comment by LogGits** [comment]
@kangarko Could you provide me with the code that you are now using to do this (after the update that was meant to resolve this). I just did a few tests and it seems to be weird. Sometimes it cancels the event other times it sends death messages when it shouldn't.

I even tried with ur code @jascotty2 and it isnt working now. This seems to be unstable. Is something being ran async?

**Comment by kangarko** [comment]
What other plugins are running on your server?

**Comment by LogGits** [comment]
I have made progress. I was testing this with a player and what happens is the message doesn't get sent to the players but it gets sent to me. This also happens to them when they try to test the death messages. It seems that the player who dies gets the death message but everyone else doesn't. Any idea what could cause this?

**Comment by kangarko** [comment]
@LogGits sorry for forgetting to get back to you, I am closing this due to regular maintenance but if you have any issues or questions what so ever please post below (I will get notified). 

If you do please make sure to be clear on what is your very recent issue so we solve it quickly ;)
