### ISSUE TITLE
Add Channel Support for Heroes Party

### ISSUE THREAD

**Issue by HansscMe** [kangarko/ChatControl-Pro#1026]
Hello,

I have a small request about this plugin.
Could you add channel party support for Heroes Party.
Just let the messages only to be seen by the players in the same party.
My server is running Heroes & ChatControl and could not find any better solution for party chat.
Though Heroes has a party chat command '/p msg' , it is really unconvenient for us.

Spigot page:
https://www.spigotmc.org/resources/⚔-heroes-the-most-powerful-class-race-and-skill-rpg-plugin.24734/

Thanks in advance!

**Comment by kangarko** [comment]
Thanks, I put this on hold as a future suggestion
