### ISSUE TITLE
[request] Channel Slowmode/Chat Cooldown

### ISSUE THREAD

**Issue by nurdism** [kangarko/ChatControl-Pro#1029]
It would be amazing to have a way to configure a channel to have a slow mode. For something like trade chat. Just a Cooldown option, so you can only send a message in the channel every `x` seconds.

**Comment by kangarko** [comment]
Hey, thank you for your suggestion, but right now we are very tight on our schedule and delaying bug fixes so definitely new features cannot be taken at the moment, sorry about that.
