### ISSUE TITLE
Default chat (No Bungee)

### ISSUE THREAD

**Issue by Kotemas** [kangarko/ChatControl-Pro#1030]
How make:

Why my default chat is Bungee (chc global) (on join)
And need write (chc global switch) to back default chat

I'm from Russia , sorry
![image](https://user-images.githubusercontent.com/41546844/50471769-b37eb900-09e8-11e9-9e32-716a12b6d43b.png)

After write (chc global switch)
![image](https://user-images.githubusercontent.com/41546844/50471787-ca251000-09e8-11e9-9f91-d5d33b088dc0.png)

How to disable this?

**Comment by kangarko** [comment]
Hey, set Bungee_Chat.Enabled_By_Default to false in settings.yml
