### ISSUE TITLE
Redirecting !text into /chc global text without additional rules

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/ChatControl-Pro#1035]
I use rules to redirect all !text to /chc global text as @kangarko said. 

Here is that rule:
match (^!+\s?)(.+)
before strip (&[0-9a-fk-or])
before replace ((^!!+)|(^!+ +)) with !
ignore string (^[!\s]+$)
then deny
then console mycmd-runas player {player} /chc global $2

Today I switched from ChatControl-7.9.31 to ChatControl-7.11.3 and now all swears are shown in bungee chat. The plugin is reacting on swears but they are not be replaced by Replace_Word from handlers file.

What can I do to fix it? Maybe it will be a good addition just to allow server administrators to redirect all 
!text into /chc global chat in a simple way?

**Comment by jascotty2** [comment]
I'm not sure what mycmd-runas is for.. have you tried using 
`then command chc global $2`

You may also be running into a permission node, `chatcontrol.bypass.rules.global` - if a player has this permission node, then the rules are not run on that player's chat

**Comment by ArtNRG** [comment]
This issue is about adding new feature to redirect chat without hacky ways. I used this system ok about 6 months waiting for this feature and now I have to write about it again. The permissions are ok, mycmd-runas is the "sudo" analog.

**Comment by kangarko** [comment]
We are not planning to include this right now, the !messages are reserved for other option.
