### ISSUE TITLE
Basic parameters {BALANCE} {ONLINE} and {DATE} for /motd

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1037]
I know you support placeholderAPI, but these should be some very baisc built in parameters to be used in the /motd.
Take a look at the basic built in parameters for Essentails /motd 
http://wiki.mc-ess.net/wiki/Help_Files#Manual_Files
All of these should be included off the bat, so when the user logs in they can see a quick overview of their Mail count, Money, the date, how many people are online.
You support {nick} for essentials already, please support balance too.

**Comment by FrozenBeard** [comment]
And how do we remove the sound from /motd? its set as   Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F, but if I remove it, it stays.

**Comment by kangarko** [comment]
Hey, please just install PlaceholderAPI for advanced and more placeholders.

To remove the sound, set it to "none".
