### ISSUE TITLE
DiscordSRV Discord > Minecraft blocked.

### ISSUE THREAD

**Issue by VergilPrime** [kangarko/ChatControl-Pro#1039]
Somewhere around December 10 I updated ChatControlPro and Discord messages stopped being visible in game from the appropriate channels in Discord.

Here's my debug paste from DiscordSRV: https://debug.scarsz.me/60cf60c5-3ea2-4327-ac1d-af23b473894f

Also chat messages no longer make it to console either.

**Comment by kangarko** [comment]
Thank you for such a detailed report. Just one thing - please set Debug to "[discord]" in your settings.yml of ChatControl and just post me the new console log when that happens. Thank you.

**Comment by kangarko** [comment]
As the log specifies, set this option to "staff-chat":

![a](https://i.imgur.com/z2nqyxL.png)

**Comment by VergilPrime** [comment]
Those were already set.
