### ISSUE TITLE
plugin breaks after 7.0.7

### ISSUE THREAD

**Issue by Chris4418** [kangarko/ChatControl-Pro#104]
i noticed that when i try to update the plugin after 7.0.7, the plugin throws errors. I have not changed anything within the configuration at all. but as soon as i rollback to 7.0.7 the plugin works fine again. As i had mentioned before about the command.txt file being the cause. it isn't has i have noticed the YAML parser shows errors on a few others after updating the plugin (which i stated not changing after the update happened). I have also noticed that, when i update to 7.0.11, it completely altered how my MOTD looked.  I know that you said that the config uses its own language, but i dont really understand why updating the plugin can cause it to fail like it has been.

**Comment by EvilOlaf** [comment]
It is hard to know what your issues are without having error logs, console output, configuration files, server version etc. as well.

**Comment by Chris4418** [comment]
i will look through my console logs and see if i cant find anything on
there. if i see anything, i will reply back with a pastebin link of my
console logs

**Comment by Chris4418** [comment]
i found the logs. i have copied the section out for Chat Control. i checked through the whole log and this is the only part that has ChatControl. 

http://pastebin.com/f5c48Tbh

**Comment by EvilOlaf** [comment]
Maybe there were some breaking changes since 7.0.7? Check changelogs on on spigotmc.

`Seems like your config is not a valid YAML.`
Validate your syntax anyways,

**Comment by kangarko** [comment]
Like Olaf said.

Comment below if issues persist.

**Comment by Chris4418** [comment]
The issue is still persisting. Even after completely uninstalling, deleting all files and letting it regenerate all the files again. I did make a mistake in the 'messages.yml', but i deleted that and let the plugin regenerate that file. checked all yml files and no errors, but the plugin is still showing 'red' in game.

**Comment by kangarko** [comment]
If it's showing red, there's some error in the console. If it's the same error, check your syntax using http://yaml-online-parser.appspot.com/ or post the affected file here. If it's a different error, post the error to pastebin

**Comment by Chris4418** [comment]
showing syntax error for chat.txt, i removed the file and let the plugin regenerate it. still showing a syntax error. it does not specify the path of the error though. 

http://pastebin.com/zn69xDzk <-- Error log from Console

http://pastebin.com/z6Cfwe9a <-- Chat.txt

**Comment by kangarko** [comment]
You can't use yaml syntax checker on rules files, as they use a different language. It can only be used against .yml files. There's nothing wrong with that file you posted me, it seems rather like an encoding error. Try using Notepad++ and saving the file using UTF-8 (without BOM) encoding.
