### ISSUE TITLE
Permission for rule notification

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1040]
According to the file it should be something like "chatcontrol.notify.rulesalert", but this does not work as intended I guess unless you set this for every single rule to "then notify chatcontrol.notify.rulesalert &8[&7Swastika&8] &7{player}: &f{message}"... however it shows for me by default for EVERY rule that is matched so I clearly have a permission that I can not isolate and assign to my staff.  What is that permission?  chatcontrol.notify.swearalert maybe?  or something like that?

**Comment by kangarko** [comment]
Hey, by default most rules are handled by a handler in handlers.yml file, see Wikipedia for more information. There you will find the permission under Staff_Alert options, typically chatcontrol.notify.ad and chatcontrol.notify.swear

**Comment by mrcoffee1026** [comment]
yeah that was what i was looking for, perfect thanks!
