### ISSUE TITLE
Commands Cooldown

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#1042]
Hello,

When i have a command cooldown message, i't won't block the command, for example, if it will say:
wait another x seconds to use, but it wont block
improvment
Thanks, your plugin is the best

**Comment by kangarko** [comment]
What other plugin are you using that modifies the chat? It seems to be interfering with ChatControl. Try this article: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
