### ISSUE TITLE
Suggestion: make a discord please

### ISSUE THREAD

**Issue by Dracathio** [kangarko/ChatControl-Pro#1043]
I'm mean in all honesty github is nice man, but discord is better.

It would help a lot of people to get help quicker for minor issues such as asking if your plugin works with towny decently or how well it works with cmi and things like that.  GitHub isn't a great place for info like that, it's also a very slow process, specially with how you are towards those asking for a simple answer that can be easily given through discord by another user of your plugin.

**Comment by DanielProGames** [comment]
Hey @Dracathio, you're right in the fact that Discord is better than GitHub for faster support, however, have you read ChatControl-Pro's plugin description & wikipedia? That will help you and a lot of people too, and will save us & kangarko's time.

**Comment by kangarko** [comment]
Discord is distractive and I cannot get anything done answering 15 questions a day. Ultimately, I postpone them until the evening, making GitHub reply time the same as Discord, so no.
