### ISSUE TITLE
Global Chat clear on bungee server

### ISSUE THREAD

**Issue by NerdyBirder** [kangarko/ChatControl-Pro#1045]
We are currently using ChatControl and enjoy the plugin but are having problems because the /chc clear does not clear chat across our bungee network, only in the server where the command was executed.

Is there a way to make the chat clear global? We have not been able to find a working plugin to do this task and have had to use a command block that spams the /chc announce feature to effectively clear the chat if needed but this is not a permanent solution.

We are running version 7.10.6 of ChatControl Pro.

**Comment by DanielProGames** [comment]
Currently, LiteBans can do that task. 
I personally use LiteBans for clearing the chat across servers, and ChatControl Pro for per-server chat clearing.

**Comment by kangarko** [comment]
At present we are not planning to expand the clear and mute feature over bungee, but such feature are already on our todo list. Thank you.
