### ISSUE TITLE
Chat "Feelings/Actions" Idea

### ISSUE THREAD

**Issue by farisjaclyn** [kangarko/ChatControl-Pro#1049]
What if Chat Controls added special action messages players could send to each other in the form of actions/feelings written in the chat? 

Example:
Command - /hug username
Chat - username sent username a hug! <3 (when the msg shows the user hears a noise)

This reminds me of the custom death messages. My players love them.

Apparently there is a similar plugin already made called ChatFeelings.

**Comment by kangarko** [comment]
Hey,

it's impossible to satisfy individual needs like that so we added a system allowing you to create own simple commands in a simple way (or maybe not that simple but understandable after a while):

Add this to commands.txt:

match ^/(hug) (.*)
then console say &a{player} &6is hugging &a$2&6!
then deny

This will match /hug <anything...> and issue a "say" command with the $2 that takes the second parenthesis (.*). This is called "regex group" (you can just Google that). Very useful and now you can create own commands like that.
