### ISSUE TITLE
Ignored_In_Commands is case sensitive

### ISSUE THREAD

**Issue by sigmaroot** [kangarko/ChatControl-Pro#105]
Hello kangarko!

A handler is not ignored via _Ignored_In_Commands_ if the entered command is not exact the same as the configured. It is case sensitive.

Is it possible to change this?

Thanks!

**Comment by kangarko** [comment]
It is case sensitive. I can modify it to be case insensitive by default.

**Comment by sigmaroot** [comment]
Yes, that would be nice. Most plugins and spigot handle commands case insensitive.

Thanks!

**Comment by kangarko** [comment]
Implemented in to the next release.
