### ISSUE TITLE
[Request] Newcomer Function

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1050]
I would like Newcomers to have double warning points. Is it possible to have a multiplier for warning points given to newly players?

Something like:
```
Newcomer: 
  
  # Multiplier for warning points to apply for newcomers.
  # Set to 1.0 equals to normal players
  Multiplier: 2.0
```
Reason:
New players always join and curse a lot more than people which are used to the chat filter. So I want loyal players to punish less hard for making "accidental mistakes".

**Comment by kangarko** [comment]
Leaving open for future implementation - will rather add a custom formula where you can simply append " * 2" at the end to multiply.

**Comment by kangarko** [comment]
Implemented
