### ISSUE TITLE
ASkyBlock

### ISSUE THREAD

**Issue by AddictedFader8** [kangarko/ChatControl-Pro#1051]
I was wondering if it is possible to add ASkyBlock variables to the formatting.yml 

ISLANDLEVEL: 
      Message: "&8[&7{ISLAND_LEVEL}&8]&r"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&6This is the player's island level"

I want to add that to the chat prefix and allow different members to get different colors and make it look something like this: https://gyazo.com/7b1271f2871bbb559e7e08c2dc71d191

**Comment by kangarko** [comment]
Please install PlaceholderAPI and use {} variables from there

**Comment by AddictedFader8** [comment]
I have papi installed and using the variables from papi, in the {} format not %%

Chat:
    Island:
      Message: '&8[&7{ASKYBLOCK_LEVEL}&8]&r '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&6This is the player''s island level'

i have even tried to use it in lowercase, yet still doesnt seem to work

**Comment by kangarko** [comment]
@AddictedFader8 I assume you fixed that by updating plugins, comment below if still having any issues
