### ISSUE TITLE
DiscordSRV Discord > Minecraft blocked.

### ISSUE THREAD

**Issue by VergilPrime** [kangarko/ChatControl-Pro#1052]
https://github.com/kangarko/ChatControl-Pro/issues/1039 <<<
This is still an issue.

https://paste.thezomg.com/74542/58245615/
As you can see in this paste both of my discord_channels were already configured, as I had this working prior to an update in the plugin which broke it.

**Comment by kangarko** [comment]
Thanks will take a look. Don't need to open a new ticket, I read all the comments and re-open old tickets if they become valid.

**Comment by kangarko** [comment]
Sorry for the big delay this time. Next version should introduce new option solving this.
