### ISSUE TITLE
[Request] A command to mute bungee messages.

### ISSUE THREAD

**Issue by PlayDatblockCom** [kangarko/ChatControl-Pro#1053]
A command, "/chc g mute", that mutes/unmutes bungee messages coming from other servers for the player that executes the command. Bungee messages sent from the same server would still be shown.

I would love to have this feature and would be glad to pay to get this feature added/prioritized. I am not interested in using the channels feature as it can't replicate this exactly.

**Comment by kangarko** [comment]
Thank you, I believe something like this is already put on the roadmap, however due to our current workload other features and fixes have been prioritized.
