### ISSUE TITLE
Russian text causes error

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1057]
https://pastebin.com/a86SXcrZ
Filter is bypassed and text is placed in chat.

ChatControl 7.11.6

**Comment by x1p** [comment]
```
match [^\u0000-\u007F]+
ignore string ☺|☹|㋡|★|❤|€
id UNICODE
then replace
```
Settings:
`Translate_Diacritical_Marks: true`

**Comment by kangarko** [comment]
Thanks, it should be fixed in the next version.

**Comment by kangarko** [comment]
Interestingly it was related to: lower-casing second character but there is none.

**Comment by x1p** [comment]
:-)
:+1:
