### ISSUE TITLE
Still skyblock levels are not showing

### ISSUE THREAD

**Issue by AddictedFader8** [kangarko/ChatControl-Pro#1058]
You had closed my last ticket before it was even solved, i had placeholderapi installed with the skyblock extention installed:
https://gyazo.com/e3d1409e84208ddbd049af6515bea088
https://gyazo.com/b1fc9676966d162faf7899026a331f12
https://gyazo.com/e941bb29a2f0529af10b1dfc28645f0b
https://gyazo.com/3636128157b1db9f9dcaede1ef067b81

Here is my chat format:
https://gyazo.com/4eb0d217fd468668f4a0f33b7f43dc78

Im not sure if i have to add a java script under /plugins/ChatControl/variables/javascript

but if so, how would i go about that

**Comment by kangarko** [comment]
You can comment below a closed ticket, so I will get back to you.

Anyways, as per https://www.spigotmc.org/threads/javascript-askyblock-chatcontrol.356114, this is now solved.
