### ISSUE TITLE
Signs notify 4 times

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1059]
When a swear is places on a sign and handled by handlers.yml, it shows notification 1 time. Sign brakes. Story ends.
When a word is placed on a sign with just a notification (and no punishment) the notification is given 4 times.

Example rules.txt
```
match \bip\b
then notify chatcontrol.notify.ad &8[&cAdvertisement?&8] &c{player}&f: &7{message}
```
It's matched 4 times on the console exactly the same.
When the same is being said in the chat, only 1 match occurs and gets notified.

Chc 7.11.7

**Comment by kangarko** [comment]
This is to increase our match rate, we check it from 1st line to last and up, also with new lines and without them:

![a](https://i.imgur.com/CdLCbYS.png)

If you have any specific idea to workaround this in mind, you can share it below ;)
