### ISSUE TITLE
Sponge version

### ISSUE THREAD

**Issue by Yann151924** [kangarko/ChatControl-Pro#106]
Do you have plan for port chatcontrol to sponge, i'm very interested for my new upcoming server in 1.10 ?
I have already chatcontrol on 1.7 server and i want to use with sponge too.

**Comment by kangarko** [comment]
ChatControl is compatible with 1.10

There are no plans for porting it to anywhere currently.

**Comment by Yann151924** [comment]
I understand but for the modded server in 1.10 there is no bukkit only sponge :(

**Comment by feardevilz** [comment]
It's definitely disappointing that some dev's don't have resources to add in sponge support - even the expensive paid ones like this one. I just end up looking for another plugin on sponge that does both. I haven't checked on chat related functions but i'm sure one is there that can work on bungee and spigot too.

**Comment by dryter97** [comment]
i mean just look at bungeechat long has i remember it was the number one ages ago and still fine for what you want to do... maybe using a regex patching addon or some modification cause its open source would make it better

**Comment by StormyIceLeopard** [comment]
So, there are no plans to add support for Sponge?
This is the best chat filter there is.

**Comment by kangarko** [comment]
I am a single-man developer for 5 plugins right now, I don't have the resources to do this right now.
