### ISSUE TITLE
incompatibility with showitem

### ISSUE THREAD

**Issue by Domo123POP** [kangarko/ChatControl-Pro#1062]
howitem doesn't work in chat when chat is printed in chatcontrol channel. Instead of showing item in json format, it shows some hash number like $showitem-123456

reproduction

1. have chatcontrol and set up some channel
2. have showitem installed
3. try to project item with showitem by typing %item% ( by default )

Adjusting Listener_Priority.Formatter to LOWEST, LOW, HIGH and HIGHEST.
but all didn't work.

**Comment by kangarko** [comment]
Does it work without ChatControl? That has problem may also come from ShowItem itself.
I am afraid I can't help, some plugins are programmed in such a way that it makes ChatControl impossible to co-operate.

**Comment by Domo123POP** [comment]
ShowItem did work, the same is true for installing ChatControl Pro.
But, formatting: if "true"
ShowItem will didn't work

**Comment by kangarko** [comment]
I am sorry this appears to be an incompatibility with that plugin
