### ISSUE TITLE
Replace Essentails help files, /info, custom messages, rules etc.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1063]
At present I serve all my custom help pages, information, pre-made books etc through Essentails:
http://wiki.mc-ess.net/wiki/Help_Files
That page covers it all, I mostly use the custom.txt and create commands to the pages through bukkits commands.yml, this works, but its dated.

You have everything already made to re-implement all of this, formatting for clicking and hover over events, no limit to 9 lines to display information. 

I have stuff scattered all around in /info commands, in /customcommands and then I have a separate /help which is the auto generated one based on permissions.

You could make such an amazing new version of all help files & creating custom information using the formatting system in ChatControl pro.

I would want everything under one command, but also have the dynamically generated /help too.

So being able to replace Essentials custom.txt with your Chat system where we can format it too.

from a user perspective the best way to do this would be to create a custom command say /help that redirects to chatcontrols custom index page.

This is how I would format mine:
/help - Shows your own formatted index message, so you could have your own commands listed in here and mybe some intro text, that people could click.

/help searchterm, would search for custom pages/tags for custom pages first with that name, then fall back to auto searching for permissions like essentails does

/help commands shows all commands like essentails /help currently does, so this is all automated.

**Comment by FrozenBeard** [comment]
Better idea:
Taking that formatting from the configs and instead of displaying that information in the chat, display it in a book when the command is run. Then the user can focus on the book without chat getting pushed when people talk.

**Comment by kangarko** [comment]
Thank you for your suggestion. At present all of our plugins' road-maps are overcrowded so I'll have to prioritize other issues. It honestly seems really neat so I don't want to let it deprecate here for many months like many already suggested features. 

Good news is, I will be expanding my staff team this year when I have more resources after I finish some real-life projects.

**Comment by kangarko** [comment]
Pulled to roadmap

Still dont have a team, until MineAcademy kicks gear and I invest into a dev from money earned there it will be on hold

**Comment by FrozenBeard** [comment]
+1 suggestion here, Opening up this information into a live book without giving the person a book, just opens the book interface they can read through help files.

**Comment by kangarko** [comment]
Thanks!
