### ISSUE TITLE
Chat filters still apply when player is muted [FIX]

### ISSUE THREAD

**Issue by oflords** [kangarko/ChatControl-Pro#1064]
According to the LiteBans API, it is possible to check if a player is muted. Using this you could check for the mute and then stop the chat filter working.

`import litebans.api.Database;

UUID uuid = UUID.fromString("d7b3493a-69cc-3a00-8bc8-366dac6da036");
String ip = "127.0.0.1";

boolean banned = Database.get().isPlayerBanned(uuid, ip);
boolean muted = Database.get().isPlayerMuted(uuid, ip);`

Adding this would help so much to avoid unnecessary checks with the plugin and annoying alerts for staff that see the results of the chat filter.

Here is the full documentation: https://gitlab.com/ruany/LiteBansAPI/wikis/home

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities#banmanager--litebans
