### ISSUE TITLE
ChatControl back to 1.8

### ISSUE THREAD

**Issue by Laurent-Sonny** [kangarko/ChatControl-Pro#1067]
Hello Kangarko,
I am so happy, that you made this plugin and it is very awesome. My problem is now: I have a 1.8-1.13 BungeeCord-server. So, I want to use ChatControl on every single server. The lobby and the minigames servers are still on 1.8 and the survival server is on 1.13.1. I tested every chat three times on every server:
1. 6.8.0 on all 1.8 servers, 7.11.3 on the 1.13 server
2. All servers with 6.8.0
3. All servers with 7.11.3
The chats are still only working on every servers correctly when I use the first versions list, so the old versions on 1.8 and the newest version on 1.13.
You wrote, we should not mix the versions while using BungeeControlBridge. But the BCB does not work with the original chat - just only when I put the server on the "chat relay" servers list. But the outputting are horrible, because it is the standardchat.
So, can you bring out a version of ChatControl, who is working on 1.8 to newest (minimum 1.13.1) or helping me for fixing my problem?

**Comment by kangarko** [comment]
No support is given to older releases than the latest, that is 7.11.8. That release works on 1.8.9 as well.
