### ISSUE TITLE
Suggestion (i guess this is where i put this)

### ISSUE THREAD

**Issue by BamaJoe411** [kangarko/ChatControl-Pro#107]
Add the functionality to the '/join <channel>' command to automatically remove the player from their current channel instead of the player to have to issue 2 separate commands to leave then join a channel.

**Comment by EvilOlaf** [comment]
So "join" would actually work as "switch" ?

**Comment by BamaJoe411** [comment]
yea if they are currently in a channel. is there a switch command i don't know about?

**Comment by EvilOlaf** [comment]
No clue. Though this is a sugguestion issue report, so.... :D

**Comment by Carisus** [comment]
I couldn't find a switch command. But I really like the suggestion. The way it is now is too clunky.

**Comment by kangarko** [comment]
The implementation allows to have multiple channels. However, during the development I only got the implement one channel functionality properly, so this is a left-over and thus I am leaving this open for the future in case I will add multiple channel system.
