### ISSUE TITLE
How to make Faction Enemy chat

### ISSUE THREAD

**Issue by iPintoBean** [kangarko/ChatControl-Pro#1073]
I'm interested in making a channel that only enemy factions can use. I also want players to be able to toggle the chat on and off if they wish. We are using SavageFactions for our factions plugin. Is this something that can be done in ChatControl and how would I go about creating it?

**Comment by kangarko** [comment]
Hey, at present it is not possible to create an enemy factions channel, only a channel connecting players in your own faction, see https://github.com/kangarko/ChatControl-Pro/wiki/Channels#party
