### ISSUE TITLE
Please do not repeat the same (or similar) message.

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1076]
After being afk for a while (>15min), player tries to say 1 word, something like "back" and gets the `Anti_Spam.Similar_Message` (Please do not repeat the same (or similar) message.)
This is odd, since the same message is not repeated at all. It keeps blocking the word until you say something more than 1 word, something like a sentence.

It looks quite similar to issue #910 
I tried antispam-time debug but this does not give a clue
```
Delay from last message: 1203 vs configured delay for TestPlayer123: 0
```

**Comment by x1p** [comment]
Turned parrot off, but it's not caused by that.
```
    Parrot:
      Enabled: false
```

**Comment by x1p** [comment]
Just FYI: same with 7.11.14

**Comment by SmallSansSerif** [comment]
Started getting this recently on /reply

Any idea if this is related?

! Please wait 1 second before your next command.

![2019-02-09_21 39 11](https://user-images.githubusercontent.com/4984139/52528827-8e52bb00-2cb5-11e9-97f0-372c5591fdbf.png)

**Comment by x1p** [comment]
Idk but there are strange things happening. Like this one:
The similar_message error also appears when a muted player tries to whisper to player.
`/msg playername123 Why am I muted?` is apparently the same as /msg playername123 Could someone tell me why I am muted?` It doesn't matter what is been said, the same player name is enough.

**Comment by x1p** [comment]
Still exists in 7.12.0

**Comment by kangarko** [comment]
Sorry for the delay, please test the next version. Also check console for potential errors please.

**Comment by x1p** [comment]
Same
If there was an error, I would certainly noticed.

**Comment by kangarko** [comment]
Alright so after I installed CMI, the chat event started to be fired twice. This is a bug in CMI, please report to its developer. I am glad we are onto something.

**Comment by x1p** [comment]
> By itself CMI doesnt fire chat message twice.
Stuck between 2 plugins -_-

**Comment by x1p** [comment]
I have a suggestion which could be a nice workaround and a nice feature too.

It would be nice if I can block the third (same) message. Like when a player is permitted to say 1 sentence (somewhat) duplicate, but not a third time.
This would be nice besides this issue. So I'll make a separate issue to keep track of it.

**Comment by kangarko** [comment]
Thank you, right now we are not planning to change the antispam but I noted it down

I hope that dev will answer you soon :)

**Comment by x1p** [comment]
I definitely want this blocking the third message thing anyway regardless of this issue.

**Comment by x1p** [comment]
It's solved by CMI. Just want to share the solution.

> Yea, he is actually correct, this is issue with paper spigot slightly different handling of chat message. Will do some adjustments to eliminate secondary event. Even tho its been canceled which should be checked by ChatControl, but lets make it better.

**Comment by kangarko** [comment]
That is wonderful news!

Right now my plate is full and so I am not planning to further adjust the antispam, but you can adjust these two highlighted features to pretty much prevent most heaviest forms of spam:

![a](https://i.imgur.com/LqgzTgV.png)
