### ISSUE TITLE
"ignore usernames" deletes username from text

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1077]
When a rule contains "ignore usernames", this username will be deleted from the text completely. I would expect it would ignore the player name from checking.

Example chat.txt:
```
match ([a-z])(?=\1\1\1+)
ignore usernames
then replace
```
Player1 executes: /msg Player2 Hey Player2 hoooooooooooows it going old chap?
```
[12:31:42 INFO]: Player1 issued server command: /msg Player2 Hey Player2 hoooooooooooows it going old chap?
[12:31:42 INFO]: *--------- Rule match (chat) for Player1 ---------
[12:31:42 INFO]: MATCH: ([a-z])(?=\1\1\1+)
[12:31:42 INFO]: CATCH: Player2 Hey Player2 hoooooooooooows it going old chap?
[12:31:42 INFO]: FINAL: Hey hooows it going old chap?
```
This results, in this particular case, in the command: `/msg Hey hooows it going old chap?` So it fails due to `Player not found` because `hey` is not a player.

If it would be a global chat it would result in `Hey hooows it going old chap?` which breaks the meaning too. It simply deletes the username. Same behavior if this is in a handler.

**Comment by x1p** [comment]
`ignore usernames` is probably case sensitive because it keeps muting players when the case is not exactly the same. This leads to unnecessary mutes and is confusing for players.
Is there a way to make this not case sensitive?

**Comment by kangarko** [comment]
Hey, at this time it is not possible to make it case insensitive. 

The way our system works is that it needs to remove the playername from the rule to make the rest of the rule possible to check. We are evaluation possible changes.

**Comment by x1p** [comment]
Players type player names as they like. Especially on servers with tab completion disabled (not mine anyway). I estimate 80% have tab complete turned off. Meanwhile this function should be used with care.

**Comment by kangarko** [comment]
I have turned it around by pretty massive workaround, player names are translated into _pid + player unique id during rule check and then reverted back into normal just before the message is compiled.

From my testing it works fine, so you should be able to use it starting the next release ;)
