### ISSUE TITLE
DiscordSRV intergration no longer shows deaths in chat.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1078]
I used to get custom death messages sent from DiscordSRV to the main server chat, but this no longer works.

**Comment by kangarko** [comment]
Hey, sorry for the delay,

Do you mean the death messages from messages.yml file?

**Comment by FrozenBeard** [comment]
Either/or no death messages are being sent to the Discord SRV server as chatcontrol takes over death messages.

**Comment by kangarko** [comment]
Added integration to the next version
