### ISSUE TITLE
Advertisement notifier permission node

### ISSUE THREAD

**Issue by MandiKro** [kangarko/ChatControl-Pro#108]
Hey so I'm owner of noxiouscraft.net, whenever someone advertisers I get a notification like [AD] Playername > mineplex.com, whats the permission to see this because I want my staff to see notification when someone tries to advertise.

**Comment by EvilOlaf** [comment]
`chatcontrol.notify.ad` as predefined in your `handlers.yml`

**Comment by MandiKro** [comment]
thanks,. feel free to close
