### ISSUE TITLE
[Feature Request] [item]

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#1080]
Hello kangarko,

Recently I have been searching and searching for an [item] plugin which displays the item you are currently holding into chat.

All of the plugins I have come across are either broken, outdated, or do not support ChatControlPro.

If you could implement this feature into this plugin it would be much appreciated.

Thanks for your consideration :D

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion, but at present we are not planning to include it.
