### ISSUE TITLE
How to type multiple lines in /chc announce

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#1081]
Exactly how it says in the title.

You have this image here in your plugin description:
![image](https://user-images.githubusercontent.com/17891302/52172793-cc873200-272b-11e9-8ea3-e2eba71f8302.png)

How did you do that?

Thanks for your help.

**Comment by kangarko** [comment]
Hey,

use | to split the message:

/chc announce Hello|World
