### ISSUE TITLE
PlayerMention highlights only the name

### ISSUE THREAD

**Issue by fjeddy** [kangarko/ChatControl-Pro#1082]
HELLo,

Currently the `Color` option in `Sound_Notify` is only highlighting the persons name, I would rather highlight the entire message, instead of the name itself.

Aka, I want to apply the color to the entire message, not just the persons name.

Possible?

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion, at present we are not planning to change the current system.

**Comment by fjeddy** [comment]
This is related to #1083, you can easily make this a config option when you fix the other issue. It will in fact be easier for you to highlight the entire message, instead of highlighting just the name.
