### ISSUE TITLE
Factions 3 variable compatibility

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1085]
Hey.
So apparently one of the developers of the original Factions split from the rest of the team and contacted me saying they wheren't updating the main branch anymore.

He's currently developing a new branch named Factions3 here: https://www.spigotmc.org/resources/factions3-for-1-13.63602/
Could you possibly add compatibility for the new Factions through the variables? Since they currently stopped working and look like this: 
![imagen](https://user-images.githubusercontent.com/6623704/52247824-b1632080-28eb-11e9-9606-2e84550a073a.png)

CC v.7.11.0

**Comment by kangarko** [comment]
Thank you, but we are not planning to add it since we already support PlaceholderAPI which handles most of our variables anyways. Contact their dev instead please
