### ISSUE TITLE
Optimize Player quit event

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1086]
I noticed player quit event on chatcontrol it alway one on  top of timings, i tested also without mysql, as you can see it for example on kitpvp
https://timings.aikar.co/?id=1c845cb675a34f0ea8f2941efb5a0b0e

**Comment by kangarko** [comment]
Set **Log_Lag_Over_Milis** to **1** and **Debug** to **["*"]** (warning - lots of spam will get produced) and post me your console when someone logs out.

**Comment by xion87** [comment]
[2019-02-12-1.log.gz](https://github.com/kangarko/ChatControl-Pro/files/2864838/2019-02-12-1.log.gz)
I attached the full day of a random day

**Comment by xion87** [comment]
any news about this?
see chatcontrol quit event is alway on top https://timings.aikar.co/?id=a2ab3b7571da4fdc97e66c8d94a6ca86

**Comment by xion87** [comment]
maybe you should make it async?

**Comment by kangarko** [comment]
How big is your data.db file?

**Comment by kangarko** [comment]
Made the saving of the file asynchronous, next update should increase performance

**Comment by xion87** [comment]
477 kb
