### ISSUE TITLE
[Request] To show player's server display name from Discord message

### ISSUE THREAD

**Issue by momoservertw** [kangarko/ChatControl-Pro#1087]
Can you add a way the show the player's server display name from Discord message?
I tried some placeholder and it didn't work.  {player}, {nick}, {display_name}, {cmi_user_display_name}

ChatControlPro version: 7.11.13 (latest)
DiscordSRV version: 1.16.6 (latest)
Paper version: git-Paper-521 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (latest)

**Comment by kangarko** [comment]
If the player is online, the {player} variable will work. You can also turn Compatibility.Discord.Apply_Natural_Format_If_Online to true in channels.yml to apply the natural format just as he would type in-game.
