### ISSUE TITLE
JSON in chat formatter

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#109]
Quite a while ago I had the idea to JSONify player prefixes. https://github.com/kangarko/ChatControl/issues/45

As this does not work I recently had a new idea.
I was thinking to add a small info box in the beginning of each and every players message by simply adding it to the `Message_Format`. However this info box should contain JSON stuff like hover text and I am unsure if this would be at all.

So the chat should look something like this:

`[?] (Player) xxIamStupidxx: hello`

On mouse over the `[?]` will reveal its secret content.

**Comment by kangarko** [comment]
Hello,

on premium version, this is totally possible, you'll find examples on how to do it easily in chat.yml. Just add a new section in the desired format in that file, use hover event and add lines that will show upon hovering on that text piece.

**Comment by EvilOlaf** [comment]
Awesome. I'll give it a try some when.....I updated to premium xD

**Comment by kangarko** [comment]
Thank you! Feel free to post the file below if you'll be stuck or need help. 

TIP: You can use CHC along with PlaceholderAPI to display thousands of variables from all kinds of plugins.

**Comment by kangarko** [comment]
Create a new ticket if you'll need help.
