### ISSUE TITLE
LuckPerms can't set 'chatcontrol.messages.join' to false

### ISSUE THREAD

**Issue by minortoms** [kangarko/ChatControl-Pro#1090]
### Issue
After reload the plugin, ChatControl keep spamming my chat with a join messages. I know that I can disabled it with a 'chatcontrol.messages.join' permission. but somehow they don't works.

I capture the messages below with a 'default' group player, sorry that all the messages are translated. 

![2019-02-10 030044](https://user-images.githubusercontent.com/47142098/52524431-3f6e4b00-2ce0-11e9-8b52-f1d5167355f0.jpg)

### Default group's permission
![2019-02-10 030016](https://user-images.githubusercontent.com/47142098/52524430-3ed5b480-2ce0-11e9-8515-53c053bb8b27.jpg)

### Versions
- [Paper 1.13.2-R0.1-SNAPSHOT (build 521)](https://papermc.io/ci/job/Paper-1.13/521)
- [LuckPerms 4.3.94](https://ci.lucko.me/job/LuckPerms/870)
- ChatControl 7.11.14

**Comment by kangarko** [comment]
Create a localization file (https://github.com/kangarko/ChatControl-Pro/wiki/Localization) and set these messages to 'none':

![a](https://i.imgur.com/4xIrdI7.png)
