### ISSUE TITLE
Option to hook into EssentialsX ignore.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1091]
Would it be possible to hook into Essentials' ignore system? I currently use Essentials private messaging and ignore system to block miscellaneous functions such as ignoring teleport requests and in-game mails form a specific player. However I have gotten reports that players who are ignored, they still show up in public chat.

Players would like to truly ignore someone outright and not see their messages. Thus would it be possible to hook into Essentials' ignore system so certain players can not receive ignored individual messages in public chat?

**Comment by kangarko** [comment]
Added
