### ISSUE TITLE
small issue with formatting

### ISSUE THREAD

**Issue by UncleM0** [kangarko/ChatControl-Pro#1092]
Im using savagefactions and Luckperms. and trying to create (***Fac[Prefix]NAME: Message)

this is what i have come up with. but it does not work. It removes all of the formatting as soon i add {faction} to the formatting settings.  So it goes from [Prefix]Name: Message    to    
***Faction Name> Message..

    faction: 
      Message: "{faction}"       
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - ""
    prefix: 
      Message: "{luckperms_prefix}"       
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - ""
    Player: 
      Message: "{player}:"                 
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&7Message issued: &b{timestamp}"
          - "&7Click to send a PM"
      Click_Event: 
        Action: SUGGEST_COMMAND
        Value: "/tell {player} "            
    The_Rest: 
      Message: "{pl_suffix}&r {message}"

What am i doing wrong?

**Comment by UncleM0** [comment]
Alright hello, i have solved the issue, For those who have the same issue here is how to solve it. 
Placeholders from Factionuuid.


    faction: 
      Message: "{rel_factionsuuid_relation_color}{factionsuuid_player_role}{factionsuuid_faction_name}"       
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - ""

**Comment by kangarko** [comment]
Thank you for posting the solution.
