### ISSUE TITLE
SocialSpy not working

### ISSUE THREAD

**Issue by CryLegende** [kangarko/ChatControl-Pro#1093]
PaperSpigot 1.12.2
ChatControlPro 7.11.14

SocialSpy work only for Auto_Start and do not display players' private messages

**Comment by kangarko** [comment]
It works for me (https://i.imgur.com/rAkHRp9.png), please post me your ChatControl folder in a ZIP

**Comment by CryLegende** [comment]
Yes, that work for the command in "Command_List" (Format) but not for the mp (Format_PM)

**Comment by jascotty2** [comment]
Cannot reproduce. 
You need to have all of the commands you want to spy on (including "reply") in the Command_List.
You may have another plugin conflicting with /reply
