### ISSUE TITLE
Death coordinates

### ISSUE THREAD

**Issue by Enlar** [kangarko/ChatControl-Pro#1094]
Hi! Can we please add in the next version of the text with the coordinates at the point of death?

**Comment by kangarko** [comment]
Hi, you can just install PlaceholderAPI and use a variable that shows the death location from that plugin.

**Comment by Enlar** [comment]
Yes... But I do not want to load the server because of a couple of lines of code...

**Comment by kangarko** [comment]
We are not implementing any more variables due to dozens of requests like that, if you need it use that plugin
