### ISSUE TITLE
Add Item2Chat support

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#1095]
Do you remember how I said most item 2 chat plugins were not working for me? Well I came into contact with the dev of one of them. He said this:

https://gyazo.com/c74373770c3f52e722630a24a359641c

If you could please tell me what that means, or implement it would be much appreciated.

Thanks for your help!

**Comment by kangarko** [comment]
Hi, honestly I have no idea as we do not modify chat in such way. Sorry about this. I recommend you check out this ticket to discover ways to add player hand item to your chat: https://github.com/kangarko/ChatControl-Pro/issues/1054
