### ISSUE TITLE
Performances issue

### ISSUE THREAD

**Issue by Kira07** [kangarko/ChatControl-Pro#1096]
Hi!

Could you please improve the performances of these events in the next update? :c 

https://i.imgur.com/Zsd1QSw.png

Best regards,

**Comment by kangarko** [comment]
Hi, please provide your ChatContol ZIP so I can test with your configuration.

**Comment by Kira07** [comment]
Hi,

I forgot to mention that I have 100+ players online, is that an issue?

Regards,

**Comment by kangarko** [comment]
I don't know, I am waiting for your settings.yml to look at what's the problem

**Comment by Kira07** [comment]
Sure, here it is:

**Comment by kangarko** [comment]
I am sorry I dont see it here

**Comment by Kira07** [comment]
It was attached to the mail, can you see it?

**Comment by kangarko** [comment]
Hey, our developer Jacob was kind enough to implement some optimizations, it should be better in the next version please test it out :)

**Comment by Kira07** [comment]
Hey, thank you very much ! I'll test all this :)

**Comment by Kira07** [comment]
Hi,

Thanks a lot for your help and kindness, I tested the update but
unfortunately I still have performance issues with the latest version
(1.13.1) and 100+ players online: https://i.imgur.com/0FHhv5n.png

**Comment by kangarko** [comment]
Can you please upload your ChatControl in a ZIP to uploadfiles.io ?

**Comment by Kira07** [comment]
Sure!

https://ufile.io/zan1s

**Comment by Kira07** [comment]
Sure, did you got it?

**Comment by Kira07** [comment]
Sure, did you get it?

**Comment by kangarko** [comment]
Not here, sorry:

![a](https://i.imgur.com/qtSl0jl.png)

**Comment by Kira07** [comment]
Oh I see, how can I send it to you in private?

Regards,

**Comment by kangarko** [comment]
PM on on SpigotMc and we take it from there. Use uploadfiles.io to upload

**Comment by Kira07** [comment]
Sure thing, pm'd ! Thank you
