### ISSUE TITLE
Preventing 1 message to violate more than one rule

### ISSUE THREAD

**Issue by Kira07** [kangarko/ChatControl-Pro#1097]
Hi,

How can I prevent one single message from triggering several rules at once?

Best Regards,

**Comment by kangarko** [comment]
Hi, this is not possible due to the nature of the plugin, the way it was built from the ground up. You can however sort your rules in the rules files from top to bottom in the way you want them to be checked - player receives only 1 "then warn" or "Warn" (in handlers) message.

**Comment by Kira07** [comment]
Hi,

I understand, thank you for your reply.

Regards,

**Comment by Kira07** [comment]
Could you make it so that the player receives only one "then points" too?

Regards,

**Comment by kangarko** [comment]
Hey, this is the same as with above, our current system does not work that way, there is only the exception for messages but everything else will trigger all relevant rules

**Comment by Kira07** [comment]
I understand, thanks anyway
