### ISSUE TITLE
Sugestion, Add a /helpop command that sends over bungeecord

### ISSUE THREAD

**Issue by GeertBraakman** [kangarko/ChatControl-Pro#1098]
Suggestion
=======

Hello kangarko, I am x313 and I have a suggestion for the ChatControl plugin, maybe you could add a `/helpOp` command that sends over the **Bungeecord**, I would really like this because I love the way you make everything configurable and that's what i need. I would like to have it support `JSON` as well, like you did with the admin chat feature. 

---
**Some features i would like to have:**
- Write to it with a permission like `chatcontrol.commands.helpop`.
- Read it with a permission like `chatcontrol.helpop.recive`.
- Send it over the whole Bungeecord network.
- Have it support `JSON` and chat variables.
- Not being able to switch to it like you did with admin chat, I want it to have a command only.

I hope you will consider it! 😄

---
Best regards **x313**

**Comment by kangarko** [comment]
Hey, thank you, I am leaving this open as right now we are not taking any more bigger feature changes

**Comment by kangarko** [comment]
After going through this issue we decided not to include it, sorry

You can just setup channels to achieve a similar result
