### ISSUE TITLE
Debug paste command

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#11]
To improve the quality of support it is also needed to encourage users to add probably helpful information for the developer in first place like CB/Spigot version, plugin version, other plugins that may interfere. Often developers have to ask for those information because users don't have in mind to provide them with the issue report.

Therefore I suggest to add a issue template that is automatically filled in the text window when opening a new issue report. This should be added to both free and pro version repositories.

An example you can find below:
https://github.com/IntellectualSites/PlotSquared/blob/master/.github/ISSUE_TEMPLATE.md

This can give reporters an idea which kind of information is needed to do further investigation. Also it could contain pre-report steps that should be performed before opening an issue report like `make sure you are using the latest version of both Spigot and CHC` or `check your latest log for stuff related to CHC` ...

For clarification related to the issue template example above: `/plot debugpaste` has been introduced in P^2 quite a while ago and will automatically gather all necessary information about the plugin itself, their configuration files, other plugins running, the server software as well as the running Java environment. Basically everything it can get that might be useful for debugging and puts it to Hastebin. So the users does not have to collect these information by itself, it will provided within a single link.

**Comment by kangarko** [comment]
I highly appreciate your help. I believe that adding such command will definitely improve the quality of the plugin overall. I will consider making a template.

**Comment by kangarko** [comment]
Pulled & improved. Thank You.

The debug command has a low priority. Thanks for your understanding.

**Comment by EvilOlaf** [comment]
No worries.
