### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by EnvelGo1** [kangarko/ChatControl-Pro#1102]
Hi! I found a bug. 
  
`Grammar: 
  
  # Punctualize every sentence (insert a dot at the end).
  Insert_Dot:
    Enabled: true
    Min_Message_Length: 5`

The point is not assigned if, for example, Russian language. The point is, if you use English, but not Russian. Please fix it.

**Comment by EnvelGo1** [comment]
![image](https://user-images.githubusercontent.com/45996618/52861068-609cc480-3142-11e9-8878-728cb7f98479.png)

**Comment by EnvelGo1** [comment]
Russian. The point is not set automatically.

**Comment by kangarko** [comment]
Hi, I apology but there is no support for punctuation for Cyrillic alphabet in the methods from Java language that we use.

**Comment by Enlar** [comment]
No, you'll have to fix it. You can simply add a dot to all messages in the chat.

**Comment by kangarko** [comment]
That&#39;s not how it works. We use regular expressions to match sentence&#39;s syntax. If the expression is not able to recognize non-latin alphabet, I am afraid I cannot do anything about it.

**Comment by Enlar** [comment]
It is a pity that other languages are not supported. Negatively.

**Comment by kangarko** [comment]
It is a pity that you fail to distinguish between ChatControl and regular expressions, these are two different software and I cannot modify the code of the second one.

**Comment by kangarko** [comment]
I have done some research and adjusted the regex code buffer. Haven't tested, kindly let me know if it works in the next update

**Comment by Enlar** [comment]
:)

**Comment by Enlar** [comment]
It looks like in the latest update this doesn't work yet.

**Comment by kangarko** [comment]
Will be fixed

**Comment by Enlar** [comment]
It's fixed. Thanks so much.
