### ISSUE TITLE
Player side console spam?

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1104]
Heya! My players reported this to me:
[21:12:49] [main/WARN]: Unknown custom packed identifier: plugin:chatcontrol

Apparently it was spamming them every time someone said something or they got a pm. I don't see this in my console at all, all I can see is them mentioning they can see it. 

Paper spigot 1.13.2

**Comment by kangarko** [comment]
Hey, this is not coming from ChatControl directly. Seems like another plugin or you enabled Bungeecords in ChatControl but not installed BungeeControlBridge on your Bungee.

**Comment by Kbryst** [comment]
I'll double check that. Thanks so much!
