### ISSUE TITLE
Whitelist_Similarity just check the start of the command

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl-Pro#1105]
I updated ChatControl from a old version and I'm having issues with this:

```
    Whitelist_Similarity:
    - /tell
    - /pm
    - /t
    - /r
    - /w
    - /m
    - /msg
    - /emsg
```

Users can't use /wb repeated times because of /w, in old version it was working fine.
In addition, `Ignore_First_Arguments_In_Commands: true` on old version was useful but now we haven't it.

**Comment by kangarko** [comment]
Ignore_First_Arguments_In_Commands is still there and toggle naturally.

Post me your settings.yml

**Comment by YellowZaki** [comment]
I haven't that option.
https://pastebin.com/9xUmHnV1

In oldsettings.yml it is, but not on settings.yml.

What about the first issue? It is the most important

**Comment by kangarko** [comment]
Ignore_First_Arguments_In_Commands was removed in newer ChatControl and is now enabled automatically.

You can set Regex_In_Whitelists to true and add \b at the end of the command. Make sure to add \ in front of / for Whitelist_Similarity and Whitelist_Delay in commands:

```
Whitelist_Similarity:
    - \/tell
    - \/pm
    - \/t
    - \/r
    - \/w\b
    - \/m
    - \/msg
    - \/emsg
```
