### ISSUE TITLE
DiscordSRV

### ISSUE THREAD

**Issue by EmanuelSimard** [kangarko/ChatControl-Pro#1109]
1. Currently using Towny
2. Using Towny Chat
3. Using DiscordSRV
4. Using Chat Control Pro

Trying to get DiscordSRV to track what people are saying on our Discord channel. However it doesn't seem to be working because we're using Chat Control. (Atleast thats what the DiscordSRV staffs say, they told me to post the issue here). They say we can't use TownyChat and ChatControl at the same time. Should I just remove TownyChat?

**Comment by EmanuelSimard** [comment]
DiscordSRV Debug:

https://debug.scarsz.me/583328e2-9a59-4f01-9783-ec5c3276663e

**Comment by EmanuelSimard** [comment]
ChatControl settings.yml:

https://hastebin.com/xicokigufi.coffeescript

**Comment by EmanuelSimard** [comment]
DiscordSRV config.yml:

https://hastebin.com/tekuziloxi.bash

**Comment by EmanuelSimard** [comment]
DiscordSRV account linked to bot.

**Comment by EmanuelSimard** [comment]
It only says when the server starts and stops, and when a new player joins the game for the first time. It doesn't transfer the messages. Something is blocking the event.

**Comment by EmanuelSimard** [comment]
ChatControl is necessary to allow cross-server chat between servers however...

**Comment by EmanuelSimard** [comment]
I noticed that removing chat control allows us to chat from Discord to minecraft but not minecraft to Discord. I’ll look further into the configurations I suppose.

**Comment by EmanuelSimard** [comment]
I removed TownyChat, since we want to be using ChatControl for cross-server chat. 

The following line of configuration from channels.yml allowed us to be able to chat from Discord to Minecraft, but not Minecraft to Discord:

    Deny_Unknown_Channel: false

**Comment by EmanuelSimard** [comment]
I noticed I'm not the only one facing this issue at the moment with TownyChat.

**Comment by kangarko** [comment]
Hey,

please set Debug to ["discord"] in settings.yml and restart to discover where the problem lies.

**Comment by kangarko** [comment]
I added new option to formatting.yml allowing you to send messages to Discord. Test the next version

![a](https://i.imgur.com/CLQaarQ.png)

**Comment by EmanuelSimard** [comment]
> [15:17:25 INFO]: [Towny] SupremeObsidian : test
> [15:17:25 INFO]: [DiscordSRV] [DEBUG] Chat message received, canceled: false
> [15:17:25 INFO]: [ChatControl] [discord] [ChatControl->Discord] Sending msg from SupremeObsidian to 'global' channel: test
> [15:17:25 INFO]: [DiscordSRV] Plugin ChatControl v7.13.0 cancelled AsyncPlayerChatEvent (author: SupremeObsidian | message: test)
> [15:17:25 INFO]: [DiscordSRV] [DEBUG] Chat message received, canceled: true
> [15:20:04 INFO]: [DiscordSRV] [DEBUG] Synchronizing player SupremeObsidian
> [15:20:04 INFO]: [DiscordSRV] [DEBUG] Could not find role id 000000000000000000 for use with group synchronization. Is the bot in the server?
> [15:20:04 INFO]: [DiscordSRV] [DEBUG] Could not find role id 000000000000000000 for use with group synchronization. Is the bot in the server?
> [15:20:04 INFO]: [DiscordSRV] [DEBUG] Could not find role id 000000000000000000 for use with group synchronization. Is the bot in the server?
> [15:20:04 INFO]: [DiscordSRV] [DEBUG] Tried to sync groups but no synchronizables existed

**Comment by EmanuelSimard** [comment]
It did not send the message to our #global channel, do I have to paste the ID of the channel somewhere besides DiscordSRV's configs?

**Comment by kangarko** [comment]
Make sure you linked the channel ID in your discord config.yml, then not really. Does it work when you are an operator?

**Comment by EmanuelSimard** [comment]
It does not.. It works on all our servers except for the Towny server.
