### ISSUE TITLE
Error with Private Messages

### ISSUE THREAD

**Issue by lizardfreak321** [kangarko/ChatControl-Pro#111]
**Version:**
Newest spigot 1.8.8
Sent over bungeecord.

**ChatControl version:**
7.0.20

**Error:** http://pastebin.com/JDcTgTC5

**How to reproduce:**
Send a PM with the interactive formatter disabled. It should be using the static format, but it is not.

**Comment by kangarko** [comment]
Thanks for reporting, I will fix it in the latest version.
