### ISSUE TITLE
Per World chat - how to disable range notification ?

### ISSUE THREAD

**Issue by Dzack10** [kangarko/ChatControl-Pro#1112]
Hello !
First i wanted to say congratulations for your plugin, it's helping me a lot ^^

I just have a little question : i activated the per-world chat (using the range setting), but when someone is alone in a world, there is a message that say there is no-one in range for his message. Is there a way to deactivate this message, and if yes, how ?

Thank you for your help !
Have a good day :)

**Comment by kangarko** [comment]
Hey, see https://github.com/kangarko/ChatControl-Pro/wiki/Localization and set the message in that file to "none" or ""
