### ISSUE TITLE
[Sugestion] similarity blocking the third message

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1113]
Would it be possible to block not the second but the third message a player chats, somewhat the same message?

This way a player is allowed to says 1 duplicate message, but not 3 times.
To my knowledge, this is not possible to configure right now.
If `Similarity_Message_Check_Count:` is set to 2, it would still block the first time a player repeats itself.

This would allow a server to be more tolerant to players and would be a great workaround for issue 1076

**Comment by kangarko** [comment]
Thanks, noted
