### ISSUE TITLE
Suggestion: Toggle messages from other servers.

### ISSUE THREAD

**Issue by PlayDatblockCom** [kangarko/ChatControl-Pro#1114]
**Suggestion:** Option for "/chc g switch" to also toggle receiving messages from other servers. At the moment it can only toggle sending to other servers. 

I did not find this suggestion on the roadmap and my players are always requesting to have this feature added.

**Comment by kangarko** [comment]
Thanks, leaving open

**Comment by PlayDatblockCom** [comment]
I would be happy to donate to this project to have this feature prioritized if that is a possibility.

**Comment by kangarko** [comment]
I am thinking about making a separate command /chc g toggle instead for clarity, the switch has different function. What do you think?

**Comment by PlayDatblockCom** [comment]
That sounds good, but the new command will toggle both sending and receiving messages right?

**Comment by kangarko** [comment]
Yes, you will be able to use /chc g toggle twice and it will disable/enable receiving bungee messages.

**Comment by PlayDatblockCom** [comment]
Was this feature added?

**Comment by kangarko** [comment]
No sorry, we're not having time for any major new features right now

**Comment by kangarko** [comment]
Pulled into roadmap
