### ISSUE TITLE
What's wrong with my swear filter?

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1117]
Hey. Recently I found out my swear filter wasn't working, so I updated it like this, according to the default swears on a clean install:
https://pastebin.com/MGJ3vLa9

Still doesn't work, not all swears work, for example "prostitute" doesn't get processed, and all my spanish swears too.

ChatControl v.7.13.4

**Comment by kangarko** [comment]
You have the '#' letters in front which makes the code not install by the program. These letters mean that the line is a commentary, remove to make it work. Also remove it from all other filters below that contain it.

![a](https://i.imgur.com/ZGTamZg.png)
