### ISSUE TITLE
Issue with formatting chat and having different chat colours for different ranks.

### ISSUE THREAD

**Issue by MrWardy** [kangarko/ChatControl-Pro#1118]
Hi there! I'm trying to set up different chat colours for different ranks. One colour for default, one for lower staff, and one for upper staff. But the way I'm doing it isn't working. I've attached an image of the relavent config and what is happening.

I'm using v7.11.3 (I am aware this is not up-to-date, this issue has been an issue for about a month maybe more.

I'm using "Paper version git-Paper-488 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

The expected output in chat is for the chat to be entirely yellow.
![frYKSm](https://user-images.githubusercontent.com/27183976/54079948-17501880-429b-11e9-8bc5-e1ae4ec24e50.png)
![4tiuiZ](https://user-images.githubusercontent.com/27183976/54079950-1a4b0900-429b-11e9-9a71-8e1e6c520742.png)

**Comment by kangarko** [comment]
Update your ChatControl.

Add Permission: "your.permission" below "Message" key for each group and give that perm to the respective users, example:

```
Default_Color_Message:
  Message: ....
  Permission: your.fancy.permission

```

**Comment by MrWardy** [comment]
I added permissions to each, and it still doesn't work. I do have both the default and the management permissions, but that shouldn't make a difference since there can only be one colour at a time and the management colour comes last. From adding the text "yeet ||" to the messages it seems like the issue is happening between the colour part and the message part (indicated by the drawn red arrow in one of the attached images.)

![DSCe4W](https://user-images.githubusercontent.com/27183976/55284290-819f2a80-5328-11e9-9578-0d56fbe14721.png)
![HRK39d](https://user-images.githubusercontent.com/27183976/55284291-819f2a80-5328-11e9-93b4-fcb2449ecd97.png)

**Comment by MrWardy** [comment]
@kangarko

**Comment by kangarko** [comment]
@MrWardy I apology, I gave you an outdated advice. We recently changed the Permission key to Sender_Permission. 

For a future reference, please see https://github.com/kangarko/ChatControl-Pro/wiki/Formats

**Comment by MrWardy** [comment]
I've changed it to Sender_Permission but nothing seems to have changed.

**Comment by kangarko** [comment]
Upload me your entire formatting.yml file to pastebin.com please.

**Comment by MrWardy** [comment]
For sure.
Here it is: https://pastebin.com/M6S6vFNC

**Comment by kangarko** [comment]
I've edited the file slightly, you'll find "kangarko edit start" and "kangarko edit end" for your convenience.

https://pastebin.com/GFMwJnge

If you are an OP or have '*' permission, you will get all parts displayed to you. What you need to do then is to give yourself negative permissions (starting with a -, or called false permissions on LuckPerms) for all the parts you don't want to have displayed on yourself.

**Comment by MrWardy** [comment]
Okay, I will update it, sorry about that. I appreciate you helping me regardless.

**Comment by MrWardy** [comment]
So I do have a question actually. You mentioned if I have wildcard permissions all parts will be displayed. Which makes sense if you had some text or something. But since the parts that are concerned in this ticket are just colour codes, even if I have wildcard permissions shouldn't I just get the owner colour since it's the last one of the other colours in the config?

**Comment by MrWardy** [comment]
Yes, my theory was correct, I have wildcard permissions and I still get the red chat colour. Thank you so much for your support, I really appreciate it.

**Comment by kangarko** [comment]
No worries you are welcome :)

**Comment by BenjaminHoegh** [comment]
i have the same issue, how did you guys fix it?
