### ISSUE TITLE
Chat Colors

### ISSUE THREAD

**Issue by Dallas1117** [kangarko/ChatControl-Pro#1119]
I've given the perm for color chat and it just simply doesn't work for anyone except people that are opped. I did /pex group <name> add chatcontrol.chat.format.color.* and it just simply doesn't work for the Rank I gave the perm to.

**Comment by kangarko** [comment]
Hey, sorry for the delay, are you using formatter.yml file or channels.yml? Where exactly does it not work when they write - chat, admin chat, bungee chat etc.?

**Comment by kangarko** [comment]
Closing due to no response, comment below if you still need help. Thanks
