### ISSUE TITLE
Channel Joining

### ISSUE THREAD

**Issue by TeeKay1** [kangarko/ChatControl-Pro#112]
so I am having an issue where people cant join the channel while they have perms for it. My Server Designer wasnt able to join the channel of the server. Ive tried to set it up so they join that server channel automatically but for some reason its not working. There is no errors in my console or logs so now im just stumped. Please help. If you need more info please ask. I described it the best i could, but i can try again if need be. It's saying invalid permissions.

**Comment by kangarko** [comment]
Please post me your chat.yml

**Comment by kangarko** [comment]
Closing, assuming it's fixed.
