### ISSUE TITLE
Double death message

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1120]
Often i get double messages about death players
![image](https://user-images.githubusercontent.com/3611852/54236987-3d80ed00-4515-11e9-98ff-69fd73bbcb0a.png)

**Comment by kangarko** [comment]
Hey, sorry for the delay. I believe it was fixed in the most recent update.

Anyways, in case you run into it again, set Debug to [deathmessages] and restart. When that happens please post me the console output. It should say {player}'s death cause is {cause} with replaced variables.
