### ISSUE TITLE
Ranged channels broken with 7.12.0

### ISSUE THREAD

**Issue by skyybender** [kangarko/ChatControl-Pro#1124]
The function of having range limited channels got broken with the ChatControl update 7.12.0. All channels that have a specified range limit are readable all over the world now.

I have tested about 20 different versions for finding the last working state. I also deleted my plugin and channel configuration but this did not solve the problem. Would be great if you can fix that as soon as possible :)

**Comment by sandwally** [comment]
I have the same that ranged value seems to lost its check in 7.12.0 and later versions have the same problem.
Tried everything from current pre 7.12.0 settings where it works and tweaking it on 7.12.0 and reset of all permissions and plugins to slowly add and try, but can't get the chat sent to ranged.

**Comment by kangarko** [comment]
Thanks, we are on it, preparing a fix soon

**Comment by kangarko** [comment]
The issue has been resolved. I personally apology for the delay and the inconvenience caused. I have tested the new major release and it will be available for download in 1 hour.
