### ISSUE TITLE
Decoder Exception

### ISSUE THREAD

**Issue by GalaxyBabe** [kangarko/ChatControl-Pro#1125]
![image](https://user-images.githubusercontent.com/48149850/54555852-37c95280-49c0-11e9-9432-68a9a6ebd735.png)

Everytime I press tab I get kicked and that error appears.  Below is what is printed in console:

Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

**Comment by kangarko** [comment]
Hey, sorry for the delay.

What is your Minecraft server version? If you are using ViaVersion you need to disable Packets in ChatControl.

**Comment by kangarko** [comment]
I assume you use ViaVersion so please disable Packets in ChatControl, if not comment below and I will get back to you.
