### ISSUE TITLE
PrivateMessageEvent not triggering

### ISSUE THREAD

**Issue by Gaurav99** [kangarko/ChatControl-Pro#1126]
In my plugin that's hooked into ChatControl, I've registered a class as a listener and have a listener method for PrivateMessageEvent but it doesn't seem to be triggering -- I added a debug print statement on any message to test it and it's not printing to console. It has the @EventHandler tag

Is this not meant to work?

**Comment by kangarko** [comment]
Hey, I apology for not updating our API on the wiki, grab the latest one from https://kangarko.com/api/ChatControlAPI.jar and listen to PrePrivateMessageEvent or PostPrivateMessageEvent.
