### ISSUE TITLE
Toasts not working for me

### ISSUE THREAD

**Issue by GermanMinersNET** [kangarko/ChatControl-Pro#1128]
Hello there,
the toast notifications for private messages do not work properly for me (anymore).
Sometimes they work and are displayed and sometimes not (the vast majority of times they are not displayed). However, the messages in the chat are always displayed, there are no problems with them.
I guess it's one of the last updates, because before I updated the toasts worked without problems and I haven't edited the config since.
The Minecraft version of the server is 1.12 and the plugin version 7.41.1.

In the settings.yml toast --> Enabled: is true and in the server log I also get a warning about toasts (so toasts are definitely enabled).

**Comment by kangarko** [comment]
Please upgrade to ChatControl 7.15.0 that will be available in 1 hour
