### ISSUE TITLE
[item] placeholder

### ISSUE THREAD

**Issue by mesandridge** [kangarko/ChatControl-Pro#1130]
I saw that someone else already suggested this and you closed it as not going to be done.  Is there a way other than creating a new ticket such as this one to add my name to wishing for this?  Or, would it be possible via the java-script interface (I don't know enough about how it works to know if it could be done that way)?

As for not doing it, I would like to suggest that this is the ideal place for it since it's a chat action that would trigger this (say, someone putting [i] or [item] in a chat message).  So please reconsider as a low priority future feature?

**Comment by kangarko** [comment]
This is already on our roadmap but I am leaving it open here because we are going to prioritize it. These days I am busy with a real life project so only doing bugfixes so I cannot give you an estimate, sorry.

**Comment by kangarko** [comment]
Pulled as high priority into roadmap

**Comment by Sikatsu** [comment]
Can't wait for this one. Many of my players requested such feature and I don't want to install more plugins just for a small extra feature.

**Comment by kangarko** [comment]
@Sikatsu this is one of the most requested features and our great dev team will be ready to implement this in December/January

**Comment by Sikatsu** [comment]
Will this also be added for the Bungee chat? Can't wait to implement this on my server! @kangarko

**Comment by Sikatsu** [comment]
@kangarko December/January deadline missed. Any news?

**Comment by AngelDeaD** [comment]
@kangarko I'm also interested in this. Decembar/January of which year? It's April now, btw. Thanks

**Comment by lackoSK** [comment]
@AngelDeaD coming in next update :P :)
