### ISSUE TITLE
Incompatibility with MobArena's isolate-chat feature.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1131]
Paper dev 585 (Spigot 1.13.2)
ChatControlPro v7.14.1
MobArena v0.103.2-SNAPSHOT (discord test build 02/16/19)

@kangarko RE: https://github.com/garbagemule/MobArena/issues/395#issuecomment-475846118

**Comment by garbagemule** [comment]
Does CCP use the recipients list in the chat events? If not, that is most likely the cause. MobArena filters the recipients list to exclude players who shouldn't see the given message, and this results in the expected behavior on a barebones Spigot setup.

**Comment by kangarko** [comment]
@garbagemule ChatControl clears all recipients and sends the message using own JSON methods to support hover elements, that's why it must come as the last plugin in the pipeline so that it takes an already clean recipient list

@mibby what about setting Listener_Priority.Formatter to MONITOR ?

**Comment by mibby** [comment]
@kangarko Unfortunately even with it set to MONITOR, it does not work.

**Comment by kangarko** [comment]
Unfortunately it appears unsolveable for me at this moment, however if you are using chat channels I can look into adding a separate party channel that would only send messages to players in the same arena as the sender. I could make a player join/leave that channel automatically based on join/leave of an arena. Sounds good?

**Comment by mibby** [comment]
@kangarko Unfortunately I am not using chat channels. :( I have all chat being sent publicly to all servers in all worlds - a single "global" chat so to speak.

Even if I was, wouldn't it be more work to add compatibility to every single arena plugin that may exist instead of just letting the arenas handle how it wants to isolate chat? Trying to bring back compatibility so MobArena itself can isolate players seems like a more appropriate resolution to the issue so you don't have to hook into dozens of different plugins.

**Comment by garbagemule** [comment]
I definitely think the per-arena channel idea is good if it solves the problem - the responsibility of handling chat lies within chat plugins, not with arena plugins.

I don't think CC should hook into each and every arena plugin, however. Instead, it should provide a way for the arena plugins to set up and tear down the party channels on a per-session basis, but in a way that doesn't require the arena plugins to hook into CC directly.

For example, MobArena could provide triggers/hooks that allow server admins to run commands or assign permissions based on different events, such as "first player joins new session", "another player joins existing session", "last player leaves existing session". ChatControl could provide commands to set up and tear down channels, and then server admins could use ChatControl's commands in MobArena's hooks/triggers/events to achieve the isolated chat.

The result would be isolated chat managed by ChatControl, as it should be, but "initiated" by MobArena.

**Comment by kangarko** [comment]
@garbagemule thanks for the input!

@mibby I just had some time to test, using isolated-chat on true and default NORMAL priority with formatting.yml enabled, it worked just fine and the chat was isolated

![a](https://i.imgur.com/hSmNkC4.png)

I would need to see your entire ChatControl/ folder as well as MobArena/ folder. If these are private please contact me on SpigotMC.

**Comment by mibby** [comment]
@kangarko Quite odd. Perhaps having a bunch of placeholders prior breaks the player detection for isolation? I'll send you a spigot PM with all configurations as I can quite easily reproduce the issue on my test server.

**Comment by kangarko** [comment]
We'll continue on Spigot ;)
