### ISSUE TITLE
Ignore swear not working?

### ISSUE THREAD

**Issue by SpartanPride7** [kangarko/ChatControl-Pro#1132]
Hello!

I own a server with players who like to swear. However, I want new players who I don't want to see swears or swear themselves right away. I'm trying to use the command: /chc ignore swear to make it so players who ignore the filter can curse, and see their curse word, but players who do not ignore swear still cannot see it. However, every time a player runs the command, they still get the message replaced by ***.

Just to repeat myself so it's not confusing :P : 
-Players cannot swear, or see swears, by default
-Players who do /chc ignore swear can swear fine and also see when other people swear
-People who do not do /chc ignore swear cannot see any swears (even from people who had ignored it), and nor can they swear themselves.

Please tell me this is possible? Am I just doing something wronglly?

Settings.yml: https://pastebin.com/3BvwWUkD
Rules.txt: https://pastebin.com/JswKmHDU

**Comment by SpartanPride7** [comment]
EDIT: here is the handlers file: https://pastebin.com/CbjQh6k6

When I put the "  Ignore_Chatdisplay: swear" in, players just don't see the message in chat at all. I want them to be able to see the curse words, and for other people to see the curse word as well IF they have swear ignored. People without swear ignored will still see ***. However, that isn't happening.

**Comment by kangarko** [comment]
@SpartanPride7 hey Spartan, apology for a late response, totally lost your ticket.

At this moment this is not possible, however I took a note of it as a suggestion and will look forward into expanding our chat ignore into the future.

You can however, simply give chatcontrol.bypass.swear permission to people who can swear and they will be able to bypass the filter.
