### ISSUE TITLE
Timed Announcer

### ISSUE THREAD

**Issue by Roran2** [kangarko/ChatControl-Pro#1134]
Is it possible to center a line in the announcer section? I've tried using <center> and </center> but that doesn't work at all lol.

**Comment by kangarko** [comment]
Hey, yes, but you have to start the line with `<center>` only.

```
Message: 
  - '&8*--------------------------------------------------*'
  - '<center>&fHello {player}, this is centered'
```

**Comment by Roran2** [comment]
So you're saying something like this;
Vote:
        - '&7[&e!&7]&f&m                                            &7[&e!&7]'
        - ''
        - '<center>&7[&e!&7]&6»&fINFO&6«&7[&e!&7]'
        - ''
        - ''
        - '&7» &eDon't forget to vote for'
        - ''
        - '&7» &esome awesome rewards&7!'
        - ''
        - '&7[&e!&7]&f&m                                            &7[&e!&7]'
would work?

**Comment by kangarko** [comment]
Please post me your entire settings.yml to pastebin.com, I cannot read that code above.
