### ISSUE TITLE
Bungee clearchat

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1135]
We have our server setup so many people play on different servers with the same chat. It would be very handy to get an option in config for /clearchat to work on bungee.

**Comment by kangarko** [comment]
Thanks, that is already on the roadmap. To be honest I am redoing SpigotCourse right now so after that I can hire a dev and we can finally start working through the todos there since they have been hanging there since 2017 which I something that saddens me but that's simply physical time issue.
