### ISSUE TITLE
FactionChatting

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1136]
Any way I can use ChatControl so I don't have to use a dedicated FactionChat plugin for Factions3?
If such method is not implemented, could you offer compatibility for Factions3 by providing Factions Chats?

I don't think this is the right place to ask this, but you did direct me here from the first messsage on the discussion session.

**Comment by kangarko** [comment]
Hello,

Thanks for posting here, that is indeed the best place!

ChatControl supports faction party mode for channels, so if you enable channels in ChatControl for your server it should be able to hook into majority of Factions plugins.

More info + tutorial here: https://github.com/kangarko/ChatControl-Pro/wiki/Channels#party 

Hope that helps,
Have a wonderful day!
