### ISSUE TITLE
Insufficient Permissions (No permissions msg)

### ISSUE THREAD

**Issue by dmnchild** [kangarko/ChatControl-Pro#1137]
Reading through what i could, supposedly there should be a 'reason' listed with the insufficient permissions error. Just installed, and my ops and myself can use /pm /msg /tell but non staff cant. 

I assume its a permissions issue with LuckPerms, and ive been playing around with what to add in there but no luck so far. (the irony)

Seems there could be a more visible permissions section or something addressing such problems. I been looking for awhile, and im either blind or it doesnt exist :(

**Comment by kangarko** [comment]
Hey,

thanks for posting on GitHub.

First, make sure you have Private_Messages.Enabled to true. There should be the 'reason' as you mentioned if you get a no permission message from ChatControl. If you have localization/ folder with a custom locale file, you may want to try to remove it temporarily to get the latest translation.

Also, all perms are listed here: https://github.com/kangarko/ChatControl-Pro/wiki/Permissions. You need to give staff **chatcontrol.commands.tell** and **chatcontrol.commands.reply** permissions.

Hope that helps,
Have a wonderful day!
