### ISSUE TITLE
Death error

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1139]
https://gyazo.com/351b6eb22a859003dac275024c3261b0

version 7.15.0
paper 1.13.2 build 591

**Comment by kangarko** [comment]
Sorry, the error log appears to be incomplete, were there any more errors?

I have solved this "incompletion" problem in the next release, please update and see if you are able to catch it new and repost it.

Thanks
Have a wonderful day!

**Comment by kangarko** [comment]
Closing this ticket due to inactivity, please reply below if you have any questions.
