### ISSUE TITLE
[Script] Nested custom script replacements

### ISSUE THREAD

**Issue by v3Monsta** [kangarko/ChatControl-Pro#1145]
As I was creating custom variables, I came across a scenario which in my mind I thought would work but instead I was greeted by a whole lot of errors in console.

Scenario:
This works just fine and I can use it in my other variables, however I didn't want to have to keep repeating the retrieval of the API so I tried splitting the two up.
![Untitled](https://user-images.githubusercontent.com/16313385/55655288-c829d480-57c1-11e9-8570-b87f14911476.png)

This is when everything went wrong. I was greeted with an error stating `$luckPermsApi` does not exist.
![Untitled2](https://user-images.githubusercontent.com/16313385/55655402-22c33080-57c2-11e9-898d-e17393777863.png)

I wanted to know if it was possible to be able to do something like in the second screenshot or if it was just a limitation and/or wouldn't be worth the performance penalty.

**Comment by v3Monsta** [comment]
It also looks like issue #552 is back. I will get logs and my javascript.txt

**Comment by kangarko** [comment]
Hey, how about changing the $variableName to {variableName} instead?

Also I would say that combining function(node) with Java function may break. I am not really that sound in Javascript's support in Java, but I'd go with that it's a limitation. Sorry about that. 

If you want me to test individual code please upload it to pastebin.com so I don't have to retype it.

If you have any specific errors I should take a look at please post them below, and I will get to you.

**Comment by kangarko** [comment]
Yep, that was ChatControl's limitation. I fixed that, enjoy!

**Comment by kangarko** [comment]
Also, I added a better debug, simply set Debug to [variables] to discover how they are parsed next time :)
