### ISSUE TITLE
Suggestion: More placeholders

### ISSUE THREAD

**Issue by SpartanPride7** [kangarko/ChatControl-Pro#1147]
Hello! I'm using ChatControl along with the plugin UltraCustomizer (GUI setting). Right now, I have 5 chatcontrol party rooms for players to have private, group conversations. What I am attempting to do is use the GUI plugin so players can easily join and leave the channels without issuing the commands manually. However, I would need a placeholder for the GUI to understand if the player is in a chat channel or not so the GUI buttons could change accordingly. Could you make a placeholder that can tell if players are in certain channels, please? :)

**Comment by kangarko** [comment]
Hey,

thank you for using ChatControl. There are over 10,000 placeholders right now from all kinds of different plugins. It's not possible to add all of them and so we decided the following:

1. Install PlaceholderAPI.

PlaceholderAPI brings 1000s of variables, you can check if they got your plugin covered as well. Simply download the proper expansion pack and use the {syntax} variables.

2. Code own variables in custom/variables.txt

If you know a bit of Javascript and that plugin has an API, you can easily code own variable. See that file for comments.
