### ISSUE TITLE
Suggestion: Localization File in Plugin Folder

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [kangarko/ChatControl-Pro#1148]
It is a massive pain atm to edit the locale file, I need to go into jar, edit file, and then upload jar every time a new update comes. Please make this not as much of a pain to do by allowing us to have the locale file in plugins folder than can be reloaded on /chc reload

**Comment by BlackGamer000** [comment]
You don't need to do it. 
Create in your directory called exactly "localization" and then reload with /chc reload.

**Comment by kangarko** [comment]
Please read https://github.com/kangarko/ChatControl-Pro/wiki/Localization and save yourself from pain
