### ISSUE TITLE
Dropped support for SimpleClans

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1149]
This isn't abandoned and massively used, so now when I update im going to have to change my entire formatting? OH and you are forcing me to update because you changed the class names to this "MineAcademy" what the hell is happening?

**Comment by kangarko** [comment]
Hi there,

I understand it is inconvenient to switch your placeholders, and I apology for that. You can install PlaceholderAPI and the SimpleClans variables from there instead.

As I explained on the forums, MineAcademy is my company that will licence and sell all of the premium resources and more. Nothing to worry about here. Our mission is to hire team members to reduce ticket response delays and provide long-requested features.
