### ISSUE TITLE
Rules not applying

### ISSUE THREAD

**Issue by cmisztur** [kangarko/ChatControl-Pro#115]
With the default configs, should swears be removed from chat?
Ads are not removed either.
Am I missing something simple?

- CraftBukkit version git-Spigot-850da7e-fd8d8cf (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
- ChatControl v7.0.28
- 6 plugins: BukkitCompat, ChatControl, dynmap, WorldEdit, ProtocolLib

The only warning/error during startup (through MCMA) is:
- WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream

Thanks
Chris

**Comment by EvilOlaf** [comment]
You can enable debug mode within CHC config to see if the rules are parsed at all.

**Comment by cmisztur** [comment]
I enabled Debugger: Global: true.
I do not see any console or log output when trying to be offensive.

http://pastebin.com/PpiCQp8c

**Comment by EvilOlaf** [comment]
When enabling debug mode and you do a `chc reload` all rules are parsed in the console. Are all offensive rules parsed as well?

**Comment by cmisztur** [comment]
Yes, it looks like it. Here is the 'jerk' rule.

[09:18:00] [Server thread/INFO]: ChatControl Rule{
[09:18:00] [Server thread/INFO]: ChatControl     Id = UNSET
[09:18:00] [Server thread/INFO]: ChatControl     Match = '\b(j+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*k+(\W|\d|_)*)',
[09:18:00] [Server thread/INFO]: ChatControl }

**Comment by EvilOlaf** [comment]
When someone tries to type `jerk` in game chat is this parsed by CHC in console?

**Comment by cmisztur** [comment]
no.

10:09:59 AM CONSOLE: [INFO] ChatControl 53 global, 15 chat, 4 command, 2 packet and one sign rule(s) found
10:09:59 AM CONSOLE: [INFO] ChatControl
10:10:03 AM TATODOG: jerk

**Comment by EvilOlaf** [comment]
That's odd. Do you have bypass permission for these or any rules, `*` permission or op status? If so, try to remove and try again.

However may not make any difference as AFAIR CHC always shows matches in console regardless of permissions or op status. It just skips the defined action.

**Comment by cmisztur** [comment]
I am op.
I have not messed with any perms.

**Comment by EvilOlaf** [comment]
`Op_Has_Permissions: true` is the default setting. Either remove your op status or set this to `false`.

**Comment by cmisztur** [comment]
Ahhh... I de-opped myself.  It works!

`10:14:56 AM CONSOLE: [INFO] TATODOG issued server command: /deop TATODOG
10:14:56 AM TATODOG:: De-opped TATODOG]
10:14:58 AM CONSOLE: [INFO] TATODOG issued server command: /op
10:14:58 AM CONSOLE: [INFO] *--------- Rule match (command) for TATODOG --------- ID /op
10:14:58 AM CONSOLE: [INFO] MATCH: Rule{
10:14:58 AM CONSOLE: [INFO] Id = /op
10:14:58 AM CONSOLE: [INFO] Match = '^/op\b',
10:14:58 AM CONSOLE: [INFO] Bypass With Perm = 'chatcontrol.bypass.rules',
10:14:58 AM CONSOLE: [INFO] Warn Message = 'Yes, we are giving away OPs. Seriously, what did you expect?!',
10:14:58 AM CONSOLE: [INFO] Deny = true
10:14:58 AM CONSOLE: [INFO] Log = true
10:14:58 AM CONSOLE: [INFO] }
10:14:58 AM CONSOLE: [INFO] CATCH: /op
10:14:58 AM CONSOLE: [INFO] Original message cancelled.
10:15:00 AM Server: Saving world data. Expect lag for a short while.
10:15:00 AM CONSOLE: [INFO] Saving...
10:15:00 AM CONSOLE: [INFO] Saved the world
10:15:00 AM Server: Save Complete
10:15:03 AM CONSOLE: [INFO] *--------- Rule match (chat) for TATODOG --------- ID UNSET
10:15:03 AM CONSOLE: [INFO] MATCH: Rule{
10:15:03 AM CONSOLE: [INFO] Id = UNSET
10:15:03 AM CONSOLE: [INFO] Match = '\b(j+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*k+(\W|\d|_)*)',
10:15:03 AM CONSOLE: [INFO] }
10:15:03 AM CONSOLE: [INFO] CATCH: jerk
10:15:03 AM CONSOLE: [INFO] ChatControl Set TATODOG's 'swear' points from 0 -> 2
10:15:03 AM CONSOLE: [INFO] FINAL: *****
10:15:03 AM TATODOG: *****`

**Comment by EvilOlaf** [comment]
:+1:

**Comment by kangarko** [comment]
Many thanks @EvilOlaf for the assistance!
