### ISSUE TITLE
Private Message Reply (/r) isn't registering

### ISSUE THREAD

**Issue by eightbitx** [kangarko/ChatControl-Pro#1150]
When I send a message to someone I cannot use /r to send them another message. It only works after they have messaged me.

Here is my config: https://pastebin.com/EaVJjaPe

ChatControl Version: 8.0.1

Paper version: git-Paper-614

Note: This issue appeared after enabling Bungee for private messages. When Bungee is disabled, it works as expected.

**Comment by kangarko** [comment]
This seems bungee-related and upon further investigation turns out to be bigger than I expected. Currently I don't have the time to fix that so I just put this into roadmap.

**Comment by kangarko** [comment]
Reopened due to request.

**Comment by kangarko** [comment]
Fixed.
