### ISSUE TITLE
Incompatible with Item2Chat

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [kangarko/ChatControl-Pro#1152]
When trying to do #hand to show the item in chat, this shows up: #hand☐Hellcode48 (the box shows a em in it)

I tried setting listener priority of Formatter and reloaded plugin through plugman to each setting (Lowest, Low, Normal, High, Highest) but to no avail.

Plugin Page: https://www.spigotmc.org/resources/item2chat.33622/

**Comment by xH3LLRAIZ3Rx** [comment]
Seems like it might be a issue with the item2chat plugin itself...

**Comment by kangarko** [comment]
This is already planned: https://github.com/kangarko/ChatControl-Pro/issues/1130
