### ISSUE TITLE
Tab Complete for Bungeecord

### ISSUE THREAD

**Issue by eightbitx** [kangarko/ChatControl-Pro#1154]
Hi, I'd like to suggest adding tab-complete for bungeecord messaging. I previously assumed we didn't have it because it wasn't possible, but I noticed that bungeecord's built in commands (like /find) have tab-complete, so I assume there is an API that can be used by plugins too.

ChatControl version: 8.0.3
Paper version: git-Paper-616
BungeeControl version: 2.0.0
Waterfall version: (drop and replace for Bungeecord) "git:Waterfall-Bootstrap:1.13-SNAPSHOT:52eea2d:274 by md_5"

**Comment by kangarko** [comment]
Hey,

apologies, this is currently not planned due to amount of works on other projects and already a full roadmap. We may return to this in the future though.
