### ISSUE TITLE
Need more wiki page!

### ISSUE THREAD

**Issue by djacks6278** [kangarko/ChatControl-Pro#1155]
i trying to change my message.yml
but message file dosen't have wiki page
so i need that wiki

and some more future need!

i think some message can show action bar or title , subtitle 
not only chat message!

if u can try this it's be nice!

**Comment by kangarko** [comment]
What's the problem with messages.yml?

**Comment by djacks6278** [comment]
@kangarko i don't know what i can use in message.yml
so we need wiki for message
ex)
can i use action on notify in message? or some announce?
what is Broadcaster mode?
can use Broadcaster conditions?
what is "Message : default" mean?
what is
  Discord:
    Enabled: true
    Channel: myDiscordChannel
?
some else ...
and how can i find original message.yml in wiki?
that's it
we need help!

**Comment by kangarko** [comment]
Hey,

to get the comments on how to use these options, simply open ChatControl.jar with winrar or winzip and read messages.yml from there - do not modify it, only read it, it will contains comments.
