### ISSUE TITLE
Compatible with other chat format?

### ISSUE THREAD

**Issue by climeno** [kangarko/ChatControl-Pro#1157]
Hi!

I want to buy the plugin but i want to know if it is compatible with other plugins that add some thing to the chat format, for example using marriage master, it adds a hearth before the nick of the player, and in essentials chat format i can custom my chat, i want to know if it is replaced with other format of ChatControl

**Comment by kangarko** [comment]
Hey,

some plugins are compatible some are not, you can edit priority (the order) of the chat event we listen on, making most plugins compatible. In the event there is a fatal incompatibility I will refund you the money if you report within 7 days of your purchase and we are not able to solve it.
