### ISSUE TITLE
 Option to send all !text to Bungee_Chat instead of Global_Chat

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/ChatControl-Pro#1159]
Please add some switch to send all !text to Bungee_Chat instead of Global_Chat. I used custom rules for that but this is a common feature and it's must be available by default without hacky ways.

**Comment by kangarko** [comment]
Great suggestion indeed. Currently I'm too busy so I only caught up and clarified the naming convention between global and bungee chat. In a future update I will enable you to configure the prefix for bungee chat and global chat separately.

**Comment by ArtNRG** [comment]
I have seen the 8.0.9 changelog. Please clarify if it's possible now to set up sending !test into the bungee chat?

**Comment by kangarko** [comment]
No, not yet, we will implement it when we have time for it in the future

**Comment by kangarko** [comment]
Added, see the next changelog :)
