### ISSUE TITLE
Ignore_Commands Sub command arguments

### ISSUE THREAD

**Issue by baticag** [kangarko/ChatControl-Pro#1161]
In handlers we cannot add sub commands whitelist by putting them in Ignore_Commands section of specific handler.

For example: I want to exclude **/clan setrank** <args...> from the handler swear and when I put bolded part in Ignore_Commands section that doesn't work. It works if only **/clan** is put there, but I don't want to exclude whole clan command, but only specific sub command of it.

**Comment by kangarko** [comment]
Thanks, from now on we evaluate these messages as "starts with" instead of "equals first argument" so that should start working. Please update.
