### ISSUE TITLE
messaging issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1162]
I cant remember the setting in console but we have it set so when you /msg a player it sets them as your recipient. However this doesn't seem to work anymore in 8.0.7.

https://gyazo.com/cf157acdf245591155596a30d3eb6c9d

**Commands:**
- /msg [playername] test
- /r test2

**Comment by kangarko** [comment]
Seems like your PM's are disable in ChatControl, that's Essentials like formatting. Ensure you have Private_Messages.Enabled to true in settings.yml. Also make sure you have the two following options in that section:

![a](https://i.imgur.com/SfVymfq.png)

Keep in mind this feature does not work over bungee.

If still does not work, set Debug to [pm] in settings.yml, restart and report console output. I will read your message below.
