### ISSUE TITLE
[Request] CHC & BC: Auto Tab Completion

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1163]
BungeeControl and Chatcontrol suggests several commands even though players do not have the permission to execute them or the function is disabled.
BungeeControl:
```
- bc
- bcontrol
- bungeec
- bungeecontrol
```
ChatControl:
```
- ch
- channel
- admin
- global
- a
- g
- nobc
- nobroadcast
- notc
- togglebc
- togglebroadcast
- toggletm
```
Would it be possible to not suggest commands for players without the proper permission?

**Comment by LogGits** [comment]
I would also like this. It would also be nice if tabcomplete for /msg tabcompletes for players on other servers on the bungee network.

e.g. if i am on one server and I type `/msg [player on another server on the bungee network]`, it should start to tabcomplete the users name. You can use

**Comment by kangarko** [comment]
Hey, at present this is not possible with the current system and it would take long time to rewrite it from scratch, we'll be focusing on the other suggestions for now, thank you for your understanding

**Comment by BenjaminHoegh** [comment]
will be nice
