### ISSUE TITLE
Question Color Format

### ISSUE THREAD

**Issue by xGlenor** [kangarko/ChatControl-Pro#1165]
Hello, I have a problem! How the permissions chatcontrol.chat.format.color.{Color} work?

**Comment by GeertBraakman** [comment]
if you give a player the permission `chatcontrol.chat.format.color.white` they will be able to select that color for their chat. 
they have to do `/chc color` to open the GUI to select it which requires the permission `chatcontrol.commands.color`

**Comment by xGlenor** [comment]
OK, 
I set myself the default one as green and it does not work

**Comment by xGlenor** [comment]
Ok, I gave permission to bad,
Everything is working
