### ISSUE TITLE
Issue with nation party

### ISSUE THREAD

**Issue by GeertBraakman** [kangarko/ChatControl-Pro#1166]
Hello, I got an issue with creating nation chat channel. The party option doesn't work for nations. For towns it works completely fine but when I create a nation channel and chat in it everyone in that channel is able to see my message, even tho they are not in my nation. I also tested it with players that are not even in a nation. It will also send the message while not being in a nation at all, not like town where you will get an message when your not in a town. I hope this will get fixed soon. :)

Geert Braakman

**Comment by kangarko** [comment]
Hi,

please update to the next version, set Debug to "[channel-party, towny]" in settings.yml, and post me the console output when it happens.

**Comment by GeertBraakman** [comment]
Ok here are the results, don't know if you can do anything with it because it doesn't look really impressive.

## Console 
![image](https://user-images.githubusercontent.com/36223190/57038212-b4a34980-6c59-11e9-954d-6472c2317c22.png)

## x313
![image](https://user-images.githubusercontent.com/36223190/57038245-cdabfa80-6c59-11e9-8c56-f7a08a23452e.png)

## y313
![image](https://user-images.githubusercontent.com/36223190/57038309-ecaa8c80-6c59-11e9-8308-e82b7a249785.png)

### Also some extra towny information
#### x313
![image](https://user-images.githubusercontent.com/36223190/57038347-ff24c600-6c59-11e9-8b57-fa81a7c5d3c8.png)
![image](https://user-images.githubusercontent.com/36223190/57038368-0d72e200-6c5a-11e9-8a34-c39ec15485fa.png)

#### y313
![image](https://user-images.githubusercontent.com/36223190/57038417-1ebbee80-6c5a-11e9-978b-c6d39e6a771b.png)
![image](https://user-images.githubusercontent.com/36223190/57038423-24b1cf80-6c5a-11e9-8eca-7cafb7527d18.png)


### And the configuration
#### Channels.yml
![image](https://user-images.githubusercontent.com/36223190/57038470-40b57100-6c5a-11e9-88e5-2cea35b9f8f1.png)

I hope you can do something with this.

**Comment by kangarko** [comment]
Hi, sorry for delay, the /tc message worked just fine did not it? It removed the other player.

I am curious were they any console message for the /nc message? The image seems cut.

**Comment by GeertBraakman** [comment]
TC worked fine, but nc did nothing, I didn't cut the image.
Here is the full image
![image](https://user-images.githubusercontent.com/36223190/57356770-982f7180-7171-11e9-8df9-4bfef4e847d6.png)
as you can see it doens't do anything party related.

**Comment by kangarko** [comment]
That's very odd, seems the party was not even loaded? Oh I noticed you had 'party' and not 'Party' with a capital P. These maps are case-sensitive in Java, unlike the other settings key you're used to!

Let me know if that solved the problem, if not I updated CHC with more meaningful debug messages in Debug option [channel-party] so just update and report the console output :)

**Comment by kangarko** [comment]
I just coded that in, the program now takes in keys, case insensitive.

**Comment by GeertBraakman** [comment]
Yess that was the issue, didn't notice myself xd. 

Another small question, could you add the option to customize the message that is giving. Because currently it gives this message: 
![image](https://user-images.githubusercontent.com/36223190/57392955-609ce580-71c2-11e9-81b4-57ab3bf78e7d.png)
while trying to use nation or town chat while not being in a town. Or just make a message based on the party you try to talk to.

**Comment by kangarko** [comment]
You can use localization file to customize this message. See Wikipedia on this and look for the message labeled:

![a](https://i.imgur.com/5jh9sGa.png)

**Comment by GeertBraakman** [comment]
Oke, thanks for the help
