### ISSUE TITLE
[Feature Request] Silent/Ghost muting

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#1169]
Hello there!

This is a good way to punish players. How this works is you are muting someone without them noticing. They can still type and see messages in chat, but nobody else will be able to see their message. You are essentially adding them to the ignore list of every single player on the server.

Is this feature available in the plugin as of now, or could it be added in the future?

Thanks for your time!

**Comment by kangarko** [comment]
Hi,

thank you, awesome suggestion, we have this in our roadmap and I prioritized that up.
