### ISSUE TITLE
Global /afk?

### ISSUE THREAD

**Issue by poblabs** [kangarko/ChatControl-Pro#117]
I tried to ask this question on the forums but was met with some... differing opinions on the matter from the community. 

Nevertheless, I thought I'd ask here. Is there a way to hook into the automatic AFK from Essentials or the /afk command to globally broadcast when a user is AFK?

**Comment by kangarko** [comment]
Just for the reference, I shall copy my answer from the forums herein:

The following filter with two packet rules should work:

```
match ^\* (.*) (is now AFK\.)$
then bungeeconsole alert $1 is now gone!
then deny

match ^\* (.*) (is no longer AFK\.)$
then bungeeconsole alert $1 is here!
then deny 
```

**Comment by kangarko** [comment]
If you have any more questions, feel free to comment below.
