### ISSUE TITLE
Asynchronously request

### ISSUE THREAD

**Issue by Heliosard** [kangarko/ChatControl-Pro#1170]
Hello,

I would like to remind you of an important subject.

Currently, chat and regex management is synchronous. It would be wise to manage these two parts asynchronously. The chat is basically managed in this way in minecraft... Why did you switch it to synchronous? The optimization is catastrophic on large servers.

Thank you in advance for taking the time to seriously consider my request.

**Comment by kangarko** [comment]
Hi,

we listen to the AsyncPlayerChatEvent that is asynchronous. There, all regex processing as well as variable replacing is done. It should not delay the other happenings on your server.

Matej
