### ISSUE TITLE
(SUGGESTION) Item In Hand Info

### ISSUE THREAD

**Issue by johnsoncui02** [kangarko/ChatControl-Pro#1175]
add a function that would allow players to type [i] and it would display the item name and if player hovers over the chat it would show information.

**Comment by TeamPositiveYT** [comment]
I second this!

**Comment by kangarko** [comment]
Thanks, that was already suggested many times and is our top most priority, however at present we're busy with building training programs outside of Spigot so I personally can't give you an ETA. This will definitely come however.
