### ISSUE TITLE
setting up per world chat formats

### ISSUE THREAD

**Issue by TimeSlinky** [kangarko/ChatControl-Pro#1176]
I am having the hardest time setting up per world chat formats. I have read through the documentation and keep getting errors using the code from it. 

I tried the steps from [here](https://github.com/kangarko/ChatControl-Pro/wiki/Per-World-Chat-Formatting) in per world chat formatting but i keep getting an error with the interactive format. Im using group manager for my permissions. Im just pretty lost on how to set it up. 

I tried adding this to the settings.yml in the groups section

Groups:
  Enabled: true
  Group_List:
    factions:
      Interactive_Format: '{faction}{pl_prefix} {nick}{pl_suffix}&r: {message}'

And then this in the group manager permissions section for the world factions

permissions:
    - chatcontrol.group.factions

**Comment by kangarko** [comment]
Hi,

Apology for a late reply.

What's the error you're getting?

**Comment by TimeSlinky** [comment]
Hi there, the issue I think is with the interactive formate I’ve put in the groups section. I can edit this in a little with the exact error from console (not sure how I forgot to put it in OP). I’ll have to get to my computer and recreate the issue. But I get an internal error whenever I put the format under the group section as instructed by the steps I liked to in the OP.

**Comment by kangarko** [comment]
Please post me that error.

**Comment by TimeSlinky** [comment]
Sorry, I had to leave for a couple days for personal reasons. I found a fix for the issue though. It gave me the answer in the error message in console. On the groups section of the wiki it says 
`Groups:
  List:    
    guest: 
      Channel_Limit: 1
      Message_Delay: 4
    vip: 
      Message_Delay: 1
    staff: 
      Message_Delay: 0
      Interactive_Format: Staff_Format`

The console says Report / Unknown group option ' Interactive_Format'
However, it says after that Chat_Format is a valid option and that seems to fix the format and includes the interactive part.

I am also having an issue getting the permissions to work properly. I dont get an error other than permission denied. But it seems as though all the permissions including permission for `/chc reload` are not working without any error. I am using Group Manager.

**Comment by kangarko** [comment]
Hi,

can you please upload me your settings.yml to pastebin.com?

**Comment by TimeSlinky** [comment]
https://pastebin.com/4WSCyaxx

**Comment by kangarko** [comment]
Your file loads for me just fine.

The error says it's 'Interactive_Format', please change that to 'Chat_Format' and it should be fine.
