### ISSUE TITLE
[request] Private Message last message reply timeout

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1178]
A very long time ago, I requested and got implemented a system into EssentialsX that added a timeout to your /r when talking to people in private message.

The biggest annoyance when getting into a conversation with someone is having someone message you and your /r gets taken over! This is beyond frustrating. If someone opens up a dialogue you want to be able to reply as fast as possible, which works with /r message, no having to toggle something, no having to put in their username, just /r. when you are in a conversation you do not want anyone to break up your conversation flow.
This is why I requested EssentailsX implement `last-message-reply-recipient-timeout: 180` which they did as its very handy.
I still cant move from Essentials message as this feature is not in chatcontrol pro, I have requested it in the past but cant find what I called it!
I can see Register_Reply_To_Self and Register_Reply_To_Receiver, but these are perminant, there is no timeout, a timeout means that you dont have to put in a username, it means that after your conversation your /r gets re-opened up to the next person that will message you, so you dont have to do anthing but use /r.
This works very well.

These are the settings from EssentailsX

```
# Changes /reply functionality. If true, /r goes to the person you messaged last, otherwise the first person that messaged you. 
# If false, /r goes to the last person that messaged you.
last-message-reply-recipient: true

# If last-message-reply-recipient is true, this specifies the duration, in seconds, that would need to elapse for the 
# reply-recipient to update when receiving a message.
# Default is 180 (3 minutes)
last-message-reply-recipient-timeout: 180

```

**Comment by kangarko** [comment]
If we would be chatting, and someone else would message you, the reply would not get changed.

However, if we would stop chatting for let's say 3 minutes, and someone else would message you, the reply would get changed since it is over the 3 minutes threshold.

Is that what you're asking for?

**Comment by FrozenBeard** [comment]
Yup, that's it.

**Comment by kangarko** [comment]
Added. I've tested it, but if you experience any unusual behaviour set Debug to [pm-replytimeout] and report the console messages.

**Comment by FrozenBeard** [comment]
Right, got to test this morning, the timer seems to work from some quick testing.

1) If I start a new conversation with someone while in the timeout period, it doesn't switch my /r to the new person I have started  conversation with, if you start a new conversation with /msg username your /r should go to that conversation, so you are always in control of your msg.

**Comment by kangarko** [comment]
Do you have Register_Reply_To_Self enabled?

**Comment by FrozenBeard** [comment]
Yup

**Comment by kangarko** [comment]
Try to set Debug to [pm] and look out for console messages and post them here please ;)
