### ISSUE TITLE
Suggestion: Private-messages working with essentials nickname

### ISSUE THREAD

**Issue by GeertBraakman** [kangarko/ChatControl-Pro#1179]
Hello,
I have a suggestion for the private message system. Essentials has the feature to message people by typing there nickname. Could you add this into chatcontrol? With support for essentials nickname?

**Comment by kangarko** [comment]
Hi,

thank you for your suggestion. At present our roadmap is pretty much full but you may come back in the summer and re-suggest this once we have a dev team in place. Thanks!
