### ISSUE TITLE
Color doesn't appear on match (Upgrading from ChatControl to ChatControl Pro)

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl-Pro#118]
Hello, I had ChatControl free with these config in chat.txt:

match stars|star
then replace &e✯&f

match <3|hearts|heart
then replace &d❤&f

When I used to type in chat: star heart
The result was: &e✯  &d❤

But now in the ChatControl Pro, the result in chat is: &r✯  &d❤ (it doesn't catch the color of the star)
This occurs with the rest of emojis I have, when I write some words in chat, only 1 emoji has color.

Thanks.

**Comment by kangarko** [comment]
Confirmed. Will look up the solution at my earliest possibility.

**Comment by kangarko** [comment]
Sorry for the delay.

A new feature in ChatControl Pro was introduced that, by default, removes the color from the processed message. This is to lower the rate of false positives, and, decrease the bypass range by players inserting colors into their messages so they are ignored by filters.

Please navigate into your **settings.yml** and set **Regex_Strip_Colors** to **false**. I have tested it with that option disabled and the color has remained.
