### ISSUE TITLE
Trident and dolphin death messages

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#1180]
The trident is a popular toy in version 1.13. For it, one would find plenty of funny death messages. Unfortunately, it is currently only counted as a projectile. Would be cool if you could add it!

Paper 1.13.2 - 622
ChatControl 8.0.11

**Comment by kangarko** [comment]
Thanks, noted, however at present we are pretty busy with training courses so I am not sure when we can get to it.

**Comment by kangarko** [comment]
And for dolphin:

It would be really cool if you could set up a death message for dolphin death. The cute little animals are popular and dangerous!

Paper 1.13.2 - 622
ChatControl 8.0.11

**Comment by kangarko** [comment]
Pulled into roadmap
