### ISSUE TITLE
Anti unicode characters filter it block also smileys

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1182]
Using the rule:
match [^\u0000-\u007F]+
then deny
then warn You can't use this!

on chatcontrol 7.9.31 it allow default chatcontrol "smiley" to be used
instead the new versions of chatcontrol now it block all these smileys (the ones on chat.txt)
trying using ignore into the rule don't fix the problem, so i am sure that it was a breaking change

**Comment by kangarko** [comment]
You need to put this rule above the smileys. Also update to the latest version.

![a](https://i.imgur.com/2AiQ42e.png)
