### ISSUE TITLE
(QUESTION) Player Chat Message On Console

### ISSUE THREAD

**Issue by johnsoncui02** [kangarko/ChatControl-Pro#1189]
My current situation is that when players chat through using  chatcontrolpro it doesn't recognize player message typed on the console, therefore it won't show player message that they typed. Is there a way to enable this option?

**Comment by kangarko** [comment]
What do you mean? If the console sends a /tell private message it does not show players that it was the console who sent it?

**Comment by johnsoncui02** [comment]
I meant say if 
Player1 : hi
Player2: suh dude

If the players typed these messages it wouldn't display it on the console. Which I want to in order to keep things regulated when I'm not available ingame.

**Comment by kangarko** [comment]
Post me your entire ChatControl/ as a ZIP please

**Comment by johnsoncui02** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3209032/ChatControl.zip)

**Comment by kangarko** [comment]
Hey, sorry I was not able to find the problem yet.

What plugins are you having on your server?

Also please try changing Listener_Priority.Formatter to LOWEST or HIGHEST to see if that solves the problem.

**Comment by johnsoncui02** [comment]
that seems to have worked. thanks.
