### ISSUE TITLE
Unable to forbid chat colors with /me

### ISSUE THREAD

**Issue by TeamPositiveYT** [kangarko/ChatControl-Pro#1190]
Players with donator ranks have the ability to change their chat colors.
Whenever they type /me TEXT HERE, it turns everything people - except their text.

How do I fix this and make it all purple?

Heres my code in formatting.yml:
![FormatCode](https://gyazo.com/259d412960c58b2897968938ecc3cdfc.png)

This is what it looks like in game:
![2019-05-15_01 10 47](https://user-images.githubusercontent.com/50473750/57752513-12e71800-76af-11e9-9b4c-fc959df36402.png)

**Comment by kangarko** [comment]
Hi,

just checking up, have you enabled the Me command in settings.yml?

I assume so, now make sure the player haven't changed their color via '/chc c' menu, otherwise their color will get applied to their me command.

**Comment by TeamPositiveYT** [comment]
Yes, I have changed my color via '/chc c'. Is there a work around to change it and make it ALL purple, though?

**Comment by kangarko** [comment]
Hi, sorry, at present that's not possible however I've put this into the roadmap for the future :)
