### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to ChatControl v8.1.3

### ISSUE THREAD

**Issue by TeamPositiveYT** [kangarko/ChatControl-Pro#1191]
I am not able to use cursing/advert censorship.
I keep getting errors. I even rolled back the settings and it still gives me the error.
"[Wed, 15. May 2019 15:48:32 UTC ERROR] Could not pass event AsyncPlayerChatEvent to ChatControl v8.1.2"

Console: 
![CONSOLE](https://i.gyazo.com/b9f8cd4e927baa5a96544d1fde3e74de.png)

**Comment by TeamPositiveYT** [comment]
The errors seems to be the same as:
https://github.com/kangarko/ChatControl-Pro/issues/779
https://github.com/kangarko/ChatControl-Pro/issues/724
https://github.com/kangarko/ChatControl-Pro/issues/715

**Comment by kangarko** [comment]
Hi,

the three error you've posted are different. Yours relates to outdated Spigot build. I recommend upgrading to the latest PaperSpigot.
