### ISSUE TITLE
ERROR prefix when putting a ! in front of the chat message

### ISSUE THREAD

**Issue by Sti-jn** [kangarko/ChatControl-Pro#1194]
We are on paper 1.13.2 build 622 and are on Waterfall version git"Waterfall-Bootstrap:1.14-SNAPSHOT:2afc278:283 
We use bungee cord but disabled syncing normal chat across servers. We are on version 8.1.3 this issue is also present on 8.1.2 but not on 8.1.1. 
When a player sends a message with the ! prefix it sends it to all servers with a red prefix that says ERROR. No errors appear in console.
![image](https://user-images.githubusercontent.com/39404504/57855486-17b0e680-77eb-11e9-8e79-187af9b52bf1.png)
![image](https://user-images.githubusercontent.com/39404504/57855502-213a4e80-77eb-11e9-850a-891bff7545d6.png)
![image](https://user-images.githubusercontent.com/39404504/57855540-31eac480-77eb-11e9-8b2a-59fb80a42482.png)

**Comment by kangarko** [comment]
Does it prints out ERROR as well when you use /chc bc ?

**Comment by Sti-jn** [comment]
If I do /chc bc it just tells me I don't have perms for it since non of us on this server do.
When I give myself chatcontrol.* and do it it uses the ERROR prefix as well. It seems like the shortcut is somehow bypassing the permissions for it?

**Comment by kangarko** [comment]
Hi,

no, we enable bungee chat if you have it enabled by default or the player has the permission. If you have it Enabled_By_Default than we allow it regardless of the permission for "!".

For the ERROR, set your Server_Name to a unique name in settings.yml

**Comment by Sti-jn** [comment]
As you can see from the third screenshot I send we have enabled by default set to false. Players without permission are able to use ! anyways.

**Comment by kangarko** [comment]
Thanks, I will fix that
