### ISSUE TITLE
Unknown Server (BungeeControl)

### ISSUE THREAD

**Issue by SpencerSharkey** [kangarko/ChatControl-Pro#1195]
All my cross-server chat shows up w/ Unknown Server. I had it working after setting all the `server-name` fields on my servers but I believe a later update broke this feature.

**Comment by kangarko** [comment]
Hi,

Minecraft broke that feature, sadly. Please configure each server name in your settings.yml now:

![a](https://i.imgur.com/i9CA0wH.png)

**Comment by x1p** [comment]
The issue seems to be related to ChatControl v 8.1.3.
Version 8.0.11 did not had this issue.

**Comment by kangarko** [comment]
We had to change things to update to 1.14. Now you must explicitly specify the server name since we no longer can use this from server.properties
