### ISSUE TITLE
{nick} still not working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#12]
On the latest version 6.8.3 the nickname is still not working from essentialsX: http://prntscr.com/aif53f

**Comment by EvilOlaf** [comment]
The nick variable is deprecated AFAIK. There are others now. I think there was a hint at the changelog at the spigot page. Just take a look there.

**Comment by Sikatsu** [comment]
The nick variable stayed the same but the priority has changed from Nicky > Essentials > Bukkit.
However, on the previous version (6.8.2) the nicknames didn't work and instead showed the player name and using 6.8.3 it shows {nick} for everyone.

**Comment by EvilOlaf** [comment]
Found it.  https://github.com/kangarko/ChatControl-Pro/issues/4

**Comment by kangarko** [comment]
I reconsidered it **not** to split it. But I have split it and forgot to tell about it :tired_face: 
Will be fixed.

Sikatsu is right about the priority.
