### ISSUE TITLE
JSON doesnt work

### ISSUE THREAD

**Issue by Ghastlegion2** [kangarko/ChatControl-Pro#120]
`      - '[JSON]["",{"text":"«---------------------------------------»\n","color":"red","bold":true,"strikethrough":true},{"text":" Server Rules","color":"red","bold":true,"strikethrough":false},{"text":" ➣\n","color":"gold","bold":false},{"text":"  By joining this server you automatically accept\n  the &6(Terms & Services)&7 also known as","color":"gray","insertion":"«---------------------------------------»"},{"text":" T&S Link\n","color":"aqua","insertion":"«---------------------------------------»","clickEvent":{"action":"open_url","value":"https://www.ghastlegion.com/threads/general-server-rules.7/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"&bT&S Link"}]}}},{"text":"  for an complete list.\n","color":"gray","insertion":"«---------------------------------------»"},{"text":"«---------------------------------------»","color":"red","bold":true,"strikethrough":true}]'`
(This is normally one line)
Im using the newest version

**Comment by kangarko** [comment]
Message broadcaster is a kind of a special case. You need to set the **Broadcaster.Prefix** to **'[JSON]'**, and then only place the json directly without the [JSON] prefix in the message list.

**Comment by Ghastlegion2** [comment]
dude. whats broadcaster.prefix?

**Comment by Ghastlegion2** [comment]
you are allowed to give a example?

**Comment by Ghastlegion2** [comment]
your example doesnt work

**Comment by kangarko** [comment]
You can find an example in
https://github.com/kangarko/ChatControl/wiki#json-in-automatic-message-broadcaster-in-messagesyml

**Comment by Ghastlegion2** [comment]
"your example doesnt work"
again it doesnt work

**Comment by kangarko** [comment]
Please post me your messages.yml as it is now with the broken json added.

**Comment by Ghastlegion2** [comment]
Why dont you try it yourself? with the newest version and then send me your messages.yml

**Comment by kangarko** [comment]
Here is an example where I use your message.
http://pastebin.com/0gWVUMdR
