### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by GeertBraakman** [kangarko/ChatControl-Pro#1201]
Hello, 
I have a request for the API. I was checking it and i missed the method `isIgnoringBroadcast()`. There is a method `setIgnoringBroadcast()`. but not the getter. Can this be added please. 

![image](https://user-images.githubusercontent.com/36223190/58037799-87e2a380-7b2e-11e9-9e72-36c706de745b.png)

![image](https://user-images.githubusercontent.com/36223190/58037826-9cbf3700-7b2e-11e9-9b5d-f3ba8e27254e.png)

**Comment by kangarko** [comment]
Thanks,

changed to:

isIgnoringTimedMessages
setIgnoreTimedMessages
