### ISSUE TITLE
Ranged channel not working 

### ISSUE THREAD

**Issue by SpartanPride7** [kangarko/ChatControl-Pro#1204]
Hey,

My ranged channel is not working properly. The channel itself is there, but the 100 block range just isn't there. Anyone from any end of the map is able to chat with each other in the ranged channel, even if not less than 100 blocks away. Here are my files:

settings.yml https://pastebin.com/wD0u7hKH
channels.yml https://pastebin.com/5dFZgNmM
formatting.yml https://pastebin.com/vBeYkh1S

**Comment by kangarko** [comment]
Hi,

when you use Linked_Worlds, range is set to the entire world's range. Can you still reproduce this problem removing your linked worlds option?

Just to note, you have channels disabled. Ranged chat from formatting.yml is a standard ranged chat applied for everything.

**Comment by SpartanPride7** [comment]
Yep, that worked! Lastly, I'm trying to hide the join/leave messages when players enter a channel. I hid it in the channels, and then it said also hide it in Localization. Where is that?

I don't think the answer is yes, but is there a way to hide the join / leave for some channels, but keep it on for others?

**Comment by kangarko** [comment]
I believe it's Channels.Join_Other.

No sorry, this message cannot be toggle individually
