### ISSUE TITLE
Suggestion: reorganize configs to have server settings in its own fil

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1205]
Ahoy!

I use chatcontrol across my servers, but keeping configs and rules updated across them all is a bit of a pain, i've recently moved my configs to github so i call pull across servers and included a gitngnore for data and logs and log folder.

The one issue I have is that a lot of server specific settings are in the same file settings.yml.
Most nearly all rules will be the same across servers so this is fine, but in the settings.yml things like:

- Server_Name
- MySQL data

Will change per server, it would be nice to have this server settings in its own file.yml, then I could gitignore it!

Thanks.

**Comment by kangarko** [comment]
Thanks,

synchronizing data over all servers is something we have on our list. At presents it's unplanned since my table is very full, but once we take feature updates we'll implement this as well.

**Comment by kangarko** [comment]
I am sure there are some third party plugins that can do that just fine until than ;)
