### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl

### ISSUE THREAD

**Issue by TakoidGit** [kangarko/ChatControl-Pro#1207]
[log.txt](https://github.com/kangarko/ChatControl-Pro/files/3219795/log.txt)

**Comment by kangarko** [comment]
Due to breaking changes in Spigot, we now require PaperSpigot for packet rules to function properly. There is currently no working solution for this as those changes were made deep in the server itself. PaperSpigot has solved this issues long time ago.

**Comment by TakoidGit** [comment]
I am using PaperSpigot already.

**Comment by kangarko** [comment]
Thanks for letting me know, have you tried updating ProtocolLib?

**Comment by TakoidGit** [comment]
http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/
Unless there is a beta version I don't know about I think I have the most up to date version. I have been using the Stable Build from the link above that is supposed to work with 1.14+.

**Comment by kangarko** [comment]
Thanks, I opened a ticket on Paper

**Comment by kangarko** [comment]
I believe I solved that issue at the end, please test the next version
