### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to ChatControl v8.1.5

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#1208]
Getting the error below when running a command from the rules.

https://pastebin.com/yTJyzsvS

Server: git-Spigot-03bd4b0-17da342 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

**Comment by TeamPositiveYT** [comment]
I have the same issue.

Server: Paper-1.14.1-Build 43

**Comment by kangarko** [comment]
Due to breaking changes in Spigot, we now require PaperSpigot for packet rules to function properly. There is currently no working solution for this as those changes were made deep in the server itself. PaperSpigot has solved this issues long time ago.

@TeamPositiveYT please update your Paper

**Comment by AmazedMender16** [comment]
@kangarko any idea if it will ever be fixed in spigot?

**Comment by TeamPositiveYT** [comment]
I use PaperSpigot... Build 51

**Comment by TeamPositiveYT** [comment]
@kangarko

**Comment by kangarko** [comment]
Hi, this will get solved in the next version

**Comment by TeamPositiveYT** [comment]
It works! Thanks <3
