### ISSUE TITLE
Could not pass event InventoryClickEvent to ChatControl v8.1.5

### ISSUE THREAD

**Issue by TeamPositiveYT** [kangarko/ChatControl-Pro#1209]
I tried adding a rule for Voting Tickets in items.txt

`match \b(v+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*i+(\W|\d|_)*n+(\W|\d|_)*g+(\W|\d|_)*)
then warn This item cannot be include 'Voting' in its name.
then deny`

And I get this error:
https://pastebin.com/nANg5qY7

**Comment by kangarko** [comment]
Due to breaking changes in Spigot, we now require PaperSpigot for packet rules to function properly. There is currently no working solution for this as those changes were made deep in the server itself. PaperSpigot has solved this issues long time ago.

**Comment by TeamPositiveYT** [comment]
Well, I am currently using PaperSpigot
`29.05 02:46:43 [Server] INFO This server is running Paper version git-Paper-50 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)`

**Comment by TeamPositiveYT** [comment]
@kangarko

**Comment by kangarko** [comment]
Should be fixed in the latest version

**Comment by TeamPositiveYT** [comment]
FIXED!!! :D <3
