### ISSUE TITLE
Not working on 1.10 (paid version)

### ISSUE THREAD

**Issue by Mutim** [kangarko/ChatControl-Pro#121]
I've seen on the spigot site, that this version was tested on 1.10. I plugged this in the way i saw Koz4Christ explain (everything worked for him, but on different version) When I type in chat /chc I get no message, no "Unknown Command" message, no "no perms" message. So, this tells me that it's being read, just not registered? I'll provide any logs you need. Please help. I have paid for the full version, so expediency is obviously expected. Thank you!

**Comment by EvilOlaf** [comment]
Check your console if the command has been recognized. 
Also check if the plugin has been loaded at all. If in doubt post a full startup log here. 
Also tell us which version of CB/spigot or whatever you are using as well as the tested CHC version. Keep in mind that "latest" is not a useful answer. Use /version if in doubt.

**Comment by gerardvanschip** [comment]
Easiest way to see if its the plugin or permissions is to OP yourself. If OP can run the command it's a permission issue, if OP cant then there is something else wrong. Also check if you have another plugin with the same command. I had this in the past with HeroChat and CreeperHeal which both used the /ch shortcut.

**Comment by kangarko** [comment]
Unless the OP provide a valid startup log or any error log that appears during the server launch, there's little I can do. Also please do not use plugin reloaders as they do not work.

**Comment by kangarko** [comment]
Closing. Please comment below if you still having issues.
