### ISSUE TITLE
Error for updating???

### ISSUE THREAD

**Issue by cheesepufftyler** [kangarko/ChatControl-Pro#1210]
27.05 03:00:18 [Server] Server thread/ERROR Could not pass event InventoryDragEvent to MBedwars v4.0.6
27.05 03:00:11 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)
27.05 03:00:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
27.05 03:00:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
27.05 03:00:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
27.05 03:00:11 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008)
27.05 03:00:11 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
27.05 03:00:11 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
27.05 03:00:11 [Server] Server thread/WARN at de.JeterLP.ChatManager.update.Updater$1.run(Updater.java:141)
27.05 03:00:11 [Server] Server thread/WARN at de.JeterLP.ChatManager.update.Updater.read(Updater.java:290)
27.05 03:00:11 [Server] Server thread/WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
27.05 03:00:11 [Server] Server thread/WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
27.05 03:00:11 [Server] Server thread/WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
27.05 03:00:11 [Server] Server thread/WARN java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curseforge.com/servermods/filesrojectIds=65863
27.05 03:00:11 [Server] Server thread/ERROR Error on trying to check remote versions. Error: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.curseforge.com/servermods/filesrojectIds=65863
27.05 03:00:10 [Server] Server thread/ERROR MBedwars is currently using a deprecated method to hook into PlaceholderAPI. Placeholders for that plugin no longer work. Please consult [Marcely1199] and urge them to update it ASAP.

**Comment by kangarko** [comment]
This is not from our plugin, please report this to MBedwars
