### ISSUE TITLE
Websites aren’t blocked at all

### ISSUE THREAD

**Issue by TeamPositiveYT** [kangarko/ChatControl-Pro#1212]
If I type “Facebook.com,” for instance, it puts “Facebook com” in chat and doesnt deny it from being posted. Although, if I put an IP address, it works. 

Here is the code:

https://pastebin.com/yVa9fDYG

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com
