### ISSUE TITLE
Warnings on startup

### ISSUE THREAD

**Issue by TufanMeric** [kangarko/ChatControl-Pro#1215]
I get these warnings after plugin creates messages.yml, I think it's because my OS is Turkish. I had this issue a few years ago, I managed to fix it and now I don't know how.

Spigot 1.13.2, Windows 10 Home, Latest plugin version

> [20:35:38 INFO]: Created default file: messages.yml
> [20:35:38 INFO]: [Warning]: The death cause 'Ent?ty_Attack' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Project?le' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Suffocat?on' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'F?re' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'F?re_T?ck' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Drown?ng' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Block_Explos?on' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Ent?ty_Explos?on' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Vo?d' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'L?ghtn?ng' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Su?c?de' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Starvat?on' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Mag?c' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'W?ther' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Fall?ng_Block' is missing from your messages.yml. Ignoring..
> [20:35:38 INFO]: [Warning]: The death cause 'Cramm?ng' is missing from your messages.yml. Ignoring..

**Comment by kangarko** [comment]
Hi,

I am not really sure, it has to be related to how the files are saved, make sure you store them in utf 8 encoding: https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
