### ISSUE TITLE
Error when using some essentials commands (onPacketSending)

### ISSUE THREAD

**Issue by Disorbs** [kangarko/ChatControl-Pro#1217]
So I get some errors with some commands I use like (/echest, /ci) probably more but didn't wanna keep testing.

https://pastebin.com/raw/kTqyFkzg
Chatcontrol pro 8.1.6
Paper spigot 1.14.2
Protocollib 4.5.0 snapshot

**Comment by kangarko** [comment]
Thanks, please update ChatControl
