### ISSUE TITLE
match feature doesn't work with unicode character

### ISSUE THREAD

**Issue by netherstar** [kangarko/ChatControl-Pro#1219]
example:
```
match địt
then replace ***
```
i also tried 
```
match \u0111\u1ECBt
then replace ***
```

**Comment by kangarko** [comment]
Hi, please see https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#rules-dont-work-for-my-non-english-server---i-use-special-characters-but-they-are-not-matched
