### ISSUE TITLE
Just a few issues, I may be missing a permission or config thing. 

### ISSUE THREAD

**Issue by gelsbern** [kangarko/ChatControl-Pro#1220]
Love the plugin, almost perfect. There are 4 things though. and maybe I am missing it. 

1. I would like certain levels of staff to be able to join the local channel to write and spy at the same time. The reason for this is if a new player is unsure how to access one of the global non ranged channels, we want to be able to see it to help them out. I've messed with the permissions and set 
chatcontrol.chat.spyranged and chatcontrol.chat.spy but the local ranged messages don't show unless they join the local channel in spy mode. 

2. I have things set where players join multiple channels in read mode and use aliases to send to those channels. Like /market is an alias for /ch send market <message> to send to the market channel. That way they don't have to remember to switch to a channel. On a couple of the channels they have an option to leave them. (like the market channe), however the alias I have set, still lets them send to that channel even if they aren't joined. Is there a way to block /ch send command if they aren't joined?

3. CCPro ignores every PremiumVanish setting. I have tried listener priorities, but the ranged alert goes away if a vanished person is close by. Would be nice if it would ignore vanished and still say "No one is close enough to hear your chat". Also with PremiumVanish there is an option to require a trailing "/" so that you don't accidentally trigger local chat while in vanish mode, but CCPro still sends the local chat. 

4. And finally, I tried DiscordSrv, I set up all my channels and everything worked great, except, all the local chat was coming to the main global channel in Discord. Is there a setting for a channel to not send to Discord?

All in all a great plugin, I have checked out many, and this one has most of what is needed. Just need to figure these 4 things out to make it perfect for my server.

**Comment by kangarko** [comment]
Hi,

1) You can just use autojoin permissions to join them in the spy mode, and they can always write to that channel using /ch send command. See Channels in our Wiki on how to achieve that.

2) I have added a new option Send_Command_Require_Join to channels.yml, you will be able to toggle that in the next version

3) Sorry, we listen to the "vanished" metadata which is standardized among vanish plugins. Please contact their dev to ask them to add that meta to vanished players.

4) I have added a new Discord option for each channel in channels.yml. Simply write that option under the channel you want to disable discord functionality on, and set it to false.

Thanks for using CCP!
