### ISSUE TITLE
Broadcast MINI lag, bug or mojang limitation?

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#1221]
We noticed a tiny freeze when a broadcast comes up. Does not matter if it's short or long. You especially notice it when running, swimming, on a cart or flying as those all have you go fast in 1 direction. When the broadcast pops up you rubberband back. CPU and Mem usage is low and TPS high so does not seem to be a resource issue.

**Comment by kangarko** [comment]
Please ZIP me your entire ChatControl folder to https://github.com/kangarko/ChatControl-Pro/issues/1221, I'll take a look, seems these issues are similar.

**Comment by gerardvanschip** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3247839/ChatControl.zip)

**Comment by gerardvanschip** [comment]
Why is it closed?

**Comment by kangarko** [comment]
Closed because if two people have similar issues we'll continue the discussion together on a single page for clarify.Closed because if two people have similar issues we'll continue the discussion together on a single page for clarify.
