### ISSUE TITLE
ChatControlPro and NameTagEdit Compatibility Issue?

### ISSUE THREAD

**Issue by bencourtwright** [kangarko/ChatControl-Pro#1227]
I am trying to get ChatControlPro and NameTagEdit to work together. I set the prefix color for the username in NameTagEdit and it works in the tablist but when I say something in the chat the username color stays the same without color.

**Comment by kangarko** [comment]
Hi,

sorry, seems like incompatibility. You can try couple of things:

1. Change formatter priorities as per: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

2. See if PlaceholderAPI supports that plugin's variable, if it does, install PlaceholderAPI and use that pluigin's variable from it in your chat format.
