### ISSUE TITLE
1.14.2 IllegalStateException AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1228]
Internal tears. Trying to convert our server to 1.14.2 by this evening but it looks like chat doesn't want to work. 

Error from chatcontrol log:
https://pastebin.com/krdtTuCD

Error from server log:
https://pastebin.com/vUi9B3xh

no errors on startup
paper 1.14.2 - #67 - latest version

*Removed most of the plugins and was able to recreate. Made sure bungee bridge is up to date as well.

**Comment by Kbryst** [comment]
Note: This was on 8.2.1-BETA
I also tested it with 8.1.7 and got the same thing

**Comment by Kbryst** [comment]
-Rolls face on keyboard-

Changed this from true to false:
Multi_Event: false

fixed it incase anyone has this issue

**Comment by kangarko** [comment]
Thanks for providing a solution!
