### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by cheesepufftyler** [kangarko/ChatControl-Pro#1229]
07.06 23:58:41 [Server] INFO at org.mineacademy.chatcontrol.final. .LpT8.native(SourceFile:196) ~[ChatControl-8.2.1-BETA.jar:?]
07.06 23:58:41 [Server] INFO Caused by: org.mineacademy.chatcontrol.final. .cOm9: Report / Malformed YAML file data.db
07.06 23:58:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1662) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
07.06 23:58:41 [Server] INFO org.bukkit.event.EventException: null
07.06 23:58:41 [Server] Server thread/ERROR Could not pass event PlayerCommandPreprocessEvent to ChatControl v8.2.1-BETA
07.06 23:58:41 [Server] Server thread/INFO ChatControl 8.2.1-BETA encountered a InvalidConfigurationException! Please check your error.log and report this issue with the information in that file.

**Comment by kangarko** [comment]
Please post me your data.db file

**Comment by kangarko** [comment]
Lets continue on https://github.com/kangarko/ChatControl-Pro/issues/1244
