### ISSUE TITLE
DiscordSRV Support for channels

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#123]
I use the DiscordSRV plugin which connects in game chat with our discord channel. Has been working flawless in both HeroChat and LegendChat but I was told that ChatControl was better so I switched. As it turns out the channel way is not supported and it needs a hook?

https://github.com/Scarsz/DiscordSRV/tree/master/src/main/java/com/scarsz/discordsrv/hooks/chat

Is that something that might happen or should I ditch ChatControl? Hope not as I just paid for the pro version.

**Comment by kangarko** [comment]
Ditch ChatControl. 

Just kidding. I have unfortunately no experience with said plugin so I cannot offer immediate help, but I will investigate it asap. I would say that the channel system wouldn't work, because ChatControl cancels the event and handles it by its own due to the fact that it's not possible to achieve the desired results with plain bukkit API. For now, please try only the interactive or static chat.

What do you mean by the channel way not being supported? Does channels work in-game but they won't display in Discord?

**Comment by gerardvanschip** [comment]
In the DiscordSRV config I can tell it to link a channel to a discord channel.

So in this case the default "standard" to a channelid on my discord server. Anything said will be passed on so Discord users can chat to in game users and visa versa. Right now it only works one way, anything said on Discord arrives at the server, anything said on the server never shows up. Server messages show up just fine. Thats joins, leaves, achievements, deaths etc.

Sadly I don't know coding. This is what the java hook for HeroChat looks like. LegendChat worked even though there is no hook in DiscordSRV which makes me thing this should be possible.

`package com.scarsz.discordsrv.hooks.chat;

import com.dthielke.herochat.Channel;
import com.dthielke.herochat.ChannelChatEvent;
import com.dthielke.herochat.Chatter;
import com.dthielke.herochat.Herochat;
import com.scarsz.discordsrv.DiscordSRV;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;

import java.util.ArrayList;
import java.util.List;

public class HerochatHook implements Listener {

    public HerochatHook() {
        DiscordSRV.hookedPlugins.add("herochat");
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onMessage(ChannelChatEvent event) {
        // make sure event is allowed
        if (event.getResult() != Chatter.Result.ALLOWED) return;

        // make sure chat channel is registered
        if (!DiscordSRV.chatChannelIsLinked(event.getChannel().getName())) return;

        // make sure chat channel is linked to discord channel
        if (DiscordSRV.getTextChannelFromChannelName(event.getChannel().getName()) == null) return;

        // make sure message isn't blank
        if (event.getMessage().replace(" ", "").isEmpty()) return;

        DiscordSRV.processChatEvent(false, event.getSender().getPlayer(), event.getMessage(), event.getChannel().getName());
    }

    public static void broadcastMessageToChannel(String channelName, String message, String rawMessage) {
        Channel chatChannel = Herochat.getChannelManager().getChannel(channelName);
        if (chatChannel == null) return; // no suitable channel found
        chatChannel.sendRawMessage(ChatColor.translateAlternateColorCodes('&', DiscordSRV.plugin.getConfig().getString("ChatChannelHookMessageFormat")
                .replace("%channelcolor%", chatChannel.getColor().toString())
                .replace("%channelname%", chatChannel.getName())
                .replace("%channelnickname%", chatChannel.getNick())
                .replace("%message%", message)));

        // notify players
        List<Player> playersToNotify = new ArrayList<>();
        chatChannel.getMembers().forEach(chatter -> playersToNotify.add(chatter.getPlayer()));
        DiscordSRV.notifyPlayersOfMentions(playersToNotify, rawMessage);
    }
    
}`

**Comment by gerardvanschip** [comment]
The Discord guys have a description on how to easily get it to work:
https://github.com/Scarsz/DiscordSRV-ApiTest

**Comment by kangarko** [comment]
Thank you for providing such extensive information. I shall test it out soon, possibly this weekend.

**Comment by gerardvanschip** [comment]
Any news on this update? I have been using Venturechat while waiting for this feature to be added as Discord integration is essential for me. Sadly found today that Venturechat won't work with 1.11.2 so again curious if I can switch back to the plugin I bought.

**Comment by kangarko** [comment]
Hey, you can track the development here: https://github.com/kangarko/ChatControl/issues/162
I am waiting for their update so I won't need to update it two times.

**Comment by kangarko** [comment]
I am communicating with its developers on Spigot. I will keep you informed about the progress. I have expanded my API in the next version so it would make such implementation possible.

**Comment by kangarko** [comment]
@gerardvanschip preliminary support for DiscordSRV has been added in 7.1.0. Please test against this release whether messages in channel displays on Discord.

**Comment by SmallSansSerif** [comment]
@kangarko Oops posted in wrong ChatControl Github thread. So I'm a registered user of the pro version and wondering if the DiscordSRV support allows the incoming chat messages to be filtered as normal chat. It seems to bypass ChatControl currently. I did try to bump up priority to High but didn't seem to change anything. Try Highest too? Or is there a flag or hook I have to turn on in ChatControl Pro.

**Comment by kangarko** [comment]
@SmallSansSerif which DiscordSRV version are you using? The plugin has a completely new api in its version 13.x, breaking with ChatControl.

**Comment by kangarko** [comment]
Hey @gerardvanschip, Discord has updated their API so I implemented beta support for sending channel messages to discord in 7.3.0. Let me know if there are any bugs or other uncommon behaviour.

**Comment by gerardvanschip** [comment]
I switched my server to Towny some time ago so now use the Towny Chat plugin.

**Comment by SmallSansSerif** [comment]
Ok traveling but should be able to give it s go shortly.

**Comment by kangarko** [comment]
I am closing this, if you'll notice anything or have any question, feel free to make a new issue.
