### ISSUE TITLE
Moving from 8.1.5 to 8.2.1-BETA breaks all permissions on 1.12.2 paper.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1230]
I've spent hours trying to diagnose why permissions for chat-control are not working on my Creative, I just cant see any reason why its not working.

git-Paper-1615 (MC: 1.12.2)
ChatControl version 8.2.1-BETA
LuckPerms version 4.4.22 (& bungee LP 4.4.22)

I have 2 servers running at present, my survival & my creative, I recently toggled on MOTD & MSG to be run by ChatControl on my Survival added perms, works as you would expect, if I use the exact same permissions on my Creative, it shows the user "! Insufficient permission (chatcontrol.command.tell) for example, this is the issue with ALL chatcontrol permissions I add to the creative, But its just limited to ChatControl, I have edited other permissions to make sure im editing the right files, checking that LuckPerms is working correctly and it is, its just any ChatControl perms I add will not work.

I backdated to 8.1.5 and it fixed it, so somewhere between 8.1.5 and 8.2.1-BETA broke all permissions being added in ChatControl to 1.12.2 on Paper.

**Comment by JohnS19** [comment]
+1 
It worked on 8.1.7
broke when updating to 8.2.1 BETA

**Comment by cdmvirt** [comment]
all permissions are broken in new beta

**Comment by kangarko** [comment]
Thank you, the problem was that we required chatcontrol.command.X and chatcontrol.commands.X permissions. That is now solved and we successfully migrated to the singular command permission. See the most recent changelog. Apology for the inconvenience.
