### ISSUE TITLE
Party chat and custom death messages

### ISSUE THREAD

**Issue by iTz-MrAnonymous** [kangarko/ChatControl-Pro#1231]
Hello,
I was just wondering but would it be possible to add the ability to create custom "party chats" without using the channels feature in the plugin?
So my idea was to have it work like the admin chat, where you can use
"/chc adminchat switch" or /chc adminchat <message>
and the perm would so the same, so: 
chatcontrol.commands.adminchat
chatcontrol.commands.<party_name>

My second suggestion was to add a delay on the custom death messages, so if you died and died again 5 seconds later, there would be a delay of something like 120 seconds or so seconds before the death message shows up in chat for everyone again. You could it something like
 dalay: 120
and if you set it to '0' the delay is disabled completely! I believe plugins like Essentials have this feature but I also enjoy having the ability to have custom messages!! Thank you for taking the time to read this!

**Comment by kangarko** [comment]
Hi,

sorry but we're currently very busy and not taking any more suggestions. However as they seem very interesting I am leaving this open for the future.

**Comment by kangarko** [comment]
After going through this issue we decided not to include it, sorry
