### ISSUE TITLE
Command suggestions 

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#1232]
What section blocks command suggestions? The tab section isn't it
Even as op, EVERYTHING is blocked. Why?

**Comment by BobbyMere** [comment]
Great news! the problem starts with 8.2.x. 8.1.7 works as I'd imagine it would

**Comment by kangarko** [comment]
Hi, please use the next version, we have made some permission naming changes, see the upcoming changelog. Thanks.
