### ISSUE TITLE
Updating without uninstalling

### ISSUE THREAD

**Issue by PandaLiz** [kangarko/ChatControl-Pro#1234]
Is there any way to update to the newest version without uninstalling and reinstalling

**Comment by gelsbern** [comment]
I am not sure I am following you but almost every minecraft plugin is a jar file.  Just put the new jar file in the plugins directory and move the old one out (save it just in case along with the config directory) then fire up your spigot/paper/bukkit server.  It will automatically use the new jar file with the old config.

**Comment by kangarko** [comment]
Yes,

if you are updating from the free version read the wikipedia. If you are updating from an older pro version just remove the old .jar and place the new one in, all settings are updated automatically. Watch the console for changes.
