### ISSUE TITLE
Permissions Changed/Removed

### ISSUE THREAD

**Issue by cdmvirt** [kangarko/ChatControl-Pro#1235]
perms don't work, old perms seems to have changed, example chatcontrol.commands.message now has to be chatcontrol.command.message:message and another chatcontrol.commands.reply is now chatcontrol.command.reply. This was noticed right away as players could no longer /msg or /r others have issue too like the perm for chatcontrol.commands.spy doesn't seem to be working after update.

The Messages from joining, leaving and switching no longer works either on the Beta.

We haven't changed anything other then to move over to the 8.2.1-Beta

**Comment by kangarko** [comment]
Thanks, that was changed. Now just use chatcontrol.command.X permission please.
