### ISSUE TITLE
Formatting breaks in 8.2.2

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1236]
Worked in BETA version so I just rolled back to that version (ChatControl-8.2.1-BETA).

I've used combinations of formatting.yml as well as placeholders and even javascript.txt for some nice hover over information when you hover someone's rank in chat.  As soon as I upgraded, everything on that front broke to be replaced by the value of just one of the placeholders (the jobs prefix) and nothing else, even the rank that's supposed to be the hover-over "trigger" to reveal this information is now gone.  So not sure what the update included but it's evaluating everything differently now and so formatting won't work as expected... any ideas?

**Comment by mrcoffee1026** [comment]
8.2.3 fixes this it must have been the folder name change.

Thanks!

**Comment by kangarko** [comment]
Apology for the inconvenience. We changed the folder to ChatControlPro but quickly reverted that change.
