### ISSUE TITLE
Why in ChatControl Pro 8.2.2 it makes a new folder

### ISSUE THREAD

**Issue by iskandarluqman** [kangarko/ChatControl-Pro#1238]
Why in ChatControl Pro 8.2.2 it makes a new folder? It wasnt mentioned in the updates unless I missed it. I really thought I lost all of my files. Apparently it was because the plugin generated a new plugin folder which is weird since it wasnt being mentioned.

**Comment by Sikatsu** [comment]
Yup, noticed the same.

**Comment by kangarko** [comment]
This was an experiment, only affected 8.2.2 and will be reverted in 8.2.3. Migration is complicated and heavy given the large userbase we have. Apology for forgetting to mention it.
