### ISSUE TITLE
ChatControl Pro 8.2.2 Broadcaster bugged

### ISSUE THREAD

**Issue by gaRt3n** [kangarko/ChatControl-Pro#1239]
Thats what i get ingame
`
▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬$E-D$D-E$ Here my BroadCast $E-D$D-E$▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
`

What my config got
https://paste.md-5.net/cakuvuwuri.cs

**Comment by kangarko** [comment]
Thanks for noticing, please wait for the next version and update.
