### ISSUE TITLE
Issues with MCMMO

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#124]
One of the features of MCMMO is a private party chat where a bunch of people can chat together but since switching to ChatControl Pro this private chat is now public for all to see.

I combed through the config but saw nothing for mcmmo, there was one party thing but that made no difference.

**Comment by EvilOlaf** [comment]
Try to play around with the listener values.

**Comment by kangarko** [comment]
Hello,

please try adjust some settings in your configuration according to this article:
https://github.com/kangarko/ChatControl/wiki#townyfactions-rules-channels-or-chat-is-overlapping--dont-show-or-show-when-not-supposed-to

I believe you only need to focus on the **Listener_Priority.Formatter**.

**Comment by kangarko** [comment]
Closing. Please remind me if issues persist.
