### ISSUE TITLE
Duplicated permissions

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl-Pro#1240]
These are some examples of permissions that must be added both in order to work the command:

    - chatcontrolpro.command.spy
    - chatcontrol.commands.spy

    - chatcontrolpro.command.ignore
    - chatcontrol.commands.ignore

    - chatcontrolpro.command.reply
    - chatcontrol.commands.reply

    - chatcontrolpro.command.tell
    - chatcontrol.commands.tell

**Comment by kangarko** [comment]
Thanks, fixed. Use the singular "command" permissions from now.
