### ISSUE TITLE
Error in console when running /chc reload

### ISSUE THREAD

**Issue by Zoneman1972** [kangarko/ChatControl-Pro#1241]
Getting the following error when making adjustments to configs and running /chc reload in game or console. http://prntscr.com/o1ufgq

**Comment by kangarko** [comment]
Have you used /reload or PlugMan previously?

**Comment by Zoneman1972** [comment]
No, this is happening straight after starting the server. I have used plugman previously to reload Chat Control but it doesn’t actually load it properly so I don’t use it anymore.

**Comment by kangarko** [comment]
Alright I see. This can happen when you actually use PlugMan once and this can start happening in the future when CHC is kept running.

Anyways, please test the next release.

**Comment by kangarko** [comment]
I believe the next release solves the issue, comment below if you still experience it
