### ISSUE TITLE
Malformed data.db

### ISSUE THREAD

**Issue by JimmySuckOn9** [kangarko/ChatControl-Pro#1244]
Console error log: https://pastebin.com/f0PDpL17
Error log: https://pastebin.com/f7djNFjJ

Thx!

**Comment by kangarko** [comment]
Please upload me your data.db file, for example to uploadfiles.io

**Comment by JimmySuckOn9** [comment]
> Please upload me your data.db file, for example to uploadfiles.io

https://ufile.io/mokh7nfw

**Comment by kangarko** [comment]
Thank you. Please write to me on SpigotMC, just need to verify your username.

**Comment by JimmySuckOn9** [comment]
Okay

**Comment by kangarko** [comment]
Hi,

I am afraid you'd have to delete data.db completely. Let me know when that happens again.

**Comment by JimmySuckOn9** [comment]
I haven't delete it.

**Comment by kangarko** [comment]
If you don't delete it with your current state the error will remain. Just remove it and it will get generated again. Let me know if anything happens over and repost any new errors in case they show up.
