### ISSUE TITLE
Jobs Reborn placeholders dont work

### ISSUE THREAD

**Issue by maxrio21** [kangarko/ChatControl-Pro#1245]
Hello kangarko, i have a problem when i want to use a **placeholder** from the plugin **Jobs Reborn** to my **chat format**, it doesnt work and i want to know that is because **Jobs Reborn** isnt compatible with **Chat Control Pro** or its because am I writing it wrong or am I doing something that is not possible.

I've seen the variable guide and instead of using **%placeholder%** I'm using **{placeholder}** because according to the wiki it does not work the other way, and even then it does not work, I've also tried writing with **%placeholder%** but it does not work either

If the error is because it is not compatible I would like that in one of the following updates **(do not be in a hurry)** add the compatibility with plugins like Jobs Reborn, because surely other users will want to use other plugins.

Thank you very much for your assistance and my congratulations for creating such a **complete and versatile** plugin!

**Comment by kangarko** [comment]
Hello,

I am sorry to tell but this in particular is incompatible, however you can try reading Event Priorities article on Wiki to change the formatter priority to a higher value such as HIGHEST.

Alternatively, you can install PlaceholderAPI to try if they have access to Jobs Reborn placeholders.
