### ISSUE TITLE
My Servers Are Somehow connected with each other..

### ISSUE THREAD

**Issue by SinlesFlyer376** [kangarko/ChatControl-Pro#1247]
For some odd reason ALL of the servers are connected and i don't have mysql setup, but i see the other server chat. I don't have discord setup with it, or nothing..
It's all default files except for my formatting.yml
Is there a way to fix this. It's pretty annoying and it sends twice..

Proof: http://prntscr.com/o688z2

**Comment by kangarko** [comment]
Hello,

are you talking about the messages in white? It seems it's not coming from ChatControl but rather a different plugin. Try removing ChatControl to see if that helps. Also try setting Bungeecord.Enabled to false in settings.yml

**Comment by SinlesFlyer376** [comment]
I have figured out that it is luckperms, i just need to find the correct perm

**Comment by kangarko** [comment]
Alright awesome!
