### ISSUE TITLE
Server message to individual

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#1248]
Hello, is there a way to send a editable message from the console to a player? like /say but instead of [Console] as the prefix, the prefix is editable

**Comment by kangarko** [comment]
Hey,

at this time you can only use /tell however you can change the prefix to whatever you want in your localization/ folder in your messages_X.yml file.

**Comment by BobbyMere** [comment]
It says the command is not supported yet

**Comment by BobbyMere** [comment]
> Hey,
> 
> at this time you can only use /tell however you can change the prefix to whatever you want in your localization/ folder in your messages_X.yml file.
It says the command is not supported yet when put into the console

**Comment by kangarko** [comment]
Sorry I don't understand what you mean?
