### ISSUE TITLE
Warns/Generated an exception while executing task

### ISSUE THREAD

**Issue by M0dii** [kangarko/ChatControl-Pro#1249]
https://pastebin.com/AA9Bx0k1

Server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

ChatControl Pro 8.2.5 and 8.2.6.

Plugin list: 
https://imgur.com/a/AfiRkWV

**Comment by kangarko** [comment]
Hey,

if you disable Timed Messages in messages.yml does it still appears?

Do you have errors.log file? If so please upload it here (you can just ZIP it)

**Comment by M0dii** [comment]
Did you mean broadcaster?

**Comment by kangarko** [comment]
Yes the Broadcaster key in messages.yml.

**Comment by M0dii** [comment]
The issue seems to be gone right now. Possibly there was another cause of it.
