### ISSUE TITLE
Dont fully break the plugin for small syntax issues in config

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1250]
One of my biggest annoyances with ChatControl is if you make a small syntax or formatting mistake in the config, I fully breaks the plugin requiring a server restart.
It drives me utterly mental. If i'm testing a new formatting change and something in the formatting doesn't work it just full on breaks chat control, if I fix it and /chatcontrol reload it wont work and will require a restart of the server.
Could we please have a safety check, that if the chatcontrol reload throws an error it just doesn't uses the old working config, but still warns you in console/game about the syntax or formatting issue.
Then you can fix it and /chc reload without rebooting the entire server.

**Comment by Mutim** [comment]
That's any config. Not just chat control. Your best bet is to use YAML parsing and find errors before publishing. I'll drop you a really good one. This honestly shouldn't be in issues. 

http://yaml-online-parser.appspot.com/

**Comment by FrozenBeard** [comment]
Yeah thats what im asking for, a quick YAML parse check when /chc reload happens, and if there is a parse issue, don't break the plugin, just tell the user there is a parse issue.

**Comment by kangarko** [comment]
This is a safety feature on its own and with the current system it's impossible to change it without either adding ridiculous overhead to the code or rewritting it which I don't have time for as I am recording new training series.

You should be using a local test server for those changes or as Mutim suggested, use a third party service.

There is a solution however, and that is to scan your entire ChatControl/ folder for all .yml files and just parse them for syntax errors before reloading. If that's the main cause of your pain I can add it?

**Comment by kangarko** [comment]
I've also sent you a PM on Spigot, appreciate if you can get back to me there ;)

**Comment by FrozenBeard** [comment]
I'll see if I can get VSCode to show me YAML errors, that was the problem something wasnt tabbed that needed to be tabbed in and it broke the entire plugin, chat, filters, everything for a 2 second change that I just needed to do and not have to fuck around with a test server/online yaml parsers, it was a quick change that just needed to happen fast and no pissing around.

**Comment by kangarko** [comment]
Got it, well I dont know any other plugin on the market who can do that during reload, but I understand it is frustrating so I can add that feature soon.

**Comment by kangarko** [comment]
Pulled
