### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by DjTurky** [kangarko/ChatControl-Pro#1253]
Doesn't work with java 11 (I think they removed SharedSecrets in Java 11). Heres the error:

`[15:08:03] [Server thread/INFO]: [ChatControl] Enabling ChatControl v8.2.6
[15:08:03] [Server thread/ERROR]: Error occurred while enabling ChatControl v8.2.6 (Is it up to date?)
java.lang.NoClassDefFoundError: sun/misc/SharedSecrets`

**Comment by kangarko** [comment]
Update your Java 11 to the latest, works fine:

![a](https://i.imgur.com/u5ndHl7.png)
