### ISSUE TITLE
Paper 1.13.2 - ChatControlPro  8.2.7 – Chatcontrol is ignoring Autojoin for operators and pushing me always in an unwanted channel

### ISSUE THREAD

**Issue by werbemaschine** [kangarko/ChatControl-Pro#1254]
I configurated ChatcontrolPro with Channels and Bungeecord.
I have a "nearby" channel, range 100 and no bungee, no discord.
A "world"  channel, range *, no bungee, no discord.
A "global"  channel, bungee is on, no discord.
And a discord channel, no bungee, discord is on.

Autojoin and limits are configurated, that a player can only write in one channel but read all channels by default. Standard write channel is and should be always "nearby".

As normal player (no OP) the autojoin works without problems. He/she will get "nearby" as write and "world", "global" and "discord" channels as read. Could leave all channels except "nearby"
(I set different permissions for nearby, so nobody can leave it – is a must have channel).

Problem: when I login as OP, it always pushes me into the "discord" as "write", all others as "read".
I want to note here, that there are no special permission settings in my permission plugin for OPs according chatcontrol, actually they should get the same permissions and autojoin as erverybody else.

Before that I also had an "admin" chat in my channels.yml and as OP I always got pushed as "write" in the admin chat. Back than, I thought is a default because of OP, so I removed the "admin" chat. Now I always get pushed into "discord" as "write" as mentioned above. I also removed the "Discord_Channel" property from the "discord" config part in the channels.yml, since you told me in a previous answer that it is for admin chats only and not needed for normal discord channels (DiscordSrv).

Anyways, it would be nice if I could get the same autojoin like everybody else, cause it is anoying to change the channel on each login as OP.

Also, I could read the nearby channel from other worlds (range: 100) as OP what is totally weird. Didn't test the last part as normal player, have to do it soon.

Ty

**Comment by kangarko** [comment]
Hello,

as an operator, you inherit all autojoin permissions and you may end up in "write" mode for all available channels.

To prevent this, you need to give yourself negative permissions for all channels you do not want to join as described here: https://github.com/kangarko/ChatControl-Pro/wiki/Channels

You only need to give yourself this permission per channel:

`-chatcontrol.channel.autojoin.{channel}.*`

If you have LuckPerms, this is the "false" permission. For PermissionsEx, it begins with an "-".

**Comment by werbemaschine** [comment]
Hello,
I understand, I will try it this weekend.
Thank you
