### ISSUE TITLE
generated an exception while executing task 13338

### ISSUE THREAD

**Issue by Nachtaktiv77** [kangarko/ChatControl-Pro#1255]
Hey, when I leave my server (but not other players) I got this error:

[https://pastebin.com/yZ7af0M4]

Obviosly it has to do something with my MySQL Database and Chatcontrol. I recently fully migrated my server to a new IP.

**Comment by kangarko** [comment]
Hello,

I apology, but this has to do with your MySQL database and not ChatControl directly, you'd better ask your hosting company for assistance as I am not sure what to do here.
