### ISSUE TITLE
Suggestion: add isConversing to Chatcontrol API

### ISSUE THREAD

**Issue by lulu2002** [kangarko/ChatControl-Pro#1256]
Besides Chatcontrol, I still have other plugins like chatroom...etc in my server, it will cause: though I am conversing with other player, but the message will still send to chatrooms because of event priority.

So if ChatControl can add this method to api, I can just check is player conversing with some one, and prevent the message send to chatroom.

**Comment by kangarko** [comment]
Hello,

do you mean the Bukkit conversation system using Prompt and Conversation class? This is already supported and ignored by ChatControl. If changing priorities to even HIGHEST and MONITOR did not help I am afraid there's a major incompatibility.

**Comment by lulu2002** [comment]
Oh, I mean the @<playerID> option's  conversing, not bukkit one.

**Comment by lulu2002** [comment]
Thread closed, but hope you can still watch what I said ;-;

**Comment by kangarko** [comment]
Of course, I added it!

![a](https://i.imgur.com/eVt5Qoi.png)
