### ISSUE TITLE
oddly - user specific - replace?  of the word none at the start of a sentence

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1257]
In chat... and this only seems to affect ME with permission to *, that I can tell this comes up under no other cases that I've witnessed yet.  If I begin my chat with the word "none " followed by anything else... the message will appear in staff chat as "one " followed by whatever else I typed. I have attempted many other variations, but this is the only affected word that there seems to be.  I can't imagine what could be causing this to happen, I've had other staff members attempt similar texts and this doesn't happen for them.

**Comment by kangarko** [comment]
Hello, 

It is a secret feature to make you number one if you are having unlimited permissions.

I have now changed it so it only makes _me_ number one when I join your server. Please test the next release.

Just kidding. Thanks for report, small thing, patched it.

Matej
