### ISSUE TITLE
Chat tags?

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#1259]
Any way to add chat tags like those found using Deluxetags? The layout and format of that plugin looks so outdated. 

Also, is there a discord for simple questions like this?

**Comment by kangarko** [comment]
Hey,

GitHub is the best and most robust way of handling support, we currently don't have paid staff on Discord, sorry.

What do you mean by tags? We support infinite amount of variables. See https://github.com/kangarko/ChatControl-Pro/wiki/Variables and also see JavaScript variables. All PlaceholderAPI variables are also supported.
