### ISSUE TITLE
ChatControl prefix bug

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1267]
When I use /chc announce before every line it will show the ChatControl prefix. 
Same is happening with /motd.

**Comment by Sikatsu** [comment]
Example with /chc reload : http://prntscr.com/obcymo

**Comment by Curtis73** [comment]
![image](https://user-images.githubusercontent.com/14040165/60768074-a7229980-a0b8-11e9-9bc5-99d5b19f5dbc.png)
Yeah, I'm experiencing this too

**Comment by kangarko** [comment]
Thank you, this will be resolved, sorry for the delay.
