### ISSUE TITLE
Can't see /tell messages when sent

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1269]
This tends to happen when I update ChatControl, private messages are sent, but the player who sends them doesn't see them.

Am I missing some configuration? Everything was ok before I updated.

Spigot 1.13.2
CC 8.2.8

**Comment by kangarko** [comment]
Hello,

please make sure there are no errors, and that if Bungeecords is enabled you also have BungeeControl on your Bungeecords.

Are you still experiencing this problem? I apology for a late reply. If you do, simply ZIP me your entire file and drop it here.

**Comment by MithrandirCraft** [comment]
You changed the bungee plugin's name which was confusing xD Let's see how it goes...

**Comment by kangarko** [comment]
Closing in good faith this has been resolved, kindly comment below if still getting issues

**Comment by MithrandirCraft** [comment]
Fixed.
