### ISSUE TITLE
MOTD breaks ChatControl Pro

### ISSUE THREAD

**Issue by rtchal** [kangarko/ChatControl-Pro#127]
Modifying anything in the MOTD section of the settings.yml file is causing ChatControl Pro to crash. I can use the default MOTD, but if I try to change it to my custom one using the same amount of lines and the same formating, the plugin crashes. 
I am using the latest version of the plugin from Spigot, and I am on 1.11.

**Comment by kangarko** [comment]
Post the **Motd** part from your settings.yml

**Comment by rtchal** [comment]
`# -----------------------------------------------------------------------------------------
# Welcome players to the server with Message of The Day
# -----------------------------------------------------------------------------------------
Motd: 
  Enabled: false
  
  # How long to wait before displaying after login? Used to avoid covering by other messages.
  Delay_Ticks: 2
  
  # Sound to play. Format: <bukkitSoundName>, <volume>, <pitch> 
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  
  Message:
  - '&6*--------------------------------------------------*'
  - '&3Hello &a{player}&3! Welcome to the &bCreatonics Network&3!'
  - '\n'
  - '&3Don't forget to check the forums daily for important news and announcements!'
  - '\n'
  - '&3Also, please vote for us on all of the Minecraft server listing websites!'
  - '\n'
  - '&3For help, do &b/help'
  - '&6*--------------------------------------------------*'


# -----------------------------------------------------------------------------------------
# Spying allows to see others' commands, including content of private messages.
# -----------------------------------------------------------------------------------------`

Here is one of the ones that I tried that didn't work. It broke even with 'Enabled:' set to false.

**Comment by rtchal** [comment]
Ok, I don't know why that comment posted like that, sorry.

**Comment by rtchal** [comment]
![capture](https://cloud.githubusercontent.com/assets/23729280/20728751/c1185836-b644-11e6-8ccd-f625fc4d34fe.PNG)

GitHub still isn't showing exactly what I had, so here is a screenshot.
Sorry again.

**Comment by kangarko** [comment]
The apostrophe ' on line "Don't forget to ..." is causing problems. Replace the beginning and ending apostrophes with " like so:

    - "&3Don't forget to check the forums daily for important news and announcements!"
