### ISSUE TITLE
Add Factions3 support

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1270]
CC 8.2.8
Spigot 1.13.2
**Edit:** forgot to mention I'm using the latest version of Factions3 (which is the only actively updated factions to date, by one of the developers of the original factions)

Channels:
  faccion:
    Format: $4[&fFaccion&4] &7{pl_prefix}{player}:{pl_suffix} {message}
    Party: faction

This configured channel doesn't seem to function propperly. Every time someone attempts to talk with other factions members, they get a message saying no plot exists in their location.

**Comment by kangarko** [comment]
Hey,

apology for a late reply. Please wait till the next version and set Debug to [channel-party] in settings.yml and restart. Post me the console output.

**Comment by MithrandirCraft** [comment]
Here it is: https://gist.github.com/MithrandirCraft/596b4ab398e8896956354626831c076f

**Comment by kangarko** [comment]
Apology, seems like your Faction plugin is unsupported. I am leaving this open for future implementation.

**Comment by kangarko** [comment]
Pulled to roadmap
