### ISSUE TITLE
Cyrilic charaters in regex rule

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#1271]
Hi,

1.
```
> version
[18:11:20 INFO]: This server is running Paper version git-Paper-637 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:11:20 INFO]: Previous version: git-Paper-624 (MC: 1.13.2)
[18:11:20 INFO]: Checking version, please wait...
[18:11:20 INFO]: You are 1 version(s) behind

```

```
> chc
[18:11:48 INFO]: -----------------------------------------------------
[18:11:48 INFO]:  // ChatControl Pro™ running 8.2.6
[18:11:48 INFO]:  // Created by kangarko © 2013 - 2019
```

2.
It's an serbian server, I'm their developer, there is swear "JEBEM" which is "fuck", but nevermind.
There is cyrilic language that most of the players understands, and if you write "JEVEM" in cyrilic it looks the same as "JEBEM" in latin, this is those letters: "ЈЕВЕМ".

I wrote this regex rule:
https://regex101.com/r/1pHu6j/1

It works perfect on regex101, but in server it does not work.
Is there a way to add ```/miu``` at the end of regex so it can use unicode characters and insensitive?

**Comment by kangarko** [comment]
Hello,

please see https://github.com/kangarko/ChatControl-Pro/wiki/Rules#chinese--cyrillic--accented-languages-and-rules

I assume this had helped you so I am closing this. If it did not, kindly write below and I get your message :)

**Comment by AngelDeaD** [comment]
I tried ```Translate_Diacritical_Marks``` but it do not help. It was true for me, I changed it to false, restart server but it still not catching the same letters in cyrilic alphabet.
I tried the same with ```Anti_Spam.Similarity_Check.Ignore_Special_Characters``` but it does not help.

**Comment by kangarko** [comment]
Sorry for the delay, I am on it.

What about setting Regex_Strip_Colors to false in settings.yml?

**Comment by AngelDeaD** [comment]
```Regex_Strip_Colors``` either ```true``` or ```false``` still same.

**Comment by kangarko** [comment]
I am so sorry, I experimented with it, even added "the ignore case" flag to the regex however it really seems the Java regexes is not matching it.

![a](https://i.imgur.com/Sih23tr.png)

This seems to be a problem in the Java regex library (or I am mistaken?). Anyways I honestly can't help any more in this scenario. Sorry to let you down.

**Comment by kangarko** [comment]
Oh wait a second, seems like the 'm' in the message was also Cyrillic. If you copy the following text it will work: "јевем" (the last m is from Cyrillic)

**Comment by AngelDeaD** [comment]
Please, take a look at this:
https://regex101.com/r/1pHu6j/2
and compare it to:
https://regex101.com/r/1pHu6j/3

Both of those regex rules have only cyrilic letter to match (letters in regex rule) and both of them have ```\i``` which is for "insensitive case", meaning it will match both upper and lower case letters, but first rule: https://regex101.com/r/1pHu6j/2 do not have ```\u``` and matches only the lower case string, (because in regex rule there are only lower case letters to match, for an reason it's inogring ```\i```). But in second rule: https://regex101.com/r/1pHu6j/3 I added ```\u``` at the end and it matches both upper and lower case.
Is there a way to add it via an variable in CHC config, like we have ```handle as swear``` in ```rules.txt```
I think it would be great if you can add:
```chc-charset default```
and for this unicode
```chc-charset utf8```
Meaning that ```chc-charset default``` will use current config, but ```chc-charset utf8``` will add that ```\u``` to every regex rule we added (just like we have to add ```handle as swear``` to each rule), since ```\u``` is only way to enable case insensitive for cyrilic letters.

I found this on stackoverflow, maybe it can help you:
https://stackoverflow.com/a/10894689

I think it's best to add ```chc-charset``` variable because so many people who uses just latin letters can stay on default, but we who are in need for cyrilic, can switch some of our chat filters to utf8.

**Comment by kangarko** [comment]
Thanks I will take a look and we can have a settings.yml option for that!

However there will be performance loss (https://i.imgur.com/tfwwtAM.png), are you willing to tolerate that?

**Comment by kangarko** [comment]
What about adding (?ui) to the end of the regex in the match operator, does it help (test in Minecraft please)?

**Comment by AngelDeaD** [comment]
> Thanks I will take a look and we can have a settings.yml option for that!
> 
> However there will be performance loss (https://i.imgur.com/tfwwtAM.png), are you willing to tolerate that?

Do you know how much of performance loss?



> What about adding (?ui) to the end of the regex in the match operator, does it help (test in Minecraft please)?

I just tried this, but when I add `?ui` regex rule does not match anything

**Comment by kangarko** [comment]
Not sure how much performance loss, you can do /timings report or see if any "X took over" messages appear in the console.

I have added that matching internally, test new version and see how that goes, thanks.

**Comment by kangarko** [comment]
Closing

**Comment by kangarko** [comment]
Comment below if having issues or questions
