### ISSUE TITLE
ChatControl 8.2.10, Minecraft 1.14.3: Groupmanagers {GROUP} not working in formatting.yml

### ISSUE THREAD

**Issue by Kyrenic** [kangarko/ChatControl-Pro#1274]
Hey, just wanted some help in formatting my chat, here is my formatting.yml https://pastebin.com/RRipTZZ0 and the permission plugin I use https://www.spigotmc.org/resources/groupmanager.38875/ .

I tried to use {GROUP} in a hover event and it didn't display the group, if you could offer any help that'd be awesome!

**Comment by kangarko** [comment]
Hello,

please install Vault and use the {pl_group} variable instead of {GROUP}, thanks :)
