### ISSUE TITLE
Group Chats

### ISSUE THREAD

**Issue by SimoDavid** [kangarko/ChatControl-Pro#1275]
Is there the ability to lock a particular  player to only see and send messages within a group? Other players within the group may not have that restriction and can interact with the public chat, but I want to restrict certain players to being able to interact with certain other players. 

Is this an ability that can be done with this plugin?

**Comment by kangarko** [comment]
Hello,

you can achieve that using Channels, see channels.yml as well as the wiki article. Using Groups there is currently no such option, it has never been requested and honestly not really possible with the current system.

Thanks
