### ISSUE TITLE
No documentation working

### ISSUE THREAD

**Issue by omgitsAngus** [kangarko/ChatControl-Pro#1277]
HI!

I want to know how to add my own server's IP to ChatControl's advertisements? So it's whitelisted? I searched for these options for 20+ mins, checked online, tried to join discord to ask others and none of those methods worked!

**Comment by poma123** [comment]
In the rules.txt you can use `ignore string play.yourname.net|mc.another.com` in the Domain/URL filter section.

**Comment by kangarko** [comment]
As poma said ;) Simply read that file in your rules/ folder and you should be able to do it.

There's also a Wiki article: https://github.com/kangarko/ChatControl-Pro/wiki/Rules#whitelisting--allowing-links-or-ips
