### ISSUE TITLE
How to disable this messages?

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1278]
12.07 12:45:21 [Server] INFO [ChatControl 8.2.12] Rules parse: commands.txt took 0.09 ms
12.07 12:45:21 [Server] INFO [ChatControl 8.2.12] Rules parse: commands.txt took 0.18 ms
12.07 12:45:21 [Server] INFO [ChatControl 8.2.12] Command Rules Check took 0.3 ms
12.07 12:45:21 [Server] INFO [ChatControl 8.2.12] Command event took 0.34 ms

**Comment by kangarko** [comment]
Set Log_Lag_Over_Milis in settings.yml to -1.

**Comment by andris155** [comment]
Thanks!

**Comment by andris155** [comment]
Not work this.

**Comment by kangarko** [comment]
Thank you for letting me know, I have solved this and it should now start working.
