### ISSUE TITLE
AntiBot Issue

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1279]
Hello,

AntiBot is not working on my server, I am using latest CHC version and am on Spigot 1.8.9.
With that being said, I feel like the reason of this happening is that players get TPed to spawn on join. Could you fix this so the spawn TP on join doesn't count has movement. 

Thank you.

**Comment by pvpstryker** [comment]
The cooldown doesn't work either I just realized.

**Comment by pvpstryker** [comment]
Still not fixed, can I have support?

**Comment by kangarko** [comment]
I apology for a late reply.

Yes indeed, if the players get teleported on join ChatControl registers this movement and compares to their original location and since it got changed, it enables them to chat. Unfortunately there's no system to easily change this scenario at the moment.
