### ISSUE TITLE
[feature] message (advertisement) of player seen only by him

### ISSUE THREAD

**Issue by md79** [kangarko/ChatControl-Pro#128]
I have an idea for an interesting anti-advertising filter. If plugin detects that the player wrote mcserver.com for example, then the message will be hidden for other players but not for himself. This method can be good because he will think that he was able to advertise another server but no one really didn't even see his message. I hope you know what I mean.

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. Yes, I already have a similar task in the roadmap, hopefully get to it this year.
^Only the player himself will see the uncensored message, thinking it passed through. Others won't see anything or see it censored, plus admins will be notified.
