### ISSUE TITLE
AntiSpam and Sound_Notify issue

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1280]
Hello,

AntiSpam blocks my messages because I am tagging the same person in different messages. Would it be possible to make it so AntiSpam doesn't count it has a similarity. It should honestly do it for all player names. Player names should not be considered as spam.

**Comment by pvpstryker** [comment]
Still not fixed, can I have support?

**Comment by kangarko** [comment]
Apology for a late reply. 

The heuristics run on player names could slow down the server so we don't offer it. You can consider increasing the anti spam similarity threshold.

Please do not bump your message as it renders as new and I always start replying to oldest tickets first.
