### ISSUE TITLE
Chat Control Null issue. 

### ISSUE THREAD

**Issue by RisenCloud** [kangarko/ChatControl-Pro#1281]
Hello, we keep getting this in our server spamming console when people do warps sometimes or say some things. The plugin obvioulsy doesn't like it. 

[23:31:39 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [23:31:39 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [23:31:39 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [23:31:39 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [23:31:39 INFO]: [ChatControl] Unable to parse JSON message. Got null

**Comment by kangarko** [comment]
Thanks, I will change that error to be more descriptive so that we can actually fix it. Please repost using the next release.

**Comment by kangarko** [comment]
Fixed
