### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by GameHoundInteractive** [kangarko/ChatControl-Pro#1283]
ChatControl Pro latest version having a massive issue loading, Works fine if i revert it to the last update but version:  8.2.13 does this error, Version 8.2.10 does not. 
https://pastebin.com/P61eLENy

**Comment by DeadMaster121** [comment]
Also having the same issue here

**Comment by giuliotoplad** [comment]
I have your same problem, apparently the latest version of ChatControlPro doesn't work because of that Error.
The other versions worked correctly, in fact now I have version 8.2.12.

**Comment by kangarko** [comment]
I apology for this problem, and will fix it in today's release.
