### ISSUE TITLE
1.14.3 - Error with some placeholders?

### ISSUE THREAD

**Issue by Phoetrix** [kangarko/ChatControl-Pro#1286]
Hi!

Since version 8.2.12 of ChatControlPro, my placeholder "%vault_eco_balance%" (Maybe others placeholders) in the custom motd don't return money but just itself ( {vault_eco_balance} ). Same in the version 8.2.13 but in the version 8.2.11 everything work. :o

**Comment by HexedHero** [comment]
Same issue too...
{vault_eco_balance}
{player_name}

none work in Motd
8.2.13 as well

**Comment by HexedHero** [comment]
They don't work anywhere but
{javascript_myplaceholderapiscript}
works fine.
All the placeholders work everywhere else but on CC

**Comment by HexedHero** [comment]
https://cdn.hexedhero.com/u/6EBXuF9ofq.jpg

**Comment by kangarko** [comment]
Thanks, fixed.
