### ISSUE TITLE
Log_Lag_Over_Milis: -1 not work. Always write 0 ms

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1287]
14.07 13:10:43 [Server] INFO [ChatControl 8.2.13] Rules parse: books.txt took 0 ms
14.07 13:10:43 [Server] INFO [ChatControl 8.2.13] Rules parse: books.txt took 0 ms
14.07 13:10:48 [Server] INFO [ChatControl 8.2.13] Rules parse: books.txt took 0 ms
14.07 13:10:48 [Server] INFO [ChatControl 8.2.13] Rules parse: books.txt took 0 ms
Please add disable fully this messages.

**Comment by kangarko** [comment]
Thank you, next version will solve this problem.
