### ISSUE TITLE
/r issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1288]
Typing `/r` yields `"Usage: /r <message>"`
Players are complaining cause they try to type `/r ?` as a generic response message but it doesn't send, instead it just sends the commandsender `"Usage: /r"`without message(not like the first one).

ChatControl Pro 8.2.13
Paper 1.13.2 build 637

**Comment by HexedHero** [comment]
Big oversight, hope it gets fixed. doing
/r ?
to reply to a message is a very very common thing.

**Comment by kangarko** [comment]
Thanks, fixed, apology for overseeing this. We rewrote the command system recently in Foundation library however ChatControl uses an older system so it got caught in the library before the plugin could send the proper message. Fixed.
