### ISSUE TITLE
How to disable message about joining in a channel? Feature to post on global chat.

### ISSUE THREAD

**Issue by Vynderman** [kangarko/ChatControl-Pro#129]
When player joins in a chat, everyone in a channel gets the message "%PLAYER_NAME% has joined to this channel (local)". I have big server and local channel by default, I wanna hide this message.

And would you kindly to release following feature: when player staying in any channel, he can (with needed permission) post message with next construction "!Text" and this message will be posted on decided channel (Like the "Global" or other).

**Comment by kangarko** [comment]
Hello,

you can disable this message in the localization. There, set **Channels.Join** to **none**. You can find more informations about this in the ChatControl Wiki.

You can send messages to any channel via "/ch send" command, or, to the global chat when you have ranged mode enabled, just by prefixing message with "!".

Sincerely,
kangarko

**Comment by kangarko** [comment]
Closing. Feel free to comment below if you have any questions.
