### ISSUE TITLE
Doesn't deny any message until /chc reload

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#1290]
I seriously have no idea why this is happening.
https://cdn.hexedhero.com/u/QNBaqr6s2X.jpg

**Comment by HexedHero** [comment]
Does it with default configs but you have to turn the formatter on

**Comment by kangarko** [comment]
Any messages in the console? Please post me your ChatControl file as a ZIP.

**Comment by HexedHero** [comment]
http://cdn.hexedhero.com/u/CSaF19ePEH.zip
http://cdn.hexedhero.com/u/CSaF19ePEH.zip

Even tried on a vanilla server with just LuckPerms, Vault, ProtLib and CC and still does it.
In the zip is only two files because they are the only ones needed to re-make the problem.
I have only added a @ shortcut for the Admin-Chat and enabled formatting. All I have changed.

**Comment by kangarko** [comment]
Hey, please update to the latest version and change Formatter_Priority.Checker to HIGH in settings.yml

Now it should prevent me from typing before I move:

![a](https://i.imgur.com/Xxo70ez.png)
