### ISSUE TITLE
Channels + Towny {Help Needed}

### ISSUE THREAD

**Issue by EnderGamingFilms** [kangarko/ChatControl-Pro#1292]
Hey so I am trying to setup town chats with ChatControl (no TownyChat plugin), and I have run into a small issue where when players do /tc they get put into the town chat and it works properly but when they do /g or /global it says "You are already in this channel" and they HAVE to use /ch join global to fix... I want them to be able to do /tc to toggle on town chat and message, but I also want them to be able to "read" global chat. then they can do /g, /global, and or /tc (again) to return to global chat without any issues. Do you know how I could achieve this?

Channels.yml: https://pastebin.com/kmayGVjJ

Formatting.yml: https://pastebin.com/ATFM72ky

Also would it be possible to do this?
https://imgur.com/0obrw8a
https://imgur.com/WYg6YQ3
So that players have to be apart of a town to use /tc?

Side Note: Also a discord/IRC would be great for stuff like this because this isn't really a bug persay but more of a question on how to use the plugin.

**Comment by kangarko** [comment]
Hey,

I apology for a late reply. Mixing Towny and ChatControl in this way is not possible, you'd have to only stick to ChatControl fully and then make an alias for /global that invokes /chc join global read or write (use commands.yml file for that in root server folder, see our Wiki for a tutorial).

Your Javascript placeholder should work, though.

**Comment by EnderGamingFilms** [comment]
Alright, I just use chat control for formatting and toeny for channels :) also side note someone bypassed my spam control idk how...

**Comment by kangarko** [comment]
Sounds good :)

If you have a console log from that incident feel free to post me it below.
