### ISSUE TITLE
Colors gui no longer has any effect

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1293]
No errors thrown.
Paper version 638
Chatcontrol-pro version ChatControl-8.2.13

Not sure if it might be a permission you updated nodes for or not; the permissions i've set are like this one - for example:
- chatcontrol.chat.format.color.blue

**Comment by mrcoffee1026** [comment]
OOPS, this is partly untrue... I've determined that colors DO have an effect... in admin chat still.. just not anywhere else.

**Comment by mrcoffee1026** [comment]
Oops again, it also still has an effect on /me's (which I've let essentials take over?)... possibly anything that has a command in it that is not basic chat.

**Comment by mrcoffee1026** [comment]
Colors work again in chc 8.3.1.
However: anyone without a nickname now no longer has a name AT ALL in chat.

**Comment by kangarko** [comment]
I guess that "clears" things up lol.

I fixed that {nick} problem.
