### ISSUE TITLE
ChatControl / BungeeControl Redis Issue

### ISSUE THREAD

**Issue by Affixes** [kangarko/ChatControl-Pro#1294]
Hi there,

Tested on the latest versions of BungeeControl (2.1.1) and ChatControl (8.2.5): 

Using the `Execute_Bungee_Commands` feature in `handlers.yml` sends a command to ALL Redis subscribers, meaning that commands (such as warnings) are duplicated across all of our bungee instances. There should be a way to exclude a proxy/BungeeControl instance from listening to the commands in the list.

**Comment by kangarko** [comment]
Hey!

I apology for a late response, this is not a typical reply rate.

To understand you correctly, would you like a whitelist by server name in BungeeControl plugin, or should the BungeeControl plugin exclude the server the commands were sent from initially?

Matej

**Comment by Affixes** [comment]
I'd say the former is the best option out of the two - just define a bungeecord instance that should execute the command.

**Comment by kangarko** [comment]
Alright awesome, thanks for clarifying. It should be implemented as we discussed within the next 1-2 days.

**Comment by kangarko** [comment]
I added "redis-send-commands" option, you may set it to false in the next update
