### ISSUE TITLE
[Question/Suggestion] About Join Messages and Announcer 

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#1297]
Is there any way to have the discord word within this join message be a link without having to input the link and have users see it? I think you do it via json like the formatting but not sure on how to do it for the join message.

Also can you do it for the announcer?

Join Message:
![image](https://user-images.githubusercontent.com/5675428/61316496-05f2bc00-a7f9-11e9-93b6-82626d239f0a.png)

Announcer Message:
![image](https://user-images.githubusercontent.com/5675428/61316541-202c9a00-a7f9-11e9-871d-612233d741ca.png)

Anyway to change these at all? If not then I'd ask for it to be added. 
~Blood

**Comment by kangarko** [comment]
In the announcer, you can simply set the name of a chat format from formatting.yml that will contain a clickable link. See Ad_Info in the default formatting.yml for example of that click action. Then you would simply use: 

![a](https://i.imgur.com/hepJu43.png)

Try the same for join message, if that won't work then you'd have to create it manually as stated in https://github.com/kangarko/ChatControl-Pro/wiki/JSON#json-in-yml-files
