### ISSUE TITLE
Console Spam: What does it mean?

### ISSUE THREAD

**Issue by omgitsAngus** [kangarko/ChatControl-Pro#1299]
Hi there!

I keep getting this spam in my console - happens every 10-15 seconds.

> [06:38:54 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:54 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:54 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:54 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:54 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:57 INFO]: UUID of player codename4you is d7ab9432-2cd2-4315-a1eb-169ad1937721
> [06:38:57 INFO]: codename4you[/73.55.148.199:43368] logged in with entity id 617305 at ([PlayersMines]170.4868450194983, 1.0, 273.08490226978125)
> [06:38:58 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:58 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:58 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:58 INFO]: [ChatControl] Unable to parse JSON message. Got null
> [06:38:58 INFO]: [ChatControl] Unable to parse JSON message. Got null

Any ideas?

**Comment by omgitsAngus** [comment]
Ok im so sorry I wasnt on latest version and noticed you fixed it.

**Comment by kangarko** [comment]
Right. Let me know if you experience any more issues :)
