### ISSUE TITLE
External services to filter messages

### ISSUE THREAD

**Issue by feardevilz** [kangarko/ChatControl-Pro#130]
Hi,
Would it be possible to add in premium features if enabled by users for external chat filtering as an optional enabled feature? There's external services like CleanSpeak (https://www.inversoft.com/products/profanity-filter) and webpurify that are very useful for chat filtering. I'd also like to see an option that gives end users the ability to enable or disable those features based on their client chat settings - possibly something saved in mysql.

Note, this would not replace the regex filtering, but add on to it. I'd like the see regex get modified to be more like pwnfilter.
Example: https://www.spigotmc.org/resources/messageit-webpurifyaddon.10378/

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. Currently I am not taking feature requests of this size due to little time and having different priorities, but I am leaving this open for the future.

**Comment by Tsuser1** [comment]
This would be a great 8.5.0 milestone sort of project, I would personally give this feature a try. Having a filter for every single form of profanity is proving ineffective along with the significant server performance issues it causes. Other 2nd or 3rd party APIs could be used to more efficiently moderate chat messages with a fraction of the performance hit; this would apply especially to high-demand networks.

**Comment by kangarko** [comment]
Addressed, https://github.com/kangarko/ChatControl-Pro/issues/64
