### ISSUE TITLE
Usage Message Issue

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1301]
Hello,
The usage messages don't look good and the config lacks settings, you can only change the start of the message and not the end. Example: 

>   Usage: '&6Chat &8>> &7Incorrect usage. Use &f'

Making it look like this:
https://i.gyazo.com/29b046451e1a31fc44634a1401de563b.png

There shouldn't be a "or ?" at the end of the usage and you should be able to add a period at the end of the sentence. There should be a %usage% placeholder or **even better would be being able to configure all of them**. Overall the message looks unprofessional, when some of my players saw it, they told me it looked unprofessional which brings me here to you.

Can it be fixed?

**Comment by kangarko** [comment]
Hey,

we will improve the usage messages in the next version where the "?" would cause inproper messages to appear in some cases.

Thank you for your inquiry, I am taking this as a suggestion. The current system generates the usage messages on the fly, making each message having a separate locale section would be extremely inefficient. What I suggest is you change the General.Usage key in your localization file to something like that:

`&6Chat &8>> &7Incorrect usage. Use &f`

If I am mistaken and there is a command that produces double usage output let me know.

Matej

**Comment by pvpstryker** [comment]
So you copy pasted what I already had done? 
Usage: '&6Chat &8>> &7Incorrect usage. Use &f'
Can there be a period at the end of it, make the automatic generation a placeholder so we can add a period at the end of the message making it look more professional.

**Comment by kangarko** [comment]
So you want me to add a "Usage_Suffix" like label that will add your customizable text at the end of the auto generated usage text?

**Comment by pvpstryker** [comment]
Yeah, or just make a placeholder for the auto generated text.
`Usage: '&6Chat &8>> &7Incorrect usage. Use &f%Usage%&7.'`

**Comment by kangarko** [comment]
Alright sounds good. I have reviewed the code but it's gonna take a while (lots of operators to merge) and we don't have the resources for it right now: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-14-4.10258/update?update=286812

I will keep this open as a suggestion

**Comment by kangarko** [comment]
Pulled with high priority

**Comment by kangarko** [comment]
@pvpstryker is the latest version sufficient for your needs?
