### ISSUE TITLE
messages_en.yml automatically updated

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1302]
Installing ChatControl on an empty default server always shows this message
```
Update messages_en.yml. Move 'General.Server_Prefix' (was '[Server]') to 'Server_Prefix'
Update messages_en.yml. Move 'General.Console' (was 'server') to 'Console_Name'
```
The messages_en.yml contains this header:
```
# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 19.07.2019 20:52:17
#  to ChatControl 8.3.1
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologize.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the ChatControl-8.3.1.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/ChatControl/wiki
# 
# -------------------------------------------------------------------------------------------
```
I thought this was only a temporary issue but it has been since a month now (version 8.2.5)

**Comment by kangarko** [comment]
Thanks, that should be fixed. Ensure you have the localization/ file in your ChatControl folder.

The problem was that Foundation, the library we use, now looks for those two keys not in the General section but the in the no-section path. I moved those keys out of General internally as well.

Thanks for your patience

**Comment by x1p** [comment]
Thank you very much.
Tested the new version and I noticed some changes over the past version.
First of all, a lot of `'` are replaced by `"` but what really surprised me was this larger margin here:
![Screenshot_20190722_101558](https://user-images.githubusercontent.com/28690790/61616840-ce0cce00-ac69-11e9-8c60-be5d21b8ea7e.png)
and every other place where `|-` was used.
Is this correct?

**Comment by kangarko** [comment]
Yep, that is correct. If using |- then the lines must be indented with the same margin for each new line.

We do not control single ' or double " quotes, that's either your system or SnakeYAML library Bukkit uses for saving yml files.

**Comment by x1p** [comment]
I know there is an indent, but if you look closely, the margin is twice as big as normal.
See this comparison program:
![Screenshot_20190724_173819](https://user-images.githubusercontent.com/28690790/61807464-e2072a00-ae39-11e9-830b-48dbbf3e3149.png)
Left = old with 2 more spaces than `List_Format: |-`, right = new with 9 spaces more than `List_Format: |-`

**Comment by kangarko** [comment]
It's just aesthetics, the margin does not really matter, what matters is what's shown in the game.
