### ISSUE TITLE
rules no longer being applied

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1304]
console is logging the catches but the replacements are no longer being made in chat: for example
[18:03:13 INFO]: *--------- Rule match (chat) for Zombie_brains ---------
[18:03:13 INFO]: MATCH: (....)(?=\1\1+)
[18:03:13 INFO]: CATCH: !!!!!!!!!!!!!!!!!!!!!!!!!11
[18:03:13 INFO]: FINAL: !!!!!!!!!11
[18:03:13 INFO]: [standard] Zombie_brains: !!!!!!!!!!!!!!!!!!!!!!!!!11

"Final" which is the expected output is NOT being output into chat.  Only into the console.  As of ChatControl 8.3.0
Paper-638 (1.13.2)

**Comment by mrcoffee1026** [comment]
on a side note I was trying to get the version so did "/chc list" and I get the following message:
"Wrong arguments.  Type /chc list for command list."  Which of course is the action that resulted in this message to begin with.

**Comment by mrcoffee1026** [comment]
nevermind this rules are applied again in 8.3.1.  The circular /chc list thing still happens in 8.3.1 though so if there's a place to replace that with "/chc ?" that may need to be done.

**Comment by kangarko** [comment]
Thanks, I will update the localization keys. The list command is now just /chc ?.
