### ISSUE TITLE
All unnicked users have no names in chat now (v8.3.1)

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1305]
Setting any /nick to a user remedies the problem, but without a nick only the formatted prefix and postfix are shown.  No nick at all.  Updated to latest PlaceHolderAPI in case that was the problem but that had no effect.

**Comment by mrcoffee1026** [comment]
Still properly displays the ign when doing the formatted "hover" action just not in the main chat where it also should.... Like THIS PART:
```
  Chat:
    Prefix:
      Message: '&f{pl_prefix}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*'
        - '&7Prefix&8: &7{pl_prefix}'
        - '&7Ping&8: {ping}'

```Looks correct except... now this no longer works:
Message: '{nick}&r&b>&r' 
as nick no longer falls back to player like it should. there may be some way to work this into a javascript function i suppose to test for a value for nick and then not use nick if there isn't one, but that seems excessive besides that i'm not really sure how to do that.

**Comment by mrcoffee1026** [comment]
For now i've added this to my javascript.txt
```

define {displayname}    
script:
    getDisplayName();
    function getDisplayName() {
      return "{nick}" == "" ? "{player}" : "{nick}";
    }
```
And changed in formatting.yml (under Player):
Message: '{displayname}&r&b>&r'


There may be a better way to go about doing this, but this seemed like the most straightforward approach I could sort out.

**Comment by Sikatsu** [comment]
Same here, some users lost their name. Only their rank shows up.

http://prntscr.com/ohrp5j

**Comment by kangarko** [comment]
Thanks, solved. We added a better support for (legacy) Nicky plugin, and that seemed to "clear" some things up.
