### ISSUE TITLE
8.3.1-8.3.2 Error, won't launch

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1308]
Server version 1.8.8
Error: https://pastebin.com/g8mkFKDi

**Comment by x1p** [comment]
```
Listener_Priority.Formatter must be higher than Listener_Priority.Checker! This is to prevent messages being formatted before they are checked. If unsure just set Listener_Priority.Formatter to HIGH in settings.yml (see below for more)
```
Did you check this setting?

**Comment by pvpstryker** [comment]
> ```
> Listener_Priority.Formatter must be higher than Listener_Priority.Checker! This is to prevent messages being formatted before they are checked. If unsure just set Listener_Priority.Formatter to HIGH in settings.yml (see below for more)
> ```
> 
> Did you check this setting?

I can run 8.3.0 with no problem. I shall test it and see.

**Comment by kangarko** [comment]
Edit settings.yml as the error says.
