### ISSUE TITLE
[feature] Bungee drop-in support, non-bukkit based

### ISSUE THREAD

**Issue by feardevilz** [kangarko/ChatControl-Pro#131]
Hey,
Realizing that this is a bukkit-based plugin I've been searching for the exact same features but only installed on a proxy serving side. Is there any specific features built in which only support bukkit api calls? There's a few other chat filtering plugins that work bungee side only but none have similar features. 

I'd like dev to consider having either an additional plugin or revamping current code so it can be dropped in to a bungee only server as an option. If that means disabling some features when in bungee-only mode, i'd think that would be ideal for a premium plugin.

**Comment by kangarko** [comment]
Hello,

ChatControl is and will most likely stay solely a Bukkit plugin.

There is an extension named BungeeControlBridge, check it out at
https://www.spigotmc.org/resources/bungeecontrolbridge.13079/
