### ISSUE TITLE
Toggleable slow mode for channels

### ISSUE THREAD

**Issue by KarlOfDuty** [kangarko/ChatControl-Pro#1313]
I have looked around and I don't think such a feature already exists, correct me if I'm wrong though.

It would be very useful to let moderators set the chat in a slow mode with a configurable rate limit when it gets a bit spammy.

**Comment by kangarko** [comment]
Thanks, that indeed sounds like something a lot of people would benefit from, and I marked that to the roadmap, however we can't take new suggestions right now: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-14-4.10258/update?update=286812
