### ISSUE TITLE
I need help Configurate Groups in ChatControl

### ISSUE THREAD

**Issue by JhordanPG** [kangarko/ChatControl-Pro#1314]
I need help on how to configure the input and output messages for a specific group, I attach proof of how I configured it:

http://prntscr.com/okggoy
http://prntscr.com/okggz6

**Comment by kangarko** [comment]
Hey,

remove that group options as they are invalid, and create a new conditional join/leave message in your messages.yml file:

![a](https://i.imgur.com/sN1XxxF.png)
