### ISSUE TITLE
Color permissions issue

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1315]
So I've made sure my players do NOT have the following permissions:

chatcontrol.chat.format.color.{color}
chatcontrol.chat.format.magic
chatcontrol.chat.format.bold
chatcontrol.chat.format.strikethrough
chatcontrol.chat.format.underline
chatcontrol.chat.format.italic
chatcontrol.chat.format.reset

However they can still talk in color using color codes. I've even negated the perms and they can still do it. 

I am currently on 8.3.2, will be on 8.3.3 later tonight.
Paper Spigot 1.14.4 - 146. 
Using PEX right now, will be switching to luck perms soon.

**Comment by kangarko** [comment]
Thanks, that will be fixed.
