### ISSUE TITLE
Sounds for formatting

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#1316]
Could we possibly have a sound setting for the custom chats like
Admin-chat etc so players that can see the chat get a sound played?
like this:

http://cdn.hexedhero.com/u/7FNzdvOlqc.jpg

**Comment by Ghostipedia** [comment]
Absolutely something I'd like to see. +1

**Comment by kangarko** [comment]
Hey, definitely something I can add to the roadmap, however as per our SpigotMC recent announcement we're not doing anything new until further notice, thanks.
