### ISSUE TITLE
Buggy Color Menu + Forced BungeeChat

### ISSUE THREAD

**Issue by Octanium0** [kangarko/ChatControl-Pro#1317]
Hi,
On a 1.14.4 Paper server running ChatControl Pro 8.3.2
I encountered some problems after setting up ChatControl Pro. We found that oped users are automatically in BungeeChat, even if BungeeCord is disabled.
We also saw that the color cat (from the colors menu) is buggy.

Ex: If we chose aqua color in the color menu, when we type "test" in the chat, it will write "btest"

PS: A BungeeCord proxy is configured but not linked to the server on which we encountered the problem

[Config folder](https://github.com/kangarko/ChatControl-Pro/files/3438170/ChatControl.zip)

**Comment by kangarko** [comment]
Hey,

you cannot use the § letter as the admin chat shortcut, this letter is reserved internally for colors and will cause issues. Change it please.

Matej
