### ISSUE TITLE
Improve cache stability during heavy load

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1318]
Paper-641 (1.13.2)

Mostly these:
Chatt Control did ok for awhile then "crashes" with a lot of these:
Could not pass event AsyncPlayerChatEvent to ChatControl v8.3.3
After the errors appear any filtering stops as far as chat is concerned.  I can see in the logs it still "tries" from time to time but often runs into this:
[19:17:00] [Server thread/INFO]: Player Console kicked PunchYourPanda for Slow down chat (last warning).
[19:17:00] [Server thread/INFO]: CONSOLE issued server command: /kick PunchYourPanda Slow down chat (last warning)
[19:17:00] [Server thread/INFO]: Error: Player not found.
In spite of the player still being there.  Since most of the spam auto-actions are just never done since "player not found' always, it wasn't much help in this incident at all.
Also encountered a Com1 somewhere along the lines there was a note to contact the dev with these logs and the error.log.  This is the console log for the duration of the attack:
https://pastebin.com/k6X4RjBU
And this is the error.log:
https://pastebin.com/evU2Hv20

**Comment by kangarko** [comment]
Thanks for the report, interesting to see the plugin under a stress test. I believe this can be rather concurrency issue, which means we have to dig deeper.

As for the `Could not pass event AsyncPlayerChatEvent to ChatControl v8.3.3 error`, is this error then caused by the two issues in the error.log file you've posted?

Do you get errors after the attack has stopped?

**Comment by mrcoffee1026** [comment]
no errors after the attack stopped.  The console log continued to spit out mostly the "count not pass event AsyncPlayerChatEvent to chatcontrol..." type and then the "com0" error which is what generated the error.log.  The "player not found" errors in the console log may well be lag induced but I'm not certain of that... where the player was not found "at the moment" but they certainly were present at the time the trigger had been implemented by the spam filter.  Most of the names left and joined multiple times over several minutes.  My banning each name as they did eventually stopped the attack by preventing those particular alts from returning.  The person either ran out their store of names or patience... the entire event lasted around 30 minutes.  In the log I identified something like 137 nicks.  Several never actually "joined" the server due to my 50 user limit they managed to attain for a few nonsequential moments throughout the event.

**Comment by kangarko** [comment]
Thanks, I looked briefly into it but it seems like a more complex issue, will do more testing with a bot simulating this behavior

**Comment by mrcoffee1026** [comment]
Alright, part of why I posted it was this bit that appears in the logs (somewhere):
`[19:11:57] [Async Chat Thread - #130/INFO]: ChatControl 8.3.3 encountered a COm1! Please check your error.log and report this issue with the information in that file.`
So hopefully it helps you figure out whatever it is.  I feel this sort of attack is a bit unusual... first of its kind I've seen anyway.

**Comment by kangarko** [comment]
Thanks, after more investigation this has to do with much of the player cache system, bad news is we have to rewrite much of it, good news is you're the first reporting this. I'm putting in on high priority and will get back to you next week.

Should be the same no matter what MC version you're using.

**Comment by kangarko** [comment]
Pulled
