### ISSUE TITLE
Plotsquared plot chat support

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#132]
I would like to chatcontrol moderate also plotsquared chat since user can spam here and use bad things and stuff.
@MattBDev help with this implementation :)

**Comment by kangarko** [comment]
Hello,

please change the Checker priority to either HIGHEST or MONITOR. See
https://github.com/kangarko/ChatControl/wiki#townyfactions-rules-channels-or-chat-is-overlapping--dont-show-or-show-when-not-supposed-to

**Comment by xion87** [comment]
instead to close the ticket, i tried botch HIGHTEST and MONITOR as checker priority, it will just cause chatcontrol to ignore all swear and ads, caps ecc...

**Comment by kangarko** [comment]
Hey, are you sure you restarted your server entirely? I had many users reporting that changing the priority to HIGHEST or MONITOR has fixed the problem. If it had not, there's little I can do because I can't control other plugins.

**Comment by xion87** [comment]
yeah, i restarted same thing, btw i got a similiar issue with askyblock plugin, when i type something by using /is teamchat, the message will be out in teamchat messsage and normal chat....
