### ISSUE TITLE
Commands Cooldown

### ISSUE THREAD

**Issue by Kyrobi** [kangarko/ChatControl-Pro#1324]
**Expected behavior**: Plugins like essentials X would be able to add a cooldown to the commands specified in commands.txt

**Actual behavior**: Essentials will pick up on the fact that the command is on cooldown and warns you. However, the command and its payloads are still executed.

**How can this issue be replicated?** Specify a command you want to block in the config of Essentials. Make a command on chat control. Execute the command. Essentials won't be able to block it.

**Additional Information**: I have priority of the listeners all set to LOWEST. 
Paper 1.14.4
ChatControlPro 8.2.11

Commands.txt file: https://pastebin.com/mfDiVbdr

I'm using CMI in this image, but the same thing happens with others. You can see in this photo that the cooldown does pick it up, but the payload is still executed:

![image](https://user-images.githubusercontent.com/20980266/62019394-40a70d80-b184-11e9-9991-4f214905ff0e.png)

Maybe have a built-in operator for like the command section of the plugin? Something like `then cooldown 30` or something.

**Comment by Kyrobi** [comment]
I lied. Using Essentials, it doesn't even pick it up.

So I'm testing another command: 
`match ^/testing123`
`then warn {nick}`

And my cooldowns in essentials are:
![image](https://user-images.githubusercontent.com/20980266/62149280-fc6d5780-b2c0-11e9-988f-0f77b769ef84.png)

**Comment by kangarko** [comment]
Hello,

when you create a command using the rules system, you don't really create one. We are just listening to the 'command event' and if the command starts with the given match, we run the operators.

Essentials seems to work for commands registered using the Bukkit ecosystem.

Your last be would be setting the checker priority to HIGHEST or MONITOR.

Matej

**Comment by Kyrobi** [comment]
I'll try to get Essentials to add this feature, but I have no idea how to describe it. Could you help? https://github.com/EssentialsX/Essentials/issues/2705

**Comment by kangarko** [comment]
I see that got cleared, seems like you'll have to use another plugin to register those simple commands as he told.

**Comment by Kyrobi** [comment]
Thanks for your helpful response. :heart:
