### ISSUE TITLE
 How to create different types of chat messages for different privileges

### ISSUE THREAD

**Issue by MaxWainer** [kangarko/ChatControl-Pro#1325]
How to create different types of chat messages for different privileges
Example:
Group1
 First_Part: 
      Message: "L "
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&7Tralalala"
       Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/help'

**Comment by kangarko** [comment]
Hello,

you can create different chat formats or use Groups. If you use different chat formats, you can use the Sender_Permission key to render the particular part of that format only if the sender has a certain permission, that would be your group.

- Help for Formats: https://github.com/kangarko/ChatControl-Pro/wiki/Formats
- Help for Groups: https://github.com/kangarko/ChatControl-Pro/wiki/Groups
