### ISSUE TITLE
Disable Similarity Check

### ISSUE THREAD

**Issue by EnderGamingFilms** [kangarko/ChatControl-Pro#1327]
Do you think you could add a simple "enabled: true" section to the anti spam features because setting the check to 100 or 0 isnt something I would think of immediately. Also, having a dedicated line to enable and disable features makes it easier to customize the ugin.

**Comment by kangarko** [comment]
Hey,

for now we are not planning to change it, you can just read the comments to learn that setting it to 0 will disable it.
