### ISSUE TITLE
Allow this plugin to hook?

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#1328]
Can you allow this plugin hook into yours so then it's not broken?
https://www.spigotmc.org/resources/showitem.10133/

**Comment by kangarko** [comment]
I am sorry we are not planning to add this in the moment.

Here are your options:

1. Try using PlaceholderAPI if it does not already support it.
2. Try changing Listener_Priority of Formatter, see Wikipedia on how to do it.
3. You can use JavaScript to code own hook, see Wikipedia on GitHub. That plugin must have an API tho.
