### ISSUE TITLE
Formatting : Placeholders not working

### ISSUE THREAD

**Issue by DeusOccisor** [kangarko/ChatControl-Pro#133]
Formats: 
Example_Format: 
Parts: 
Tag: 
Hover_Event: 
Action: SHOW_TEXT
Values: 
- "{deluxetags_description}"
Message: "&f[{deluxetags_tag}]"

In chat=
[{deluxetags_tag}]PlayerName: Message

Does not show the tag that is applied through deluxe tags. I have PlaceholderAPI installed. It works in other plugins, but not in ChatControl. I am using the latest premium version of CHC as well as the latest version of PlaceholderAPI and DeluxeTags

*note: NO placeholders work except for what is in the # area of the chat.yml (such as {timestamp}, {player}, {message}, etc)

**Comment by kangarko** [comment]
Hey,

please make sure you have **Variables.Custom_Enabled** to true in settings.yml

**Comment by DeusOccisor** [comment]
Hello,
I resolved the issue. It turned out that PlaceholderAPI was not saving the
extensions correctly on my end (port issue with host perhaps?) But I was
able to resolve this. Thank you for contacting me via email. That means a
lot. Expect a 5 star review, outstanding customer service.
Regards,
Deus

**Comment by kangarko** [comment]
Closing. Feel free to remind me if any further issues occur.
