### ISSUE TITLE
Welcome New Player Message

### ISSUE THREAD

**Issue by CaliDreams** [kangarko/ChatControl-Pro#1332]
Maybe a stupid question, but is it possible to set up a welcome message for a new player that joins my hub server for the first time, and is seen by all, across all my servers like the rest of my chat is set up to do?
If not, is it possible to at least set up a welcome message everyone sees at least on the proxy a new player joins for the first time?

Running Bungee network with BungeeControl 2.2.1 with 7 Spigot/Paper proxies 1.12.2-1.14.4

**Comment by kangarko** [comment]
Hey, apology for a late reply, we've been extraordinarily busy with mineacademy.org and I will get back to you within 24 hours.

**Comment by kangarko** [comment]
Hey,

I have reviewed your case but at this time such feature is not possible within ChatControl, I am sorry for this. 

You can however show such message on a Spigot level when the player joins an individual server for the first time, that would be shown to all players within that server.
