### ISSUE TITLE
Considering purchasing, need to know if Pro does what I want.

### ISSUE THREAD

**Issue by donut4490** [kangarko/ChatControl-Pro#1334]
Plugin looks very impressive, I have a few questions though.

Does this plugin allow players to join multiple channels in the server at once? If not, does it allow DiscordSRV to push messages from one Minecraft channel to multiple Discord channels?

And how does it work with BungeeCord? Could certain channels be across all servers, messages work across all servers?

**Comment by kangarko** [comment]
Hello!

Yes, players can join as many channels as they have permission for and the limit is set for.

We can only push messages from one Minecraft channel to one Discord channel.

Yes, if you install BungeeControl you will see channels that have their bungee option enabled across all servers where ChatControl is installed.
