### ISSUE TITLE
1.14.4 Chat Control interfering with Tardis Plugin - Tardis Information System issue

### ISSUE THREAD

**Issue by LozoTrioxide** [kangarko/ChatControl-Pro#1337]
Hey!

So im not sure how to explain this easily, but basically the Tardis plugin has a feature called the Tardis Information System - 
![5d53899bbb7f81c13337f75cf9283e0b](https://user-images.githubusercontent.com/50601395/62789209-60153300-bac0-11e9-98b5-1f832eb09447.png)

To use it, it asks you to type a white letter to proceed, but when you type  one of these white letters, all it says is - 
![86e746ce5868356412c44e773589cefc](https://user-images.githubusercontent.com/50601395/62789236-6acfc800-bac0-11e9-8230-4fca52ee739e.png)

It also does it when trying to exit the System so you get stuck in the system. The developer of the plugin does know, however, after removing chat control it seems to fix it which is why im posting here :)

Here's the CC zip if you need it
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3486929/ChatControl.zip)
Thanks,
Lozo

**Comment by eccentricdevotion** [comment]
https://github.com/eccentricdevotion/TARDIS/blob/v4.0/src/main/java/me/eccentric_nz/TARDIS/info/TARDISInformationSystemListener.java

**Comment by eccentricdevotion** [comment]
Have changed my chat listener so that it strips colour codes from the chat before checking it [fd498ef](https://github.com/eccentricdevotion/TARDIS/commit/fd498ef517bf7c3deb58e631f42c79a7173480f3), confirmed working.
