### ISSUE TITLE
Make private messaging work with essentials nicknames

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1338]
Hey, would it be possible so we can use PM commands together with essentials nicknames?
It'd be so much easier.

**Comment by kangarko** [comment]
Hey,

I am sorry such functionality is not yet supported and we're not planning to change the current system right now.

**Comment by Sikatsu** [comment]
Hey, does this happen with all plugins? We're planning on switching to CMI instead.

**Comment by kangarko** [comment]
I am not sure, if you use CMI you can just use their PM commands instead of ChatControl's if they support it.
