### ISSUE TITLE
Players hear chime if you type their name in a channel they have not joined

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#134]
I have a moderator only channel, and if you type a player's name in the moderator channel, that player can hear the chime even though they don't see the message.  This is concerning because if you are observing someone as a potential cheater they might stop cheating if they know they are being talked about.  It could also be confusing to players if you use a sound like the level up chime and they haven't actually leveled up.

**Comment by kangarko** [comment]
Fixed in 7.1.0
