### ISSUE TITLE
Socialspy issues

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1340]
For some reason the format is different between /r and /msg
Also the {receiver} is sometimes empty so it only shows []

http://prntscr.com/oqpii8

**Comment by kangarko** [comment]
Hey,

it is because there are two formats for spy, see Spy.Format_PM for the second one with [].

The recipient might be empty when using BungeeCord, currently we cannot get the recipient from another server this way.

**Comment by Sikatsu** [comment]
So there is no way /r and /tell will show the same format?

**Comment by kangarko** [comment]
They cannot because we dynamically output the receiver to /reply, but you can make them look very similar by editing those two settings options

**Comment by Sikatsu** [comment]
About the [] thingy, it also happens when on the same server sometimes. Bungee is enabled though.
http://prntscr.com/oulo0z

**Comment by kangarko** [comment]
The only reason I see why this is happening is that the cache for whatever reason is null, so we had to recreate it. If you're using MySQL then cache is synced when the player joins, not manually in the code elsewhere.

![a](https://i.imgur.com/nSASijg.png)

Contributions are welcome, at this point I am not aware of other solution. Syncing MySQL there would drain performance.
