### ISSUE TITLE
BanManager hook: Notify when PM'ing muted players

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1341]
If a user is muted and someone sends them a message via /msg send them back a message to say they are muted, so they know they will not respond.
I currently use BanManager to mute people.

**Comment by kangarko** [comment]
This is already done if one uses /ignore, there's a warning message already.

I could take this as a suggestion but our plate is maxed out right now, please come back in a few months.

**Comment by FrozenBeard** [comment]
Staff issue mutes all the time, global thing across all servers, it would just need to check if a user is muted and ping a message back if they are.

**Comment by kangarko** [comment]
Do you know if BanManager reports the mute status to Essentials or somewhere else such as Vault? 

I am leaving this open as a future suggestion.

PS: MineAcademy is opened, email me and I will continue your account as we agreed :)

**Comment by FrozenBeard** [comment]
They have an [API](https://github.com/BanManagement/BanManager/blob/master/src/main/java/me/confuser/banmanager/BmAPI.java)? 
https://www.spigotmc.org/resources/banmanager.21927/
```
    IpBanEvent
    IpBannedEvent
    IpRangeBanEvent
    IpRangeBannedEvent
    IpRangeUnbanEvent
    IpUnbanEvent
    PlayerBanEvent
    PlayerBannedEvent
    PlayerUnbanEvent
    PlayerMuteEvent
    PlayerMutedEvent
    PlayerUnmuteEvent
    PlayerNoteCreatedEvent
    PlayerWarnEvent
    PlayerWarnedEvent

```

**Comment by kangarko** [comment]
I understand they have an API, but the problem there is that we must add another dependency to Foundation. With each new dependency compiling time slows down and so does the entire workflow. I aim to remove less-used and obsolete dependencies not add more.

However I can try to add this using reflection, however at present I'm busy with other ventures. Leaving open.

**Comment by kangarko** [comment]
Pulled
