### ISSUE TITLE
[Improvement] Custom AFK checker

### ISSUE THREAD

**Issue by jer3m01** [kangarko/ChatControl-Pro#1342]
Currently the only way to check if a player is AFK (used for the `@player` message ping) is using Essentials.

Would it be possible to add the ability to register our own check i.e.:
```java
ChatControlAPI.registerAFKProvider(? extends AFKProvider);
```
```java
public abstract class AFKProvider {

    /**
     * Get whether the player is AFK.
     *
     * @param player The player we're checking
     * @return Whether the player is AFK
     */
    public abstract boolean isPlayerAFK(Player player);

}
```

Thanks!

**Comment by kangarko** [comment]
Hello,

thank you for your suggestion, however ChatControl does not have an AFK system so we can't add this integration because at max we would only have to do a proxy to Essentials which is unnecessary overhead.
