### ISSUE TITLE
Cross-server private messaging

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1344]
When a player uses /w or /reply for some reason it will say the player is offline (cross-server).
This might be due to EssentialsX also being on the server? Since ChatControl says ''we're taking over..'' on these commands. Other PM commands work fine.

**Comment by kangarko** [comment]
Does it work when you remove EssentialsX temporarily?

**Comment by kangarko** [comment]
Do you have the option BungeeCord enabled. We recently removed the plural -s (BungeeCords) so make sure both servers have that exact option on, as well as Bungee for Private_Messages.

You can set Debug to [bungee] in settings.yml for both servers and post me the console output.

**Comment by Sikatsu** [comment]
Removing essentials works, aswell for editing plugin.yml. However since it says chatcontrol is taking over, I would expect it to work without having to edit plugin.yml each time.

**Comment by kangarko** [comment]
Do you have Towny installed?

**Comment by Sikatsu** [comment]
No I don't have towny installed.

**Comment by kangarko** [comment]
Please post me your settings.yml from one server

**Comment by Sikatsu** [comment]
Switching to CMI and it solved this issue for me.

**Comment by kangarko** [comment]
Alright I am sorry I was not able to help, let me know if you need more help with CCP specifically in the future.
