### ISSUE TITLE
Global join/leave messages question

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1345]
Hey,

So i've setup bungeecontrol like this: http://prntscr.com/oqyyei

I set hide_join_quit_kick_messages to true on all spigot servers.

On the creative server we can see whenever a player logs in on the network, but while we are on survival we don't see ANY login messages. Survival is currently the fallback server where they connect to by default.

What did we do wrong?

**Comment by Sikatsu** [comment]
Is there anyway to get ''Joined the server for the first time'' global aswell with bungee?

**Comment by kangarko** [comment]
For your first question, please set "debug" to "[leave]" in config.yml and restart, report me the messages.

For your second question, I am sorry this is not possible at this time.

**Comment by Sikatsu** [comment]
Would it be possible to make the ''Joined the server for the first time'' global in a future BungeeControl update?

**Comment by kangarko** [comment]
With the amount of time we have left these months no sorry, but I believe this is already suggested in Roadmap from last year so there is a chance it will come up.
