### ISSUE TITLE
"Please do not repeat the same (or similar) command"

### ISSUE THREAD

**Issue by UoibiE** [kangarko/ChatControl-Pro#1346]
Hi,

How do I get that to stop happening? I can't find it in the config. Please help.

**Comment by nunavailabul** [comment]
I think you're looking for this area of settings.yml.

`Commands:
    Command_Delay: 2
    Limit:
      Period: 10 seconds
      Max_Commands: 8
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 3 - {delay}
    Similar_Percentage_Block: 80
    Similarity_Points:
      Warn_Set: spam
      Amount: 4 * ({similarityPercentage} / 2)
    Whitelist_Works_Like_Blacklist: false
    Whitelist_Similarity:
    - /c toggle
    - /tell
    - /pm
    - /t
    - /w
    - /r
    - /togglepm
    - /togglebroadcast
    Whitelist_Delay:
    - /spawn
    - /hello
    Handle_As_Chat:
    - /me`

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#how-to-edit-messages-you-have-to-wait-x-seconds-before-another-message-or-please-do-not-post-the-same-or-similar-messages-or-announcement-format

**Comment by BradyMan69** [comment]
noic
