### ISSUE TITLE
How to put URL's at broadcast messages?

### ISSUE THREAD

**Issue by jaydee0004** [kangarko/ChatControl-Pro#1348]
Whenever I put URL's broadcaster messages, it shows up syntax errors.

Can someone clarify how put URL's in these messages?

Thank you.

**Comment by jaydee0004** [comment]
[messages.zip](https://github.com/kangarko/ChatControl-Pro/files/3498428/messages.zip)

**Comment by kangarko** [comment]
The file you've posted contains URL and seems to be fine, used https://yaml-online-parser.appspot.com/

But make sure you use quotes 'like this' each time there's colors on your lines, and I have seen some lines with colors but not quotes so try fixing that first.
