### ISSUE TITLE
How to use ChatControl with Skript ?

### ISSUE THREAD

**Issue by Wasabules** [kangarko/ChatControl-Pro#135]
Hi, 
I have installed ChatControl-Pro but all event "on chat" doesn't work.
I use this event to save into a MySQL database all messages of player.

You have a idea ?

**Comment by Wasabules** [comment]
I have an idea:
It is possible to create a Mini-spigot plugin to add a custom event for ChatControl intro Skript ?
"on chatcontrol chat:"

**Comment by kangarko** [comment]
I am sorry, ChatControl has no special compatibility with Skript that way.
