### ISSUE TITLE
1.14.4: "An illegal reflective access operation has occurred"

### ISSUE THREAD

**Issue by lawnmeower** [kangarko/ChatControl-Pro#1350]
First issue, hope I don't screw this up.

Upon a server startup, this is output (not sure by what):

[INFO] [ChatControl] Loading ChatControl v8.3.10
[WARNING] An illegal reflective access operation has occurred
[WARNING] Illegal reflective access by org.mineacademy.chatcontrol.final.nul. .j (file:/home/gs-40546/plugins/ChatControl-8.3.10.jar) to field java.net.URL.factory
[WARNING] Please consider reporting this to the maintainers of org.mineacademy.chatcontrol.final.nul. .j
[WARNING] Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[WARNING] All illegal access operations will be denied in a future release

I am unable to upload a copy of the plugin folder. However, I have not modified the folder at all.

**Comment by kangarko** [comment]
It is just a warning, feel free to ignore it if the plugin starts fine, it is probably your java distro.
