### ISSUE TITLE
Chat Formatting

### ISSUE THREAD

**Issue by nunavailabul** [kangarko/ChatControl-Pro#1351]
I know it's just me being stupid, but I cannot get chat formatting to work.

I have changed prefixes and colour codes in Formatting.yml under the "Chat" format group, but chat prefix and username do not change at all.

Very sorry!  This plugin is just so comprehensive I am a little overwhelmed.

**Comment by kangarko** [comment]
Hey,

I assume you've just forget to set Enabled to true in formatting.yml

Let me know below if still having issues!
