### ISSUE TITLE
Cannot reload plugin

### ISSUE THREAD

**Issue by XxPoNaGeXx** [kangarko/ChatControl-Pro#1354]
------------------------------------[ 15.08.2019 19:34:20 ]-----------------------------------
ChatControl 8.3.11 encountered an IllegalPluginAccessException
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_201
Plugins: ProdigyNightClub v2.0.2, PhantomSpawnControl v2.1.1, BlockLocker v1.6.1, PlaceholderAPI v2.10.3, PlayerRespawnerPlugin v0.0.1-SNAPSHOT, NoChat v1.0, Spicord v1.0.4-SNAPSHOT, PlugMan v2.1.6, FarmLimiter v1.2, StaffFacilities v4.1.0, SuperTrails v9.7.1, RandomTeleport v2.4.1, ViaVersion v2.1.3, CraftingStore v2.2.0, CoreProtect v2.17.5, LagAssist v2.18.2, LuckPerms v4.4.1, WorldEdit v7.0.1-SNAPSHOT;4548-a9b3fb1, AdvancedBanAutoBan v1.0.1, XRayDetector v1.0, AdvancedBan v2.1.5-RELEASE, spark v1.3.0, BanAnnouncer v1.0.2, Votifier v2.5.2, DiscordBotAPI v3.0, MVdWPlaceholderAPI v3.0.1, VotingPlugin v5.19.2, Minepacks v2.0.9-Release, FeatherBoard v4.22.0, LimitPillagers v2.4.1, LuckPermsMVdWHook v4.1-SNAPSHOT, Vault v1.7.2-b107, TimeVote v1.42, PlayerShopGUIPlus v1.3.1, DailyBonus v2.2.7, WorldGuard v7.0.1-SNAPSHOT;1945-b0e4cf1, DiscordChatWM v3.1.2, MyWarp v3.0.2-SNAPSHOT+travis-b1784.git-f3ed0f39ba, ShopGUIPlus v1.19.6, Essentials v2.17.1.0, SpigotLib v9.0.3, ProtocolLib v4.4.0, EssentialsChat v2.17.1.0, mcMMO v2.1.101, GriefPrevention v16.11.6, PluginLibrary v1.2.1, EnderCore v4.3, ArmorStandTools v3.4.0, Matrix v2.1.3, HolographicDisplays v2.3.3-SNAPSHOT, Duels v3.3.0, MaintenanceSpigot v3.0.2, EssentialsSpawn v2.17.1.0, ChatControl v8.3.11, CrateReloaded 2.0.14 by dinosaur, DonationsHolograms v1.4.2
----------------------------------------------------------------------------------------------

More Information: 
Error reloading ChatControl 8.3.11
IllegalPluginAccessException Plugin attempted to register org.mineacademy.chatcontrol.hook.short@43ef436b while not enabled
	 at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:574)
	 at org.mineacademy.chatcontrol.final.nul. .CON.const(SourceFile:2047)
	 at org.mineacademy.chatcontrol.final.nul. .LpT4.const(SourceFile:45)
	 at org.mineacademy.chatcontrol.final.nul. .com4.const(SourceFile:806)
	 at org.mineacademy.chatcontrol.ChatControl.transient(SourceFile:214)
	 at org.mineacademy.chatcontrol.final.nul. .com4.static(SourceFile:744)
	 at org.mineacademy.chatcontrol.final.nul. .short.const(SourceFile:562)
	 at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:305)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
This error is hiding something else, please post me your entire console log from the reload time.

**Comment by XxPoNaGeXx** [comment]
Please check this issue? Maybe that's related? https://github.com/kangarko/ChatControl-Pro/issues/1353

**Comment by kangarko** [comment]
You still haven't posted your console log, NOT error.log file.

**Comment by XxPoNaGeXx** [comment]
```
17.08 16:43:20 [Multicraft] kyleboyce_ ran command Message of the Day
17.08 16:43:36 [Server] INFO kyleboyce_ issued server command: /msg princesscyr testing
17.08 16:43:36 [Server] INFO ChatControl 8.3.11 encountered an IllegalArgumentException! Please check your error.log and report this issue with the information in that file.
17.08 16:43:36 [Server] INFO java.lang.IllegalArgumentException: Plugin must be enabled to send messages
17.08 16:43:36 [Server] INFO at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:538)
17.08 16:43:36 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:113)
17.08 16:43:36 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:43)
17.08 16:43:36 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .AUX.const(SourceFile:165)
17.08 16:43:36 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:305)
17.08 16:43:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
17.08 16:43:36 [Server] INFO at java.lang.Thread.run(Thread.java:748)
17.08 16:43:36 [Server] INFO !-----------------------------------------------------!
17.08 16:43:36 [Server] INFO Failed to execute command /msg princesscyr testing
17.08 16:43:36 [Server] INFO !-----------------------------------------------------!```

**Comment by XxPoNaGeXx** [comment]
```ChatControl 8.3.11 encountered a COm1! Please check your error.log and report this issue with the information in that file.
17.08 16:47:18 [Server] INFO !-----------------------------------------------------!
17.08 16:47:18 [Server] INFO Error loading configuration in settings.yml!
17.08 16:47:18 [Server] INFO Problematic section: ''
17.08 16:47:18 [Server] INFO Problem: org.mineacademy.chatcontrol.final.nul. .COm1: Report / Settings class already loaded! (see below for more)
17.08 16:47:18 [Server] INFO Plugin is now disabled.
17.08 16:47:18 [Server] INFO !-----------------------------------------------------!
17.08 16:47:18 [Server] INFO Disabling ChatControl v8.3.11```

**Comment by kangarko** [comment]
Seems like ChatControl failed to start, you can't send messages after the plugin has crashed.

Please restart the server and post me the entire startup log, use pastebin.com

**Comment by XxPoNaGeXx** [comment]
Alright

**Comment by XxPoNaGeXx** [comment]
https://paste.gg/p/anonymous/a99fce66559f4d8db98112ded35b679a

**Comment by XxPoNaGeXx** [comment]
Sending messages says "... because player is ignoring you" but they are not.

**Comment by kangarko** [comment]
Alright seems like ChatControl enabled itself correctly there, how did you get it to crash? Post the console input from the exact time of the first error message from CCP.

**Comment by XxPoNaGeXx** [comment]
I fixed that part. It was because I didn't have my bungee server named in the settings.

**Comment by XxPoNaGeXx** [comment]
I've also tried use this 

```Perm: chatcontrol.bypass.togglepm
Info: Enforce sending a private message to the player that has PM's disabled.```

but that doesn't work either

**Comment by kangarko** [comment]
You've already reported that error and it will be patched in the next release.

Thanks for the output, I'll make it so the plugin will print more detailed error message so that you noticed it better.

**Comment by XxPoNaGeXx** [comment]
Alright, when will this be released? Can I downgrade to an older version? 

It's very annoying that I've bought a broken plugin

**Comment by kangarko** [comment]
It'll be released in about an hour. I apology for the trouble. The plugin overall functions it just needs a fix for private messages, the first error you were getting was due to the missing setting option.

**Comment by XxPoNaGeXx** [comment]
Thank you

**Comment by kangarko** [comment]
You're welcome - I just pushed the update ;)
