### ISSUE TITLE
Private Messages Variables

### ISSUE THREAD

**Issue by AntZaro** [kangarko/ChatControl-Pro#1356]
I have a question about private messages. There are those two placeholders {sender} and {receiver}. In the game, it pulls the person's nickname if they have one. Is there a way to get those variables to pull in the username no matter what?

I tried looking through the wiki but I did not even see these two variables mentioned. Apologies if I missed something obvious!

**Comment by kangarko** [comment]
Hello,

at present those are hardcoded to prioritize the player's nick, then his name if they don't have a nick. We may change this feature in the future.

Matej

**Comment by AntZaro** [comment]
Ah ok, thanks for letting me know! In the future, it might be nice to have the option to leave them as usernames. Thanks for all your work on this plugin!

**Comment by kangarko** [comment]
Thank you for your suggestion!
