### ISSUE TITLE
Enable /ignore bypass in /tell on BungeeCord

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#1358]
Fix that if someone ignores you across bungee, you won't be able to message him even when having the bypass ignore permission.

Proposed change: Add a new field at the end of the protocol, boolean with value true if the sender can bypass.

**Comment by Fabrimat** [comment]
I think this should be considered as an issue, not an improvement.

**Comment by kangarko** [comment]
It's not a major issue and due to large work required it's labeled as improvement

**Comment by kangarko** [comment]
Pulled with high priority

**Comment by PsychoLynx** [comment]
Thank you. This is very much appreciated!

**Comment by kangarko** [comment]
Sure! Contributions and volunteers welcome. 

Many suggestions are left in that thread for 2 years but I really want to get this up asap, however with my schedule I am thankful I only had to cut off AutoPlay and Puncher and not all plugins. If you know a dev give him a hint :)
