### ISSUE TITLE
Stupid, but worrying problem. 

### ISSUE THREAD

**Issue by VieuxMulot** [kangarko/ChatControl-Pro#136]
Hi,

I apologise for this basic problem but I am not able to fix it, and make CC work. 
I've tried to edit my channels, and their formats but it does not work, as if I had edited nothing.

Here's a screen of my chat, and of my plugin list.
![capture](https://cloud.githubusercontent.com/assets/22868424/21364162/eef96b44-c6ef-11e6-80cd-d651e6c82645.PNG)

And another, of my chat config file. 
![capture](https://cloud.githubusercontent.com/assets/22868424/21364328/a515b2e8-c6f0-11e6-9af0-e4acb3cd71a7.PNG)

Thanks for your help, I'd like to change my chat. 
NB : Perhaps you've seen, but English is not my mother tongue. Sorry for this!

**Comment by kangarko** [comment]
Some other plugin is interfering with ChatControl. The plugin that causes the prefix '[2:0 PM] [World]', you need to disable first.

**Comment by VieuxMulot** [comment]
Okay, thanks for your answer, I think SimplePrefix is interfering. 
I'm going to disable it and lead new tests.
I'll keep you aware if I meet some new problems.
