### ISSUE TITLE
essentials chat url

### ISSUE THREAD

**Issue by disqetow** [kangarko/ChatControl-Pro#1366]
This plugin didnt support with essentials.chat.url?

AD cant be block with essentials.chat.url
https://imgur.com/a/vvrhXWR

**Comment by kangarko** [comment]
Make sure you gave people that permission, see https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com
