### ISSUE TITLE
Disable color usage in chat

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1371]
I tried denying the following permissions:

chatcontrol.chat.format.color.* 
chatcontrol.chat.format.*

Now they are not able to use color codes within PM's. For the user itself it will show &cTest, for me (the receiver) it still shows WITH color code though.

Thing is, they are still able to use color codes within the normal bungee chat.

**Comment by kangarko** [comment]
May I see your ChatControl ZIP folder please?

**Comment by Sikatsu** [comment]
Yes, here it is: https://www.dropbox.com/s/bsolow9jm4orplb/ChatControl.rar?dl=0

This issue aswell for the chat priorities seem to have started since I switched my server over to Bungee and enabled the Bungee chat.

**Comment by TNTUP** [comment]
Same here. I can send my CC ZIP file aswell on request, don't think that would fix the issue. Using LuckPerms, Denied chatcontrol.chat.format.* and color.*, no luck. (Sorry for hijacking your issue, since it already had one, I didn't bother making one to avoid a duplicate)

**Comment by BenjaminHoegh** [comment]
same as @TNTUP

**Comment by kangarko** [comment]
Closing due to recent update changes, please let me know if you can still experience the issue in private messages. We fixed commands such as /me or others.
