### ISSUE TITLE
ChatControl Blocks tab-complete even for OPs in Bungee

### ISSUE THREAD

**Issue by Krakenazo** [kangarko/ChatControl-Pro#1379]
Hello:

I've had this configuration set up for my paper server, and it never gave any problems... When i decided to convert my server into a bungee network, i suddenly couldn't tab-complete the commands. I tried disabling Packets in the settings.yml, but it still doesn't let me.

Is there something I'm doing wrong or is this a bug?

Thanks!

**Comment by kangarko** [comment]
Set Packets.Tab_Complete.Enabled to false, also ensure you did not accidentally disable it in spigot.yml in tab-complete
