### ISSUE TITLE
[Help] Unicode does not work.

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl-Pro#138]
Why doesn't Unicode work?
```
match value
dont verbose
then replace &b&l \u25ac&7

```
Can then replace use JSON text?
JSON text Unicode is working.

**Comment by kangarko** [comment]
You have to insert the unicode directly, like so:

```
match value
dont verbose
then replace ✰
```

No, "then replace" cannot use JSON because the rest of the message is not in JSON in the event from which it is coming from (e.g. signs, commands, chat), but you can send JSON messages by:

> then console tellraw {player} {"text": "Hello World"}

**Comment by xyblues** [comment]
Thank you very much.
The problem has been solved.
