### ISSUE TITLE
/chc color doesn't work when running with a database enabled

### ISSUE THREAD

**Issue by robot7boy** [kangarko/ChatControl-Pro#1380]
Hello,

Ever since I've enabled my MySQL database connection, whenever my staff or I do /chc color and click on any of the chat color icons, it doesn't seem to change our chat color. Upon closing the GUI we still have our normal white chat color.

**Comment by kangarko** [comment]
Hey, I cannot reproduce the problem, any errors in the console?

Also make sure you restarted after you have enabled that setting. MySQL takes over data.db so the old settings might have got forgotten and no longer used.

**Comment by robot7boy** [comment]
Hey, I didn't have any issues in my console or anything but I also fixed it by removing the old ChatControl_Data from my database. I don't quite know why that resolved the issue quite yet but I am looking into it.

**Comment by kangarko** [comment]
Awesome, maybe you had an older version of the data.

Let me know if you experience any more issues and I am sorry for the inconvenience!
