### ISSUE TITLE
/tag

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1382]
I can't seem to find a name tag plugin that works with chatcontrol, I do see on the wiki a plugin linked there but it is extremely out of date.

Is there a possibility of adding a /tag system or adding support for one?

**Comment by kangarko** [comment]
Not at the very moment, sorry, but we have a system in place to make most plugins work with a bit of customization, see https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
