### ISSUE TITLE
chatcontrol /r conflicts with authme /r

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1383]
Title pretty much sums it up.
If you attempt at registring with /r pw pw with authme, the command doesn't work because apparently it's being interpreted as a msg answer.
Any way I can workaround this? (Ideally disabling cc's /r untill loged in would be great)

**Comment by kangarko** [comment]
Hey,

you can remove the r from Private_Messages.Aliases.Reply in your settings.yml
