### ISSUE TITLE
Bungee_Server_Name Confusion

### ISSUE THREAD

**Issue by BenjaminHoegh** [kangarko/ChatControl-Pro#1384]
You have this ´Bungee_Server_Name ´ and saying it need the server name that I guess is ´server-names´ in the config.yml ? 

I guess these names are the one you use with /server \<servername>

When you have multiple servers I should list them all in `server-names` as I understand, but what name should I write in `Bungee_Server_Name`, the hole list or the name of the specific server

**Example**

If I have my config.yml like this:

    server-names:
      lobby: "lobby"
      survival: "survival"
 
should I then write:

 - lobby server:
   `Bungee_Server_Name: "lobby"`

 - survival server:
   `Bungee_Server_Name: "survival"`

**Comment by kangarko** [comment]
You should write the exact same name in your settings.yml as you have in config.yml of BungeeCord.

For your case it is "lobby" and "survival"
