### ISSUE TITLE
CMI commands stuck on "Please wait 1 second."

### ISSUE THREAD

**Issue by Laos1996** [kangarko/ChatControl-Pro#139]
Players have issues with Content Management Interface plugin. When they try to execute commands such as /colors or /charges it will print out message saying "Please wait 1 second." which doesen't go away at all.
I managed to "fix it" when i reloaded completely ChatControl-Pro, but on restart this issue came back. I don't see any console errors.

**Comment by EvilOlaf** [comment]
Add particular commands to the Whitelist in your chc configuration.

**Comment by Laos1996** [comment]
Well I added it inside settings.yml at Anti-Spam both inside  Whitelist_Similarity: and Whitelist_Delay:
No effect, still happening.

**Comment by EvilOlaf** [comment]
Can you paste us your  `settings.yml` as well as the stuff ask for at the contribution guidelines?

https://github.com/kangarko/ChatControl-Pro/blob/master/CONTRIBUTING.md

**Comment by kangarko** [comment]
I would like to see your settings.yml as well.

If it still doesn't work, please try changing [priorities](https://github.com/kangarko/ChatControl/wiki#priorities-townyfactions-rules-channels-or-chat-is-overlapping--dont-show-or-show-when-not-supposed-to) of Checker to either LOWEST or HIGHEST or even MONITOR.

**Comment by Laos1996** [comment]
https://hastebin.com/nedanakoze.php

Version right now (Used PaperSpigot till now, same issue);
CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

Plugin that it interferes with;
https://www.spigotmc.org/resources/content-management-interface.3742/

**Comment by kangarko** [comment]
Try changing priorities as I mentioned above. The plugin is premium so I can't test it, sorry.

**Comment by kangarko** [comment]
Closing. Please remind me if issue still persist.
