### ISSUE TITLE
[Request] Sound on notify

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1393]
I would like to play a sound when a rule is caught. That part is easy. Only the sound goes to the player causing the rule.

Example:
```
match \bstaff\b
then notify chatcontrol.notify.rulesalert &8[&7Staff&8] &7{player}&f: &7{message}
then sound BLOCK_NOTE_BLOCK_BASS, 1.0, 1.0
```

I would like to play this sound only to those with the 'chatcontrol.notify.rulesalert` permission.
Can this be done with ChatControl?

**Comment by kangarko** [comment]
Hey, sure, you can use the "then sound" operator:

# then sound <bukkitSoundName>, <volume>, <pitch> (Plays a sound to the player. Example: 'then sound ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1')

**Comment by x1p** [comment]
Not according to my tests.

The sound is played to the player who wrote the message containing the key word. 

I would like to have the sound played only ro those who have the notify permissions aka Staff.

**Comment by kangarko** [comment]
Oh I see, sorry this is not possible at the moment, I can put it into the roadmap.
