### ISSUE TITLE
[Question] is ChatControlPro can making "all plugins have no permission will replace a custom text" ?

### ISSUE THREAD

**Issue by NightPrimez** [kangarko/ChatControl-Pro#1396]
is ChatControlPro can making "all plugins have no permission will replace a custom text" ?
.
: i want to making all plugin command which have no permission text to replace same text all

(sry for bad english)

**Comment by kangarko** [comment]
Yes, there is a packet rule in rules/packets.txt like that, you can remove or change it:

![a](https://i.imgur.com/OVKbNjt.png)
