### ISSUE TITLE
Chatcontrol quit event need to be optmized (Mysql)

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1397]
Just see the spikes https://timings.aikar.co/?id=55d2e11a8948414ca657aa09f907bd1d

The event ChatControl::Event: o.m.c.f.n. .A (PlayerQuitEvent) need optrimization, (using chatcontrol 3.8.6 + 1.8.8)

**Comment by kangarko** [comment]
Due to past events where the mysql would cause instability, we now enforce the connection to be run on the main thread. There is no workaround/quick fix but once the system is redone from scratch this will be handled differently.
