### ISSUE TITLE
Quick question about lic.

### ISSUE THREAD

**Issue by TDStewart** [kangarko/ChatControl-Pro#1398]
Hello,  I have purchased CCP and have it on a server that is only open to my family.  I'm working on setting up another server that is also currently only open to my family but is not a bungee network.  It might be opened to public and might become bungee networked in the future, not sure.  Might just bungee network for the family.  Really not sure yet.  

1.  My question is do I need more than 1 lic. 
2.  If so how do I obtain more.  SpigotMC only allows one purchase.  
3.  Also if I setup a test server (would be a dupe of my family server for testing new mods before installing to family server) will it need a separate lic.

**Comment by kangarko** [comment]
You can just use one ChatControl Pro for all of your servers for now, that's easiest ;)
