### ISSUE TITLE
Problem with Chatcontrol chat.yml rules

### ISSUE THREAD

**Issue by OGreenC** [kangarko/ChatControl-Pro#1399]
I've been trying to moderate my chat, using chatcontrol. Therefore I would like to trigger on certain words/sentences.

While writing these rules, I realised that the rules somehow does not trigger on the letters "æ ø å", which is heavily used in Danish, which is the primary language of our server.

Does the rules not support UTF-8?

I wrote the following rule in /plugins/ChatControl/rules/chat.yml:

match (test1|test2) (1|2|får)
then deny

When I type, say "test1 1", the message is denied, and therefore not shown in the chat.
But when I type, say "test1 får", the message gets displayed in chat.

Any Ideas as to why this is?

**Comment by kangarko** [comment]
Hey, try toggling Translate_Diacritical_Marks and Regex_Unicode options in settings.yml (disable if enabled or vice versa until you find a combination that will match :) )
