### ISSUE TITLE
Cannot mute

### ISSUE THREAD

**Issue by jaboy** [kangarko/ChatControl-Pro#14]
Hello

This is a continuation of this
https://www.spigotmc.org/threads/chatcontrol-pro-80th-update-600-downloads-sale-paid.82298/page-55#post-1403298
and this
https://www.spigotmc.org/threads/chatcontrol-pro-80th-update-600-downloads-sale-paid.82298/page-56#post-1407929

i tried setting my formatter to HIGH, and now players cannot chat if muted and you are using local only chat.
but if they are using the bungee (global) chat, then they can still talk without problems :C

**Comment by kangarko** [comment]
You mean if they use /chc global ? Well, then there's little I can do because the plugin is 'blind' and don't see if the player actually can write. The event system is like a pipeline where the things can work concurrently without seeing each other. I cannot do this there, I am sorry.
I am leaving open for maybe-future fixes.

**Comment by jaboy** [comment]
i am a little confused by this :P

since i can turn off "sending chat to bungee" in the configuration, it has to be because the plugin on the spigot server sends the chat to bungee, why cant the spigot server check permissions before sending to bungee ?

if its because you are checking permissions by actually starting the message event and then see if it is cancelled, then send it on the local server first, if it is not canceled, then send it to bungee.

i am aware that it can be hard on another servers to check permissions when the message gets there via bungee, but if i didnt want the player to chat on the other servers, i would just have to make sure i use a global mute plugin that will locally mute him on all servers.

**Comment by jaboy** [comment]
and if it is still impossible, is there any mute plugin out there that can mute the players on bungee ?

**Comment by kangarko** [comment]
When can they talk even if muted? If executing /chc global command, in chat channels or in regular chat ? Can you send me the effective parts of your settings.yml and chat.yml respectively.
I honestly give this little chance to be fixed within the plugin. Idk many bungee plugins, but I am sure there are lots of (free) ones that offer mute functionality.

**Comment by jaboy** [comment]
my settings http://pastebin.com/NGfR4dYs
my chat http://pastebin.com/BJfZmE9z

as you see in my settings, i have
Bungee_Chat:
  Enabled_By_Default: true

if i mute from ban-management, players can still talk both on local and with bungee.
as a test, i attempt to use /chc g switch (turn off bungee) and then the player could no longer chat.

**Comment by EvilOlaf** [comment]
Set your listener priorities both to HIGH

**Comment by kangarko** [comment]
Can you also try setting the Formatter's priority to HIGHEST and MONITOR? (Always restart the server after doing so.)

**Comment by jaboy** [comment]
Setting the formatters priority didnt seem to help, but when i set the checkers priority to highest, then it worked, players are now muted on both local and bungee chat, thank you :3
