### ISSUE TITLE
[Question]Then rewrite how to wrap?

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl-Pro#140]
I try to use \n to wrap, but it doesn't work.
![z5_ m14k6 rh 2gpy05](https://cloud.githubusercontent.com/assets/15712089/21483371/f0acc154-cbbb-11e6-8b12-6b3f55325a10.png)

**Comment by kangarko** [comment]
It seems like your system does not support the standard line divider. You can enforce it by setting **Enforce_New_Line** to **true** in settings.yml

**Comment by xyblues** [comment]
Still not working, I have saved and restarted the server.
![image](https://cloud.githubusercontent.com/assets/15712089/21487791/f0bb2d18-cc0e-11e6-90b7-6a0e22518e91.png)
![image](https://cloud.githubusercontent.com/assets/15712089/21487793/0aaa4678-cc0f-11e6-8b23-e1975380fb64.png)
![image](https://cloud.githubusercontent.com/assets/15712089/21487798/3b4e6598-cc0f-11e6-8291-6658f4c0dd77.png)

**Comment by xyblues** [comment]
then console tellraw does not support this feature.
![image](https://cloud.githubusercontent.com/assets/15712089/21495474/a422a956-cc52-11e6-843c-1914eeadc781.png)

**Comment by kangarko** [comment]
I am sorry, I just reviewed how the bukkit API works and yes, \n is not function in the player's chat.

The console tellraw is working for me, including regex groups. Example (packet rule):

match (You do not have access to that) (.*)
then console tellraw {player} {"text":"&cMissing permission for that $2"}

**Comment by xyblues** [comment]
![image](https://cloud.githubusercontent.com/assets/15712089/21710728/7366a710-d425-11e6-9d7c-c194a38b871c.png)

`match value='@QTVIP', outdated='(.*)'
then console tellraw {player} {"text":"&b&l ▬ &7权限组: &b&l青铜VIP &7过期时间: &b&l$2"}`

![image](https://cloud.githubusercontent.com/assets/15712089/21710846/1a748144-d426-11e6-9b31-6e6d9f6445e1.png)

Why doesn't it work?

**Comment by kangarko** [comment]
There's no such syntax in the 'match' operator. You only match the message directly:

`match @QTVIP`

**Comment by kangarko** [comment]
Closing. Remind me if any issues.
