### ISSUE TITLE
Quick question about ignore string and before strip

### ISSUE THREAD

**Issue by AudioPlugged** [kangarko/ChatControl-Pro#1400]
PaperSpigot 1.8.8
Chatcontrol Pro 8.3.18

Is it by any chance possible to make the following rule work?

```# Blocks 'anal'
match (a+(\W|\d|_)*n+(\W|\d|_)*a+(\W|\d|_)*l+(\W|\d|_)*)
ignore string analog|an all
before strip \s*
handle as swear
```

It ignores analog fine but an all gets blocked because of before strip \s* - is there any way to make the ignore string run before it removes the space, or is there another way to make this work?

**Comment by kangarko** [comment]
Sorry, this is the combination on how this works, it's hardcoded:

1. Strip before
2. Replace before
3. Ignore string
4. Replace diacritics

![a](https://i.imgur.com/MPWQMyW.png)

**Comment by AudioPlugged** [comment]
Thank you for clarifying this! I guess I’ll just use one of them instead of both at the same time 🙂

Have a great day!
