### ISSUE TITLE
chatcontrol priority and other games

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1405]
I noticed  chatcontrol formatation with also lowest prioriity it keep to overwrite  the other plugin like murder games, i have to disable chatcontrol format and use ChatFormat plugin that work perfect (outside games it show formated chat, inside game the game chat)

**Comment by kangarko** [comment]
Hello,

have you tried the other priorities such as LOW, NORMAL, HIGH, HIGHEST and even MONITOR? If these don't work then unfortunately it's a major incompatibility and you can use another plugin for that part.

**Comment by xion87** [comment]
yeah i tried all stuff it don't work

**Comment by kangarko** [comment]
I am sorry, seems like the other plugin is listening on a priority that makes us incompatible. Just use yoru chat format for the time being.
