### ISSUE TITLE
1.14.4 My emoticons :) are just showing as ?

### ISSUE THREAD

**Issue by rybuilder23** [kangarko/ChatControl-Pro#1406]
When I type things such as :) and <3 it does not convert to emoticons. Is there anything I can do to fix this?

chatcontrol version: 8.3.19
paper: git-Paper-192 (MC: 1.14.4)

i regenerate my files chaned noting still doest work.
i open and saves the files with notepad++

my chatcontrol folder ( new generated )
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3639433/ChatControl.zip)
screen:
http://prntscr.com/p9be53

**Comment by kangarko** [comment]
Please use UTF-8 encoding when saving your files, see https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
