### ISSUE TITLE
[Suggestion] Toggle chat colors

### ISSUE THREAD

**Issue by SiuanSong** [kangarko/ChatControl-Pro#1409]
Add a toggle command to hide color codes in chat.
I've found that most of my community is split 50/50 on whether they like colored chat or not.  If possible, I figured it'd be a nice little addition so that players who don't like rainbow chat don't have to have their eyes hurting. lol

**Comment by kangarko** [comment]
Thank you for suggesting! We already pulled all suggestions into the next major version (and there's a lot!) but you are free to re-suggest in the Winter when we start accepting new ideas!

**Comment by SiuanSong** [comment]
Alrighty, I'll probably never remember, but thanks for letting me know you aren't accepting suggestions right now.  I'll try to remember in the next coming months.
