### ISSUE TITLE
How to make capital letters get marked as well? (Chat Filters)

### ISSUE THREAD

**Issue by Disorbs** [kangarko/ChatControl-Pro#1410]
Trying to block some racist words but with this it lets ones that are capitalized letters get through but for now i fixed it by re-adding the same block with capital letters but i thought the \W works for numbers and caps? because i also had to add \* to block numbers.

`\b(n+(\W|\d|_)*(i|\*|\_|-|)+(\W|\d|_)*g+(\W|\d|_)*(e|\*|\_|-|)+(\W|\d|_)*r+(\W|\d|_)*)`

it doesn't block the following ones in capital * is the letter but i removed it for this post

```
N*GG*R
N*G*R
```
Server: 1.14.4 paper

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3666234/ChatControl.zip)

**Comment by kangarko** [comment]
Hey,

I have tested the uppercase variations without OP or special permissions using your setup, and it did get blocked.

![a](https://i.imgur.com/fk0x2eR.png)

What's your console output when the message should be filtered but isn't ?

**Comment by Disorbs** [comment]
actually i didnt test this in-game i was using Regex101 at the time to test it and it wasn't working there for me so idk if thats different but ill try adding it on the server and testing it there

**Comment by kangarko** [comment]
Assuming it works in game, let me know if it does not below
