### ISSUE TITLE
"You lack permissions to send chat messages."

### ISSUE THREAD

**Issue by UnknowngrimR** [kangarko/ChatControl-Pro#1412]
I've recently gotten UltaPermissions and I cannot speak with ChatControlPro enabled, everytime I try to speak I get the same message, "You lack permissions to send chat messages." until I disable ChatControlPro and it lets me talk in chat. Is there a permission that I am missing? I've went through all of the perms and none of them let me speak until I decided to disable the plugin. Anything will help, thanks! ;p

- Grim

**Comment by kangarko** [comment]
Hello,

it's chatcontrol.chat.write and chatcontrol.chat.read permissions :)
