### ISSUE TITLE
ChatControl not letting people use /gamemode, /gm, etc

### ISSUE THREAD

**Issue by Alastowor** [kangarko/ChatControl-Pro#1415]
**Version: 1.14.4
Running PaperSpigot.**

Howdy, so I had this issue for a while and somehow found the issue in another plugin's issue tracker. Apparently, ChatControl does not let people use /gamemode, /gm, etc. I unloaded the plugin, and it instantly worked for all users. Even operators and ranks with the * permission node can't use it until I unload that plugin. Checked it in `/lp verbose on essentials.gamemode` and everything came up just fine.

How would I go on about fixing this as I paid for this plugin and don't it to go to waste?
Plugin list: https://pastebin.com/ZW0fp49j
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3683611/ChatControl.zip)

**Comment by kangarko** [comment]
Please review your rules/command.txt file, you will find the following rule there, just remove it:

```aml
match ^/(gm|gamemode)
ignore perm chatcontrol.bypass.rules
id /gm
then warn &aThat would be nice, wouldn't it?
then notify chatcontrol.notify.rulesalert &8[&7ID %ruleID&8] &7%player: &f%message
then deny
then log
```
