### ISSUE TITLE
Replace text correctly

### ISSUE THREAD

**Issue by OriginersMc** [kangarko/ChatControl-Pro#1417]
Hi!

I getting some problems to replace the next text:

Original text:
![image](https://user-images.githubusercontent.com/13259577/66233105-d0b88480-e6ea-11e9-9b04-84dec48c1d49.png)

Text I want writte:
![image](https://user-images.githubusercontent.com/13259577/66233118-dada8300-e6ea-11e9-81a8-7ff34fef7fdd.png)

How I can do that?

I tried something and nothing.
TIP: is important respect colors.

Best regards

**Comment by kangarko** [comment]
Hello,

I am sorry but packet rules cannot replace the message respecting colors. You can try using regular expressions groups and then putting it into the message. Regular expressions are international language so you can google or ask on Spigot forums, I am not that good at them.

match (El modo de juego de )(.*)( ha side cambiado a )(.*)
then replace El mode de joc de $1 ha sigut canviat a $2

Or try increasing the numbers in $ as well.

**Comment by OriginersMc** [comment]
I copied and paster code you give me, and now don't change nothing.

**Comment by OriginersMc** [comment]
Hi
fixed.

How I can add a break line/new line on then replace message?

**Comment by kangarko** [comment]
Hey! I am sorry for a late reply. You can use the \n character, but if that does not work you can set Enforce_New_Line to true in settings.yml and see if that helps :) If it does not help then unfortunately it's not possible on your system.
