### ISSUE TITLE
join in the game Hover

### ISSUE THREAD

**Issue by calf8876** [kangarko/ChatControl-Pro#1418]
I want to ask when the player enters the game.
Show [calf8952 join the game]
calf8952 Above Can I display information using Hover_Event?
If so, how to set up the yml file

**Comment by kangarko** [comment]
Hey,

either you can write the JSON literally as per https://github.com/kangarko/ChatControl-Pro/wiki/JSON or you can try creating a new format in formatting.yml and then referring it's name in the specific join message, but I am not sure if we got this feature to work.

**Comment by calf8876** [comment]
I love you , I successfully used it. 
Once I learn to use it, it's really worth buying. This is also the first plug-in I bought in my life. Although it was a bit complicated at first, everything needs to be learned.
