### ISSUE TITLE
Admin channel discord duplication reload

### ISSUE THREAD

**Issue by KyroOW** [kangarko/ChatControl-Pro#1419]
The messages from Discord to ingame Admin channel will get duplicated with every reload of the plugin, for example, if i reload the plugin twice, from now on all the messages from discord to ingame admin channel will be sent twice, if i reload 50 times, messages will be sent 50 times.

I'm using 1.12.2 Paper

**Comment by kangarko** [comment]
Thank you for reporting, this problem will be resolved within the next 1-2 hours.
