### ISSUE TITLE
Server stops responding and crash when using multiple color format on private messages

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl-Pro#1421]
Although players can't use color on messages:

`[08:24:48] [Server thread/INFO]: rico issued server command: /msg mikenex10 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 &2 hola
`

And it crashes.

https://pastebin.com/rse03K8H

**Comment by kangarko** [comment]
Sorry I cannot reproduce this problem

![a](https://i.imgur.com/7i8047Y.png)

We will remove the automatic replacing of color codes as it creates unnecessary space. This should solve the issue you are observing.
