### ISSUE TITLE
ChatControl Color_Menu

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#1422]
The shulker boxes show up on 1.12.2 as white, while on 1.13.2 and 1.14.4 they show up with their color.
Would be cool if it could behave the same on both 1.12.2 and 1.14.4

ChatControl Pro version: 8.4.1

https://prnt.sc/pishkg

**Comment by kangarko** [comment]
I apology but due to material naming changes it is not possible to correctly render colors on these Minecraft versions. We are still supporting old Minecraft but some features are stripped.
