### ISSUE TITLE
[1.14.4] Plugin detects the letter ı as i

### ISSUE THREAD

**Issue by darkjoya** [kangarko/ChatControl-Pro#1424]
In Turkish Alphabet we have İ and ı. Im trying to create some bad word rules. When player try to write sık plugin detects word as sik and prevents write this word. I tried this string "ignore string sık" but this time player starts write sik.

I tried both "Translate_Diacritical_Marks: true and false"
I tried both "Ignore_Special_Characters: true and false"

ChatControl Folder:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3731332/ChatControl.zip)

**Comment by kangarko** [comment]
There is some internal optimization of the regular expression which merges those two symbols together. I apology, there's currently not known solution, you'll have to try to use the 'ignore string' to the extent possible, if any.
