### ISSUE TITLE
Swear word not blocked if formatting is enabled

### ISSUE THREAD

**Issue by HapCave** [kangarko/ChatControl-Pro#1425]
Paper 1.14.4
ChatControl Pro 8.4.2
LuckPerms 4.4.1

When I set Enabled to false in formatting.yml, the swear catch works as expected with the swear word not showing in the chat. When Enabled is set to true, the formats display properly, but the chat line is displayed to all users with the swear word showing. The formatted chat message is using my LuckPerms prefixes.

I've been using ChatControl Pro since before 6.4.1.  Please advise.
Thanks

[latest (with formatting enabled).log](https://github.com/kangarko/ChatControl-Pro/files/3731960/latest.with.formatting.enabled.log)
[latest (with formatting not enabled).log](https://github.com/kangarko/ChatControl-Pro/files/3731961/latest.with.formatting.not.enabled.log)
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3731962/ChatControl.zip)
[LuckPerms.zip](https://github.com/kangarko/ChatControl-Pro/files/3731963/LuckPerms.zip)

**Comment by kangarko** [comment]
Do you have any other chat related plugin?

```
Listener_Priority:
  Signs: HIGHEST
  Checker: NORMAL
  Formatter: NORMAL
```

Try putting the Checker priority in your settings.yml to HIGH, if that does not help try leaving it on NORMAL and set Formatter to HIGH

**Comment by HapCave** [comment]
Solved. I tried setting Checker to HIGH, but the startup threw an error saying Checker can't be higher than Formatter. When I set Checker back to NORMAL and Formatter to HIGH, it worked. Thanks for the quick response. By the way, I don't have any other chat-related plugin since I upgraded to PaperMC.
