### ISSUE TITLE
Nicky prefix dont' work

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1428]
I noticed the nick of the plugins nicky don't add the nick prefix (prefix: '&e~') , time ago was working, i am using {nick} on chatcontrol format.
Using 8.3.6 chatcontrol and latest nicky

**Comment by kangarko** [comment]
How are you getting the prefix? Does just using {nick} work for Nicky?

**Comment by xion87** [comment]
i only get the nick of nicky without the prefix  '~'

**Comment by kangarko** [comment]
I apology for a late reply!

I understand, unfortunately that isn't what we're getting through the API, so I am afraid there's nothing that can be done. Maybe you can try using PlaceholderAPI if they provide that additional nick-related letter.

**Comment by xion87** [comment]
I just noticed, using nicky 0.6.9 the prefix work perfect, instead after the rewrited nicky 0.7.0 the prefix is gone, not sure where is the fault

**Comment by kangarko** [comment]
It looks like a bug on their side, we are indeed hooking into the 0.7 version.

**Comment by xion87** [comment]
Thank you I will downgrade and try to contact author
