### ISSUE TITLE
I don't understand help please

### ISSUE THREAD

**Issue by Darck19831** [kangarko/ChatControl-Pro#1429]
I don't know how to censor the swear words, could you please help me 

Anti_Bot:
  Cooldown:
    Rejoin: 4
    Chat_After_Login: 1
    Command_After_Login: 1
  Block_Chat_Until_Moved: true
  Block_Commands_Until_Moved:
  - /afk
  - /me
  - /warp
  - /spawn
  - /tpa
  - /tpaccept
  - /helpop
  - /sethome
  - /home
  Show_Quit_Message_Only_If_Logged: true
  Block_Signs_With_Same_Text: true
  Disallowed_Nicknames:
  - (f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)\perra
  - (p+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*r+(\W|\d|_)*a+(\W|\d|_)*)
  - asshole
  - PERRA

**Comment by kangarko** [comment]
Hello,

I recommend you use the /chc addrule swear command to add new swear words to be blocked. Or you can edit your rules/rules.txt file manually.
