### ISSUE TITLE
Create CLICK on chat

### ISSUE THREAD

**Issue by OriginersMc** [kangarko/ChatControl-Pro#1432]
Hi

Here when user use command /warps
Image shows when user uses commands /warps
![image](https://user-images.githubusercontent.com/13259577/67158898-77815f80-f33e-11e9-8871-293e02ca1635.png)

I want, when user click to Surv text on chat, executes commands /warps Surv.

How I can do that?

**Comment by kangarko** [comment]
Hello,

you can create a command rule and then send the raw JSON output, see "JSON in Rules" and see the link on top of that page for JSON generator: https://github.com/kangarko/ChatControl-Pro/wiki/JSON

Matej
