### ISSUE TITLE
Paper#221 1.14.4: ChatControl unregisters towny /t command.

### ISSUE THREAD

**Issue by GeertBraakman** [kangarko/ChatControl-Pro#1436]
Hello, when i startup my minecraft server I get this message:
![image](https://user-images.githubusercontent.com/36223190/67368148-1d1f1380-f577-11e9-9f59-b222c3b23396.png)
That tells me that ChatControl can't unregister `/t` from towny. Thats ok because i want that command reserved for towny. But when I go in-game and execute the `/t` command it is not registerd.

![image](https://user-images.githubusercontent.com/36223190/67368301-61aaaf00-f577-11e9-933e-868db0015d4c.png)

ChatControl version: _8.4.4-BETA_
Towny version: _0.93.0.0_

Last ChatControl version I know that worked was _8.3.20_

I also have the `/t` command not in my `settings.yml` so ChatControl shoudn't even try to unregister it right?

[Settings.yml](https://pastebin.com/EkfefaUq)

I hope i gave you enough information. And i hope you can fix this because the `/t` command is now not working on my server.

**Comment by kangarko** [comment]
Thanks, I solved that in the next release.
