### ISSUE TITLE
ProtocolLib support problem

### ISSUE THREAD

**Issue by FastJoe0** [kangarko/ChatControl-Pro#144]
Players are kick out by the plugin with the message "Empty Packet!" when they click to ender crystal 

Log from bungeecord - https://hastebin.com/pasiwaheho.lua

When I removed chatcontrol, it's all worked normally.

**Comment by kangarko** [comment]
I don't believe it's caused by ChatControl, because Chatcontrol does nothing when player click ender crystals.

Please ensure your bungee version is the latest version, also your server is up-to-date.

**Comment by FastJoe0** [comment]
Your plugin doesn't accept empty packets. I have PaperSpigot 1.7.10 (protocol hack). Changing the BungeeCord version gives nothing.

**Comment by kangarko** [comment]
Empty packets are ignored. ChatControl operators on bukkit only. BungeeControlBridge does not have any feature that deals with packets.

**Comment by FastJoe0** [comment]
But what is it packets.txt? Maybe this has something to do with this error.

**Comment by FastJoe0** [comment]
I checked it thoroughly. The error doesn't occur when I install only ChatControl (without ProtocolLib). If I add ProtocolLib, the error appears and the player is kicked. If I only have ProtocolLib without ChatControl error doesn't occur and everything works normally. There must be something with the ProtocolLib support.

**Comment by kangarko** [comment]
What server type and minecraft version are you using?

**Comment by FastJoe0** [comment]
Survival and I use PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by kangarko** [comment]
I see. I was not able to reproduce it, but I would say that the 'protocol hack' version makes the packet feature incompatible. I apologies, I don't have time nor energy to research an old version and make it compatible in a special way. At present, I would advise you to disable the Packet feature completely (settings.yml --> Packets.Enabled to false), 

A side note, I would recommend you replacing the 1.7.10 protocol hack with either https://www.spigotmc.org/resources/protocolsupport.7201/ that allows older clients to connect, or ViaVersion that allows never clients to connect, all running a clear spigot build where the packets are unattended.
