### ISSUE TITLE
JSON in BungeeControl?

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl-Pro#1440]
Hello!

I am trying to set up BungeeControl join messages to use JSON, but so far I've had no luck. I was wondering if this is even technically possible to achieve with BungeeControl or if I am doing something wrong.

I've tried both:

  join-target: |-
    [JSON]
    ["",{"text":"Hello World","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"This is a test!"}]}}}]

And
  join-target: '[JSON] {"text": "Hello World"}'

**Comment by kangarko** [comment]
Hello!

I personally apology, it is not possible to send json messages using JSON in the BungeeControl plugin.

Matej

**Comment by PsychoLynx** [comment]
Thanks for confirming. I will figure out another way, then.
