### ISSUE TITLE
Quest Creator Issues/Compatibility

### ISSUE THREAD

**Issue by AkiraKokiri** [kangarko/ChatControl-Pro#1442]
I spoke with the Quest Creator dev about this issue I have been having where the chat event is not being properly triggered/detected when sending messages in a channel that is set as the default sending channel in CCP. 

Here are my channel and config files:
https://pastebin.com/Wj0dK7qb   ---- Chat Control Pro config
https://pastebin.com/b1MnW1c0   ---- Chat Control Pro channels

I am on the latest version of both Quest Creator and of CCP as well as 1.14.4 MC Paper

Here is my log that shows the issue: https://pastebin.com/81f2npCR

What is happening is I am sending messages automatically to the global channel but the chat event is not being received by QC supposedly. This is seen in lines 21, 24 etc. 

However when using the command **/ch send global TEXT**, the chat event is picked up by QC. 
This is seen in lines 37 through 42

They believe this to be an issue on CCP's side so they asked me to talk to you guys.

**Comment by kangarko** [comment]
Hello!

It seems like there's a priority issue. ChatControl sends the chat in its own unique way, thus it cancels the event for other plugins.

You can take a look at this article, and try editing Formatter priorities to be LOWEST, LOWER or HIGHEST to test whether one of these combinations will work.

https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
