### ISSUE TITLE
Enforce global chat using bungee

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [kangarko/ChatControl-Pro#1443]
Is it possible to enforce using bungee global chat? If not - it would be lovely feature <3

**Comment by kangarko** [comment]
Yes it is.

Give players negative chatcontrol.command.bungeechat permission and set Bungee_Chat.Enabled_By_Default to false in settings.yml. That way, they are automatically joined the bungee chat and cannot leave.

**Comment by kangarko** [comment]
Ups, I meant Bungee_Chat.Enabled_By_Default to **true**.
