### ISSUE TITLE
Group formats - forced chat color

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#1444]
Hey!

I had an idea just like groups having the Sound notify setting but instead, it'll be the chat colour and it'll overwrite whatever the user has in /chc color

Example of config:

    Vip: 
      Message: "&6* "
      **Chat_Color: 'DARK_RED'**
      Condition: 'player.hasPermission("chatcontrol.groups.vip")'
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&6This player is VIP"
          - "&6Check out &e/web &6to obtain VIP"

**Comment by kangarko** [comment]
Thank you for your suggestion, but this can already be achieved by a simple format part that sends a message starting with the chat color in the format.

**Comment by HexedHero** [comment]
> Thank you for your suggestion, but this can already be achieved by a simple format part that sends a message starting with the chat color in the format.

you mean something like
'&6{message}'
because this doesn't overwrite the players /chc color if they have it selected

**Comment by kangarko** [comment]
No it does not, this is not supported at the moment, sorry.
