### ISSUE TITLE
Block flood message ?

### ISSUE THREAD

**Issue by Flashback083** [kangarko/ChatControl-Pro#1447]
Hello ! First, sorry if the feature is already in, but i dont see it at all T.T
There is a way to prevent flood message ? 
Like :  
coooooooooool will be denied and we can set a limit for same character in same message 🤔 
thanks for your reply !

**Comment by kangarko** [comment]
Yes it is there, please see rules/chat.txt 

![a](https://i.imgur.com/ZHlUSh2.png)
