### ISSUE TITLE
1.14.4 - Bypass togglepm not working

### ISSUE THREAD

**Issue by Kaassss** [kangarko/ChatControl-Pro#1449]
ChatControl Pro version 8.4.6
BungeeCord version git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9e76966:1421

Players with the permission chatcontrol.bypass.togglepm set to true are not able to send messages to people with PMs disabled. (Even as an admin with all permissions the messages get blocked.)

My ChatControl folder:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3842723/ChatControl.zip)

**Comment by kangarko** [comment]
This is a known issue over BungeeCord. This is not happening within a single server. A fix is planned in the roadmap.

https://github.com/kangarko/ChatControl-Pro/issues/1358
