### ISSUE TITLE
Players added to chatchannels whitout permisson for it

### ISSUE THREAD

**Issue by GeertBraakman** [kangarko/ChatControl-Pro#1451]
Hello,
I have this problem on my server where players get randomly added to the admin channel in read mode. They don't have any permission for this and i cant figure out why. When I remove those persons from the channel they will join back the next time they login. I think it has something to do with the storage but idk how there names come in there.

![image](https://user-images.githubusercontent.com/36223190/69014424-63a33a80-098a-11ea-955e-a08c5b36db23.png)
Only x313 and koolbraza should be able to read the adminchat here. The rest is added randomly. Its only a couple of players.

I have a debug file of 13mb with the channel-join debug option on, but i coudnt get any wiser from that. I hope you will be able to help me, because now my players can read the admin chat.

Thanks, x313

**Comment by kangarko** [comment]
Please use pastebin.com to upload the channel-join debug messages only from the time someone joins and they are put in the channels they are not supposed to have.

**Comment by GeertBraakman** [comment]
Sorry for the late reaction, i was really bussy with school.

Here is the pastbin link:
https://pastebin.com/YuBeHFQ2

The first in the pastbin was the last time he didnt have adminchat
after the next he had admin chat. without permission. And the last is the channels join after that.

**Comment by lackoSK** [comment]
Hello,

You permitted them to read six channels, so they are reading them.

Just remove them permission to join the chat you don't want to make them able to read.

Regards,
lackoSK

**Comment by GeertBraakman** [comment]
No, i dont gave them the permission to join the admin chat. 
Channels:
![image](https://user-images.githubusercontent.com/36223190/70602019-bec7f600-1bf3-11ea-97cd-b721d04976f1.png)

Permissions they have:
```YAML
- chatcontrol.channel.aurain
- chatcontrol.channel.aurain.join.read
- chatcontrol.channel.aurain.join.write
- chatcontrol.channel.aurain.send
- chatcontrol.channel.autojoin.aurain.read
- chatcontrol.channel.autojoin.aurain.write
- chatcontrol.channel.autojoin.nation.read
- chatcontrol.channel.autojoin.standard.read
- chatcontrol.channel.autojoin.standard.write
- chatcontrol.channel.autojoin.town.read
- chatcontrol.channel.nation
- chatcontrol.channel.nation.join
- chatcontrol.channel.nation.join.read
- chatcontrol.channel.nation.join.write
- chatcontrol.channel.nation.send
- chatcontrol.channel.standard
- chatcontrol.channel.standard.join
- chatcontrol.channel.standard.join.read
- chatcontrol.channel.standard.join.write
- chatcontrol.channel.standard.send
- chatcontrol.channel.town
- chatcontrol.channel.town.join
- chatcontrol.channel.town.join.write
- chatcontrol.channel.town.send```

**Comment by lackoSK** [comment]
Hey,

Thanks for reporting the issue, can you set the channel-join to debug in settings.yml and send me the debug.log file? 

Also please, include whole ChatControl folder.

Thanks
