### ISSUE TITLE
1.14.4 Duplicated chat in Bungee

### ISSUE THREAD

**Issue by Thrashjoking** [kangarko/ChatControl-Pro#1452]
![bug](https://user-images.githubusercontent.com/57519648/69361149-9f7c1f80-0c6a-11ea-8c1a-d16b3c582f32.PNG)
Hi, the chat in another bungee server shows whitout formating and duplicated. I didn't find any error in the logs. 
[ChatControl (1).zip](https://github.com/kangarko/ChatControl-Pro/files/3875926/ChatControl.1.zip)
ChatControl 8.4.6

**Comment by kangarko** [comment]
Please update to latest ChatControl and verify you have latest BungeeControl as well, thanks.
