### ISSUE TITLE
Remove/Delete Messages

### ISSUE THREAD

**Issue by M0-Craft** [kangarko/ChatControl-Pro#1455]
Hello.

I'd like to offer a feature for the plugin, that is - message deleting.
Not exactly sure about implementation, maybe if you have the required permission and the feature is enabled you would be able to see an [x] (change-able) button right before the message, i.e:
[x] [PREFIX] Nickname » Message

Thank you for your time in advance.

**Comment by kangarko** [comment]
Hello,

Thank you for your suggestion. It's fairly complicated since it requires the whole chat history to be stored for each player then rewritten completely and sent back once that button is clicked. We have a small team and we decided no to include this feature right now.

Matej
