### ISSUE TITLE
1.14.4: Help with ChatControl/rules/commands

### ISSUE THREAD

**Issue by OperatorValexio** [kangarko/ChatControl-Pro#1456]
Hello, I am working on the commands.txt file and am having an issue with trying to block a certain command. I am able to successfully block all of my other desired commands however I am having an issue blocking the command: /?. Whenever I do block the command, it works however in doing that, it seems to block every other command on the server. For instance, when the command /? is blocked, it will block /bal or /list, etc, even though I have the permission for those specified commands. Please help on how to effectively block this command without blocking every other command on the server.

Here is the file:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3884808/ChatControl.zip)

**Comment by OperatorValexio** [comment]
Figured out issue

**Comment by kangarko** [comment]
Have you tried the following syntax?

```
match ^\/\?
then warn &cInsufficient permission.
then deny
```

Please use regex101.com to test potential matches (without "match ") to see what the result should be in the game.

**Comment by OperatorValexio** [comment]
That worked, thank you.
