### ISSUE TITLE
TownyChat Integration?

### ISSUE THREAD

**Issue by jakkuh** [kangarko/ChatControl-Pro#1459]
Would be awesome if /spy had integration with TownyChat so we can moderate it!

:D

**Comment by lackoSK** [comment]
Hello,

Thank you for the suggestion.

 We will think about this feature being added to ChatControl.

Regards, 
lackoSK

**Comment by jakkuh** [comment]
I tested out the new version but it only seems to spy for arguments after the "/t" command. This command is used for changing town settings not running townchat.

Townchat is a separate chat channel that can be toggled on and off with "/tc".

**Comment by kangarko** [comment]
Reopening, we'll likely implement this.

**Comment by kangarko** [comment]
Hello there!

I went over the code and we are already listening for Towny Chat events when the spy is enabled:

![a](https://i.imgur.com/Aji1DOs.png)

I cannot find the problem, please produce the steps to reproduce it.

**Comment by kangarko** [comment]
We cannot reproduce the problem, please provide us your versions of Minecraft server, Towny and ensure ChatControl is on the latest version

**Comment by kangarko** [comment]
Closing due to no response
