### ISSUE TITLE
Lag on player join

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#1461]
For some reason ChatControl is making my server lag for a brief few MS on every player join with this message in console
`[ChatControl 8.4.3] Join Event - Vanish took 223.38 ms`

Any work around or anything to fix this?

**Comment by lackoSK** [comment]
Hello,

Can you please update it to the newest version? 

Also please, send me a full debug log.

Thanks!

**Comment by JavaFactoryDev** [comment]
User not responding.

**Comment by HexedHero** [comment]
> Hello,
> 
> Can you please update it to the newest version?
> 
> Also please, send me a full debug log.
> 
> Thanks!

I'm now on the latest version but what do you mean by a debug log?
Server logs show nothing but what I posted sometimes on join but not always.

**Comment by HexedHero** [comment]
[07:39:36 INFO]: [ChatControl 8.4.9] Join Event - Vanish took 215.16 ms

**Comment by lackoSK** [comment]
Hey, 

Please set the debug in the config to Join Event and send me the debug.log file.

Thanks
