### ISSUE TITLE
Can't stop players from tab completing commands

### ISSUE THREAD

**Issue by Equity7** [kangarko/ChatControl-Pro#1462]
I can't seem to stop tab completion for the default group. I checked today and I have the latest copy of ChatControl and the latest copy of ProtocolLib, running on a 1.14.4 Paper server. Here are the config settings:

Packets:
  Enabled: true
  Replace_Unicode_In_Books: true
  Tab_Complete:
    Hide_Vanished_Players:
      Enabled: false
      Maximum_Length: 20
    Enabled: false
    Only_In_Commands: false
    Require_Arguments: 1
    Require_Length: -1

Maybe I just have a setting wrong? I tried different variations but I can't seem to get it to work.

**Comment by lackoSK** [comment]
Hello,

Please zip me your file and send me it. 

Thanks!

**Comment by Equity7** [comment]
Do you mean the settings file?
[settings.zip](https://github.com/kangarko/ChatControl-Pro/files/3913343/settings.zip)

**Comment by lackoSK** [comment]
Hello,

Please send us the whole ChatControl file not only settings.yml.

Thanks!

Here's guide
https://github.com/kangarko/ChatControl-Pro/issues/1252

Regards,
lackoSK

**Comment by Equity7** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3918447/ChatControl.zip)

**Comment by Equity7** [comment]
Oops I didnt mean  to close it.

**Comment by kangarko** [comment]
@lackoSK @JavaFactoryDev may you please have a look?

**Comment by lackoSK** [comment]
Hello,

It works for me with your configs. Can you run ChatControl only on the server? (remove every other plugin) and test it.

Thanks!

Regards,
lackoSK

**Comment by Equity7** [comment]
Hi. yes I am working on that now? I have a server with no plugins so I will add it there. When tab completion is disabled, can you tell me if there is an admin override?

**Comment by lackoSK** [comment]
>  When tab completion is disabled, can you tell me if there is an admin override?

What do you mean, can you explain it? 

If you disable it in spigot.yml? It will get disabled everywhere, not just for ChatControl.

**Comment by lackoSK** [comment]
Closing this issue - customer not responding.
