### ISSUE TITLE
Bungee welcome message

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1463]
Hey.

Currently there is a welcome message PER server. I would like to have one global, so that on any server it just shows the welcome message once. This would look so much better and professional.

**Comment by lackoSK** [comment]
Hello,

You can disable welcome message in the messages.yml file and keep it enabled only on the server you want to. The flag is "Conditions,"

Regards,
lackoSK

**Comment by Sikatsu** [comment]
That's not really what I want though. @lackoSK 

I would like to have it global, so if anyone joins the welcome message can be seen on all servers.
So in my case, my chat and join/leave messages are global, but when someone joins the lobby for the first time, no one is aware that the player is new.

I'm really surprised why it's possible with join/leave messages, but not with the welcome message.

**Comment by Sikatsu** [comment]
It's on the to-do list, but hope it can be added soon:

http://prntscr.com/q5oi2z

**Comment by lackoSK** [comment]
I'll have a look later. I'll see what can I do, maybe, it will be added soon, maybe later

**Comment by Sikatsu** [comment]
I hope rather soon then later. Willing to pay 10$ eventually.

**Comment by kangarko** [comment]
Thanks, I already tagged our great team in the Roadmap issue.
