### ISSUE TITLE
Bungee announce

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1464]
I would like to see an announce command that works with bungee. For example if I announce from lobby, it will be shown on Survival and Creative as well.

In general, I think ChatControl could use some love for bungee. :P

**Comment by GeertBraakman** [comment]
That is already here, you just need to enable the bungee option for the announcement in every settings.yml

**Comment by lackoSK** [comment]
Hello,

This feature is already there.

You can easily access it in settings.yml file it's under flag "Announcer."

Regards,
lackoSK

**Comment by Sikatsu** [comment]
Thanks!
