### ISSUE TITLE
[Question] Strip color from /me

### ISSUE THREAD

**Issue by Kyrobi** [kangarko/ChatControl-Pro#1465]
So I do not allow players to use colors in chat.

However, it seems like ChatControl has its own /me plugin that allows the players to use /me with a color code.

For example, `/me &6Hi`.

So the question is how to disable the color code while still letting people using /me?
I've tried setting Regex strip color to true in settings.

**Comment by lackoSK** [comment]
Hello,

Yes, ChatControl has own /me command.

This feature is not available but I will consider it.

Thanks!

Regards,
lackoSK
