### ISSUE TITLE
Center JSON in MOTD?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1466]
Can't seem to be able to add <center> to center JSON within the MOTD?

**Comment by lackoSK** [comment]
Hello,

Please, can you tell me what you want to do? Exactly.

Thanks!

Regards,
lackoSK

**Comment by Sikatsu** [comment]
Oh github removed that part.
To center the MOTD you can use the center tag, much like HTML. However when you use JSON messages in your MOTD this doesn't seem possible.

**Comment by lackoSK** [comment]
Hello,

Json guide for chatcontrol:
https://github.com/kangarko/ChatControl-Pro/wiki/JSON

Regards,
lackoSK

**Comment by kangarko** [comment]
Sorry at present you can only use the `<center>` parameter without JSON as this compiles the chat into different parts in a way we can't add spaces into (currently)
