### ISSUE TITLE
Request: Allow seperation of sign.txt from rules.txt

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1472]
I have rules blocking urls in my rules.txt, but this is breaking some signs being auto created that use dots formatting automatically with my Cannons plugin.
I was just going to copy/paste the formatting from my rules.txt into my sign.txt but in the sign.txt it says it auto pulls from rules.txt, so I cant actually deny the one specific rule I want from rules.txt just for signs, can you either add a variable per rules to blacklist certain things like signs, or give us the option to not include rules.txt auto in signs.txt.

Better option would be the blacklist, then I dont have to duplicate my rules.

For example:
```
# IP filter. 
# (Notice the operator strip which removes specified characters BEFORE the message is checked.)
match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
id 1
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement
blacklist signs
```

See blacklist signs at bottom.

**Comment by JavaFactoryDev** [comment]
Hello FrozenBeard,

Thank you for using ChatControl!
Thanks for your improvement, we will consider integrating it.

Regards,
Leonhard from MineAcademy

**Comment by kangarko** [comment]
@FrozenBeard I was doing a checkup on this ticket, and you can actually use the `ignore event signs` operator instead of `blacklist signs` to make a certain rule ignore signs event

@JavaFactoryDev take a note :)

**Comment by FrozenBeard** [comment]
@kangarko dope!
