### ISSUE TITLE
Players are getting added to channels they do not have permissions for

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#1473]
This has been an ongoing problem for a while now and it's quite frustrating.  Players who do not have permissions for some channels are being added to all channels, making our moderator only chat susceptible to spying.

When I look at the data.db file, I see entries like this:

  AnonymousPlayer:
    Channels:
      adventure: write
      arena: read
      buildbattle: read
      creative: read
      dirtblock: spy
      easy: spy
      hardcore: spy
      helper: spy
      hg1: spy
      hg2: spy
      jail: spy
      lobby: spy
      lounge: spy
      parkour: spy
      skyblock: spy
      skywars: spy
      svs: spy
      testlobby: spy

They should only have access to the "adventure" channel in this case.  All of my servers set permissions for the chat on that server only.  In my permissions.yml file, I assign permissions like this:

    chatcontrol.channel.adventure: true
    chatcontrol.channel.adventure.join.write: true
    chatcontrol.channel.autojoin.adventure.write: true

There are NO other permissions set in this server for ChatControl for regular players.

I think this may happen when certain servers are offline and they get kicked to a fallback server, but I really don't know.

I think the best way to fix this would be to disable the data.db file so it never saves channel information for players.  Is there a way to do that?

**Comment by c0wg0d** [comment]
It happens in all Minecraft versions from 1.8.9 to 1.12.2.  I'm not uploading my plugins folder because they are irrelevant.

**Comment by lackoSK** [comment]
Hi, 

They are relevant for us to find the cause. 

Please send them to us.

Regards,
lackoSK

**Comment by c0wg0d** [comment]
I appreciate that you need more info to properly deduce this problem, but the fact is I have 15 different Paper servers and this happens on all of them, and each server has many different plugins.  This is purely a permissions issue with ChatControl.  The only other plugin that may have relevance is zPermissions or Vault.

Please just let me know if I can disable the creation and use of the "data.db" file.  I believe that is the issue.

**Comment by lackoSK** [comment]
We are sorry you're having issues, can you set debug (settings.yml) to "[channel-join]" and upload it on Pastebin?

Thanks

**Comment by c0wg0d** [comment]
Where will the debug messages get logged to?

**Comment by lackoSK** [comment]
Hey,

You can see the debug (messages) in the console, or you can look into your debug.log that got created automatically inside the plugin' folder.

Regards,
lackoSK

**Comment by kangarko** [comment]
@c0wg0d are you still experiencing this problem? If so just post us your channel-join debug log from your console when someone gets joined into channels they should not be

**Comment by c0wg0d** [comment]
Yes, it's still happening, but I have not had time to turn on debugging and look at the logs.  Even deleting the data.db file, reloading ChatControl, and having the player log sometimes doesn't fix the issue.  I usually have to create a ServerSign that has ch leave commands for all our chat channels to fix the issue.  Players do not have any access to the /ch command and should be forced into a specific chat channel upon joining a server, but for some reason, sometimes they are added to multiple channels, which can include our moderator only chat channel.  I will try to find time to turn on debugging and get some logs posted here when I can.

**Comment by kangarko** [comment]
@lackoSK missed this again?

**Comment by c0wg0d** [comment]
I have not seen this issue come up again for several weeks now.  Hopefully it is resolved.  I couldn't even tell you how to recreate it, because I don't know how it happens.

**Comment by lackoSK** [comment]
Hello,

Okay, we will keep this issue closed once it will appear again, let us know! 

Sincerely,
Ladislav from MineAcademy.org
