### ISSUE TITLE
Ignore bypass doesnt work

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#1474]
This permission: "chatcontrol.bypass.ignore" doesn't work, 

If you add it to a group/player and other players ignore that user, it doesn't work and the sender can be ignored. however, if the sender has the '*' permission it works fine and the player cannot be ignored.

ChatControl version 8.4.9

**Comment by JavaFactoryDev** [comment]
Hey HexedHero,

Thank you for using ChatControl & reporting this issue.
We will have a look asap.

Regards,
Leonhard from MineAcademy.

**Comment by lackoSK** [comment]
Hey,

Apology for the late response. It's fixed in the most recent version.

Regards,
lackoSK
