### ISSUE TITLE
Error 8.4.10

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1475]
Seem to receive this error once in a while, not sure what it is?

Sometimes the death cause (assuming that's what it has to do with) is different.

https://pastebin.com/eWMuiE4L

**Comment by lackoSK** [comment]
Hello,

Can you explain when it appears so we can find the problem and fix it? 

Do you have the latest version of ProtocolLib? 

Regards,
lackoSK

**Comment by Sikatsu** [comment]
I have the latest version of ProtocolLib yes.
And I really don't know when it appears, but it's there, often enough to get bothered.
This is not something new as of the latest version, it happened before.

**Comment by lackoSK** [comment]
Does it appears when you type into chat?

**Comment by Sikatsu** [comment]
Don't believe so.

**Comment by lackoSK** [comment]
You have to tell me when it appears. I can **not** detect it without further description.
