### ISSUE TITLE
1.14.4 ChatControl-Pro Error on reload

### ISSUE THREAD

**Issue by iTz-MrAnonymous** [kangarko/ChatControl-Pro#1477]
So the plugin runs pretty much as intended however once I try to make use of the integration with BungeeCord feature of the plugin and enable it, the plugin will give me this error after I type **/chc reload**

This is the error I get in the console.
https://pastebin.com/BryRc4qT

It should also be noted that if I go into settings.yml and under BungeeCord, change enable: from 'true' back to 'false', I am able to reload the plugin as normal without any problems. Otherwise the plugin will break when reloading it, if bungeecord is enabled.

**Comment by lackoSK** [comment]
Hello, 

Can you set a debug to 'discord' and send us the debug log? Also please, are you running the latest version of the DiscordSRV plugin? 

P.S. Please send us your 'ChatControl' folder (zip it)

Thanks!

Regards,
lackoSK

**Comment by iTz-MrAnonymous** [comment]
DiscordSRV Version: 1.18.4, which is the latest version.

Discord Debug:
https://bin.scarsz.me/fd6f1a41-b55b-4767-a9a0-a2ba06782263#zS5WVgBuxaS8UfDSfoIR00aTouRfkZ6F

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3963102/ChatControl.zip)

**Comment by lackoSK** [comment]
I meant debug in chatcontrol. Set debug in settings.yml to '[discord]

**Comment by iTz-MrAnonymous** [comment]
Pardon my ignorance, but where about's would the debug log be located?

**Comment by lackoSK** [comment]
Hey,

It's located inside 'settings.yml' set
>debug: [discord]

**Comment by iTz-MrAnonymous** [comment]
Thanks for the help!
Turns out I had just made a silly mistake and it was an issue on my side, which was in regards to
Bungee_server_name: in settings.yml

Closing this now, as my issue has now been resolved.
