### ISSUE TITLE
FactionsUUID + ChatControl not formatting

### ISSUE THREAD

**Issue by Cretezy** [kangarko/ChatControl-Pro#1483]
ChatControl version: 5.8.7 (latest)

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/3969870/ChatControl.zip)

FactionsUUID version: 1.6.9.5-U0.5.6-b211 (latest)

[Factions.zip](https://github.com/kangarko/ChatControl-Pro/files/3969872/Factions.zip)

Relavant configs:

ChatControl message format: `Message_Format: '%factionsuuid_faction_name%%factionsuuid_faction_only_space%%luckperms_prefix%&r&7%cc_color%{player} &7»&r {message}'
`

ChatControl listeners:
```
Listener_Priority:
  Formatter: LOWEST
  Checker: LOWEST
```

Factions chat:
```
    chat {
        allianceChatFormat="§d%s:§f %s"
        alwaysShowChatTag=false
        broadcastDescriptionChanges=false
        broadcastTagChanges=false
        factionChatFormat="%s:§f %s"
        # Allow for players to chat only within their faction, with allies, etc.
        # Set to false to only allow public chats through this plugin.
        factionOnlyChat=false
        modChatFormat="§c%s:§f %s"
        tagFormat="%s§f"
        # If true, disables adding of faction tag so another plugin can manage this
        tagHandledByAnotherPlugin=true
        tagInsertAfterString=""
        tagInsertBeforeString=""
        tagInsertIndex=0
        tagPadAfter=true
        tagPadBefore=false
        tagRelationColored=true
        tagReplaceString="[FACTION]"
        truceChatFormat="§5%s:§f %s"
    }
```

(`tagHandledByAnotherPlugin=true`)

**Expected Result**:

ChatControl properly formats the placeholders in the message format.

**Actual Result**:

![image](https://user-images.githubusercontent.com/2672503/70938418-23c88500-2014-11ea-9b7a-b0a63edd499e.png)

ChatControl is not able to format the placeholders.

Without Factions, it does work (to all applicable placeholders):

![image](https://user-images.githubusercontent.com/2672503/70938472-3ba00900-2014-11ea-8bae-4c5b2671e840.png)

**What I tried**:

- Multiple variations of the listeners. Tried HIGHEST, LOWEST, HIGHEST/LOWEST, LOWEST/HIGHEST, NORMAL/NORMAL
- `tagHandledByAnotherPlugin=false`

**Comment by lackoSK** [comment]
Hey,

This is **ChatControl-Pro** support. But okay.

Do you have PlaceholderAPI or MvdwPlaceholders installed on your server?

In case you are using PlaceholderAPI you have to do 
> /papi ecloud download <extension>

Regards,
lackoSK

**Comment by Cretezy** [comment]
Yes, I have Placeholder API

**Comment by Cretezy** [comment]
This issue would affect Pro as well I believe.

Yes, I have Placeholder API (v2.10.4).

What do you mean with the the Placeholder ecloud? FactionsUUID provides the placeholders built-in (no need for extension). ChatControl also fills the rest of the placeholders correctly without Factions

**Comment by lackoSK** [comment]
You can find placeholders here https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#factionsuuid

**Comment by Cretezy** [comment]
@lackoSK I'm not sure you are understanding the issue. With ChatControl and Factions, ChatControl does **no** placeholder replacement

**Comment by lackoSK** [comment]
I can not test it cuz I don't have the plugin, but can you try using {} instead of %%?

**Comment by ArtelGG** [comment]
I've been experiencing this too and it is **obnoxious**, to say the least, and it truly feels like there's zero documentation available (this is multiplied tenfold if you want documentation for Free, it simply does not exist.).
I've been able to reproduce this with both Free and Pro, across a few versions of FactionsUUID. No placeholder or format seems to be working.
The `{faction}` placeholder doesn't work on Free at all, I believe it used to mention this during the startup messages saying it only supports the "free" version, which also makes no sense since the plugin has been abandoned (to my knowledge) and UUID is open source with free development builds available (same as releases).
I've tried the following formats (just for posterities sake):
- `{}`
- `%%`
- `{%%}`
- `%{}%`

**Comment by lackoSK** [comment]
> I've been experiencing this too and it is obnoxious, to say the least, and it truly feels like there's zero documentation available (this is multiplied tenfold if you want documentation for Free, it simply does not exist.).

Yes, we are working on a new one ;)

> Edit: To Just to clarify, the {} format does technically try and replace it, but it's empty.
It´s should not be empty. Do the {faction} placeholder work at all? 

There are official Factions UUID placeholders:
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#factionsuuid

**Comment by Cretezy** [comment]
@lackoSK You can find the Jenkins for FactionsUUID at https://ci.ender.zone/job/FactionsUUID/. It's fine to use it to test.

**Comment by lackoSK** [comment]
Hi,

Which ChatControl now you´re talking about?
On the non-premium, one is limit 12.

**Comment by Cretezy** [comment]
The free version. And limit for what?

**Comment by lackoSK** [comment]
The limit of placeholders in the free one is 12.

**Comment by Cretezy** [comment]
Placeholders used? I'm using under 12 as you see above

**Comment by haeiven** [comment]
On ChatControl Pro, this is working: 

Message: "{rel_factionsuuid_relation_color}{factionsuuid_faction_name} "

**Comment by lackoSK** [comment]
Yeah, the ChatControl (free) has a limit to 12 placeholders in the whole plugin. Please, upgrade to ChatControl PRO to use these features. 

Also, find the right placeholders.

Thanks!
