### ISSUE TITLE
Formatting question

### ISSUE THREAD

**Issue by MoonWolf63** [kangarko/ChatControl-Pro#1485]
So I have a custom skript that allows me to change my Name color, but when I added channels it wont work anymore. How do I get it working again.

**Comment by lackoSK** [comment]
What a skript do you mean? And explain the issue further, so I can understand your problem..?

**Comment by MoonWolf63** [comment]
A skript that changes my displayname and tabname. Like changing the color of my name in the chat and the tablist. Ever since I added channels it won't work anymore.

**Comment by lackoSK** [comment]
What a skript? Do you mean chatcontrol' skript or a normal one? If it is a normal skript than it's not a chatcontrol' issue, you have to change your code of it.
