### ISSUE TITLE
8.4.13 anti-cap bypass

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1487]
Start a chat with a special character and then write a phrase with unstucked letter, like "* I A M N O O B A A A"

**Comment by lackoSK** [comment]
What do you mean by 'special character' ?

**Comment by xion87** [comment]
the jolly character or symbol character like "- ," ecc

**Comment by lackoSK** [comment]
Like if I type: 'A-B-C-D', it shouldn't get 'lowercased', it will get 'lowercased' when I type: 'ABCD' (ex.)

**Comment by xion87** [comment]
No, like "-A-B-C-D-E" it will not get lowercased (notice the starting symbol)

**Comment by lackoSK** [comment]
Should it be lowercased?

**Comment by xion87** [comment]
yeah also if start with a special character

**Comment by lackoSK** [comment]
I think it should not get lowercased if you type HELLo it should be, H-E-L-L-O shouldn't be?

**Comment by xion87** [comment]
H-E-L-L-O will get lowercased
-H-E-L-L-O will don't get lowercased

**Comment by lackoSK** [comment]
I think this is not an issue. It should be like that.  

-H-E-L-L-O should not get lowercased. It can be some CODE or stuff like that.

**Comment by xion87** [comment]
dude this is a issue with recently chatcontrol versions, before never acted like this, two user reported this in this montly to my server

**Comment by kangarko** [comment]
Sorry for the delay, @lackoSK please note users responding to closed tickets.

This is by design, however you could edit the Min_Caps_Percentage or Min_Caps_In_A_Row option in the Anti_Spam section of settings.yml to make it more sensitive, then it should be blocked.
