### ISSUE TITLE
Bypass Version Check

### ISSUE THREAD

**Issue by nicostrebel** [kangarko/ChatControl-Pro#1488]
Is there any option to disable this version check? 

> 22:43:00 INFO: !-----------------------------------------------------!
> 22:43:00 INFO: ** Your Minecraft version v1_15 has not yet
> 22:43:00 INFO: been officialy tested with the Foundation
> 22:43:00 INFO: library that powers the ChatControl plugin.
> 22:43:00 INFO:
> 22:43:00 INFO: For your safety, the plugin is now disabled.
> 22:43:00 INFO: !-----------------------------------------------------!

If not, is there any information when the Foundation library is available for Minecraft 1.15?
As far as i know there is hardly any change code-wise for plugins in Minecraft 1.15 compared to Minecraft 1.14.

**Comment by JavaFactoryDev** [comment]
Hi nicostrebel,

We will do this asap.
ChatControl will be usable for 1.15 soon.

Regards,
Leonhard from MineAcademy

**Comment by AmazedMender16** [comment]
@JavaFactoryDev Deadline was set to 24/12, any updates on that?

**Comment by JavaFactoryDev** [comment]
The deadline was until 2020.
It will be done today.

**Comment by JavaFactoryDev** [comment]
Hi nicostrebel,

ChatControl Pro & all the other plugins now fully support 1.15.
Keep in mind that this is still a beta version so it might suffer from smaller bugs.

Regards,
Leonhard from MineAcademy

**Comment by kangarko** [comment]
1.15 is now out and has been tested. As Leonhard (JavaFactoryDev) pointed out, it's a pre-release but I personally loaded the plugins up and run through some of the features to ensure smooth using. Merry Christmas!
