### ISSUE TITLE
Some chatcontrol event need to be optimized 

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#1489]
https://timings.aikar.co/?id=6e5297768b9341f1bf6c093cd6942d08
chc 8.4.13
I see some small lag spikes caused by chatcontrol, by reply command and quit event, i am not using mysql but normal files

**Comment by lackoSK** [comment]
Hello,

I don't think 50ms (0,05s) is a lag. That causes the delay, and we have to save the data for the player that means it will take a few seconds. 

I'll have a look at what we can do with the performance on PlayerQuitEvent in ChatControl.

Thanks!

**Comment by kangarko** [comment]
@lackoSK have you taken a look yet?

**Comment by kangarko** [comment]
@xion87 Can you please upload us your data.db file?

**Comment by xion87** [comment]
[data.zip](https://github.com/kangarko/ChatControl-Pro/files/4045968/data.zip)

**Comment by kangarko** [comment]
@xion87 please use the next version, we have enhanced the mechanism that clears up your data.db
