### ISSUE TITLE
Problems with Ranged chat (1.12.2)

### ISSUE THREAD

**Issue by MaxIsV** [kangarko/ChatControl-Pro#1491]
I had some problems with chat formatting:
1. When admins (with "*" perm) write to a local chat, absolutely all players see their messages.
2. In all worlds except the standard "world", if a player writes a message to a local chat, then this message will also be seen by all players in all worlds.

I tried to solve these problems for a very long time. I changed different settings, issued and removed different permissions, but these problems nevertheless remained.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4002324/ChatControl.zip)

**Comment by lackoSK** [comment]
>When admins (with "*" perm) write to a local chat, absolutely all players see their messages.
Then you have to remove the standard player's permission to read the channel.

> all worlds except the standard "world," if a player writes a message to a local chat, then this message will also be seen by all players in all worlds. 
It doesn't seem like you have enabled the world channel function. This means that everybody - everywhere can see the message sent.

**Comment by MaxIsV** [comment]
> > When admins (with "*" perm) write to a local chat, absolutely all players see their messages.
> 
> Then you have to remove the standard player's permission to read the channel.
> 
> > all worlds except the standard "world," if a player writes a message to a local chat, then this message will also be seen by all players in all worlds.
> 
> It doesn't seem like you have enabled the world channel function. This means that everybody - everywhere can see the message sent.

I do not quite understand which permission needs to be removed. And yes I have disabled channels

**Comment by lackoSK** [comment]
Wait, what do you mean by 'local' chat then?

**Comment by MaxIsV** [comment]
> Wait, what do you mean by 'local' chat then?

I have ranged mode enabled. When a player writes a message, it is sent in a local chat (which is visible to players within a radius of 100 blocks). When a player writes a message with a "!" at the beginning, it is visible to all players (i.e. in the global chat). I meant it

**Comment by lackoSK** [comment]
And what´s the problem then?

**Comment by MaxIsV** [comment]
> And what´s the problem then?

What is the problem in Sense? I described all the problems at the very beginning, they have not gone away. I repeat:

I had some problems with chat formatting:

When admins (with "*" perm) write to a local chat, absolutely all players see their messages.
In all worlds except the standard "world", if a player writes a message to a local chat, then this message will also be seen by all players in all worlds.

I tried to solve these problems for a very long time. I changed different settings, issued and removed different permissions, but these problems nevertheless remained.

**Comment by lackoSK** [comment]
Have you tried this perm? 

>Perm: chatcontrol.notify.outofrange
Info: Get notified when nobody sees your message in ranged chat because it's too far away.

**Comment by MaxIsV** [comment]
> Have you tried this perm?
> 
> > Perm: chatcontrol.notify.outofrange
> > Info: Get notified when nobody sees your message in ranged chat because it's too far away.

did not understand where does it

**Comment by MaxIsV** [comment]
> Have you tried this perm?
> 
> > Perm: chatcontrol.notify.outofrange
> > Info: Get notified when nobody sees your message in ranged chat because it's too far away.

Do you mean, did I try to add this permission?

**Comment by lackoSK** [comment]
Yes, add it to admins as a negative one.

**Comment by MaxIsV** [comment]
Thanks!  All problems are resolved.
