### ISSUE TITLE
There is no whitelist for Anti_Spam.Commands.Limit

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1492]
I have a plugin CMI that allows editing Armour stands, but Chatcontrol pro flags

> "You can only send 10 commands in the last 10 seconds."

I do not know what command they are running and there is no bypass for specific commands.

Anti_Spam.Commands.Limit needs to have a whitelist.

**Comment by lackoSK** [comment]
Hi,

Thank you for your suggestion! 

However, the feature is to limit commands for a time snap which means it should not be bypassed.

We will consider adding it (maybe in the next update of the plugin) if we will agree it to be added.

**Comment by FrozenBeard** [comment]
Thank you, this is currently blocking CMi Armour stand editor from working, and I don't want to have to disable the entire Commands within X amount of time, we just need a whitelist.
