### ISSUE TITLE
OP's get added to all channels

### ISSUE THREAD

**Issue by Klaerke91** [kangarko/ChatControl-Pro#1493]
All my OP get added to ALL channels. 

Is there a way to not give OP's channel permissions?

**Comment by lackoSK** [comment]
Hello,

I don't understand correctly. Can you explain your's issue?

**Comment by Klaerke91** [comment]
whats not to understand.

all OP's  /op PLAYER
gets access to all channels.  I am asking if this can be made so they dont, so when they go out of OP mode they dont have to set all there channels again as they are saved in database.db as write

maybe also make a config option to disable database.db.

**Comment by lackoSK** [comment]
Yes, you can open the plugin with WinRar or similar zip opener and open the plugin.yml - here you can change it: 

> default: op/true -> false
