### ISSUE TITLE
1.14.4 Placeholders in admin/bungee-chat

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1495]
Placeholders won't get escaped in the bungeechat and adminchat. 
For example {bungee_server_name} will become "Survival", but there are some other critical placeholders from papi that will be converted too.
The default server chat already escapes placeholders.

**Comment by lackoSK** [comment]
Can you send us your placeholder/file configuration?

**Comment by martijnpu** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4008595/ChatControl.zip)
Here you have the hole map (excluding logs and errors). Alle settings etc are the same on every server we have.

**Comment by lackoSK** [comment]
Is the country placeholder getting replaced?

**Comment by martijnpu** [comment]
Yes, that one too. But I'm more worried about all the other external placeholders

**Comment by lackoSK** [comment]
Please, use yes or no as the answer. I can not understand you.

**Comment by martijnpu** [comment]
Yes.

(Chatcontrol-placeholder - papi placeholder - papi-placeholder)
![image](https://user-images.githubusercontent.com/38832167/71632438-db61b780-2c0e-11ea-8057-b25817875be7.png)

**Comment by lackoSK** [comment]
And on-hover?

**Comment by martijnpu** [comment]
You can't hover the text because there isn't a placeholder for that

**Comment by lackoSK** [comment]
What do you mean? Hover your prefix? As you want to use {bungee_server_name} that is in your onHover event

**Comment by martijnpu** [comment]
That's not what I mean. I'll try to explain it again;
ALL players can use placeholder in the chat by just typing it in their message.
This means that normal players can get sensitive information if they say the right placeholder.

All I ask you guys is to prevent the use of placeholders in the chat. Not the prefix, not the nickname nor the suffix. If you want it can be configured in a perm, but disable it

**Comment by martijnpu** [comment]
@lackoSK have you already looked into it?

**Comment by kangarko** [comment]
@lackoSK

**Comment by martijnpu** [comment]
How's the status?

**Comment by lackoSK** [comment]
Should be done today´s evening ;

**Comment by kangarko** [comment]
Thanks, fixed
