### ISSUE TITLE
1.15.1 i cannot use /chc reload!

### ISSUE THREAD

**Issue by rybuilder23** [kangarko/ChatControl-Pro#1497]
when i use /chc reload i get this eror
 i think its my format file.

with a clean startup everthing works fine.
but i like that /chc reload works to.

i use
paper 31
if i need to give more information i m happy to help!

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4008036/ChatControl.zip)

**Comment by JavaFactoryDev** [comment]
Hey rybuilder23,

Thanks for using ChatControl-Pro.
Can you please show us, which error you get.

Regards,
Leonhard from MineAcademy.

**Comment by rybuilder23** [comment]
oeps i made a paste bin but forgot to paste it lol haha xD
here it is
https://pastebin.com/QD8DzEZ6

**Comment by rybuilder23** [comment]
today it is gone.
/chc reload works again 
realy wird.
