### ISSUE TITLE
Format placeholders {ruleID} and {handler} from handlers.yml don't work in formatting.yml

### ISSUE THREAD

**Issue by TheReverend403** [kangarko/ChatControl-Pro#1499]
Title says it all. If I specify the message in handlers.yml, {ruleID} and {handler} work, but then I don't get the event cause, only the text.

If I define it in formatting.yml, I get the event source, but not {ruleID} and {handler}.

![Example](https://dev.pste.pw/f/oUX.png)

Exactly the same format, the only difference is the second example is in handlers.yml and the first in formatting.yml.

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

Please, send us your zipped ChatControl folder. 

Thanks!

**Comment by kangarko** [comment]
@lackoSK have you tested this? Seems like we are not replacing them in the code, you can just make them to be replaced

**Comment by lackoSK** [comment]
Hey, 

We are solving this problem & adding this feature.
Will be done soon ;)

Thanks!

King Regards,
lackoSK

**Comment by kangarko** [comment]
This will be fixed in the next version thank you!
