### ISSUE TITLE
Command Aliases

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1500]
Hello,
Could you add aliases for the "/chc announce" command and the "/chc clear" command?
Thank you.

**Comment by pvpstryker** [comment]
*crickets*

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

You can do it your self! 
https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands
