### ISSUE TITLE
Can I send all bungee server chats to a discord channel?

### ISSUE THREAD

**Issue by mov51** [kangarko/ChatControl-Pro#1502]
ChatControl-8.5.0
DiscordSRV-Build-1.18.4
git-Paper-32 (MC: 1.15.1)
waterfall build #311

We are trying to send the messages from each of the subservers through discordsrv. Based on [this](https://github.com/kangarko/ChatControl-Pro/wiki/Discord) wiki page it should be possible but we can't get anything other than the server that discordsrv is installed on to send or receive discord messages. 
Not sure if we are doing something wrong or if it's not possible to send global chat. Config files for all 3 servers are attached.
[tmp.zip](https://github.com/kangarko/ChatControl-Pro/files/4019385/tmp.zip)

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

Can you set a debug in the settings.yml to [discord] - Send us the output?

Thanks!

**Comment by mov51** [comment]
The only one that is generating a debug log is the server that contains discordsrv. Thats making me think we need to have it in each server, but the messages from the other servers don't show up in the log at all so i'm still unsure.

If we do need to have discord srv in each server, how would it need to be configured? We have been told that puting the same bit token and channel info can cause issues.

Once enabling debug mod I reloaded the plugin then stated "this is (server)" in each server/discord channel. It appears to have only logged sending from the survival server however.

[debug.log](https://github.com/kangarko/ChatControl-Pro/files/4030622/debug.log)

**Comment by lackoSK** [comment]
Yes, you need to have it on each server.

The tutorial is here https://github.com/kangarko/ChatControl-Pro/wiki/Discord

**Comment by mov51** [comment]
And discordsrv won't have any issues? Would i just configure discord srv normally?

**Comment by lackoSK** [comment]
It should work flawlessly.

**Comment by james090500** [comment]
Thank you. We have implemented this and it works perfectly. We have Survival, Creative and Hub and you can see the server in front of the player. Messages are delivered to each server and the DiscordSRV linked account are linked using symlinks.

https://i.imgur.com/64tRX79.png
