### ISSUE TITLE
Death Messages with enchantment info of {killler_item}

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#1503]
Since 20 version ago (or maybe more), I got warning on `chc reload`:
`[Warning]: The death cause 'Entity_Attack' is missing from your messages.yml. Ignoring...`

After I add that in messages.yml it shows the message that I defined when someone dies. But if I do not add it to messages.yml I get this pretty advanced message:
https://i.imgur.com/fYZOiAc.png

How can I use "Entity_attack" in messages.yml and show the same data as in my picture? Of course I want to change that message how I would like I just need to know how to show this hover with "Entity_attack".
{killer_item} shows just name of item, there is no hover effect.

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

Can you send me a zipped ChatControl folder? 

Thanks!

**Comment by AngelDeaD** [comment]
Sorry, I could not upload `errors.log`, `logs` directory (they are too big, I have slow upload rate) and `rules/rules.yml` (because I worked a lot on that and I'm not planning to share it)

[chc.zip](https://github.com/kangarko/ChatControl-Pro/files/4030578/chc.zip)

I do not really understand why do you need entire folder, because I just need to know how to show hover effect on {killer_item}, just like on my pictures which is default killer message.

CHC: 8.4.13

**Comment by lackoSK** [comment]
You have # here, remove it.


![image](https://user-images.githubusercontent.com/53174757/71923865-3440cb00-318e-11ea-8061-bd8270e2f0d6.png)

**Comment by AngelDeaD** [comment]
@lackoSK You need to read my first comment again.
I'm familiar with hashtag and commentar in programming world. My problem is entirely different thing.

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay.

So you want to show {killer_item} with HoverEffect? Can you set the debug in settings.yml to "deathmessages"

**Comment by AngelDeaD** [comment]
Hi,

How do I do that?
Just add
`debug true`
after `Death_Messages:` line or I should do it somehow else?

**Comment by lackoSK** [comment]
Can you set the **debug** in **settings.yml** to **"deathmessages"**

**Comment by AngelDeaD** [comment]
Hi,

I added
`Debug: true` after `Death_Messages:` and remove hashtags for `Entity_attack` in `messages.yml` then I typed `chc reload` in console. Do I need to restart server for `debug`? 
Anyway I do not see any changes. It still the same problem:
console: https://i.imgur.com/CctR1WD.png
chat: https://i.imgur.com/M9lZi06.png

The kill message which I get when I comment `Entity_attack`:
https://i.imgur.com/c07TvqW.png I want to translate these english words in my language. and add some more cases of this message, since chc death messages can do it.

Regards

**Comment by lackoSK** [comment]
No.

Go into your **settings.yml**
find the key **debug** inside them
replace the "[]" to **"[deathmessages]"**

And send us the output.

**Comment by AngelDeaD** [comment]
I found debug.

With Entity_Attack:
console: https://i.imgur.com/QO6OAj2.png
chat: https://i.imgur.com/LTBxm4U.png

As you can see the `{killer_item}` is grey as rest of the message,

Without Entity_Attack:
console: https://i.imgur.com/fwr3JM6.png
chat: https://i.imgur.com/qRx17jS.png

while here the `{killer_item}` is linked and shows more data when you put mouse on it.
How do I display more data on `{killer_item}` **with** `Entity_Attack` ?

**Comment by lackoSK** [comment]
You cant change the color of the item. The item has a specific color that can't be replaced by &.

**Comment by AngelDeaD** [comment]
I do not want to change the color, I want hover effect:
https://i.imgur.com/c07TvqW.png

**Comment by lackoSK** [comment]
Hey

So you probs want us to add this feature, we will consider doing it (it might be done in the next update, it might be done in a month...)

Hope you understand, we are also just peoples. 

PS: Adding to my to-do list.

Regards,
lackoSK
