### ISSUE TITLE
Help with conditions

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#1504]
Chat:
    Gang:
      Message: '{rel_factionsuuid_relation_color}{factionsuuid_player_role}{faction} '
      Condition: '"{factionsuuid_faction_name}" != ""'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
          - '&e&lFacção {%factionsuuid_faction_name%}'
          - '&9Função: {factionsuuid_player_role_name}'
          - '&bPoder: {factionsuuid_faction_power}/{factionsuuid_faction_powermax}'
          - '&aDTR: &a{factionsuuid_faction_dtr}&7/&c{factionsuuid_faction_dtrmax}'
          - '&eCoins: {factionsuuid_player_balance}'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/f who {faction}'

that condition i used with gangplus, i tried to using for faction, i want when the player is not a faction (wilderness) this entire part won't show, ty

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

You want to do: When the player is not in any faction to display "Wilderness"?

**Comment by dabou0** [comment]
i want to when he is not in a faction, to exclude the entire thing, so it doesn't show nothing, thats why i tried using the conditions, but i don't know js, ty

**Comment by kangarko** [comment]
Can you please test what the "{factionsuuid_faction_name}" variable will write to the chat by putting it in the Message key? What will it write to the chat when there is no faction?

`      Message: '{rel_factionsuuid_relation_color}{factionsuuid_player_role}{faction} test="{factionsuuid_faction_name}" '`

**Comment by dabou0** [comment]
Sure, it gives this
http://prntscr.com/qmde76

Selva = Wilderness
S (Selva)= W (Wilderness)

its changed to S instead of Selva in the plugin translation, i don't want leave it blank cause i use it in tab

**Comment by kangarko** [comment]
1. Please go to variables/javascript.txt and place this at the end of the file:

```
define {test_faction}
script:
	Array.from('{factionsuuid_faction_name}')
```

2. Open settings.yml and set Variables.Custom_Enabled to true.

3. Change the test to test="{test_faction}" and let us know what it says. 

Thank you!

**Comment by dabou0** [comment]
before and after
http://prntscr.com/qpynll

it also gave an error
https://pastebin.com/pHrRe5VA

**Comment by lackoSK** [comment]
Not sure if it is gonna to work but you can try using this, to get the first letter so W (S)

```
define {test_faction}
script:
  "{factionsuuid_faction_name}".charAt(0)
```

**Comment by dabou0** [comment]
Hi, its like this now
http://prntscr.com/qtmg9q

**Comment by lackoSK** [comment]
Then it means there is no name under it? Because this is intended to take the 1st letter out of the world.

**Comment by dabou0** [comment]
I wanted to show nothing when hes in no faction, i still need this please

**Comment by kangarko** [comment]
@lackoSK missed this

**Comment by lackoSK** [comment]
Hello,

Are you still having issues? 

Regards,
lackoSK

**Comment by dabou0** [comment]
no longer needed ty
