### ISSUE TITLE
Placeholder suddenly not working

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#1505]
Placeholder suddenly not working, after a reload they started to glitch and gave this error (error.log)
https://pastebin.com/T4S6ArP8

also im using FactionsUUID

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

1) Update to the latest version.
2) The player has to be online if he wasn´t.

**Comment by dabou0** [comment]
with latest version same error, player is always online
https://pastebin.com/6W0gEPNE

**Comment by kangarko** [comment]
This is a problem in the massivecraft factions plugin (see the stack trace), contact their dev team instead please.
