### ISSUE TITLE
Chat listener problems

### ISSUE THREAD

**Issue by Darkweasam** [kangarko/ChatControl-Pro#1506]
Listener_Priority:
Checker: LOWEST
Formatter: LOWEST
Signs: LOWEST

There is this plugin called PlayerShops, an addon to the good, well known BossShopPro
https://www.spigotmc.org/resources/playershops-gui-bsp-allow-players-to-create-public-shops.29568/

Issue:

Whenever I add an item to my shop, ("please input your price of this item in chat" method), the number is displayed in the global chat
The issue is also here when I use other plugins that requires me to enter something into the chat, it just simply stays visible for everyone

Please help, I kinda hate this priority thing in this plugin since I bought it

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

I don´t think this is ChatControl´s issue, can you try to use the ShopPlugin without ChatControl and test it?

**Comment by Darkweasam** [comment]
Yes I tried, the issue is still there, both for this plugin and also for MMOItems plugin.

Everything I type in is visible on chat.

**Comment by lackoSK** [comment]
> Yes, I tried, the issue is still there, both for this plugin and also for MMOItems plugin.
Everything I type in is visible on chat.

Then it´s not a ChatControl´s issue? If you disabled it and the plugin and the problem still continued,

**Comment by Darkweasam** [comment]
Lmao sorry, I totally meant it the other way.

So this issue is only here if chatcontrol is enabled. otherwise the issue is gone. Just try it yourself

**Comment by lackoSK** [comment]
Hello,

Apologies the delay, 

Are you using the Chat Channels? 
What version of ChatControl are you running?

**Comment by Darkweasam** [comment]
Hello,

No I dont use chat channels, there is a single global chat and thats all. I am using a standalone server.

I always use the latest version of chatcontrol PRO

**Comment by lackoSK** [comment]
What´s the lastest? Need an exact version.

**Comment by Darkweasam** [comment]
ChatControl-8.5.2.jar

**Comment by lackoSK** [comment]
That´s not the lastest btw. 

Can you also try a priority MONITOR?

**Comment by lackoSK** [comment]
Closing the ticket due to inactivity.

**Comment by Darkweasam** [comment]
I dont see where should I put the word monitor, i got an error saying "illegal values in settings.yml"

**Comment by Darkweasam** [comment]
Now my whole plugin broke, I get this on reload....
https://i.imgur.com/gSVTL4t.png

**Comment by kangarko** [comment]
@lackoSK missed this?

**Comment by lackoSK** [comment]
Hello,

Are you still having issues? 

Regards,
lackoSK

**Comment by Darkweasam** [comment]
I got rid of the BossShop's Addon. So I dont know anymore

**Comment by lackoSK** [comment]
Hello,

Do you need any more help? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Darkweasam** [comment]
Not on this one, thank you though
