### ISSUE TITLE
Death messages item with lore

### ISSUE THREAD

**Issue by baticag** [kangarko/ChatControl-Pro#1508]
We want to use death messages from ChatControl and we use them now, but we don't get weapon like in vanilla death messages, because it doesn't have lore and enchants. 

Can you please add this feature? Maybe as a separate placeholder?

**Comment by lackoSK** [comment]
Hello, 

We will consider adding it! 

Thanks!

**Comment by kangarko** [comment]
Thanks, however due to large amount of more important features on our roadmap we decided not to include this one.
