### ISSUE TITLE
1.14.4 Adminchat and bungeechat do net sync

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1509]
When you are as staff talking in the adminchat (chc ac switch) and switch to a different server inside the bungee you go back to the bungee chat. I tried to resolve this with a SQL-database, but it's still not working.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4027752/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

Can you explain the issue further?

**Comment by JavaFactoryDev** [comment]
Hey martijnpu,

Could you please respond to the question of @lackoSK as we need this information to figure out the issue?

Regards,
Leonhard from MineAcademy

**Comment by martijnpu** [comment]
There are multiple servers in our bungee-network. They are all also connected to a chc-sql database.
If you're as staff in the staffchannel (the default one) and you switch to another one, you left the adminchannel and join the bungeechannel again

**Comment by lackoSK** [comment]
Yes, you leave a channel, and it will join you to the other? Or what do you mean? Still don't get it

**Comment by martijnpu** [comment]
If you are in survival in the staffchannel and you go to skyblock (Another server).
In skyblock you are not longer in the staffchannel but in the bungeechat.

**Comment by lackoSK** [comment]
Yes, because it´s a chat channel that is synced globally.

**Comment by martijnpu** [comment]
But if the previous time you were in Skyblock you were in the staffchannel. And in survival you are in the bungee and you switch to Skyblock you join the staffchannel.

I understand bungee is the default chat channel, but why isn't the staff channel butter globally synced?

**Comment by lackoSK** [comment]
Okay, I will have a look if it is possible to be added

**Comment by lackoSK** [comment]
Hey,

This issue was caused by the autojoin (OP) feature; we have added a flag to disable it inside the configuration. You will be able to use it in the next update.

We have also added a 0,5s delay, to do the sync more secure.

PS: Set autojoin to **false** 

Regards,
lackoSK
