### ISSUE TITLE
Any way to prevent this type of spam?

### ISSUE THREAD

**Issue by BlackBeltPanda** [kangarko/ChatControl-Pro#151]
Had about 25 alts all login at once and spam like so: http://pastebin.com/raw/98Tshuhd

Is there any way to prevent that type of spam coming from multiple players, instead of just one?

**Comment by kangarko** [comment]
You can adjust the regex IP filter to be more free, but keep in mind this will increase false catches. The filter is located in rules/rules.txt file.

ChatControl can help lower such spam by adjusting rules, but in general I'd recommend using NoCheatPlus in combination of some AntiBot plugin that prevents proxy connections.

Also ensure you have Anti_Bot.Block_Chat_Until_Moved to true, this will deny players sending messages until they have moved.

**Comment by BlackBeltPanda** [comment]
I'll have to look into a configurable AntiBot plugin, then. In this case, I had it configured to block chat until they moved. They did wait several minutes before spamming, too.
Thanks for the suggestion. =)

**Comment by kangarko** [comment]
Closing :) If you have any more questions, feel free to post below.
