### ISSUE TITLE
Tab-Complete bypass isnt working (1.14.4)

### ISSUE THREAD

**Issue by NightPrimez** [kangarko/ChatControl-Pro#1510]
im put permission bypass tab-complete but it not work

im trying to 
• set -1 in spigot.yml and enable in settings.yml*
• set -1 in spigot.yml and disable in settings.yml*
• default setting in spigot.yml and enable in settings.yml*

but.. it doesnt working of all :'(

* "enable in setting.yml" = Tab_Complete.Enable: true

Server Version  = paper 1.14.4
ChatControlPro = 8.5.0-BETA

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

The permission is:
> Perm: chatcontrol.bypass.tabcomplete
Info: Allow player to tab complete.
Notice: If you are using Spigot it is highly recommended to disable this feature and use the inbuilt one in spigot.yml

Can you try it with this one?

**Comment by NightPrimez** [comment]
yes i did it

**Comment by lackoSK** [comment]
And? That worked?

**Comment by NightPrimez** [comment]
no it's not

**Comment by lackoSK** [comment]
Okay, what does not work exactly? 

You want to enable or disable tab completion?

**Comment by NightPrimez** [comment]
i need to disable ONLY who dont have op
and i want to make who have op just bypass antitab-complete

**Comment by lackoSK** [comment]
Then add them **chatcontrol.bypass.tabcomplete** as **FALSE** (to the normal users)

**Comment by NightPrimez** [comment]
not working..

i meann

• i just Packets.Tab_Complete.Enable = true and i just add permission chatcontrol.bypass.tabcomplete (true) to admin group

but.. admin (have op) (have bypass permission) can't using tab-complete

**Comment by lackoSK** [comment]
What is your spigot.yml?

**Comment by NightPrimez** [comment]
https://pastebin.com/raw/mF1i3pe4

**Comment by lackoSK** [comment]
tab-complete:

**-1** will disable tab completely
Default: **0**
**1** will mean you have to type the first letter
**2** will mean you have to type the second letter... etc...

That will help you ;-)

**Comment by NightPrimez** [comment]
if i set -1 ..so.. how to bypass disable tab-complete for admin ..?

**Comment by lackoSK** [comment]
set it to 0 and remove the permission for a standard players

**Comment by NightPrimez** [comment]
i didnt set bypass tab-complete for normal player
.. im just only set in ADMIN GROUP

so.. already did it but admin (have op) still cant using tab-complete option

**Comment by lackoSK** [comment]
give the admin permission and set it to 0

**Comment by NightPrimez** [comment]
already did it and still cant

ในวันที่ พฤ. 16 ม.ค. 2020 เวลา 21:47 Ladislav Proc <notifications@github.com>
เขียนว่า:

**Comment by lackoSK** [comment]
Can you try giving them " ***** " permission so we can spot if it is a permission problem?

**Comment by NightPrimez** [comment]
uh

**Comment by lackoSK** [comment]
Can you do it?

**Comment by NightPrimez** [comment]
seems like it's doesnt work

ในวันที่ อา. 19 ม.ค. 2020 เวลา 21:31 Ladislav Proc <notifications@github.com>
เขียนว่า:

**Comment by lackoSK** [comment]
Please, zip me your entire chatcontrol's folder. Thanks.

**Comment by NightPrimez** [comment]
ah, nvm i found some plugin to disable tab-complete with bypass permission
you can close this ticket

..thx

ในวันที่ พ. 22 ม.ค. 2020 เวลา 01:23 Ladislav Proc <notifications@github.com>
เขียนว่า:
