### ISSUE TITLE
Command Aliases #2

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1511]
You closed my ticket without letting me answer.
That method doesn't work with arguments, that's why I asked for the "/chc announce" alias. I set the alias the "/announcechat", doing "/announcechat %announcement%" returns incorrect usage.
Fix this please and stop closing the tickets before getting a response.

**Comment by kangarko** [comment]
Sorry can you refer to your old ticket? You can always comment under closed tickets and we'll continue to reply there.

**Comment by kangarko** [comment]
Have you tried putting this in your commands.yml ?

![a](https://i.imgur.com/jVYfFTh.png)

**Comment by kangarko** [comment]
@lackoSK
