### ISSUE TITLE
Weird private messages bug

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl-Pro#1512]
Well, lets try to explain this bug. I've been being informed about issues with private messages for months. I've been updating ChatControlPro on every update, but the fix never came.
It just happens sometimes. I'll try to explain it easy:

There is user A, B and C. A and B are messaging each other, but not C.

`A issued server command: /msg B wanna go to the nether?`

B receive the message from C instead of A
C receive the message from himself

`A issued server command: /msg B wanna go to the nether?????`

B receive the mesage from A

`B issued server command: /r for what?`

A receive the reply from B
C receive the reply from C

`B issued server command: /r 2 people already told me the same thing`

A receive the reply from himself

My settings about private message: https://pastebin.com/pw0ad41E
Formatting: https://pastebin.com/ewPC4ikT

**Comment by lackoSK** [comment]
Hello,

So: 

If user A is in the other world and sends the message to user B the message is sent to user C?

**Comment by YellowZaki** [comment]
I don't know in what world they were, it just happen some times.

**Comment by lackoSK** [comment]
I need you to explain the issue & how to reproduce it. If you can´t provide me this stuff, I am not able to fix it.

So please, provide it.
