### ISSUE TITLE
Basic bot protection, If X amount of new players all join and say X in X amount of time then do X.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1513]
You already listen for new player joins and you are reading chat, a really simple way to do X (say run a command like kick) would simply be to see if X amount of people all join within X amount of time (say a second) and all say the same thing, then kick them.
Most bot attacks spam the same thing.

**Comment by johenkel** [comment]
Great idea! 
Run a custom command and even having an option to run a delayed 2nd would give the bot controller no indication of what ticket it off.

**Comment by lackoSK** [comment]
Hey,

Thanks for your idea! It´s a great idea. We will consider adding it 👍

**Comment by lackoSK** [comment]
Okay, 

We have added it; you will be able to download it in the next update of ChatControl <)

Thanks for the idea!

Regards,
lackoSK
