### ISSUE TITLE
SUPERGUILDS plugin placeholder does not work

### ISSUE THREAD

**Issue by MaxIsV** [kangarko/ChatControl-Pro#1515]
My minecraft version:
Paperspigot 1.12.2

I have a SUPERGUILDS plugin, I want the chat to display the name of the Guild you are a member of. But unfortunately the placeholder does not work, it looks like this: "{skript_superguilds::{player}::guild_name}"
This plugin is a script, so the placeholder looks like this. I tried to insert it in different ways, changed {player} to {player_name}, but nothing helped. I also tried all kinds of formatter priorities. I don’t know what else could solve my problem...

I tried this placeholder with another chat plugin, everything worked there, when I put a special placeholder (instead of {player}) from the plugin itself, which gave out the player’s nickname.

My plugin's folder:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4048515/ChatControl.zip)

**Comment by JavaFactoryDev** [comment]
Hi MaxIsV,

Thanks for reporting this issue.
We have registered it and we will have a look at it asap.
If we can confirm this issue and if it's connected with ChatControlPro,
we will fix it asap

Regards,
Leonhard from MineAcademy

**Comment by lackoSK** [comment]
Hey, I don't think that´s an actual placeholder? Can you do 

/papi parse {player} {skript_superguilds::{player}::guild_name}

And send us the output?

**Comment by MaxIsV** [comment]
Unfortunately, the placeholder does not work with this command, so you need to replace "{player}" with another placeholder. For example, in the TitleManager plugin, I took the placeholder "% {name}", which adds the TitleManager itself and so it works. But in this plugin (ChatControl) placeholders {player} and {nick} did not work.

**Comment by lackoSK** [comment]
> /papi parse {player} {skript_superguilds::{player}::guild_name}

If it does not then it´s not PlaceholderAPI or MVdWPlaceholderAPI placeholder.

We support only MVdWPlaceholderAPI and PlaceholderAPI in our plugins. 

Thanks!

**Comment by MaxIsV** [comment]
Sorry, but this is exactly the PAPI placeholder, just in SUPERGUILDS it is implemented a little incorrectly. If you use "% skript_superguilds :: Detfor :: guild_name%", then the guild name is displayed correctly, which means the placeholder is working. In other plugins, I did not have a problem with this, I placed inside it, instead of {player}, a placeholder from the plugin itself to get the player’s nickname. But when I applied it in your plug-in (ChatControl), then nothing worked for me.

**Comment by lackoSK** [comment]
Hey

do /papi parse {player} {skript_superguilds::{player}::guild_name}

and send us the output.

**Comment by MaxIsV** [comment]
Output is "{skript_superguilds::{player}::guild_name}"

> Hey
> 
> do /papi parse {player} {skript_superguilds::{player}::guild_name}
> 
> and send us the output.

**Comment by lackoSK** [comment]
can you try also %% ?

**Comment by MaxIsV** [comment]
When using the command "/papi parse me %skript_superguilds::{player}::guild_name%", the output is "VGuild", that is, the correct name of the player’s guild. But in formatting.yml, it does not work, in the chat I see "%skript_superguilds::Detfor::guild_name%"

**Comment by kangarko** [comment]
Hi there, Matej here,

The problem is that the {player} variable is replaced _after_ the long variable from SuperGuilds, leaving the {player} unreplaced causing errors:

![a](https://i.imgur.com/w47iO1r.png)

There are no current plans of changing the order of things as this would break other stuff and variables in PAPI. 

As a last resort you could set Variables.Custom_Enabled to true in settings.yml and try putting this in your variables/javascript.txt:

```
define {guild_test}
script:
  "{skript_superguilds::" + player.getName() + "::guild_name}"
```

Then test using {guild_test} , however if that does not work then unfortunately it won't work.

**Comment by MaxIsV** [comment]
> Hi there, Matej here,
> 
> The problem is that the {player} variable is replaced _after_ the long variable from SuperGuilds, leaving the {player} unreplaced causing errors:
> 
> ![a](https://camo.githubusercontent.com/0cc387e49d4da77ddc601b31f33c7eeb495152ee/68747470733a2f2f692e696d6775722e636f6d2f773437694f31722e706e67)
> 
> There are no current plans of changing the order of things as this would break other stuff and variables in PAPI.
> 
> As a last resort you could set Variables.Custom_Enabled to true in settings.yml and try putting this in your variables/javascript.txt:
> 
> ```
> define {guild_test}
> script:
>   "{skript_superguilds::" + player.getName() + "::guild_name}"
> ```
> 
> Then test using {guild_test} , however if that does not work then unfortunately it won't work.

I get the result "N / A" :(

**Comment by MaxIsV** [comment]
> Hi there, Matej here,
> 
> The problem is that the {player} variable is replaced _after_ the long variable from SuperGuilds, leaving the {player} unreplaced causing errors:
> 
> ![a](https://camo.githubusercontent.com/0cc387e49d4da77ddc601b31f33c7eeb495152ee/68747470733a2f2f692e696d6775722e636f6d2f773437694f31722e706e67)
> 
> There are no current plans of changing the order of things as this would break other stuff and variables in PAPI.
> 
> As a last resort you could set Variables.Custom_Enabled to true in settings.yml and try putting this in your variables/javascript.txt:
> 
> ```
> define {guild_test}
> script:
>   "{skript_superguilds::" + player.getName() + "::guild_name}"
> ```
> 
> Then test using {guild_test} , however if that does not work then unfortunately it won't work.

Are you sure that I should use the placeholder code exactly how you wrote it? I didn’t find anything similar on the wiki page, everything looks completely different there

**Comment by MaxIsV** [comment]
Hooray! I managed to make a working placeholder using variables / javascript.txt:
`define {guild_test}
script:
  "{skript_superguilds::" + "{player_name}" + "::guild_name}"`
