### ISSUE TITLE
How to use First, Second and Third_Part in Ranked Format

### ISSUE THREAD

**Issue by BenjaminHoegh** [kangarko/ChatControl-Pro#1517]
How can i use `First_Part` `Second_Part ` `Third_Part` in a ranked format?

**Comment by lackoSK** [comment]
Hey, you can find it here! https://github.com/kangarko/ChatControl-Pro/wiki/Formats

**Comment by BenjaminHoegh** [comment]
@lackoSK I know but you got a error when trying to combine ranked format and part format

**Comment by lackoSK** [comment]
Send the error.

**Comment by lackoSK** [comment]
Closing the ticket due to inactivity.
