### ISSUE TITLE
Conflict with Script (Skript)

### ISSUE THREAD

**Issue by BrettplayMC** [kangarko/ChatControl-Pro#1518]
When using ChatControlPro and Skript side-by-side, ChatControl seems to not like the `cancel the event` effect in Skript.  When done without ChatControl for example, if I want to cancel a chat message from being sent, it works fine however with chatcontrol installed, I get this:
![image](https://user-images.githubusercontent.com/20050432/72302331-4cea2e80-362f-11ea-9b5f-3146275646fc.png)
A fix for this would be amazing, thanks.

**Comment by lackoSK** [comment]
Still not sure what your issue is. Can you please explain it?
