### ISSUE TITLE
Chatcontrol setcolor does not work

### ISSUE THREAD

**Issue by MrMorganCz** [kangarko/ChatControl-Pro#1519]
Hi, I have a problem with the /chc setcolor command if a player sets for example red, so it doesn't not change, it looks like a permission issue... because if I have * it works ...
 
Chatcontrol: 8.5.4
Permission plugin: LuckPerms v5.0.39
Server type: Paper -version git-Paper-48 (MC: 1.15.1)

**Comment by lackoSK** [comment]
Hey,

Can you check the user have these permissions?
> Perm: chatcontrol.chat.format.color.{color}
Info: Permission to use a specific color with the '&' character. 
      Replace {color} with the color name, or * for all colors. 
      - Use LOWERCASED names from 
        https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html

**Comment by MrMorganCz** [comment]
Yes, players have it, but it doesn't work ...

**Comment by lackoSK** [comment]
Do you have chatcontrol formatting enabled?

**Comment by MrMorganCz** [comment]
Yes.

**Comment by lackoSK** [comment]
Do you have the MySQL enabled?

**Comment by MrMorganCz** [comment]
Yes, if it helps you i can send chat control file to discord till pm

**Comment by lackoSK** [comment]
Yes, you can. Contact me over discord **lackoSK#0001**

**Comment by MrMorganCz** [comment]
Solved

**Comment by TheJoshue** [comment]
any help for this? i have the same issue
except that i am on CHC PRO 8.10.11

**Comment by WolverStones** [comment]
> any help for this? i have the same issue
> 
> except that i am on CHC PRO 8.10.11

Sorry unfortunately I no longer remember how it was solved.
