### ISSUE TITLE
/tell & /msg bug

### ISSUE THREAD

**Issue by Digiw0lf** [kangarko/ChatControl-Pro#152]
/tell and /msg aren't working seems to go to minecraft /tell or /msg . I have disabled the essentials message commands in the plugin.yml 

Plugin List : Wild, TitleAdvanced, WorldEdit, DragonEggDrop, EssentialsX, ChatControl, WorldGuard, Multiverse-core & portals, HeadDatabase, Litebans, Holograms, VoxelSniper, Particles, Tab. Vault, EssentialsXSpawn, LockettePro, MoneyMobs, Towny, VirtualShops, TownyGUI, CreateReloaded, LuckyPerms, DiscordSRV, Vouchers, AuctionHouse, HeadDatabase

**Comment by kangarko** [comment]
Make sure you have enabled them within the plugin itself by setting **Private_Messages.Enabled** to **true** in settings.yml

**Comment by Digiw0lf** [comment]
# -----------------------------------------------------------------------------------------------
# Private messages allow you to secretly message another player without everyone else seeing.
# There are currently following commands: /tell and /reply
# [NOTICE] If disabled, you can still use commands with the same label from other plugins/server.
# -----------------------------------------------------------------------------------------------
Private_Messages:
  Enabled: true
  
  Bungee: false
  
  Aliases:
    Tell: [message, t, whisper, msg, emsg, pm, w]
    Reply: [r, reply]
  
  # Following two formats are effective if you have disabled interactive chat (Chat.Formatter.Interactive.Enabled).
  Static_Format_Sender: "&8[&6you &8-> &6{player}&8] &7{message}"
  Static_Format_Receiver: "&8[&6{player} &8-> &6you&8] &7{message}"
  
  # Interactive formatters.
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver

**Comment by Digiw0lf** [comment]
Config files

https://mega.nz/#!FsQyBLrD!nMQkZkiqyBveHP1v19U5GIf19S8fKlZs3NxwVODXu_4

**Comment by kangarko** [comment]
Is there any error message when server starts or players run /msg command? If unsure, post me the part from server startup log where chatcontrol starts.

**Comment by kangarko** [comment]
Closing, assuming it's fixed, comment below if any questions.
