### ISSUE TITLE
Reply command lagg spikes

### ISSUE THREAD

**Issue by MoonSoD** [kangarko/ChatControl-Pro#1520]
**Minecraft version:** 1.15.1
**Chatcontrol version:** 8.5.4

So I have been experiencing this issue for quite some time. Every time someone uses the reply command the server gets into a **heavy** lagg spike. Sometimes it gets to the point when 2 people are communicating through the reply command and the server gets unplayable. That got me to disable the reply command entirely. Using BungeeControl with connected chats aswell.

Here is an example of the spikes, every significant drop on the graph is caused by the reply command.
![spikes](https://user-images.githubusercontent.com/35657724/72379443-b8a5c780-3713-11ea-9464-41fdba547d5f.png)

After contacting the support on discord I got told to send the timings report and settings

**Timings:** [can be found here](https://timings.aikar.co/?id=06accf83f4e64a579f79f7fec22ba0df#plugins)
**Settings:** [can be found here](https://gist.github.com/MoonSoD/e106c1e3d825d9e28617dbcb4bca1f86)

**Comment by lackoSK** [comment]
Hey!

As I told you, I will do the testing tomorrow!

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hey!

I could not restimulate the lag; Please provide us the exact steps on how to do it. Include us your´s entire ChatControl folder.

Thanks

**Comment by AmazedMender16** [comment]
@MoonSoD You're not alone on this same, seeing the exact same here.
This does not happen when there are only a few users texting, this happens when there are quite a few people on a server.
My TPS drops to 5 in some cases

**Comment by lackoSK** [comment]
Okay guys, send me your timings, when it appears (in details) and **test ChatControl only alone on the servers** (if the lag appears also without other plugins)

Thank you guys!

**Comment by AmazedMender16** [comment]
@lackoSK excuse me but @MoonSoD already provided timings, these look similar to mine.. 
These drops already start after 5 minutes of running..

**Comment by AmazedMender16** [comment]
Sharing: servers have been running fine since disable Private Messaging in ChatControl, I do want to re-enable this again though.. Please look into this..

**Comment by kangarko** [comment]
@MoonSoD I see you have Toast notifications enabled. This caused a heavy disk operation whenever a /tell or a /reply command is invoked. At present, to show Toasts this is the only way to do it and so if you experienced unbearable lag spikes, you'll have to disable it: https://i.imgur.com/dhTBcE3.png

**Comment by AmazedMender16** [comment]
@kangarko I don't have that feature enable and I'm experiencing the same thing.

**Comment by kangarko** [comment]
@AmazedMender16 please send me a PM on SpigotMC with your full timings report so I can open and navigate it + your ZIP folder of ChatControl installed on the problematic server. It may but it may not be the same problem if you don't have Toasts enabled.

**Comment by AmazedMender16** [comment]
> @AmazedMender16 please send me a PM on SpigotMC with your full timings report so I can open and navigate it + your ZIP folder of ChatControl installed on the problematic server. It may but it may not be the same problem if you don't have Toasts enabled.

@kangarko Send it to you on Spigot, thanks!

**Comment by lackoSK** [comment]
Fixed in the last update 8.5.8
