### ISSUE TITLE
String index out of range: -1

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#1521]
https://pastebin.com/raw/88tZe4XT

**Comment by lackoSK** [comment]
Hey,

Please provide us more information, when it appears the exact details etc.

**Comment by R1NZLER15** [comment]
> 
> 
> Hey,
> 
> Please provide us more information, when it appears the exact details etc.

Same issue here, it just appears randomly, it messes up the chat format and there seems to be no pattern for when this error log appears

https://pastebin.com/raw/PRj0rw0w

**Comment by lackoSK** [comment]
>it messes up the chat format

Can you send me a pick of chat after?
