### ISSUE TITLE
/chc announce oneliner

### ISSUE THREAD

**Issue by TNTUP** [kangarko/ChatControl-Pro#1524]
One-Liner announcements throws out an error. (/chc announce (message) should return a oneline announcement

Tried like Message: '&aServerName &8&l//&f {message}' but it seems not to accept it. If adding a new line, it works.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4069912/ChatControl.zip)

Uploaded the zip, in the messages_en.yml, you'll see the oneliner announcement. The required file is present in the zip file (error.log).

**Comment by lackoSK** [comment]
Can you send the error?

**Comment by HexedHero** [comment]
https://pastebin.com/raw/5EfwdEgu

Its literally in the file.

**Comment by lackoSK** [comment]
Hey,

Can there should be something more. There should be a stack trace above it. Can you send that one? Thanks.

**Comment by TNTUP** [comment]
> Hey,
> 
> Can there should be something more. There should be a stack trace above it. Can you send that one? Thanks.

Will look and update this comment aswell

**Comment by lackoSK** [comment]
Hey,

Apologies the super late reply, I will release the new update tomorrow. 

Thanks for being patient.

**Comment by TNTUP** [comment]
> Hey,
> 
> Apologies the super late reply, I will release the new update tomorrow.
> 
> Thanks for being patient.

No problem! Take your time :)

**Comment by kangarko** [comment]
Thanks, oddly enough but it seems we have fixed it :)

**Comment by TNTUP** [comment]
Big thanks to you Kangarko <3
