### ISSUE TITLE
Per-channel Discord formatting.

### ISSUE THREAD

**Issue by TheReverend403** [kangarko/ChatControl-Pro#1526]
I'm trying to have a setup where my standard discord<->minecraft chat uses one format both ways (no prefix), and a different format for my admin chat with a prefix, both ways. Right now, my channels send and receive the correct discord channels. The admin chat in game has the prefix, but when a message is sent to the staff channel on discord, the staff channel in-game receives the standard format with no prefix, making it impossible to tell if a staff message came from discord in-game. Am I doing something wrong or is this just not possible?

![standard](https://dev.pste.pw/f/1sz.png)

![standard](https://dev.pste.pw/f/TmG.png)

![admin](https://dev.pste.pw/f/6Yo.png)

![admin](https://dev.pste.pw/f/quD.png)

I'm trying to get the second one to look like this for messages from discord.

![staff](https://dev.pste.pw/f/2WB.png)

**Comment by lackoSK** [comment]
Can you send me the ChatControl's folder ? Also please, have a look, if you didn't messed up the discord channel' ids. 

Thanks!

**Comment by TheReverend403** [comment]
> Can you send me the ChatControl's folder ? Also please, have a look, if you didn't messed up the discord channel' ids.
> 
> Thanks!

https://dev.pste.pw/f/Qjb.gz

**Comment by lackoSK** [comment]
Everything seems okay, 

But do you want to change the formatting of message wrote on discord and sent to mc?

**Comment by TheReverend403** [comment]
Yes, but only for a specific channel.

**Comment by lackoSK** [comment]
Hey,

You should be able to do it:
https://github.com/kangarko/ChatControl-Pro/wiki/Channels#format

Best,
Ladislav

**Comment by TheReverend403** [comment]
That doesn't allow you to set a *per-channel* discord format.

**Comment by lackoSK** [comment]
Hello,

It should be possible: 
![image](https://user-images.githubusercontent.com/53174757/73379465-8fb03580-42c2-11ea-87d8-ea3535770986.png)

If you don't mean this feature, I can add it for you. 

Regards,
lackoSK

**Comment by TheReverend403** [comment]
No, I don't mean that feature. That sets the Discord format for *all* channels.

**Comment by lackoSK** [comment]
Do you want to change it for each channel different?

**Comment by TheReverend403** [comment]
Yes.

**Comment by lackoSK** [comment]
Hello,

Thanks for the idea
I have added it to TODO list ^^

Regards,
lackoSK
