### ISSUE TITLE
Player Perm Muted

### ISSUE THREAD

**Issue by Copendub** [kangarko/ChatControl-Pro#1528]
Player was Perm muted for cursing and cant figure out how to unmute them also I just want players chat to be censored not mute them and can't figure that out either.

**Comment by lackoSK** [comment]
What command did you used to mute exact player? 


>  I just want players chat to be censored not mute them and can't figure that out either.

I think you will have to write a JS condition for it.

**Comment by Copendub** [comment]
I ended up figuring it out. It was grief prevention that did it. Thanks for
replying tho.
