### ISSUE TITLE
[1.15.1] issue with join message & DiscordSRV hook

### ISSUE THREAD

**Issue by thinkverse** [kangarko/ChatControl-Pro#1529]
### Write your Minecraft version in the title:
- System Info: Java 1.8 (Eclipse OpenJ9 VM openj9-0.14.0)
- Host: Linux 4.15.0-55-generic (amd64)
- Paper 1.15.1-62
- ChatControl 8.5.4
- DiscordSRV 1.18.4
### Be clear: What is your current situation, desired situation, and your problem?
Join messages has stopped working; see [NullPointerException](https://pastebin.com/dv7Rj1Ej), I don't get why it says I'm not using Java 8 when I am, it all worked before I restarted my server, same config, and everything, all worked, restarted the server, and now nothing is working as it should, and trying to reload **ChatControl** causes it to error about **DiscordSRV**, I just want it to go back to normal and start working again.
### Upload your plugin's folder.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4100332/ChatControl.zip)

**Comment by thinkverse** [comment]
Did some testing and the issue seems to be with the newest version of Spigot and Paper, switched back to `Paper 1.15.1-60` and everything worked, updating to `Paper 1.15.1-62` broke something, not sure what yet.

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting the issue, if we can confirm it, we will fix it ASAP. 

Hope you understand.

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hello,

This issue is being resolved in ticket #1531 

I will close this one - Hope you understand.

Regards,
lackoSK
