### ISSUE TITLE
PM Spy Formatting Doesn't Apply?

### ISSUE THREAD

**Issue by jakkuh** [kangarko/ChatControl-Pro#1530]
I switched over to ChatControls internal PM system rather than using Essentials in hopes of making use of the `Format_PM` formatting so our mods can more easily distinguish who is messaging who.

However, it seems like it never usees `Format_PM` and rather uses the `Format` formatting.  I've noticed it does at least use the `Format_PM` formatting with the `/reply` command, but none of the others (/msg, /whisper, /tell, etc).

```
  Format: '&8[&5SPY&8] &7{player}: &7{message}'
  Format_PM: '&8[&5SPY&8] &7[{player}] -> [{receiver}]: &7{message}'
```

https://i.imgur.com/2HAuUkw.png

MC Version: 1.12.2 Paper 1618
ChatControl: 8.4.11

**Comment by lackoSK** [comment]
Hey,

Can you update your ChatControl to the latest version? 

Thanks!
