### ISSUE TITLE
Global chat without "!"

### ISSUE THREAD

**Issue by R4zzerYT** [kangarko/ChatControl-Pro#1532]
Is it possible to make global chat to the default chat format?

**Comment by R4zzerYT** [comment]
bump

**Comment by lackoSK** [comment]
Hey,

Sorry for the late reply, 
(you do not have to "bump" issues.)

Do you mean formatting? 
https://github.com/kangarko/ChatControl-Pro/wiki/Formats

If yes, you can find the answer above. If not, just message here again.
