### ISSUE TITLE
[1.15.2] NPE in Runnable, Java version issue persists

### ISSUE THREAD

**Issue by thinkverse** [kangarko/ChatControl-Pro#1533]
### Write your Minecraft version in the title:
- System Info: Java 1.8 (Eclipse OpenJ9 VM openj9-0.14.0)
- Host: Linux 4.15.0-55-generic (amd64)
- Paper 1.15.2-65
- ChatControl 8.5.4
### Be clear: What is your current situation, desired situation, and your problem?
While not officially supported with an update yet, just thought I'd let the team know that CHC for 1.15.2 is throwing a NPE in what I'm guessing it the tip runnable? [NPE Error](https://pastebin.com/u8fEJjsN), and the plugins seems to think I'm not running Java8 when I am issue is persisting in 1.15.2 aswell.
### Upload your plugin's folder.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4100326/ChatControl.zip)

**Comment by v3Monsta** [comment]
Same issue here, it looks like the day has finally come where Nashorn isn't available.

**Comment by MrMorganCz** [comment]
next time you should check to see if you have sensitive data such as password to db ...

**Comment by thinkverse** [comment]
> next time you should check to see if you have sensitive data such as password to db ...

Thank you for reminding me, that totally slipped my mind.

**Comment by lackoSK** [comment]
#1531
