### ISSUE TITLE
Tell/Reply is causing crazy TPS drops.

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#1534]
I have been using chatcontrol pro for years, since recent updates the /tell and /reply command is bringing my server TPS down like crazy. Once I remove chatcontrol PRO it runs completely fine.

https://prnt.sc/qrf3ic

I do use BungeeControl and Accross bungee private messaging.
We are running Paper 1.15.2

https://prnt.sc/qrfdk2

**Comment by lackoSK** [comment]
#1520

**Comment by kangarko** [comment]
Continued in the issue above

**Comment by AmazedMender16** [comment]
Reopening this, was fixed but came back in recent updates..

**Comment by AmazedMender16** [comment]
This came back in 8.6.x, still waiting on a resolution, @lackoSK was gonna check 1 month ago ( discord )
@kangarko

**Comment by kangarko** [comment]
@lackoSK ?

**Comment by lackoSK** [comment]
Edit: Communication over the discord.

**Comment by AmazedMender16** [comment]
@kangarko I'm seeing this again on 8.8.16...
https://prnt.sc/v3c8id
