### ISSUE TITLE
1.15.2 Breaking Chatcontrol 

### ISSUE THREAD

**Issue by Phamous1** [kangarko/ChatControl-Pro#1535]
[eq0f0dfA.txt](https://github.com/kangarko/ChatControl-Pro/files/4101707/eq0f0dfA.txt)

I have no clue what this is trying to do lol. It gave a java error, but once i restarted it fixed itself.  But now i have this error in error log, but nothing in startup log

**Comment by Phamous1** [comment]
Donno what i was thinking lol.  But theres the loggs 
[error (2).log](https://github.com/kangarko/ChatControl-Pro/files/4103800/error.2.log)
[settings.txt](https://github.com/kangarko/ChatControl-Pro/files/4103803/settings.txt)
The Start up log is showing Java error.  Is missing a library, but it is up to date, so not sure what has changed from 1.15.1 to 1.15.2 everything is the same, this plugin is the only one  that broke it the upgrade

**Comment by lackoSK** [comment]
#1531

**Comment by Phamous1** [comment]
Sounds good, sorry for the double post didnt see the other one when i did it

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/1531
