### ISSUE TITLE
Using variables inside PlaceholderAPI variables 

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1538]
For an exmaple this Papi requires the text to be put inside the variable name, so it would be:
` {RainbowColor_{message}}`
This does not work, can you please support putting variables inside variables. 
https://github.com/aBooDyy/RainbowColor-Expansion

**Comment by lackoSK** [comment]
Hey, 

Thanks for your idea! We will consider adding it <)

Regards,
lackoSK

**Comment by kangarko** [comment]
Sorry it's not possible with the current system from the ground up. The only idea I would have is to create a new javascript variable in variables/javascript.txt file:

```
define {test}
script:
  "{RainbowColor_{message}}"
```

**Comment by FrozenBeard** [comment]
So I can do this if I create the variable as a JavaScript variable first? 
What would I need to toggle in settings @kangarko ?

**Comment by lackoSK** [comment]
Yea, u can use JS to do it. See our wiki for tutorial.

**Comment by FrozenBeard** [comment]
> 
> 
> Sorry it's not possible with the current system from the ground up. The only idea I would have is to create a new javascript variable in variables/javascript.txt file:
> 
> ```
> define {test}
> script:
>   "{RainbowColor_{message}}"
> ```
> 
> You'd have to toggle some options in the Variables section of settings.yml

Right the day has come April 1st to use this, and this does not work, it still just prints out:
{RainbowColor_this is the message}
I have been playing around with javascript, but it throws errors to do with the curly brackets which you use, as it conflicts with JavaScript.

For example. this also does not work, as it throws errors:

```
define {RainbowMessages}
script:
  var messageTag = "{message}";
  var Rainbow = "{RainbowColor_"+messageTag+"}";
  Rainbow;
```
 
Its really annoying not being able to put a variable inside a placeholder variable, even with Javascript, I know its suppose to work as I did a test of static text in the formatting.

```
    Message:
      Message: '{RainbowMessages} {RainbowColor_This is an example}'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/msg {player} '

```

"This is an example" is shown in rainbow text.

**Comment by FrozenBeard** [comment]
![Screenshot 2020-04-01 13 30 27](https://user-images.githubusercontent.com/144046/78137354-10072a00-741d-11ea-84e8-e76f6f83faa8.png)


Even if I escape the brackets, it still throws an error, but actually puts the variable name in rainbow in the console lol!

**Comment by lackoSK** [comment]
Okay, so what do you need us to help with?

**Comment by FrozenBeard** [comment]
The examples given do not work, and I tried other Javascript to try and get it to work, but it dousnt.

**Comment by lackoSK** [comment]
If you still need help with this. Simply, comment under this issue.

**Comment by kangarko** [comment]
@lackoSK please **read** what he wrote above before closing

**Comment by lackoSK** [comment]
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org
