### ISSUE TITLE
Custom Join Messages.

### ISSUE THREAD

**Issue by MaxIsV** [kangarko/ChatControl-Pro#1541]
I want to make custom messages when players enter, but they are not visible when "Hide_Join_Quit_Kick_Messages:" is set to true. And if you set "Hide_Join_Quit_Kick_Messages:" to false, then the standard join/left messages that I want to hide will be visible.

**Comment by lackoSK** [comment]
Hey, 

I've fixed that, you will be able to download it in the next update.

Thanks! 

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hello,

Can you send us your ChatControl's folder? 

If the flag is set to true, all kick messages OR if the user is muted, will be hidden. 

Regards,
lackoSK

**Comment by MaxIsV** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4135435/ChatControl.zip)
(I removed the logs from the folder, because there is valuable information that you do not need)

**Comment by MaxIsV** [comment]
And I did not understand what you wanted to say with this message: "If the flag is set to true, all kick messages OR if the user is muted, will be hidden." Sorry, I just do not know much English and use GoogleTranslate

**Comment by lackoSK** [comment]
Hey,

Let me explain: 
If you set the flag to true, if the user, is kicked, we will hide the message.

Primary, it's meant to work with the bungeecords
![image](https://user-images.githubusercontent.com/53174757/73523748-d65d7700-440b-11ea-92f1-ed6b3cd1542d.png)

Regards,
lackoSK
