### ISSUE TITLE
Error on /chc reload after changing listener priority

### ISSUE THREAD

**Issue by Darkweasam** [kangarko/ChatControl-Pro#1543]
Whenever I change my listener priority, /chc reload breaks the whole plugin

Error loading configuration in settings.yml!
29.01 09:30:21 [Server] Startup [14:30:21 INFO]: Problematic section: Listener_Priority
29.01 09:30:21 [Server] Startup [14:30:21 INFO]: Problem: org.mineacademy.chatcontrol.final.nul. .com9: Report / [DO NOT REPORT, SEE ABOVE AND FIX IT] Illegal value in settings.yml, see above for steps how to fix it (see below for more)

If I change

Listener_Priority:
Checker: LOWEST

To NORMAL, HIGH, HIGHEST or MONITOR the plugin breaks!

**Comment by lackoSK** [comment]
Hello,

After changing the listener's priority, you have to restart your server. 

Have you done it? 

Regards,
lackoSK

**Comment by Darkweasam** [comment]
Hello,

Yes but if i do /chc reload then everything breaks again

**Comment by lackoSK** [comment]
Send us the error.

Thanks!

**Comment by Darkweasam** [comment]
https://pastebin.com/s30SCcy9

`Listener_Priority:
  Checker: NORMAL
  Formatter: LOWEST
  Signs: LOWEST`

**Comment by lackoSK** [comment]
Hello,

`29.01 16:01:48 [Server] Startup [21:01:48 INFO]: ** THIS IS NOT A BUG, DO NOT REPORT, JUST CHANGE A KEY
29.01 16:01:48 [Server] Startup [21:01:48 INFO]: ** IN YOUR SETTINGS.YML YOURSELF
29.01 16:01:48 [Server] Startup [21:01:48 INFO]: Listener_Priority.Formatter must be higher than
29.01 16:01:48 [Server] Startup [21:01:48 INFO]: Listener_Priority.Checker! This is to prevent
29.01 16:01:48 [Server] Startup [21:01:48 INFO]: messages being formatted before they are checked.
29.01 16:01:48 [Server] Startup [21:01:48 INFO]: If unsure just set Listener_Priority.Formatter to
29.01 16:01:48 [Server] Startup [21:01:48 INFO]: HIGH in settings.yml`

It almost told you what to do.

Formatter must have higher priority then checker. Please, give it to it.

Regards,
lackoSK
