### ISSUE TITLE
Redis Support

### ISSUE THREAD

**Issue by jakkuh** [kangarko/ChatControl-Pro#1545]
We run ChatControl Pro on a large network with multiple bungees connected. We do not however use RedisBungee, rather a custom setup that provides similar functionality.

With that in mind, I'd request that ChatControl/BungeeControl adds native support for using Redis for bungee messages outside of the RedisBungee plugin (ie. setting up a native Redis messaging service for BungeeControl).

I'm willing to provide a dev environment for this if needed.

**Comment by lackoSK** [comment]
Hello,

I am not sure what you mean exactly. But we support Redis within BungeeControl

Regard,
lackoSK

**Comment by jakkuh** [comment]
The support for REdis with BungeeControl is done through the RedisBungee API (as far as I am aware).

What I'm asking for is native Redis support, where you would supply your Redis server IP / password, and BungeeControl would forward messages/alerts/whatever to other BungeeControl instances also connected to the Redis server. This is instead of using the RedisBungee API as many server have multiple Bungee servers but use a custom solution to link them rather than using RedisBungee.

**Comment by lackoSK** [comment]
Oof, 

Like, I can push it to the roadmap. But I am not telling you it will be added. Maybe after the recoding of ChatControl. 

I hope you understand. 

Best,
lackoSK

**Comment by jakkuh** [comment]
I'm happy to have one of our dev's contribute the code to BungeeControl for redis, but it's closed source.

Let me know if there is anyway we can help! Discord: jake#0001.

**Comment by lackoSK** [comment]
I’m sorry, can’t add you. lackoSK#0001 feel free to contact me here.

**Comment by jakkuh** [comment]
Sent
