### ISSUE TITLE
ignore bungeewide?

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1547]
Hi,

I can't find the option anywhere to set /ignore for bungeewide. At the moment it only ignores if the target is in the same server, but when it's in another server the messages are not longer ignored.
Is this a bug or did I miss a setting?

martijnpu

**Comment by lackoSK** [comment]
Hello,

We do not support ignore over bungee.
It's already in our roadmap.

Regards,
lackoSK
