### ISSUE TITLE
Server lag caused by ChatControl 

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [kangarko/ChatControl-Pro#1548]
I had this error, while running ChatControl. 
https://pastebin.com/VT0Jbafd

Im using it on bungeecord and message is sended to chat (and other servers) correctly, but as the error says server is froze

Version 8.5.6
Paper b87 1.15.2

**Comment by lackoSK** [comment]
Hello,

Can you please send us your ChatControl's folder? 
Also, please set the debug to "debug: [*]" in the settings.yml and send us the console output.

Regards,
lackoSK
