### ISSUE TITLE
PremiumVanish private message issue

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1549]
When players use /msg they can see vanished players in tab complete.
Bungee is enabled, not sure if that's related.

Could this possibly be fixed?

**Comment by lackoSK** [comment]
Hello,

We don't support filtering tab-complete from bungeecord users. This is already in our roadmap and should be added in some time. 

PS: I am working on that roadmap almost every day.

Regards,
lackoSK

**Comment by Sikatsu** [comment]
Ahh well I hope this will be a priority, vanish is sort of useless now if we just show up in tab complete.

**Comment by lackoSK** [comment]
I will close it here, it will be added soon.

**Comment by Sikatsu** [comment]
Thanks. Would be nice
