### ISSUE TITLE
Error Starting

### ISSUE THREAD

**Issue by Haveyougonemad** [kangarko/ChatControl-Pro#1551]
> [15:29:59 INFO]: *-----------------------------------------------*
> [15:29:59 INFO]: Plugin is now disabled.
> [15:29:59 INFO]: *-----------------------------------------------*
> [15:29:59 INFO]: [ChatControl] Disabling ChatControl v7.6.16
> [15:29:59 INFO]: Plugin might not shut down property. Got NullPointerException: null
> [15:29:59 WARN]: java.lang.NullPointerException
> [15:29:59 WARN]: at me.kangarko.chatcontrol.null.COm4.const(SourceFile:877)
> [15:29:59 WARN]: at me.kangarko.chatcontrol.null.COm4.const(SourceFile:249)
> [15:29:59 WARN]: at me.kangarko.chatcontrol.null.LPt1.onDisable(SourceFile:185)
> [15:30:00 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
> [15:30:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
> [15:30:00 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.lpt4.const(SourceFile:429)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.Com9$super.const(SourceFile:123)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.Com9$super.const(SourceFile:113)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.Com9$super.const(SourceFile:105)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.Com9.strictfp(SourceFile:54)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.Com9.const(SourceFile:32)
> [15:30:00 WARN]: at me.kangarko.chatcontrol.null.LPt1.onEnable(SourceFile:85)
> [15:30:00 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [15:30:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
> [15:30:00 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
> [15:30:00 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
> [15:30:01 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
> [15:30:01 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
> [15:30:01 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
> [15:30:01 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
> [15:30:01 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
> [15:30:01 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
> [15:30:01 WARN]: at java.lang.Thread.run(Unknown Source)
> [15:30:01 INFO]: _____ _ _ _____ _ _ +
> [15:30:02 INFO]: / ____| | | | / ____| | | | |
> [15:30:02 INFO]: | | | |__ __ _| |_| | ___ _ __ | |_ _ __ ___ | |
> [15:30:02 INFO]: | | | '_ \ / _` | __| | / _ \| '_ \| __| '__/ _ \| |
> [15:30:02 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
> [15:30:02 INFO]: \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_| \___/|_|
> [15:30:02 INFO]:
> [15:30:20 INFO]: Configuration loads..
> [15:30:20 INFO]: Created default file: settings.yml
> [15:30:21 INFO]: Created default file: javascript.txt
> [15:30:22 INFO]: Created default file: channels.yml
> [15:30:22 INFO]: Created default file: data.db
> [15:30:23 INFO]: Created default file: formatting.yml
> [15:30:24 INFO]: Created default file: messages.yml
> [15:30:25 INFO]: *-----------------------------------------------*
> [15:30:25 INFO]: Please contact kangarko at SpigotMC!
> [15:30:25 INFO]: Plugin is now disabled.
> [15:30:25 INFO]: *-----------------------------------------------*
> [15:30:25 INFO]: ChatControl 7.6.16 encountered a lpT4! Please check your error.log and report this issue with the information in that fil

**Comment by lackoSK** [comment]
Hello,

You are running a very outdated version. Download the newest version.

Regards,
lackoSK

**Comment by Haveyougonemad** [comment]
lmao

**Comment by lackoSK** [comment]
Hi,

What lmao? ** Update to the newest version.**

Regards,
lackoSK

**Comment by Haveyougonemad** [comment]
i tried BUT nope
I unistalled it ANd now i'm rather using other

**Comment by lackoSK** [comment]
What nope?

Just get the newest version..

If there is some error when booting, send it here.

Regards,
lackoSK
