### ISSUE TITLE
Add a GUI selector for the format groups

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1553]
Hey,

I made several tags/badges within the formatting.yml file;

>    Novice:
      Message: '&2[N] '
      Sender_Permission: chatcontrol.groups.novice
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&7----- &3{player} &7-----'
        - '&7Deze badge is verdient door'
        - '&2[Novice] &7te behalen.'
        - ''
        - '&7Om de &2[N] &7badge te verdienen:'
        - '&3• &7Registreer op de website'
        - '&3• &7Badges zijn voor donator ranks'
        - ''
        - '&6Klik voor meer info over ranks!'
      Click_Event:
        Action: RUN_COMMAND
        Value: /ranks
    Villager:
      Message: '&a[V] '
      Sender_Permission: chatcontrol.groups.villager
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&7----- &3{player} &7-----'
        - '&7Deze badge is verdient door'
        - '&a[Villager] &7te behalen.'
        - ''
        - '&7Om de &a[V] &7badge te verdienen:'
        - '&3• &7Speel 24 uur'
        - '&3• &7Vote 15x'
        - '&3• &7Badges zijn voor donator ranks'
        - ''
        - '&6Klik voor meer info over ranks!'
      Click_Event:
        Action: RUN_COMMAND
        Value: /ranks

Would it be possible that players who have the permission can switch between them using a GUI?

**Comment by lackoSK** [comment]
Hello,

You can create JS condition ^^ 
See our wiki for tutorial :)

Regards,
lackoSK
