### ISSUE TITLE
Javascript variables still not working (8.6.1)

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1554]
errors are
https://pastebin.com/WBtpNEgV
and the created error.log:
https://pastebin.com/kg9QC1AJ

Ticket was closed already so you may not see this comment on that.

**Comment by lackoSK** [comment]
Hello,

I have seen it.
Duplicate: #1531 

Will close it here ^^

Regards,
lackoSK
