### ISSUE TITLE
Request: /Ignore from simpleclans chat

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1555]
Can we either have compatibility to /ignore chat from SimpleClans clan ally chat and clan chat, or a way to ignore people that use commands like /a or /c to talk in SimpleClans.

**Comment by lackoSK** [comment]
Hello,

We can try to.

However, the link developer has for the API is not working.
![image](https://user-images.githubusercontent.com/53174757/74080943-55286480-4a49-11ea-822a-779775f63810.png) (https://www.spigotmc.org/resources/simpleclans.5269/)

Regards,
lackoSK

**Comment by FrozenBeard** [comment]
Oh that resource is very outdated! Sorry I should have mentioned its updated on his github:
https://github.com/marcelo-mason/SimpleClans/releases

I have also requested via his end.
https://github.com/marcelo-mason/SimpleClans/issues/551

**Comment by lackoSK** [comment]
Cool,

If he would need any change inside our API, let us know ^^

Regards,
lackoSK

**Comment by FrozenBeard** [comment]
Via https://github.com/marcelo-mason/SimpleClans/issues/551

Chat Control needs to listen to an event from SimpleClans: 

> https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/events/ChatEvent.java
> ChatControl just needs to listen to this event and remove any player that used /ignore from the receivers list (`getReceivers()`).

**Comment by lackoSK** [comment]
Hi,

We can implement it in some while. 

Regards,
lackoSK

**Comment by FrozenBeard** [comment]
@kangarko please reopen this request for 8.x series.

**Comment by kangarko** [comment]
Thanks, I ensure this works again on V9. V8 is on the servicing channel right now.

**Comment by FrozenBeard** [comment]
I wont be using V9 if its flawed, I just want to have this in the stable version that will be updated in the future.

**Comment by kangarko** [comment]
Just to clarify: 8.x.x --> I am getting this to super-stable right now, then will release 9.1.0 which will also be super stable and then discontinue 8.x.x
