### ISSUE TITLE
Request: A profanity filter toggle. Not Chat_Ignorer!

### ISSUE THREAD

**Issue by B-Knight49** [kangarko/ChatControl-Pro#1556]
Chat ignorer stops the entire message from appearing if someone decides to filter out any messages that match the rules. For example:

"This message contains some vital information but sprinkled deeply within it is the word FUCK and now no one can see it if they've got the Chat_Ignorer filter enabled."

I'd like it so that people can run a command and they'll then be able to either see matched-words as censored or uncensored. 

(Sends) Player A: Message with information but also with a FUCK
(Receives) Player B: Message with information but also with a FUCK
(Receives) Player C: Message with information but also with a ****

Player B has a censorship filter disabled. Player C has the filter enabled. 

If you could handle the censoring/replacement of characters during the process of determining if a player has the Chat_Ignorer tag then you could easily handle per-player censorship rules. As it currently stands, the censorship rule is applied and then the new message is either sent or just ignored forever.

**Comment by lackoSK** [comment]
Hello,

With the current system, this is impossible, because we would have to run a different chat for each user. 

However, thank you for your idea, we can implement it after doing recode for ChatControl.

Hope you understand.

Regards,
lackoSK

**Comment by B-Knight49** [comment]
> With the current system, this is impossible, because we would have to run a different chat for each user.

That's not entirely true. See the following plugin for example:
https://github.com/Jochyoua/MCSF/blob/master/com/github/Jochyoua/MCSF/Main.java

You would simply just have to intercept the packet and customise that depending on the user. Were the code no obfuscated, I could probably edit ChatControl myself to include this.

**Comment by Leomelonseeds** [comment]
+1 for this, although this is closed...
