### ISSUE TITLE
Error 8.6.1

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1557]
Hey, after updating I got this error: https://pastebin.com/1D2QEk0R

**Comment by lackoSK** [comment]
Hi,

When did it start to happen? After updating ChatControl or Paper?

Ladislav

**Comment by Sikatsu** [comment]
After updating ChatControl. Paper is the same version.

**Comment by Sikatsu** [comment]
The private messages of ChatControl are broken, so much.

This error comes everytime I write this message for example:

https://pastebin.com/73Nz7UBZ

Also, when I write a message to someone in PM, mid sentence it just sents my message, while my input is still being written..

**Comment by lackoSK** [comment]
Hi,

This is not even real can happen.

Can you provide us your files, also please **test the ChatcControl alone on the server**

Regards,
lackoSK

**Comment by Sikatsu** [comment]
It does happen as of a recent update that made changes to the private messaging command.

Half way through my message, it just sents the message in the chat without clicking enter. 

[Survival.zip](https://github.com/kangarko/ChatControl-Pro/files/4208454/Survival.zip)

I'll try to make a record from it.

**Comment by lackoSK** [comment]
Damn, that's super weird, was chatting a while ago with three accounts, with your setting, always sent only after enter got pressed.

**Comment by Sikatsu** [comment]
It's indeed really weird, and it's a rare chance it happens. I tried to record it, wasn't able to reproduce. This morning it happened again, of course when I wasn't recording. It's super annoying and happens since the recent updates.

**Comment by xion87** [comment]
confirmed too, it happen on private chatting

**Comment by lackoSK** [comment]
Hi guys,

I am going to push a newer version with some fixes for it. 

Can you guys tell me if the issue continues after updating? 

Best,
lackoSK

**Comment by Sikatsu** [comment]
Will do, thanks!!
