### ISSUE TITLE
DiscordSRV bungeechat

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1558]
Hey, i'm trying to get the bungeechat showing up in DiscordSRV, but it's only logging the messages from the survival server where the DiscordSRV plugin is setup. How would I make it so the messages from the other servers also get logged?

**Comment by lackoSK** [comment]
Hi,

You want to send messages to bungeechat and forward them to each server?

Best,
Ladislav

**Comment by Sikatsu** [comment]
Basically, I want the bungeechat that is enabled by default in settings.yml (in my case) broadcasted to DiscordSRV.

**Comment by lackoSK** [comment]
Hello,

You, the bungeechat (chc g/bc), is just a channel in your ChatControl. You can set it up in the channels.yml

Regards,
lackoSK

**Comment by Sikatsu** [comment]
But I don't use bungeechat from channels.yml, I use the one from settings.yml and enabled it by default.

**Comment by lackoSK** [comment]
Why not just register chat everywhere - on each server?

**Comment by Sikatsu** [comment]
What do you mean?

**Comment by lackoSK** [comment]
Like, to register the discord channel on each server

**Comment by Sikatsu** [comment]
The issue is that it doesn't work with the bungeechat (linked chats between servers).

It works fine if you disable the bungeechat, use a per-server chat, and install DiscordSRV on every server as a workaround.

**Comment by lackoSK** [comment]
So you are saying that's a bungee issue?

**Comment by Sikatsu** [comment]
Nevermind, I don't need this anymore anyway
