### ISSUE TITLE
Admin Chat Shortcut permission

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl-Pro#1559]
Permissions page doesn't seem to show this permission, is there any?

**Comment by lackoSK** [comment]
Hello,

Of course, there is: 
https://github.com/kangarko/ChatControl-Pro/wiki/Permissions

![image](https://user-images.githubusercontent.com/53174757/74261961-4e754800-4cfc-11ea-8dff-f5c7f904c7ce.png)

Regards,
lackoSK

**Comment by Neeonn** [comment]
I don't think you understood me.
I can't find the permission that allows my players to access the staffchat using a shortcut (@).
