### ISSUE TITLE
Cannot.Command_Until_Moved

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1560]
The translation message `Cannot.Command_Until_Moved` is not used for blocked commands until a player is moved. Instead the message `Cannot.Chat_Until_Moved` is used

Used configuration:
Empty 1.15.2 test server.
ChatControl 8.6.1 default setup except:

```
  # Block chat until the player has moved? They can still execute commands.
  Block_Chat_Until_Moved: false

  # A list of commands to block until the player has moved.
  # To disable, set to: Block_Commands_Until_Moved: '[]'
  Block_Commands_Until_Moved:
    - /afk
    - /me
    - /list
```
This config enables a player to chat and only the given commands are blocked.
Test:
Player joins and executes /list
The following message appears: `! You cannot chat until you move!`
This message belongs to the line `Cannot.Chat_Until_Moved: '&8&l! &7You cannot chat until you move!'`

Can this be fixed by showing the message `Cannot.Command_Until_Moved: '&8&l! &7You cannot use this command until you move!'` ?

Thank you in advance

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting. It's now fixed. Please wait until the new ChatControl gets released.

Thanks again!
Ladislav
