### ISSUE TITLE
Chatcontrol error when I remove {dynamicline}

### ISSUE THREAD

**Issue by TastyBlueberry** [kangarko/ChatControl-Pro#1562]
I get an error when I receive {dynamicLine} from messages_en.yml.

Part of the config (still with {dynamicLine}, but when i remove {dynamicLine} it gives an error) (messages_en.yml):
Announcer:
  _Message: |-
           &8*___________________________________________________*
           &f
                           &7. . . &6&lA N N O U N C E M E N T &7. . .
           &8*___________________________________________________*
           &f
           &f {message}**{dynamicLine}**
           &8*___________________________________________________*
  
  Console_Message: '&f[Announcement by &b{player}&f]: &7{message}'
  Self_Message: '&7Announcement sent.'_

----------------------------

Error when I remove {dynamicLine} from that part of the config:
_12.02 09:21:16 [Server] INFO ChatControl 8.5.4 encountered an ArrayIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file.
12.02 09:21:16 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 1
12.02 09:21:16 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .short.const(SourceFile:215)
12.02 09:21:16 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:322)
12.02 09:21:16 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
12.02 09:21:16 [Server] INFO at java.lang.Thread.run(Thread.java:748)
12.02 09:21:16 [Server] INFO !-----------------------------------------------------!
12.02 09:21:16 [Server] INFO Failed to execute command /chc announce t
12.02 09:21:16 [Server] INFO !-----------------------------------------------------!_

**Comment by lackoSK** [comment]
Hello,

Can you please provide us your configuration files (ZIP ChatControl's folder)

Thanks!
lackoSK

**Comment by lackoSK** [comment]
Hi,

You are also running outdated ChatControl: 8.5.4  - update to the newest version.

If that doesn't fix your issue, comment under this issue/open another one.

Regards,
lackoSK
