### ISSUE TITLE
JavaScript variables won't function.

### ISSUE THREAD

**Issue by devonzimmi** [kangarko/ChatControl-Pro#1563]
https://pastebin.com/P2xYtzAp

I am trying to create my own javascript variable but I get the error above.
This is the variable I am trying to create.

`define {customprefix+}`
`script:`
`  getTagOrPrefix();`

`  function getTagOrPrefix() {`
`      var tag = "{deluxetags_tag}";`
`      return tag == "" ? "{luckperms_prefix} " : "{luckperms_prefix} " + tag;`
 ` }`

I'm a bit confused because I definitely have an updated version of Java.
![image](https://user-images.githubusercontent.com/22530000/74383171-54c6fb00-4db4-11ea-9b1b-f084f64b4414.png)

Can you help me?

**Comment by lackoSK** [comment]
Hello,

JS placeholders are not currently working, because of issue #1531 

Hope you understand.

Regards,
lackoSK

**Comment by lackoSK** [comment]
Okay,

We've released version 8.6.3, which should fix this issue.

If the issue continues for you, feel free to message under it, and we will re-open it. 

PS: Thank you for reporting it ^^ 

Best,
lackoSK
