### ISSUE TITLE
'none' occasionally appears before playername

### ISSUE THREAD

**Issue by OGreenC** [kangarko/ChatControl-Pro#1564]
When I type a playername in the chat, there's an occasional 'none' that appears in front of the playername.
(see picture below)
https://gyazo.com/514e0a2c6f84ac02467fa41f1f170ec8

We've come to the conclusion, that the first time we type the name after a server restart, it happens. From here, we don't really see a clear pattern.

We've tried to spam playernames - It only happens once in a while (once every 7'th message or so)
Do you have any idea what could cause this?

**Comment by lackoSK** [comment]
Hello,

Can you please provide us your ChatControl's folder (Zip it)

Thanks!
lackoSK

**Comment by OGreenC** [comment]
Sure,

The folder is attatched below

Thanks in advance!
- OGreenC
#
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4208565/ChatControl.zip)

**Comment by lackoSK** [comment]
Does it happen also when you disable Sound_Notify ?

**Comment by OGreenC** [comment]
It seems to fix it, when I Disable Sound-Notify.

Thank you!

**Comment by lackoSK** [comment]
Awesome!
