### ISSUE TITLE
Recursive spam

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#1565]
My config:
https://github.com/kangarko/ChatControl-Pro/files/4030578/chc.zip
version: 8.4.13

Problem:
https://hastebin.com/vemucufowu.nginx
No matter what Anti Spam Chat values I set in settings.yml players can spam this way in public chat.
1st message: one two three
2nd message: one two three one two three
3rd message: one two three one two three one two three
and so on...
How do I stop it?

**Comment by lackoSK** [comment]
Hello,

You can use "Join_Flood" section in settings.yml

Regards,
lackoSK

**Comment by AngelDeaD** [comment]
It does not help me:
https://i.imgur.com/sbEJp6Q.png
Does it work in bungee network on gameplay server or only in single server situation?

config:
`# If within a given time interval there's more than specified amount of players
  # who joined, and at least X amount of their last messages is equal, you can
  # run specific commands to ban/kick/mute them.
  #
  # Useful to prevent bots who mass-join and spam the same messages.
  Join_Flood:

    # Enable this feature?
    Enabled: true

    # What is the amount of time we monitor for last joins?
    Join_Threshold: 300 seconds

    # How many players must join within the interval above for the commands below to run?
    Min_Players: 2

    # How many players of those above must sent the same message to the chat?
    Min_Equal_Messages: 3

    # If all three conditions above match, run the following commands. Replace {player} with your player name.
    Commands:
      - "/kick {player} &4Spam"`

**Comment by AngelDeaD** [comment]
@lackoSK you there?

**Comment by lackoSK** [comment]
Sorry, missed out your message. Please update to the latest version.

**Comment by AngelDeaD** [comment]
I'd say this needs to be better
https://i.imgur.com/ZFy1ddz.png

I set ``` Min_Equal_Messages:``` to 2, it should not block 6th message, it should block 3rd.

**Comment by lackoSK** [comment]
Join flood is about when many players are joining & sending the same messages -> we block them. (Bot attack)

**Comment by AngelDeaD** [comment]
Thank you for join flood option, I really needed it, but I also need to stop spam from one user. As shown in screen shots

**Comment by lackoSK** [comment]
Then, you can use Anti_Spam section in settings.yml

![image](https://user-images.githubusercontent.com/53174757/75690351-f8fcdd00-5ca2-11ea-92fc-4a03ab7b1d4e.png)

**Comment by AngelDeaD** [comment]
console + game: https://i.imgur.com/cz89seX.png
config: https://i.imgur.com/2kxoslA.png

2nd attempt:
https://i.imgur.com/l6a04Up.png
https://i.imgur.com/rNhLtUp.png

Is there only way to stop this kind of spam, by limiting messages per seconds ?

**Comment by lackoSK** [comment]
![image](https://user-images.githubusercontent.com/53174757/76002903-90fb0080-5f07-11ea-80ba-54fec83ea46d.png)

You can find it in settings.yml under Anti_Spam section

**Comment by AngelDeaD** [comment]
Is that **only** way to block this kind of spam?
Why I can not block this with similarity check ?

**Comment by lackoSK** [comment]
You can also use similarity check

**Comment by AngelDeaD** [comment]
What values should I change? I left my config in first post.

**Comment by lackoSK** [comment]
**Similar_Percentage_Block: 80**
Similarity_Message_Check_Count: 3

**Comment by AngelDeaD** [comment]
console + chat: https://i.imgur.com/fEjCrWq.png
config: https://hastebin.com/nicubaxelo.coffeescript

I guess you are talking about `Chat:`

**Comment by lackoSK** [comment]
yes

  Chat:
    Message_Delay: 1
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 3 - {delay}
    **Similar_Percentage_Block**: 80
    Similarity_Message_Check_Count: 2
    Similarity_Points:
      Warn_Set: spam
      Amount: 4 * ({similarityPercentage} / 2)

**Comment by AngelDeaD** [comment]
@lackoSK if you checked my previous message, you would see that I already have it in my config.
It does not work. I have played with it before starting this issue and you can see it in my previous message.

**Comment by lackoSK** [comment]
Please zip me again your current ChatControl folder

**Comment by lackoSK** [comment]
and also update to the latest version

**Comment by AngelDeaD** [comment]
console + chat: https://i.imgur.com/52KirUJ.png

ChatControl folder: [chc.zip](https://github.com/kangarko/ChatControl-Pro/files/4348015/chc.zip)
Sorry I had to remove logs files and rules.txt due to privacy

**Comment by lackoSK** [comment]
Can you try to move up Similarity_Message_Check_Count: 2 

Maybe give it value like 5

**Comment by AngelDeaD** [comment]
I raised it to 5, but it's same:
https://i.imgur.com/57AHt6Y.png

**Comment by lackoSK** [comment]
Can you talk to me on discord? lackoSK#0001
