### ISSUE TITLE
Missing Permission & Chat Color affecting commands

### ISSUE THREAD

**Issue by Neeonn** [kangarko/ChatControl-Pro#1566]
Chat Color affects plugins in different ways, UltraCustomizer for example when trying to create a command, and commands such as staffchat when you try to use a shortcut from chatcontrol (@text).

What is the permission for the admin-chat shortcut (@text)?

**Comment by lackoSK** [comment]
Hi,

It should be able to find permissions here:
https://github.com/kangarko/ChatControl-Pro/wiki/Permissions

Regards,
lackoSK

**Comment by Neeonn** [comment]
It should, but there isn't any for what I'm asking.

**Comment by lackoSK** [comment]
I think the perm is the same as for writing to it. Can you give it a try?
