### ISSUE TITLE
Question: Is it possible to mute the messages sent to the server from the DiscordSRV-linked channel during a global server-chat mute?

### ISSUE THREAD

**Issue by B-Knight49** [kangarko/ChatControl-Pro#1567]
I had to mute the server chat the other day but some particularly stubborn users resorted to messaging each other and the server chat by writing into Discord (which gets sent to the server-chat in-game). Is there a way I can prevent those messages being sent through to Minecraft during a global-chat mute?

**Comment by lackoSK** [comment]
Hello,

So am I right? 
When you muted the chat the messages were sent to discord? 

Best,
lackoSK

**Comment by B-Knight49** [comment]
Nah, people could message the discord channel called #server-chat and that then comes through into the Minecraft server and thus the Minecraft server chat.

**Comment by lackoSK** [comment]
Hi, 

I've fixed it, will be released soon.

Thanks!

Kind thanks, 
lackoSK | Mineacademy
