### ISSUE TITLE
Chat listener problems

### ISSUE THREAD

**Issue by Darkweasam** [kangarko/ChatControl-Pro#1569]
Listener_Priority:
Checker: LOWEST
Formatter: LOWEST
Signs: LOWEST

There is this plugin called PlayerShops, an addon to the good, well known BossShopPro
https://www.spigotmc.org/resources/playershops-gui-bsp-allow-players-to-create-public-shops.29568/

Issue:

Whenever I add an item to my shop, ("please input your price of this item in chat" method), the number is displayed in the global chat
The issue is also here when I use other plugins that requires me to enter something into the chat, it just simply stays visible for everyone

Please help, I kinda hate this priority thing in this plugin since I bought it

I dont use chat channels, there is a single global chat and thats all. I am using a standalone server.
I always use the latest version of chatcontrol PRO 8.6.1

**Comment by Darkweasam** [comment]
https://pastebin.com/FunUfZaP

MONITOR

**Comment by lackoSK** [comment]
Hello,

You should have a bigger priority for Formatter (higher than the others)

Best,
lackoSK

**Comment by Darkweasam** [comment]
Tried with 
Listener_Priority:
  Checker: NORMAL
  Formatter: HIGH
  Signs: NORMAL

Doesnt help

**Comment by lackoSK** [comment]
Can you try to message the author to fix the compatibility, this doesn't seem like a ChatControl's issue.

**Comment by HexedHero** [comment]
Not a ChatControl issue at all also works fine for me but I am using a custom version of BSP.

**Comment by Darkweasam** [comment]
@HexedHero Its not BSP itself but it's addon called "PlayerShops"
