### ISSUE TITLE
Player tag color issue

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#157]
Hey,

When I use @<playername> sometimes it turns green, most of the times it stays white. I typ the correct playername however and I have OP. When players try to tag eachother, the same issue appears. Could you make it so a tag always turns green no matter what?

ChatControl Pro: 7.1.5

**Comment by kangarko** [comment]
I will test it out soon, I though the latest version had it fixed, I am sorry.

**Comment by kangarko** [comment]
Please post me your settings.yml :)

**Comment by kangarko** [comment]
I have identified a flaw in static chat formatter and resolved it. 

Btw, ChatControl does not identify the color in player's suffix. That said, if you assert a color to the player's suffix, the message after the player's name is mentioned is turned to white. This is because we only lookup for the last color in the chat message itself, not the formatting (currently without my scope).

**Comment by kangarko** [comment]
Hey, please test out the latest version.

**Comment by Sikatsu** [comment]
I'm not sure if I use the static chat formatter, i'm using hover events and such?

I see, well for example when I do @animalnl it turns green and when I do @king_freakert it turns white.

I will test the new version tomorrow.

**Comment by Sikatsu** [comment]
Still white: http://prntscr.com/eaht8h

**Comment by kangarko** [comment]
Could not reproduce. Some rules to keep in mind:
1) You cannot tag yourself.
2) Check which conditions (delay, afk) you have set in the Sound_Notify section.

Please post me the entire **Sound_Notify** section from settings.yml

**Comment by Sikatsu** [comment]
I didn't tag myself. I tagged Masky078 and his name stayed white, when he tagged me it turned green. This is also random for players, for freakert it stayed white, for animal it stayed green for example.

`Sound_Notify:
  Enabled: true
  Notify_Only_When_Afk: false
  Notify_Only_If_Prefixed_With: '@'
  Sound: ENTITY_EGG_THROW, 1F, 1.5F
  Enabled_In_Commands:
  - me
  - msg
  - m
  - tell
  - t
  - reply
  - r
  - mail
  - pm
  - w
  - whisper
  Cooldown_Seconds: 10
  Color: '&a'`

**Comment by kangarko** [comment]
I see. Just to remind you, you have Cooldown_Seconds to 10 seconds, That said, you have to wait 10 seconds before you can use the function again. Try to setting it to 0 and test again, just for the reference.

**Comment by Sikatsu** [comment]
When I tested, atleast minutes where in between. So I don't think this is the case, but I will change the cooldown anyway.

**Comment by Sikatsu** [comment]
This still occurs by the way. Seem not to be able to tag all players succesfully.

**Comment by kangarko** [comment]
Apologies for the delay. I think I have resolved the issue. Please test 7.2.3.

**Comment by SilberRegen** [comment]
It's still an issue in 7.2.3
I find that the colouration only works, when the name is typed without capitalization. With tab-complete it won't work either (all tested names included capitals).
The acoustic signal works fine though.

**Comment by kangarko** [comment]
Hey @SilberRegen,

It works fine on capitalized nicknames for me, included when I use tab-complete to fill the rest of the username. Since I have anti-caps enabled, I receive a CAPS warning and the username gets capitalized, but everything works (both the color and sound).
![pic](https://i.imgur.com/hXVWbTM.jpg)

Please post me your settings.yml and chat.yml.

**Comment by kangarko** [comment]
@Sikatsu, I have checked many things I could think of, but I have not come up with something I can advice you directly as a quick fix. Here are some things I have come up with:
* Check your permissions. When you tag a player and it's white, do you have operator status? Which permissions related to chatcontrol do you have?
* Make sure you and your players have chatcontrol.notify.whenmentioned permission.
* Are you testing over bungee? Sound notify only works within the bukkit server

**Comment by Sikatsu** [comment]
Hey @kangarko 

Thanks for taking a look at the problem.

> Check your permissions. When you tag a player and it's white, do you have operator status? Which permissions related to chatcontrol do you have?

I have operator and as @SilberRegen already said, it might be an capitalization issue.

His minecraft name is King_Freakert, yet only @king_freakert makes it give a color.

> Make sure you and your players have chatcontrol.notify.whenmentioned permission.

As I have operator, I do have that permission. Player ranks don't have ANY permission, however. Do they need that to be tagged? Would be weird as some players can be tagged succesfully.

> Are you testing over bungee? Sound notify only works within the bukkit server
I'm just using spigot, no bungee.

**Comment by SilberRegen** [comment]
![chatcolor](https://cloud.githubusercontent.com/assets/3227532/23994409/2799a1e2-0a45-11e7-9acf-d802d8513f1f.png)

Settings: http://pastebin.com/fWJkBwJA
Chat: http://pastebin.com/TvvrJGip

Everybody has the notify-perm, nobody has op.

**Comment by animalnl** [comment]
Please untag me from this mail my name is animalnl. Thank YouTube.

Op 16 mrt. 2017 12:40 schreef "SilberRegen" <notifications@github.com>:

**Comment by SilberRegen** [comment]
@Sikatsu mentioned you, animalnl. 
He might have to edit his post.

**Comment by kangarko** [comment]
All inconsistencies solved in 7.2.4. I made mistakes when I was testing it, I am sorry that it took long time to fix. We learn something new every day :)

**Comment by SilberRegen** [comment]
It does colour the names now everytime, which is nice.
But I already got some complains from players, because their names are now all lowercase, even if typed in correctly.
E.g. my username ist "SilberRegen" but it will always come out as "silberregen".
Personally I don't care how other people write my name, but I can relate to the player who are annoyed by this. The only people who can type out the names correctly now, are the players themselves, as they cannot tag themselves.

**Comment by kangarko** [comment]
@SilberRegen thank you for reporting, I have fixed it! A new release will be available tonight.

**Comment by Sikatsu** [comment]
@kangarko Is there actually anyway to also make it work for usernames from Essentials?

**Comment by kangarko** [comment]
Not at the moment. Only player names can be found with the current system.
