### ISSUE TITLE
Console keep sending errors

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1570]
PaperSpigot 1.15.2
and the console keep sending same errors, it really bothers me.

Error: https://pastebin.com/mDw9VMSZ

Config
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4209315/ChatControl.zip)

**Comment by lackoSK** [comment]
Hi,

Can you tell me, when exactly it happens to you? 

Regards,
lackoSK
