### ISSUE TITLE
chatcontrol.bypass.togglepm not working?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1571]
I gave this permission to my staffmembers, but they can't message anyone with PM's disabled.

Looks like a bug?

**Comment by lackoSK** [comment]
Hi,

This should bypass the guy who sent the message to someone, who has toggled his PMs.

Feel free to send us your ChatControl folder.

Best,
lackoSK

**Comment by Sikatsu** [comment]
Yeah, I want staff to be able to message someone who has their PM toggled off.

My chatcontrol folder has been shared on other issues like the bungee debug one. I'm on my phone right now.

**Comment by lackoSK** [comment]
Feel free to send it again.

**Comment by kangarko** [comment]
System broken on bungee only, we fixed that to the next version :)
