### ISSUE TITLE
Startup debug

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1572]
Hey, could you remove this startup debug?
Don't think it's needed to show this on every startup.

https://pastebin.com/pQuJ0HU0

**Comment by lackoSK** [comment]
Hello,

![image](https://user-images.githubusercontent.com/53174757/74764259-ae7e6800-5281-11ea-83bf-82c181ba46e1.png)

You can use this section in settings.yml

Regards,
lackoSK
