### ISSUE TITLE
Hidden Format ?

### ISSUE THREAD

**Issue by Phamous1** [kangarko/ChatControl-Pro#1574]
So i am attempting to remove Essentials, which means i enabled chatcontrol formatting for my chat.  But it is giving me a &f &o value for my player names which is overriding my luckperms prefix permissions i have set up for the player names.  I have gone through the config and i dont see where it is coming from.  Any Ideas ?

https://pastebin.com/Rkdm6bGG

this is the test servers readout §f§f§7§l{§b§lO§3§lW§8§lN§b§lE§3§lR§7§l}§4§o §f§f§oPhamous1§7: §f§f§ftest
so somewhere in chat control it is inserting the §f§f§o which is overriding my luckperms
i have been through every config on chat control and i do not see it, i even did a ctrl+f looking for &f&f&o and &f on every one and nothing.  So where is it coming from lol, no other plugin that handles chat on my server.

**Comment by lackoSK** [comment]
I think we have talked over the discord so that I will close it here. You can contact me on discord again.
