### ISSUE TITLE
Problem with /r 

### ISSUE THREAD

**Issue by GienoX** [kangarko/ChatControl-Pro#1575]
ChatControlPro: 8.6.4
Paperspigot: 629
server: 1.13.2
Plugins on server: AAC, AdvancedPortals, AuthMe, BetterEnderChest, BlueShop, ChatControl, Citizens, CrateReloaded, CustomDrops, Essentials, EssentialsSpawn, FairNaturalSpawns, FastLogin, GriefPrevention, GXCzek, GXHome, GXNotes, GXNullTickBlocker, HeadDatabase*, HolographicDisplays, IllegalStack, KillerMoney*, LiteBans, LuckPerms, MobFarmManager, MoreFish, MyCommand, MysqlEconomyBank, OldCombatMechanics, OpenInv, OreAnnouncer, PremiumVanish, ProtocolLib, PvPManager, RandomCoordinates, Shopkeepers, SkinsRestorer, TitleManager*, TreasureChestReloaded, Vault, WorldBorder*, WorldEdit, WorldGuard, WorldGuardExtraFlags

Hi i have problem with /r /tell commands.. If on server play more then 10 players, /r writes to a random person

**Comment by lackoSK** [comment]
Please provide us you ChatControl folder

**Comment by GienoX** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4226255/ChatControl.zip)

**Comment by lackoSK** [comment]
This issue was fixed in version 8.6.4

Can you give it a try? 

If it doesn't work, please, comment under this issue/open new. 

Thanks!

**Comment by GienoX** [comment]
but i use version 8.6.4

**Comment by lackoSK** [comment]
Hello,

We were doing testing with 13 Minecraft accounts messaging between them selfs.
We have used the 1.13.2 paper spigot.

However, we could not confirm this issue.

![](https://cdn.discordapp.com/attachments/651368918275063810/680474051093069853/unknown.png)

![](https://cdn.discordapp.com/attachments/651368918275063810/680474051093069853/unknown.png)

PS: Are you running more than one server instance (bungeecord)?

Best,
Ladislav from Mineacademy

**Comment by lackoSK** [comment]
![](https://cdn.discordapp.com/attachments/651368918275063810/680474079475925041/unknown.png)

**Comment by GienoX** [comment]
yes server is on bungeecord

**Comment by lackoSK** [comment]
The only logical problem can be this:
You have some servers online and some in offline mode and UUID for them is different

**Comment by GienoX** [comment]
can we tallk on discord next day?

**Comment by lackoSK** [comment]
Yah, of course: lackoSK#0001

**Comment by kangarko** [comment]
@GienoX please test the next version coming up tonight, where you need to put ["pm", "bungee"] to your Debug key in settings.yml, and post us the console output when it happens again
