### ISSUE TITLE
All Player Data Clearing on Startup

### ISSUE THREAD

**Issue by delbertina** [kangarko/ChatControl-Pro#1576]
Server: Paper 1.15.2 build 118 (Latest)
ChatControl Pro: 8.6.4

Relevant Config Section
`Clear_Data_If_Inactive: 30 days` (Default)

Top of Config After Updating
```
#  Your file has been automatically updated at 22.02.2020 19:26:21
#  to ChatControl 8.6.4
```

Updated from 8.4.9 to 8.6.4 when updating to 1.15.2 and noticed that the startup log included many lines of `Removing data for [playername]` then at the end it said `Cleared data.db of ### inactive players` . Looked at the list and noticed that the list included players that were on that day before the update. Now, every time the server starts up it clears all the data from the players who logged since the last restart. I'm not too sure what data it is deleting because players still have their points for like spam etc.

**Comment by lackoSK** [comment]
Hello,

Yes, we do clear some data to improve the performance of the plugin. 

Can you provide us your folder **before restart**?

Thanks.

**Comment by delbertina** [comment]
[CCUpdateData.zip](https://github.com/kangarko/ChatControl-Pro/files/4247395/CCUpdateData.zip)
Here's the database file before and after updating.

**Comment by lackoSK** [comment]
Hello,

I didn't request the only the database. I need your whole ChatControl folder.

**Comment by delbertina** [comment]
Sorry, here's the whole folder zipped up.
Before
[ChatControl-20200222.zip](https://github.com/kangarko/ChatControl-Pro/files/4258990/ChatControl-20200222.zip)

After (A few days later)
[ChatControl-20200226.zip](https://github.com/kangarko/ChatControl-Pro/files/4258964/ChatControl-20200226.zip)

**Comment by lackoSK** [comment]
Apologies for the late respond (Am on vacation)

I think it seems okay. We are removing unnecessary data like "last join" and these. If you are not familiar with it. You can disable it in settings.yml 

Thanks!

**Comment by delbertina** [comment]
Do you know which setting turns that off? I can't seem to figure out which one it would be.

**Comment by lackoSK** [comment]
![image](https://user-images.githubusercontent.com/53174757/76002698-4bd6ce80-5f07-11ea-91c8-ba967e37c6ad.png)

You can find it in settings.yml

**Comment by delbertina** [comment]
Oh sorry, I was meaning the thing that clears data on startup from players who were on since the last restart.

**Comment by lackoSK** [comment]
No. Of course not lol.

Thank you!
I will close it here.
