### ISSUE TITLE
Is this ChatControl blocking the book? I cant find this error message in the messages file

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1577]
Im trying to figure out what plugin is blocking a book for a player, is this a chat control error message? I scanned all plugin files for these words but cant find it anywhere, which means the error message is hard coded.

![is this chat control](https://user-images.githubusercontent.com/144046/75237917-208e0a00-57b8-11ea-8701-b86dbfc6577a.png)

**Comment by lackoSK** [comment]
Hi,

I could not find it in code too. (Had a quick look)

I am not so sure but to test it you can do:
1) Set debug to "rules_books" in settings.yml
2) Disable it inside config: 
![image](https://user-images.githubusercontent.com/53174757/75271816-1e01d380-57fd-11ea-89a9-51f2acd598f3.png)

If you can confirm, it's coming out of ChatControl I will find it add translation message.

Regards,
lackoSK

**Comment by FrozenBeard** [comment]
I just noticed the "Please do not advertise other websites or IP adresses." Is inside handlers.yml I 100% know its ChatControl as you have spelt "adresses" wrong, it's addresses.
But for the "Book was blocked" I cant find that text in ChatControl at all, i'm wondering if its another plugin thats also triggering it, not entirely sure its why im asking.

**Comment by lackoSK** [comment]
Can't you test just ChatControl on your server?

**Comment by FrozenBeard** [comment]
> 
> 
> Can't you test just ChatControl on your server?

No its a production server.

**Comment by lackoSK** [comment]
> I just noticed the "Please do not advertise other websites or IP adresses." Is inside handlers.yml I 100% know its ChatControl as you have spelt "adresses" wrong, it's addresses.

I have fixed it, thanks.

Also... found it!
![image](https://user-images.githubusercontent.com/53174757/75689871-39a82680-5ca2-11ea-9f38-53b7be052307.png)
