### ISSUE TITLE
Hilfe...

### ISSUE THREAD

**Issue by T4iKoN** [kangarko/ChatControl-Pro#1578]
Ich habe Chat Control auf meinen Server sowie auch LuckyPerms aber die Prefix werden nicht angezeigt. wieso???

**Comment by lackoSK** [comment]
Hello,

The support is only given in English. I have contacted my teammate, which is german, so he will help you if you can't speak English. 

Can you provide us your ChatControl folder? 

Thanks!

**Comment by JavaFactoryDev** [comment]
Hallo T4iKoN,

Meines Wissens nach wird LuckPerms nativ unterstützt.
Für sowas musst du im Normalfall einfach nur mit dem ListenerPriorities rumspielen.

Wenn du etwas im Wiki ließst, solltest du das schon schaffen.
Ist eigentlich ganz einfach.

Schau einfach mal hier: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

Da ich nicht für ChatControlPro zuständig bin, kenne ich mich damit nicht so gut aus.

**Comment by JavaFactoryDev** [comment]
Wenn du weitere Fragen hast, kannst du diese natürlich hier stellen.

Btw. Eigentlich wäre es sehr hilfreich, wenn du auf Englisch schreiben könntest^^
