### ISSUE TITLE
Getting essentials ignore override console spam on player join

### ISSUE THREAD

**Issue by KarlOfDuty** [kangarko/ChatControl-Pro#1579]
![image](https://user-images.githubusercontent.com/18099825/75580141-85bb5700-5a67-11ea-8ab8-08e77cf33166.png)

Basically the above issue. It happens pretty frequently when players join. We don't have any debug settings on and it doesn't seem to go away after chatcontrol tries to override it for the player.

**Comment by lackoSK** [comment]
I am not sure where this issue comes from. Can you test it without Essentials?

**Comment by KarlOfDuty** [comment]
We don't really have a test server set up with any player data on it and we can't really remove essentials form the main servers either. Are you saying this comes from essentials? I could open an issue with them in that case.

**Comment by lackoSK** [comment]
Hello,

I have fixed this, it will not appear again. Please, wait until the next version released. 

Thanks!

**Comment by KarlOfDuty** [comment]
Nice, thanks!
