### ISSUE TITLE
/btlp fake add <name>  Is broken

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#158]
/btlp fake add <name>
Does not work at all. Ingame, you get a message saying that you don't have permission. On console, the command isn't even identified.
I'm reporting this because this command is displayed on the wiki documentation.

CC v 1.7.6
Spigot for MC: 1.11.2

**Comment by kangarko** [comment]
This command is not included in ChatControl. Please link exactly to the wiki documentation.
