### ISSUE TITLE
Command to mute the chat for a specific player

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1583]
Hello!
I want to be able to mute the chat via command for a specific player at a specific time, the idea being when a user enters a tutorial their chat isnt being spammed with users that are playing!
This lets you run custom commands:
https://www.spigotmc.org/resources/server-tutorial-plus.37741/

There has to be a way to temporarily mute the Chat from a player thats in a tutorial so that their chat can be dedicated just to the tutorial while they are in it.

Also needs a fail-safe, so if the logout during the period when they log back in, its reset back to normal so they are not stuck without chat, as then they cant even ask for help!

I *think* there is a permission to deny reading/writing in chat, so the only thing I can think of at present is to set this permission to the user temporarily on a timer, which is a bit sketchy way of doing it.

**Comment by lackoSK** [comment]
Hi, 

I don't agree to do this because I don't think this is that much "chat-related" stuff; also, ChatControl is **not** permissions/management plugin.

Yes, there is permission "chatcontrol.chat.read"

Mostly, I **really** like your idea, but I don't like/(agree on with) this one.

Best,
Ladislav

**Comment by FrozenBeard** [comment]
What? there is already a /chc mute, im asking for a parameter to make it player specific.

**Comment by lackoSK** [comment]
Ah, now I get it. Then, yes sure. I can defo add this. (Am on vacation, so will take some time) 

Adding this to TODO.

Sorry for the misunderstanding & Thanks!

**Comment by lackoSK** [comment]
Do you want it with a specific time snap? (the mute like /chc mute .player 30min)

**Comment by FrozenBeard** [comment]
Please, if its also an option it will be very handy. so on/off and also timer.

**Comment by FrozenBeard** [comment]
@kangarko please reopen this request for 8.x series.

**Comment by kangarko** [comment]
Will be pulled into V9 again soon. V8 is on being serviced right now.

**Comment by FrozenBeard** [comment]
I wont be using V9 if its flawed, I just want to have this in the stable version that will be updated in the future.
