### ISSUE TITLE
Infinite loop MySQL

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl-Pro#1584]
Hello,

Since few updates now, i'm having an issue with chatcontrol. It's randomly creating an infinite loop in the database, who make the server crashing. 

Crash report: https://paste.soleria.eu/ofahivedil.md

It's not the first time it happend :/ not rly sure why...

**Comment by lackoSK** [comment]
Hi,

This is not ChatControl. It told you "Please report this to PaperSpigot directly!"

If so, you can set "debug" in settings.yml to ["mysql"] to see what's going on. 

PS: Comment under this issue if it will continue.

Regards,
lackoSK
