### ISSUE TITLE
Question pre purchase

### ISSUE THREAD

**Issue by mellowism** [kangarko/ChatControl-Pro#1586]
Hi, 

Sorry if this is the wrong place but honestly I couldn't understand where to post pre purchase questions.

I am thinking about moving from Venturechat to Chatcontrol Pro. One thing Venturechat does well is channels. However one feature I'm lacking is to easy see what channel you are currently chatting in, and an easy way to change channels without command. 

Is it possible to change channel by clicking the channel name from another users chat with this plugin? Or a similar method which changes channel?

Thanks in advance.

**Comment by lackoSK** [comment]
Hello,

Nope, that's not possible. But it's a good idea. 

> I'm lacking is to easy see what channel you are currently chatting in

What do you mean? You can set a different formats for each channel. Like (GLOBAL) PLAYER: MESSAGE

**Comment by mellowism** [comment]
Yea, but the problem is in Minecraft I believe. I'm talking about when you press "t", and start chatting, there is no easy way to see where that message is going to end up in what channel before you press enter. There's no indication of what channel you're currently in.
I switch channel between local, global, staff etc. all the time. So may times I've said something in staff that was meant for global and vice versa :). 
If pressing the channel name from another persons chat was an option, I would use that all the time to switch between channels.

**Comment by lackoSK** [comment]
Nope. That is not possible. Sorry

**Comment by mellowism** [comment]
Is the option to be able to click the channel name to change channel something you could consider adding?

**Comment by lackoSK** [comment]
Like if you have read permission. Maybe hover message in other channel and if clicked on, join him to channel?

**Comment by mellowism** [comment]
Yea, but just able to add a command and the command could be to join channel, or other commands if you want that.

**Comment by mellowism** [comment]
I just wanted to add here that I bought ChatControl Pro today. I think I explained what I was after pretty bad and you misunderstood me because the formatting options has what I am after. So I am happy :) Thanks for a great plugin and keep up the good job! :)

**Comment by lackoSK** [comment]
I mean it's not a bad idea. But with the current system - impossible. However, we might implement this after recoding of ChatControl
