### ISSUE TITLE
Minecraft server version 1.15.2 - How to enable /chc color for everyone by default

### ISSUE THREAD

**Issue by Parsly** [kangarko/ChatControl-Pro#1587]
Hello.
Is there a way to enable /chc color for all users by default? 
I do not wish to use a permission system, I only use essentials. 

I would like to allow every player to access /chc color (GUI) without using a permission system.

Thank you.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4301386/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

You can not enable color by default, but you can set formatting to white for example and each user which didn't set any color in the GUI, will write white.

Does this solve your problem?

**Comment by Parsly** [comment]
Hello,

Thank you for getting back to me so soon. No this doesn't solve the problem unfortunately as I already have default formatting set to white. I Just wanted default users to be able to open the color GUI, without using a permission plugin.

Thank you
Natalie

________________________________

**Comment by lackoSK** [comment]
Ah okay. We can add such a feature.

**Comment by lackoSK** [comment]
Added within next update.
