### ISSUE TITLE
Using the client setting "Show commands only" in the client doesn't filter out normal chat in 1.15

### ISSUE THREAD

**Issue by KarlOfDuty** [kangarko/ChatControl-Pro#1588]
Hello, we recently went from 1.13 to 1.15 and it seems that minecraft clients now see all chat as command feedback. Some of our players like to filter out chat and just want to see their command feedback so this is an issue for them. Not really sure if this is something that can be fixed as it seems to be an issue with minecraft 1.15.

Here is the original issue reported: https://github.com/EarthMC/Issue-Tracker/issues/981

**Comment by lackoSK** [comment]
Hello,

Yes, that's Minecraft's issue. We can not modify this. 

Hope you understand.

Anyways, thanks for reporting it.

Best
Ladislav
