### ISSUE TITLE
1.12.2 - Error when merging items using an anvil

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl-Pro#1589]
Hi!

Recently, I tried to merge two items using and anvil, and I had [this error](https://hastebin.com/corilekexi.apache) shown in the console.

Here's the plugin folder
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4302360/ChatControl.zip)

**Comment by lackoSK** [comment]
Weird. It happened to you when you put item1 + item2 together in an anvil?

**Comment by ElBananaa** [comment]
> Weird. It happened to you when you put item1 + item2 together in an anvil?

When I merge Item1 + item2 using an anvil yes.

**Comment by lackoSK** [comment]
I am not able to reproduce the issue. Is it happening constantly or it happened only once?

**Comment by ElBananaa** [comment]
Hey! I don't know how, but it looks like the issue has been fixed ^^
Sorry for the inconvenience,
Have a nice day.

**Comment by ElBananaa** [comment]
Hi! I finally found what is causing the issue.
Soo, the infinite anvil system of [this plugin](https://songoda.com/marketplace/product/ultimaterepairing-repair-items-on-an-anvil-at-a-cost.20) is the cause of the issue. I contacted its author to report the issue, and I do same here. I don't know if you can do something about that, but I still report this error so you know it exists.
Have a nice day.

**Comment by lackoSK** [comment]
Cool.
