### ISSUE TITLE
Show {killer_item} with formatting in death messages

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#159]
I have been trying out the custom death messages in ChatControlPro and they are awesome!  I have a few feature requests, but for now I'll just start with the easiest.

Can we please get an update to show the item name, including formatting codes, of {killer_item}?  Right now players who give their weapons custom names aren't seeing those names in chat, it will just say, for example "Diamond Sword."  This was a feature in BattleTracker v2, which has been abandoned, and I'd love to see that feature added to ChatControlPro.

**Comment by kangarko** [comment]
Hello, thank you for your feedback. I have added it to the roadmap. At the very present, there are other features that take priority.

**Comment by Sikatsu** [comment]
Would love to see this aswell.

**Comment by kangarko** [comment]
As per the next version,

the items that have custom metadata with a custom name will show their custom name instead of their material name.
