### ISSUE TITLE
Cannot send message 

### ISSUE THREAD

**Issue by NovaPixell** [kangarko/ChatControl-Pro#1592]
Hi I am writing to report a problem. On the server where I work it often happens that some random player, every now and then, has the problem that he is unable to write in chat. When he tries to write he gets the error "Cannot send message". This problem occurs for some time and then goes away on its own. I wanted to report it because it is not very normal, as I do not check for errors in the console or in the "error.log" file of the plugin.

(sorry for the bad english but I used the translator: D)

**Comment by lackoSK** [comment]
Please send us your permissions config, and zip your ChatControl folder (send it too)

Thanks
