### ISSUE TITLE
1.15.2: Questions about chat channels; too big for title

### ISSUE THREAD

**Issue by Noxillio** [kangarko/ChatControl-Pro#1593]
I'm having some complications with ChatControl and I'd like some answers that could help me put together what I'm trying to do.

We have 3 channels. Standard, for everyone to talk in; staff, for staff to talk in; admin, for admin.

When I join as an admin I would like to be able to read all channels, but when I send messages I only want them to send in standard unless I manually switch to the other channels myself or use the send command. However, when opped and with * permission, it sends messages in all channels. I don't want that.

How can I go about fixing this?

**Comment by lackoSK** [comment]
I told you solution on discord
