### ISSUE TITLE
DiscordSRV, double messages and error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1595]
When I tag someone in-game, it shows this error in the console: https://pastebin.com/d5VNqrfB

In-game it looks like this: https://prnt.sc/rhfskb

**Comment by lackoSK** [comment]
Please.. provide us your configs. zip your chc folder. Thx

**Comment by Sikatsu** [comment]
This is fixed when you disable the feature to translate in-game mentions to discord mentions within the DiscordSRV configuration. Note that this is not an issue with VentureChat. Looks like an incompatibility with DiscordSRV.

**Comment by lackoSK** [comment]
hmm. quite dont get this
