### ISSUE TITLE
1.15.2 /ch switch command not working

### ISSUE THREAD

**Issue by rybuilder23** [kangarko/ChatControl-Pro#1598]
ChatControl-8.6.6
paper version 143
minecraft 1.15.2

i m in 3 channels.
But he says that i can only switch if  i m already in a channel

http://prntscr.com/rjmhod

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4359995/ChatControl.zip)

**Comment by lackoSK** [comment]
You have to first join. /ch join <name>
