### ISSUE TITLE
{channel} as placeholder - suggestion/how to create it myself?

### ISSUE THREAD

**Issue by mellowism** [kangarko/ChatControl-Pro#1599]
When using channels and creating a format for those, it would be nice to be able to use one format for many channels, instead of many different formats. 

What I would like to have: https://pastebin.com/fHSPWwC9
What I end up having: https://pastebin.com/1s3pFTT7

With 11 different channels there are 11 different formats. Would prefer to have only one replacing all of those.

**Comment by lackoSK** [comment]
Hi there,

Do you want 1 global format for all channels? 

Regards,
lackoSK

**Comment by mellowism** [comment]
Not necessarily just one, but if channel were a variable I wouldn't need to have one format for each channel like I do now, since I mention the channel name in hover and in RUN_COMMAND etc. 

I've seen it is possible to create you own variables, but lack the skill to do so. Is this something you could help with?

**Comment by lackoSK** [comment]
Oh, you want to format the channels with hover event?

**Comment by mellowism** [comment]
I just want {channel} as a variable/placeholder. Not sure if you had a look at my config examples but I will try to explain better: 
I have 11 channels. 

- Global
- Local
- Creative
- Survival
- etc.

I want to be able to hover over and see for example: "Click here to join Global". Then, when clicking the channel name I want a command to execute, that makes the player join global.

The way I have set this up now is by having 11 different formats. One for each channel. The reason is that there is no placeholder for channel, so if I just make one format, where it says "click here to join global", I can't use that on Local channel, creative, survival and so on...

So if I could have a placeholder called {channel} I could create just one format where this is applicable to all channels. 

    First_Part:
      Message: "&f[&2{channel}&f] "
      Hover_Event:
        Action: SHOW_TEXT
        Values:
          - "&2&oClick to join {channel}"
      Click_Event:
        Action: RUN_COMMAND
        Value: '/ch j {channel}'

Have I misunderstood or isn't this something that should be possible to achieve with a custom javascript variable?

**Comment by lackoSK** [comment]
Hey,

Apologies for the late reply.

Now I get what you mean.  However, ChatControl-Pro is under recode, so you'll need to wait (Only Formatting part)

Regards,
lackoSK

**Comment by lackoSK** [comment]
Hello,

This will be added within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
