### ISSUE TITLE
Tell and Reply causes TPS drop

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1600]
Hi,

I'm using chatchontrol for bungeewide chatting. But when there are 25+ players online the tell and reply commands are causing a lot of TPS drop.
Am I doning something wrong or is this something in the code?
I know there are some simular issues, but not in the last time.

**version info**
git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
ChatControl: ChatControlPro version 8.6.6

**ChatControl.zip:**
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4368535/ChatControl.zip)

**Timings:**
https://pastebin.com/Gw4WLycz

regards,
martijnpu

**Comment by lackoSK** [comment]
Hi there,

We are working on fixing this issue. We need just to implement a new System (already made) to ChatControl.
