### ISSUE TITLE
Colours in chat not working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1601]
Hey,

I disabled the global bungee chat between servers and it is now using a chat per server. However, colours like player tagging nor /chc color work until I use a /chc reload after server startup. I'm not sure why it doesn't work after a server startup.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4374730/ChatControl.zip)

**Comment by lackoSK** [comment]
Talk to me on discord, please
