### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/ChatControl-Pro#1602]
Minecraft : 1.15.2
Tuinity : Build 14
Java : 11
Chatcontrol : 8.6.6

This error has being happening a long time now, for many versions.
https://pastebin.com/raw/LtQnzEN4

Config:
[config.zip](https://github.com/kangarko/ChatControl-Pro/files/4377327/config.zip)

**Comment by lackoSK** [comment]
We do not support Tuinity or any others. We support only Spigot and Paper.

**Comment by LucidAPs** [comment]
This was happening with Paper aswell for many many versions.

**Comment by LucidAPs** [comment]
Please reopen the issue.

**Comment by lackoSK** [comment]
Can you please send me this error, running spigot?

**Comment by LucidAPs** [comment]
Here it is.
https://pastebin.com/raw/xjvQ5DL9

**Comment by lackoSK** [comment]
Hey,

Apologies for the late response. 

You're running Java 11 can you switch to 8?

Thanks,
lackoSK

**Comment by HexedHero** [comment]
Same issue, paper java 8

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
