### ISSUE TITLE
1.15.2: Cannot disable formatting

### ISSUE THREAD

**Issue by MrOscarvs** [kangarko/ChatControl-Pro#1604]
ChatControl 8.6.6
Paper 1.15.2 (last build 146)

Hello, I want to disable the formatting option of the plugin, because I have a custom plugin that sends the messages in the format I want.

The thing is: I have the "Enabled" option disabled in 'formatting.yml', but the format is still working.

Am I doing it wrong or it's a bug? Thanks!
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4396717/ChatControl.zip)

**Comment by Darkool** [comment]
Hello there,  

I've this issue too:

`Enabled: false` on formatting.yml and it keeps overwritting my chat format.

Any solutions?

Best regards.

**Comment by lackoSK** [comment]
Hey guys,

Apologies for the late response. 

That should be working at all. However, we are under the recode of formatting. 

Maybe try to remove the whole ChatControl folder and restart the server? Give it a try please (Backup the old one)

**Comment by MrOscarvs** [comment]
Okey, I just read that when you enable the Channel Functionality, it completely disables standard formatting.

Is there any way to avoid this? I really need to use channels and an exterior formatting.

**Comment by lackoSK** [comment]
We are doing brand new formatting, we will consider it :)
