### ISSUE TITLE
8.6.6: Possible Whitelist All Links?

### ISSUE THREAD

**Issue by mcpantheon** [kangarko/ChatControl-Pro#1605]
Hi, Is it possible to whitelist all links? My mods are getting link spam messages from chatcontrol when they are doing worldediting. For example, this string throws errors:

/br sphere 1,1:1,1:2

So I can't think of a way to have worldedit bypass the URL filter so probably better I disable it. How can I do this? 

Thank you,
Oscar

**Comment by ElBananaa** [comment]
> Hi, Is it possible to whitelist all links? My mods are getting link spam messages from chatcontrol when they are doing worldediting. For example, this string throws errors:
> 
> /br sphere 1,1:1,1:2
> 
> So I can't think of a way to have worldedit bypass the URL filter so probably better I disable it. How can I do this?
> 
> Thank you,
> Oscar

Give your mods the permissions: chatcontrol.bypass.ad
and it should fix the issue.

Refer to https://github.com/kangarko/ChatControl-Pro/wiki/Permissions

**Comment by mcpantheon** [comment]
Thank you! I appreciate your quick help :)
