### ISSUE TITLE
Paper 1.12.2 | Issue with AirBar and ChatControlPro

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl-Pro#1607]
Hi!

I recently bought [AirBar](https://www.spigotmc.org/resources/airbar.16649/) and placed it on my server. But, since, I have this message shown in the console everytime a player send a message:
[ChatControl 8.6.6] AsyncPlayerChatEvent at HIGH(ignore cancelled = true) took 129 ms

The problem is that this is a real spam in the console, and it seems to be the source of latency in the chat.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4399177/ChatControl.zip)

**Comment by lackoSK** [comment]
Hey, 

Apologies for the late response. 

Does that appear also when you remove the AirBar? 

Regards,
lackoSK

**Comment by ElBananaa** [comment]
> Hey,
> 
> Apologies for the late response.
> 
> Does that appear also when you remove the AirBar?
> 
> Regards,
> lackoSK

Hey,

No problem. ^^

No, It only appear when I have AirBar installed with ChatControlPro.

**Comment by lackoSK** [comment]
We're recoding formatting so just wait, it might fix the issue. If not, open new issue. 

Thanks
lackoSK

**Comment by ElBananaa** [comment]
Up.

Reopening it since you are using github again.

**Comment by kangarko** [comment]
Thanks, I am back. Please wait until tonight, download the upcoming 8.7.0 version and then send us your full ChatControl/ folder ZIP file so I can have a look.
