### ISSUE TITLE
Unknown custom packed identifier: plugin:chatcontrol

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1608]
Paper dev 146 (Spigot 1.15.2)
Waterfall dev 326 (BungeeCord 1.15.2)
ChatControl Pro v8.6.6
BungeeControl v2.2.6

Client - Minecraft 1.15.2

The client seems to spam this in its logs, usually after someone says something.

```
[10:46:33] [main/WARN]: Unknown custom packed identifier: plugin:chatcontrol
```

**Comment by lackoSK** [comment]
Hey there, 

Apologies for the late response. 

That's weird, can you send us the whole log. 

Regards,
lackoSK

**Comment by mibby** [comment]
That is the whole log and only thing that is relevant. The warning message occurs with the use of ``BungeeControl`` to bridge the chat over BungeeCord. The message usually happens after someone types something when it is occurring, and happens for every single line posted. 

Removing BungeeControl and having chat be solely on one server, this issue does not occur.

**Comment by lackoSK** [comment]
Hello,

I was testing and wasn't able to simulate this issue. Any steps? Something that might be helpful? 

Sincerely, 
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
I'm not too sure how to reproduce, just that it occurs in the client's logs when the bridge is installed. Perhaps you must have someone connect to two different servers with chat being relayed to both so the bridge engages?

**Comment by lackoSK** [comment]
Hello,

Please zip me your settings and bungeecontorl's settings. I think I know where is the issue. 

Sincerely,
Ladislav from MineAcademy.org
