### ISSUE TITLE
Matching an uppercase character only

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1609]
According to regex testers, the `[I]`should match the uppercase `I` and not the lowercase `i`
Chatcontrol matches the `i` also.

Question is: why? Did I do something wrong?

Chc ver 8.6.6
Paper 1.15.2

**Comment by lackoSK** [comment]
Hey, 

What's your exact regex? 

Cheers, 
lackoSK

**Comment by x1p** [comment]
```
\boo*[I]o+
```
```
MATCH: \boo*[I]o+
CATCH: oioioi
FINAL: ioi
```

**Comment by lackoSK** [comment]
![image](https://user-images.githubusercontent.com/53174757/78759578-2151b880-7980-11ea-93a3-a266d52b1be7.png)
0 matches

**Comment by x1p** [comment]
It should match `ooIoo` where the "I" is a capital.
According to https://regex101.com/ it should work
![Screenshot_20200409_205345](https://user-images.githubusercontent.com/28690790/78930402-56efc200-7aa4-11ea-946b-a45274b21ec5.png)

**Comment by lackoSK** [comment]
Hello,

Now it's fine. Just to be sure - You are saying ChatControl-Pro matches also lowercased "i", right? (I need to be sure what to look for)

Sincerely,
Ladislav from MineAcademy.org

**Comment by x1p** [comment]
Yes. I would expect it to match only a capital i. And chatcontrol matches also the lowercase variant.
According to chatcontrol there is no difference between [E] and [e].
So chatcontrol is case insensitive in general.

`ooIoo` is sometimes used to express a middle finger. It's not a very big deal but I would like to know if there is any way to match an UPPERCASE character?

**Comment by lackoSK** [comment]
Hello,

The problem is, we are using regex we get (as I read the code) we do not modify it.
Can you zip me your ChatControl?

Sincerely,
Ladislav from MineAcademy.org

**Comment by x1p** [comment]
That won't be necessary because it is very simple:
- test server with paper 1.15.2 + chatcontrol 8.6.6 with default files (everything)
- rules.txt add test case e.g.:
```
match \bTest[w]ord
then warn The word was Testword

match \bTest[W]ord
then warn The word was TestWord
```
- chc reload
- player says: `This is a testword`
- player says: `This is a testWord`
- watch what will happen

My outcome is:
The word was Testword
The word was TestWord
`Player: This is a testword`
The word was Testword
The word was TestWord
`Player: This is a testWord`

**Comment by lackoSK** [comment]
Hello,

So you are saying it takes both? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by x1p** [comment]
Correct

**Comment by lackoSK** [comment]
Hello,

I will try to fix this issue within the next update of ChatControl-Pro. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by kangarko** [comment]
Apology this has been dragged for so long. I have quickly added a new flag to the settings.yml with the following caveact (please read the comments):

![a](https://i.imgur.com/QGH1Jmj.png)

Both flags will be available in the next release within the next few days.
