### ISSUE TITLE
[Suggestion] Delay between similarity message + caps detection

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl-Pro#161]
It would be very cool to add an option to set a delay between similarity message for block them only during a defined time. For example, if we say "Hi" and we left, we can't say "Hi" again.
I know that there is a whitelist but it's only an example and it happens several times with different messages.
Also, for the whitelist, it would be very nice if it detects the term no matter the capital.

PS : Sorry for my bad english.

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. Currently, more important features take place, but in the future I may seek out to expand the antispam.

Btw, there is a whitelist in Anti_Spam.Chat.Whitelist_Similarity.
