### ISSUE TITLE
Spigot 1.8.8 Packet Error

### ISSUE THREAD

**Issue by pvpstryker** [kangarko/ChatControl-Pro#1610]
ChatControl: 8.6.6
Error log: https://pastebin.com/HzBwa0yV
I get this error when players get certain items in their inventories.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4432585/ChatControl.zip)

**Comment by lackoSK** [comment]
Hey there,

Can you disable Packets in settings.yml

Regards,
lackoSK

**Comment by pvpstryker** [comment]
I did and I still get an error:
error: https://pastebin.com/MbeK3F2R
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4434254/ChatControl.zip)

**Comment by lackoSK** [comment]
Disable them also in Rules

**Comment by pvpstryker** [comment]
Yes, I did but it's still throwing the error, can you fix it now? 
error: https://pastebin.com/KZrBewLz
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4450803/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

Sorry, but you are using TacoSpigot that's a problem for me to restimulate the issue. 

We do not support TacoSpigot. 

However, I can give it a shot, send me your TacoSpigot.jar (use uploadfiles.io)

Sincerely,
Ladislav from MineAcademy.org

**Comment by pvpstryker** [comment]
https://yivesmirror.com/downloads/tacospigot

**Comment by lackoSK** [comment]
Hi,

What should be the items?

Regards
lackoSK

**Comment by pvpstryker** [comment]
A creeper egg,

Damn this support sucks, waiting 3 days for one liners. It's been 2 weeks and feel this issue is nowhere near from resolved.

**Comment by lackoSK** [comment]
Hello,

Sorry, we are all busy. Recoding ChatControl takes so much time.  

Anyways, you are using an unsupported fork of Spigot/Paper.

I have tested this issue and I was not able to simulate the packet error with your configs. 

Sincerely,
Ladislav from MineAcademy.org
