### ISSUE TITLE
Rare double chat output with DiscordSRV.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1611]
See: https://github.com/DiscordSRV/DiscordSRV/issues/675

ChatControlPro v8.6.6
DiscordSRV v1.19.0-SNAPSHOT (DiscordSRV-Build-1.19.0-SNAPSHOT-1585835031.jar)

Using ChatControl & DiscordSRV together, rarely there is a double output that occurs in chat.

**Comment by lackoSK** [comment]
Hey, 

please send us your ChatControl folder. 

Thanks
lackoSK

**Comment by mibby** [comment]
Please edit comment to remove link once obtained.
https://www.dropbox.com/s/4cbomwxj9o0novj/ChatControl.zip?dl=0

**Comment by lackoSK** [comment]
Hi there,

I was unable to simulate this issue. How am I supposed to simulate it?

Regards,
lackoSK

**Comment by mibby** [comment]
I'm not sure how to simulate this issue. It occurs at random and only for one or two messages that happen at the same time. DiscordSRV devs in the linked ticket say it would be an integration issue with ChatControl.

I'm assuming the chat listener breaks somewhere if it refreshes or lags.

**Comment by lackoSK** [comment]
Hello,

We have made some changes... After the new version will be out. Give it a shot, please. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
Sure, anxiously waiting for the new version.

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you.

Sincerely,
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
Hello @lackoSK, 

I'm not receiving any double output but I've discovered a plethora of discord linking issues with v9.0. I'll create new tickets for organization.
