### ISSUE TITLE
Spigot 1.15.2 - /tell /reply causing memory leak 

### ISSUE THREAD

**Issue by Verdux** [kangarko/ChatControl-Pro#1612]
It appears ChatControl is causing memory leaks when players use /tell and /reply, TPS drops massively to around 12 when players are messaging each other. When I take away perms to use these commands the TPS returns to normal.

Spigot 1.15.2
ChatControl: 8.6.6

Bungee relay was initially enabled but I disabled it in an attempt to see if that was the issue.

Timings: [Link](https://timings.spigotmc.org/?url=epurezivar)
[ChatControl (2).zip](https://github.com/kangarko/ChatControl-Pro/files/4424400/ChatControl.2.zip)

**Comment by lackoSK** [comment]
Hey, 

This is a known issue. It will be fixed soon. Don't worry, we are working on a new Formatting complex. 

Regards,
lackoSK
