### ISSUE TITLE
Showing player ip on join

### ISSUE THREAD

**Issue by SoftballGenius3** [kangarko/ChatControl-Pro#1613]
Hello! I downloaded ChatControl for my server and when we decided it wasnt the best fit for our server and deleted it, after we restarted whenever people joined it would show their ips and everyone could see them. any idea on why this is happening
!
[Uploading Screen Shot 2020-04-03 at 8.04.45 AM.png…]()

**Comment by SoftballGenius3** [comment]
![Screen Shot 2020-04-03 at 8 04 45 AM 2](https://user-images.githubusercontent.com/58284980/78366217-cb4ad280-7585-11ea-8922-24c03b3134a6.png)
sorry here

**Comment by lackoSK** [comment]
Hey,

This seems like essentials. 

The best way how to test:
1) Stop the server
2) Remove Essentials
3) Start it ^ Join

Best, 
lackoSK
