### ISSUE TITLE
split motd.yml into separate files (+? formats)

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1614]
As soon as I /chc mute, everyone spams /afk filling up the chat, please can you block the AFK messages when the chat is suppose to be muted.
Also can you have an option to block log in/log out messages when the chat is muted.

**Comment by lackoSK** [comment]
Hi there, 

Apologies for the late response. 

Yes, we will do so. 

However, ChatControl's formatting is right now under recode so this will take to while.

PS: Added to TODO!

Thanks,
lackoSK

**Comment by FrozenBeard** [comment]
@lackoSK If the formatting is under a recode, PLEASE implement #980 that I requested, a folder for formatting that breaks each section up so its not all bundled together, so we can have a motd.yml just for the MOTD, at present I have had to dynamically create the WHOLE formatting file to auto generate my MOTD, found here;
https://piratemc.com/motd/

I wrote an entire wordpress plugin to allow me to do this, its SOOO annoying having all formatting in one giant file, I hate it.

**Comment by kangarko** [comment]
@FrozenBeard I remember you suggesting this long time ago :) Will get done!

Would having the motd.yml file separated from settings.yml hold for now? And the formats.yml could stay merged. If there is a critical reason to split it we could, then each format would residue in its separate file in formats/format_name.yml for example

**Comment by FrozenBeard** [comment]
> 
> 
> @FrozenBeard I remember you suggesting this long time ago :) Will get done!
> 
> Would having the motd.yml file separated from settings.yml hold for now? And the formats.yml could stay merged. If there is a critical reason to split it we could, then each format would residue in its separate file in formats/format_name.yml for example

Not separate from Settings.yml, separate from the Formatting.yml, as this is the part that changes with new content!

Have a look at my https://piratemc.com/motd/ and CTLR+F for motd, this is where the automated content is filled in by Wordpress for latest block posts and stickied forum posts.

I like the idea of formats/format_name.yml that way its not all bundled in one giant config, if you look at mine, its huge and quite hard to find things sometimes.

**Comment by kangarko** [comment]
Thanks! We will split it!

**Comment by lackoSK** [comment]
Hello,

Hello, we have split the formats into different files. 

I am not sure what will the motd do? Explain, please. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
@FrozenBeard

**Comment by FrozenBeard** [comment]
The motd displays the message when a user logs in.

**Comment by lackoSK** [comment]
Gotcha, so like they would be custom for each ChatControl's group?

**Comment by kangarko** [comment]
@FrozenBeard sorry for delay, we got the system implemented, each format now residues in its own file in the new formats/ folder. A new release will be coming up this week.

**Comment by FrozenBeard** [comment]
Brilliant news, this will allow for automated changes in formatting! I'm excited to get hacking with them all!

**Comment by lackoSK** [comment]
@FrozenBeard would you like to test our new version? We have some beta tester team, and you might be interested in joining?

**Comment by FrozenBeard** [comment]
@lackoSK yes sounds good!

**Comment by lackoSK** [comment]
@FrozenBeard lackoSK#0001

**Comment by lackoSK** [comment]
May I close it here? @FrozenBeard

**Comment by FrozenBeard** [comment]
@lackoSK Sure I will open a new ticket if there are issues with it. I have not tested yet, im waiting for it to be more stable.

**Comment by FrozenBeard** [comment]
@kangarko please reopen this request for 8.x series.

**Comment by kangarko** [comment]
Not possible, at least without putting crazily amount of effort. V9 will bring this.

**Comment by FrozenBeard** [comment]
They briefly had it working fine in the v9 that was temporarily released?

What is the plan? why are there 2 versions?

**Comment by kangarko** [comment]
Replied elsewhere :)
