### ISSUE TITLE
/me on a per-channel basis

### ISSUE THREAD

**Issue by Feriixu** [kangarko/ChatControl-Pro#1615]
I am want to have the /me <message> command to be executed on a per-channel basis.
For example: If i am in the "standard" chat, only people who are reading "standard" should be able to read the output of the /me command. Similarly if I joined the "other-topic" channel I want only people who joined that channel to be able to see my /me command.
Is this possible?

**Comment by lackoSK** [comment]
Hey!

Thanks for the idea! 
However, I don't think that's a good feature for ChatControl.

Cheers,
lackoSK
