### ISSUE TITLE
nicknames not showing color

### ISSUE THREAD

**Issue by Hendrick020301** [kangarko/ChatControl-Pro#1616]
when using the chat formatting this is what i have.
    Message_Format: '%pl_prefix&r %nick%pl_suffix&r &7>>&r %message'
problem is it doesn't show the color of the nickname and its also removing the ~ when someones nicked, how can I fix this?

**Comment by lackoSK** [comment]
Hey there!

See https://github.com/kangarko/ChatControl-Pro/wiki/Formats
You have to use { } instead of % % 

Please, give it a try :)

Best, 
lackoSK
