### ISSUE TITLE
Path prefix must not end with a dot

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1618]
https://pastebin.com/vyV6H4kE

**Comment by lackoSK** [comment]
Hello there! 

Please send us your ChatControl folder.

Regards,
lackoSK

**Comment by coco0325** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4433732/ChatControl.zip)

**Comment by lackoSK** [comment]
Can you please remove your data.db ?

**Comment by coco0325** [comment]
ChatControl can't accept Discord name end with a dot, that's the problem.

**Comment by lackoSK** [comment]
Hello,

We are matching channels by name. We are getting the one from our configuration if the message sent is in the channel that equals to the channel in config. We process the message.

Is this issue solved? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by coco0325** [comment]
No, the issue is caused by Discord username.

**Comment by coco0325** [comment]
The problem happened when a Discord sender's name end with a dot.

**Comment by lackoSK** [comment]
Hello,



Sincerely,
Ladislav from MineAcademy.org

**Comment by kangarko** [comment]
Your sender "木貓教你如何吃瓜南......" contains dots. This is unsupported by ChatControl and it will fail. People playing on your server must not contain dots in their usernames.

**Comment by coco0325** [comment]
I consider it as a bug.

**Comment by kangarko** [comment]
Apology, but such functionality is not support, this is not a bug, Minecraft software is not coded to support dots in usernames like this properly.

**Comment by coco0325** [comment]
Could you make the plugin just ignore and not to display the dot?

**Comment by lackoSK** [comment]
It's not possible to ignore dots because we use them in our configuration and that would crash the plugin.

**Comment by coco0325** [comment]
How about replacing all "." in Discord user name to nothing?
