### ISSUE TITLE
Channel Command Simplicity

### ISSUE THREAD

**Issue by brickman312** [kangarko/ChatControl-Pro#162]
I would like to suggest an update to the commands used to join, leave, switch, and spy on channels. My main issue right now is that switching between channels is fairly difficult when you are spying on the channel you want to switch to. My idea would be that if you were to run the command /ch switch [chname], it would actually switch the places of the channels. So if I am in channel A and am spying on channel B, and I want to switch to channel B. I can run /ch switch B. This will make me join channel B and spy on channel A.

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. The next release includes improvements to the configuration and also cosmetics changes to how channels work. I will see if I can add up more simplicity to the channel commands in the future.
