### ISSUE TITLE
1.15.2: Admin channel prefix not working until plugin is reloaded

### ISSUE THREAD

**Issue by Curtis73** [kangarko/ChatControl-Pro#1620]
Hey, I have set my admin channel prefix as `!`, but until I reload the plugin with `/chc reload`, the full message is sent to my standard channel:
![image](https://user-images.githubusercontent.com/14040165/78606859-ec494700-7855-11ea-9b65-73813919876b.png)

I have also linked the admin channel to Discord, and after reloading the plugin with `/chc reload`, any messages sent to the admin channel in-game are not relayed to the Discord channel, whereas it worked fine before reloading.

ChatControl files:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4440876/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

I am unable to restimulate this issue. What is your ChatControl version? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Curtis73** [comment]
That's odd, I'm running on the latest ChatControl version 8.6.6. 
I've also noticed that the actual chat filter doesn't work until the plugin is reloaded, but only when it's integrating with DiscordSRV

**Comment by lackoSK** [comment]
Hello,

I have tested this on my server, with all of your configs. There were no issues for me. Can you please provide full a plugin list? Also, would be awesome to know your current Minecraft (exact) version (eg. Paper 1.15.2 build 70)

Sincerely,
Ladislav from MineAcademy.org
