### ISSUE TITLE
Feature Request: Channel Cooldown, /me - Cooldown

### ISSUE THREAD

**Issue by En0tS** [kangarko/ChatControl-Pro#1624]
Hi! When will coming next update and will it have per channel message cooldown? 
I need this feature so much and I waited a long time for it.

**Comment by En0tS** [comment]
Also, idk if it possible for now, but /me should be ranged.

**Comment by lackoSK** [comment]
Hello,

Please stay patient! 

We are doing massive changes to ChatControl-Pro. 

Explain the /me feature please...

Regards,
lackoSK

**Comment by En0tS** [comment]
/me shouldn't be global, I want to allow see these message only for players in 100 blocks range or even closer.

**Comment by lackoSK** [comment]
Hello,

So should we make it as range chat? We can make using channels. 

Me Command -> gets channel from config-if enabled -> sends the message to that channel

Sincerely,
Ladislav from MineAcademy.org
