### ISSUE TITLE
Any coma and dot are recognized by IP or website

### ISSUE THREAD

**Issue by scorninpc** [kangarko/ChatControl-Pro#1626]
Every message who has dot or coma, the plugin block with message:

Please do not advertise other website or ip addresses.

![image](https://user-images.githubusercontent.com/2607849/79409382-34fab180-7f74-11ea-8a9c-19804151f910.png)

My message example:  

![image](https://user-images.githubusercontent.com/2607849/79409437-5360ad00-7f74-11ea-87aa-7f862a2b4a48.png)

My config: https://pastebin.com/NGdKqAnp

ps 1: /g is my alias to !chat

ps 2: Can I allow IP and website on chat?

ps 3: maybe the problem are message who has , or . before the COM word, like `bla bla, com bla`. That is common in Brazil

**Comment by scorninpc** [comment]
Some commands too

`shop create 1 3 1.50 admin`

![image](https://user-images.githubusercontent.com/2607849/79497568-46889b80-7ffe-11ea-8aa3-35209a9e7806.png)

**Comment by lackoSK** [comment]
Hello,

You need to make proper configuration.. Go to /rules/chat.txt and you can edit it. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Everything is explained here: https://github.com/kangarko/ChatControl-Pro/wiki/Handlers

**Comment by scorninpc** [comment]
Ah ok, thank you
