### ISSUE TITLE
Better AdminChat+DiscordSRV integration on Bungeecord

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl-Pro#1627]
I was very excited to see that ChatControl had integration with DiscordSRV in regards to its AdminChat channel. However, there are major problems with this integration on Bungeecord networks which limit its usefulness.  

Essentially, AdminChat can be configured to work across the entire Bungeecord network, however AdminchatSRV channels cannot. Messages sent in-game will still be visible to all servers, as well as messages sent from the AdminChatSRV channel _only as long as there are players within the configured server._ (For example, if a SRV bot from a hub server is set to be the adminchatsrv bridge, then messages messages written in the Discord channel will only send network-wide if players are connected to the hub. The moment the server is empty, messages are not shared between servers.) Messages sent from game servers other than the configured SRV server are never logged to the Discord channel, even if the AdminChat message is received in the configured server--it must be sent from there in order for it to work.

Logically, you'd assume to be able to remedy this by configuring multiple DiscordSRV bots to use the same AdminChat channel for integrating the system across the network. However, this method results in duplicate messages and for messages sent through the AdminChatSRV channel to be visible to everyone in game, defeating the purpose of AdminChat.

Though this feature would be incredibly useful, it is useless on a Bungeecord configuration due to this issue. It's as if the integration does not consider the "Bungee: true" option in Admin_Chat: settings.

Here's an example of how it should work:
![unknown](https://user-images.githubusercontent.com/43658058/79420912-72187100-7f7f-11ea-961b-44f238ff9886.png)

Versus how it works currently:
![unknown1](https://user-images.githubusercontent.com/43658058/79421005-983e1100-7f7f-11ea-8d51-49ed8f2a6267.png)

**Comment by lackoSK** [comment]
Hello,

Thank you for the suppression. 
We will consider implementing it to the ChatControl-Pro

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

This should be added within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
