### ISSUE TITLE
Incorrect player sound notifiy messages strip message formatting

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl-Pro#1628]
Player usernames are case-sensitive when using sound-notify. Though sound-notify will trigger on messages containing propper capitalization, these messages will be stripped of all formatting + prefixes. 

For example, two players Notch and Jeb_.

Jeb_ says "Notch" in their message. As a result, "Notch" is highlighted green within the message and Notch, the player, hears the ping sound.

Notch says "jeb_" in their message. The username is spelled correctly, but the capitalization isn't correct. As a result, the player "Jeb_" hears the ping sound, but the message from Notch contains no formatting, their prefix is missing, and the username is not highlighted.

Real example: In this case, the player's real name was "Catsidy14". Capitalizing the name correctly would have "fixed" the issue.
![unknown2](https://user-images.githubusercontent.com/43658058/79422116-dccaac00-7f81-11ea-8777-5b2b9b70c642.png)

Solution: Make it so that sound-notify does not care about case. Most players do not tab-complete short/familiar usernames making this bug extremely common. Making it so that sound-notify _only_ responds to correct capitalization would not be a solution here for the same reason.

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
