### ISSUE TITLE
Suggestion: Allow sound notify to ping users on partial usernames 

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl-Pro#1629]
An annoyance of many players on my server is that they are required to type the _full_ username of the individual they wish to ping. On an older chat plugin we used, players could type a shortened version of another person's name and their message would still ping the other player; that does not exist as an option with ChatControl.

For example: 

Player1 says "BakiDance" in chat and the user, BakiDance, is pinged. However, BakiDance is not pinged if Player1 says "Baki". This is a problem for many as very rarely do players use full-usernames in their messages _especially if that username contains numbers_. If a player's username is "DylanDude150", they will not be pinged in game if someone says "DylanDude" or more commonly, just "Dylan". 

On multiple occasions this has resulted in staff (in addition to regular players) from being notified when they are mentioned. An easy solution for this would be to introduce a configurable option for players to be pinged if the first x letters of their real username is mentioned. In this case, "Baki" would trigger a ping for "BakiDance" if the sound_notify module is set to the first four letters of the username. This number could be configurable for the server based on its needs, or set to -1 to disable, requiring the full name be mentioned as it requires now.

As it stands now, missing 50% of name mentions makes it difficult to keep up with chat. Players rarely use full usernames when mentioning others, and having a way to ping others with partial names is a must-have. This could be as simple as introducing a "required_letters_for_ping: num" entry in settings.Sound_Notify.

**Comment by lackoSK** [comment]
Hello,

Thank you for the suppression. 
We will consider implementing it to the ChatControl-Pro

Sincerely,
Ladislav from MineAcademy.org
