### ISSUE TITLE
Suggestion: permission to only mute private message

### ISSUE THREAD

**Issue by TonnyBear** [kangarko/ChatControl-Pro#1633]
Can't find any way to ignore only private messages from other players while still being able to see chat messages. 
I need this to be done with some kind of bypass permsission since I don't want this option for everyone. 
Example: Staff member wants to ignore private messages from a regular player but I need him to see his messages in chat so he can react if needed. 
This is how chatcontrol is working for OP's I can ignore private messages but I can still see chat messages, 
I just need a way to enable the same thing for other members of staff team.

Would be nice if there was something like chatcontrol.ignore.bypass.chat and chatcontrol.ignore.bypass.private

**Comment by lackoSK** [comment]
Hi there, 

You can toggle pms. 
![image](https://user-images.githubusercontent.com/53174757/79694507-e9485080-8270-11ea-90d1-29544f4ad5c7.png)

(TogglePM) one found in settings.yml

Regards,
lackoSK from Mineacademy.org

**Comment by TonnyBear** [comment]
Hello there, togglePM disables PM from everyone, we need to ignore PM from specific players ( for example one player, not everyone ). Like I wrote above, this is really useful for staff members. This way they can ignore PM from someone anoying and focus on supporting other players, but they can still see if that PMIgnored player is breaking some rules in global chat.
