### ISSUE TITLE
Untranslateable words

### ISSUE THREAD

**Issue by MaxWainer** [kangarko/ChatControl-Pro#1634]
Plugin version: ChatControl-Pro-8.6.6
Core: spigot-1.12.2

Edited: I can't translate this line: 
![image](https://user-images.githubusercontent.com/53620097/79699834-93889e00-829a-11ea-84a6-47b4f1f195d9.png)
Proof of this:
![image](https://user-images.githubusercontent.com/53620097/79699851-aac78b80-829a-11ea-8579-2f6aa5f12ccf.png)

It's my ChatControl folder:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4500269/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

This will be added within the next release of ChatControl-Pro.

PS: You will be able to find it in Cannot.Newcomer_Chat [localization]

Sincerely,
Ladislav from MineAcademy.org
