### ISSUE TITLE
Channel permissions

### ISSUE THREAD

**Issue by Krakenazo** [kangarko/ChatControl-Pro#1635]
Hello, 

Users who have permissions for a channel at a given time, when revoked, are still being added to the channel every time they logon to the server. I've checked and the permission for autologin is not active.

Thanks for your assistance.

**Comment by lackoSK** [comment]
Hello,

You need to enable autojoin: Auto_Join: and set it to true [channels.yml]

Is that what you meant? Or? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Krakenazo** [comment]
Hello, 

No. That isn't what I meant. Autojoin is working, the problem is that people are joining channels that they no longer have the permission to do so.

Thanks.

**Comment by lackoSK** [comment]
Hello,

Apologies for the late reply. 

We have partly recoded Channels along with new Formatting. 

Please, wait until the new version of ChatControl-Pro is out. 

Thanks!

Sincerely,
Ladislav from MineAcademy.org
