### ISSUE TITLE
1.12.2: Message not cancelling

### ISSUE THREAD

**Issue by bzigus** [kangarko/ChatControl-Pro#1636]
https://prnt.sc/s2uez2
The message is still being sent eventhough it is supposed to be canceled (not sent). When I do reload the plugin (/cc reload) it works, but when I restart the plugin it stops again. Any idea way??

Plugin Info:
ChatControlPro - 8.6.6
Plugin List http://prntscr.com/s2ulj5
git-Paper-1618 (MC: 1.12.2)

No console errors

**Comment by lackoSK** [comment]
Hello,

Please zip us your ChatControl-Pro folder. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by bzigus** [comment]
Hi, sorry for the wait, didn't get a notification. 
Here you go :)
[ChatControl (3).zip](https://github.com/kangarko/ChatControl-Pro/files/4565820/ChatControl.3.zip)

**Comment by lackoSK** [comment]
Hello,

What are your permissions? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by bzigus** [comment]
I don't think it's a permissions issue. Like I said, it works when I reload the plugin (/cc reload). 
Here is the exported file. there's a lot of perms
[test.json.gz](https://github.com/kangarko/ChatControl-Pro/files/4600831/test.json.gz)

**Comment by lackoSK** [comment]
Hello,

`match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
id 1
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]|\s*
handle as advertisement`

Your condition lacks "deny".
add `then deny` (Cancel the player's message from appearing in the chat.)

PS: Let me know if worked.

Sincerely,
Ladislav from MineAcademy.org

**Comment by bzigus** [comment]
Hi!
It's not just advertisements. It is whenever it tries to "deny" the message, so for spamming, it will warn but not do anything. It is also not what you said above because it is being handled by the Advertisement handler

`advertisement:
  #
  # Ignore players with a proper permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.ad"
  #
  # Do not filter ads in the following commands:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  #
  # Warn the player.
  #
  Player_Warn_Message: "&7Please do not advertise other websites or IP adresses."
  #
  # Notice online staff members.
  #
  Staff_Alert: "chatcontrol.notify.ad Ad_Info"
  #
  # Deny the message entirely.
  #
  Block_Message: true
  #
  # Log the violation so you can check it if you are offline.
  #
  Write_To_File: logs/advertisements.log`

**Comment by lackoSK** [comment]
Hello,

I got in trouble simulating it using your configs. Can you please provide me the newest configs where the issue is visible? I wanted to test it on your configs. However, I can't because they are not acutal/**chicken.com does nothing** (when I had all the perms down)

Sincerely,
Ladislav from MineAcademy.org

**Comment by bzigus** [comment]
[ChatControl (2).zip](https://github.com/kangarko/ChatControl-Pro/files/4612525/ChatControl.2.zip)
Here you go. I've changed nothing recently. And you are not opped when running the message?

**Comment by kangarko** [comment]
@bzigus hey, I tried to reproduce your problem but was unsuccessful

Just to be sure, can you please test only using ChatControl and no other plugin? That way we find out if there is another plugin causing this incompatibility.

You can also change Listener_Priority.Checker to HIGHEST and Formatter to MONITOR to see if these help.

**Comment by bzigus** [comment]
Ok, only like 3 weeks later. We got to the bottom of it. Tested in a clean server, it works. I raised the Listener_Priority.Check to Highest then had to lower it to HIGH because of the formatter needing to higher. It's working now Thank You!

**Comment by lackoSK** [comment]
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org
