### ISSUE TITLE
1.15.3 StringIndexOutOfBoundsException on Chat Event

### ISSUE THREAD

**Issue by RainbowDashLabs** [kangarko/ChatControl-Pro#1637]
This error occurs random when a player sends a message. It breaks the whole formatting of the message and changes it to the default format. The error can not be reproduced by sending the same message again.

Error:
https://pastebin.com/6ygTptU5

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4531952/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
