### ISSUE TITLE
ChatControl-Pro 

### ISSUE THREAD

**Issue by Bonitic** [kangarko/ChatControl-Pro#1638]
**** Why does the plugin not work for me, I do /pl and it is red

**Comment by lackoSK** [comment]
Hello,

Is there any error in the console? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Bonitic** [comment]
I Fixed the issue, I needed to download another plugin for it to work. Thanks for responding tho 😊


Sent from Mail for Windows 10
