### ISSUE TITLE
Handle command with space ?

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl-Pro#164]
Hi, I have a big problem with the configuration, when we set a short alias like "t" (alias of "/tell") for command, it also affects all commands starting with t like "/tpa", etc. Same with "w" (alias of "/whisper") & "/warp"...
I tried to leave a space after the "t" but it doesn't care.
Is there a solution to make the plugin understand that only the letter with a space behind has to be handled?
And if not, would it be possible to add that?

Example in my settings.yml configuration : 
`
  Commands_To_Apply:
  - msg
  - m 
  - pm 
  - tell
  - t 
  - whisper
  - w 
  - reply
  - r `
`
    Handle_As_Chat:
    - msg
    - m 
    - pm 
    - tell
    - t 
    - whisper
    - w 
    - reply
    - r `

PS : Sorry for my bad english.

**Comment by kangarko** [comment]
Hey, it's not currently possible. You can use Bukkit's commands.yml file to add aliases that will respect letters.
