### ISSUE TITLE
CMI msg priority

### ISSUE THREAD

**Issue by alecfarmer** [kangarko/ChatControl-Pro#1640]
I'm using CMI in replacement for essentialsX. I'm running into the issue of CMI's /msg overriding ChatControl's /msg. I'm not sure if I'm missing something. I've tried modifying commands in the spigot commands file and still nothing. I'm probably missing the slightest detail, but any ideas?

ChatControl+ 8.6.6
Paper 1.15.2 - version 155

**Comment by Kbryst** [comment]
Heya friend, Use cmi alias editor to redirect the /msg to /tell. 

I believe I also changed cmi's /msg back to /cmi msg - I know I eventually disabled it somehow, but I can't remember what I did. The above is just a tempfix.

**Comment by lackoSK** [comment]
Hello,

Do you still need help with this issue? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by alecfarmer** [comment]
> Heya friend, Use cmi alias editor to redirect the /msg to /tell.
> (I believe its /cmi aliaseditor new msg$$-tell$$ - read the cmi wiki about the $ placeholder)
> 
> I believe I also changed cmi's /msg back to /cmi msg - I know I eventually disabled it somehow, but I can't remember what I did. The above is just a tempfix.

Just changing the alias of /msg back to /cmi msg fixed the issue. Thank you so much!

**Comment by alecfarmer** [comment]
> Hello,
> 
> Do you still need help with this issue?
> 
> Sincerely,
> Ladislav from MineAcademy.org

No, all good here!
