### ISSUE TITLE
ChatControl 8.6.6 encountered a bM and a ConcurrentModificationException

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1641]
tunity paper 1.15.2
cc 8.6.6

Just noticed today a few errors in the error.log and the error_yaml.log - These have been going on for a while.  Earliest recorded I can see just by scrolling up in the error log is like early april. 

https://pastebin.com/U8atuXcQ

We are currently having some chat issues, but I can't confirm if this is related or not. I don't think it is, since this has been going on for a while.

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
