### ISSUE TITLE
Issue with {server_name}

### ISSUE THREAD

**Issue by hwrichardson999** [kangarko/ChatControl-Pro#1642]
I run Chat Control Pro on a bungee network. I have 9 servers.

All the servers run 1.15.2 and one runs 1.12.2. The server with 1.12.2 instead of showing SMP in the {server_name} prefix shows A minecraft server. The config's are fine as far as I can tell. I have copied and pasted them from the other server and adjusted the names to SMP.

**Comment by hwrichardson999** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4561258/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

You can change it in server.properties.

Sincerely,
Ladislav from MineAcademy.org

**Comment by hwrichardson999** [comment]
Sadly that's not the issue

**Comment by lackoSK** [comment]
Hello,

Weird, loaded up your configs and it works
![image](https://user-images.githubusercontent.com/53174757/81095551-76dc9f00-8f05-11ea-9359-3fc5007d027c.png)

Sincerely,
Ladislav from MineAcademy.org

**Comment by hwrichardson999** [comment]
Closed
