### ISSUE TITLE
1.15.2: Chat color isn't removed when players have no permission

### ISSUE THREAD

**Issue by mikesonchan** [kangarko/ChatControl-Pro#1643]
I gave the permission "chatcontrol.command.color" to VIP. But when the VIP membership ends, the color won't be removed. I knew that chat color will be removed automatically when the player logs in and lacks the permission from version 7.8.28. But it doesn't seem to work.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4566080/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

Just to clarify. When the player's perm for color expires, he will still be able to use the color command? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by mikesonchan** [comment]
No, he won't.

![註解 2020-05-03 164637](https://user-images.githubusercontent.com/33176179/80909803-b1a3d300-8d5d-11ea-96a4-ebd86ccac282.png)

**Comment by lackoSK** [comment]
Hello,

So if he doesn't have the permission (chatcontrol.command.color) anymore his color remains. Right? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by mikesonchan** [comment]
Yes

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
