### ISSUE TITLE
Players cannot use smileys?

### ISSUE THREAD

**Issue by Vehzx** [kangarko/ChatControl-Pro#1645]
Maybe there is an option somewhere in settings for this, but I can't seem to find it.

Players cannot use :) in-game, it gets changed to some random characters, I tried saving the file as UTF-8 encoding but still no luck.

**Comment by Vehzx** [comment]
Also: OPs (me) can use smileys with no issue

**Comment by lackoSK** [comment]
Hello,

Do you have proper permissions set up? You can find permissions on our wiki. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

Do you still need help? If yes, please comment under this issue and **mention me to respond!**. 
Example: 
`Yes, I do! @lackoSK `

If not, then we hope your issue was solved! If there is anything more we can do for you, just follow the "Yes" part.

 Anyways, have a beautiful day!

Sincerely,
Ladislav from MineAcademy.org

**Comment by Vehzx** [comment]
Yes, I do! @lackoSK 

Hi, sorry for not replying for so long and suddenly re-opening this thread, honestly not too sure if I have the permission node setup.

I did take a look through the permission wiki, but I can't seem to find the permission that allows for uses of :) etc, could you possibly reply with the correct permission node?

Again, sorry to be a pain

**Comment by kangarko** [comment]
Apology for that we forgot to return to you, I am tagging my teammate :)

@lackoSK

**Comment by lackoSK** [comment]
Hello,

Apologies for the delay. Can you please send us your ChatControl-Pro folder? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Vehzx** [comment]
Hi just saw this, I ended up fixing my issue in the end I was just being stupid haha

Sorry about leaving this open for so long.
