### ISSUE TITLE
1.15.2: If swearings are on the second+ place in the sentence they're working

### ISSUE THREAD

**Issue by Volgeop** [kangarko/ChatControl-Pro#1646]
Hi, players on my server could swear like they want. They can't write swearings in this format "Idiot", but they can write them in this "You're idiot!". Problem is that swearings aren't blocked, replaced, etc. when they are on the second or next positions in the whole sentence.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4568676/ChatControl.zip)

Image: https://ctrlv.cz/ABCo

**Comment by lackoSK** [comment]
Hello,

Yes! It's possible,
1) You need to enable Private_Messages in settings.yml.
2) Search for format: 
`Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
`
3) Open your format in formatting.yml
4) Follow https://github.com/kangarko/ChatControl-Pro/wiki/Formats

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Dobrý deň, 

Máte tam zlý regex. 
Dajte tam `\b(i+(\W|\d|_)*d+(\W|\d|_)*i+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*)` a malo by to fachať.

S pozdravom, 
Ladislav z Mineacademy.org

**Comment by Volgeop** [comment]
Stále nefunguje. Jinak v tom regexu, který tam mám, a který jste poslal, je akorát rozdíl v tom, že jste mi odebral varianty idY/ioT/d. Avšak zkusil jsem i Váš regex a stále to nefunguje... Hráči normálně mohou místo idiot napsat: ty jsi idiot a nic to neblokne.

**Comment by kangarko** [comment]
Ahoj,

Skúšal som nájsť chybu, po odstránení "strip" operátora to funguje. Na probléme s chýbajúcou medzerou pracujeme.

![a](https://i.imgur.com/3yiuikQ.png)

```
# Blocks 'idiot'
match \b(i+(\W|\d|_)*d+(\W|\d|_)*(y|i)+(\W|\d|_)*o+(\W|\d|_)*(t|d)+(\W|\d|_)*)
then replace vzdělanect
then sound <AMBIENT_CAVE>
#before strip \s*
```

**Comment by Volgeop** [comment]
Ano, pravda, již to funguje bez toho strip, až na ty mezery. A to strip není tedy nijak potřebné? Mám ho všude oddělat?
