### ISSUE TITLE
CMI Private Message (CHAT Interactive msg on hover)

### ISSUE THREAD

**Issue by CyreX12** [kangarko/ChatControl-Pro#1647]
I bought the plugin two days ago and I have an important question to ask. I am currently using a CMI plugin instead of Essentials. There is also a private messaging system here. Is it possible to do that when I hover over the cursor to the name of the sender / receiver write it out information from player, with placeholders. If you can do it, how? I use the latest version of both plugins. (8.6.6 and 8.6.24.0).
Thank you in advance for your help.

**Comment by lackoSK** [comment]
Hello,

Yes! It's possible,
1) You need to enable Private_Messages in settings.yml.
2) Search for format: 
`Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
`
3) Open your format in formatting.yml
4) Follow https://github.com/kangarko/ChatControl-Pro/wiki/Formats

Sincerely,
Ladislav from MineAcademy.org
