### ISSUE TITLE
Question: how to ignore a rule in console

### ISSUE THREAD

**Issue by LoneDev6** [kangarko/ChatControl-Pro#1648]
Hello,
is there a way to stop a rule from being logged in console?
It's a big spam when a lot of players matched the rule during the day.

Thanks

**Comment by lackoSK** [comment]
Hello,

You can find it in settings.yml 
![image](https://user-images.githubusercontent.com/53174757/81093387-53fcbb80-8f02-11ea-9bf8-7c9e208e62be.png)

Sincerely,
Ladislav from MineAcademy.org

**Comment by LoneDev6** [comment]
@lackoSK hello, thanks for the answer, will this work also on ChatControl free version?

Thanks
