### ISSUE TITLE
Vip Formatting

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#1649]
so i basically copied my Default chat formatting and pasted changing all the names to Vip_(name)
and also made that thing
Default: Chat, so i made for vip be Vip: Vip

and this is the current formatting

  Vip:
    Vip_Gang:
      Message: '&b&l[&e{dixtonstats_oi&b&l]'
      Sender_Permission: rank.1
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&bClick for more info'
        - '&babout this Gang'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: /gang info {gangsplus_gang}
    Vip_Space:
      Message: ' '
      Sender_Permission: rank.1
    Vip_First_Part:
      Message: '&f<&7'
      Sender_Permission: rank.1
    Vip_Player:
      Message: '{pl_prefix+}{player_name}'
      Sender_Permission: rank.1
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - oi
    Vip_Final:
      Message: '&f> '
      Sender_Permission: rank.1
    Vip_Third_Part:
      Message: '{vault_suffix_color}{message}'
      Sender_Permission: rank.1

it doesnt give any console error, i gave the player the permission, but it doesnt work

**Comment by lackoSK** [comment]
Hello,

Have you enabled the Formatting in settings.yml? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
yes it is, cause the default is working, but for the vips its not

**Comment by lackoSK** [comment]
Hello,

Did you give the role VIP perm rank.1?

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
yes i give them the permission, also even if they will be using the permission * or OP wont work

**Comment by dabou0** [comment]
i actually ended up solving this problem, but now im having an issue regarding conditions
i have a /fake plugin, and when they using /fake i want to show no prefix as if they were default players with no rank, cause i made it to the prefix give the color, so if no prefix = no color = default player

this plugin will change player name at packet level, but if i will message a player name thats trought /fake it will say theyre not online, so i tought if i could make a condition that would say the player name to check if they online, if they not it wont show it would work, but idk how to do this

here are the following

    prefix: #default
      Message: '{pl_prefix+}'
      Condition: '"{player}" == "kangarko"'
    Rank_1: #default
      Message: '{player_name} {player_displayname} {player} {nick} {display_name}'
#      Sender_Permission: "rank.1"
      Hover_Event:
        Action: SUGGEST_COMMAND
        Values: "/tell {player} "
        Action: SHOW_TEXT
        Values: 
        - "/say {player}"


and also when i click the name this suggest command is not working

only the hover msg

![image](https://user-images.githubusercontent.com/34607217/81586293-ae2ad000-938b-11ea-8cdc-ed7277f54bc2.png)


thank you very much

**Comment by lackoSK** [comment]
Hello,

So you want to check if the player is online? Because once his nick is changed (properly), it's hard to work it out. I would just get a placeholder for that player **from** that nick-changer plugin. 

Can you please run the %player_name% (or whatever it is) placeholder through PlaceholderAPI parse engine so we can see what are we working with. Do `/papi parse me My nick is: %player_name%`

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
![image](https://user-images.githubusercontent.com/34607217/81627886-8d876800-93d5-11ea-89e2-1febad680f06.png)
it will change also if i change to my fake name,

**Comment by lackoSK** [comment]
Hello,

That's strange. I think you can use UUIDs 

player.getUniqueId().toString() == uuid

UUID never changes (unless your plugin can do it :D) - give it a shot.

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
hi, its giving this
https://pastebin.com/pzLxXHCN

**Comment by lackoSK** [comment]
Hello,

You must replace the UUID with your UUID. Get yours [here](https://mcuuid.net/)

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
but i want for everyone this to work, cause all staffs can use /fake

**Comment by lackoSK** [comment]
Hey,

Okay then you can match the player groups using: (hope you use LuckPerms)

`{luckperms_primary_group_name} == admin` (or group(s) you want to use (||) to split 

- lackoSK

**Comment by dabou0** [comment]
but its still the same group they have, it just change their name in a packet level, ty

**Comment by dabou0** [comment]
also is it possible for someone to disable their chat ? so they wont see chat messages from players, and only PMs

**Comment by lackoSK** [comment]
Hello,

For now, you can take them the perms. We will be working on the toggle chat command soon. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
kk  tkx, can you help me with the fake thing yet, ty

**Comment by lackoSK** [comment]
Hello,

What's still wrong with it? Just use groups to match it if groups do not change

Sincerely,
Ladislav from MineAcademy.org

**Comment by dabou0** [comment]
but i want for example, when they are using a fake name, their chat formatting will be one that doesnt show their rank, when their not using a fake name it will be a one that shows their rank

**Comment by dabou0** [comment]
also can u make that for me with multiples groups, make for example with owner, admin and mod+, cause i didnt understand how to make the separation, tyvm

**Comment by dabou0** [comment]
this is regular formating, i want when hes using /fake to use another part of the formatting, that will hide his rank, and also his name will have color &7 so no player will know their staff and will think they are default player, so like this staff can look for hackers

**Comment by lackoSK** [comment]
`({luckperms_primary_group_name} == owner || {luckperms_primary_group_name} == admin || {luckperms_primary_group_name} ==  mod+)`

May I receive that NICK plugin to see what can we do about it? I need to know if it has an API that we can use. lackoSK#0001

**Comment by dabou0** [comment]
Hi
i tried using the condition you gave me, but it didnt work
https://pastebin.com/ALy8NUkZ

ty

**Comment by lackoSK** [comment]
I tried hooking it to plugin manually but the plugin doesn't seem to have a functional API then. (If it is bungee pl we can not reach it) so I am not sure how to make it work with this plugin. Maybe ask the developer to create an API and send you how to use it.

**Comment by dabou0** [comment]
kk tkx
