### ISSUE TITLE
Bungee chat "Enabled_By_Default: false" not working

### ISSUE THREAD

**Issue by hazamashoken** [kangarko/ChatControl-Pro#1652]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4581794/ChatControl.zip)

When i turn the option to false and restart the server. Players join still have bungee chat on by default.

**Comment by lackoSK** [comment]
Hello,

I've tested this issue with your configs. Works. (If you have OP it joins you automatically)

Sincerely,
Ladislav from MineAcademy.org

**Comment by hazamashoken** [comment]
is there a way to disable auto join for op ?

**Comment by lackoSK** [comment]
Hello,

I will try to fix it in the next version of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
