### ISSUE TITLE
Any shortcut function provided for channel.yml?

### ISSUE THREAD

**Issue by JimmySuckOn9** [kangarko/ChatControl-Pro#1653]
As title.
I've made a Staff Chat using the 'Channel' function. However, compared with the admin chat inside the settings.yml, settings.yml can set a shortcut for the people, like "!Hi" will show "Hi" in Staff Chat, but when I'm using 'Channel' function, it didn't provide any 'shortcut' function inside. Hope the author can add this function (Shortcut) to 'Channel'. Thx a lot!

**Comment by lackoSK** [comment]
Hello,

https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands

Sincerely,
Ladislav from MineAcademy.org

**Comment by JimmySuckOn9** [comment]
What I mean is not 'Alias', should be 'Shortcut'.

Admin_Chat:
  Bungee: true
  Log_To_Console: true
  Write_To_File: true
  Discord_Channel: ""
  **Shortcut: '`'**

From the settings of CHC, when I typed '`Hi', it shows 'Hi' in admin chat.

**Comment by lackoSK** [comment]
Hello,

Gotcha.

Thank you for the suppression. 
We will consider implementing it to the ChatControl-Pro

Sincerely,
Ladislav from MineAcademy.org
