### ISSUE TITLE
Could not pass event PlayerJoinEvent to ChatControl v8.6.6

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1654]
Got an error when a player joined.

Server log: https://pastebin.com/6Njn820r
error.log: https://pastebin.com/uv3wfZCu
error_yaml.log: https://pastebin.com/BCvznzzz

**Comment by lackoSK** [comment]
Hello,

Can you attach your ChatControl-Pro folder? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by x1p** [comment]
I'm not sure what you expect to find there. This error is very rare. It's not that I made an obvious mistake somewhere.
The player that joined, is a regular player who joins often without any error.  Many players join and leave every day without any errors.
I censored many things for obvious reasons.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4604393/ChatControl.zip)
Good luck

**Comment by lackoSK** [comment]
Hello,

Got it. I am just making sure to simulate it properly to get better results when testing accurately. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hey there!

Can you please contact me on discord? lackoSK#0001

I will send you a new version and you will test it. 

Regards,
Ladislav form Mineacademy.org
