### ISSUE TITLE
Warn Operator

### ISSUE THREAD

**Issue by Snowy001** [kangarko/ChatControl-Pro#1657]
Hi, I'm having an issue with my warn sets. What I want to do is to /warn someone with my AdvancedBan plugin, however, when I type warn, it instead just says the command args to the player instead of running the command. Is there a way I can disable the warn operator or just directly run the warn command? I've tried /warn but it doesn't work since commands in console don't need slashes. Thanks in advanced.

**Comment by lackoSK** [comment]
Hello,

What do you mean? Seems like AdvancedBans issue, not ChatControl-Pro issue? Isn't it? What are you trying to achieve with warns? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Snowy001** [comment]
It's not an advancedbans issue. When I type warn in the command place, it uses the warn operator which makes the rest of the command just be displayed to the player instead of running the command

**Comment by kangarko** [comment]
Replace the rule operator from:

`then warn X`

to

`then console warn X`

That will actually run the command /warn from your plugin.

Cheers!
