### ISSUE TITLE
1.15.2: Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by angelcraft** [kangarko/ChatControl-Pro#1658]
![image](https://user-images.githubusercontent.com/14032215/81699299-6f6a4800-9467-11ea-8f93-c9ec61e0bdf1.png)

**Comment by Vehzx** [comment]
Was going to make an issue post of this, seems I get the same thing sometimes, this doesn't seem to happen when I have player direct sound pinging on (when someone types a name in the chat of someone who is logged in, and it's green, playing a sound to that player).

My error (pretty sure it's the same as above): https://pastebin.com/5hqMThjk

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
