### ISSUE TITLE
Request: Show item in chat (In hand) using regex. 

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1659]
Using a regex placeholder like [item] or [i] replace that with the item the player has in their hand.

CMI has this, but I don't want to have to give up formatting from ChatControl pro just to have this feature, I also don't wan to have to install a whole extra plugin to to manage chat.

Examples;
https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/

https://www.spigotmc.org/resources/%E2%96%B6-displayitem-%E2%97%80-share-your-item-in-chat-by-saying-item.28931/

**Comment by FrozenBeard** [comment]
Edit: just thought this should be possible with placeholderapi?

**Comment by FrozenBeard** [comment]
There is %player_item_in_hand_name% in "Player" PlaceholderAPI, but there is nothing for Lore.
Further more, It seems you can't have hover over information for replacements in Rules.txt/Chat.txt

:(

**Comment by lackoSK** [comment]
Hello,

I can join you to BETA testers on discord and you can try the new ChatControl with this feature. If you want to contact me on discord: lackoSK#0001

If not, coming in the next update. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by FrozenBeard** [comment]
@kangarko please reopen this request for 8.x series.

**Comment by kangarko** [comment]
Not possible, never be. V9 will bring this.
