### ISSUE TITLE
Make ChatControl-Pro for Spongeforge

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#166]
I would like to see this plugin compatible with spongeforge (example i run pixelmon under bungeecord, i would like to use chatcontrol admin chat so i can comunicate with my staff from pixelmon server)

**Comment by kangarko** [comment]
Hey,

in the meantime, ChatControl is available for Bukkit-only. You can install [BungeeControlBridge](https://www.spigotmc.org/resources/13079/) to your bungee server to enable many bungee features.
