### ISSUE TITLE
using placeholder match for party channel

### ISSUE THREAD

**Issue by keyute** [kangarko/ChatControl-Pro#1660]
as said in the title. is it possible to use placeholders for party channel?

**Comment by lackoSK** [comment]
Hello,

In ChatControl-Pro formatting you can use any placeholder which supports PlaceholderAPI or MvdwPlaceholders 

Sincerely,
Ladislav from MineAcademy.org

**Comment by keyute** [comment]
Perhaps my question didnt went across right. Is there a way to make chat channel party function work with placeholders?

something like
Party: placeholder
Placeholder_Match: %someplaceholderhere%

so that any players who have the same placeholder will be able to see the message you've sent

**Comment by lackoSK** [comment]
Hello,

You can create a "party" using:
TOWN
NATION
FACTION
FEUDAL
KINGDOM
FEUDAL_ALLY
PLOT

(Plugins)

Sincerely,
Ladislav from MineAcademy.org
