### ISSUE TITLE
Disable chat colour command.

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1661]
There are times when players dislike seeing too many colours in chat. I was reflecting on it and realised there should be a command to toggle off chatcolours for an individual. E.g. `/chc ignore colours`. 

The function is, if the player types the command `/chc ignore colours` it should not send them chat colours (except for player displayname/prefixes). Everyone else should see the colours unless they explicitly use the `/chc ignore colours`. This would also need to be a toggle. Meaning, using it, turns the feature on/off for the player depending on its current state.

Similar to this logic:
`value = !value;`

**Comment by lackoSK** [comment]
Hello,

Thank you for the suppression. 
We will consider implementing it to the ChatControl-Pro

Sincerely,
Ladislav from MineAcademy.org
