### ISSUE TITLE
Command on chat

### ISSUE THREAD

**Issue by OriginersMc** [kangarko/ChatControl-Pro#1662]
Hi

I want on chat:
When user writtes an command on chat (like "hello, use /tpa for go with me") this command (/tpa) appear on purple on chat.

How I can do that?

Best regards

**Comment by lackoSK** [comment]
Hello,

Hey! You can use regex to do it when they say "hello, use /tpa for go with me"

`match hello, use \/tpa for go with me
 then replace /tpa|&d/tpa` 

Hope it will work

Sincerely,
Ladislav from MineAcademy.org

**Comment by OriginersMc** [comment]
/tpa is any command, not just /tpa.

How I can do that?

**Comment by lackoSK** [comment]
What do you mean?

**Comment by OriginersMc** [comment]
When user writtes an command on chat, mark this in purple

**Comment by lackoSK** [comment]
Oh, you mean when I write /tpa and wont send (will just type to chat) it it should be purple?

**Comment by OriginersMc** [comment]
Yes, any command writted on chat change it on purple

**Comment by lackoSK** [comment]
Oh, well, sorry that is not possible. 

If we mean the same thing
![image](https://user-images.githubusercontent.com/53174757/82156904-78e81b80-987e-11ea-8622-c2e0fba7c660.png)
Do you want to turn that from gray to purple?

**Comment by OriginersMc** [comment]
You no understand me.

No execute command.

Writte on chat on server:
"Eiii, please send me /tpa and come with me"

This /tpa appear on chat writte on purple text

**Comment by lackoSK** [comment]
So you can use:

`match \/tpa
then replace /tpa|&d/tpa 
`

and it will find `/tpa` and replace it with `&d/tpa`

**Comment by OriginersMc** [comment]
Hi

Apply this replace to all commands writted on chat, not just for /tpa

**Comment by lackoSK** [comment]
`match (?!.*\/).+(\s)
 then replace (?!.*\/).+(\s)|&d(?!.*\/).+(\s)`

not sure if it will work test it

**Comment by OriginersMc** [comment]
I will check later

**Comment by OriginersMc** [comment]
Hi

I tried and not work, can you give other options? I added this on rules.txt
file.

**Comment by kangarko** [comment]
What about just

```
match \/tpa
then replace &d/tpa
```

**Comment by OriginersMc** [comment]
It work correctly.

How to apply for all commands?

**Comment by lackoSK** [comment]
Hello,

Use `(\/\w+)`

Sincerely,
Ladislav from MineAcademy.org

**Comment by OriginersMc** [comment]
I am not where I need add that?

match (\/\w+)
replace &5(\/\w+)

or how?

**Comment by JarFiles** [comment]
You need to do that in the commands.txt file located in the rules directory :)

**Comment by OriginersMc** [comment]
Hi

It don't apply for all commands, just /tpa.

[image: image.png]


How fix that?

I have the next rule on commands.txt:
match (\/\w+)
then replace &5(\/\w+)

**Comment by lackoSK** [comment]
Hello,

What did you write to chat.txt?

Sincerely,
Ladislav from MineAcademy.org

**Comment by OriginersMc** [comment]
It appear this:
[image: image.png]

**Comment by lackoSK** [comment]
I cant see the image sorry

**Comment by OriginersMc** [comment]
Appear
"(/w+) in purple instead command

**Comment by lackoSK** [comment]
Hello,

We will sort it out within a few versions. Thanks

Sincerely,
Ladislav from MineAcademy.org

**Comment by kangarko** [comment]
Hi there!

The closest we can help you get is using the following regex. It will replace the color of the message to pink and the reset it back to white after the command. Unfortunately the color message you had before the command cannot be restored.

![a](https://i.imgur.com/aBjPMie.png)

Matej
