### ISSUE TITLE
[Feature] Able to custom afk message from Essentials 

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#1664]
can i use custom afk message in the plugin?

**Comment by lackoSK** [comment]
Hello,

What do you mean? What AFK? We do nothing with AFK

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
![maxresdefault](https://user-images.githubusercontent.com/2604798/82257797-fbdda480-9958-11ea-9d33-4442ac2feece.jpg)

Default Essentials' afk message, i dont know how to format it :(

would be nice if ChatControl handle it if Essentials plugin installed right?

**Comment by lackoSK** [comment]
Hello,

That should be in Essentials' config files. We are not going to implement this feature. 
See https://wiki.mc-ess.net/wiki/Locale 

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
sure, but i can't use placeholders :'(

**Comment by kangarko** [comment]
@rErEaT you can just install PlaceholderAPI and use placeholders from there

**Comment by rErEaT** [comment]
@kangarko, PlaceholderAPI and EssentialsX isn't compatible :'(
So i think its wont work :/
