### ISSUE TITLE
[Feature] Single MessageRemove

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#1665]
Can you implement this plugin?
https://www.spigotmc.org/resources/messageremover.1400/

with permission, moderators allowed to remove a single message like this
![c75cbb952e918ebdef273947dc41b339dc033696](https://user-images.githubusercontent.com/2604798/82256060-fa5ead00-9955-11ea-845c-fe59aa8f940f.png)

It would be nice in this Premum plugin!

**Comment by lackoSK** [comment]
Hello,

This feature is planned. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
Oh, okay thanks a lot!
