### ISSUE TITLE
[Feature] BSkyblock island team channels

### ISSUE THREAD

**Issue by bartyrealms** [kangarko/ChatControl-Pro#1666]
Please add support for the BentoBox (BSkyblock, Acid Island, etc.) team channels.
https://www.spigotmc.org/resources/bentobox-bskyblock-acidisland-skygrid-caveblock-aoneblock.73261/

**Comment by lackoSK** [comment]
Hello,

Thank you for the suppression. 
We will consider implementing it to the ChatControl-Pro

Sincerely,
Ladislav from MineAcademy.org

**Comment by bartyrealms** [comment]
Why was this closed?
