### ISSUE TITLE
[Bug?] chc global command

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#1668]
global command doesn't work, it says try /chc ? to list commands.

Is it renamed?

**Comment by lackoSK** [comment]
Hello,

Try /chc bc (bungeechat) 

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
oh so there isn't a command what send a message like broadcaster? :(

**Comment by lackoSK** [comment]
do you mean /chc a ?

**Comment by rErEaT** [comment]
no i don't, i wanted to send a message with a command with the prefix what defined in broadcaster messages.

**Comment by rErEaT** [comment]
Ah sure, thanks i will change it :)

**Comment by rErEaT** [comment]
chc announce works well for me, but the {server_time_HH:mm:ss} placeholder not working :(

is it able to fix?
![kép](https://user-images.githubusercontent.com/2604798/82750345-d7962380-9daf-11ea-90be-67ca341dbd68.png)

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
Oh sorry, okay, thanks a lot :D
