### ISSUE TITLE
Factions role prefix formated with chatcontrol is not appaering

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#167]
Hi i just started to use chatcontrol formater with free factions, here the factions prefix role like "+" and similliar is not appaering, on chat i configured like this in chat.yml https://hastebin.com/pesefuxeya.pl

**Comment by kangarko** [comment]
The {prefix} variable from ChatControl only include the faction name itself. For more extended options, please install PlaceholderAPI and use variables from there.
