### ISSUE TITLE
[Feature] Whitespace

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#1672]
Hi!

I am using %server_date_HH:mm:ss% variable from placeholderapi.
This variable will say 11:15:32 but always with difference lenght what cames from font?!

Is it able to set to {server_date_HH:mm:ss+} for being the same length?
Or i have to report this to PlaceholderAPI? :(
Would be nice if you can implement a {whitespaces} variable what works everywhere

**Comment by lackoSK** [comment]
You have to ask a developer of that plugin (servetime) not sure what plugin it is.

**Comment by rErEaT** [comment]
its PlaceholderAPI's placeholder :(

**Comment by lackoSK** [comment]
Then contact them

**Comment by rErEaT** [comment]
Thanks, I opened an Issue at there :)

When you will release the new version of ChatControl Pro? :)

**Comment by lackoSK** [comment]
We are working on it :)
