### ISSUE TITLE
[Translate] messages_hu update!

### ISSUE THREAD

**Issue by foxi69** [kangarko/ChatControl-Pro#1673]
Link: https://www.dropbox.com/s/ei7gmuwa98nt03a/messages_hu.yml?dl=0

I have a question about this:
what does "ignoreSet" means?

Can you leave an example?

**Comment by JarFiles** [comment]
That's the set of messages which are ignored. Like 'swears' for all swear messages
![grafik](https://prodigysupport.team/img/u/uzFWkHt4jD.png)
(https://prodigysupport.team/img/u/uzFWkHt4jD.png)

**Comment by lackoSK** [comment]
Hello,

We are sorry this feature might create issues (we got reported) so I do not recommend you using it yet. We’ve recoeded it and even more simple version of this feature is coming within a few next updates. 

Also, thank you very much for Hungarian localization. Might I send you localization file from new ChatControl v9 so you can translate it for us? 

I hope you understand. Thank you very mzch. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by rErEaT** [comment]
@lackoSK yes if u send that file :)

**Comment by lackoSK** [comment]
Hello,

This will be prioritized. ChatIgnores will be available & recoded withing a few next previews of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
