### ISSUE TITLE
Toggling Swears

### ISSUE THREAD

**Issue by itzWebby1** [kangarko/ChatControl-Pro#1674]
I read the wiki on this located at https://github.com/kangarko/ChatControl-Pro/wiki/Chat-Ignorers

I was wondering if I could just leave the current rules as they are, making the needed changes to settings.yml and handlers.yml,  or would I need to change some stuff in the rules?

Also, what is the easiest way to disable swear filters for certain words that way some aren't blocked?

Thank you.

**Comment by lackoSK** [comment]
See https://github.com/kangarko/ChatControl-Pro/issues/1673
