### ISSUE TITLE
1.15.2: Reporting error_yaml.log

### ISSUE THREAD

**Issue by NovaPixell** [kangarko/ChatControl-Pro#1678]
Hi, in the file mentioned in the title, it is said to report these errors to you. Here, what is it about?
I also wanted to tell you that every now and then it happens that a user cannot write in chat giving a "Cannot send chat message" error, it is not a problem of permissions, after a few days he settles himself.

[error_yaml.log](https://github.com/kangarko/ChatControl-Pro/files/4707795/error_yaml.log)

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org
