### ISSUE TITLE
1.15.2: tell:* commands not spyable

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1679]
There's a few variants of the /tell,msg... command family that show up if you add ":" to the end.
![imagen](https://user-images.githubusercontent.com/6623704/83425942-bcba5380-a42e-11ea-8a73-490790039d0a.png)
Executing these variants completely avoids the personal messages from getting spied.

**Comment by lackoSK** [comment]
Hello,

That's being done by Minecraft belive. I will look into it but nothing guaranteed.

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
I already blocked minecraft's vanilla messaging.

And it can't be, because the reception message is formatted with chatcontrol.
![imagen](https://user-images.githubusercontent.com/6623704/83449089-4b40cc00-a453-11ea-8cb4-8ef51b710d25.png)

**Comment by lackoSK** [comment]
Hello,

Minecraft automatically adds commands. The mail label for CommandTell is **tell** and aliases are msg, t, whisper 

Minecraft **by its nature** adds maincommand: alias to tab-complete

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
yet for some reason you can't track the aliased command for spying (?)

**Comment by lackoSK** [comment]
Hello,

Not sure what you mean? Sorry. Can you explain it?

We cannot change tell:msg or tell:pm

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
You don't need to change them, just make sure they also can be spied with the /spy command

**Comment by lackoSK** [comment]
They are being spied? What version are your running?

**Comment by MithrandirCraft** [comment]
They are not being spied with the /spy command ._.
cc v. 8.6.6

**Comment by MithrandirCraft** [comment]
oops, wrong mention.

**Comment by lackoSK** [comment]
Hello,

Can I mark this as solved? @MithrandirCraft 

Sincerely,
Ladislav from MineAcademy.org

**Comment by MithrandirCraft** [comment]
The latest versions of CC seem to present a lot of changes. I'm actually kinda scared of updating, since my current installation is quite stable, so once I update, I can verify.

For now, if you think the issue is solved, it's ok if the ticket is closed.
