### ISSUE TITLE
Player tag color issue #2

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl-Pro#168]
Hi, I have seen an other issue about player tag color bug
Mine is a bit different, I would disable color option but when I set Color: '' or Color: none, it doesn't colorize the tagged name but it sets the sentence behind in white...
I have also noticed that it doesn't happen when the pseudo begin with a capital. I don't understand why it affects only player's name with minuscule at start (or when we don't write the capital).

Sorry for my bad english.

**Comment by kangarko** [comment]
I think I have resolved the issue. Please test 7.2.3

**Comment by dartasen** [comment]
Fixed !

**Comment by kangarko** [comment]
Super! :)
