### ISSUE TITLE
1.15.2: Players randomly placed into multiple write chat channels at a time.

### ISSUE THREAD

**Issue by bartyrealms** [kangarko/ChatControl-Pro#1680]
Some of my players are being put into multiple write channels when they are not allowed to in the settings. They are not running any commands to do this, it just seems to... happen?

![image](https://user-images.githubusercontent.com/42015460/83427004-09d20180-a3fe-11ea-90d5-2ebce8f83623.png)
![image](https://user-images.githubusercontent.com/42015460/83427024-0f2f4c00-a3fe-11ea-97af-2aa0340f0ae7.png)

No reliable way to reproduce this but it should not be happening.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4712199/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

In the next update, there will be only 1 channel you can write in meaning the issue should be fixed. We will keep this open until you will confirm it does not happen on the next version released. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org
