### ISSUE TITLE
Chat event priority is unclear [AdvancedBans+XProtect]

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl-Pro#1682]
Core: PaperMC-309 (MC-1.15.2)
AdvancedBans: latest
ChatControl: latest
Configs: default with fomatting turned on

Hello, I am running a server without a Bungee with AdvancedBans and ChatControl. And I cannot prevent players from using chat by mutting them. I decided to run some tests on test build with minimum plugins (Vault, LuckPerms, ChatControl, AdvancedBans). And I run all default configs.

So my issue is that whenever I enable chat formatting players can write into chat while being mutted. They get the message that they are mutted, but the message is still visible to everyone. Important to note that the message DOES NOT appear in console.

I managed to fix this by setting formatting priority to MONITOR (nothing else helped). However I am not sure how valid this solution is. I am very confused why AdvancedBans is not working out of box with ChatControl out of box and I don't know whether MONITOR priority may cause any problems in future. So it would be nice if you could look into this question/problem and explain what is going on under the hood. This information might be helpful for future users of ChatControl as well. Thank you.

**Comment by radiant-ai** [comment]
Ok. So now there IS a real problem. When I set formatting to MONITOR, suspected bot (from XProtect plugin) cannot pass captcha test, which is even more confusing for me, because AFAIC handler with _Monitor_ priority is always called at the very end.

**Comment by lackoSK** [comment]
Hello,

It's okay setting it to MONITOR. We need to let AdvancedBans cancel the ChatEvent before we format it.

Sincerely,
Ladislav from MineAcademy.org
