### ISSUE TITLE
mc 1.15.2 (tuinity): mentions in chat give error (capitalization?)

### ISSUE THREAD

**Issue by Aitnys** [kangarko/ChatControl-Pro#1683]
I have mentions set so it pings and colors the name. When players use wrong capitalization (caps when none are in the name or no caps when it should have one) I get errors in console ( https://pastebin.com/Q4LnTHv1 ), my ingame name is Aitnys, when people do aitnys it does the essentials chat setup(with the <>) , gives an error but it does play a sound and when they do Aitnys it plays the sound makes it green and no error. 

[cc.zip](https://github.com/kangarko/ChatControl-Pro/files/4719177/cc.zip)

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org

**Comment by Aitnys** [comment]
okey thanks for your reply

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Aitnys** [comment]
i think im going to wait until this function is actually in the plugin, or at least until its proven not to give too much other issues.

**Comment by lackoSK** [comment]
okay.
