### ISSUE TITLE
1.8.8: Error on startup with default configs

### ISSUE THREAD

**Issue by Shmeeb** [kangarko/ChatControl-Pro#1684]
https://pastebin.com/QEsSMCkr

This server is running Zephyrus version git-Zephyrus-0c72a7f (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

**Comment by lackoSK** [comment]
Hello,

Can you try using n normal spigot such as paper? It shouldn't happen here.

Sincerely,
Ladislav from MineAcademy.org
