### ISSUE TITLE
1.12.2 : Discord Staff Chat

### ISSUE THREAD

**Issue by bzigus** [kangarko/ChatControl-Pro#1685]
Hey! 

I'm trying to set up staff chat in discord. I have it set up so that the staff chat goes to discord, but the messaged that are sent in the discord channel end up being sent to all players, not just staff members. Staff chat is really just the Admin Chat feature btw. 

A couple images to help. 
In Game (staff member) - http://prntscr.com/su1gii
In Game (Non-staffmember) - http://prntscr.com/su1gwk
In Discord - http://prntscr.com/su1gsa

Here is the Chat Control Zip.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4733283/ChatControl.zip)

Hope you can help <3

**Comment by lackoSK** [comment]
Hello,

Please send over also DiscordSRV config.

Sincerely,
Ladislav from MineAcademy.org

**Comment by bzigus** [comment]
Here you go. I removed the Bot Token so no one can steal it :)
[config.zip](https://github.com/kangarko/ChatControl-Pro/files/4747497/config.zip)

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org
