### ISSUE TITLE
Wither rose deathmessage

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#1686]
A death due to the effect of a wither rose is not traced back to it, instead a death message from the wither is called. It would make some nice new death messages possible, if one could differentiate here.

```
  WITHER_ROSE:
    Message:
    - '&e{player} &7 got caught in a Venus flytrap'
```

ChatControl 8.6.6
Paper 1.15.2 - 227

**Comment by lackoSK** [comment]
Hello,

Sure thing! I think it would be better to recode death messages from scratch! We will do it within a few next previews of ChatControl-Pro 

Sincerely,
Ladislav from MineAcademy.org
