### ISSUE TITLE
1.15.2: Setup different prefixes for different servers?

### ISSUE THREAD

**Issue by memetrollsXD** [kangarko/ChatControl-Pro#1688]
Hi. I recently bought ChatControl Pro and I wanted to know how to setup a prefix for global chat

Let's say I have 3 different servers: lobby, survival, creative.

I want players who chat in creative to have a prefix, like [C] and so on.

Any idea on how to do this?

**Comment by lackoSK** [comment]
Hello,

You can go to formatting.yml and under format "Chat" add a new part of format or edit the old one.

Sincerely,
Ladislav from MineAcademy.org
