### ISSUE TITLE
/channel set <player> <channel> - Invalid arguments.

### ISSUE THREAD

**Issue by SilberRegen** [kangarko/ChatControl-Pro#169]
Server: CraftBukkit version git-Spigot-d4f98a3-4448a7e (MC: 1.11.2)
CHC: 7.2.0-BETA and 7.2.1-BETA

Example:
Channelname: example
Playername: SilberRegen
--> Command: /channel set SilberRegen example
Output: Invalid arguments. Type /channel help for help.

Is this broken, or did I miss something?

**Comment by kangarko** [comment]
There is no such command yet, it is under development. The help message in /ch ? is a debug leftover.
