### ISSUE TITLE
Paper version git-Paper-334: <center> not working in messages_en

### ISSUE THREAD

**Issue by Kirrasio** [kangarko/ChatControl-Pro#1690]
Inside messages_en under announcer, center is not is not working correctly, it simply shows as a text in game with /chc announce (message)

**Comment by lackoSK** [comment]
Hello,

Do you want to center /chc a **message** <-- this? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Kirrasio** [comment]
Yes

**Comment by lackoSK** [comment]
Hello,

It's not possible now but we have in plans to recode whole announcements system [will be a lot better] You can expect this mid-summer. 

Sincerely,
Ladislav from MineAcademy.org
