### ISSUE TITLE
Minecraft Version: Tabbing pushes console errors

### ISSUE THREAD

**Issue by Skipzy72** [kangarko/ChatControl-Pro#1691]
### How to ask questions or report a problem here?
**If you want to get your question answered quickly, please stick to those three rules:**

### 1 - Write your Minecraft version in the title:
Example: 1.14.3: My chat is not being formatted per-world
Chat control Tabbing error
### 2 - Be clear: What is your current situation, the desired situation, and your problem?
I need my chat to work both in 1.12.2 and 1.15.2 with no errors, I had seen a post you made saying that the plugin only supports paper spigot, which I have along with the most updated protocollib for packet control.

Paper-1.15.2
Protocol Lib - v4.5.1
Chat control pro - 8.6.6
### 3 - Upload your plugin's folder.

Right-click the folder and follow the instructions below. For macOS right-click and select "Compress"
I would like to do this privately if the issue persist.

Then simply drag and drop the ZIP file into the issue field.
https://pastebin.com/TvTyESfq
Thank you.

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org
