### ISSUE TITLE
1.15.2: Chat decoration menu doesn't work

### ISSUE THREAD

**Issue by mikesonchan** [kangarko/ChatControl-Pro#1692]
Player isn't able to change chat colors by using chat decoration menu. But color codes work fine.

https://www.youtube.com/watch?v=91cREQJrqmg

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4757165/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org
