### ISSUE TITLE
1.15.2: channels dont work

### ISSUE THREAD

**Issue by IIIVVIII** [kangarko/ChatControl-Pro#1694]
when Channels are True in Config and the file - data.json is present on plugin folder - then error:

> 11.06 10:41:23 [Server] INFO UUID of player __SD__ is b5562586-8a00-4de5-bc8d-db0a3ce82d66
> 11.06 10:41:23 [Server] INFO [RegionFile] Using Java 8 DirectByteBuffer cleanup method
> 11.06 10:41:24 [Server] ERROR Could not pass event PlayerJoinEvent to ChatControl v9.0.0-Preview1
> 11.06 10:41:24 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.mineacademy.chatcontrol.lib.chatcontrol.api.ChatControlChannelMode.global=WRITE
> 11.06 10:41:24 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at org.mineacademy.chatcontrol.lib.chatcontrol.api.ChatControlChannelMode.valueOf(SourceFile:13) ~[?:?]
> 11.06 10:41:24 [Server] INFO at org.mineacademy.chatcontrol.a.a(SourceFile:194) ~[?:?]
> 11.06 10:41:24 [Server] INFO at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
> 11.06 10:41:24 [Server] INFO at org.mineacademy.chatcontrol.a.<init>(SourceFile:194) ~[?:?]
> 11.06 10:41:24 [Server] INFO at org.mineacademy.chatcontrol.a.a(SourceFile:776) ~[?:?]
> 11.06 10:41:24 [Server] INFO at org.mineacademy.chatcontrol.a.a(SourceFile:762) ~[?:?]
> 11.06 10:41:24 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .Y.onJoin(SourceFile:104) ~[?:?]
> 11.06 10:41:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor108.execute(Unknown Source) ~[?:?]
> 11.06 10:41:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:238) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$0(PlayerList.java:175) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:343) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:140) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1344) ~[patched_1.15.2.jar:git-Paper-334]
> 11.06 10:41:24 [Multicraft] Skipped 6 lines due to rate limit (30/s)
> 11.06 10:41:24 [Server] WARN [ChatControl] Plugin ChatControl v9.0.0-Preview1 generated an exception while executing task 40

**Comment by IIIVVIII** [comment]
[error.log](https://github.com/kangarko/ChatControl-Pro/files/4762840/error.log)

**Comment by IIIVVIII** [comment]
fix it please! i payed !
but plugin dont work...

**Comment by malonnnn** [comment]
dont worry, he will fix it. If you need stable build, download the version just prior to v9

**Comment by JohnS19** [comment]
+1

**Comment by lackoSK** [comment]
Hello,

Sorted.

Sincerely,
Ladislav from MineAcademy.org
