### ISSUE TITLE
1.15.2: RU translate not work

### ISSUE THREAD

**Issue by IIIVVIII** [kangarko/ChatControl-Pro#1697]
When Locale: RU  in config - then error

11.06 18:32:21 [Server] WARN org.mineacademy.chatcontrol.final.nul. .bK: Report / Default messages_ru.yml lacks a String at 'Cannot.Newcomer_Command'
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .bb.a(SourceFile:56)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dD.i(SourceFile:1503)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dD.h(SourceFile:508)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dD.q(SourceFile:671)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.dl(SourceFile:335)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .ay.init(SourceFile:774)
11.06 18:32:21 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.06 18:32:21 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.06 18:32:21 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.06 18:32:21 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.b(SourceFile:197)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.a(SourceFile:166)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.d(SourceFile:148)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.a(SourceFile:40)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF$1.a(SourceFile:60)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dD.m(SourceFile:224)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.cX(SourceFile:231)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dB.a_(SourceFile:39)
11.06 18:32:21 [Server] WARN at org.mineacademy.chatcontrol.final.nul. .dF.a(SourceFile:84)

**Comment by lackoSK** [comment]
Hello,

Thank you, we will update our Russian translation.  

Sincerely,
Ladislav from MineAcademy.org
