### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by JamieSinn** [kangarko/ChatControl-Pro#17]
Is there an API available? 
I'd need to hook in and send messages as well as set prefixes etc.

See Herochat's api for an example of what I need.

**Comment by kangarko** [comment]
There's no API at the moment.
What exactly do you need. Please give me examples of implementation and I will consider adding it.

**Comment by JamieSinn** [comment]
```

You can find out information about channel-based messages by listening for a ChannelChatEvent. This custom event contains the message sender (a Chatter object), the channel the message is being sent to, the result of the messaging attempt (a Chatter.Result object), and the original Bukkit PlayerChatEvent that resulted in the ChannelChatEvent. If you change the channel the message is being sent to, you should call event.setResult(event.getSender().canSpeak(newChannel)) unless you want to ignore the normal checks before sending the message.

```

From herochat's bukkit dev page.

Specifically, I need the following

* A way to get a channel's messages, and edit them or resend to another channel.
* A way to send a message to a channel.
* A way to have tag formatting that can be replaced when a player chats.

**Comment by JamieSinn** [comment]
If this is too much, is it possible to just use the chat filtering part without using the chat channels and the related parts?

**Comment by kangarko** [comment]
* It's not too much :) Seems like I can implement a ChannelChatEvent, to which you can listen and act accordingly.

* Sending a message to a channel will be implemented from the console. Then, you will be able to manually execute a console command without the need of an API.

* I don't understand, what do you mean? You are able to catch AsyncPlayerChatEvent on a higher priority, after ChatControl, and furthermore edit the message to your likings.

But currently I have a very busy time, totally lack of any space for development honestly :/

**Comment by JamieSinn** [comment]
Ah, that sounds good, no ETA needed.

In regards to the question later on: Is it possible to use the chat filtering for curse words part of this plugin without using the chat channels and the rest of this plugin.

**Comment by kangarko** [comment]
Yes, you can turn off any part of the plugin except for rules, which also work with chat formatter disabled.

**Comment by kangarko** [comment]
@JamieSinn hello! I am sorry for the delay :(

Here is the API I currently implemented:

> me.kangarko.chatcontrol.api.ChannelAPI for manipulating with channels.
> The event 'ChatChannelEvent' allows you to modify the message, format, recipients, or get information regarding the channel or even cancel the message before it's sent out.

I think it will be sufficient for you. The release is scheduled this week. Let me know if you have any inquiries.

**Comment by JamieSinn** [comment]
Thanks! That should be great!
