### ISSUE TITLE
1.8.8: ChatControl 9.0.0 - Private Message not working

### ISSUE THREAD

**Issue by jj136975** [kangarko/ChatControl-Pro#1701]
Hey, using private messages is generating errors and not working on default config. Plugin used with paper 1.8.8. (NullPointerException)

**Comment by lackoSK** [comment]
Hello,

Please paste the error. Include your configs.

Sincerely,
Ladislav from MineAcademy.org

**Comment by jj136975** [comment]
I used a wrong settings.yml xD sry for that
