### ISSUE TITLE
1.15.2: ChatControl 9.0.0 - MySQL database is missing primary key field.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1702]
Paper dev 348 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1591793461

Looking at the ChatControl mySQL database directly in phpMyAdmin, I'm not able to edit any of the table entries. It specifies;

> Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.

The database is from ChatControl v8 and updated from v9. I'm trying to edit the Ignored_Players & Ignored_Sets ``[]`` entries to go back to ``{}`` since ChatControl complains when downgrading back to v8.

**Comment by lackoSK** [comment]
Hello,

Please reset the whole database. [ChatControl Table] Can you give it a try?

Sincerely,
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
Sure, I can try again later to see if it's added with a fresh database.. I just manually added a primary key to the uuid table for now to be able to edit the entries.

**Comment by lackoSK** [comment]
Hello,

Okay, let me know then. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
This is still an issue with fresh database tables on ChatControl v9.0.0-beta-3.

How it looks browsing the ChatControl_Data table. You can see I am unable to make any adjustments or edits.
![link1](https://i.imgur.com/9kn4PDP.png)
Table structure, no primary keys set. Generally most sql database tables from other plugins have a primary key set in the structure. Sometimes they make use of secondary index keys as well, but always a primary at the least.
![link2](https://i.imgur.com/StHJplA.png)

Forcing a primary key on the UUID table.
![link3](https://i.imgur.com/SHtHSug.png)
Can now make edits to the inserted player data.
![link4](https://i.imgur.com/dKAR52K.png)

**Comment by JavaFactoryDev** [comment]
Will be fixed until next release;)

**Comment by mibby** [comment]
Thank you, confirmed fixed as of 9.0.3-BETA.
