### ISSUE TITLE
1.12.2 Paper: ChatControl Pro Lag Server Version 

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/ChatControl-Pro#1703]
Can anyone tell me how to optimize the lag from chatcontrol:
https://gyazo.com/7eee38d69e1f77b2d77497cff05de1aa
https://timings.aikar.co/?id=9ea9ae673a5c419baa6bc5c1c7b5b981#plugins

**Comment by lackoSK** [comment]
Hello,

You can use a 9.0.0 preview or wait for a stable version. 

Sincerely,
Ladislav from MineAcademy.org
