### ISSUE TITLE
1.15.2: Channels cant write into

### ISSUE THREAD

**Issue by IIIVVIII** [kangarko/ChatControl-Pro#1704]
"9.0.0 BETA1"
When channels are True, and I`m Join to channel - i`m still can`t write into channels.

![image](https://user-images.githubusercontent.com/34328781/84544923-b45bf580-ad17-11ea-9877-cf430366b319.png)
![image](https://user-images.githubusercontent.com/34328781/84545043-eec59280-ad17-11ea-88fb-13a80b655d5e.png)

**Comment by EriolEandur** [comment]
I believe this to be the same problem: 
![grafik](https://user-images.githubusercontent.com/13347460/84566650-3b8a8700-ad73-11ea-8c0a-353c3b323e93.png)
Also command /ch send fails with this error.log:
`------------------------------------[ 13.06.2020 12:35:04 ]-----------------------------------
ChatControl 9.0.0-BETA-1 encountered a bK
Running Paper 1.15.2-R0.1-SNAPSHOT and Java 1.8.0_252
Plugins: HackedCore v2.26.0, LuckPerms v5.0.72, dynmap v3.0-beta-10-257, PlaceholderAPI v2.10.5, HackedServer v2.50.1, DynamicBooks v2.0-SNAPSHOT, ProtocolLib v4.5.0, The Multiverse-Core Plugin, MysqlInventoryBridge v2.3.2, MVdWPlaceholderAPI v3.0.1, FastAsyncWorldEdit v1.15.2, VoxelSniper v1.0.3-backward, React v6.618, Vault v1.7.2-b107, ServerListPlus v3.4.8, MyWarp v3.0-SNAPSHOT-MCME-01+unknown-b0.git-ba6568ab23, WorldEdit v1.15-256;e35a1b8, Essentials v2.17.2.0, WorldGuard v7.0.2-SNAPSHOT;bf2593e, DiscordSRV v1.18.4, MyBirthday v3.4.0-SNAPSHOT, EssentialsGeoIP v2.17.2.0, PluginUtils v1.3.2, Animations v1.2.3, PremiumVanish v2.5.11, TheGaffer v2.7.1, ChatControl v9.0.0-BETA-1, MCME-Architect v2.5.3, Tours v2.7.1, CommonerVote v1.2.9, MCME-Chat v1.5-SNAPSHOT, MiniGames v2.0.1, PlotBuild v1.2, McMeProject v3.7.1-SNAPSHOT, Guidebook v1.1.5, Perks v2.2, Environment v3.0, MCME-Editor v1.3.6, MCME-Connect v1.3-SNAPSHOT, AutoTeleport v1.2.4, MCME-Architect-Watcher v1.1, Votifier v2.6.0-SNAPSHOT, SuperbVote v0.5.4
----------------------------------------------------------------------------------------------

More Information: 
Unknown type of data: CraftPlayer{name=Eriol_Eandur} (CraftPlayer)
bK Report / Unknown type of data: CraftPlayer{name=Eriol_Eandur} (CraftPlayer)
	 at org.mineacademy.chatcontrol.final.nul. .aE.a(SourceFile:113)
	 at org.mineacademy.chatcontrol.final.nul. .aE.a(SourceFile:47)
	 at org.mineacademy.chatcontrol.final.nul. .aa.sendMessage(SourceFile:323)
	 at org.mineacademy.chatcontrol.final.nul. .p.c(SourceFile:41)
	 at org.mineacademy.chatcontrol.final.nul. .k.a(SourceFile:29)
	 at org.mineacademy.chatcontrol.final.nul. .bq.execute(SourceFile:344)
	 at org.mineacademy.chatcontrol.final.nul. .br$b.a(SourceFile:304)
	 at org.mineacademy.chatcontrol.final.nul. .bq.execute(SourceFile:344)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
----------------------------------------------------------------------------------------------`

**Comment by IIIVVIII** [comment]
the error is the same, but in my case the **/ ch send** command works.

![image](https://user-images.githubusercontent.com/34328781/84566890-371f9780-ad8e-11ea-833a-a60043aa0934.png)

**Comment by lackoSK** [comment]
Sorted.
