### ISSUE TITLE
1.14.4+ - ChatControl 9.0.0 - Could not pass event PlayerCommandPreprocessEvent to ChatControl

### ISSUE THREAD

**Issue by EnderGamingFilms** [kangarko/ChatControl-Pro#1705]
### Issue
(Mostly see pastebin) I am using the plugin EazyNick for adjusting players "displaynames, PlayerListName, and tag name", however, the player UUID stays the same and is not changed. Whenever the command /nick is run 100% of the time the error bellow appears. I have found that using ```yml vault-unsafe-lookups: true``` in the LuckPerms config will stop this error from appearing. I just wanted to bring this to your attention as a "possible bug".

### Console-Errors
https://pastebin.com/Z5nRTraj

### Plugins Causing This
[Luckperms](https://www.spigotmc.org/resources/luckperms.28140/)
[EazyNick](https://www.spigotmc.org/resources/eazynick-autonicksystem-api-src-bungeecord-multiworld-1-7-10-1-15-x.51398/)
[ChatControl-Pro](https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-15-2.10258/)

**Comment by lackoSK** [comment]
Sorted.
