### ISSUE TITLE
1.15.2: Swear from Discord channel

### ISSUE THREAD

**Issue by IIIVVIII** [kangarko/ChatControl-Pro#1707]
Hey Man!
i have a question!)

is it possible to configure swear protection in messages that come to chat from the Discord channel? at the moment, all the bad words coming from Discord are not obeyed by the rules ..

**Comment by lackoSK** [comment]
Implemented.

**Comment by IIIVVIII** [comment]
Implemented ? Where ?
messages from the Discord channel entering the game are not processed by
the rules
[image: image.png]

сб, 13 июн. 2020 г. в 18:14, Ladislav Proc <notifications@github.com>:
