### ISSUE TITLE
1.15.2: Smiles from Discord

### ISSUE THREAD

**Issue by IIIVVIII** [kangarko/ChatControl-Pro#1708]
9.0.0 Beta-1

Smiles from Discord looks like that..

![image](https://user-images.githubusercontent.com/34328781/84571401-4f9eaa80-adac-11ea-99a9-20a6a50c67d6.png)

**Comment by lackoSK** [comment]
Hello,

Are that emojis UTF-8? Don't think they are. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by IIIVVIII** [comment]
and where does utf-8?
I assume that the emoticons from the discord should be displayed un chat like this ": laughing:: relaxed:"

in DiscordSRV config 
![image](https://user-images.githubusercontent.com/34328781/84575195-cfd10a00-adc4-11ea-8759-4ee0a32a2401.png)

**Comment by lackoSK** [comment]
Hello,

Implemented. 
![image](https://user-images.githubusercontent.com/53174757/84634491-30119a00-aef2-11ea-9796-c149be9186a0.png)


Sincerely,
Ladislav from MineAcademy.org
