### ISSUE TITLE
Anti_Bot.Block_Signs_With_Same_Text does not allow multiple blank signs

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#171]
If the setting Anti_Bot.Block_Signs_With_Same_Text is true, players cannot place multiple signs with blank text.  These are used often when making mob farms or controlling water, so I think this should be allowed even if the setting is true.

**Comment by kangarko** [comment]
Thank you for reporting. This bug has been resolved and a fix will be available in the next release.
