### ISSUE TITLE
[How to make this] ?

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl-Pro#1710]
Hello. 

match (discord)
then warn &7Our discord is bla bla bla

Right? But i want to do is the user spells "¿Which is the discord of the server"? 

match (discord) + (which)

So if the line of the guy include those 2 words (no matter the order) the warn will be displayed, but i cant do that,.

**Comment by lackoSK** [comment]
Hello,

This should work fine: 
`(.* which)(.*discord)`

Sincerely,
Ladislav from MineAcademy.org
