### ISSUE TITLE
1.15.2: betta 2 bugs

### ISSUE THREAD

**Issue by IIIVVIII** [kangarko/ChatControl-Pro#1711]
**1. wrong permissions - channel.send**
![image](https://user-images.githubusercontent.com/34328781/84597339-bf7c6600-ae7c-11ea-82a5-df4a5d040d7a.png)

**2. when Discord "Add_Formatting: true or false"  - message from discord sends to chat with format from DiscordSRV, but not from CC.**
![image](https://user-images.githubusercontent.com/34328781/84597839-015adb80-ae80-11ea-9c7e-4e04b2d8c854.png)
**and error from console**
![image](https://user-images.githubusercontent.com/34328781/84597865-28b1a880-ae80-11ea-9262-3abf406ddbeb.png)

**3. rules for swearing don`t work in messages from discord**
![image](https://user-images.githubusercontent.com/34328781/84597946-a2499680-ae80-11ea-9942-4c837a1cb0df.png)

4.Range in Ranged channel don`t work. messages sends to all world. And notify is not sends that player is out of range.

5. when false -  player still can’t write to the chat until it moves
![image](https://user-images.githubusercontent.com/34328781/84598261-eb9ae580-ae82-11ea-9d4c-815c40fe76b8.png)

My Perms:
![image](https://user-images.githubusercontent.com/34328781/84598191-644d7200-ae82-11ea-98dd-f01a41696c00.png)
![image](https://user-images.githubusercontent.com/34328781/84598199-76c7ab80-ae82-11ea-8547-872201bd888c.png)

**Comment by lackoSK** [comment]
Hello,

1) Fixed.
2) Fixed, and works:
![image](https://user-images.githubusercontent.com/53174757/84630256-f9d11c00-aeeb-11ea-85ac-e2f8f6e71a66.png)
3) Works | Maybe you got a bypass?
![image](https://user-images.githubusercontent.com/53174757/84627979-1ff4bd00-aee8-11ea-91e1-2afdbc6918f0.png)
4) Added the message (check), Do you have the entire world enabled? 
5) Fixed.


Sincerely,
Ladislav from MineAcademy.org

**Comment by IIIVVIII** [comment]
where can i check for changes? beta3?

**Comment by IIIVVIII** [comment]
2. message **from discord** sends **to chat** with format from DiscordSRV, but not from CC.
![image](https://user-images.githubusercontent.com/34328781/84641264-37499f80-af14-11ea-9b56-9bb8baeb6e81.png)
And Error : 

> 15.06 14:25:42 [Server] ERROR [DiscordSRV] DiscordSRV API Listener org.mineacademy.chatcontrol.final.nul. .Q сгенерировал ошибку:
15.06 14:25:42 [Server] INFO java.lang.reflect.InvocationTargetException
15.06 14:25:42 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15.06 14:25:42 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

>15.06 14:25:42 [Server] INFO Caused by: java.lang.ClassCastException: org.mineacademy.chatcontrol.lib.fo.model.o cannot be cast to org.bukkit.entity.Player
15.06 14:25:42 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .aa.sendMessage(SourceFile:308)
15.06 14:25:42 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .Q.a(SourceFile:138)
15.06 14:25:42 [Server] INFO ... 24 more<

And if this error  -rules for swearing From Discord to Mincraft - don`t work too.
![image](https://user-images.githubusercontent.com/34328781/84642057-601e6480-af15-11ea-9061-22e59b0379cb.png)

**Comment by lackoSK** [comment]
Hello,

Have you tested this on beta 3?

Sincerely,
Ladislav from MineAcademy.org

**Comment by IIIVVIII** [comment]
Not yet, have not time now.. later i will test it necessarily
