### ISSUE TITLE
1.15.2: can't write to channels

### ISSUE THREAD

**Issue by EriolEandur** [kangarko/ChatControl-Pro#1713]
with ChatControl 9.0.0-BETA-2 I still can't write to channels. There are no errors in the console and **/ch send** command works fine
![grafik](https://user-images.githubusercontent.com/13347460/84605868-12681480-aea1-11ea-85a7-d2cc132aa061.png)
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4777332/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

Can you try to reset your data.json? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by EriolEandur** [comment]
Deleting data.json solved the problem. Thanks!
