### ISSUE TITLE
Togglepm on/off argument

### ISSUE THREAD

**Issue by marekvac** [kangarko/ChatControl-Pro#1714]
Hi, I have a question about command /togglepm, the command has only one argument, which is for specify the player. And I need to specify the state, like "_/togglepm player on_". Is possible to add this feature in next updates? I'm currently running ChC 8.6.6, because waiting on stable 9.0.0 version.

Thanks.

**Comment by lackoSK** [comment]
Hello,

Yes /togglepm [player] will work. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by TomLewis** [comment]
Bumping this old ticket as, I too need a `/togglepm <player> <on|off>` Specifically the on/off part.

https://github.com/PirateCraft/dev/issues/63

**Comment by kangarko** [comment]
Sounds good, will come with CHC 9
