### ISSUE TITLE
1.15.2: ChatControl 9.0.0-BETA-3 - No option to ignore replacement of emojis from discord chat sent in-game.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1716]
Paper dev 353 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0-BETA-3
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592237938

ChatControl 9.0.0-beta-3 added the integration discord setting ``Replace_Emojis_With_Raw``. Value true replaces emojis sent on discord with ``:name:``, whereas value false strips/removes the emoji being sent altogether but still sends a blank message.

I use the plugin EmojiChat to integrate emojis from discord to in-game with a resource pack. 
https://github.com/RadBuilder/EmojiChat
https://www.spigotmc.org/resources/emojichat.50955/

**I do not** want ChatControl to be stripping emojis from discord chat sent in-game. Please make false respect default behavior or add an option ``ignore``. 

This works fine with DiscordSRV and ChatControl v8.6.6.

**Comment by lackoSK** [comment]
Hello,

Now, if that plugin exists, it will not perform any action. Wait until the next update. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by mibby** [comment]
@lackoSK This is still broken as of ChatControl v9.0.1-BETA. 

``Replace_Emojis_With_Raw: false`` & ``Replace_Emojis_With_Raw: true`` both end up breaking emojis from discord sent in-game. It shows up as blank boxes.

![link1](https://i.imgur.com/anuNTiZ.png)
![link2](https://i.imgur.com/hKJNlEw.png)

**Comment by mibby** [comment]
ChatControl Pro 9.0.3-BETA
DiscordSRV-Build-1.19.1-SNAPSHOT-1594090513
EmojiChat v1.8.3

@lackoSK @JavaFactoryDev Still an issue as of 9.0.3-BETA. I **do not** want ChatControl to touch or even strip emojis from discord or from in-game being sent to discord. v8 does not have this problem.

As of 9.0.3-BETA, in-game emojis used are also being forwarded to Discord before they are replaced with EmojiChat, causing the chinese unicode to be sent.

Wrote in-game.
![linkaa](https://i.imgur.com/gF8TIH3.png)
What was sent to discord.
![linka](https://i.imgur.com/dtAxvO8.png)

Wrote on discord.
![linkb](https://i.imgur.com/Io9jTsz.png)
What was sent in-game.
![linkbb](https://i.imgur.com/2t14kxF.png)

**Comment by mibby** [comment]
Still an issue as of ChatControl 9.0.4. Please re-open the ticket.
