### ISSUE TITLE
1.15.2: ChatControl 9.0.0-BETA-3 - Forcefully sending "joined into bungee chat" message on first login.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1717]
Paper dev 353 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0-BETA-3
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592237938

First login to the server with a new database outputs this message to the client in-game.

```
You have automatically joined into bungee chat.
```

settings.yml
```
Bungee_Chat:
  #
  # Enable bungee chat for players after login automatically. They can turn it off with '/chc bc switch'
  #
  Enabled_By_Default: true
```

I do not want this message to occur as players do not know what Bungee is and I silently force it enabled to enact a forced global public chat across all servers. There is no setting or localization option to disable this.

**Comment by lackoSK** [comment]
Hello,

Added to localization. Wait for the next update.

Sincerely,
Ladislav from MineAcademy.org
