### ISSUE TITLE
1.15.2: ChatControl 9.0.0-BETA-3 - Unknown custom packed identifier: plugin:chatcontrol

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1718]
Paper dev 353 (Spigot 1.15.2)
Waterfall dev 346 (BungeeCord)
ChatControl-Pro v9.0.0-BETA-3
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592237938

In the client logs (.minecraft/logs/latest.log), ChatControl is spamming plugin channel messages whenever players chat.

```
[13:52:34] [main/WARN]: Unknown custom packed identifier: plugin:chatcontrol
```

Client log example.
https://paste.ubuntu.com/p/swzY4d9rsM/

This is presumably coming from BungeeControl when ChatControl's bungee chat is enabled by default, as messages are sent to BungeeCord for forwarding from public chat, discord chat, and admin chat. At the time of testing, only 1 server was online with bungee chat being enabled but also happens with both servers up.

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting this issue. I will try to solve it as soon as I can.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Is this issue still present in the newest ChatControl?

**Comment by JavaFactoryDev** [comment]
Please respond.

**Comment by mibby** [comment]
Were changes even made? This is related to messages being sent through BungeeCord with BungeeControl.
