### ISSUE TITLE
1.12.2: Players can use colors in messaging

### ISSUE THREAD

**Issue by Affixes** [kangarko/ChatControl-Pro#1719]
**Issue:**
All players can use color codes in messages sent via ChatControl using /tell or any of its aliases.

**Versions:**
```
> version
[23:46:37 INFO]: This server is running Paper version git-Paper-1605 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
> version chatcontrol
[23:46:43 INFO]: ChatControl version 9.0.0-BETA-2
[23:46:43 INFO]: Authors: kangarko and lackoSK
```

**Config:**
https://pastebin.com/raw/9u8DxaZf

**Example:**
![image](https://user-images.githubusercontent.com/12236423/84729885-137a6e00-af95-11ea-954d-e889ca19f048.png)

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting this issue. I will try to resolve it as soon as I can. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Will be fixed until next release.
