### ISSUE TITLE
1.15.2: Error in console

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#1721]
Found this error:
https://gist.github.com/MithrandirCraft/8ebfe9a3b5b8712dfc1c68223b008414
error.log
https://gist.github.com/MithrandirCraft/4006c242e2d83be2f36f47cbcdc8e914

**Comment by lackoSK** [comment]
Hello,

This issue is fixed in 9.0.0. 

Sincerely,
Ladislav from MineAcademy.org
