### ISSUE TITLE
1.15.2 - Spy command not does not log all messages

### ISSUE THREAD

**Issue by NovaPixell** [kangarko/ChatControl-Pro#1722]
Hi, yesterday I updated to the latest version of ChatControlPro. Which totally restored the config files. Now the Spy functionality of private messages only logs messages that are made only with "/tell, /t" and not with "/msg" which is the most used.
Can it be set or is it a bug?

**Comment by lackoSK** [comment]
Hello,

I'm just reviewing this issue and I do not have enough information. Can you add a little more detail to this ticket? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by NovaPixell** [comment]
Even with the latest version if a user executes "/msg USER hi, hello", this is not shown in the ChatControl "Spy" but only messages with "/tell"

**Comment by lackoSK** [comment]
Hello,

Works fine for me:
https://gyazo.com/70c156ebcb0c69db11abcd105ac0f791

Sincerely,
Ladislav from MineAcademy.org

**Comment by NovaPixell** [comment]
I have disabled the private message option managed by ChatControl. I set it up so that they use the default minecraft (which reads essentials) like the old version of chatcontrol

**Comment by lackoSK** [comment]
Hello,

What do you mean?

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Please respond.
