### ISSUE TITLE
1.12.2 Paper Case sensitive bug

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/ChatControl-Pro#1723]
How to make chat.txt not case-sensitive?
match hacker
id ServerHate32
then notify chatcontrol.notify.rulesalert &8[&7ID {ruleID}&8] &7{player}: &b&f{message}
then warn &c&lDo not hackusate! &7Use /report.
im trying to only detect hacker typed alone not hackerstest

**Comment by lackoSK** [comment]
Hello,

Here's regex you should use for improved matching:
`\b(h+(\W|\d|_)*a+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*e+(\W|\d|_)*r+(\W|\d|_)*)`

For case-sensitive we got a setting:
![image](https://user-images.githubusercontent.com/53174757/85130429-36c34880-b235-11ea-8ba7-e50aa3d2e423.png)


Sincerely,
Ladislav from MineAcademy.org
