### ISSUE TITLE
1.15.2 Not listening to Denizen Chat Trigger - Paper 345

### ISSUE THREAD

**Issue by Kirrasio** [kangarko/ChatControl-Pro#1725]
I am using denizen chat trigger for npcs, it's posting the user's replies in open chat when the user responds to the npcs.

I have tried different settings in Formatter_Priority: including Lowest, Normal, High, Highest and Monitor, each with a restart.

Version: ChatControl-9.0.1-BETA
Version: Denizen-1.1.4-b1710-REL.jar

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4806550/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

I don't think this is a ChatControl-Pro issue. You should contact Denizen team and ask them which priority to use. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Kirrasio** [comment]
I just had the old chat control version in before I opened this issue back when the priorities were 3 different priority settings and it was working fine on high. 
I reinstalled a fresh chatcontrol 8.6.6 and it's working fine, once I install the new beta version it stops working correctly. I also just fresh installed the beta version and it tried every one of the priority settings at https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities.
It says that denizen is supposed to be set to high.

It's definitely the new beta version.

**Comment by lackoSK** [comment]
Hello,

Can you add a little more detail to this ticket? What should it do, how should it work? 

PS: We got a new wiki... 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Kirrasio** [comment]
It is doubling up, once the npc hears the response it is supposed to not post it in chat.  Before it was silent in chat when talking to an npc, basically canceling the chat event.

**Comment by lackoSK** [comment]
Hello,

Okay, I will have a look. 

http://support.mineacademy.org/

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future.
We now need to focus on making ChatControl impeccable and fix any current bugs.

We will not add support for this plugin right now.

Feel free to re-suggest this feature in the future if you still have this problem
 
Regards
Leonhard from MineAcademy

**Comment by Kirrasio** [comment]
This wasn't a feature request. This is a bug that happened from the previous version to this version, it wasn't happening before beta dropped.
