### ISSUE TITLE
1.15.2: Error while receiving Bungee message with 9.0.1-BETA

### ISSUE THREAD

**Issue by EriolEandur** [kangarko/ChatControl-Pro#1726]
Hey, 
With channels enabled messages are not send from one serer to another via Bungee. At the console of the receiving server there is this error every time a message is received: 
https://pastebin.com/7PMNRH6x
At the Bungee proxy BungeeControl 3.0.0 is running.
Server is running paper-350
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4808588/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

I've done some changes meaning these issues should be fixed within the next release of ChatControl-Pro.

PS: I would like to ask you to test it properly. Thank you. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by EriolEandur** [comment]
Hey,
I tested ChatControl 9.0.2-BETA. Still sending messages from one server to another via Bungee (Waterfall build 357) is not working. 
There is now another error at the receiving server: [https://pastebin.com/YTS0MzFW](https://pastebin.com/YTS0MzFW)

**Comment by lackoSK** [comment]
Hello,

Can you set debug in settings.yml to [bungee] and send me the output? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by EriolEandur** [comment]
Hey,

Sending server: 
`[15:03:37 INFO]: [bungee] Server 'world' sent bungee message [plugin:chatcontrol, CHANNEL]: Eriol_Eandur, global, test,`
I double checked it ends with a comma ','
Receiving server:
`[15:03:37 INFO]: [bungee] Channel plugin:chatcontrol received CHANNEL message from world server.`
Which is directly followed by the error message in server console: [https://pastebin.com/nsz884yx](https://pastebin.com/nsz884yx)
[error.log](https://github.com/kangarko/ChatControl-Pro/files/4842291/error.log)

Thanks for your support
- Eriol

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
