### ISSUE TITLE
1.15.2: ChatControl 9.0.1-BETA - No placeholder variable to use discord nickname instead of discord username.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1728]
Paper dev 367 (Spigot 1.15.2)
Waterfall dev 348 (BungeeCord)
ChatControl-Pro v9.0.1-BETA
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592862790.

Discord formatting seems to use the player's discord account name instead of the server nickname they set. DiscordSRV by default generally uses the nickname instead of account name. 

discord.yml
```
Composition:
- Part: '&8<&7Discord&8> &7{player}: &f{message}'
```

Would it be possible to add a variable or setting to use the account nickname instead to match DiscordSRV behavior? This wasn't a problem with DiscordSRV and ChatControl v8.

I tried adding the PAPI DiscordSRV expansion (https://github.com/DiscordSRV/DiscordSRV-PlaceholderAPI-Expansion) but ChatControl's formatting does not register either ``%discordsrv_user_nickname%`` or ``{discordsrv_user_nickname}``.

**Comment by lackoSK** [comment]
Hello,

Can you try 9.0.2-BETA?

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Please respond.

**Comment by TheReverend403** [comment]
I'm also having this issue using 9.0.2-BETA on 1.16.1.

**Comment by JavaFactoryDev** [comment]
Thanks for sharing!

**Comment by JavaFactoryDev** [comment]
Can you please update to 9.0.4 and try again?

**Comment by TheReverend403** [comment]
Still not working. For reference, my format is

```
Composition:
- Part: '{discordsrv_user_nickname} &9» &r{message}'
```

**Comment by JavaFactoryDev** [comment]
We will rollback to 8.6.6, please tell us whether this still happens in the latest version.
