### ISSUE TITLE
1.15.2 JS-Engine evaluation bug

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1729]
### How to ask questions or report a problem here?
**If you want to get your question answered quickly, please stick to those three rules:**

### 1 - Write your Minecraft version in the title:
Example: 1.14.3: My chat is not being formatted per-world

### 2 - I began migrating my formatting.yml from the old chatcontrol into the new one's chat.yml.  I struggled at some differences and getting them to display as I wanted to, so I needed to /chc reload many times and check the results of what happened in chat.  Things were ALMOST how I wanted them until it took issue with verifying a second condition... I may or may not have gotten the formatting of that second condition set properly, but I'll never know since the next /chc reload resulted in it rejecting the file in its entirety... in fact, now even the chat.yml that came with the plugin isn't accepted anymore.  It errors at the very first use of "- Part" in the entire file... which appears before anything I've entered has been put in.   Errors again at "Condition: " later on when using my own file.  In any case I can't get past this now, this is beyond just tweaking my existing settings, the plugin is now permanently disabled since it can't even use the files it came with.

I've noticed that the very act of loading the files like chat.yml causes them to be changed on the disk: double quotes exchanged for single quotes... and occasionally it will wreck yaml formatting by adding or removing spaces where they are NOT SUPPOSED TO BE.  Please stop the plugin from making these sweeping changes to the files while loading them, or make it an option that we can have it do what we say instead of completely alter the meaning and intent of the code as it was written by formatting and producing completely different files... that aren't even readable by the plugin. 

### 3 - Upload your plugin's folder.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4816531/ChatControl.zip)

The chat.yml in the folder is the "default" that came with the plugin... but it may well have already been altered by chatcontrol simply trying to load it.  The one titled chat_theoneiwant.yml was almost entirely working until the last load it did, at the time before that it was only failing to verify the && part of the conditions I set, though I didn't get a chance to find out why not as it just stopped working at all once I got to that point.

**Comment by lackoSK** [comment]
Hello,

I will see what can we do about this. Thank you for reporting it.

Sincerely,
Ladislav from MineAcademy.org

**Comment by mrcoffee1026** [comment]
I was later instructed to do it here so this ticket is:
https://support.mineacademy.org/issues/plugins/servlet/desk/portal/3/CHC-96
I got sorta further along but still stuck.  It seems to just not be evaluating the items for the condition.  By that I mean {this_item} will be evaluated as this_item_value as it should be.. . but the entire condition is simply evaluated as "has any value" instead of this_item_value.  Like a character string of any length... present for a condition... will result in a condition being permanently met under all other existing conditions... regardless of what is part of the character string (a true statement, false statement, a numeric value, etc.). Conditional formatting cannot work this way since there isn't a way to assign a null or false value as the result of the condition.  Even the word "null" would be treated as a character string and the condition would again be met.  There would necessarily have to be some sort of keyword that provided different results like Condition: eval({something} == whatever) since it isn't taking the extra step to make the evaluation now.  However nothing is documented on how to do this and as far as I can tell, it's supposed to do this automatically.  Let me know, thanks.

**Comment by JavaFactoryDev** [comment]
Hi mrcoffee1026,

your issue with JavaScript should have been fixed.

Is there anything more left.

Regards
Leonhard from MineAcademy

**Comment by mrcoffee1026** [comment]
No this is still unresolved.  I see that they have changed the wiki slightly for the condition examples like this:
`Condition: "{luckperms_primary_group_name} === admin"`
 Instead of the original 
`Condition: "{luckperms_primary_group_name} == admin"`
but the behavior is identical now as before.  Even with the last beta release put today 9.0.3-BETA: double quotes are instantly replaced by single quotes when the plugin is loaded.  Anything present for "condition" appears to being treated as the value of a character string and so the actual contents of that string make no difference.  Specifying a condition creates a permanent condition of TRUE, which is also the default if no condition is provided, and so conditional formatting still does not work.

**Comment by mrcoffee1026** [comment]
Condition: 'false' or FALSE or null - with or without quotes... is also evaluated as TRUE, btw.

**Comment by JavaFactoryDev** [comment]
Okay thanks, it seems like something is wrong with the JavaScript engine.
We will find time and fix this.

**Comment by JavaFactoryDev** [comment]
We will rollback to 8.6.6, please tell us whether this still happens in the latest version.

**Comment by mrcoffee1026** [comment]
I have set up and used conditional formatting in the proguard 8.6.6 proguard download put out today, it works there although custom javascript variables do not, some other placeholders still do... trying to use papi's javascript for the missing ones still does not, doesn't seem to be any particular reason why other than that it's also javascript.  But yes it does properly evaluate conditions, and there seems to be a way of setting it up in an extremely similar way as to what v9 showed in the wiki, and it actually works since it doesn't auto replace double quotes with single quotes and reformat when the file is loaded, so the original intent is preserved.

**Comment by kangarko** [comment]
@mrcoffee1026 sorry for the delay, I am finally back

Still having the issue? If so just open a new ticket & test the latest ver :)

**Comment by mrcoffee1026** [comment]
Yes still having the same issue in ... while I downloaded 8.7.2 to test in when I type /chc it says it's 8.6.6, are you sure you uploaded the right one?

**Comment by kangarko** [comment]
Yes it says it is the right one:

![a](https://i.imgur.com/8NU3FqN.png)

Anyways, lets continue on there instead.
