### ISSUE TITLE
Sound_Notify color issue

### ISSUE THREAD

**Issue by Johandrex** [kangarko/ChatControl-Pro#173]
When a player mentions any online players username the text turns into white. I have set the "Color: ''" to ''. But the issue still occurs, using version 7.1.6, but also occurs on 7.2.1.

Sound_Notify:
  Enabled: true
  Notify_Only_When_Afk: false
  Notify_Only_If_Prefixed_With: none
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
  - reply
  - m
  Cooldown_Seconds: 10
  Color: ''

**Comment by dartasen** [comment]
Linked to #157 & #168

**Comment by kangarko** [comment]
I think I have resolved the issue. Please test 7.2.3.

**Comment by kangarko** [comment]
Closing, I believe it was fixed.

If not, please repost at https://github.com/kangarko/ChatControl-Pro/issues/157
