### ISSUE TITLE
1.15.2: ChatControl 9.0.1-BETA - Re-implement shortcuts for sending over Bungee if BungeeChat is disabled by default.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1732]
Paper dev 367 (Spigot 1.15.2)
Waterfall dev 348 (BungeeCord)
ChatControl-Pro v9.0.1-BETA
BungeeControl v3.0.0
DiscordSRV 1.19.1-SNAPSHOT-1592862790.

Can you re-implement the shortcut option to send messages over BungeeCord if BungeeChat is disabled by default? ChatControl v8 had an option to use ``Shortcut: '!'`` so you can talk privately (server only) and still send messages publicly (if needed) with the shortcut. 

An example use, this was used on my test server to keep testing chat private but still allow chat without having to constantly toggle back and forth.

**Comment by lackoSK** [comment]
Hello,

Please see https://support.mineacademy.org/wiki/display/CHC/Shortcuts

Sincerely,
Ladislav from MineAcademy.org
