### ISSUE TITLE
My folder doesnt have Formatting.yml it only has format file with chat.yml and other yml in there

### ISSUE THREAD

**Issue by HiMyNameIsBoxxy** [kangarko/ChatControl-Pro#1734]
### How to ask questions or report a problem here?
**If you want to get your question answered quickly, please stick to those three rules:**

### 1 - Write your Minecraft version in the title:
1.15.2

### 2 - Be clear: What is your current situation, the desired situation, and your problem?
My folder doesnt have Formatting.yml it only has format file with chat.yml and other yml in there

### 3 - Upload your plugin's folder.

Thank you.

**Comment by lackoSK** [comment]
Hello,

Please read the new documentation. http://support.mineacademy.org/

Ladislav
