### ISSUE TITLE
How can i make a kingdom chat (only for kingdom members)

### ISSUE THREAD

**Issue by TheKr1szTEN** [kangarko/ChatControl-Pro#1735]
We use the Xkingdoms plugin.
How can i make a custom k chat, or disable the formatting over the Xkingdoms, cuz chatcontrol duplicate the k chat message.

**Comment by lackoSK** [comment]
Hello,

It is not possible because plugin XKingdoms does not provide Developer PAI 

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future. Feel free to re-suggest this feature in the future if you still have this problem

Regards,
Leonhard from MineAcademy
