### ISSUE TITLE
Reply isnt good enough

### ISSUE THREAD

**Issue by TheKr1szTEN** [kangarko/ChatControl-Pro#1736]
mc: 1.15.2
ccp: last build

The reply is sent to the player i last wrote to, not to the one who last wrote to me. (no error message)

**Comment by lackoSK** [comment]
Hello,

I'm just reviewing this issue and I do not have enough information. Can you add a little more detail to this ticket? 

PS: "LAST BUILD" Is not a valid version

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Please respond.

**Comment by JavaFactoryDev** [comment]
Will be reopened once User replies.
