### ISSUE TITLE
I can't upload my own swearing list.

### ISSUE THREAD

**Issue by Mcdikmen** [kangarko/ChatControl-Pro#1738]
Hello,

I can't import my own swearing list. When im trying to upload my own list it gets me that problem:

https://prnt.sc/t7bkki
https://prnt.sc/t7bkn4
https://prnt.sc/t7bktf

And this is my swearing list:: https://hastebin.com/wofuvisila.css

Thank you.

**Comment by lackoSK** [comment]
Hello,

It failed because the file you are importing contains rules which are already specified. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Mcdikmen** [comment]
Thank you, it's solved.
