### ISSUE TITLE
1.15.2: How to pipe messages to specific chat channel?

### ISSUE THREAD

**Issue by collinP93** [kangarko/ChatControl-Pro#1739]
Hey there,
I’m wanting to pipe messages to certain channels.
For example:
Auto messages get sent to Info or Tips chanel so players that want to see them fine, if not then they can leave the channel.
Certain plugins such as events / VoteParty messages get sent to an event channel.
Have auctions sent to an auctions or trade channel.
Death messages could be sent to a casualties channel.

TLDR:
I want a way to clean up the chat by sending chat events to specified channels so if you want to see those join or leave the channels.

Thank you for reading and hope to hear something back soon!
Thank you for your time and have a nice day/night.

**Comment by lackoSK** [comment]
Hello,

So you want to send all the joins etc to specific channels? I don't think that's a good idea & feature. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by collinP93** [comment]
Hey there,
I was mostly referring to the things I detailed above and just as an example mentioned death messages.
I’m currently controlling join and leave messages through bungeecontrol, and I’ve seen this type of system on text based games where the chat gets flooded with auctions, trading, death announcements, Yvette notifications, and hints/tips.
In my experience, it is really annoying to have all those events going on in a active chat where you have to constantly scroll up to see what has been said so having the chat filtered into channels would be a great relief.
Thank you for reading, I hope to hear something back from you.
Thank you for your time and have a nice day.

**Comment by lackoSK** [comment]
Hello,

You can create a separate channel and send the messages to that channel. 

I really don't think this feature is usable for most people. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by collinP93** [comment]
Hey there,
Thank you for the reply. How might I go about doing that? Do I need to create a rule or is there something else I need to do?
Thank you for your time and hope to hear from you soon.
P.S I’m a visually impaired player where the chat is read out by the built-in Minecraft accessible screen reader. when the chat gets slammed with a bunch of messages, it’s hard to read and keep track of conversations.

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future.
We now need to focus on making ChatControl impeccable and fix any current bugs.
Feel free to re-suggest this feature in the future if you still have this problem
 
Regards
Leonhard from MineAcademy
