### ISSUE TITLE
bStats Folder

### ISSUE THREAD

**Issue by Johandrex** [kangarko/ChatControl-Pro#174]
I'm sick of having so many folders in my plugins folder, would be amazing if you could allow us to choose the location for the bStats integration or allow us to disable the integration + folder creation from ChatControl's settings.

**Comment by kangarko** [comment]
Hey,

I totally understand you. I am having tons of 'update', 'bStats', 'Metrics' folders like this on all of my servers. I would love to just remove them all as I have toggled most of the metric system off, and it's just wasting my time when I am updating plugins or simply looking for something, the folders are biased. The same goes with files like '.update-lock' and such at the root server directory. I am keeping an eye on a solution, and will let you know if I find one! For the time being it seems we just have to allow that one little folder to appear there, until a better solution is made. Thank you for your understanding and once again I wholeheartedly agree with this opinion.

Good luck with your server,
kangarko

**Comment by kangarko** [comment]
Closing for now. Feel free to write below if you have any questions.
