### ISSUE TITLE
Own hover placeholders on Java level

### ISSUE THREAD

**Issue by iamtheRichie** [kangarko/ChatControl-Pro#1740]
Hello

I think the function that you can show your item from the main hand in the chat with placeholders with the version 9.0.* to all players is great.

I would also like to display own hover messages in the chat with own values and items of players.

I could not find such a possibility in the Wiki or in the Item.yml file.

So I would like to see if you could use an event to change a placeholder into a hover element.  If you use a registered placeholder in a chat, an event will be executed which specifies the player and the placeholder and returns a TextComponent.

For example 
 
Public TextComponent onPlayerChat(PlayerChatPlaceholderEvent event) {}

The following values could be added:

- all items from the inventory that can be seen directly
- Player's account balance
- EXP of the player
- other values from other plugins

I find it very practical to be able to use such a possibility.

Sorry for my bad English.

Sincerely
Richie

**Comment by lackoSK** [comment]
Hello,

So you want us to add an event when a player uses variable from /variables?

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future. We are trying to make ChatControl-9.X.X impeccable at the moment and need to focus on this, not on adding more features.

Feel free to re-suggest this feature in the future if you still have this problem

Regards
Leonhard from MineAcademy
