### ISSUE TITLE
1.15.2: Duplicity chat in Bungeecord

### ISSUE THREAD

**Issue by Alexej3999** [kangarko/ChatControl-Pro#1741]
Hello, 

### 1 - Minecraft version 1.15.2:
Chat is duplicate messages in Bungeecord

### 2 - Problem: 
A few days ago, we uploaded the latest version of Chatcontrol to the server
(9.0.2 BETA)

We have such a minor problem: We have connected servers via bungeecord and the problem is that the messages are repeated in servers, we have changed the priority to MONITOR, but the messages are repeating again..

https://imgur.com/a/QfitsmO

I don't know if the bug is with server or in the plugin, or if it would be blocked by another plugin. 
Or must wait for the update ? ..

Thanks for the reply, have a nice day.

**Comment by lackoSK** [comment]
Hello,

I don't have such an issue. Can you please only ChatControl itself? (Remove other plugins)

Sincerely,
Ladislav from MineAcademy.org

**Comment by Alexej3999** [comment]
Solved, thank your for answer
