### ISSUE TITLE
1.16: Unable to disable "just chat formatting" in 9.0.2

### ISSUE THREAD

**Issue by Baterka** [kangarko/ChatControl-Pro#1743]
### How to ask questions or report a problem here?
I am wondering if in `9.0.2-BETA` there is any way to disable ONLY chat formatting like in `8.8.6`? I am using chat formatting from CMI and private message formatting from Chat Control, but as I see I can just disable all formatting or none...

Seems kinda downgrade for me from older version. I cannot use older version because I am on 1.16

**Comment by lackoSK** [comment]
Hello,

Just make the CMI event higher than the event in ChatControl.
![image](https://user-images.githubusercontent.com/53174757/86269932-bef90480-bbca-11ea-9240-1469d37a431d.png)

(settings.yml)

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Hey!
It seems like this issue is resolved, isn't it?

I will close it now. 
If you have further questions please let me know.

Regards,
Leonhard from MineAcademy
