### ISSUE TITLE
1.16.1 Error loading configuration in settings.yml -  Newcomer

### ISSUE THREAD

**Issue by Cryper** [kangarko/ChatControl-Pro#1745]
I tried to update from 1.15.2 to 1.16.1 . Worked fine with all Plugins but ChatControl makes some issue. 
I always get : 

```
Error loading configuration in settings.yml!
Problematic section: Newcomer
Problem: org.mineacademy.chatcontrol.final.nul. .bK: Report / Malformed configuration! Key 'Newcomer.Restrict_Seeing_Chat' in settings.yml must be Boolean but got MemorySection: 'MemorySection[path='Newcomer.Restrict_Seeing_Chat', root='YamlConfiguration']' (see below for more)
```

I started the server. Chatcontrol did a update from the settings.yml . Restarted the Server and suddenly this error appears :/

**Comment by lackoSK** [comment]
Hello,

Can you please send me your ChatControl folder?

Sincerely,
Ladislav from MineAcademy.org

**Comment by Cryper** [comment]
Yeah sure. Folder Download:
https://mega.nz/file/KEozGK6L#2GHRU6xzNjg9Gx0cWtEF5YEciMjt0rAaDHL459hDLeA

**Comment by lackoSK** [comment]
Hello,

It loaded up correctly with your configuration. 
Any steps / what to do to simulate this? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Cryper** [comment]
I didnt to anything. I just have some other Plugins running like CMi,TAB and more

**Comment by Cryper** [comment]
I dont know what happend. But now it works .. weird
