### ISSUE TITLE
How do I separate my chats?

### ISSUE THREAD

**Issue by v0v0v** [kangarko/ChatControl-Pro#1746]
How do I make local (ranged) and global (not ranged, with `!` prefix) on 9.0.2? For example, `!hello everyone` will be displayed to everyone and `hello nearby` will be displayed to players nearby.

**Comment by lackoSK** [comment]
Hello,

See https://support.mineacademy.org/wiki/m/view-rendered-page.action?abstractPageId=6389781

I will re-add the feature soon.

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Please reopen this if further questions occur.

Regards,
Leonhard from MineAcademy
