### ISSUE TITLE
Chat Color

### ISSUE THREAD

**Issue by bzigus** [kangarko/ChatControl-Pro#1747]
Hey, 

I have a quick question about chat color. How would I go about having staff members chat in different colors. 

Thanks,
Bug

**Comment by lackoSK** [comment]
Hey!

Just follow up on our Wikipedia. Here's the link  
https://support.mineacademy.org/wiki/display/CHC/Formatting+Groups

Best
Ladislav form MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Please reopen this, if further questions occur.

Regards,
Leonhard from MineAcademy

**Comment by bzigus** [comment]
Ok, so I just got around to trying this and testing properly, but now it doesn't want to link the groups up correctly. I've got the Manager group but it is displaying the Dev color code. :( http://prntscr.com/td104t
Here's what I got


`Composition:
- Part: '{pl_prefix+}'
  Hover:
  - '&9Player Information'
  - '&bRank: &7{player_group}'
  - ''
  - '&bVisit &9ironbornmc.buycraft.net to'
  - '&bbuy rank a rank.'
  Open_Url: https://ironbornmc.buycraft.net
- Part: '&7{display_name}'
  Hover:
  - '&7Click to message.'
  Suggest_Command: /msg {player_name}
- Part: ' {deluxetags_tag}'
- Part: '&8: '
- Part: '&e'
  Condition: '{luckperms_primary_group_name} === trainee'
- Part: '&6'
  Condition: '{luckperms_primary_group_name} === helper'
- Part: '&a'
  Condition: '{luckperms_primary_group_name} === mod'
- Part: '&2'
  Condition: '{luckperms_primary_group_name} === sr-mod'
- Part: '&b'
  Condition: '{luckperms_primary_group_name} === admin'
- Part: '&9'
  Condition: '{luckperms_primary_group_name} === manager'
- Part: '&c'
  Condition: '{luckperms_primary_group_name} === dev'

- Part: '{message}'`
