### ISSUE TITLE
1.16.1: Magic color code wont show

### ISSUE THREAD

**Issue by DragonPlays** [kangarko/ChatControl-Pro#1748]
ChatControl Pro version: 9.0.2-BETA
No matter what I have tried I cant seem to get the color code &k to work. I have even enabled all perms for colors and checked my formatting list. It wont show for my deluxe tags or when I type it in chat. All other codes and formats work tho. 
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4861487/ChatControl.zip)

Thank you.

**Comment by maaatthias** [comment]
Hey DragonPlays,

Thank you for reporting this issue here.
Could you give us an example, where the color-code doesn't work?

Regards
Matthias

**Comment by DragonPlays** [comment]
I have deluxe tags on witch a tag that has &k;&5Hero the &5 works just not &k to make the magic format same with if I type &k in chat. I wonder if the new update changed the way chat formats are?

**Comment by maaatthias** [comment]
Hi DragonPlays,

we have found your issue.
It is already fixed and waits to be released in the next version of ChatControl.

Regards,
Matthias
