### ISSUE TITLE
Lag - Possible Perm Issue?

### ISSUE THREAD

**Issue by braceyourself07** [kangarko/ChatControl-Pro#175]
I'm having an unusual issue that I don't think I've had in the past. I am unsure what changed, but some users had been reporting short lag spikes in the past several days. I looked and saw the [lag] entries in the server log and saw one recently and asked if it happened a few moments ago and they said 'yeah, and there it goes again'. Upon closer inspection, it's happening every time I talk... but not the general users on our server.

(my IGN is mikedmd and my alt account is braceyourself07)
14.03 21:11:10 [Server] INFO ChatControl [Lag] interactive chat took 110.527 ms
14.03 21:11:10 [Server] INFO [GLOBAL] mikedmd: .
14.03 21:11:28 [Server] INFO ChatControl [Lag] interactive chat took 150.298 ms
14.03 21:11:28 [Server] INFO [GLOBAL] mikedmd: test
14.03 21:11:42 [Server] INFO ChatControl [Lag] interactive chat took 149.414 ms
14.03 21:11:42 [Server] INFO [GLOBAL] mikedmd: hmm

14.03 21:27:08 [Server] INFO [GLOBAL] braceyourself07: well the good news is i found the cause of the lag spikes
14.03 21:27:14 [Server] INFO [GLOBAL] braceyourself07: the bad news it's whenever i talk :(
14.03 21:27:18 [Server] INFO [GLOBAL] braceyourself07: so i guess i won't talk anymore
14.03 21:27:28 [Server] INFO [GLOBAL] braceyourself07: doesn't seem to affect anyone else
14.03 21:27:40 [Server] INFO ChatControl [Lag] interactive chat took 145.615 ms
14.03 21:27:40 [Server] INFO [GLOBAL] mikedmd: test
14.03 21:27:43 [Server] INFO ChatControl [Lag] interactive chat took 111.764 ms
14.03 21:27:43 [Server] INFO [GLOBAL] mikedmd: test 2

mikedmd does have a staff rank and braceyourself07 is on a standard user rank. If I promote braceyourself07 to a staff rank, the lag spikes start.

The only ChatControl related permissions in a staff account are:
chatcontrol.notify.*
chatcontrol.channel.*
chatcontrol.commands.*
chatcontrol.chat.spy
chatcontrol.commands.clear
chatcontrol.commands.clear.console
chatcontrol.commands.clear.silent
chatcontrol.commands.fake
chatcontrol.commands.list
chatcontrol.commands.mute.anonymous
chatcontrol.commands.mute.silent
chatcontrol.commands.reload

Our server is usually populated by older players (teens/adults) and we don't have any of the filters turned on, or at least everything I could find is commented out in the rules folder. Is there anywhere I can look specifically to resolve this issue?

handles.yml is completely commented out
Everything in the /rules folder is commented out except the built in swastika rule.
settings.yml is https://hastebin.com/amoxobapec.php

We are on version 7.1.4 and I do plan to upgrade, but we have a large contest going on at the moment and I don't want to make any major plugin changes until it's over.

**Comment by braceyourself07** [comment]
I removed all chatcontrol perms except chatcontrol.commands.* (so staff could still /mute and reload, etc) and I still get the lag report in console.

**Comment by kangarko** [comment]
Hey, may I see your chat.yml? If you wish it private you can send it directly via PM on spigot.

Do you have coded custom variables ? Those are usually the cause. Just to test, set Variables.Custom_Enabled to false and see if it still occurs.

**Comment by braceyourself07** [comment]
Here is our chat.yml  https://hastebin.com/jagojevapu.php

I changed custom variables to false and did a /chc reload.  It didn't seem to make any difference.

On a positive note, during my testing I've asked the players to be aware if they see any lag spikes and they have reported no lag at all.  So this may only affect a couple of players that have poor connections.  Maybe 100-200ms isn't a big deal.  Just curious why I see it when staff talk but not others.

**Comment by kangarko** [comment]
Hey, thank you for providing all information. I was not able to reproduce it, using both 7.1.4 and a custom 7.2.3 as below:
![pic](https://i.imgur.com/NKHT9lCg.png)

I am not exactly sure what the root cause is, but it may be the player's connection delay. If there are not any actual lag spikes, you can just set the lag checker to a higher limit in settings.yml at Log_Lag_Over_Milis, for example to '250'.

**Comment by braceyourself07** [comment]
Ok, thanks for looking into it!

**Comment by kangarko** [comment]
Hey, no problem! Let me know if the lag starts to get over 200. I would highly advise to update to 7.2.4, which will be coming up shortly. I just tested that (early) version, the update process is autonomous, you'll only be required to change Static_Format to Format in chat.yml. There is no static formatter anymore, but I made a workaround for people like you having lots of static formatters, so you won't be required to rewrite them so many times. Also the lag message will be improved with the exact part of the formatter that is problematic.

**Comment by braceyourself07** [comment]
I upgraded to 7.2.4 as recommended.

17.03 23:43:53 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 126.273 ms

Still get the same lag messages and again only for staff but not regular players.  Looks like it's in the formatting component.

**Comment by kangarko** [comment]
Hey, could you please test the following, because I am interested to see which variable exactly causes the problem?

1) replacing {display_name} with {player} 
2) commenting out {pl_group}
3) replace {pl_prefix} with empty
4) replace {pl_suffix} with empty 

Please do only one step at the time and restart the server after each step. If you find the problematic variable please also post me how it look like on the player. Thank you!

This is the edited format after all four steps:
 ```yml
  BuildersRefuge_Format:    
    Parts:
      Prefix:
        Message: ""       
        Hover_Event:
          Action: SHOW_TEXT
          Values:
            - "&8*-----* &f{player} &8*-----*"
            #- "&7Membership&8: &b{pl_group} "      
      Player:
        Message: "&f{player}&f: "                 
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/tell {player} "
        Hover_Event:
          Action: SHOW_TEXT
          Values:
            - "&8IGN: &7{player}"            
      Suffix:
        Message: "{}"        
      Message:
        Message: "{message}"
```

**Comment by braceyourself07** [comment]
Got it... here are my results and it is interesting.  The one with the biggest impact on lag is 20-30ms from {display_name} in the JSON hover over the prefix.  As soon as I took that one out I didn't get any more lag messages so I lowered the threshold to 10ms just to see what the others were.  I'm using Essentials (nick/displayname) and LuckPerms (prefix)

Normal with nothing changed
18.03 07:40:42 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 124.545 ms
18.03 07:40:42 [Server] INFO [GLOBAL] mikedmd: so pardon if i spam

Without {display_name} from JSON Prefix Hover
18.03 07:43:23 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 100.92 ms
18.03 07:43:23 [Server] INFO [GLOBAL] mikedmd: .

Without {display_name} from Player but left it in Prefix
18.03 07:42:23 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 135.613 ms
18.03 07:42:23 [Server] INFO [GLOBAL] mikedmd: .

Without {display_name} and {pl_group}
18.03 07:44:40 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 99.054 ms
18.03 07:44:40 [Server] INFO [GLOBAL] mikedmd: testing

Without {display_name), {pl_prefix} and {display_name}
18.03 07:46:47 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 98.441 ms
18.03 07:46:47 [Server] INFO [GLOBAL] mikedmd: .

Without {pl_suffix} and {pl_prefix} and {display_name}
18.03 07:47:39 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 96.07 ms
18.03 07:47:39 [Server] INFO [GLOBAL] mikedmd: .

With all variables removed
18.03 07:48:55 [Server] INFO ChatControl [Lag] creating component [BuildersRefuge_Format] took 98.351 ms
18.03 07:48:55 [Server] INFO [GLOBAL] mikedmd: one more


So, since the {display_name} on mouse hover is not absolutely necessary, I'm going to remove that and it brings the average to under the 100ms threshold.  Amazing idea to check for those variable lookups.

**Comment by kangarko** [comment]
Just a quick idea that I have come up with:

The display name actually uses Bukkit method, and in praxis I am not really aware of what the difference is from just the {player} variable, because most plugin's that have nicknames just handle it their own way anyway. 

The problem may lie in that the UUID is resolved each time the {display_name} is called, while the {player} name is cached without any need for external resolving.

If you are having the same output using {display_name} and {player}, just use {player} :)
