### ISSUE TITLE
Important - This page will be closed soon, here is where to report issues

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#1751]
We have been working hard to developer our own, better portal for issues, help and documentation so that you can spend less time being frustrated and waiting for support, and spend more time enjoying the plugin and upgrading your server to the next level.

Having said that, we will be closing down GitHub in next 1-2 weeks or sooner. Check the link below to enter our new Support Portal, and anything you'd normally post to GitHub just post there instead.

https://support.mineacademy.org

Thanks
Matej

**Comment by JavaFactoryDev** [comment]
Please report new issues using support.mineacademy.org
