### ISSUE TITLE
1.12.2, 1.15.2 & 1.16.1: Dupe messages with discord relay enabled & bungeechat as default chat

### ISSUE THREAD

**Issue by ElBananaa** [kangarko/ChatControl-Pro#1752]
Hey! I open this as requested by a player since he doesn't know what he should write.

Basically, he uses bungeechat as default chat on his network, and he enabled Discord Relay. Here's the problem:
When someone sends a message from Mc to Discord, everything's fine, but when someone sends a message from Discord to Mc, messages are dupe.
CHC debug: https://pastebin.com/19HcuT2F
Screenshot of the issue: ![image](https://user-images.githubusercontent.com/53318613/86521107-bdd70a00-be4c-11ea-83ae-9d70d742ec8a.png)
[Chat_Control_Investigation.zip](https://github.com/kangarko/ChatControl-Pro/files/4873892/Chat_Control_Investigation.zip)

Have a great day, and thanks!

**Comment by JavaFactoryDev** [comment]
Hi!
thanks for reporting this issue;)
We will have a look tomorrow.

Regards
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Will will find time and fix this issue.

**Comment by JavaFactoryDev** [comment]
We will rollback to 8.6.6, please tell us whether this still happens in the latest version.
