### ISSUE TITLE
1.16.1: Can't open links in chat due to click event

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1753]
If you use a click event in private messages, for example so it triggers /r, you are unable to open any links that are sent within a private message. Is there anyway to except links so you can still open those?

**Comment by JavaFactoryDev** [comment]
Hi Sikatsu,

thanks for reporting this issue here.
Can you please further explain what you mean by links?

Regards,
Leonhard from MineAcademy

**Comment by Sikatsu** [comment]
A URL, for example a link to github. You can not open it anymore when you set a click event for private messages. ^^

**Comment by maaatthias** [comment]
Hey,
Could you send me the command and the version of ChatControl?
We played around with the latest version and couldn't find any issues so far.
I need more information to reproduce the issue.
Thank you.

Regards,
- Matthias from MineAcademy

**Comment by Sikatsu** [comment]
9.0.3-BETA, the private message commands like /msg, if you set a click event on it, you are no longer able to open links/urls that anyone send you.

**Comment by JavaFactoryDev** [comment]
Will be added to the next version;)

**Comment by sandwally** [comment]
9.0.4 version did not fix this.
Same happens in all formatting's that have **Suggest_command:** combined with **{message}** inside **-Part:**
Example with changed chat.yml to reproduce. https://pastebin.com/0Rk70V4Q

Workaround for the moment is to split your formating like this.
https://pastebin.com/f9sZ3ZyP

**Comment by EnTIv** [comment]
chatcontrol-9.0.3-BETA can lead to the same problem

**Comment by JavaFactoryDev** [comment]
We will rollback to 8.6.6, please tell us whether this still happens in the latest version.
