### ISSUE TITLE
1.16.1: CMI command spy support

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1754]
In version 8 of ChatControlPro, I was able to enter /mail so it would spy on those commands from CMI. When I do this in version 9, this no longer seems to work properly.

**Comment by JavaFactoryDev** [comment]
Hi!
Thanks so much for suggesting your feature/idea. We have carefully discussed it with our team and have concluded that, although interesting, it is at present, not a good fit nor we have the resources to add it in the near future.
We now need to focus on making ChatControl impeccable and fix any current bugs.
Feel free to re-suggest this feature in the future if you still have this problem
 
Regards
Leonhard from MineAcademy
