### ISSUE TITLE
Continuation of #1747

### ISSUE THREAD

**Issue by bzigus** [kangarko/ChatControl-Pro#1755]
I couldn't seem to open the ticket so I'm making a new one (https://github.com/kangarko/ChatControl-Pro/issues/1747)

Here is what I said in the other one 

Ok, so I just got around to trying this and testing properly, but now it doesn't want to link the groups up correctly. I've got the Manager group but it is displaying the Dev color code. :( http://prntscr.com/td104t
Here's what I got

`Composition:

Part: '{pl_prefix+}'
Hover:

'&9Player Information'
'&bRank: &7{player_group}'
''
'&bVisit &9ironbornmc.buycraft.net to'
'&bbuy rank a rank.'
Open_Url: https://ironbornmc.buycraft.net
Part: '&7{display_name}'
Hover:

'&7Click to message.'
Suggest_Command: /msg {player_name}
Part: ' {deluxetags_tag}'

Part: '&8: '

Part: '&e'
Condition: '{luckperms_primary_group_name} === trainee'

Part: '&6'
Condition: '{luckperms_primary_group_name} === helper'

Part: '&a'
Condition: '{luckperms_primary_group_name} === mod'

Part: '&2'
Condition: '{luckperms_primary_group_name} === sr-mod'

Part: '&b'
Condition: '{luckperms_primary_group_name} === admin'

Part: '&9'
Condition: '{luckperms_primary_group_name} === manager'

Part: '&c'
Condition: '{luckperms_primary_group_name} === dev'

Part: '{message}'`Ok, so I just got around to trying this and testing properly, but now it doesn't want to link the groups up correctly. I've got the Manager group but it is displaying the Dev color code. :( http://prntscr.com/td104t
Here's what I got

`Composition:

Part: '{pl_prefix+}'
Hover:

'&9Player Information'
'&bRank: &7{player_group}'
''
'&bVisit &9ironbornmc.buycraft.net to'
'&bbuy rank a rank.'
Open_Url: https://ironbornmc.buycraft.net
Part: '&7{display_name}'
Hover:

'&7Click to message.'
Suggest_Command: /msg {player_name}
Part: ' {deluxetags_tag}'

Part: '&8: '

Part: '&e'
Condition: '{luckperms_primary_group_name} === trainee'

Part: '&6'
Condition: '{luckperms_primary_group_name} === helper'

Part: '&a'
Condition: '{luckperms_primary_group_name} === mod'

Part: '&2'
Condition: '{luckperms_primary_group_name} === sr-mod'

Part: '&b'
Condition: '{luckperms_primary_group_name} === admin'

Part: '&9'
Condition: '{luckperms_primary_group_name} === manager'

Part: '&c'
Condition: '{luckperms_primary_group_name} === dev'

Part: '{message}'`

**Comment by JavaFactoryDev** [comment]
Please report new issues using support.mineacademy.org
