### ISSUE TITLE
Parrot can not be disabled

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#1756]
In `ChatControl/settings.yml`  I had:
` Parrot:
      Delay: 1 second
      Minimum_Similarity: 85%`

I changed it to:
` Parrot:
      Delay: 0 second
      Minimum_Similarity: 85%`

Players still get: `Someone else said that just recently`

Then I changed it to:
` Parrot:
      Delay: 0 second
      Minimum_Similarity: 25%`
But still same: `Someone else said that just recently`

How do I disable parrot completly?
![image](https://user-images.githubusercontent.com/18153673/86792971-492de680-c06b-11ea-9bda-1763ce3e13cb.png)

**Comment by JavaFactoryDev** [comment]
Please only report new issues using support.mineacademy.org.
