### ISSUE TITLE
1.16.1: onPacketSending looking up permissions on main server thread, luckperms does not like.

### ISSUE THREAD

**Issue by jakkuh** [kangarko/ChatControl-Pro#1758]
### 2 - Be clear: What is your current situation, the desired situation, and your problem?
https://pastebin.com/vfgEcQi7

onPacketSending looking up permissions on main server thread, luckperms does not like it.

Occurs when WorldGuard goes to send region farewell/greetings and ChatControl is catching the packet.

**Comment by jakkuh** [comment]
Note: Disabling "Check_Packets" fixes the error spam, likely because it is not checking those chat messages.

**Comment by JavaFactoryDev** [comment]
Hey, thanks for reporting this issue, but 1) It should have already been fixed in my dev build 2) Please use support.mineacademy.org to do so.
