### ISSUE TITLE
Paper 1.16.1- Chat_Formatting not disabling 

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#1759]
how do I disable chat format from this plugin completely? using paper 1.16.1 
```
Chat_Formatting:
  #
  # Enable chat formatting?
  #
  Enabled: false
```
^This apparently doesn't do it

<img width="349" alt="Annotation 2020-07-10 010740" src="https://user-images.githubusercontent.com/25316276/87124545-9a4a0000-c24e-11ea-9881-06517b4b9ace.png">

the hover message works fine without this plugin
This is without chatcontrol

<img width="116" alt="Annotation 2020-07-10 011741" src="https://user-images.githubusercontent.com/25316276/87124616-bb125580-c24e-11ea-82ef-35412fa80dc2.png">

Everything is default except Chat_formatting enable turned to false. 

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4901473/ChatControl.zip)
using v9.0.3-BETA

**Comment by JavaFactoryDev** [comment]
Please only report bugs using support.mineacademy.org.

**Comment by BobbyMere** [comment]
How do I post this on a website that requires an account if the account creation screen never loads?
