### ISSUE TITLE
Logging pm's

### ISSUE THREAD

**Issue by tbasten** [kangarko/ChatControl-Pro#176]
Hi, I can't seem to figure out why PM's aren't being logged. Can't see anything in the wiki or config files

**Comment by c0wg0d** [comment]
Since PMs are not part of the channel chat, they don't get logged.  I would LOVE to have this feature added, where it logs all PMs and /me or /action messages along with the rest of the chat, because digging through the server.log files specifically for chat messages is very tedious.

**Comment by kangarko** [comment]
There is a chat saver feature named Writer in settings.yml. You can save individual commands like PMs or any other.

![pic](https://i.imgur.com/FwEq3Ov.png)

**Comment by c0wg0d** [comment]
I have those options specified in my Writer.Write_Commands section but they do not get saved to the chat log file.  Is that because I am using Bungee mode?

**Comment by kangarko** [comment]
If those commands are from your bungee server, then yes, they can't be saved because are out of reach of bukkit.

**Comment by c0wg0d** [comment]
That's a bummer.

**Comment by kangarko** [comment]
Yes definitely. I would advise looking up some third party plugin that is specifically designed for that, on bungee. I have little knowledge because most of the years I was dedicated to Bukkit.
