### ISSUE TITLE
MinHow do I post this on a website that requires an account if the account creation screen never loads?ecraft Version: Your Issue Title

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#1763]
How do I post this on a website that requires an account if the account creation screen never loads?
<img width="758" alt="Annotation 2020-07-10 134253" src="https://user-images.githubusercontent.com/25316276/87188004-b338cc80-c2b3-11ea-95e4-daf1cfe0e8cb.png">

Loading going on 54minutes now

**Comment by andris155** [comment]
<img width="656" alt="Annotation 2020-07-11 160957" src="https://user-images.githubusercontent.com/8324198/87226060-9a9ee400-c391-11ea-891c-b50de2d5063e.png">

**Comment by andris155** [comment]
<img width="480" alt="Annotation 2020-07-11 161534" src="https://user-images.githubusercontent.com/8324198/87226079-c326de00-c391-11ea-8718-63f5abfe3520.png">

**Comment by andris155** [comment]
I don't know how to register to this site...

**Comment by JavaFactoryDev** [comment]
Please report this using our discord.
