### ISSUE TITLE
1.16.1: Not supported the EssentialsX RGB colored nick names Admin chat

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1764]
The ChatControl on 1.16.1 not supported the EssentialsX RGB colored nick names.

If set to /nick &#40FD30test my nickname the ChatControl this with black color. But this the green color.

<img width="185" alt="Annotation 2020-07-11 160957" src="https://user-images.githubusercontent.com/8324198/87225951-fc128300-c390-11ea-936e-928dbf205d8a.png">

**Comment by JavaFactoryDev** [comment]
Only report new issues using support.mineacademy.org.

**Comment by andris155** [comment]
support.mineacademy.org registration not work...
"Not a member? To request an account, please contact your Jira administrators."

**Comment by andris155** [comment]
I don't know who is the Jira administrator.
