### ISSUE TITLE
1.16.1: PlaceholderAPI failed to set ScriptEngine for javascript placeholder

### ISSUE THREAD

**Issue by EnTIv** [kangarko/ChatControl-Pro#1767]
![image](https://user-images.githubusercontent.com/38716516/87396741-ddf19080-c5e5-11ea-979e-e4cfc4f19a16.png)

ChatControl Pro: 9.0.4
PlaceholderAPI: 2.10.6

**Comment by JavaFactoryDev** [comment]
Please only report bugs using support.mineacademy.org & use the latest ChatControl version.
