### ISSUE TITLE
1.16.1: ChatControl PRO Formatting chat: Global and Local Chat Range-mode

### ISSUE THREAD

**Issue by VasilModerator** [kangarko/ChatControl-Pro#1768]
Hello, I have questions about setting up the ChatControl Pro plugin, whether it is possible to enable the range (range of local chat) in any chat format or not, I just need to divide the chat into local and global, but without the use of channels, and I I appeal to you because due to a new update (more precisely version of the plugin 9.0.4) of the plugin in which the plugin was rewritten from scratch the chat formatting system was changed and this function of activating the range (range of local chat) and version of the plugin 8.6 was removed. 6 is not supported on version 1.16.1 (I can't port it to 1.16.1 so this version is blacklisted for this plugin) is there a solution to this problem or not? I also posted two archived folders from the plugin version 8.6.6 and version 9.0.4, ie what was before and after, I hope that you will solve this problem because many people use this feature.
Thank you for your understanding.

[ChatControl - 8.6.6.zip](https://github.com/kangarko/ChatControl-Pro/files/4920284/ChatControl.-.8.6.6.zip)
[ChatControl - 9.0.4.zip](https://github.com/kangarko/ChatControl-Pro/files/4920302/ChatControl.-.9.0.4.zip)
![2020-07-14_21 54 00](https://user-images.githubusercontent.com/62768099/87464975-a94cfb80-c61c-11ea-9f06-725e5a54d692.png)
![2020-07-14_21 54 15](https://user-images.githubusercontent.com/62768099/87464983-ac47ec00-c61c-11ea-8093-7c705d9602d5.png)
https://github.com/kangarko/ChatControl-Pro/issues/1746

**Comment by JavaFactoryDev** [comment]
Please use 8.6.6 & report issues using support.mineacademy.org..

**Comment by JavaFactoryDev** [comment]
Please just use the latest 8.6.6 / 8.6.7 build. Both are working fine on 1.16.
