### ISSUE TITLE
Chat formatting seems not to work

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#177]
Hey there. Chat formatting seems not to work, I did everything I could've thought to do. Formatter.Enabled is true, formatter.format is in the right format, I even deleted essentialsX because I thought it was the issue because of essentials chat. I made a default permission for the default group and gave it out to default group but still the same result: http://i.imgur.com/sWR4AAO.png

**Comment by AndGK** [comment]
Vault was broken. Fixed by reinstalling it. But now I don't get it, how do I create suffixes for few groups? I need to create formatting for each group as I suppose? Or maybe there's easier method?

**Comment by kangarko** [comment]
Hey,

make sure you have **Variables.Vault.Multi_Prefix** and **Variables.Vault.Multi_Suffix** to **false**

**Comment by AndGK** [comment]
It was true, but I had to delete them and do it in my permissions plugin instead. Thanks anyways ^-^
