### ISSUE TITLE
Spigot 1.8.8-1.14.4 | "disconnect.spam" kicking players when typing commands too fast, not set up anywhere to kick players

### ISSUE THREAD

**Issue by RadiantNetwork** [kangarko/ChatControl-Pro#1770]
I don't have it set up anywhere in the chat control config or any other file in the folder to kick players. When typing commands quickly, it kicks the player for 'disconnect.spam'

Console:

15.07 05:16:09 [Disconnect] User IceNinja has disconnected, reason: disconnect.spam
15.07 05:16:09 [Server] WARN handleDisconnection() called twice

How do I disable this?

Is this even chat control doing the kicking? This is the only chat plugin I have on this server. 

Thank you for your time and help!

**Comment by JavaFactoryDev** [comment]
Please use 8.6.6 & report issues using support.mineacademy.org..
