### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by kangolist** [kangarko/ChatControl-Pro#1772]
`# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 16.07.2020 00:52:45
#  to ChatControl 9.0.4
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologize.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the chatcontrol-9.0.4.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/ChatControl/wiki
# 
# -------------------------------------------------------------------------------------------

Composition:
- Part: '{pl_prefix+}'
  Sender_Permission: chatprefix.membru
  Hover:
  - '&6Informatii jucator'
  - ''
  - '&9Grad : &6{player_group}'
  - '&9Discord : &ediscord.blazecraft.ro'
  - '&9Store : &estore.blazecraft.ro'
  - ''
  - '&9Timp online : &e{statistic_time_played}'
  Open_Url: https://store.blazecraft.ro
- Part: '{player_name}'
  Hover:
  - '&7Click pentru a trimite mesaj.'
  Suggest_Command: '/msg {player_name} '
- Part: '&7: &f{message}'

Composition:
- Part: '{pl_prefix+}'
  Hover:
  - '&6Informatii jucator'
  - ''
  - '&9Grad : &6{player_group}'
  - '&9Discord : &ediscord.blazecraft.ro'
  - '&9Magazin : &estore.blazecraft.ro'
  - ''
  - '&9Timp online : &e{statistic_time_played}'
  Open_Url: https://store.blazecraft.ro
- Part: '{player_name}'
  Hover:
  - '&7Click pentru a trimite mesaj.'
  Suggest_Command: '/msg {player_name} '
- Part: '&7: &f{message}'
Formats:
- Part: '&6VIP &r{pl_prefix}'
  Sender_Permission: chatprefix.vip
  Hover:
  - '&6Informatii jucator'
  Open_Url: https://store.blazecraft.ro
`

I have a question, How do I add multiple consecutive ranks? but i dont understand how...
Can u me please a link to an example with more rank, how is it in the video below?

https://www.youtube.com/watch?v=_1faSHTJdug&t=219s

**Comment by JavaFactoryDev** [comment]
Please use 8.6.6 & report issues using support.mineacademy.org, this is for legacy purposes only.
