### ISSUE TITLE
1.15.2: Messages are not sent via bungee when channels are enabled

### ISSUE THREAD

**Issue by EriolEandur** [kangarko/ChatControl-Pro#1774]
Hey,
I get an error in  the bungee proxy when trying to send messages via bungee in global channel:
[https://pastebin.com/A63CffGv](https://pastebin.com/xwCWsD2p)

I'm using BungeeControl-3.0.0 at waterfall-357 proxy and ChatControl-9.0.4 at paper-350 servers.

ChatControl folder:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4962738/ChatControl.zip)

Thanks for your support.
-Eriol

**Comment by JavaFactoryDev** [comment]
Hi,

Thanks for being kind and trying to report an issue here.
this repository is for legacy purposes only. Please use support.mineacademy.org.

P.S. 9.X releases are deprecated, please only use 8.X ones. More information on our discord.

If you have any more questions please just ask me.

Regards,
- Leonhard

**Comment by EriolEandur** [comment]
Ah ok. I missed that info before. Thanks.
