### ISSUE TITLE
1.15.2 paper 378 - Spy is logging with bypass enabled

### ISSUE THREAD

**Issue by Kirrasio** [kangarko/ChatControl-Pro#1775]
Spy bypass isn't working and is logging on /spy with the permission node to prevent it.

Example:
Added the permission chatcontrol.bypass.spy to admin rank, added permission chatcontrol.command.spy to helper rank, helper ranks can still see admin's private messages.

**Comment by JavaFactoryDev** [comment]
This is issue section is for legacy purposes only. Use support.mineacademy.org to report issues.
