### ISSUE TITLE
9.0.4 not working with placeholder API 2.10.7

### ISSUE THREAD

**Issue by trickman325** [kangarko/ChatControl-Pro#1776]
CC version 9.0.4 - running Paperspigot (128) 1.16.1

Does not work with PlaceholderAPI 2.10.7
Spams console with this
https://pastebin.com/UYh9P8R9

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5002838/ChatControl.zip)

**Comment by andris155** [comment]
Same problem.

**Comment by JavaFactoryDev** [comment]
Hi,

ChatControl 9.X is deprecated, please only use 8.6.8. 2) This page is for legacy purposes only. Please use support.mineacademy.org.

Regards
Leonhard

**Comment by poma123** [comment]
> please only use 8.6.8.

There is no such a version. 
![image](https://user-images.githubusercontent.com/25465545/89045025-1b2a8200-d34b-11ea-8a9d-2fe85614247e.png)

And 9.0.4 is the latest version, why is it deprecated???

**Comment by andris155** [comment]
8.6.6 not work with 1.16.1...
<img width="485" alt="Annotation 2020-07-31 164024" src="https://user-images.githubusercontent.com/8324198/89045905-9476a480-d34c-11ea-86a7-2a2d3389b3f5.png">

**Comment by JavaFactoryDev** [comment]
The updated 8.6.6 is working with 1.16. Please join our discord & download
the dev builds.

Am Fr., 31. Juli 2020 um 16:41 Uhr schrieb András Marczinkó <
notifications@github.com>:
