### ISSUE TITLE
1.16.1: chc 8.6.8 java.lang.IllegalAccessError on start up

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1777]
This error in the log on startup prevents chatcontrol pro from starting with the server:
https://pastebin.com/SDd7YjJR

Paper-131
[11:42:43 INFO]: This server is running Paper version git-Paper-131 (MC: 1.16.1)
 (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[11:42:43 INFO]: Checking version, please wait...
[11:42:44 INFO]: Previous version: git-Paper-128 (MC: 1.16.1)
[11:42:44 INFO]: You are running the latest version

**Comment by mrcoffee1026** [comment]
This persists with the version placed on spigot 8.6.8.  While the file size is different the error is identical and chatcontrol will simply not load.  Entire folder included if this is helpful
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5012550/ChatControl.zip)

**Comment by JavaFactoryDev** [comment]
Hi,

This is very weird because it works well for me and others. Which version of java are you using?

Regards,
- Leonhard

**Comment by mrcoffee1026** [comment]
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Comment by mrcoffee1026** [comment]
AH! Seems to load if I remove punishcontrol.

**Comment by JavaFactoryDev** [comment]
Okay, then we can fix it:) Thanks for the hint.

**Comment by JavaFactoryDev** [comment]
Should be fixed with ChatControl 8.6.9.

**Comment by mrcoffee1026** [comment]
awesome, thanks!

**Comment by mrcoffee1026** [comment]
This seems ok for chatcontrol, but now punishcontrol hangs on startup so the server can't finish loading up, i'll just have to keep PC disabled for now.

**Comment by kangarko** [comment]
@mrcoffee1026 apology for the mess recently. There will be another release soon, I will test it and ensure it works together with PunishControl but just let us know if you spot anything, here, on GitHub.

**Comment by mrcoffee1026** [comment]
Will do of course, thanks so much!

**Comment by JavaFactoryDev** [comment]
Hi it works fine for me.
https://ibb.co/gmZN21B

Regards,
Leonhard

Am Di., 4. Aug. 2020 um 13:46 Uhr schrieb mrcoffee1026 <
notifications@github.com>:

**Comment by mrcoffee1026** [comment]
In your example here, Punish Control loaded first.  On my server, ChatControl loaded first... it never gets passed the large text intro on PunishControl, nothing is printed to console past that last line of character art.

**Comment by JavaFactoryDev** [comment]
Can you ensure to use the latest version of PunishControl & delete the
punishcontrol folder?

Am Di., 4. Aug. 2020 um 14:05 Uhr schrieb mrcoffee1026 <
notifications@github.com>:

**Comment by JavaFactoryDev** [comment]
Just tested with the latest jar files.
https://ibb.co/k2KQjgx

Am Di., 4. Aug. 2020 um 14:06 Uhr schrieb Leonhard Solbach <
javafactorydev@gmail.com>:

**Comment by mrcoffee1026** [comment]
worked after i deleted the folder and tried again.  Thanks!
