### ISSUE TITLE
1.16.1 RGB Spy Colors 8.6.7

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/ChatControl-Pro#1778]
The rgb colors from 1.16 do not work on the mcmmo spy messages.
![image](https://user-images.githubusercontent.com/42933023/89128841-21faf580-d501-11ea-9be9-484fbfe78ff5.png)

**Comment by JavaFactoryDev** [comment]
Hi,

thanks for reporting this, we can schedule a time to fix it.

Regards,
Leonhard

**Comment by kangarko** [comment]
Hi, the 8.x.x branch does not have a support for RGB, so I put it into the to-do list above. I cannot guarantee any ETA due to recent constrains on our team, but it will get done.

Thanks.

**Comment by Sikatsu** [comment]
v8 actually does support RGB, using {#RRGGBB}.
I think the problem here is that the wrong format is being used.

@kangarko

**Comment by LucidAPs** [comment]
RGB works fine in all other aspects of the plugin but for the mcmmo spy messages we get this error. This is definitely an issue!

**Comment by Sikatsu** [comment]
I think that is because the formatting used there is different from what ChatControl uses. Since I use {#RRGGBB} everywhere, I don't seem to have this issue..
