### ISSUE TITLE
1.16.1: Hexcodes in /chc color

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1781]
Hey, would it be possible to add hexcode support in /chc color?

For example a anvil/sign in /chc color, when you click on it you can enter a hexcode {#RRGGBB} in the chat, which will then save in the database so you keep talking in that specific color.

**Comment by JavaFactoryDev** [comment]
Hi,

thanks for suggesting this here, it seems like a great improvement.

Regards,
- Leonhard

**Comment by kangarko** [comment]
Thanks, already pulled to the roadmap.

**Comment by Sikatsu** [comment]
I don't actually see it on there though

**Comment by kangarko** [comment]
See under: "RGB Spy Colors #1778"

**Comment by Sikatsu** [comment]
It's about RGB not parsing in mcmmo spy messages, this is a feature request for /chc color, just hoping the feature request won't be forgotten now it's closed

**Comment by kangarko** [comment]
Thanks, added it there explicitly. Right now it is definitely not a priority. We must get the plugin up to a bare usable minimum which it isn't. Then we'll provide stability patches and then features, thanks.

**Comment by Sikatsu** [comment]
I understand that, though now you changed the line to say the same twice.

![image](https://user-images.githubusercontent.com/5664135/89294506-e4f94500-d65f-11ea-91cb-35da9bf96059.png)

Think it should be:

- Fix RGB colors not parsing in mcmmo spy
- Add support for hexcodes in /chc color

They are two completely different things haha

**Comment by kangarko** [comment]
Damn, thanks, fixed.
