### ISSUE TITLE
Minecraft Version: Player Join Cause Server LagSpike

### ISSUE THREAD

**Issue by lulu2002** [kangarko/ChatControl-Pro#1785]
![image](https://user-images.githubusercontent.com/41278925/89141779-27dfed80-d578-11ea-9dde-974acb4d3035.png)
![image](https://user-images.githubusercontent.com/41278925/89141801-3928fa00-d578-11ea-8b92-0eb3d821ca73.png)
![image](https://user-images.githubusercontent.com/41278925/89141821-4d6cf700-d578-11ea-8bd2-2abd5358980a.png)

**Comment by JavaFactoryDev** [comment]
Hi, thanks for reporting this.
We will improve this in future versions.

**Comment by Sikatsu** [comment]
I upvote this one, also seem to have the same in my timings!

**Comment by kangarko** [comment]
The 8.x.x branch was unfortunately poorly done, I apology for this mistake. That was a long-standing issue I can remember back from 2019 already.

I decided to focus my efforts on getting the 9.x.x back up quickly and stabily.

The 8th generation will only receive security patches and bug fixes until then.

Thanks
Matej

**Comment by lulu2002** [comment]
Actually, I have reported this problem before, and it got fixed, I don't know why this issue happens again.. (https://imgur.com/a/IbIa8eo)

By the way, this issue doesn't exist in version 8.6.4, I hope you can take look at it, thanks.

**Comment by kangarko** [comment]
Got it, well the problem was that the developer implemented some "async" mechanisms unfortunately which resulted in a lot of other issues so I just reverted it back onto the main thread. Leaving open. Will have a look in a few days.
