### ISSUE TITLE
1.16.1: RGB Formatting with &#RRGGBB

### ISSUE THREAD

**Issue by benedictr** [kangarko/ChatControl-Pro#1786]
Will the `&#RRGGBB` colour format be supported in the (near) future? It seems to be either the main formatting convention in many other plugins (e.g. Essentials) or at least supported in plugins that use other formatting conventions. This is causing compatibility errors for me in the currently, specifically with using prefixes not being rendered correctly in other plugins. This is a great shame, as I love ChatControlPro otherwise and have had no other issues so far!

Many thanks

**Comment by JavaFactoryDev** [comment]
Hi,

thanks for your great feedback. RGB colors are already supported in the latest ChatControl version.

Regards,
Leonhard

**Comment by benedictr** [comment]
Hi,

Sorry if this wasn't clear - RGB is working absolutely fine for me using `{#RRGGBB}`, but this only works inside of ChatControl-handled plugins and messages etc. It appears this does not work in any other plugins that I am using. For example, I am using `{#RRGGBB}` in LuckPerms for my role prefixes, but this then does not translate to any other plugins that use the LuckPerms prefix or placeholder (e.g. my tab list plugin).

As a way to make this compatible with most other 1.16-supported plugins, is it at all possible for `&#RRGGBB` to be useable in ChatControl, even if not the default/recommended way of using RGB, as this seems to be the main way plugins are handling it?

Many thanks.

**Comment by Sikatsu** [comment]
It's actually odd most of your plugins use &#RRGGBB, as most of mine use {#RRGGBB}. More of the bigger ones like CMI and SuperTrails even use that. The code I provided Leonhard uses {#RRGGBB} however, it shouldn't be hard to support more then one format.

**Comment by benedictr** [comment]
Oh, that's weird. I know EssentialsX uses `&#RRGGBB`, and to be honest, that's probably the biggest example I found I had an issue with, but also with other plugins. BungeeTabListPlus for example uses `[color=#RRGGBB]' which is probably the weirdest I've seen so far, but they did later add in support for other formats such as `&#RRGGBB`.

I think the difficulty is that there is no 'standard' way of doing it, and frustratingly, plugin developers have different ways of doing it - this is no reflection on the plugin developers at all though!

It would be great though if CHC could support more formats, because as a chat plugin, the likelihood of it needing to parse a number of different formats appears to be becoming common!

As a side-note, I just want to say a massive thank you to the developers of ChatControl at the moment - it takes big guts to pull a major release like you did with v9, and I know it can't be easy to be where you are right now! I look forward to seeing the plugin develop into the future, and I've been super happy with it so far! 😄

**Comment by kangarko** [comment]
Thanks for the support! While adding cosmetic fixes such as colors is not on my/out plate right now (since it is full), we will definitely cover this in all places of the plugin after we put CHC back to stability again.

**Comment by benedictr** [comment]
That's completely understandable - thanks for the clarification, and all the best to you and the team in developing CHC back to its former stability!

**Comment by B1gLev** [comment]
> Hi,
> 
> thanks for your great feedback. RGB colors are already supported in the latest ChatControl version.
> If you have any specific issues with the latest version's RGB support we're more than happy to help.
> 
> Regards,
> Leonhard

Hi, I would have a question about how to use rgb. Because I don’t really know how to use it.

**Comment by kangarko** [comment]
Use {#123456} syntax and wait for the next version please.
