### ISSUE TITLE
1.16.1: Sign spy color , chc 8.6.9

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/ChatControl-Pro#1787]
Spy sign color is not applied correctly. Only the first line from the sign keeps the color from the config while the rest goes to default.

![image](https://user-images.githubusercontent.com/42933023/89192137-9d65b100-d5ac-11ea-90a7-37685c818b3d.png)

![image](https://user-images.githubusercontent.com/42933023/89192100-8f179500-d5ac-11ea-87db-801603a8ef66.png)

**Comment by JavaFactoryDev** [comment]
Hi,
thanks for reporting this we will have a look later today.

Regards,
Leonhard

**Comment by kangarko** [comment]
Unfortunately this is how Minecraft handles sending multi line messages when using the tell method. Please just put the color before each new line manually.
