### ISSUE TITLE
1.8.8: No support for old PlaceholderAPI

### ISSUE THREAD

**Issue by iProMC** [kangarko/ChatControl-Pro#1788]
hello i do have a problem when i type in chat anything the the plugin crash and i sent in error.log i don't know why this happen .

[Uploading error.log…]()

**Comment by JavaFactoryDev** [comment]
Hi,

thanks for reporting this.
We can't access your error.log as it is shown as "uploading". Can you please change this?

Regards,
Leonhard

**Comment by iProMC** [comment]
https://pastebin.com/iAV6wuhR

**Comment by iProMC** [comment]
here you go you can check.

**Comment by JavaFactoryDev** [comment]
Hi, 
you are using an outdated and unsupported version of the placeholder API. Please update.

Regards,
Leonhard

**Comment by iProMC** [comment]
I can't update the placeholder API because 99% of my plugins work on this version

**Comment by iProMC** [comment]
I use 2.10.6 and all of my plugins can't support 2.10.8

**Comment by kangarko** [comment]
Understood, we will make it so to support both the old PlaceholderAPI and the new one. We will let you know the progress shortly.

**Comment by Sikatsu** [comment]
I would also like to use 2.10.6 for now, since 2.10.7 and 2.10.8 is not compatible with some of my plugins.

Thank you!

**Comment by Sikatsu** [comment]
Not really my ticket, but the above message @kangarko

**Comment by kangarko** [comment]
Seems like PlaceholderAPI author made it a bit complicated for us, but I will try to hack it in using reflection so it works with all versions.

**Comment by iProMC** [comment]
thank you. 👍  I will wait for the new update

**Comment by kangarko** [comment]
Thanks we got it fixed! Please use PlaceholderAPI-2.10.9.
