### ISSUE TITLE
1.16.1: Multiplie lines warn

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl-Pro#1789]
Hi, i would like to warn with multiples lines

match (.*como)(.*protejo)
then warn &7No puedes proteger.
then warn &7Debes hacer tu casa sin protecciones

Thats not working

**Comment by kangarko** [comment]
Hi there!

You can separate the messages using "|" like this:

```
then warn &7No puedes proteger.|&7Debes hacer tu casa sin protecciones
````

Matej
