### ISSUE TITLE
1.16.1: DiscordSRV and ChatControl duplication issue

### ISSUE THREAD

**Issue by AngellitoX** [kangarko/ChatControl-Pro#1790]
Hello guys! Angel Avila here.
This has been a very old error happening for months with ChatControl and DiscordSRV and It's related to ChatControl duplicating messages on AdminChat if this is setup to be cross-server. This has even been reported a lot of times here without any fix after all.

![image](https://user-images.githubusercontent.com/1666907/89256495-db34fa80-d5e9-11ea-8464-020f44ececb7.png)

My setup:
- Latest Waterfall build
- Lobby - Paper 1.12.2 build 1618
- 2nd server - Paper 1.16.1 latest build
- ChatControl 8.6.9

The steps to reproduce are pretty straightforward.
1. User BungeeControl 2.2.6 with default settings.
2. Install ChatControl in both servers and place these settings file: https://pastebin.com/TzjEkS69
3. Setup your DiscordSRV by making these changes on the config.yml: https://pastebin.com/WVAbeM9R
4. **IMPORTANT:** Turn your servers and join with a different account in each server. **You must have at least one player in Lobby and one player in 2nd server.** if you speak through the game (/chc ach Hello guys), you should see your chat going cross-server, and also you should be able to see you chat on the AdminDiscordChannel you setup from the DiscordSRV config.yml
5. The problem comes when you speak from AdminDiscordChannel to send a message to the AdminChat. You will get the message duplicated.

The message gets duplicated by the amount of servers you have under your network and by having at least one person in each of them. I have a 10 servers network and most of the time they're crowded, so you can imagine how a nightmare it is to chat with admins from Discord.

Hope you can reproduce the issue. If you need the full folder to keep running tests, I can also provide you anytime.

Thank you very much!

**Comment by LeehamElectronics** [comment]
Hi Angel Avila!
I had this same issue for a long time using ChatControlPro version 9.x.x
Now I am using the latest v8 which is ChatControlPro version 8.7.4 and the issue is no longer there. I did have to rebuild all of my settings.yml and all other config files but now it works well. It could also be your BungeeControl config, I had to disable 'Chat_Relay' in my config in order to stop chat duplication's from Discord as well. Let me know if I helped or not!
Thx

Kind Regards,
Liam

**Comment by kangarko** [comment]
So happy to announce that this problem HAS BEEN SOLVED once for all!! 🥇

**Comment by LeehamElectronics** [comment]
> So happy to announce that this problem HAS BEEN SOLVED once for all!! 🥇 

What was the solution?

**Comment by AngellitoX** [comment]
@LeehamElectronics on the latest update from CHC this gets patched. I can absolutely confirm. You don't have to move anything from your configs :)
