### ISSUE TITLE
1.16.1: Announce feature outputs too many blank / dynamic lines.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1791]
Tuinity dev 328 (https://github.com/Spottedleaf/Tuinity/actions) (Paper 1.16.1 Fork)
ChatControl Pro 8.6.9
Java 14.0.2 (Oracle)
CentOS 8

Using the ``/chc announce message`` command, too many dynamic lines seem to get outputted, causing the message to not be seen unless you open your chat window.

![link](https://i.imgur.com/ANS4JUk.png)
![link2](https://i.imgur.com/LOwyeBl.png)

localization/messages_en.yml
```
Announcer:
  # Supports variables: {message} and {player} (the one who announced it)
  # and {dynamicLine} which will automatically inserts line separator
  # to make the announcement on 10 lines
  Message: |-
    &8*___________________________________________________*
    &f
                    &7. . . &6&lA N N O U N C E M E N T &7. . .
    &8*___________________________________________________*
    &f
    &f {message}{dynamicLine}
    &8*___________________________________________________*

  Console_Message: '&f[Announcement by &b{player}&f]: &7{message}'
  Self_Message: '&7Announcement sent.'
```

ChatControl v9 didn't have this issue / fixed it, but this was brought back with v8 being the new main version.

**Comment by kangarko** [comment]
Thanks, I fixed that.

**Comment by mibby** [comment]
@kangarko This still is a problem with v8.7.1. :(

**Comment by kangarko** [comment]
Omg so sorry! I tested it but for whatever reasons my configuration files were alright.

Can you please ZIP your whole config?

**Comment by mibby** [comment]
Here you go. I would have thought it is a Java 14 issue, but v9 didn't have this issue -- only v8.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5024170/ChatControl.zip)

I also had someone hit my spam filter for saying ``f u c k`` in a long sentence and ChatControl _did_ match the regex/ID, but the message was let through instead of blocked.

**Comment by kangarko** [comment]
Thanks, I sat down, rewrote it, tested it and updated ChatControl.

**Comment by mibby** [comment]
Confirmed fixed, thanks!
