### ISSUE TITLE
PAPI

### ISSUE THREAD

**Issue by iProMC** [kangarko/ChatControl-Pro#1792]
Hello, 

I open the a ticket yesterday and the problem was that I have to update papi to the last version the problem is that I can't because all of my plugins require 2.10.6 and the last version is 2.10.8 will stop my server. so who you can fix that because I need chat control

thanks.

**Comment by iProMC** [comment]
the chat control version 9.0.4 was work with me with the papi 2.10.6

**Comment by kangarko** [comment]
Thanks, I reopened your ticket: https://github.com/kangarko/ChatControl-Pro/issues/1788
