### ISSUE TITLE
1.16.1: Bungee spy issue

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1793]
When I talk with someone in private, and we are not on the same server, it will show spy messages from my own conversation.

![image](https://user-images.githubusercontent.com/5664135/89307949-fa776a80-d671-11ea-8c6d-32025856bf3f.png)

Tested on 8.6.8

**Comment by AngellitoX** [comment]
Hello Sikatsu, nice to see you here after all.

The issue is now being revised by Matej and the resolution will now come either today or tomorrow first thing in the morning.
Thank you!

Angel from MineAcademy.org

**Comment by Sikatsu** [comment]
Hey Angel, 

We solved our matters, so I'm still around. ^^ 

Thank you for your response!

**Comment by kangarko** [comment]
Can't really promise #1 thing in the morning since I have a long list, but yeah, I will go over this tomorrow.

**Comment by kangarko** [comment]
Just to confirm did this get fixed since you closed this?

**Comment by Sikatsu** [comment]
It's not actually solved, sorry for that.
