### ISSUE TITLE
1.16.1: Hexcode nickname breaks in private messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1795]
Hey, I am using CMI to set a hexcode in my nicknames. For some reason ChatControl is not able to show these hexcode colors right in that department. It works fine in other plugins, like party chat from McMMO and even the admin chat from ChatControl.
For some reason, in the private messages from ChatControl, it will either show as black or the hexcode won't parse at all.

![image](https://user-images.githubusercontent.com/5664135/89339691-e138e300-d69e-11ea-88a4-56e38724d2d3.png)
![image](https://user-images.githubusercontent.com/5664135/89529544-371ba100-d7ed-11ea-92be-f252eda40dfa.png)

Could you either force the colorcode in front of the placeholder, or make it working in private messages as well?

      Message: '&6[&eIk &6-> &e{receiver}&6]&6 {message}'

**Comment by AngellitoX** [comment]
Hello there! 

Yeah, we are aware that HEX was a little bit bad-implemented. This is already added to the list and hopefully it will be now fixed between today and tomorrow. 

As always, thank you for reaching us.
Angel from MineAcademy.org

**Comment by Sikatsu** [comment]
Hello!

I just realised, with some hexcodes it will turn black (probably because the last number in the hexcode is 0 for black?)

But it can get much worse then that, when it doesn't parse at all:
![image](https://user-images.githubusercontent.com/5664135/89400703-8e017780-d714-11ea-9407-2d416139006b.png)

**Comment by Sikatsu** [comment]
Hey @kangarko could you prioritize this one perhaps? Looks really messy in the private messages system. ^^

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/1807

**Comment by kangarko** [comment]
I understand it is frustrating, but I kindly ask you to use the old color codes for now until this gets resolved.

**Comment by Sikatsu** [comment]
That makes no sense. Can you not force the colorcode in front of the placeholder if fixing the hexcode system is not possible right now? Or don't use the nickname but just their original minecraft name?

I have changed all colors of my ranks, not only in luckperms, but also everywhere else in-game the rank colors are listed.
This has cost me a lot of time, and reverting back is not something I'd like to do if the solution (even if temporarily) is pretty close.

**Comment by BloodshotPico** [comment]
Pretty sure you can just use similar-ish colours until it gets patched.

**Comment by Sikatsu** [comment]
The default minecraft colors, are not at all similiar..

**Comment by BloodshotPico** [comment]
Hence why I said similar-ish?

**Comment by Sikatsu** [comment]
I don't need a fix perse so the hexcodes work, a temporarily solution would be to force the color code in front of the placeholder?

**Comment by kangarko** [comment]
Got it. The reason I replied so was that the previous developer changed a bunch of stuff without notice and now I have to learn and discover these changes. For example looking through the code for ChatColor.of did not gave any results since it turned out to be done via reflection.

Anyways, seems to be working when I hardcode it into formatting: 

![a](https://i.imgur.com/7nVT2BV.png)

I assume it is broken when coming from a permission prefix, will test.

**Comment by Sikatsu** [comment]
The previous developer implemented my code for RGB support, it seems to work everywhere in the configuration file. So indeed, the way you did it in the configuration file works fine.

When a player uses hexcodes in his nickname, using for example Essentials or CMI, the hexcode is visible in the nickname as seen in my picture. Try giving yourself a nickname using a hexcode and use the private messaging system ^^

In McMMO's party chat it parses correctly: 
![image](https://user-images.githubusercontent.com/5664135/89659081-a8338500-d8cf-11ea-9535-6df1dd2892b3.png)

**Comment by kangarko** [comment]
Thanks, I finally fixed it! However with the current system, only 1 HEX color is possible within the nickname. I will look into expanding this functionality soon.

**Comment by Sikatsu** [comment]
Ah, is it not possibe to parse all of them? It works in most plugins like McMMO and ShowItem. Players use more then one hexcode, so it'll still be a problem sadly :(

**Comment by Sikatsu** [comment]
@kangarko Can this be re-opened?

Player has one hexcode in the name {#DDEEFF} and it still shows as white.

![image](https://user-images.githubusercontent.com/5664135/89951776-5327a400-dc2c-11ea-8bdb-9067a8024b15.png)

When using two hexcodes in the name, both still do not parse.

![image](https://user-images.githubusercontent.com/5664135/89951830-6b97be80-dc2c-11ea-86e6-b62a2ee2d5c1.png)

**Comment by Sikatsu** [comment]
To make it even more interesting, when you use /msg <playername> it parses both of them:
![image](https://user-images.githubusercontent.com/5664135/89952046-cfba8280-dc2c-11ea-9118-1a96d5f0d315.png)
When you use /r, you get the above..

**Comment by kangarko** [comment]
Thanks, I got help from a volunteer on the implementation, please test the next version and let me know.

**Comment by Sikatsu** [comment]
[00:52:04 INFO]: Badjasman issued server command: /msg Sikatsu oki
![image](https://user-images.githubusercontent.com/5664135/90194900-8c951680-ddc8-11ea-8310-8f2aa83b4725.png)

Shows literally a blank message in the chat, for some reason..

Then after that the whole chat breaks: https://pastebin.com/3DJ4LbJd

![image](https://user-images.githubusercontent.com/5664135/90194977-b9e1c480-ddc8-11ea-99a9-e49482864074.png)

I assume in private messages it can only show two, and the other two return white?

**Comment by kangarko** [comment]
The "already in the map" problem will be solved, apology for this inconvenience. Then you can retest using the next release tonight.

**Comment by Sikatsu** [comment]
I think it's more broken then before, sadly.. @kangarko 

![image](https://user-images.githubusercontent.com/5664135/90294925-ec062b80-de87-11ea-9347-ecd289063bd6.png)

**Comment by kangarko** [comment]
Are you sure you are on the latest version? Last time I replied on your other ticket it was old one. Yes I did test it before the release:

![a](https://i.imgur.com/FDDzg4Y.png)
![b](https://i.imgur.com/flCoa2h.png) <-- only thing that does not work is that color changes to black after the prefix unless I put &7 there explicitly. I am working on a fix.

**Comment by Sikatsu** [comment]
Yes, I tested this on the latest version. I just accidently mixed up an error since I had too many pastebin's open.

Your second image shows the normal chat, hexcodes work fine in there. The problem is specific to private messages.
As you can see from my image, hexcodes do not parse in them on 8.7.8. 

Just to confirm:
![image](https://user-images.githubusercontent.com/5664135/90308575-e2f57880-dee0-11ea-9891-95bbd352fb3f.png)

**Comment by kangarko** [comment]
The first image showed private messages. There were some changes in the upcoming version, please test that out tonight when it's out ;-)

**Comment by Sikatsu** [comment]
Yes, the first image shows private messages. But you applied the hexcode in the configuration, that works. But using a third party like Essentials or CMI to set a nickname with hexcodes, that's where it becomes an issue.

I will test tonight's release and get back to this ^^

**Comment by kangarko** [comment]
Got it, yes I also tested CMI, it will work:

![a](https://i.imgur.com/J25KOiD.png) 👍

**Comment by Sikatsu** [comment]
Will test this later, seeing #1853 being an issue on the latest version.

**Comment by kangarko** [comment]
Closing, lets continue there instead.

**Comment by Sikatsu** [comment]
@kangarko That issue is not related to this one, plus I don't seem to have the issue they mention.

I tested it however:

In /msg everything works fine, in /r it does not.

![image](https://user-images.githubusercontent.com/5664135/90544859-0beb6700-e188-11ea-9cc1-3f80a0a6d92f.png)
