### ISSUE TITLE
1.16.1: MultiWorld Formatting ?

### ISSUE THREAD

**Issue by ChrisFlyer7** [kangarko/ChatControl-Pro#1798]
Does ChatControl Pro support different world have different chat formatting ?
If it has. How to set ?
Thanks.

**Comment by AngellitoX** [comment]
Hello there!

Of course, please refer to this site so you can learn it properly. https://github.com/kangarko/ChatControl-Pro/wiki/Per-World-Chat-Formatting

Let us know if you have any further comments.
Angel from MineAcademy.org
