### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by ZoefyC** [kangarko/ChatControl-Pro#18]
Hi,
somehow the channels aren't working for me.
I enabled channels in the settings.yml so players will join the standard channel on default. But evertime I write something in chat, it won't show ingame. It will however show in the console. 
I tried all the preset channels, the only channel that is working for me is the ranged channel. It looks like I'm missing some permissions, but I can't figure out which ones... I don't get any error messages.  Please help! :)

**Comment by kangarko** [comment]
Does them work when you are an operator? Do you have enabled the interactive chat in settings.yml?
Are they any err messages on server startup?

**Comment by ZoefyC** [comment]
Thank you so much for your response! Turns out I didn't enable the interactive chat option. It's working now, thanks again! :)

**Comment by ZoefyC** [comment]
Hi again. I was wondering if there is a way to use color codes for the messages while using channels. Right now every message that is sent uses the same color as set by the player prefix in PEX. So for example, if the player prefix for "A" is set to red, the whole chat message (<playername> + <message>) will be red.
I mean, it does look pretty - but it is a little too colorful for me... ;) 
I believe I need to change something in chat.yml, but I have no clue what that is.

**Comment by kangarko** [comment]
Since you've closed the issue, I believe it has been fixed. You can't configure that behaviour directly within chat.yml (there you can only write the color manually after the prefix so it will be hardcoded), but in PEX itself.
