### ISSUE TITLE
1.16.1: Console Spam UUID

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/ChatControl-Pro#1800]
Just updated to 8.7.1 and i get these console messages.
![image](https://user-images.githubusercontent.com/42933023/89385519-686e7100-d708-11ea-9fe7-7c29bf0f98bd.png)

**Comment by AngellitoX** [comment]
Hello!

Does that happen in any specific case? What would be the steps to reproduce it?

Also can you provide more information? Server version and build, settings.yml file.

Angel from MineAcademy.org

**Comment by LucidAPs** [comment]
It happened when i upgraded from 8.6.9, nothing else was changed or done.
I am on Paper build 131 - 1.16.1
plugins: https://pastebin.com/raw/sN8BHERH
chc settings : https://pastebin.com/raw/3bRY7XUC

**Comment by AngellitoX** [comment]
Hello,
Strange, we'll check it out shortly and give you a headsup soon.

Thank you very much!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Hi there!

I apology, but there is not a single time we use that in any messages, can you please test the 8.7.2 version?
![a](https://i.imgur.com/V1RfN09.png)

Closing in good faith this will get resolved, if not comment below.

Matej

**Comment by kangarko** [comment]
If you have PunishControl btw, try removing that plugin to see if the issue got resolved.
