### ISSUE TITLE
1.16.1: BungeeControl: Accents are replaced with garbage characters

### ISSUE THREAD

**Issue by TNTUP** [kangarko/ChatControl-Pro#1801]
The new update of BungeeControl v2.3.0 causes accents to be replaced with garbage characters like that "QuÃ©bec" for the word "Québec" and might have issues with every accents

Easy to reproduce, don't think its required to send the config files/zip

**Comment by kangarko** [comment]
I could not reproduce, but I've done some changes to today's build so assuming it got patched. Please test the next release shortly available, and, if it will still be present, comment below with steps to reproduce the problem. And yes, probably also config files, you'd be surprised.

![a](https://i.imgur.com/W7Gg6H1.png)

**Comment by TNTUP** [comment]
I've meant for the join/quit messages, not in chat

**Comment by kangarko** [comment]
This seems to me like an encoding problem, can you please complete steps here? https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

**Comment by TNTUP** [comment]
Last time I tried with BungeeControl v3, it kept reverting its encoding.

Reattempted it, same thing. The file keeps reverting to "Macintosh (LF) UTF-8"

**Comment by kangarko** [comment]
Thanks, seems like a problem in the underlying library that was used, I'll try to remove it.

**Comment by TNTUP** [comment]
Mind re-opening this as this isn't solved yet?

**Comment by kangarko** [comment]
Hi, I was working on this and I am seeing all comments. This should now be fixed, I put "Québec", deleted some entries so that the config got reloaded and it remained there as it should. Thank you for your patience.

**Comment by TNTUP** [comment]
> Hi, I was working on this and I am seeing all comments. This should now be fixed, I put "Québec", deleted some entries so that the config got reloaded and it remained there as it should. Thank you for your patience.

So it means the accents are now supported and config comments will be kept? Like ChatControl its config comments too?

**Comment by kangarko** [comment]
Config comments are not kept, this is a limitation of Bukkit currently. But accents in the keys should be kept.

**Comment by TNTUP** [comment]
Tell me why other plugins such as PlotSquared or mcMMO are able to? Guess they use another yaml API to keep them?

Nice!! I'll be happy to update to the latest version of BungeeControl when this is sorted!

**Comment by TNTUP** [comment]
Now Solved with your recent update on SpigotMC!

**Comment by kangarko** [comment]
Yeah they are custom coded: https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/config/AutoUpdateConfigLoader.java

May have a look into this in the future but I personally don't have experience with this

**Comment by TNTUP** [comment]
> Yeah they are custom coded: https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/config/AutoUpdateConfigLoader.java
> 
> May have a look into this in the future but I personally don't have experience with this

okiee!
