### ISSUE TITLE
1.16.1 paper 130 logs not saving

### ISSUE THREAD

**Issue by rena0113** [kangarko/ChatControl-Pro#1802]
Hi can 
someone please advise, i have tried look at logs for private messages due to a report from a player however nothing has saved since i updated on the 17th july 2020 i tried to find anything in the config. can anyone help please.

Rena

**Comment by AngellitoX** [comment]
Hello. We definitely need more information.

What version of ChatControl are you running?

Also private messages are stored as normal on your console logs, look for /msg or /m executed commands.

**Comment by kangarko** [comment]
Just update to the next version that I will release tonight and ZIP us your whole ChatControl/ folder to see your setup,

**Comment by AngellitoX** [comment]
I am closing this as there was no reply. Feel free to open a new ticket if you need more help. 

Greetings!
Angel from MineAcademy.org

**Comment by rena0113** [comment]
Apologies I have been having Internet issues, some idiot cut a cable where
I am and the provider been trying to sort it.
Kind regards
Rena

**Comment by kangarko** [comment]
Haha hope it is fine now! Just please read my comment above, attach what is needed below and I will reopen in.

**Comment by rena0113** [comment]
I will have a look tonight when I get in from work.

Kind regards

Serena

**Comment by rena0113** [comment]
Right i have updated to latest version  8.7.6 the chat logs haven't saved
since 19/7/2020

**Comment by kangarko** [comment]
As I said:

> Just please read my comment above, attach your folder as a ZIP below and I will help you.

**Comment by rena0113** [comment]
Chat control pro. Yes it comes through on console but I need it to store on
the logs in case I need  to check back on things if we have any issues
reported.
Kind regards
Serena

**Comment by rena0113** [comment]
And the latest version

**Comment by kangarko** [comment]
Please ZIP me your whole folder so that I can reproduce and fix your problem.

**Comment by kangarko** [comment]
I unfortunately cannot find it. Please use uploadfiles.io to upload this anew. Thank you.
