### ISSUE TITLE
1.16.1: Failed to copy /variables to variables

### ISSUE THREAD

**Issue by Penvmbra** [kangarko/ChatControl-Pro#1804]
Just purchased plugin, failed to load on first server boot.

Error is as follows:
[error.log](https://github.com/kangarko/ChatControl-Pro/files/5031588/error.log)

I don't have any more information than this, I literally just bought the plugin.

Edit: To add - Going back to a previous version (to 8.6.9 from 8.7.2) allowed the plugin to load properly.

**Comment by kangarko** [comment]
Thanks, I identified and fixed the problem. A new release will be available tonight.
