### ISSUE TITLE
1.16.1: How to do the JSON MOTD messages?

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#1806]
So I'm looking through the messages.yml and it says you can use JSON format for the MOTD you just need to set it in the formatting.yml I think? I'm not sure.

It would be great if there was a link posted along side that note within the messages.yml. But basically what I'm wanting to do is have a MOTD message that has something like:

Server MOTD
Website!

And where "website" is to have it be a hyperlink, if that's plausible?

Thanks.
~Blood

**Comment by Sikatsu** [comment]
Hi again,

The MOTD is not in the messages.yml file but in the settings.yml file.
Does this help you further in this regard? I have a similiar setup as what you'd like to have I think.

https://pastebin.com/cSz5sax6

Hope this works for you!

**Comment by AngellitoX** [comment]
Thanks a lot for the assistance!

I am closing this ticket for cleanup. Please consider reopening again if you need further help.

Angel from MineAcademy.org

**Comment by kangarko** [comment]
@AngellitoX can you please update Wikipedia regarding this?

Thanks!
