### ISSUE TITLE
1.16.1: The New RGB System?

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#1807]
I was wondering if the new RGB system is in the plugin already and setup to be used right off the bat? From the new changes Mojang made recently with one of the 1.16 versions. :)

Thanks again.
~Blood

**Comment by Sikatsu** [comment]
It's not perfect, and definitely needs some improvement. Leonhard recently implemented some of my code. 

But you can use {#RRGGBB} and it should work in most places of the configuration files. 
So far I only noticed issues with private messages and /chc color.

You can also use it with LuckPerms, in case you want to change the colors of your ranks.

![image](https://user-images.githubusercontent.com/5664135/89589121-4af2f180-d845-11ea-957a-e06158f0018d.png)

**Comment by AngellitoX** [comment]
Hello.

I am closing this ticket as it seems resolved. HEX implementation is on the works and there is already a ticket opened awaiting.

Thank you!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Thanks, reopening this and closing the other ticket since this one makes more sense.

I am not sure if I catch up RGB support in 8.X.X, I am focusing on bugs and patches at the moment but it will definitely come with 9.X.X.

Anyways, leaving this open so I can have a look when I have time.

**Comment by Sikatsu** [comment]
I don't understand how this makes ''more sense''. The RGB support works perfectly, except for in private messages. It's a bug report. It's literally one thing, that shouldn't even be hard to solve even for a temporarily solution..

**Comment by kangarko** [comment]
Lets continue here: https://github.com/kangarko/ChatControl-Pro/issues/1795
