### ISSUE TITLE
1.16.1 Case Sensitivity

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1808]
I found out that disabling `Regex_Unicode` makes rules case sensitive.
This makes all rules pretty useless if not taken care of(!)

Is this intentional?

CHC 8.7.3

**Comment by kangarko** [comment]
Thanks, I removed that option. Currently, all regex is matched Unicode. We found little performance difference while having this on/off and in order to simply our settings file I removed that option permanently.
