### ISSUE TITLE
1.16.1: Database clear on startup

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1809]
I assume this is from ChatControlPro, altho I am not 100% sure. I didn't see this on the old v9 branch however..

But is there any option to get rid of this on startup? https://pastebin.com/nWWe6VWE
It says ''inactive players'', but I see names of players that are active too..

**Comment by kangarko** [comment]
Fixed, the message was not always the case, since we also clear data for players who are active but simply don't have any data.db entry besides their last time played.

**Comment by Sikatsu** [comment]
Ah, that makes sense. I indeed didn't always see it, hence why I doubted if it was ChatControl
