### ISSUE TITLE
Player Join Console Error

### ISSUE THREAD

**Issue by doitliketyler** [kangarko/ChatControl-Pro#181]
Hey there. With the recent update this console error is showing up when a player joins a server

http://pastebin.com/bQqDGL2D

I'm on Spigot 1.11.2 Thoughts?

**Comment by kangarko** [comment]
Hey, I was not able to track it down, can you please test against 7.2.7  and repost the error?

**Comment by doitliketyler** [comment]
With the latest 7.2.7

http://pastebin.com/U6p0FJKi

**Comment by kangarko** [comment]
Confirmed. I apologies for the issue. A new release will be available within 1-2 hours.

**Comment by kangarko** [comment]
Closing. Please test out 7.2.8
