### ISSUE TITLE
1.16.1 old folders?

### ISSUE THREAD

**Issue by Yidsir** [kangarko/ChatControl-Pro#1810]
after updating to the new 8.x versions from the old 9.x versions, the "channels" and "formats" folders seem to be obsolete since channels and formats are now handled in channels.yml and formatting.yml.
should these obsolete folders be deleted?

also i noticed the autojoin permissions are working again.

**Comment by kangarko** [comment]
You can just remove these folders completely.

I highly highly suggest you rename the whole ChatControl folder to something else and let 8.x regenerate the files, as they are majorly different.
