### ISSUE TITLE
Item in Chat

### ISSUE THREAD

**Issue by NikKing97** [kangarko/ChatControl-Pro#1814]
It would be a neat feature if you could implement something to show off an item in the chat.
Like if you are typing %ITEM% / {ITEM} or something similar the item you are holding in your hand gets implemented in the chat.

_"NikKing97 » Hey guys, check out my cool [Special Sword]!"_

The Item is displayed with its name and color and if you hover over the item/text you can see all of its lore.
I think that would be a great feature for many players and will improve the trading.

- permission for using the "placeholder"/ to display a item in the chat
- maybe | permission for each channel, so you cant display items in certain channels
- maybe | permission (or something) for a cooldown, so you cant display every second/message an item in the chat
     - maybe | possibility that you can set a different cooldown for each role/rank
     - bypass permission

**Comment by AngellitoX** [comment]
Hello there.

Thank you for the suggestions. As for now, Matej is working on making the plugin as stable as you all deserve to be. Therefore, improvements and new additions may take a while as they will be planned for the future ChatControl v9 series. 

Angel from MineAcademy.org

**Comment by kangarko** [comment]
Thanks, this was suggested way too many times now - basically we got it working on 9.x.x, and when this release is ready you will see it there again ;)
