### ISSUE TITLE
1.16.1: escaped newlines from custom javascript displaying as source instead of newlines in formatting.yml

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1818]
In custom script return a value including "\n" such as
```
Key: '{multiline}'
Value: "My result should \n display in two seperate lines"
```

Where in formatting.yml you'd have something like:
`Message: "The Message was: {multiline}"`

The expected output in chat would be
```
The Message was: My result should 
 display in two seperate lines
```

But instead you will get:
`The Message was: My result should \n display in two seperate lines`

**Comment by kangarko** [comment]
Thanks, created a wiki link: https://github.com/kangarko/ChatControl-Pro/wiki/JavaScript-in-Bukkit#multiline-messages

**Comment by mrcoffee1026** [comment]
I DID have the "|-" before this part of the function was defined and it still didn't render the newline in chat, so I don't believe this is working... however since I now have to restart to test javascript changes, I won't know till I can restart again now that I've uncommented that part.

**Comment by kangarko** [comment]
Wait I am a bit confused, so you are saying the |- gets removed and smashed all together?

**Comment by mrcoffee1026** [comment]
no the |- remains where it is, it just doesn't effect how the "\n" in the function gets evaluated when it's being put into chat later

**Comment by kangarko** [comment]
Please ZIP me the file that is broken for you and I will test.

**Comment by mrcoffee1026** [comment]
Ok I just tried again on the later version you put and it worked as expected using 8.7.6

This is the entirety of the javascript file (less the startup comments) marry.txt:
```
Key: '{marry}'
Value: |-
  function gethover(){
    var thetext = '';
    if ('{marriage_partner}' > ''){
      thetext += '\n&7Partner&8: {marriage_partner}';
    }
    return thetext;
  }
  gethover();
Hover: []
```

And I use it within this conditional format in formatting.yml:
```
  Chat:
    PrefixMarry:
      Message: "&c&l♥&r"
      Condition: "'{marriage_is_married}' == 'yes'"
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*{marry}'        

```

It was doing that code smashing thing before but on this last attempt did not.  It had also just been printing "\n" before but this time actually added the appropriate new line where it was supposed to appear and placed the partner info just below the player  name as intended.  So whatever was going on before does seem to be remedied within one of the more recent builds, thank you!

**Comment by kangarko** [comment]
Nice!
