### ISSUE TITLE
1.16.1: Welcome message being spammed multiple times

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl-Pro#1819]
1) Put your Minecraft version in the title.
Example: 1.16.1: PaperMC build 99

2) When a new player joins our network an welkom message is send multiple times. Most of the times its 2 welcome messages, but sometimes this happens 3 times. I would expect to only see 1 welcome message.

The new players first joins our network via bungeecord (waterfall build 366), here we are running bungeecontrol v3.0.0 with [this setting.yml](https://pastebin.pl/view/5284dda7) file. The players gets redirected to a login server where they are asked to enter a pin number. (no chatcontrol running on that server). After doing the pin the player gets redirected to the lobby where they can pick there gametype. (scheduled implementation of chatcontrol, but no yet done).
gametype survival: [settings.yml](https://pastebin.pl/view/206d2038)
gametype skyblock: [settings.yml](https://pastebin.pl/view/f35eac9b)
gametype factions: [settings.yml](https://pastebin.pl/view/b5641e5a)

all servers run chatcontrol-9.0.4.jar

i have no clue what could be causeing the spamming of the welcome message multiple times. i hope you might know?

**Comment by AngellitoX** [comment]
Hello.

ChatControl v9 is abandoned due to a bad implementation. Please look at the SpigotMC changelog for more information and move to v8.7.4

Angel from MineAcademy.org

**Comment by donvdp** [comment]
ok, thanks for info!
