### ISSUE TITLE
Localization & Updates

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#182]
Hey there. Can you please put localization into a configuration folder, please? Because after each update you need to update the file in the jar and it gets really annoying...

**Comment by kangarko** [comment]
You should not edit the locale file directly within jar. Please follow these instructions to get the locale file permanently and conveniently in the config folder:
https://github.com/kangarko/ChatControl/wiki/Pro-&-Free-Information#localization
