### ISSUE TITLE
1.15.2 PaperMC: chatcontrol.notify.bungeechat is spamming the chat

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1820]
1.15.2: Getting chatcontrol.notify.bungeechat spammed in the chat each time a player sends a message in the default chat which is the bungee chat since I have 3 servers connected. I have tried disabling the "notify_updates" and it did not change anything. This only started happening when I went from ChatControlPro version 9.x.x to the latest ChatControlPro version 8 that has been released. Another issue that started due to changing to version 8, is that messages in game are no longer formatted, there's just a "G" at the start of all messages when a player sends a message. Any ideas? Thx
![image](https://user-images.githubusercontent.com/51737378/89723501-c1a51000-da3a-11ea-95fa-bacff6b9c1ae.png)

**Comment by LeehamElectronics** [comment]
Never mind! The issue was easily resolved, I simply had to delete all of my ChatControlPro files and rebuild all the configs because of the change from version 9.x.x to the latest ChatControlPro v8, (I had to do this on all of my servers connected to bungee.)

Keep up the good work Kangarko your doing a great job! I love your work.

**Comment by kangarko** [comment]
I am so sorry for the time waste, and I understand it was annoying, however temporarily fixing the 8.x.x was the best/only option I had possible. Having said that, the new 9.1.0 will be coming soon!
