### ISSUE TITLE
1.16.1 Client - 1.15.2 Server - Disconnect.Spam

### ISSUE THREAD

**Issue by hwrichardson999** [kangarko/ChatControl-Pro#1823]
When sending messaages using /msg or any of the other aliases, I can send them as the owner however anyone replying gets kicked for 'Disconnect.Spam'

**Comment by AngellitoX** [comment]
Hello. This is a little bit ambiguous. I am using ChatContr 8.7.4 on a 100 players server and no one is getting kicked.

What version of ChatControl are you using?
What plugins do you have?
What Spigot fork are you using? And build number
What are your ChatControl settings?

**Comment by hwrichardson999** [comment]
Issue resolved. Was ViaVersion. Very odd that it caused ChatControl to error but not to worry

**Comment by kangarko** [comment]
How did you resolve it please? @AngellitoX when @hwrichardson999 tells you how he resolved it please update our Wiki so that others can find it, too, thanks!

**Comment by AngellitoX** [comment]
@kangarko Apparently he just updated ViaVersion as they released a new update recently. If there's anything else, of course we would love to add that to our info! 😁

**Comment by hwrichardson999** [comment]
In ViaVersion settings is an option to disable 1.13 auto tab complete. That
was my issue
