### ISSUE TITLE
1.15.2 Random prefix when sending private messages on Bungee??

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1824]
1.15.2: Random prefix when sending private messages on Bungee?
ChatControlPro 8.7.4 and latest version of BungeeControl

When sending private messages to and from players across bungee there is a random prefix that looks weird, how can I get rid of this or customize the message format of /msg ?
Thanks heaps!
![Capture](https://user-images.githubusercontent.com/51737378/89786644-9f58e280-db5f-11ea-8142-5d00d6443e62.PNG)
![Capture2](https://user-images.githubusercontent.com/51737378/89786678-ab44a480-db5f-11ea-910e-77cc9c561901.PNG)

**Comment by AngellitoX** [comment]
Hello ham, it looks like the code from your file changed. Please make sure its on UTF-8. That prefix should be an email icon.

**Comment by kangarko** [comment]
As Angel said, it looks like your file is corrupted when saved, please follow the advice here: https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding and ensure that, when you reopen the file after saving, the characters are not there.

Closing in good faith this will help, if not please comment below with your folder attached.

**Comment by LeehamElectronics** [comment]
![image](https://user-images.githubusercontent.com/51737378/89844545-37d27f80-dbbf-11ea-8156-9110d99bad17.png)
Hey! Thanks for the fast reply, I tried but it is not working, I cant see the option for UTF without BOM, I tried all of the options anyway and none of them worked.
Any ideas?
Thanks

**Comment by AngellitoX** [comment]
Hello Leeham! My best suggestion is to backup your current formatting.yml and make the plugin regenerate a new one, and you paste the specific sections that you modified and see if that works for you.

Thank you!

**Comment by LeehamElectronics** [comment]
I just tried that too, still not working...

**Comment by AngellitoX** [comment]
Weird, can you provide your formatting.yml file? I just tested in a clean server and everything is working fine, unless you might be using a very strange symbol that's probably breaking the encoding.

**Comment by LeehamElectronics** [comment]
[formatting.zip](https://github.com/kangarko/ChatControl-Pro/files/5054182/formatting.zip)
That's the formatting file that CCP is currently using.

**Comment by AngellitoX** [comment]
You need to modify these lines:
`Message: "&7âœ‰ &2has been sent!"`

because it's broken

to something like
 `Message: "&7"&7✉&2 has been sent!"`

**Comment by LeehamElectronics** [comment]
Okay ill try, its odd because I deleted the formatting file and let ChatControl regenerate it so you'd think the plugin would automatically do that.

**Comment by LeehamElectronics** [comment]
Cool it all works now, should probably be done automatically but or well. Thanks so much for your help and fast replies! 
Keep up the good work.

**Comment by kangarko** [comment]
Thanks so much for your input and sharing what worked, also many many thanks to our wonderful @AngellitoX!

Also, the new BungeeControl that is going to be released tonight will fix some issues on its end too regarding its own config files.

**Comment by LeehamElectronics** [comment]
> Thanks so much for your input and sharing what worked, also many many thanks to our wonderful @AngellitoX!
> 
> 
> 
> Also, the new BungeeControl that is going to be released tonight will fix some issues on its end too regarding its own config files.

Hey mate, I know this isn't the place to ask you but I can't find a way to direct message you on GitHub, I was wondering if you could send me the 2 bonus maps for CoreArena? Would it also be possible to get the arenas.yml and the database file so we can have an example reference for CoreArena? We're having a bit of trouble setting up all the features in arenas so if we could get some examples all set up it would be amazing. My friend already sent you a PM on spigot since he was the one that paid for the plugin, but I thought you might only reply on GitHub now.
I'll delete this message when you reply cause I know it's not the right place to post it but I can't think of anywhere else 😂 sorry
Thanks in advanced!
