### ISSUE TITLE
1.16.1: DeadMessage Ender Pearl 

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl-Pro#1826]
1.16.1: I have a question on how to set up dead message for ender pearl death? I don't know where to put it, whether projectile or Suffocation ..?

**Comment by kangarko** [comment]
Hi, quick question have you tried both?

**Comment by WolverStones** [comment]
Yes, but it show a message of fall damage.

**Comment by kangarko** [comment]
Thanks

Just reviewed, not possible since CHC only sees fall damage. Will try to recode in 9.1.x
