### ISSUE TITLE
issue with the chat control 

### ISSUE THREAD

**Issue by iProMC** [kangarko/ChatControl-Pro#1828]
Hello,

when someone types anything the chat the plugin crash in the console.

the crash: https://pastebin.com/VaC6Ryxb

by the way, I use Papi  2.10.9

**Comment by AngellitoX** [comment]
Hello, this issue has been reported before and it looks like the latest ChatControl patch is not compatible with MvdwPlaceholderAPI. I'm closing this in favor of #1817 

Let's keep the discussion there, although I can't tell if it's a Chc issue or a Mdvw one.

**Comment by kangarko** [comment]
Should be fixed in the latest CHC version.
