### ISSUE TITLE
1.16.1: Private messages are not filtered (Minecraft /w, Essentials /msg, ChatControl /tell)

### ISSUE THREAD

**Issue by leviem1** [kangarko/ChatControl-Pro#1829]
Hello, please see my issue at https://support.mineacademy.org/issues/servicedesk/customer/portal/3/CHC-208. I don't have time to jump through hoops and I was in the middle of being supported when you migrated and now I can't access my old issue to copy/paste the info. I was not notified of the migration back to GitHub by any staff member.

Basically, I send a bad word in a private message and despite it saying that it's replaced in console, the recipient still receives the bad word. I'm certain my configuration is correct (see JIRA ticket) and that no plugins are interfering (tested with only this plugin installed). There is no error message either.

**Comment by AngellitoX** [comment]
Hello there! We apology for the severe jump from one platform to another. Part of our "rebooting" period meant to disband all our extra platforms, including JIRA.

Can you please try the newest ChatControl Pro version? there are several things that got fixed already, not sure if yours was one of them as private messages and rules were also patched.

Angel from MineAcademy.org

**Comment by leviem1** [comment]
Looky there, 8.7.5 seems to work! Will re-open the issue if I notice anything different in 8.7.6.

Sorry to get a little frustrated btw. I figure a few things might have slipped through the cracks these last few weeks. Good luck with working out any remaining stability issues!
