### ISSUE TITLE
1.15.2: Failed to set ScriptEngine for placeholders

### ISSUE THREAD

**Issue by Srborjaa** [kangarko/ChatControl-Pro#1832]
Hi, when I installed ChatControl Pro I got those errors from PlaceholderAPI:

https://pastebin.com/EK71Ksqr

I've read some people that had the same issue and they said that it's a problem from ChatControl Pro. I tried uninstalling it and it worked as always, but with the plugin installed in the server doesn't detect placeholders.

**Comment by AngellitoX** [comment]
Hello, what version of PlaceholderAPI and what version of ChatControl are you running? I can't seem to reproduce it with both latest PAPI and CHC, so probably you're using an outdated version.

**Comment by Srborjaa** [comment]
CHC 8.7.4 and PAPI 2.10.9

**Comment by LoSCraft-Network** [comment]
I have the same issue, ChatControlPro will break javascript placeholders.

[https://i.imgur.com/Bia5qKH.png](url)

[https://hasteb.in/casulifu.shell](url)

CHC - 8.7.5 (Its been happening with older versions as well)
PAPI - 2.10.9

**Comment by kangarko** [comment]
Similar to: https://github.com/kangarko/ChatControl-Pro/issues/1799 please continue there
