### ISSUE TITLE
1.16.1: /chc color doesn't get saved properly

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1833]
Most settings work across the network, but /chc color seems to be server specific. It doesn't save in the database, and I have to re-apply it on each server. Can this be made network-wide as well?

**Comment by AngellitoX** [comment]
Hello there. Are the servers connecting successfuly to their mysql database? I can recall being able to make it network-wide without problem. Any errors in console?

**Comment by Sikatsu** [comment]
Hey, there are no errors in the console. The network is on the same database and as far as I know, all settings work except for /chc color.

**Comment by AngellitoX** [comment]
Weird, probably something changed on recent builds. Hope Matej can take a look to this soon. 

As always, thank you so much for reaching us out!

**Comment by LeehamElectronics** [comment]
Same issue here too.

**Comment by Sikatsu** [comment]
Could it be that this also affects player-specific settings like disabling/enabling the broadcast?

**Comment by kangarko** [comment]
That was never possible actually. I added it!

**Comment by Sikatsu** [comment]
Awesome! Does this now also work for player specific settings? Like disabling private messages, broadcast and such?

**Comment by kangarko** [comment]
Disabling PMs is already synced. I added colors, decoration and disabling broadcasts.

**Comment by kangarko** [comment]
This is what is sync at the moment:

![a](https://i.imgur.com/bFO3qqI.png)

**Comment by Sikatsu** [comment]
Yeah, I wasn't aware which were already sync and which were not. Thanks for the clarification though! Good job ^^

**Comment by kangarko** [comment]
Just to clarify NOT yet, but from the next release ;)

**Comment by Sikatsu** [comment]
Understood! ^^
