### ISSUE TITLE
Private chat checking for CMI nicknames

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1838]
Ignore vanished players and support nicknames? May impose a performance penalty.
  Deep_Search: true

Is there any way we can get this to support CMI nicknames?

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Just benefits anyone using CMI to control nicknames. 

2) What would happen if we won't implement this feature? How's your server being affected?
Players complain like always. Its just a quality of life tweak. I personally may switch to letting CMI handle private messages directly (since CMI already supports this), although I lose some of the features I personally prefer with ChatControl.

**Comment by LoSCraft-Network** [comment]
Also the same thing for essentials would be amazing

Messages sent to nickname X being forwarded to the owner of that nickname

**Comment by Sikatsu** [comment]
This would indeed be a a nice quality of life tweak. I also use CMI personally!

**Comment by AngellitoX** [comment]
I absolutely support this and hopefully it can be implemented soon. I am an extensive user of CMI too!

**Comment by kangarko** [comment]
Added.

Limitations: only works for /tell, no Bungee support, no /ignore support --> these things will come in 9.X.X

**Comment by Sikatsu** [comment]
I think tab suggestions in general do not support bungee? But only per-server?
And only /tell or also it's aliases and /r?

**Comment by kangarko** [comment]
All aliases. No tab complete support yet, this will come later 👍

**Comment by kangarko** [comment]
Got /ignore support to work!

**Comment by Sikatsu** [comment]
Amazing!
