### ISSUE TITLE
1.16.1 No longer respecting Mute: Disabled_Commnads: list

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1839]
Trying to block specific command /ch send standard with this list but it's no longer working.

No combination of the following has successfully prevented this command:
```
  - /ch
  - /ch send
  - /ch send standard
  - /channel:ch send standard
  - /channel send standard


```
And so as a result a person can just use channel commands to bypass their mute.

v 8.7.5
Paper-135 (1.16.1)

**Comment by AngellitoX** [comment]
Hey bro, just in case. Have you tried using /chc? I remember that's one of the commands for Channels if I am not wrong. (I am not a current user for channels, love global, love spam, love crowd) haha

**Comment by mrcoffee1026** [comment]
Yes I've added that to the list as well, but as I created the alias that is using the command, I already know which command is being used, it's not a matter of not knowing which command is being used or that the command is not in the denied list, it is that the commands in the denied list are no longer being denied.

**Comment by mrcoffee1026** [comment]
Swapping out the command to be "/channel:ch send standard" and then adding "/channel:ch" to the denied list worked.
