### ISSUE TITLE
1.15.2: Is it safe to update?

### ISSUE THREAD

**Issue by itaquito** [kangarko/ChatControl-Pro#1842]
Hello! I'm currently running version `chatcontrol-8.6.7-SNAPSHOT_proguard_base` on all of my servers, I would love to update to the newer versions that are rolling out on SpigotMC, however, I'm not sure if it's safe to update... Do I need to restart the configs? or just replacing the .jar with the newest version will do it? I'm running a server with an active community, so I can't just update the plugin and hope for the best.

Thanks.

**Comment by kangarko** [comment]
Not sure how you get that version but I assume my previous developer has given it to you without my permission nor my awareness. 

I recommend you just backup your folders, and update by just replacing the jar. If you run into any issues unfortunately you'd have to reset your configs, unfortunately as I said I never released that version so I don't know what's up with it.

If you want to be 100% safe just setup a test server on your computer, download your configs from your server and test it there.

For any issues feel free to comment below!

Best of luck
Matej
