### ISSUE TITLE
BungeeControl 2.3.1

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1843]
Upgrading bungeecontrol from 1.3.0 to 1.3.1 gives an error on enable.

https://pastebin.com/5KWqqFif

`Report / Malformed configuration! Key 'Version' in settings.yml must be Integer but got String: '1'`

When setting this version to interger 1 everything works fine. So maybe adding an try catch? When it's unable to parse always reload the config.

**Comment by kangarko** [comment]
Can you please ZIP me your settings.yml?

**Comment by Sikatsu** [comment]
This affects 2.3.2 as well.

Error: https://pastebin.com/GjHQVVUs
The only thing I had to change is remove a few spaces before all keys.

**Comment by martijnpu** [comment]
[settings_bungeecord.zip](https://github.com/kangarko/ChatControl-Pro/files/5077712/settings_bungeecord.zip)
I've the old and the new (fixed by myself). I already told you an solution. If it's a string try Integer.parseString(x);

**Comment by kangarko** [comment]
Found the issue. Previous developer used their own configuration handler unfortunately putting all values as String into config.

To fix, simply remove "" from the numbers such as "2.3" will simply become 2.3. The same for version. Then the problem will go away.
