### ISSUE TITLE
1.16.1: ViaVersion tab-complete

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1846]
Hey, I use ViaVersion and I don't have any issues with tab-complete, any reason why this has now been force disabled?
We use this a lot with PM's and stuff like that..

**Comment by kangarko** [comment]
Sure, if you confirm you have no issues, I removed the automatic disabling of tab-complete, but I left the warning there. We had people reporting kicks with it, along with packet features. It really depends on MC version and other factors though.

**Comment by Sikatsu** [comment]
I can confirm I do not have issues with it at all, so it probably depends on different factors as well.
