### ISSUE TITLE
AFK reminder

### ISSUE THREAD

**Issue by ThisIsOllie** [kangarko/ChatControl-Pro#1847]
I'd like a feature to be added where people, who are trying to talk to someone who's AFK, get notified that they are not available at the moment (the message can be customized and this can be turned off/on if needed).

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
For example, if they were to ask a staff member of a server a question and they didn't reply back they might not know why that is, that's why this feature should be added so that the plugin can tell them that they are not going to respond. Otherwise, they'd just keep trying to get them to talk back to them which probably wouldn't happen as they are not available.

2) What would happen if we won't implement this feature? How's your server being affected?
Not much bad can happen, but this would still be a nice feature to have.

3) If suggesting something new - Can the old system be modified/improved instead?
Well, you can connect this to the Essentials plugin somehow.

**Comment by kangarko** [comment]
Sure, leaving open for future consideration, thanks.

**Comment by martijnpu** [comment]
Why don't you ask essentials for this? The afk status is their part.
So chc would have a specific function only for essentials.

**Comment by ThisIsOllie** [comment]
> Why don't you ask essentials for this? The afk status is their part.
> So chc would have a specific function only for essentials.

I'm so dumb that I didn't think of this myself... It was very late for me when I posted this suggestion. Guess I'll close it?

**Comment by kangarko** [comment]
Yeah makes more sense, I thought you wanted AFK to be added to CHC 👍
