### ISSUE TITLE
1.16.1: Invalid hexcode breaks chat formatting

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1849]
Sooo.. a correct hexcode seems to work, but if you accidently add a dot or the hexcode is invalid: https://pastebin.com/qUp7S8Cf

![image](https://user-images.githubusercontent.com/5664135/90296904-3342eb00-de8d-11ea-8ce5-44d8ad98b195.png)

**Comment by kangarko** [comment]
Thanks, I silenced the errors from invalid HEX syntax.
