### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by MrArcane** [kangarko/ChatControl-Pro#185]
Well today we encountered a crash on my server,

I tried to debug but it seems that it's not my side.

Pastebin: http://pastebin.com/FZ9W2Ahm

Chat Control: 7. 2.9
Spigot: Latest.

Thank you,
Have a nice day,
MrArcane.

**Comment by kangarko** [comment]
Hey,

it appears you were using PlugMan or /reload command. This is unstable and may result in such behaviour in many plugins, not just ChatControl.
