### ISSUE TITLE
1.16.1: Make "/chc adminchat" switch if no arguments are given afterwards.

### ISSUE THREAD

**Issue by martijnpu** [kangarko/ChatControl-Pro#1851]
Hi,

Right now you need to type `/chc adminchat <text>` to say something in the adminchat and `/chc adminchat switch` to switch.
Why isn't `/chc adminchat` the switch command? This was already in v9 and I really liked it. 
This is not only for the adminchat command but also for the bungeechat command.

This change isn't a lot of work and saves some time (and irritation at my server). The command gets easier by this change.

I hope you like this suggestion too,

Regards,
martijnpu

**Comment by AngellitoX** [comment]
Hello, you can actually create your own custom commands to access the adminchat and basically any other ChatControl command. Please use this guide as a reference:

https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands-(Aliases)

In my own network, I use /a <message> to send something to the AdminChat and I use /as to switch, so it's extremely fast :)

**Comment by martijnpu** [comment]
Hi, I understand and I already use aliases. But that's not my question.
To use your example: I want to use `/a <message>` to talk (Already did that) and i want `/a` to switch. I don't want a different command.

**Comment by AngellitoX** [comment]
Probably it could be added to the improvements plan for the future v9 series.

**Comment by martijnpu** [comment]
Could be yes. It already was and my staff and me really liked it.
But this change is less a gamechanger than the color perms update of today, so maybe it can be implemented before the v9?
😃

**Comment by AngellitoX** [comment]
I cannot promise you it will, buy I am going to reopen it so it can be taken into consideration faster, hopefully it will help.

Also, try to consider using an additional command like I did with /as, my admins at least got acustomed to that very fast :D 

Thank you for the suggestions and the good vibes.

**Comment by kangarko** [comment]
I will not be adding this because it can be confusing. I cannot please everyone, keep in mind we have 1000s of users so it must be as clear as possible.

You can hack that in by creating two aliases, something like that: /chc adminchat and /chc adminchat $1 (haven't tested but maybe @AngellitoX can have a look).

Closing, if you have notes please just post below.

**Comment by JohnS19** [comment]
I would also like this. This makes channels much more convenient to use and was one of the reasons why I used ChatControl's channel system rather than using something else.

**Comment by kangarko** [comment]
Understood. We'll bring this feature back in the next release ;)

**Comment by kangarko** [comment]
Please wait for the next release and follow: https://github.com/kangarko/ChatControl-Pro/wiki/Channels#custom-channel-commands
