### ISSUE TITLE
1.16.1/2: BungeeControl Issues

### ISSUE THREAD

**Issue by TNTUP** [kangarko/ChatControl-Pro#1852]
The new update of BungeeControl v2.3.3 with the breaking change about ditching data.txt to keep a list of unique joined players. I liked this approach as I can keep UUIDS up to date or if necessary, editing it.

I tested this new update on another localhosted bungeecord and when I logged the first player on, the file data.db is generated and usually with *.db files is somewhat SQLite compatible. Loaded up SQLite Browser, the sostware says its not a valid db or corrupted. Then I check with Notepad++, I see "{}" inside. Looks like a JSON formatting, maybe not sure.

Usually it should have a UUID in the file but nope... I guess there's an issue somewhere? I guess if a new player joins, it will trigger the New player message everytime as the file still saves "{}".

What database type it should be? If SQLite instead of raw text, please do a converter if thats possible, I have 17K to port over if I need to do that manually in SQLite or JSON or whatever file type^^

**Comment by Sikatsu** [comment]
A converter would be nice. But you also mention it doesn't actually get saved and will trigger again and again?

**Comment by TNTUP** [comment]
> A converter would be nice. But you also mention it doesn't actually get saved and will trigger again and again?

Welp forgot to say that, I tested it 3 times (rebooting bungeecord server)

**Comment by Sikatsu** [comment]
Hmm, will postpone updating to the latest version for now, seem to be some issues here and there

**Comment by TNTUP** [comment]
> Hmm, will postpone updating to the latest version for now, seem to be some issues here and there

I'm using 2.3.2 and it works flawlessy (I hope haha!!) the accents are fixed and no reported issues on my server^^

**Comment by Sikatsu** [comment]
Are you using that with .9 or the .8 from yesterday? ^^

**Comment by TNTUP** [comment]
> Are you using that with .9 or the .8 from yesterday? ^^

The .9 is fine and running on all the servers (no reported issues from now on) and I was using BC 2.2.6 before

**Comment by Sikatsu** [comment]
Ah, because .9 seems to have issues with nickname colors I've seen in another ticket.. that also makes me wait haha

**Comment by TNTUP** [comment]
> Ah, because .9 seems to have issues with nickname colors I've seen in another ticket.. that also makes me wait haha

Ah weird, probably with placeholders with EssentialsX or CMI? I'm using a 3rd party nick plugin, colors are shown in global chat (bungee mode)

**Comment by james090500** [comment]
Also it seems join_message never executes and when First_Join_Message executes it runs as the player viewing the message name:

![image](https://user-images.githubusercontent.com/20372645/90336094-7017fa80-dfd1-11ea-9e35-18094b3c4c3c.png)

Pretty major issue tbh

**Comment by kangarko** [comment]
Thanks, fixed all issues and added a converter!
