### ISSUE TITLE
Bungee_Chat Enabled_By_Default only for certain groups / disable for some groups?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1857]
I use LuckPerms on a BungeeNetwork at the moment and I also use Bungee_Chat.Enabled_By_Default so everyone can talk to each other by default, however there is a certain group of players that I would like to disable Bungee_Chat.Enabled_By_Default and instead automatically put them into a different channel. Is this possible?
I use the latest ChatControlPro and BungeeControl

Thanks

**Comment by kangarko** [comment]
If I add this option to the Group functionality of ChatControl would that be sufficient?

**Comment by LeehamElectronics** [comment]
> If I add this option to the Group functionality of ChatControl would that be sufficient?

Do you mean that I will be able to assign certain "auto_join_channel" permissions to certain groups in order for certain groups to join certain channels automatically?
If so, yes that would be amazing, thanks so much!

**Comment by kangarko** [comment]
Sure, in ChatControl 9.1.0 I will make it so that you can give a special permissions to any user and they will be automatically joined into the bungee chat.
