### ISSUE TITLE
1.16.1: How to display death messages to certain groups/players with permission

### ISSUE THREAD

**Issue by Lukos31** [kangarko/ChatControl-Pro#1860]
I'm trying to create a way to toggle individual players seeing all death messages, preferably by giving a permission to them to see them. While conditions can be added to specify which deaths show up at all, i've had trouble finding ways to control who can see them (Display_To only seems to allow ALL, BOTH, KILLER, and PLAYER).

**Comment by kangarko** [comment]
That is currently not possible, but I am taking this as suggestion thanks!
