### ISSUE TITLE
Paper 1.16.1 - formatting has stopped working

### ISSUE THREAD

**Issue by ZeeRaider** [kangarko/ChatControl-Pro#1861]
Find current log here:
https://pastebin.com/UgKp52KF

The issue is strange, I loaded my server after removing some redundant plugins (multiverse core) and the chat has just entirely stopped inheriting the chat format that I created whilst I was working correctly.

Now the chat just appears as <username> instead of nicely formatted <prefix><suffix><name>.

It seems that something it taking priority over handling the chat function, which is strange.

Really hope someone can help because I really do love Chat Control.

To answer the obvious question - I have format enabled within the formatting yml.

**Comment by ZeeRaider** [comment]
I seem to get this error, regularly in console -

[Mon, 17. Aug 2020 23:23:14 UTC ERROR] Could not pass event AsyncPlayerChatEvent to ChatControl v8.7.9

**Comment by james090500** [comment]
Clearly in the log it states
```
ChatControl could not hook into Citizens as the plugin is disabled! (DO NOT REPORT THIS TO ChatControl, look for errors above and contact support of 'Citizens')
```
Half of your brokens are broken or dont even load you need to look through your log and update them all.

**Comment by AngellitoX** [comment]
Hello, this tickets seems to be solved. Issue is clearly coming from somewhere else.

Closing it for now.
