### ISSUE TITLE
1.16.1 (CC 8.7.9) NoSuchMethodError on plugin reload

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl-Pro#1864]
### Versions:
Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
CC 8.7.9
### Error:
https://pastebin.com/2G8RD3J3
### How this happens:
Just trying to reload the plugin config with /cc reload. First this happended when I set Broadcaster: Enabled: false in messages.yml.
### Recent config:
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5088232/ChatControl.zip)

**Comment by kangarko** [comment]
Thanks, will get patched.
