### ISSUE TITLE
Add color GUIs permissions

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#1868]
At no point do I ever want anyone using magic chat formatting, sometimes I don't want them to have bold to spam chat, now its all one, so its bold, italic and a color... I just want them to use a color and nobody should ever be allowed  to use magic.

**Comment by LogGits** [comment]
I have to agree with the not changing its functionality. I used chat colours and the gui (A donor perk for persistent colours) separately. This change essentially makes my system invalid and would require me to find an alternative plugin for persistent chat colour management which i'd like to avoid. 

Side note: @kangarko can you please reopen #1453 it still happens.

**Comment by Sikatsu** [comment]
If you use chatcontrol.color.{color} you can set stuff like magic or italic to false, and only allow colors.

Anything from this link can be used as replacement behind chatcontrol.color

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html

**Comment by LogGits** [comment]
I am all for a better permission node setup (which should have tiny performance boosts). `chatcontrol.color.{color}` is a much cleaner approach. We need a `chatcontrol.colour.{color}.gui` perm so that we can separate chat colour usage with persistent colours from the gui.

Something that would allow me to use:
`chatcontrol.color.*.gui` as **false** (which doesnt let them use any persistent chatcolours.

With the ability to give individuals permission nodes to override:
`chatcontrol.color.green.gui` **true** (which would give the player the capability of using the green persistent colour while preventing the usage of all other persistent colours)

**Comment by AngellitoX** [comment]
Hello, answering directly to Tom, this can still be done through the permissions and website Sikatsu was really polite to share. You can set individually what type of text you want to allow to your groups. The only thing that has changed here was a major cleanup of the overall permissions which was extremely confusing to most of the active ChatControl users.

As for the `{color}.gui` permissions, I agree that it could be a nice addition to have. Hopefully it will be improved soon.

Thank you all for reaching out your suggestions in the most supportive way.

**Comment by TomLewis** [comment]
@AngellitoX Yes, this ticket was created directly in response to the changelog posted by kangarko, where in that changelog he linked to the list of colors available in Spigot/Paper, this is not what was up for discussion, I am aware of the colors & formatting in Minecraft.

@AngellitoX Please read the changelog here by kangarko https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/update?update=355671

With this in mind you will be able to understand this ticket.

**Comment by AngellitoX** [comment]
I have definitely read the changelog, but probably there's a language barrier on my side. 

I understood you want them to just allow your users to use colors right? Why not just negate the format like bold, magic, etc then?

If you are using LuckPerms just setup `chatcontrol.color.MAGIC` with value `false` and you should be fine.

Isn't that what you're looking for?

**Comment by TomLewis** [comment]
I know how to use LuckPerms, please do not be patronizing.

You have misunderstood.

We need the GUI permission.

**Comment by AngellitoX** [comment]
Ah, that's extremely different from your first statement. I agree that we need the GUI permission and as I mentioned, I hope this can be readded soon :) 

Pinging @kangarko so he can bring the party around.

**Comment by TomLewis** [comment]
Sounds good.

**Comment by Rillan99** [comment]
Can you please let us know when this issue is solved?

**Comment by kangarko** [comment]
Tonight
