### ISSUE TITLE
Prefixes and custom plugin

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#187]
Hey! So my developer has made a custom plugin for classes. It uses prefixes for each class by hooking into PermissionEX for prefixes. When ChatControl is disabled prefixes do work. But when I enable chat control's formatting, it doesn't. My developer does not want to look into your plugin's code because quoting him "It's unethical(I agree), and you need to spend days to learn how his plugin functions". Any ideas, or ways you can help me? I would be happy to share source code with you since I don't think you would do much with it but I don't think you're gonna waste your time on that to improve his work...

P.S. And yes, I do have formats.normal_format.parts.prefix set to {pl_prefix}.

**Comment by kangarko** [comment]
Hey,

try changing **Listener_Priority.Formatter**, as described per:
https://github.com/kangarko/ChatControl/wiki/Pro-Information#townyfactions-rules-channels-or-chat-dont-show-or-show-when-not-supposed-to

**Comment by kangarko** [comment]
Closing. Feel free to comment below if you have any questions.
