### ISSUE TITLE
1.16.2 PlaceholderAPI unparse

### ISSUE THREAD

**Issue by msgdw** [kangarko/ChatControl-Pro#1876]
Problems I encountered when using PlayerTitle
url: https://www.spigotmc.org/resources/playertitle.78048/

I set the chat format to {playertitle_use} 
unparse

And PlaceholderAPI commands and other plugins can be

**Comment by AngellitoX** [comment]
Hello, can you please explain a little bit your problem? Error logs?

**Comment by msgdw** [comment]
no error logs
unparse placeholder {playertitle_use}

**Comment by AngellitoX** [comment]
What happens if you try `/papi parse me {playertitle_use}` 
Can you show screenshot?

**Comment by msgdw** [comment]
/papi parse me %playertitle_use%
is right

/papi parse me {playertitle_use} is wrong grammar
but ccp use {playertitle_use} 

I can't upload screenshot right now
I have to wait until tomorrow
I'm not in front of the computer

**Comment by kangarko** [comment]
That is correct, for ChatControl you must use the {} syntax, but in PlaceholderAPI just use %% one.
