### ISSUE TITLE
1.8.9: Memory Leak, Worlds referenced although they have already been downloaded previously.

### ISSUE THREAD

**Issue by Tauchet** [kangarko/ChatControl-Pro#1877]
Hello.

In one of our custom plugins we make world changes in real time, that is, unload and load, our situation is that we have noticed that after passing a few reset maps in the ChatControl PRO 8.7.12 plugin, a reference of the Therefore, the memory keeps it saved and it is not possible to eliminate it completely, in addition, this leads to the use of the Garbage Collection, which would make the memory and the CPU take to the maximum and after a while the server would die for those references that remain in memory, we want to find a viable solution or suddenly know which version exactly solves this error.

Example:
https://imgur.com/a/dSFNmo9

**Comment by kangarko** [comment]
Thanks, I replaced Location with a bare String to mitigate that.
