### ISSUE TITLE
1.16.1: Custom Variable Hover

### ISSUE THREAD

**Issue by Brickfoot7** [kangarko/ChatControl-Pro#1878]
I'm trying to define a custom variable that displays whether they have mail. However, I cannot get the hover component to work. Nothing I try results in anything being displayed on hover.

```
Key: '{mail}'
Value: |-
  hasMail();

  function hasMail () {
   var mail = "{cmi_user_mail_count}"
      return (mail > 0 ? "&2✉" : "&c✉");
  }
Hover: |-
  hasMail();

  function hasMail () {
   var mail = "{cmi_user_mail_count}"
      return (mail > 0 ? "&2You have Mail!" : "&cNothing in here...");
  }
```

Even a more simplistic approach like: `Hover: ["Mail"]` doesn't work.

While I haven't tried in awhile, I'm not sure if any other optional variables like Run_Command work either.

**Comment by kangarko** [comment]
Variables have been backported from ChatControl 9 which had its development reset. This feature will get readded with the arrival of ChatControl 9.1.
