### ISSUE TITLE
1.16.1 how to spy on non-signed books?

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl-Pro#1880]
The Spy configuration contains a part that allows you to spy on books.
This only seems to work when a book is signed and closed. 
is it also possible to sky on a book that is not yet signed and closed ?

Bit that is in the settings.yml
  /# Spy on books ?
  Books: true

**Comment by kangarko** [comment]
Hi and thanks for your questions!

I will take that as a suggestion for the future 👍
