### ISSUE TITLE
1.16.1: Unknown Error, Console Error with ErrorYaml log

### ISSUE THREAD

**Issue by Mohamad82Bz** [kangarko/ChatControl-Pro#1881]
Hi there, 

Recently I got an error in my console and it said I should report this to developers, when this error happened my server delayed (lagged) a bit. It happens sometimes (very few)

Console Error: https://hastebin.com/gohalirubo.sql
ErrorYaml (in chatcontrol folder) Error: https://hastebin.com/udurogobat.coffeescript

**Comment by kangarko** [comment]
Thanks, please use the next version and let me know when that happens again, I have added more informative messages there.
