### ISSUE TITLE
Formatter support

### ISSUE THREAD

**Issue by CozyLeprechaun94** [kangarko/ChatControl-Pro#1883]
Mc version: 1.12.2

Question:

Hello guys,
Do you guys have formatters and tooltips that support placehoderapi

Like deluxechat and ezchat.

When you hover over a players name.
You can see many stats etc

**Comment by anar4732** [comment]
CHC supports PAPI check default formatter.yml file

**Comment by kangarko** [comment]
Yes we support PAPI, just use {syntax} not %% one.

See https://github.com/kangarko/ChatControl-Pro/wiki/Variables
