### ISSUE TITLE
1.16.1: How to add custom deathmessages to DiscordSRV?

### ISSUE THREAD

**Issue by rybuilder23** [kangarko/ChatControl-Pro#1884]
Hello my Question is how to link the custom deathessages to DiscordSRV?

I tried the following.

https://imgur.com/hP66tY3

https://imgur.com/GujTJJ7

the second gave me this eror
https://pastebin.com/NF6et6yG
so i take that it doesth work like that?

thank you in advanced and i have all the time so i can wait.

-rybuilder2

**Comment by kangarko** [comment]
Use the channel name, not ID. Have you linked it using DiscordSRV as well?

**Comment by kangarko** [comment]
Closing in good faith this will get fixed when you place the channel as an ID to DiscordSRV config. If not please comment below.
