### ISSUE TITLE
1.15.2: chatcontrol.bypass.ignore is not enforced when user has permission ( 8.7.12 )

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#1886]
**Version:** Paper 1.15.2
**CHC-Pro:** 8.7.12 ( cross bungee enabled )

**Description:**
`chatcontrol.bypass.ignore` is not being enforced when user has user has the permission.

```
Perm: chatcontrol.bypass.ignore
Info: Enforce sending a message to the player that is ignoring the sender.
```

**Screenshot:**
https://prnt.sc/u6f4fo

**Steps:**
1) Give owner permission: `chatcontrol.bypass.ignore` 
2) Ignore the owner account from a different user
3) Chat from owner account
4) User does not see the message

**Comment by kangarko** [comment]
Just tested on the next version, appears to be working as expected:

![a](https://i.imgur.com/42OIC34.png)

**Comment by AmazedMender16** [comment]
@kangarko You're sending a PM? I'm talking about regular chat.. 2 different permissions as well.

**Comment by kangarko** [comment]
Oh sorry, my bad. Is this happening in cross-server chat channels?

**Comment by AmazedMender16** [comment]
@kangarko I'm not using channels ( not configured ), just regular chat on single server.
Bungee is enabled for cross server PM's.

**Comment by kangarko** [comment]
Okay so just tested on a single server (Bungee does not send normal chat elsewhere), still cannot reproduce:

![a](https://i.imgur.com/84DhwYD.png)

Please wait for the next version to report if the problem persists.

**Comment by AmazedMender16** [comment]
I can still replicate it on demand on 8.8.0-BETA
https://prnt.sc/u821l2

Owner has `chatcontrol.bypass.ignore` and users cannot see the text from the owner after ignoring.

**Comment by AmazedMender16** [comment]
@kangarko I can still replicate it on demand on 8.8.0-BETA
https://prnt.sc/u821l2

Owner has `chatcontrol.bypass.ignore` and users cannot see the text from the owner after ignoring.

**Comment by AmazedMender16** [comment]
@kangarko can we have an update on this?

**Comment by kangarko** [comment]
Hi, no I had to leave my workspace. This week or the next soonest. Thanks!

**Comment by kangarko** [comment]
Hi there, I am back. Tested again with the following:

- Standard chat turned on in formatting.yml (no bungee)
- Using /ignore from ChatControl only

Unfortunately the bypass permission did work properly:

![a](https://i.imgur.com/sw7H7Cc.gif)

What did I miss please? Please ZIP me your whole folder as it is now so I can test using your setup.

**Comment by AmazedMender16** [comment]
@kangarko files have been shared with you privately via SpigotMC, message title: `[1886] 1.15.2: chatcontrol.bypass.ignore is not enforced when user has permission ( 8.7.12 )`
I just tried this again with just:
ChatControl
LuckPerms
Protocollib
Vault
ViaVersion
WorldBorder
WorldGuard
WorldEdit

![Screenshot_1013](https://user-images.githubusercontent.com/14223424/92488370-bfc39d80-f1ee-11ea-831c-31056528b1c8.png)

**Comment by kangarko** [comment]
Thanks, finally fixed! The problem was in a special case when both channels and formatting were disabled.
