### ISSUE TITLE
1.16.2: Join/Quit message {player_displayname} placeholder using incorrect name color.

### ISSUE THREAD

**Issue by rtcabooservb** [kangarko/ChatControl-Pro#1889]
Paper dev 152 (Spigot 1.16.2)
ChatControl Pro 8.7.12
PlaceholderAPI dev 108

I recently switched my LuckPerms set prefix colors in various groups from using characters/numbers to HEX, i.e. ``'&4'`` to ``'&#B22222'``. The new HEX color prefix appears perfectly fine in public chat. However I'm running into an issue where the join/quit messages are not using the HEX displayname color properly.

When I type ``/papi parse <name> %player_displayname%``, it properly shows my username and hex color.
![link](https://i.imgur.com/Fj7WrTP.png)

When I login or quit, it is not displaying the proper color. The proper color is also not displayed for other users who login that aren't Admin/OP but in various other groups with HEX prefixes. I appear green as Admin/OP, most others appear white.
![link2](https://i.imgur.com/ZU8Sfpb.png)

```
Join_Message:
  Enabled: true
  Ignore_Vanished: false
  Delay_Ticks: 5
  Message: '[JSON] ["",{"text":"[","color":"dark_gray"},{"text":"+","color":"dark_green"},{"text":"]
    ","color":"dark_gray"},{"text":"{player_displayname} ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"{player}"}]}},"color":"reset"},{"text":"has
    ","color":"white"},{"text":"joined ","color":"dark_green"},{"text":"the server.","color":"white"}]'
Quit_Message:
  Enabled: true
  Ignore_Vanished: false
  Message: '[JSON] ["",{"text":"[","color":"dark_gray"},{"text":"-","color":"dark_red"},{"text":"]
    ","color":"dark_gray"},{"text":"{player_displayname} ","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"{player}"}]}},"color":"reset"},{"text":"has
    ","color":"white"},{"text":"left ","color":"dark_red"},{"text":"the server.","color":"white"}]'
```

**Comment by kangarko** [comment]
Thank you, this should be solved in the next release.

**Comment by rtcabooservb** [comment]
Resolved as of ChatControl 8.8.0-BETA? Or a future version? As it doesn't seem to be fixed with the new one just published. I logged in with a black username now and another player logged in with an aqua one instead of his group prefix.

![link3](https://i.imgur.com/4nY6gOr.png)

Here is another example with someone logging in with a white username instead of his HEX color.

![link4](https://i.imgur.com/px1dEIX.png)

Using ChatControl's own ``{display_name}`` placeholder also has this problem. And of course again, parsing ``%player_displayname%``with PAPI does show the correct color. :(

**Comment by rtcabooservb** [comment]
@kangarko I think the issue might be ChatControl taking the ending character from the HEX code and using that for the join/quit message. As the color used in player join/quits contain a character part of their hex code.

For example my hex being set to ``AA0000`` had me login with a black name because 0 is in the HEX string and &0 corresponds to black. First image example above when my hex was ``B22222``, my name appeared green because &2 is green. Same with players who logged in with white and other color names. Their HEX ending is what color ChatControl ended up using instead of the actual HEX color.

**Comment by kangarko** [comment]
Thank you, unfortunately I am out of workspace, will see what I can do, if not then it will get fixed by weekend or the start of the next week.

**Comment by kangarko** [comment]
I attempted to make a fix, however with the current system it will always be troublesome. It should work for you in the next version when you migrate the raw JSON into formatting.yml file and reference to the name of the format. I simply tested using the default chat format:

![a](https://i.imgur.com/iceOOSG.png)

**Comment by rtcabooservb** [comment]
It still isn't fixed in JSON messages, but moving it to its own formatting configuration does fix it, thanks.
