### ISSUE TITLE
1.16.2 - Formatting in chat not working

### ISSUE THREAD

**Issue by ZeeRaider** [kangarko/ChatControl-Pro#1890]
I’ve just updated to Paper 1.16.2 and prior to this, CCP was working perfectly.
Now, regardless of what I do, formatting isn’t working at all.

The chat just shows the generic <playername> 

Is there a dev build for CCP? I notice that CC base free version states 1.16.2 support but, CCP doesn’t state the same.

I can post a paste but it does really tell you much because the plugin is working for everything except formatting.

When you drop back to 1.16.1 the format works fine again.

Another reason I don’t always post the paste immediately is because some plugins are have errors, these are known errors and not conflicting with anything but - as soon as I posted last time, I was told to go and fix those errors first, which is impossible. My issue is with CCP formatting,  not my other plugins, I’ll happily paste a log but if you do request it, please don’t comment on other unrelated errors.
(Staring this here because last time I requested support it was closed with a fix error first message before I even had a chance to reply and explain why I had said errors)

Many thanks in advance for the support.

**Comment by kangarko** [comment]
Hi Zee,

Apology that last time you did not receive a proper help, may you please link to it for reference?

I am going to update the plugin today, please retest using the next version, chances are it already has been fixed.

Matej

**Comment by kangarko** [comment]
Yes please, if it will still be broken on the next version, please attach me your full startup log. I will only comment on the relevant parts of it.

**Comment by ZeeRaider** [comment]
Thanks Kangol, I'm gonna mark this as fixed.
For your reference, the issue was BKcommonlib, they have released a dev build that now fixes the issue.

Thank-you for the reply and when I get a few mins, I'll go find the support ticket I referenced.

**Comment by ZeeRaider** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/1861

**Comment by kangarko** [comment]
Oh I see, well in these cases there is an extremely high likelihood of the other plugin causing the integration to crash which then crashes our plugin as well. That is why we always recommend to clear up all console errors before solving an issue.

Please test the next upcoming version soon.

**Comment by ZeeRaider** [comment]
I completely understand that having errors is far from ideal (hell, I’ve even signed up to your course to improve at fixing certain things myself).
I just think that maybe if people reply saying that something should be fixed - give someone a chance to reply because, there might be a good reason why things aren’t working.
The issue with mine is. I have a very complex set-up and I’m slowly trying to replace all of the conflicting plugins but, it’s hard finding alternatives that work and don’t conflict with others too.

But yes, things do seem to be working now and the closer that I get to full production, the less errors I get.

Anyway, thanks for your support and the constant fantastic work on the great plugins!

**Comment by kangarko** [comment]
Thank you for your kind words! I apology you did not get the proper support you deserved, in fact I have not seen that ticket at all since it was closed by one of our team members. I'll ensure to see closed tickets as well next time just in case I can help more.
