### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl-Pro#1892]
Hey, We're on a survival server where players can join from 1.13.2-1.16.2. But we do however want to recommend players who join in a different version to join in the latest version. 

**Is there a way to make custom join messages for those players?**

**Comment by kangarko** [comment]
Possibly, if the plugin such as ViaVersion has an API you can code a custom JavaScript variable that will connect to it a condition like this:

![a](https://i.imgur.com/lyP6dRp.png)

You can just google "Java Nashorn" tutorial if you are a developer to learn how to get a Java class into JavaScript.

Matej
