### ISSUE TITLE
1.16.2: Some placeholders will not parse in CCP despite /papi parse working.

### ISSUE THREAD

**Issue by bartymc** [kangarko/ChatControl-Pro#1894]
Placeholders from this plugin: 
https://www.spigotmc.org/resources/playtimes-check-players-playtime-server-uptime.58858/

PAPI will parse this placeholder correctly:
![image](https://user-images.githubusercontent.com/42015460/91592751-04b51d80-e92d-11ea-9536-edeffec3985c.png)

ChatControl Pro not parsing the placeholder:
![image](https://user-images.githubusercontent.com/42015460/91592867-2f06db00-e92d-11ea-89c4-ac98ed536291.png)

ChatControl Version: ChatControl-8.8.0-BETA
PAPI Version: 2.10.9

**Comment by AngellitoX** [comment]
Hello barty, just to make sure, I see a slight difference on using capital letters on your second screenshot, have you tested it with all lowercase?

If so, I'm sure we can take a look to it for the next release. 

It's also important to mention that the next build will be released until next Friday approximately, so I'd appreciate your patience.

Thank you!
Angel from MineAcademy.org

**Comment by bartymc** [comment]
The issue is case insensitive, tried both and neither worked. I narrowed the issue down to using a newer version of PlaceholderAPI, we have since downgraded to 2.10.6 and the issue disappeared.

**Comment by AngellitoX** [comment]
I see, so I'm marking this as solved. Thank you barty! If you need anything else, consider commenting below and I would reopen it with no problem.

**Comment by kangarko** [comment]
What PAPI did cause this? What expansion pack?
