### ISSUE TITLE
1.16.2: 8.8.0 - new channel issues

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1898]
Heya, using the channel setup from Matej,

  tc:
  - channel send town $1-
  nc:
  - channel send nation $1-
  g:
  - channel send global $1-

Channel write is set to 1. We are having an issue where players can write in all channels at once. This time they can toggle out of it, its just not forcing 1 write.

![aidschat](https://user-images.githubusercontent.com/34926510/91633375-716ffc80-e9ad-11ea-9102-8330a5af75a2.PNG)

**Comment by kangarko** [comment]
How to reproduce this please? Shall I just run these three commands then players will join three channels in write mode instead of them switching modes to read for the other channels, keeping write in just one?

**Comment by Kbryst** [comment]
I believe they toggled the channel and the channel before it did not "toggle off".

So talking in global
run command: /tc
Now sending message in both global and tc
run command: /nc
Now sending message in all 3 channels.

**Comment by AngellitoX** [comment]
Hello, just giving a proper follow-up, we will take a look to this in the next couple of days. Matej had an emergency and is MIA at the moment. Hope you understand.

If anything helps, you could add a second command to your alias which could make you leave the previous channel to avoid talking in all of them. Sort of a security workaround. Hopefully that might work while a proper fix is given.

Thank you for the patience in advance.
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Hi there, please use the next version of ChatControl. Let me know if the problem will still appear.

**Comment by Kbryst** [comment]
Do you mean the one that's posted today or a newer one?

**Comment by kangarko** [comment]
You can use the latest version that is now available.

Just to be clear, so you have this in commands.yml:

```yaml
  tc:
  - channel send town $1-
  nc:
  - channel send nation $1-
  g:
  - channel send global $1-
```

Because neither of those commands will actually toggle anything, those commands only send messages to a channel. It will not affect your channel status.

**Comment by Kbryst** [comment]
I have it exactly as you have it there, it is still sending double messages on the latest version.

**Comment by Kbryst** [comment]
Additional, now my players also cannot see the messages in the channel unless they are toggled into the channel.

Which still posts double messages across channels.

**Comment by JohnS19** [comment]
I believe it's putting them into the write mode using **channel send global** instead of joining them into the channel. So the player gets entered into write mode for multiple channels. It might even remove the players from the read mode of the old channel instead write mode.

**Comment by Kbryst** [comment]
It sets their mode and removes them from every other channel.

I had to roll back to a previous version, but this version is causing other issues. Is there by chance an update to this issue yet?

**Comment by kangarko** [comment]
Thanks, I solved running "/channel send <channel>" without the message specified joining duplicate channels. The command now will forcefully join you into the channel in write mode if you don't specify the message.

New version will be out tonight.
