### ISSUE TITLE
8.8.0 Sign spy debug message is left in the code

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl-Pro#1899]
### Description
Whenever a player places a sign all its content is printed into the console.

**Comment by AngellitoX** [comment]
Interesting issue, we will take a look to this in the next couple of days. Thank you for reporting it!

Angel from MineAcademy.org

**Comment by kangarko** [comment]
Doesn't look like it's coming from CHC.

What is the message exactly? Please remove CHC to see if it persists. Closing in good faith this will get resolved, if not comment below with that message.
