### ISSUE TITLE
Can't use /gm with essentials.gamemode

### ISSUE THREAD

**Issue by tara81** [kangarko/ChatControl-Pro#19]
I tried everything

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/191167/ChatControl.zip)

**Comment by tara81** [comment]
I also added the bypass perm

**Comment by EvilOlaf** [comment]
Why do you think this is an issue with CHC? There must be kind a evidence that CHC interfers like error message and so on. Please provide more information.

**Comment by kangarko** [comment]
I see you have commented out the rule in commands.txt that prevents /gm. There are no other cases where the plugin does that, so I don't see it being from ChatControl anymore.

**Comment by tara81** [comment]
Well when i got chc is when it started blocking it, lol.

**Comment by EvilOlaf** [comment]
That's odd. I use EssentialsX with CHC Pro in my testing environment and did not get any response that the gm command would not work.
Do you use EssentialsX as well or any other version of Essentials?

**Comment by kangarko** [comment]
Not caused by ChatControl. Check your rules/commands.txt if you have a rule for that, if not, then it's not this plugin.
