### ISSUE TITLE
DeluxeChat / Channel Integration Issues

### ISSUE THREAD

**Issue by Zendrex** [kangarko/ChatControl-Pro#190]
Long story short, trying to get the channel features from CC (as well as the filter, etc) to work with DeluxeChat, however CCP is forcefully taking over the format every time. If possible, I would love to see the ability to just use the DeluxeChat formatting work WITH CCP. For example, if a user is talking normally on the server, no extra prefix shows, however if they are talking in a staff channel, it shows a prefix or whatever is defined. I know you have plans to make DC work with CCP, however if there is any method in the meantime that can work, please let me know.

-Zendrex

**Comment by kangarko** [comment]
Hey,

do you have chat formatter enabled in DeluxeChat, or in ChatControl? If you have both, it will be incompatible.

Also please try changing priorities as specified on https://github.com/kangarko/ChatControl/wiki/Pro-Information#common-pro-issues

**Comment by Zendrex** [comment]
I have tried changing the formatting to false, as well as the priority all settings. I believe it has to do with channels taking priority regardless of anything else.

**Comment by kangarko** [comment]
Oh incase you're using channels, try changing Listener_Priority.Formatter to MONITOR or LOWEST.

**Comment by Zendrex** [comment]
Also, I thought of a way that may help in channels working with DC as wel. I'm not aware of any placeholders from CCP. Maybe allow for some that can display if you are sending a message in a specific channel or not? (Think of this to allow custom place sets on DC's end since you both can't format the chat like that.

**Comment by kangarko** [comment]
ChatControl does have placeholders but they are not available outside the plugin.

If you are using Channels from ChatControl + formatter from DeluxeChat, it will be incompatible, I am sorry.

**Comment by Zendrex** [comment]
I feel like we are doing telephone tag here lol. Have to run for a bit, however in a couple hours I will try and return with my results.

**Comment by Zendrex** [comment]
Why would something like that be incompatible? Simply use CCP's channel system (without applying any format), and let whatever other formatting plugin like DeluxeChat handle the formatting.

**Comment by Zendrex** [comment]
I'm just going to drop DeluxeChat. As much as I love it, I would rather have channel functionality and work the harder way to make my formatting. Awesome plugin, cant wait for the discord integration :D

**Comment by kangarko** [comment]
The way formatter work, for both ChatControl and DeluxeChat, is that they cancel the chat event. The chat event is the core essential to making it compatible, but since it doesn't support JSON, it must be cancelled and the message handled in own way, unique to those two plugins.

**Comment by TMGaby** [comment]
The channel feature will be added on DC 2.0, iirc 👍
