### ISSUE TITLE
1.16.2 - CMI Nickname support

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1901]
Just reporting that the CMI support for nicknames (in /tell and all that) does not work. 
It does not register the nicknames, and it also now is not tab completing regular names.

Paper spigot 1.16.2
Chatcontrol pro 8.8.0
CMI 8.7.6.9

**Comment by AngellitoX** [comment]
Hello there!

Thank you for letting us know. We will take a look to it in the next couple of days.

Angel from MineAcademy.org

**Comment by kangarko** [comment]
Thanks, already mentioned in https://github.com/kangarko/ChatControl-Pro/issues/1869, will get solved in a couple of days.
