### ISSUE TITLE
1.16.1 Error when using /ch help

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#1902]
Minecraft: 1.16.1
Paper: 138
CCP: 8.8.0

when i use the command /ch help, /channel help, it returns an error.
https://pastebin.com/87HgiaMC

**Comment by AngellitoX** [comment]
Hello! Woops, looks like Matej forgot to add something. A fix will come in the next couple of days.

Thank you for letting us know.
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Thanky, will be fixed.
