### ISSUE TITLE
1.16.2: Chat color issues

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl-Pro#1905]
We are having issues with chatcolors in  version 8.8.0-BETA. We want to slightly give ranks colors. We've given them alot of permissions but they still don't have permission to use a certain color. They can open the /cc color menu, but there doesn't show a color. We've given these permissions:
- chatcontrol.command.color.gui
- chatcontrol.command.color
- chatcontrol.chat.format.color.white
- chatcontrol.command.color.gui.white
- chatcontrol.command.color.gui.green

What are we missing?

**Comment by WarnDangerous** [comment]
Same on paper 1.12.2

**Comment by NerdyBirder** [comment]
We are having the same issue and I have tried all the permissions I could find to fix it. When players try the /chc color command they only see a barrier block in the middle of the gui that says "no permissions".

**Comment by kangarko** [comment]
Hi @WarnDangerous  and @NerdyBirder, colors have changed in 8.8.0, please see the changelog.

Now, these permissions are effective:

- chatcontrol.command.color
- chatcontrol.color.gui.white
- chatcontrol.color.gui.green
