### ISSUE TITLE
1.16.2: Chat spam results in recurring issue...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1907]
Player is now getting routinely kicked off the server and this is many, MANY minutes after the event... the event during which ChatControl took no action at all as far as I could tell.  After I'd kicked the player myself, they stopped on their own.  Then later they said something that got caught by the chat filter and ChatControl floods my logs with all sorts of fun errors while accusing the player of hacking and kicking them off the server again.

This is my latest.log... including the spammy portion which I believe started the mess to begin with (from player Aylr):
https://pastebin.com/6a0RarL1

The corresponding error.log is almost 6mb uncompressed so probably a bit much for even my prolevel pastebin account.
[error.zip](https://github.com/kangarko/ChatControl-Pro/files/5147493/error.zip)

v8.8.0-BETA
paper-158

**Comment by AngellitoX** [comment]
Hello there! Nice to see you again.

Interesting issue, are you using the MySQL feature? Probably disabling it at least for now might help to avoid the issue temporary.

However, we will take a look to it promptly on the next couple of days.

Thank you!
Angel from MineAcademy.org

**Comment by mrcoffee1026** [comment]
Not so sure, it happened again without the preliminary spam which I thought was the trigger... and a few users griped to me that the server had crashed since that's what they believed had happened, that had NOT happened... but in the midst of all of that consol spam every user on the server had been kicked off, including myself, so the effect was the same.

**Comment by kangarko** [comment]
Thanks, should be mitigated in the next release.

**Comment by kangarko** [comment]
*Should = I tested it without errors, save/load of mysql on 2k db entries, put some data like channels and chat colors into it and it saved / loaded properly.

If there will be more issues, please set Debug to [mysql] and post the output together with the error and the console debug mysql messages.
