### ISSUE TITLE
1.16.1: Weird Error

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#1908]
i saw this error a while ago. it happened for a player while i was offline and i have no clue if it affected them in any way.
looks like the error repeats for a while, but this is the copy-paste of the error log.

https://pastebin.com/jNpVumsC

**Comment by AngellitoX** [comment]
Hello there! Thanks a lot for reporting it. It looks like it's a 8.8.0-BETA issue. This was already reported on #1907 
I'm closing this ticket in favor of that one. 

Angel from MineAcademy.org
