### ISSUE TITLE
1.16.2 Crash

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#1909]
Using paper 1.16.2 with chatcontrolpro v8.7.12

https://pastebin.com/DdRfriUd
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5154559/ChatControl.zip)
[2020-09-01-4.log](https://github.com/kangarko/ChatControl-Pro/files/5154565/2020-09-01-4.log)

**Comment by kangarko** [comment]
Thanks, will be fixed in the next release. If you will still experience it, just post below.
