### ISSUE TITLE
"/ch set"-message bugged. 

### ISSUE THREAD

**Issue by SilberRegen** [kangarko/ChatControl-Pro#191]
The command works fine, but it gives a misleading notification to the user.

If "SilberRegen" sets "Player1"'s channel to "example" it will tell "SilberRegen":
 "The player SilberRegen is now writing in example channel."

If the same command is executed via console it will narrate:
"The player server is now writing in example channel."

It does the correct thing though and sets "Player1"'s channel.

**Comment by kangarko** [comment]
Thank you for reporting. Confirmed & will be fixed at soonest opportunity.

**Comment by kangarko** [comment]
Fixed in the latest version. A new release will be available tonight.
