### ISSUE TITLE
1.16.2: Color Permissions Inconsistencies

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1910]
It appears that the advertised permissions dont works as intended. Here are some inconsistencies:
- `chatcontrol.gui.color` is not a permission node nor does it do anything (even though the update says that's the permission)
- `chatcontrol.color.*` gives all permissions even gui permissions because `chatcontrol.color.gui.{color}` is apparently a thing. 

Solution to the 2nd one would be to update the update post to mention that the gui perm is `chatcontrol.color.gui.{colour}`

Paper 1.16.2 build 174.
Chatcontrol build 8.8.0-BETA

**Comment by AngellitoX** [comment]
Hello there! Thank you very much for noticing, we will be working on it as soon as possible!

Angel from MineAcademy.org

**Comment by kangarko** [comment]
You're right: chatcontrol.gui.color does not exist. I will change the chatcontrol.color.gui.{color} into chatcontrol.gui.color.{color} to the next version to mitigate this.
