### ISSUE TITLE
Database generating exception

### ISSUE THREAD

**Issue by Danielpeter-99** [kangarko/ChatControl-Pro#1911]
I get the following exception on booting up:

_>.... [16:58:35 WARN]: [ChatControl] Task #738 for ChatControl v8.8.1-BETA generated an exception
org.mineacademy.chatcontrol.final.nul. .bG: Report / Malformed configuration! Key 'Players.joaosc2007j.Last_Active' in data.db must be Long but got MemorySection: 'MemorySection[path='Players.joaosc2007j.Last_Active', root='YamlConfiguration']'
at org.mineacademy.chatcontrol.final.nul. .dG.a(SourceFile:1590) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dG.h(SourceFile:568) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dG.q(SourceFile:739) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .s.k(SourceFile:175) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Tuinity-"126d3cc"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Tuinity-"126d3cc"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:917) ~[patched_1.15.2.jar:git-Tuinity-"126d3cc"]
at java.lang.Thread.run(Thread.java:834) [?:?]_

This does not prevent the chat from working but I wanted to make sure you are aware of it.

**Comment by kangarko** [comment]
Open data.db with notepad++, locate joaosc2007j, delete that section but please send it to me here first for inspection before you remove it.

**Comment by Danielpeter-99** [comment]
[data.db.zip](https://github.com/kangarko/ChatControl-Pro/files/5170344/data.db.zip)

Here you are.

I have completely deleted database to generate a new one instead of editing just to be safe.

**Comment by kangarko** [comment]
Have you edited it? Seems it contained wrong section data. Nevermind, regenerating it should fix that.

**Comment by Danielpeter-99** [comment]
The one I sent you has no editions on it, to generate the new one I only renamed the old one to _data.db.old_

**Comment by kangarko** [comment]
Very strange, let me know if that happens again. Thanks. You can still use your data.db if you want, just use Notepad+, find the following string (set mode to Extended) and remove the whole section. You had two invalid sections in total where there was a map instead of a number:

![a](https://i.imgur.com/whltt7C.png)

**Comment by Danielpeter-99** [comment]
@kangarko 
The issue has repeated, I don't believe it is the same exact issue but its another issue with the database, randomly throwing errors and closing out CHC
[https://hasteb.in/eduhiqud.md](url)
[data.db.old.zip](https://github.com/kangarko/ChatControl-Pro/files/5184794/data.db.old.zip)
It happened on our lobby this time

**Comment by kangarko** [comment]
I apology, there has been a problem with warn&point system when saving to MySQL. I was not able to open your hastebin (please use pastebin next time) but I assume next version will solve your issue. If not, just use pastebin and comment below. Thank you.
