### ISSUE TITLE
1.8.8: Problem with Condition Format Part.

### ISSUE THREAD

**Issue by JorgeSilvarredonda** [kangarko/ChatControl-Pro#1912]
Im trying to setup the ranked formats, but one clan part is not working as intended, i want to make a clan part where if a player isnt in a clan, dont show the the clan part, and im making these so if the {clan_name} has more or less than 7 caracters, dont return the clan part in the chat.

`Clan_default:
        Message: "&8[&a{clans_name}&8] "
        Condition: |-
          getClan(); // call the function below that returns the tag or prefix

          function getClan() {
          // remplazar nombre de clan
            var clan = "{clans_name}";
     
            if (clan.length != 7){
              return true;
            }
            else{
              return false
            }
          }
        Sender_Permission: "chat.clan"`

I gave the permission to all players, anv the part is still printedIn even if the player doesnt have a Clan.

**Comment by kangarko** [comment]
Your permission in the script says clans_name but it should be _clan_name_ only without the -s.

**Comment by JorgeSilvarredonda** [comment]
Amm, im using AdvancedClans, and it is the right placeholder.
http://prntscr.com/ub27xd (Here i can show u)

**Comment by JorgeSilvarredonda** [comment]
I still need help, pls.

**Comment by JorgeSilvarredonda** [comment]
@AngellitoX Could u take a look a this please?

**Comment by kangarko** [comment]
@JorgeSilvarredonda I'll have a look within 24 hours ;)

**Comment by kangarko** [comment]
Hi there, are you using PlaceholderAPI to get these placeholders?

There must be a problem in the `clan.length != 7` of the script. You can use the print() function in the script to discover what the program actually sees:

![a](https://i.imgur.com/IpbH0qS.png)

Same for the other variable.

**Comment by JorgeSilvarredonda** [comment]
Okey, that worked, thx!!
