### ISSUE TITLE
Has anyone else been having trouble with tab complete since the recent update?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#1913]
Minecraft: 1.16.2
Paper: 178
CCP: 8.8.1

ever since around the time i got the recent update (shortly after it released) the tab complete feature has been dysfunctional while CMI is installed.
this issue is present for most of my plugins. all of the vanilla commands seem to have tab complete intact. worldedit tab complete is intact, auction house tab complete is intact, etc.

when i uninstall CMI, the tab complete seems to work perfectly again.
but i disabled the majority of CMIs chat features, including any tab complete settings. i've been using both plugins together for weeks and there has not been an issue with tab complete until the past day or two.

i haven't noticed anything in the server logs that sheds any light on this issue. unless i am missing something?

___________________________________

the situation seems like this:

i confirmed that CCP handles tab complete perfectly, when CMI is uninstalled. when CMI is installed, that changes for some reason.
it doesn't make any sense for CCP's tab complete to stop working just because another plugin is installed. know what i mean?

i already talked to the CMI people about it but they showed that tab complete still works when they use cmi.

____________________________________

i'm not trying to point fingers here. i'm not 100% sure what's causing this issue. i'm just trying to get some information flowing in attempts to figure this out. i can't do much more testing at the moment because i am getting players on my server.

has anyone experienced similar or the same issues? anyone have a solution or insight?

**Comment by Danielpeter-99** [comment]
Do you have AuctionHouse? If so, what version?

**Comment by KasearMC** [comment]
i am doing a bit more testing to see if some light can be shed on this issue.

With CCP (Chat Control Pro), CMI (Content Management Interface) and AH (Auction House) installed, TAB complete does not work.
When I turn off CCP Packets (which apparently controls the TAB complete feature), the result is the same. TAB complete does not work.

When I uninstall CMI and keep CCP and AH, the TAB complete starts working perfectly. (AUCTION HOUSE disables itself because CMI is the only plugin I have that provides economy)

When I uninstall CCP and keep CMI and AH, the TAB complete does not function.

When I uninstall AH and keep CCP and CMI, the TAB complete functions perfectly.

As Danielpeter-99 pointed out, the problem seems to be that AH breaks TAB complete functionality.
