### ISSUE TITLE
Improvement - Insertion

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1918]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
It allows differentiation between click-event and shift+click. Meaning a serverowner could essentially run seperate suggestions or seperate things in general for click & shift + click.

2) What would happen if we won't implement this feature? How's your server being affected?
Well i plan on using it to essentially have clicking a players name suggest "/msg player" whereas shift+clicking suggesting "/mute [playerName] 10m xyz". If its not possible via CHC i'll need to come up with an alternative as this feature would allow my staff to instantly silence problem players.

3) If suggesting something new - Can the old system be modified/improved instead?
The old system can be modified. This is essentially done via:
`TextComponent.setInsertion(String insertion)`
or
`BaseComponent.setInsertion(String insertion)`

If this is already possible via CHC please let me know 👍

**Comment by AngellitoX** [comment]
Interesting idea, I'll keep this opened so Matej can take a look to this and let us know if this is doable.

Angel from MineAcademy.org

**Comment by LogGits** [comment]
Cheers, it's a pretty simple addition that works wonders ❤️

**Comment by kangarko** [comment]
Thanks, pulled into https://www.mindmeister.com/1589858477?t=3V2HKfCGzw

**Comment by LogGits** [comment]
Awesome, thanks. You should move that to the "Simple" section because it would take 5 mins to actually make haha 👍
