### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by TheExceed** [kangarko/ChatControl-Pro#1919]
Requesting velocity support.
Velocity is an alternate bungeecord.
However, its not a fork and requires different plugin support.

**Comment by AngellitoX** [comment]
Hello there!

This may take a while as the main goal is to have our products as stable as possible in the main softwares (Spigot and Paper) and as Matej is the only developer for now, it may be complicated to add to our plans list. But keep in touch, this may change soon!

Thank you for contacting us.
Angel from MineAcademy.org

**Comment by TheExceed** [comment]
Well, velocity is the paper of bungee. So its going to grow quickly.

**Comment by kangarko** [comment]
Hi there,

Thanks for suggesting this. I will keep an eye on Velocity and if a lot of people start suggesting this, we'll create BungeeControl for it too in the future. However right now my plates are full developing other plugins.
