### ISSUE TITLE
Multiple Channels

### ISSUE THREAD

**Issue by Dyllaann** [kangarko/ChatControl-Pro#192]
Hey.

How would I be able to create a local and global chat together?
So, all players see the 'global/standard' chat and their messages go there by default, but if they use /ch send local, players near them can see it too.

Anyway to acomplish this?

Thanks

**Comment by kangarko** [comment]
Hey, you can create two channels in chat.yml:

  global:
    Format: Your_Global_Format    
 
  local:
    Format: Your_Local_Format    
    Range: 50

that way, the global chat would be for everybody, and the local chat would have the range of 50 blocks. You manage which channels player join when the join based off of their permissions, please see the wikipedia.

**Comment by Dyllaann** [comment]
Yeah I understand, but players can only be in one channel, right?

**Comment by kangarko** [comment]
Yes, at present, they can only have ONE active channel. They can spy messages from unlimited amount of other channels and use /ch send to send messages to any channel at any time.

**Comment by Dyllaann** [comment]
Fixed it. Somehow overrideranged was granted.
