### ISSUE TITLE
1.16.2: MySQL Issue

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#1920]
Minecraft: 1.16.2
Paper: 182
CCP: 8.8.1

this may have been reported already but i haven't seen an open issue about it.
this happens every time a player logs out.

https://pastebin.com/RGcYfcFs

**Comment by AngellitoX** [comment]
Hello there! Thank you for reaching us out.

We will take a look to this in the next couple of days.

Angel from MineAcademy.org

**Comment by kangarko** [comment]
Sorry, I cannot reproduce, can you please share this with me in private by sending a PM to kangarko on SpigotMC?

- Your ChatControl (ChatControl_Data) table from your MySQL database exported as SQL.
- Your ChatControl/ entire plugin folder as ZIP.

Closing this and we will continue in private over PM to avoid leaking potentially sensitive data.
