### ISSUE TITLE
 Possible problem with default settings.yml

### ISSUE THREAD

**Issue by HapCave** [kangarko/ChatControl-Pro#1921]
ChatControl Pro 8.8.2 on 1.16.2

Using the YAML parser http://yaml-online-parser.appspot.com/, the default settings.yml as extracted from the plugin's jar file tests out fine. However, when testing the default settings.yml as placed in the ChatControl folder on first execution, it shows the error. [unacceptable character #x0083: special characters are not allowed in "<unicode string>", position 38418]. It seems the error occurs on line 993 which is:

"# Handle characters with accents internally as without the accents (e.g. á goes to a)? "
   gets changed to:
"# Handle characters with accents internally as without the accents (e.g. Ã¡ goes to a)?"

Obviously the error is not fatal, but I thought you should know.

**Comment by kangarko** [comment]
Hi, seems like there is an encoding problem, please see https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

You can open the file in Notepad++ or Sublime Editor and save it in UTF-8, removing the invalid characters to prevent this error from taking place.

Thanks.
