### ISSUE TITLE
Letters like ÅÄÖ combined with smileys doesnt work

### ISSUE THREAD

**Issue by SauFey** [kangarko/ChatControl-Pro#1924]
1) Put your Minecraft version in the title.
**Paper on Bukkit 1.16.2-R0.1-SNAPSHOT**

2) Be clear: What is your current situation, the desired situation, and your problem?
**Just to be clear, I have a swedish server, so my players write in swedish. The issue with the language and the chat is that when players use our letters, ÅÄÖ, combined with a smiley, our letters turns into AAO instead. As the text below:

[15:32:10]: [INFO] MATCH: :\)
[15:32:10]: [INFO] CATCH: hmm osäker men nån gång i våras så några månader :)
[15:32:10]: [INFO] FINAL: hmm osaker men nan gang i varas sa nagra manader ☺

This occurs no matter what version of any plugin or server-jar.**

3) If needed - upload your plugin's folder here and any errors using pastebin.com.
**No errors, just an issue with the language and the symbols in chat.txt.**

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/1922
