### ISSUE TITLE
Minecraft 1.16.2: Task for ChatControl v8.8.2 generated an exception

### ISSUE THREAD

**Issue by TehZombiJesus** [kangarko/ChatControl-Pro#1927]
https://pastebin.com/cUMG8Qqt

Every time I log on my server, this errors appears in the server console.

I'm running the latest Paper version of 1.16.2 including latest ChatControlPro version.

**Comment by kangarko** [comment]
Thanks, I will patch that. Most likely your condition returns something that is either null or not a boolean, in the next release you will get an error clarifying what it returned and what you need to fix.
