### ISSUE TITLE
1.16.2 - Permissions are not as advertised

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1928]
Version 8.8.2 CHC PRO
Paper 1.16.2 build 175

The update says you changed `chatcontrol.color.gui.{color}` to `chatcontrol.gui.color.{color}` however luckperms says that's not the permission. It says the permission is still `chatcontrol.color.gui.{color}`. Hence, when I gave a group these permissions:
https://gyazo.com/6ee75a1a2d0d3579f8633fcb76bbbe1f

They have access to all chatcolours via the gui (even the formats which are negated specifically).

**Comment by kangarko** [comment]
I am not sure if that got slipped through the release, but this will get patched. Apologies!

**Comment by LogGits** [comment]
Seems to be working in the latest update, Thanks for the patch 🙂
