### ISSUE TITLE
Priority system for tags

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#193]
So I made some sort of tag system using permissions.

chatcontrol.groups.outlaw
chatcontrol.groups.baron
ect...

However is it possible to add some sort of priority system so ChatControl sees baron higher as outlaw?
Or do I really need to remove .outlaw and add .baron everytime?

**Comment by kangarko** [comment]
Hey, you can do it within your permission plugin with negative permissions, there is no way and no point of adding it separately to ChatControl.

An example:

outlaw group:
- chatcontrol.groups.outlaw

baron group:
- -chatcontrol.groups.outlaw
- chatcontrol.groups.baron

**Comment by kangarko** [comment]
Closing, let me know if any questions.
