### ISSUE TITLE
1.16.2: Not supported Luckperms hex color code (RGB) prefixes

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1930]
I enabled chat formatting. But ChatControl not supported Luckperms hex color code (RGB) prefixes.
<img width="238" alt="Capture" src="https://user-images.githubusercontent.com/8324198/92491262-547bca80-f1f2-11ea-8a91-17de4bf3df81.PNG">

**Comment by Sikatsu** [comment]
Because the format you use is invalid.

Try {#B6F542}

**Comment by kangarko** [comment]
Use what Sikatsu told, thanks!
