### ISSUE TITLE
1.16.2: Private Messages broken.

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1931]
Updated to 8.8.4 just now and my private messages seem to be broken.

Whatever I use in terms of /w or /r, messages are not being shown.

It looks like only the receiver is seeing the messages and that I am not seeing messages I send myself.

As you can see in spy, both messages.. but I can only see the one another player sents me.

![image](https://user-images.githubusercontent.com/5664135/92726553-0c81b280-f36e-11ea-9c00-486c32cb7fcc.png)

![image](https://user-images.githubusercontent.com/5664135/92726565-11defd00-f36e-11ea-8586-0a0519299e52.png)

**Comment by HexedHero** [comment]
Same issue here, /msg and /r is just broken.

/msg, you have to use players nicknames from Essentials, their normal Minecraft names don't work.
/r, tries to use the players Minecraft name but says the "player named 'name' is not online`

**Comment by Kbryst** [comment]
Posting for some extra input since I've been pushing for more CMI support instead of essentials,

We use CMI instead of essentials and are reporting no issues with msg or reply.

**Comment by kangarko** [comment]
Thanks, seems to happen due to the lack of infrastructure to look up nicks over BungeeControl.  I will have to rewrite some packets we send out, will take a few days but a fix will be out soonest possible (Monday~).

**Comment by donvdp** [comment]
just confirming that im also experiencing this issue.

**Comment by Sikatsu** [comment]
Could it be that 8.8.5 fixed this issue? Or atleast, I don't seem to have the issue right now.
I can see my own messages that I send out through private messages again.

**Comment by kangarko** [comment]
Nicks have been removed in the last release. There is a pool going on right now, please vote and I will prioritize what is best for you. Just see SpigotMC update log.

**Comment by donvdp** [comment]
so your just going to leave a rather essential part of play the game broken...?

**Comment by kangarko** [comment]
No, you clearly missed the news, read my update post.

**Comment by donvdp** [comment]
is there a link to where you post this news ?

**Comment by kangarko** [comment]
I am a single developer and don't have time to backport this to Pro, but we already got a system working fine in Red that you can get here: https://github.com/kangarko/ChatControl-Red
