### ISSUE TITLE
1.16.1: Messages going cross-server in bungee mode

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl-Pro#1932]
Im trying to configure ChatControlPro in a bungee scenario. Installed BungeeControl and ChatControl in 3 paper 1.16.1 servers. After some seconds local chats (with bungee mode disabled and players auto-joining this local chat) start crossing. I can read/write messages from any of this servers (lobby, survival and bedwars). I deleted any remaining of my old messaging system (venturechat and bungee venturechat module)

**Comment by Korinocho** [comment]
Well discovered that it start happening with admins and higher (we have user, helper, mod, admin, admin+ and owner). The only strange thing is that i dont have ANY permission added for admins :/

**Comment by Kbryst** [comment]
I know exactly the issue you're having but I can't fully remember how I had to fix it for myself.

From what I remember I had to fully flush my staff members permissions and I had to disable local-distance chats.

Now I need to point out, OP in this plugin get weird things done to them, so make sure they aren't op and if they are negate the permission from them (set to false in luck perms or add a - to the perm set)

**Comment by Korinocho** [comment]
Double checked they are not op. Also double-checked and i dont have ANY permission of chatcontrol assigned to admins. Now i have another problem. Sometimes im getting kicked from the local chat who knows why hahaha. Im getting this in the chat "Removed invalid channel write mode for KRNCHO"

**Comment by Kbryst** [comment]
Can you post your channel yml? I might not be much help but I know that's what they usually ask for.

**Comment by Korinocho** [comment]
Yes. Of course.
Here is the paste
https://pastebin.pl/view/5333194b

**Comment by Kbryst** [comment]
I think you might be missing stuff in that file. I'm pretty sure I added "Bungee: false" to mine to stop the issue, but I would check this section to see if that helps you better than I can:

 https://github.com/kangarko/ChatControl-Pro/wiki/Channels

**Comment by Korinocho** [comment]
Well. I found the problem. Idk why, but some CMI permission is making mess. Cleared admins permission and start trying 1 by 1. Found that cmi.* made the change. Omfg

**Comment by Korinocho** [comment]
Now im radomly joining channels where i cant write (without OP, and without chatcontrol.command.* or something like that)

**Comment by kangarko** [comment]
Sorry this is looking out to be a problem with your permissions setup. You can use LuckPerms debug feature or a debug feature from your favorite permission plugin to find out what permissions are being applied and when.,
