### ISSUE TITLE
1.16.2 - 8.8.4 JsonSyntaxException

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1933]
Just found an exception bug to report,
Player ran the command `/petrelease` (mypets) and it triggered:
ChatControl 8.8.4 encountered a JsonSyntaxException! Please check your error.log and report this issue with the information in that file.
They then ran `/petrelease zombie' and no other error was posted.

https://pastebin.com/7U1tnwEy

**Comment by AngellitoX** [comment]
Hello there!

Thanks a lot for reaching us. We will be looking at this issue shortly, looks like there's a collision with the plugin.

**Comment by kangarko** [comment]
Thanks, likely they have a problem but we are catching this up. I will silence this in the next release coming up on Monday.

**Comment by kangarko** [comment]
Thanks, should be solved.
