### ISSUE TITLE
1.16.1 Multiple errors: NPE sender is marked non-null but is null

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1936]
CHC 8.8.4 gives me multiple errors.

**Whenever a rule is matched**
sender is marked non-null but is null: https://pastebin.com/raw/AMN52eAR

**Player join (1 time error)**
Nodes must be provided error, scanning for null key-value pairs: https://pastebin.com/raw/gvCR3Hd6
[error_yaml.txt](https://github.com/kangarko/ChatControl-Pro/files/5207997/error_yaml.txt)

CHC 8.8.4
Paper 1.16.1

**Comment by kangarko** [comment]
Thanks, will be fixed within 24 hours. The second error is a long-standing issue, I will be investigating this.

**Comment by x1p** [comment]
Great, because currently it does not block swearing

**Comment by kangarko** [comment]
Fixed, new release will be out in less than 1 hour
