### ISSUE TITLE
1.16.2: Messages Not Synchronized and Console Spam

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1937]
Console spam: https://pastebin.com/vYz1JUb0
Can't see messages from other server in BungeeCord network after upgrade to 8.8.4
Also, the DiscordSRV hook still not working.

**Comment by AngellitoX** [comment]
Hello coco!

One small question, have you updated your BungeeControl aswell to latest version?
What's the issue with DiscordSRV exactly? not working at all? I've been using it on my 5 servers without any issue.

**Comment by coco0325** [comment]
Yes, I've updated BungeeControl to the latest.
After several tests, only 8.8.4 have this problem.

**Comment by kangarko** [comment]
Thank you and apology. Please update both plugins right now.
