### ISSUE TITLE
1.16.2: Vault Issue

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1938]
ChatControl 8.8.4 showed this https://pastebin.com/199sVbYt even I've already installed Vault.

**Comment by AngellitoX** [comment]
Hello, this message is because you need something else like LuckPerms for example, to handle the prefixes.

Please, install it and see if it solves your issue.

I'm marking this as solved. Consider commenting below if you need more help.
Angel from MineAcademy.org
