### ISSUE TITLE
1.8.9: Server freezing for 800ms everytime someone join

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl-Pro#1939]
Hello,

Since I updated ChatControl Pro to the latest version (from 8.6.4), i'm having a 800ms freeze everytime someone join.

I monitored this with spark and here is the result: 
https://spark.lucko.me/#kTI2rKhMOn

![3179b155f09dcfa53aac916c888ce304](https://user-images.githubusercontent.com/11612016/92940894-f9471380-f44f-11ea-86c3-f763cb16bf15.png)

**Comment by AngellitoX** [comment]
Hello! Thank you for providing the Spark log, it will be really useful to track what's going on. Pinging @kangarko so he can take a look further into this.

Have a good day!
Angel from MineAcademy.org

**Comment by HexedHero** [comment]
I had the same issue but only 150-200ms lag.

**Comment by haeiven** [comment]
It really need to be fixed asap :/

**Comment by kangarko** [comment]
Thanks, I will move MySQL loading into an async block.
