### ISSUE TITLE
[DiscordSRV] Name and Group are not sent to Discord in messages

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#194]
I am new to DiscordSRV but I have been anxious to try it out since you said you were going to rewrite your implementation with the new API.

I got it working great except that the message from Minecraft to Discord does not send my name, prefix, group, etc.  It only sends the message itself.

In the DiscordSRV/messages.yml file there are these two config options:

MinecraftChatToDiscordMessageFormat: "**%primarygroup%** %username% » %message%"
MinecraftChatToDiscordMessageFormatNoPrimaryGroup: "%username% » %message%"

In those examples, nothing is printed except for %message%.

It does send my name when joining the server, however.

And yes I did set Chat.Channels.Cancel_Event to true in settings.yml.

This is probably some stupid config setting I'm overlooking but as of now I'm stumped.

**Comment by c0wg0d** [comment]
I also forgot to say that this prints in the console.  Not sure if it's related.

[DiscordSRV] No chat plugin hooks enabled

**Comment by kangarko** [comment]
Hey,

thank you for an extensive feedback and also that you extracted the config from discord. I have just pushed a new release, in which I have changed it so the discord 'receives' the channel message and will process it by himself. Please let me know how it works (don't have the setup environment for discord atm).

**Comment by c0wg0d** [comment]
That fixed it!  I am going to make a separate bug about the chat plugin hook.

**Comment by kangarko** [comment]
Hmm that's odd, probably because ChatControl loads after Discord, so we can register to it's API. The other way would not be possible because Discord must be ready to accept third party registrations (I pretty much assume).
