### ISSUE TITLE
Error whenever a 'rule' is caught

### ISSUE THREAD

**Issue by wearenoobsuk** [kangarko/ChatControl-Pro#1943]
https://pastebin.com/cvPcaihR

I am getting this error on chat control, I have updated my bungeecord control link plugin and this is what happens when someone swears on the latest version. It recognises the swear in console but doesn't give me any spy notification and it allows the message though. I wanted to update chat control because it was no longer blocking links, But since updating, it seems to have completely broke,

The servers i have tested are paper 1.16.3 and paper 1.16.1 and both give the same error

**Comment by wearenoobsuk** [comment]
https://pastebin.com/C43FrF2e

Also this is now my bungeecord console..

**Comment by kangarko** [comment]
Thanks, will get fixed. Please do let me know if both errors get solved in the release just out!
