### ISSUE TITLE
1.8.9: Chatcontrol pro crashing the server

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl-Pro#1944]
Hello,

Since you updated chatcontrol pro to 8.6.5, i'm having random crashes.
I've reset my database & data.db this morning and it still happening.

Crash logs: https://paste.soleria.eu/uqocuyifaw.md
Error.log: https://paste.soleria.eu/elebawadaf.coffeescript
error_yaml: https://paste.soleria.eu/ocufujopiy.coffeescript

Best regards,

**Comment by AngellitoX** [comment]
Hello, 

From what it seems it looks like you're running out of memory. Also, you're using a strange fork called Crystal which may also be the source of your issue. I don't know anything about it, so I can't tell for sure.

Try increasing your memory and use Aikar's flags and see if it solves your issues.

I'm marking this as solved for now. If you still present problems, feel free to comment below.
Angel from MineAcademy.org

**Comment by haeiven** [comment]
Hello,

This is not happening when i use a version 8.6.4 ...
It's happening on a fork called Crystal, yes, but it happened on my hub/login server who are running PaperSpigot.
I'm already running with 20GB ram & using Aikar's flags.

I've to stay in version 8.6.4, because all highers versions are crashing/lagging my server...

Best regards,

**Comment by kangarko** [comment]
Sorry can you please wait for the next version that is going to be out tonight and test again?

When that error happens, just follow the console error instructions and send the file. I made the file being saved out of the main server thread to prevent crashes

@AngellitoX looks like our issue, forks of Spigot 99% of cases won't cause ChatControl issues btw
