### ISSUE TITLE
1.8.8: Faction Relation Placeholders

### ISSUE THREAD

**Issue by jj136975** [kangarko/ChatControl-Pro#1945]
Hi, since some updates, FactionUUID relation placeholders are not working anymore. Is there any way to make it work?

**Comment by AngellitoX** [comment]
Hello there! Have you doublechecked if PAPI parse command is returning the right value for the placeholders? Just to make sure the issue is not coming directly from FactionUUID.

**Comment by jj136975** [comment]
Hi, thx for your quick answer. I've already contacted FactionUUID devs before bcause their placeholder wasn't working when I tried to run "/papi parse me %%rel_factionsuuid_relation_color%test". Then, they said to me that it is a relation placeholder and it requires at least 2 names "/papi parserel YOURNAME THEIRNAME %rel_factionsuuid_relation_color%test". This one worked, but using it with ChatControlPro isn't working at all.

**Comment by kangarko** [comment]
Please ZIP me your ChatControl folder and navigate me where you are using this variable.

**Comment by jj136975** [comment]
it's just in chat formating 
Formats:
  Chat:
    First_Part:
      Message: "&7%rel_factionsuuid_relation_color%{factionsuuid_faction_name} "

**Comment by kangarko** [comment]
Please use {rel_factionsuuid_relation_color} instead.

**Comment by kangarko** [comment]
Closing in good faith this will fix the problem, if not please comment below.

**Comment by jj136975** [comment]
Okay, this is working but the click event isn't working for RUN_COMMAND
 
     Action: RUN_COMMAND
      Value: '/f show {player}'

**Comment by kangarko** [comment]
What does it say? Some events are incompatible...
