### ISSUE TITLE
1.16.3: The colors removed when I use chat rule

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1946]
<img width="329" alt="Capture" src="https://user-images.githubusercontent.com/8324198/93014896-1fd28f00-f5b5-11ea-8d8e-d1928020232f.PNG">

rules/chat.txt
```
match :\)
then replace ☺
```

ChatControl version 8.8.5
Server version: 1.16.3 Paper build 195

**Comment by AngellitoX** [comment]
Hello!

Thank you so much for reporting it. We will take a look to it soon!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Set Regex_Strip_Colors to false.

@AngellitoX 

That is normal behavior, but if you disable Regex_Strip_Colors players will be able to bypass rules by simply adding colors.
