### ISSUE TITLE
1.16.3: Insert dot function not work when the final character is Hungarian letter

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1947]
<img width="307" alt="Capture" src="https://user-images.githubusercontent.com/8324198/93015010-0aaa3000-f5b6-11ea-825b-d9e9e9748e89.PNG">

ChatControl version 8.8.5
Server version: 1.16.3 Paper build 195

**Comment by kangarko** [comment]
Sorry, this is a limitation of the system currently.
