### ISSUE TITLE
1.16.2: Can you make custom advancement messages

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl-Pro#1948]
Is it possible to Make custom advancement messages lik custom join/death messages using Chatcontrol Pro?

**Comment by AngellitoX** [comment]
Hello there, ChatControl Pro has a section to customize join/death messages, but it's pretty straightforward: just edit the text lines, nothing else.

If you want a more in-depth features for this function, I'd recommend you to take a look to plugins like DeluxeJoin.

Probably this can be enhanced directly in ChatControl for the future. Pinging @kangarko to know his opinion towards the topic.

Thank you for the idea!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Thanks for your suggestion, I will add this to CHC 9.1
