### ISSUE TITLE
Turning off automatic spy for ops?

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#195]
Hey! How do I turn off the auto spy for ops? It's kinda annoying and I can't false the permission since I couldn't find the global auto spy but only the channel one. Also, when is the 8.0 coming out? ^-^

**Comment by kangarko** [comment]
Please see

https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#how-can-i-turn-off-the-automatic-channel-spy-for-ops
