### ISSUE TITLE
1.8.8: How to setup (if posible) Placeholders in Death Messages?

### ISSUE THREAD

**Issue by JorgeSilvarredonda** [kangarko/ChatControl-Pro#1950]
I would like to know if i can introduce kills placehodlers in death messages like
**Player1 (Player1 Kills) was slain by Player2 (Player2 Kills)**
Can this be possible?
Im using KillStats for dealing with kills, so i would like to implement "{killstats_kills}"

Thank you, 
Jorge.

**Comment by AngellitoX** [comment]
Hello there!
It should be possible to do so. Give it a shot and let us know the results. If it doesn't work, I'm sure we can fix it :) 

Have a good day!
Angel from MineAcademy.org
