### ISSUE TITLE
Encoding Issue for mac based users

### ISSUE THREAD

**Issue by DebuffPvP** [kangarko/ChatControl-Pro#1952]
Game Version:
This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

ChatControl Version:
The latest ones for the free and pro version as i have both of them

Issue:
There is a console encoding error. This error happens for users that host their game on a mac based computer or tower.

Error:
https://pastebin.com/0Ka9p4X1

**Comment by kangarko** [comment]
Simply remove DS_Store from your ChatControl folder.
