### ISSUE TITLE
1.15.2: How to?

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl-Pro#1953]
Hello, im using the rules:

match (.)(?=\1\1+)
then replace

match (..)(?=\1\1+)
then replace

match (...)(?=\1\1+)
then replace

Its working fine replacing "hhhhhhhhhh" to "hhh" but i have clans and wheb someone do /clan join 666   (a name of a clan), he cant... ¿How to exclude certain commands?

**Comment by kangarko** [comment]
I already answered you elsewhere.
