### ISSUE TITLE
1.15.2: Doubt

### ISSUE THREAD

**Issue by msmanui** [kangarko/ChatControl-Pro#1954]
1) Hello, im using the rules:
match (.)(?=\1\1+)
then replace
match (..)(?=\1\1+)
then replace
match (...)(?=\1\1+)
then replace
Its working fine replacing "hhhhhhhhhh" to "hhh" but i have clans and wheb someone do /clan join 666   (a name of a clan), he cant... ¿How to exclude certain commands? 

2) The handle as advertisment by default is falsing me some normal chats like "/tell Railox_skill Okey:C, me interesaba el arco:C"

Any way to prevent that? Here is the full file of the .log so u can see the false positives

**https://pastebin.com/fKm5DBya**

**Comment by kangarko** [comment]
For rules, you can use the "ignore string" operator, please see rules.txt for help (see the header).

For 2., add /tell to Ignore_Commands list in handlers.yml
