### ISSUE TITLE
Per World Chat

### ISSUE THREAD

**Issue by Sairiik** [kangarko/ChatControl-Pro#1956]
Hello Hello ,

i am using ChatControl for a while now and i am in deep needs for a function , that is i think quite simple .
Its a PerWorldChat. 
I have a Survival Server and now i want to implement Minigames on it .(on userrequest) 
However, when i create them in a multiverse the Minigames Plugins are Sending Messages Globally , I mean Death messages , Join messages , quite everything i would say . 
Maybe it is possible to implement that in the channels thingy ? To being forced in a channel as soon as the Player enters the Multiverse?

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Well i dont think that any other user would be benefited in the same way im being from this update . 
But maybe people need a perworldchat in any other way than this. 
2) What would happen if we won't implement this feature? How's your server being affected?
Well i simply cannot implement minigames , due  to the extreme Chat spamming ^^''

3) If suggesting something new - Can the old system be modified/improved instead?
Ye , i guess you can add that to the Channels System , maybe ?

I hope that you understand my struggle . 

Kind Regards 

Sairiik / Richard

**Comment by kangarko** [comment]
You can disable channels and simply use the Range feature in formatting.yml.
Or you can place the Range option into your individual channels, see Wiki article on Channels here for help.
Then just use a third party plugin to run a command /channel join when a player enters that world, and /channel leave when they leave.
