### ISSUE TITLE
1.12.2: How can i make sure that the BungeeControl is working on my server

### ISSUE THREAD

**Issue by noobberry** [kangarko/ChatControl-Pro#1957]
1.12.2: how can i make sure that BungeeControl is working on my BungeeCord server?

2) how can i make sure that BungeeControl is working on my BungeeCord server?  where can i find the "set "BungeeCord.Enabled" to "true" in settings.yml " i didn't find settings.yml anywhere.

**Comment by kangarko** [comment]
If you can't see settings.yml generated in ChatControl-Pro folder, please post me your full server log uploaded to pastebin.com

Also ensure you set a server name in server-name in server.properties file in root server folder.

**Comment by noobberry** [comment]
Hello, i think i've fixed this issue, but yesterday i was able to message my friend in the other server with /tell, but today i can't anymore. here is the logs: 
https://pastebin.com/0MFHCHJL
https://pastebin.com/3nzZs4fH
https://pastebin.com/i8UTHiBf

**Comment by kangarko** [comment]
Closing, comment below what I asked for when you come back 👍
