### ISSUE TITLE
1.16.3: Bug since nickname support removed

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#1959]
You removed the nickname support, but in tab-complete it still shows CMI nicknames, which if you want to tab-complete and send a message too, says the player is offline.

**Comment by kangarko** [comment]
What command is that please?

**Comment by Sikatsu** [comment]
Just the private message system I assume, /tell

**Comment by Danielpeter-99** [comment]
I can second that, it has been happening to me

**Comment by kangarko** [comment]
Sorry, cannot reproduce on my end. Please use the next version: 

![a](https://i.imgur.com/Bmdl4Ms.gif)
