### ISSUE TITLE
Nametags

### ISSUE THREAD

**Issue by legotyrell** [kangarko/ChatControl-Pro#196]
Is there away to get the prefix and suffix from this plugin https://www.spigotmc.org/resources/nametags.13119/
into like a custom variable. Thanks

**Comment by kangarko** [comment]
There is no, so I just added it to the plugin! :)

A new release will be available tonight.

**Comment by legotyrell** [comment]
OMG, Thanks

**Comment by kangarko** [comment]
Btw, if you've enjoyed quick feature drop, maybe you can drop a quick review :)
