### ISSUE TITLE
how to allow ingame chat colors

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl-Pro#1962]
how to allow and set permission for ingame chat colors for example: &6, &9, &a, &b, &c, &d, &e, etc.?

**Comment by malonnnn** [comment]
chatcontrol.color.bold would allow a a player to use bold chat

chatcontrol.color.green would allow a player to use green chat

**Comment by Westloch** [comment]
perfect, Is there a way to edit the list of colors or possibly add more using hex codes?

**Comment by malonnnn** [comment]
no there is not, minecraft has hard-coded colors.

**Comment by kangarko** [comment]
Yes for MC 1.16 you can use HEX colors. ChatControl 9.1.0 will bring permissions for specific hex colors.

**Comment by Westloch** [comment]
Awesome, no rush but is there an eta on release?

**Comment by kangarko** [comment]
Few weeks to a month ;)
