### ISSUE TITLE
Disable formatting completely in certain worlds

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1964]
Hi, I run a mini games server and I would like to use some of my mini games built in chat formatting. At the moment ChatControlPro is over riding the plugins chat configuration, is there anyway to disable CCP formatting in certain worlds?
Thanks for your help!

**Comment by AngellitoX** [comment]
Hello Leeham, yes, this is possible by tweaking the Listener_Priorities under settings.yml, have a look to it and hopefully it might solve your issue.

I'm closing this with the faith this will be solved. Comment below if you need further help.
Angel from MineAcademy.org

**Comment by LeehamElectronics** [comment]
Thanks for that @AngellitoX I tried using the Listener_Priorities but I want it to apply only in certain worlds. When I put Listener_Priorities  to LOW the bed wars formatting works but then ChatControlPro doesn't format any chats at all. Is there a per world option?
Cheers

**Comment by AngellitoX** [comment]
Hmmm, I understand your point. Unfortunately, as for now, ChatControl takes over the whole server and manages it as such, so I don't think you can actually prioritize this. Some workarounds for this is to put it at NORMAL or MONITOR and then probably it can just work whenever it's needed. If not, you could possibly ask the other plugin's developer to increase his Chat priority to override ChatControl's when it's on Normal Priority. Let us know your thoughts!

**Comment by kangarko** [comment]
Thanks, will add Ignored_Worlds option to ChatControl 25.0.0. Just kidding, it should come in 9.1.0.

**Comment by LeehamElectronics** [comment]
> 
> 
> Thanks, will add Ignored_Worlds option to ChatControl 25.0.0. Just kidding, it should come in 9.1.0.

I look forward to it, thanks!
