### ISSUE TITLE
1.16.2: Private message variables are broken

### ISSUE THREAD

**Issue by Lariesse** [kangarko/ChatControl-Pro#1967]
Hello,

The variables of private messages are broken, you can see this image to see the error https://i.imgur.com/cpYJVUP.png
This happened after installing the TabCompleteFilter plugin 
https://www.spigotmc.org/resources/tabcompletefilter-filter-commands.75208/
I have added /r and /msg commands to the whitelist, so those commands are shown to the player

**Comment by HexedHero** [comment]
Can confirm, please stop breaking this :(

**Comment by Lariesse** [comment]
@HexedHero Do you have this problem without TabCompleteFilter plugin? I thought the problem happened because of the plugin I installed

**Comment by HexedHero** [comment]
I've never used that plugin. It's an ChatControl issue.

**Comment by LeehamElectronics** [comment]
Yep I can confirm this is also an issue for me.

**Comment by kangarko** [comment]
Thanks, fixed.
