### ISSUE TITLE
1.16.3: Problem at startup after updating

### ISSUE THREAD

**Issue by AntZaro** [kangarko/ChatControl-Pro#1968]
I just updated my server to 1.16.3 (I had been on 1.16.1 for a while, skipped 1.16.2). I noticed ChatControl now said it was compatible with this latest version of Minecraft, so I installed ChatControl version 8.8.8. 

When started my server on 1.16.3, I got the below linked error and ChatControl disables itself. 
https://pastebin.com/WR6sTj6C

https://pastebin.com/w8RPRVfF

In the past I have never used mysql with ChatControl (I use it with other plugins though). I just enabled it now with ChatControl to see if that would solve my problem, since the error kept referencing the data.db file. Unfortunately, this did nothing and I keep getting the error. 

I am running the latest version of paper, version 1.16.3 build #202.

**Comment by AngellitoX** [comment]
Hello, your error is related to data.db. I'm pinging @kangarko to investigate this further. If it's urgently for now, you could probably backup the `data.db` file and then remove it from the folder.

Hope this works for you in the meantime.

**Comment by AntZaro** [comment]
Thanks for the response! 

I should also have said, I tried erasing the data.db file completely and then starting the server up, but I got the exact same error again. That's what really confused me!

**Comment by kangarko** [comment]
Please ZIP me your full folder.

**Comment by AntZaro** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5271782/ChatControl.zip)
Here it is. Please note I deleted the chat.log file from the folder because it was way too large to upload.

**Comment by kangarko** [comment]
Thanks, please test the next release. Your config just loaded fine for me on it :)

Also ensure no plugman/reload is used, do a clean restart.

**Comment by AntZaro** [comment]
Thank you for the update! 

Unfortunately, I encountered the same errors again when loading on the new version. I even deleted the data file again, trying another reboot, and that did not make a difference either. 

https://pastebin.com/6PsgtcgG

https://pastebin.com/ZT10rBgJ

**Comment by AntZaro** [comment]
However, I will add this in case it helps:

I have a second server on this same bungee instance. After the problem with this server (errors above), I kept Server 2 on 8.7.12. Just to see, I installed 8.8.9 on Server 2. No problems at all! 

This makes me think Server 1 is somehow still experiencing a problem left over from 8.8.8... I wonder if there is a way to reset that so Server 1 can load properly like Server 2.

Let me know if none of that made any sense.

**Comment by kangarko** [comment]
You can try renaming the entire ChatControl folder to something else, redownload JAR, ensure you dont use PlugMan and no reload, and let new JAR generate new ChatControl folder.

**Comment by AntZaro** [comment]
I just renamed the folder to let it generate a new one. This was during a hard restart (server was totally shut down). 

I got the same error again! I'm going crazy trying to think of what could be causing this problem. Inside the newly generated folder, all the files appear to be fine. I also updated to the latest version of the plugin, 8.8.11. So it was a whole new jar file/version, generating new folder, and still the error. 

https://pastebin.com/11kGN8Gy

**Comment by kangarko** [comment]
There is an encoding issue somewhere:

`unacceptable code point '' (0x3) special characters are not allowed`

Check this out: https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
Maybe try using different text editor or contact your server hosting if they are overriding your files and saving them in different encoding than UTF-8.

**Comment by AntZaro** [comment]
Okay. Is there any particular file that contains the error? All I see are references to the data.db, so I'm not sure.

**Comment by AntZaro** [comment]
We use a dedicated server running CentOS, and the secondary server I mentioned also runs on this machine. That server has no ChatControl problem. 

Wouldn't a file formatting problem be machine-wide? That's what confuses me. I don't know what's specifically giving this one problems.

**Comment by AntZaro** [comment]
Update: 

After no luck trying a few more things (like generating a whole new ChatControl folder again). I started the server up on ChatControl version 8.7.12 (with no changes made at all to my files) and have no issues. It started up normally. 

I will be remaining on this version for the time being, since I cannot figure out what is tripping up the latest version.

**Comment by kangarko** [comment]
Sorry, to me it looks like something is either tampering with the JAR or the files. Even if you don't modify them they are opened for loading and editing/updating and saving internally. You can stay on that version for the time being and when ChatControl 9.1 is out please test that new version and let me know if the issue has been resolved.

**Comment by AntZaro** [comment]
Hello! I just want to follow up on this.

I updated the server the other day to 1.16.4 and installed ChatControl version 8.9.8 (current at the time), and it worked fine! No issues!
