### ISSUE TITLE
1.8.8: ChatControlPRO rules won't work until a chc reload is made

### ISSUE THREAD

**Issue by JuliCarles** [kangarko/ChatControl-Pro#1969]
Hello.

We have been using a very old version of ChatControlPRO (8.0.12) and figured it was about time to update to the latest (8.8.8) version.

I have manually reviewed line by line in every file to account for any breaking changes that may have happened between both versions and updated accordingly. 

The rules, however, (rules.txt, chat.txt, etc) are practically the same so I just replaced all the files I previously had. The plugin enables correctly and everything seems to be working perfectly except for one thing:

The rules won't cancel ("then deny" line) messages when the server starts, but they do when performing a /chc reload command. The warn messages do happen, but the message is sent either way instead of being blocked. This is fixed by performing a /chc reload command.

I am unsure why this is happening, seems like a very odd bug; everything else works just fine and no /chc reload is needed in the old 8.0.12 version.

ProtocolLib: Latest 4.5.1
CHC: 8.8.8
Server version: Latest Paper version (1.8.8).

If any other information is required, please reply back. Thank you.
Regards, Julian.

**Comment by AngellitoX** [comment]
Hello, interesting issue, I haven't experienced a problem related to rules, although I'm not an intensive user as you may be.

I'll keep this open in order to find a proper solution. 

It's important to mention that ChatControl 9.1.0 will be here very soon, so probably there's a small chance that this can be traced for that version. Stay tuned!

**Comment by kangarko** [comment]
No idea, first time happening. Please try renaming ChatControl/ folder to ChatControl_Old/ and see if the default setup causes this. If not then unfortunately you'd have to edit it out manually to your likings.

**Comment by JohnS19** [comment]
I am having this issue as well.

**Comment by kangarko** [comment]
Please test the next upcoming version. If it still happens, open a new ticket, and ZIP me your ChatControl folder.
