### ISSUE TITLE
Send message or use /msg > Crash Client

### ISSUE THREAD

**Issue by Wasabules** [kangarko/ChatControl-Pro#197]
All in the title but i have a error into the log:
https://hastebin.com/upilodefac.vbs

When i use /ch send:
https://hastebin.com/xeyojasilo.vbs

I have KCauldron on 1.7.10 and i use last Travertine build (same BungeeCord)

**Comment by kangarko** [comment]
Hey, really odd. DO you have BungeeChatAPI installed (https://www.spigotmc.org/threads/bungeechatapi.227734/)?  If not, please try with that plugin.

**Comment by Wasabules** [comment]
Yes, without, the plugin can't start ^^'

**Comment by kangarko** [comment]
Hmm, I see. I have reviewed my code and found that it is not ChatControl who created the error, but the BaseComponentSerializer class which is within Cauldron itself. It seems I can't do much at this time, so I would recommend reporting this bug to Cauldron's developers and for now disabling the Chat Formatter.

**Comment by kangarko** [comment]
tttt

**Comment by kangarko** [comment]
tttt

**Comment by kangarko** [comment]
tttt

**Comment by Wasabules** [comment]
Cauldron is no longer developing unfortunately: / Possibility of making a Cauldron version if it is not too difficult?

**Comment by kangarko** [comment]
I see. I don't have the time and resources for that now, but for the time being you can use the version 7.1.7 which is the last version using static chat formatter, not requiring nor using any of that problematic libraries.

**Comment by Wasabules** [comment]
Who to use Static Chat Formatter ?
Who to disable Chat Formatter ?

**Comment by Wasabules** [comment]
I have test the version 7.1.7 with Static and Channel mode but, not work. Same error
https://hastebin.com/dodusaxecu.vbs

**Comment by kangarko** [comment]
I see. It looks like packets-related issue. Can you please try setting Packets.Enabled to false? It will disable packet rules, but for now it seems like the only way to fix this (Cauldron it's incompatible with packet rules anyway)

**Comment by Wasabules** [comment]
I have test this with "false", but not work :s

**Comment by kangarko** [comment]
Please make sure you stop and start the server (reload does not work with this option in case you used it)

**Comment by Wasabules** [comment]
I restart the server every time

**Comment by kangarko** [comment]
I will try to alter the system a bit, please test the latest release available shortly.

**Comment by Wasabules** [comment]
On 1.11.2 server > https://hastebin.com/yebaloyabu.sql
On 1.7.10 server > http://prntscr.com/f4hjxd

Two error on 1.11.2 server, the errors have appeared in same time with two message on the screen of 1.7.10 server.

I recieve all messages of 1.11.2 server on the 1.7.10 but i can't send message.
I can't send /msg from 1.7.10 but i can recieve from 1.11.2 :s

**Comment by Wasabules** [comment]
Same error when i send message on chat with the Admin Chat.

PS: I use Channel System ^^

Thanks!

**Comment by kangarko** [comment]
Hey, sorry for the delay. Please post me the chat formats from your chat.yml from both servers, if different.

**Comment by Wasabules** [comment]
On 1.7.10: https://hastebin.com/vuwisatiwi.php
On all 1.11.2 server: https://hastebin.com/unemutaraz.php

It's differents, i have remove all "JSON part" on 1.7.10 server.

**Comment by kangarko** [comment]
Thank you, Files look allright. I will test it out asap.

**Comment by kangarko** [comment]
Hey,

I have done some testing, and unfortunately found out that KCauldron is causing the incompatibility. I have not understood exactly where the issue lies but it is outside of ChatControl and thus my hands are tied in this problem. I apologies for the inconvenience. You may try to disable Private_Messages completely and use a supplemental plugin for that feature.

**Comment by kangarko** [comment]
I am closing this issue. It appears to be unfixable at present due to the internal differences in KCauldron. There's little I can do about it besides making a completely new branch of ChatControl which I don't have time for unfortunately.
