### ISSUE TITLE
1.16.3: How to display items

### ISSUE THREAD

**Issue by Roselle-cloud** [kangarko/ChatControl-Pro#1971]
I replaced [i] with rules/chat.txt

Match [i]
Then replace {item}

But it can't display knowledge, nor can it display the knowledge I want?

Keyword: "{item}"
Value: player.getItemInHand(). getType()
Hover_Item: player.getItemInHand()
Hover: "Hello World"

Another problem is that op cannot use [i]. I know this is a permissions issue. Is there a way to use op while bypassing the rules [i]

**Comment by AngellitoX** [comment]
Hello, the item function and the javascripts have been a reported issue before. This is already planned to be fixed for ChatControl 9.1.0. Not sure if a fix can come sooner to that, hopefully it will. 

Keeping this opened to have it in mind. Thank you for reporting it.

**Comment by kangarko** [comment]
Not possible with V8, will come to V9
