### ISSUE TITLE
1.8.9: Server crash (again)

### ISSUE THREAD

**Issue by haeiven** [kangarko/ChatControl-Pro#1972]
Hello,

ChatControl Pro crashed my server (again, with an other error).

https://paste.soleria.eu/emuvijinot.md
https://paste.soleria.eu/livuzadupu.pl

Best regards,

**Comment by AngellitoX** [comment]
Hello, one of your issues is related to DiscordSRV too which can be probably lagging out the server and then causing ChatControl to fail doing its job, could you please check that plugin too?

As for the second problem, it looks like the data.db file from ChatControl got somehow corrupted. If it's urgently, you could probably backup that file until this is investigated further and then remove it from ChatControl folder and restart your server.

Thank you for reporting it!

**Comment by kangarko** [comment]
Thanks, will attempt to solve both errors in the release coming up tonight.

In case it happens again comment below with new stack trace please.
