### ISSUE TITLE
1.16.3: Console Error

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1974]
https://pastebin.com/454p8p00
https://pastebin.com/aUaz5NA5

Paper 1.16.3 ChatControl 8.8.8

**Comment by AngellitoX** [comment]
Hello, there is definitely an issue going on ChatControl 8.8.8 related to data.db. Mentioned in other tickets right now. Please port back to ChatControl 8.8.7 while the issue is resolved. 

I deeply apologize for the inconvenience. 
Thank you for reporting it.
Angel Avila

**Comment by kangarko** [comment]
Thanks, next version should patch it.
