### ISSUE TITLE
1.16.3: Private Message Placeholder Not Working

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#1976]
The {receiver} placeholder isn't working properly after I upgrade to 8.8.8.
formatting.yml
```
Private_Message_Sender:
    Everything:
      Message: '&7✉ &6-> {receiver}&7: &a{message}'
```
https://media.discordapp.net/attachments/753218904213553204/757962295375560704/unknown.png

**Comment by UltimateGamer200** [comment]
I can confirm this issue as I have the same issue as well on 1.15.2 with version 8.8.8 of the plugin. Not only the {reciever} placeholder doesn't work properly, but the {sender} placeholder doesn't work properly either.

**Comment by haeiven** [comment]
Having the same issue in 1.8.9

**Comment by Slayerpax** [comment]
same here i'm on 1.16.2 Paper spigot

**Comment by kangarko** [comment]
Thanks will fix that.
