### ISSUE TITLE
Paper 1.15.2 JSON not working

### ISSUE THREAD

**Issue by cantercrow** [kangarko/ChatControl-Pro#1978]
Hi,

I am trying to set up JSON messages in my messages.yml  but the below is not working
[messages.yml.log](https://github.com/kangarko/ChatControl-Pro/files/5263950/messages.yml.log)

Messages:
    #
    # Messages set as 'global' are displayed in all worlds.
    #
    global: 
      - '[JSON] {"text": "Hover Me","hoverEvent": {"action": "show_text","value": {"text": "Hey there! 1"}}}'
      - '[JSON] {"text": "Hover Me","hoverEvent": {"action": "show_text","value": {"text": "Hey there! 2"}}}'

**Comment by kangarko** [comment]
Set Prefix instead of '&8[&2Tip&8]&2' to '' then it'll work.
