### ISSUE TITLE
1.15.2 Permissions not applying correctly

### ISSUE THREAD

**Issue by StormyIceLeopard** [kangarko/ChatControl-Pro#1979]
I am trying to stop operators from bypassing the swear filter, but when I negate the permission operators are still able to bypass.
"chatcontrol.bypass.swear" I am using LuckPerms. See image. Yes, the permission matches handlers.yml and yes the word should be filtered as non-ops are filtered.
https://imgur.com/a/JO895ha

**Comment by kangarko** [comment]
Set all of these perms to false:

![a](https://i.imgur.com/rkZVT9y.png)

**Comment by StormyIceLeopard** [comment]
That worked, thank you.
