### ISSUE TITLE
1.16.3 Synchronize formatting

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl-Pro#1980]
1.16.3: database

2) how to make a that if i change something like format  in one server and all servers connected to one mysql database the changes go for all servers ? like if i set adminchat format to like ac{player} all servers change to that or rules like add a new swear should i replace all of them with new one or can relate this to database ?

**Comment by james-d-elliott** [comment]
You have to copy the changed files to all servers. There is no way to sync them I don't believe.

**Comment by FakEEE14** [comment]
but all of them can't get copied like server name formats and like this

**Comment by LeehamElectronics** [comment]
For now you will have to do this manually sorry. Soon Matej will be releasing a new plugin to automatically synchronize plugin files, but till then, you will just have to do it manually.
I do like the rules sharing feature though, perhaps Matej could include an option in ChatControl version 9 that stores chat rules in a MySQL database?

**Comment by kangarko** [comment]
Yeah there is a new plugin solving this "issue" in preparation however due to time constrains it has been put on hold. Currently you can symlink files using your file system (requires custom hosting setup). You can post on forums of some larger networks on how they do it.

**Comment by FakEEE14** [comment]
ok thanks, when this plugin will get released ?

**Comment by kangarko** [comment]
It's been put on hold. No ETA right now.
