### ISSUE TITLE
ChatControl not loading on 1.16

### ISSUE THREAD

**Issue by terrorhorizon** [kangarko/ChatControl-Pro#1981]
I tried to load latest build on my server and I get this error. Any ideas?

![mXkHkF17](https://user-images.githubusercontent.com/58755682/93959036-d22cf380-fd25-11ea-8e20-fe547b08ade7.png)

**Comment by AngellitoX** [comment]
Hello, we need the full error, please post it on pastebin.com so we can take a look into it.

**Comment by kangarko** [comment]
Issue with Java distribution or something else, test using just ChatControl on pure PaperSpigot without any other plugins. If it works then unfortunately something else is causing it
