### ISSUE TITLE
Seperate MySQL login config options its own file so we can use git sorce control!

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#1982]
most plugins have MySQL connection info as its own seperate file so this can be put into a git ignore file, so then you can have the plugin on source control, as its inside the main config, We HAVE to ignore the main config file which is not helpful if you want multiple peolpe to be able to work on your configs.

Please seperate MySQL connection information into its own file.

**Comment by kangarko** [comment]
Thanks, done. Will be available for CHC 9.1.
