### ISSUE TITLE
1.15.2: BungeeControl Join/Leave Message Placeholder

### ISSUE THREAD

**Issue by BijuuKrunos** [kangarko/ChatControl-Pro#1984]
I want the group Prefix in the join/leave message on Bungeecord.
But every placeholder or Variable i used is not transforming.
Example: "[+] [{pl_prefix}] {player}"
only the {player} is working.
Other Placeholders like {luckperms_prefix} is not working too.

Is there a prefix for Bungeecontrol wich should be working? I couldn't find any.
I know that normal placeholders aren't working because its on the Bungee site not paper where palceholderapi handels this.

Hope you guys can help me.

Greetz
Krunos

**Comment by kangarko** [comment]
Sorry, we cannot parse placeholders on BungeeControl at the moment.
