### ISSUE TITLE
1.12.2: Quality issues, improvements

### ISSUE THREAD

**Issue by Mohamad82Bz** [kangarko/ChatControl-Pro#1985]
Hi there, I was configuring chatcontrol from zero and I found some small issues, they are just quality issues, not game breaking ones.

1, Console onEnable message duplicate: https://imgur.com/a/QNkdYXA (I'm on Paper-1.12.2)

2, Setting.yml Nullpointer issue:
When I set this code:
`  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false
`
to this one:
`  Chat_Ignorer:
    Enabled: false
    Sets: []
`
I got NullPointerException on server startup (plugin will be disabled), I know it should give NullPointer, but the feature is false, I think it should catch the NPE.

3, Wiki text issue (missed characters): In "Groups" wiki (https://github.com/kangarko/ChatControl-Pro/wiki/Groups) on the Section "How to Use Groups" we have this line:
`To create a new group, set Groups.Enabled to true in you settings.ym, and create new groups in the List key there according to the configuration options below.`
The wiki writer missed one "L" character in "settings.yml" (It's "settings.ym)

(I'm not sure on this one)4, Chat_Format in Groups wiki suggest an integer?!
In the "Groups" wiki (i gave the link in 3) in section "Chat_Format" and "Global_Chat_Format" it says this:
`Chat_Format: 2`
I 'think' wiki writer wrote this wrong, But I think this one shouldn't be a number, it's Chat_Format so it should be a string.

Sorry if I had grammer issues. Thanks :)

**Comment by kangarko** [comment]
Thank you!

1. Never happened to me, try with only ChatControl and no other plugins to see if it still happens.

2. Correct, if no set is specified, this will raise a NPE.

3 and 4. Thanks, fixed <3

Matej

**Comment by Mohamad82Bz** [comment]
Your welcome! Sorry for replying in a closed issue.
I found another small issue in the wiki. In the "Discord" page, in section "How to use", number 2: Wiki writer wrote "DiscorSRV instead of DiscordSRV. (Page: https://github.com/kangarko/ChatControl-Pro/wiki/Discord)
Here's a screenshot if you didn't find it:
![Discor](https://user-images.githubusercontent.com/65306187/94190072-76df3a80-feb8-11ea-8169-19c27ea2f910.png)


Thanks and Have a nice day!

**Comment by kangarko** [comment]
Thank you so much!
