### ISSUE TITLE
1.16.2 not reading placeholders

### ISSUE THREAD

**Issue by Westloch** [kangarko/ChatControl-Pro#1989]
Placeholders dont seem to be read by plugin, this happened after updating to version 8.8.8, previously on version 8.8.7

![chatcontrolbug](https://user-images.githubusercontent.com/62856212/94180548-cc3d2c80-fe63-11ea-88d3-07fae16c4287.png)

**Comment by Westloch** [comment]
8.8.7 worked fine, then we updated to 8.8.8 and placeholders broke

**Comment by Westloch** [comment]
Went back to version 8.8.7, did not change anything settings, and 8.8.7 works perfectly fine

**Comment by kangarko** [comment]
Thanks will be fixed!
