### ISSUE TITLE
Interactive chat question

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#199]
Heya,

I want to use some interactivechat features on my server, but currently i do not know how to use it. Is there an explanation of it?

-Frank

**Comment by kangarko** [comment]
Hey,

I recommend you take a look to the chat.yml file, there is explanation to every option you can configure. You can enable the interactive chat from settings.yml in 'Chat.Formatter.Enabled', and then use the chat.yml file to edit how the chat looks like. By default, the 'Example_Format' formatter is used (you'll find it in chat.yml in the top).
