### ISSUE TITLE
Swear log upload to Discord channel?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1990]
It may already be possible, however I can not see how to do this, but I would like to simplify the moderating of my MC server by logging each rule breaker such as people swearing into a Discord channel for my moderators to check.
For example, if a player types a swear word, the message will be sent to a discord channel for moderators with the rule that was broken and perhaps the last previous 10 messages for easy context referencing, this would also include PM's.
Would this be possible? It would be much easier than checking the log in each of my servers chat control plugin folder.
Thanks in advanced!

**Comment by AngellitoX** [comment]
This is an incredible useful feature. Something similar related to rules is already planned for ChatControl 9.1.0 and I'm sure you gonna love it.

I'm pinging @kangarko to see if he can include this to the new rules system too. I don't want to give you too many spoilers yet, but ChatControl 9.1.0 is going to revolutionate the way ingame chat and Discord work!

**Comment by LeehamElectronics** [comment]
Looking forward to it! Thx

**Comment by kangarko** [comment]
Would it be fine if we upload logs to MySQL so you can just pull the column by type "normal communication" "rule catch" (also what rule) then you can put the puzzles together using SQL and render it on your website. Much more ppl requested this, you're the first to have this on Discord ;)

**Comment by LeehamElectronics** [comment]
That would work too, but I like the simplicity of instantly uploading logs into a discord channel, I'm guessing all you need to do is make the rule breaking channel function the same way any other Minecraft channel works which would allow us to format it and sync it with Discord integration which is already possible with chat control channels.

**Comment by kangarko** [comment]
Great, I've added "then discord" rules and handlers (will be renamed to groups) to CHC 9.1 ;)

And the context you could get using the new '/chc log' command in-game. Porting that to Discord is not feasible right now.

**Comment by LeehamElectronics** [comment]
Sounds great, thanks Matej I look forward to it.
