### ISSUE TITLE
How to enable Discord formatting per channel

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#1992]
As I mentioned in this issue: https://github.com/kangarko/ChatControl-Pro/issues/1987#issue-708124235
I have been having trouble setting up channels, however I can see a limitation already and I am not sure how to get around it. I want to setup different formatting per channel for incoming Discord messages. The following config option in the channels.yml does this but it seems to do it for ALL channels:
```
  Discord:
    #
    # If true, messages from Discord will be only send into a ChatControl channel
    # with exactly the same name, in the format below.
    #
    Control_Incoming_Messages: true
    #
    # If the option above is true, and channel is not installed on the server,
    # should be block the message from appearing in the chat? If not, DiscordSRV
    # will handle it and it will display to all players on your server.
    #
    Deny_Unknown_Channel: true
    #
    # When you are online both on Discord and in-game, apply your in-game formatting 
    # when you type from Discord? This will cause duplicated messages on Bungee, 
    # and it is therefore disabled by default.
    #
    Apply_Natural_Format_If_Online: false
    #
    # If you write a message on discord and you are NOT online under the same name,
    # the following format will be used. Specify full format or link in formatting.yml
    # If you are online, we will send it as though it was you from the server.
    #
    # Set to "" to use your channel's format, but this is not recommended
    # because we cannot replace variables since the player is not online!
    #
    Format: "&8[&3Discord&8] &7{player}: &f{message}"
```

Could we have the `Format: "&8[&3Discord&8] &7{player}: &f{message}"` option for incoming Discord messages per channel? This would be great so you can see where messages are coming from when you are listening to multiple channels from Discord at the same time.
Thanks

**Comment by kangarko** [comment]
Thanks, in CHC 9 I will make a special format part that will render when sender is coming from discord. You can just plug n play this to all formats.
