### ISSUE TITLE
owner send message not working

### ISSUE THREAD

**Issue by waiching514** [kangarko/ChatControl-Pro#1995]
my player can send message on bungeecord 
but owner cannot send message on bungeecord
------------------------------------[ 28.09.2020 11:23:41 ]-----------------------------------
ChatControl 8.8.9 encountered a MalformedJsonException
Running Paper 1.16.3-R0.1-SNAPSHOT and Java 1.8.0_262
Plugins: PlaceholderAPI v2.10.9, PlugMan v2.1.7, ConsoleSpamFix v1.8.4, PvPToggle v1.7, SSX-Connector v2.1.2, DeluxeTags v1.8.1, GameAPI v3.1.2, BungeeGuard v1.0-SNAPSHOT, RealTime v1.0, LuckPerms v5.1.93, OpenInv v4.1.4, ServerSelectorX vPremium-2.1.2, WorldBorder v1.9.10 (beta), ProtocolLib v4.6.0-SNAPSHOT-b478, LibsDisguises v10.0.16, MVdWPlaceholderAPI v3.1.1, UberEnchant v8.9.1, VoidGenerator v1.6.2, FeatherBoard v4.29.0, Vault v1.7.3-b131, Lores v1.4.1, LastLoginAPI v1.4.3, Item2Chat v4.6.1, HolographicDisplays v2.4.4, MyCommand v5.6.6, WorldEdit v7.2.0-beta-05+e575ffe, MysqlPlayerDataBridge v3.34.3, Essentials v2.18.1.0, AnimatedNames v7.3.2, spark v1.4.1, Multiverse-Core v4.1.0-b775, Citizens v2.0.27-SNAPSHOT (build 2113), EssentialsChat v2.18.1.0, TimeIsMoney v1.9.6.15, AncientGates v2.3.1, EnjinMinecraftPlugin v3.5.14, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.4+f7ff984, ajParkour v2.10.6, EssentialsProtect v2.18.1.0, EditableSign v7.3.0, PhatLoots v5.4.2, EssentialsGeoIP v2.18.1.0, EssentialsAntiBuild v2.18.1.0, GSit v[4.6.1.0], EssentialsSpawn v2.18.1.0, BungeeTabListPlus v3.4.0, CoreProtect v19.2, EssentialsMysqlStorage v1.22.2, Skript v2.5, SkQuery v4.1.3, AdvancedAbilities v2.4.2, CrateReloaded 2.0.29 by dinosaur, Shopkeepers v2.11.0, DiscordSRV v1.19.1, Plan v5.1 build 657, PlayerParticles v7.15, skRayFall v1.9.22, MythicMobs v4.10.1-SNAPSHOT, ChatControl v8.8.9, FogusCore v1.9.9, Parties v2.6.16, QuantumShop v3.9.6, PartiesSupport v1.0
----------------------------------------------------------------------------------------------

More Information: 
Failed to call toComponent!
Json: A{"text":"","extra":[{"text":"","extra":[{"text":"[","color":"dark_gray"},{"text":"OWNER","color":"red"},{"text":"] ","color":"dark_gray"},{"text":"","color":"yellow"}],"hoverEvent":{"action":"show_text","value":[{"text":"","extra":[{"text":"--------------------
Error: MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
MalformedJsonException Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
	 at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	 at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	 at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	 at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	 at com.google.gson.JsonParser.parse(JsonParser.java:60)
	 at com.google.gson.JsonParser.parse(JsonParser.java:45)
	 at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48)
	 at org.mineacademy.chatcontrol.i.bW.c(SourceFile:769)
	 at org.mineacademy.chatcontrol.hook.b.a(SourceFile:225)
	 at org.mineacademy.chatcontrol.hook.b.a(SourceFile:126)
	 at org.mineacademy.chatcontrol.i.W.onPluginMessageReceived(SourceFile:35)
	 at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
There is an 'A' letter at the beginning. If you are using JSON any places in ChatControl, put the 'A' in there and remove prefixes.
