### ISSUE TITLE
1.16.3：How to replace bungee jumping information with rules/packets.txt

### ISSUE THREAD

**Issue by Roselle-cloud** [kangarko/ChatControl-Pro#1996]
How to replace bungee jumping information with rules/packets.txt E.g. /Bungee /server etc.

**Comment by AngellitoX** [comment]
Hello! Could you please provide us a little bit more of detail of what would you like to achieve? I couldn't understand your question, sorry!

**Comment by Roselle-cloud** [comment]
> Hello! Could you please provide us a little bit more of detail of what would you like to achieve? I couldn't understand your question, sorry!

How to replace bungee information?
For example, This server is running BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:1520413:1535 by md_5
There are also commands such as /server

**Comment by kangarko** [comment]
Sorry these commands are "upstream" which means they are not visible to Spigot servers, thus we cannot edit/cancel them.
