### ISSUE TITLE
1.15.2: ChatControl Doesn't support Channels in DiscordSRV.

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl-Pro#1998]
Heyy I have encountered this error within DiscordSRV, and ChatControl.

When formatting it within discordsrv with the %channelname% placeholder it doesn't detect the channel name within chatcontrol.

https://i.imgur.com/vl92gLD.png
https://i.imgur.com/yPMFW3P.png
https://i.imgur.com/6qlIpBt.png

I am not sure if I am supposed to be contacting the discordsrv dev or you so I am putting this here as well as contacting him for support regarding this,

**Comment by AngellitoX** [comment]
Hello there! Thank you for reporting this. We will have a look into this and if it's an issue on our side, we will include a fix on ChatControl 9.1.0 :)

**Comment by kangarko** [comment]
Hey there,

We do not support DiscordSRV formatting. Instead, you need to enable Channels and use our own formatting.

ChatControl 9.1 that is going to be released soon has improved support for Discord integration.

Matej
