### ISSUE TITLE
Chat Control and Deluxe Chat

### ISSUE THREAD

**Issue by BiGUNMAN** [kangarko/ChatControl-Pro#2]
I want to use DeluxeChat for chat formatting but use Chat Control for channels. I currently have a "standard" channel thats joined by default, and a secondary channel, lets call it "secondary".

When a player joins and talks no chat is sent. A message in console does appear of their message though. (Should I modify listener priorities? Is their any known fix for this?)

**Comment by kangarko** [comment]
Due to how each of the plugins handles formatting, such combination is not possible.
ChatControl does channel formatting by its own because it is not possible to do otherwise.
