### ISSUE TITLE
/reply more variables

### ISSUE THREAD

**Issue by DanielVasquez4155** [kangarko/ChatControl-Pro#200]
Hello, I would like to have more variables implemented to the plugin's /reply
{sender}: The server of the message
{receiver}: receiver's name
Message: "&0[&a{player} &7-> &aYou&0]&8: &6{message}" -> Message: "&0[&a{receiver} &7-> &a{sender}&0]&8: &6{message}"

I would also like more variables for the spy message as well.
{sender-server}: sender's server
{receiver}: receiver's name
{receiver-server}: receiver's server
{message}: the message without the commands
Instead of having a prefix option, I want to customize everything
Prefix: '&8&o[Spying {player}&8&o] &7' -> Message: ''&8&o[Spying {player}&8&o] &7{message}'

**Comment by kangarko** [comment]
Hey,

I the receiver variables will be added, and are already in the roadmap. The rest has been added, you can check it out here: https://github.com/kangarko/ChatControl-Pro/issues/163
