### ISSUE TITLE
Suggestion: Run bungee command from Spigot server.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#2001]
By default you can not run a bungee command (Like /send) from a Spigot server, you can only run it from Bungee, so you cannot automate moving players between servers based off things that happen.

Implement a command to allow us to send a bungee command from spigot! Why? because you already have a bungee <--> spigot setup, and its utterly ridiculous that if I want to send a command from Spigot to run on the bungee it requires MORE plugins to be installed that open another listener, I already have LuckPerms & ChatControl pro that both have their own Bungee & Spigot counterparts to communicate between bungee/servers.

But why ChatControl Pro? Your amazing regex/trigger/handlers system to automate tasks based on user chat.

`/chc send bungee send all creative` would send the command `/send all creative` on the Bungee server from Spigot.

This means you could automatically send people to servers based on chat things.

_There are terribly made existing plugins that all have negative issues that already exist_
https://www.spigotmc.org/resources/commandforward.27580/
https://www.spigotmc.org/resources/commandbrothers-%C2%BB-send-console-commands-from-bukkit-to-bungeecord.44901/
https://www.spigotmc.org/resources/globalexecute.15732/
https://www.spigotmc.org/resources/bungeebridge.52500/

**Comment by kangarko** [comment]
Thanks, done for CHC 9.1:

![a](https://i.imgur.com/UiUHRAE.png)
