### ISSUE TITLE
1.16.3: /ignore no longer fully functional

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#2003]
With your modification to no longer synch with essentials' ignore, commands can now be used to bypass /ignore (/me, /mail, etc.).  You can continue to disregard essentials status and get away with this, but you would need to duplicate what /mute does in that case: where every listed command is considered to be a possible incoming message by that player for a player that has them on /ignore.  

chatcontrol pro 8.8.11
paper - 207

**Comment by AngellitoX** [comment]
Hey coffee! Nice to see you again.

Thank you for providing this useful information. As for now we're injecting all our efforts onto v9.1.0 which is a massive rewriten and face-wipe of what ChatControl used to  be. Hopefully this will bring a solution to all of the issues presented so far.

I'm keeping this open so kangarko can read it to see if there's any chance to bring a hotfix in the meantime.
Thank you!

**Comment by kangarko** [comment]
What about if you switched to ChatControl's ignore feature?

**Comment by mrcoffee1026** [comment]
Would still need the option to ignore other commands like the /mute function in chatcontrol does... otherwise it would only ignore anything initiated from within chatcontrol whereas anything run from any other plugin (like essentials: mail, msg, etc.) would simply bypass the ignore.

**Comment by kangarko** [comment]
We had to remove the bridge with Essentials due to stability concerns https://github.com/kangarko/ChatControl-Pro/issues/1867

Our entire backend has been rewritten so I could have implemented this feature back. Starting ChatControl 9.1.0, all /ignore commands will register the ignore feature in both ChatControl and Essentials.
