### ISSUE TITLE
1.12.2: How can i only show the join message in 1 world and not all the worlds

### ISSUE THREAD

**Issue by noobberry** [kangarko/ChatControl-Pro#2005]
How can i only show the join message in 1 world and not all the worlds, i only want the join message to show in world called "mainhub" and don't want it to show in my other 6 worlds, how can i do that please?

**Comment by AngellitoX** [comment]
Hello, currently you cannot achieve this. I am not sure if there is anyway @kangarko can add it to the future v9.1.0 releases but as for now I'd strongly recommend you to setup a BungeeCord network if you are looking to have a Hub.

Have a good day!
