### ISSUE TITLE
Question: 9.1.0 configuration file

### ISSUE THREAD

**Issue by ethernetcat** [kangarko/ChatControl-Pro#2007]
I'm looking forward to the new release but there's one thing I want to make sure of before releasing it.
When upgrading from 8.8.x to 9.1.0, will the format of the configuration file change, and do I need to reconfigure it? Or will the configuration file be converted automatically?

**Comment by kangarko** [comment]
Unfortunately that'll be the only time since 2015 we're asking for a full regeneration (not counting the other 9 Beta version that's now removed).
