### ISSUE TITLE
1.16.1: Join permission removed, still joins channel.

### ISSUE THREAD

**Issue by Krakenazo** [kangarko/ChatControl-Pro#2009]
Hello, 

I have an issue with the plugin. When a user is removed from a certain group in LuckPerms, he loses his permission to join certain channels... however, ChatControl keeps joining him to the channel on login.

Thanks.

**Comment by broken1arrow** [comment]
> 
> 
> Hello,
> 
> I have an issue with the plugin. When a user is removed from a certain group in LuckPerms, he loses his permission to join certain channels... however, ChatControl keeps joining him to the channel on login.
> 
> Thanks.

you use 8.8.12?

He as done this change and get this issue too. the b/ug is not hard too see, if normal player join a channel and go back he lose read mode. It work fine for spy mode but not read. I don't know if he miss something or we have to set new perm on players.

This change
Improve | Made the new feature from last version that makes the channel you left spying/reading check for the appropriate permission.

**Comment by Krakenazo** [comment]
Hello, 

I am currently using 8.8.3.

This issue has been a ocurring to me for the last year. The problem is with autojoin, not what you are mentioning.

Thanks anyway.

**Comment by broken1arrow** [comment]
> Hello,
> 
> I am currently using 8.8.3.
> 
> This issue has been a ocurring to me for the last year. The problem is with autojoin, not what you are mentioning.
> 
> Thanks anyway.

How has you set up the perms? It is a complex system of perms players need.

**Comment by Krakenazo** [comment]
It's very simple. Just add the permission to autojoin to a group and they join... the problem is when a user is removed from said group, because the plugin keeps putting him in the previous channel he had access to.

**Comment by kangarko** [comment]
Update ChatControl to the latest version, we have mitigated something like that.

**Comment by kangarko** [comment]
If you will still have issues, please set "Debug" to [channels] in settings.yml and post me your console log when a player joins and they should not join the channel but they do.
