### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#201]
23.04 14:01:45 [Server] INFO ... 16 more
23.04 14:01:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
23.04 14:01:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
23.04 14:01:45 [Server] INFO at sun.reflect.GeneratedMethodAccessor401.invoke(Unknown Source) ~[?:?]
23.04 14:01:45 [Server] INFO at nul.final...\\...........aux.LpT6.onPlayerCommand(SourceFile:238) ~[?:?]
23.04 14:01:45 [Server] INFO at nul.final...\\...........aux.lPt1.const(SourceFile:272) ~[?:?]
23.04 14:01:45 [Server] INFO at nul.final...\\...........aux.lPt1.const(SourceFile:288) ~[?:?]
23.04 14:01:45 [Server] INFO at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_60]
23.04 14:01:45 [Server] INFO Caused by: java.lang.NullPointerException: [REPORT ME] Rules map doesnt have rules type: COMMAND
23.04 14:01:45 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
23.04 14:01:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1346) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:45 [Server] INFO org.bukkit.event.EventException
23.04 14:01:45 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to ChatControl v7.3.5
23.04 14:01:45 [Server] INFO Sheepert_ issued server command: /top
23.04 14:01:45 [Multicraft] Skipped 80 lines due to rate limit (30/s)
23.04 14:01:43 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
23.04 14:01:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
23.04 14:01:43 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at nul.final...\\...........aux.lPt9.onCommand(SourceFile:52) [ChatControl.jar:?]
23.04 14:01:43 [Server] INFO at nul.final...\\...........aux.case.const(SourceFile:424) [ChatControl.jar:?]
23.04 14:01:43 [Server] INFO at me.kangarko.chatcontrol.ChatControl.private(SourceFile:216) [ChatControl.jar:?]
23.04 14:01:43 [Server] INFO at nul.final...\\...........aux.lPt1.const(SourceFile:67) [ChatControl.jar:?]
23.04 14:01:43 [Server] INFO at nul.final...\\...........aux.com4.const(SourceFile:824) [ChatControl.jar:?]
23.04 14:01:43 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.11.2-6.jar:git-Spigot-54ec0b8-7b044de]
23.04 14:01:43 [Server] INFO ^
23.04 14:01:43 [Server] INFO ... \n&6&l* &e&lKicked by: &7Console\n&6&l* &e&lReason: &7Advertisin ... 
23.04 14:01:43 [Server] INFO in 'string', line 104, column 87:
23.04 14:01:43 [Server] INFO expected alphabetic or numeric character, but found \(92)
23.04 14:01:43 [Server] INFO ^
23.04 14:01:43 [Server] INFO ... kicked!\n\n&6&l* &e&lKicked by: &7Console\n&6&l* &e&lReason: &7A ... 
23.04 14:01:43 [Server] INFO in 'string', line 104, column 78:
23.04 14:01:43 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning an anchor
23.04 14:01:43 [Server] ERROR Cannot load plugins/ChatControl/handlers.yml

Do not know what's wrong :(, says something about alphabetic or numeric character.

**Comment by kangarko** [comment]
Hey, it looks like you have a syntax error in your handlers.yml file. You can use http://yaml-online-parser.appspot.com/ to check the syntax for errors, or use pastebin.com and upload the file content to me.

**Comment by kangarko** [comment]
Assuming fixed, reply below if any questions
