### ISSUE TITLE
Hex Color Gradients?

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#2012]
Is there an easy way to make color gradients or will i have to add a hex code for each individual section to make the gradient?

**Comment by HexedHero** [comment]
You can use https://colordesigner.io/gradient-generator
but I agree, a gradient thing in CHC would be amazing.
<G#FFFFFF>Some Text<G#00000>

**Comment by kangarko** [comment]
Not right now, we're focusing on making the core stable first.
