### ISSUE TITLE
Settings for linking with Discord SRV

### ISSUE THREAD

**Issue by mA0w0** [kangarko/ChatControl-Pro#2013]
I read the wiki, but I can't understand it because I can't set it correctly.

I have purchased ChatControl Pro but I can't set it up properly.

What I want to do is send messages to Discord only from Discord Chat, and from Discord I want to send messages to Discord Chat.
Messages from Discord will not be displayed in-game, and all chat channels will send messages to Discord from within the game.

------------------------------------------------------------------------------------
Discord SRV
Channels: {"DiscordChat": "000000000000000000"}
------------------------------------------------------------------------------------
ChatControlPro
channels.yml
Enabled: true

  DiscordChat:
    Format: Discord_Chat
    Bungee: false
    Console_Format:'[DiscordChat] {player}: {message}'
    Log_Format:'{player}: {message}'
------------------------------------------------------------------------------------
Discord:
Channel name: Chat
ID: 000000000000000000
------------------------------------------------------------------------------------
Minecraft [GlobalChat] >>> Discord [Chat] = 〇
Minecraft [DiscordChat] >>> Discord [Chat] = 〇
Discord [Chat] >>> Minecraft [GlobalChat] = ×
Discord [Chat] >>> Minecraft [DiscordChat]  = ×
------------------------------------------------------------------------------------
paper:1.16.3
ChatControl Pro:8.8.13
DiscordSRV:1.20.0
CMI:8.7.8.1
Vault:CMIedition

**Comment by kangarko** [comment]
Add "Discord_Format" option to your DiscordChat in channels.yml. It can be the same as Console_Format. Then it will work.

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Discord#important-before-continuing-set-debug-key-in-settingsyml-to-discord-and-restart-this-will-save-you-hours-and-print-out-what-is-happening-to-the-console-after-you-are-finished-with-your-setup-you-can-remove-the-value
