### ISSUE TITLE
Why is the chat message from Discord to Minecraft unusually slow?

### ISSUE THREAD

**Issue by mA0w0** [kangarko/ChatControl-Pro#2014]
paper:1.16.3
ChatControl Pro:8.8.13
DiscordSRV:1.20.0
------------------------------------------------------------------------------------
[ChatControl 8.8.13] Discord to Minecraft took 13337.81 ms
[ChatControl 8.8.13] Discord to Minecraft took 13337.81 ms

Why is the chat message from Discord to Minecraft unusually slow?
Is there a way to improve it?

**Comment by kangarko** [comment]
Was the channel muted?

**Comment by kangarko** [comment]
Closing, please test the next version coming up soon.
