### ISSUE TITLE
1.15.2: Channel Changing Issue

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl-Pro#2015]
Hiya, I seem to be running into an issue with the channels in chatcontrolpro

When a player joins a channel with /ch join [channel name] write

It seems to hide all the other read channels the user auto joins is there a way I can work around this or ? 

Because I have set all the users to join every channel as read [with the autojoin permission]

then they just join the channels in write for each individual one since all users need to be able to read all channels at all times.

I may be being stupid if so I apologise in advance.

**Comment by Ash10744** [comment]
Upon further looking it seems to when joining the channel with write, remove the read permission for that channel when you leave it

**Comment by kangarko** [comment]
Can you please confirm this behavior on the latest version? See the options below and try setting them to the same values:

![a](https://i.imgur.com/owLbJXY.png)

I am closing this because I just tested and it was recently added ;)

![b](https://i.imgur.com/59SouAe.gif)
