### ISSUE TITLE
1.16.3: MySQL tps drop

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl-Pro#2016]
I had notice some tps  drops and all players gets kicked out of game and the issue has something with mysql:
The log:
https://gist.github.com/arturek1666/99e826450f9b4a051cc7ffa9453e0f98

This issue happens randomly in some time of the day. With is strange, by looking at log it looks like it might be chat control and that's why I decided to write a bug report ;)
ver:8.8.13
I had notice no MySQL issue after changing chatcontrol mysql to sqlite.

**Comment by kangarko** [comment]
Can you please keep using SQLite for now? Due to code constrains we must run these operators on the main thread on ChatControl 8. We are pushing a new major release where this will be erradicated.
