### ISSUE TITLE
1.16.3: Is there a way to disable the admin chat?

### ISSUE THREAD

**Issue by OperatorValexio** [kangarko/ChatControl-Pro#2018]
I currently have the channel functionality enabled and have created a global and staff channel with the intent of making the staff channel the replacement for the admin chat. This would allow my staff to opt in and out of reading the channel because admin chat doesn't allow you to do just that to my knowledge. So I was wondering if there is any way to disable the admin chat entirely and let my staff chat channel handle the admin chat work?

**Comment by LeehamElectronics** [comment]
You should be able to delete the admin chats configuration in the channels configuration file. I think Kangarko is going to replace the default admin chat or fix it in the new ChatControlPro 9 version.

**Comment by kangarko** [comment]
Currently not, ChatControl 9 won't have admin nor bungee channels and they will merge into regular channels you will be able to remove them.
