### ISSUE TITLE
ChatControlPro V9 Animated RGB?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#2019]
Just wondering if the new ChatControlPro version will add the ability to have players names in the chat constantly changing color with RGB? I know it is possible inside GUI menus and item lore to have animated RGB text, but will this be possible within the chat itself for prefixes or names? 
It would be a great perk for donors / patrons on servers.

Thanks

**Comment by kangarko** [comment]
Sorry not possible in chat without some hardcore packet manipulation which will lead to other problems. But, I have added the gradient feature ;)
