### ISSUE TITLE
Forward Interactive Chat to DiscordSRV

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#202]
I have been following your updates to support Discord SRV, but alas it still does not send the game-chat to the discord server, im still only getting when people log in/out which is handled by essentials.
Im using version 7.3.3 on PaperSpigot 1.11.2.

This is my chat.yml https://pastebin.com/DZkwgX25
And here is my settings.yml https://pastebin.com/3ysk4m05

**Comment by kangarko** [comment]
Hey,

at present, merely chat channels are sent to DiscordSRV. I am planning to expanding the compatibility and also forward basic chat there, soon.

I'd like to ask what do you think about this one: Should local-chat be forwarded to Discord as well?

**Comment by FrozenBeard** [comment]
Ah thanks for the update :)
I only use one chat, none of the channels or local.
DiscordSRV allows creating different channels to send to specific Discord Channels, so I would recommend using their built in system to forward specific chat to either one channel or different ones.

**Comment by kangarko** [comment]
Closing, this has been added. Feel free to commend below if you have any issues.
