### ISSUE TITLE
1.16.1: Player Notifications issue, Wrong highlight and colors

### ISSUE THREAD

**Issue by Mohamad82Bz** [kangarko/ChatControl-Pro#2020]
Hi there,
Recently I found an issue in player notifications in chat.

First problem: 
[https://imgur.com/a/dcwo2QK](url)
As you see in this picture, I wanted to tag a player named "taha5143", but it tagged another player named HA5.

Second issue: My chat color is Aqua (&b), when I tag a player rest of the messgae turns to white (&f), (You can see that in that screenshot, first leather is aqua but after the tag is white. Chat Color for normal players is gray, for them is fine. This issue only occurs when using different color in /chc color

EDIT: Sorry, but chat message turns to white for all players, not just the ones who picked a custom color.

Thanks for the great work!

**Comment by kangarko** [comment]
So sorry for forgetting to reply! This problem gets solved in the next ChatControl generation since it's not solveable with our current setup.
