### ISSUE TITLE
v9 Feature MythicMobs Death Messages

### ISSUE THREAD

**Issue by HexedHero** [kangarko/ChatControl-Pro#2021]
Add MythicMobs as support for the death message system so we can have cool custom messages for our custom mob deaths.

**Comment by kangarko** [comment]
How should that work? We'll support PlaceholderAPI for death message variables.

**Comment by HexedHero** [comment]
In the messages.yml, the Conditions where you list vanilla mobs, just allow us to list MythicMobs with their Internal names. Then just on death check if the killer is a MythicMob and then check for their Internal name on the list and use one of them death messages if not just use the normal mob type.

There is two simple APIs for this.
```
            if (MythicMobs.inst().getAPIHelper().isMythicMob(entity))
            {
                
                MythicMob mythicMob = MythicMobs.inst().getAPIHelper().getMythicMobInstance(entity).getType();
                String internalMobName = mythicMob.getInternalName();
                
            }
```

**Comment by kangarko** [comment]
Done for CCP 8 <3

https://i.imgur.com/jsqjB6c.png

**Comment by kangarko** [comment]
Feel free to follow up on mineacademy.org/discord

**Comment by HexedHero** [comment]
> Feel free to follow up on mineacademy.org/discord

Just a quick question, I didn't see anything about this added in the patch notes nor do I see any default config settings. Is this actually added into the release on Spigot?

**Comment by kangarko** [comment]
I'm sorry, I meant ChatControl 9. That is yet to be released.

**Comment by HexedHero** [comment]
> I'm sorry, I meant ChatControl 9. That is yet to be released.

Oh haha, no problem. Thanks for replying <3
