### ISSUE TITLE
Custom join messages

### ISSUE THREAD

**Issue by Rafalll** [kangarko/ChatControl-Pro#2022]
**Version: 1.16.3**

I have a problem with the configuration of messages, I have added three different information about joining players to the server. Everything works nicely, but when a player has an operator on the server it detects the wrong message. Is it possible to add a message priority? 
Configuration: https://pastebin.com/d085jAVW
In short, when I have an operator displays me premium_message and should display staff_message.

**Comment by kangarko** [comment]
Please give your player -chatcontrol.joinmessage.staff permission (that is a negative permission starting with a -, or "false" value if using LuckPerms)
