### ISSUE TITLE
1.12.2: Heavy PlayerJoinEvent when using MySQL

### ISSUE THREAD

**Issue by Mohamad82Bz** [kangarko/ChatControl-Pro#2023]
Hi there,
Recently I connected ChatControl to a MySQL (I'm using MariaDB, but it supports MySQL) database in all of my servers (including 1.8, 1.12.2 and 1.16.1 servers). Only in 1.12.2 ones, I have massive PlayerJoinEvent load.

Timing of the first 1.12.2 server: https://timings.aikar.co/?id=d4bf4d346e9f42c0ae55ee965e5c55d3
Timing of the second 1.12.2 server: https://timings.aikar.co/?id=2aab9013155a415d87762064f117f6cc

In my 1.16.1 server PlayerJoinEvent has ~1% load, but in these 1.12.2 servers I have ~300% load.

Dedicated Server Specs:
64GB Ram, Core i9-9900k, CentOS, Using MariaDB Database

I have a lot of plugins connected to the same database, but they are fine.

My server laggs a bit on PlayerJoinEvents. I'll really appreciate it if you can solve my problem, Thanks!

**Comment by kangarko** [comment]
Just to clarify both 1.16 (working fine) and 1.12 (with lags) use ChatControl?

I am aware of some slowdows when player is joining that will be patched in ChatControl 9.

**Comment by Mohamad82Bz** [comment]
I'm not completely sure about it, have a look at the timings:
1.16.1 Timings: https://timings.aikar.co/?id=30716a098231425f8948b216641edd5e

Another 1.12.2 timings: https://timings.aikar.co/?id=d92af48ed00148b598a2ac0ae5a8a065
As you see in this one, this server is a single void world server with a few plugins. It has LOTS of Join/Leave Events (It's my Authentication server)

**Comment by kangarko** [comment]
Thanks for providing these. Would it be possible if you disable MySQL for ChatControl on the auth server to see if the problem still persists?

**Comment by Mohamad82Bz** [comment]
Sure,
``[08:45:06 INFO]: [ChatControl 8.8.13] Join event took 653.77 ms``
This is the PlayerJoinEvent when MySQL is on (Auth server)

I disabled MySQL and here's the results:
``[08:49:07 INFO]: [ChatControl 8.8.13] Join event took 0.5 ms``
``[08:49:15 INFO]: [ChatControl 8.8.13] Join event took 0.82 ms``
Timings with MySQL Off: https://timings.aikar.co/?id=aee9bd7d7bd24919a320917dc27e80ac
Unfortunately instead of PlayerJoinEvent, I have PlayerQuitEvent high load.

My only usage of MySQL is changing player's channels when they change in one server.

**Comment by kangarko** [comment]
Thanks for letting me know. I'll look forward into making ChatControl 9 free of this issue and it'll load fast even having database enabled, for both join and quit events.
