### ISSUE TITLE
3 chat channels in ChatControl

### ISSUE THREAD

**Issue by vkys-vkys** [kangarko/ChatControl-Pro#2024]
Hello. I want to make 3 chat channels in ChatControl.
So the 1st channel will be local, with a visibility radius of 100 blocks. 2nd channel will be global, chat activation by entering "!" Example: "!Hello, everyone", will be sent to all worlds so that all players can see the message. 3rd channel trading, the same settings as the global channel, but activating the chat by entering "$" Example: "$Sell diamonds".

Is this possible in the ChatControl plugin?

**Comment by kangarko** [comment]
Hi there!

It is almost possible with ChatControl 8 where you could create these channels: https://i.imgur.com/KSEHNum.png

For the global chat, you would then use "/chc bungeechat"  which has the ! shortcut configurable under Bungee_Chat.Shortcut in settings.yml

However to type into the trading channel you would have to use "/channel send" or join it. I will unblock this limitation in ChatControl 9.
