### ISSUE TITLE
1.16.3: Tab-blocking functionality & Disabling features

### ISSUE THREAD

**Issue by OperatorValexio** [kangarko/ChatControl-Pro#2027]
I am aware that the plugin utilizes ProtocolLib for the tab blocking functionality, however upon enabling it, it disables the command suggestions as well, including for myself even though I have full permissions for everything. Is there a way to prevent this so that I can enable the tab-blocking functionality and disable the command suggestions for players, however disable tab-blocking functionality and enable command suggestions for me? Also, I wanted to know if with the new ChatControl version 9 coming out, will there be a possibility to see that users can enable and disable every feature within the plugin to allow for maximum customization?

**Comment by kangarko** [comment]
Hey there, sure, the new ChatControl with have much more detailed configuration:

![a](https://i.imgur.com/1tpvTzf.png)

**Comment by kangarko** [comment]
And also a bypass permission so that staff members can tab-complete everything.
