### ISSUE TITLE
1.15.2: Error on saving data crashing channels

### ISSUE THREAD

**Issue by Danielpeter-99** [kangarko/ChatControl-Pro#2028]
https://hasteb.in/esohecep.sql

Please see hasteb.in asap before its invalid.

For some reason channels are breaking on lastest version of Chc 8.8.16

**Comment by kangarko** [comment]
It's already invalid, please use pastebin.com or upload your full log here.

**Comment by Danielpeter-99** [comment]
[error.log.zip](https://github.com/kangarko/ChatControl-Pro/files/5398338/error.log.zip)
Pastebin has been down lately, thats why I haven't used it

**Comment by kangarko** [comment]
Remove your data.db and let me know if that happens again. Something has corrupted it.
