### ISSUE TITLE
Command /reply Malfunctions on Bungee

### ISSUE THREAD

**Issue by kangarko** [kangarko/ChatControl-Pro#203]
> Doing /r is glitchy at times. Some people do /r and it goes to me instead of the person they intended to reply, I'm not sure why this would even happen. I have not messaged these people and it confuses them, and I will find a way to reproduce it myself. There should be a config option to choose either one of the /r functions, but our network also prefers the essentials way.

Reported over Bungeecords.

**Comment by Shargann** [comment]
Experienced the same problem, but we are not using any cross BungeeCord functionality. Hard to reproduce, but sometimes /r messages goes to random people instead of replying to previous /msg.

**Comment by kangarko** [comment]
I am sorry for the issues. I am in the middle of the finals, but will do maximum to get to it shortly. Thank you for letting me know that it also happens off Bungee.

**Comment by kangarko** [comment]
Hey, I have done extensive testing but without luck. I have rewritten the private messages slightly to have latest coding standards, and added a debugger to allow you to track down the issue. Please read the changelog of the latest version 7.3.8 on how to enable it. Thank you.

**Comment by kangarko** [comment]
Closing, assuming it's fixed. Please comment below if you experience any unexpected behaviour.
