### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by FakEEE14** [kangarko/ChatControl-Pro#2030]
hi
im using 1.16.3 anc chat control 8.8.16
i have 7 servers on my local host connected to mysql data base when i connect the 8 one it's give me this error https://pastebin.com/GfvQkHWx .
when i disconnect one of the servers this server don't pop this error but the closed server when i run it again give this error why is that ?

**Comment by LizardNetwork** [comment]
I randomly saw your issue @FakEEE14   
I guess you need to increase the mysql max connection size.
>Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"

**Comment by FakEEE14** [comment]
thanks, im done with database problems, can you help me about this please

**Comment by LizardNetwork** [comment]
Check how many simultaneous connections to your mysql instance are allowed.  
Log into mysql and type `SHOW VARIABLES LIKE "max_connections";`  
If the limit is set too low every connnection request (coming from your plugins) will be dropped.  
Set a new limit (temporarily) according to your needs (`SET GLOBAL max_connections = NUMBER OF CONNECTIONS;`)

**Comment by FakEEE14** [comment]
it's on 100 any problem if i set it to 1000 ?

**Comment by kangarko** [comment]
I apology, I am not able to help since I don't have that expertise and that's a problem outside of ChatControl. But you can just ask out on SpigotMC forums and I'm sure people will help you out ;)

@LizardNetwork thanks for taking the lead here, feel free to comment below if you have anything else to say 👍
