### ISSUE TITLE
1.16.3: How to cooldown or use limit messages sent through global channel?

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#2031]
Speaking globally through bungee servers used to be a feature that was activated in one of the main configs, and allowed you to use the "/global" command for unlimited globally sent messages.

Some months ago this feature was removed, when I asked, I was told the standard method for global chatting now consisted in creating a global channel, which makes sense.

Hovever, even though this channel is extremely useful for cross server comunication, it would be nice to establish some limits in it's usage, else players could just naturally switch to unlimited global chatting, even if the topic is irrelevant to other servers, since it's simply the most effective chat.

Is there any way existing or implementable to limit the ammount of messages sent through global channel?

**Comment by kangarko** [comment]
Thanks, delay per each message and period limits will be added to ChatControl 9.1.
