### ISSUE TITLE
1.16.2 local MSG send to Discord 8.8.16

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl-Pro#2033]
If I use local chat it send it to global DC Chanel.

https://pastebin.com/mbZwvDHq

**Comment by kangarko** [comment]
I assume you are talking about mc-lokalt right?

If you want to, I can make it so that channels with the range option will not send message to Discord at all.

**Comment by broken1arrow** [comment]
> I assume you are talking about mc-lokalt right?
> 
> If you want to, I can make it so that channels with the range option will not send message to Discord at all.

Yes it is  mc-lokalt. Has work in older version with out it send to DC. 

Yes you can set it so range channels not send to DC (or if you can have a option if you want or not, true or false).

**Comment by kangarko** [comment]
Thanks I will add this!

**Comment by broken1arrow** [comment]
> Thanks I will add this!

I have try to fix it with your new version and I cant get it work (I will try more tomorrow).

**Comment by broken1arrow** [comment]
> Thanks I will add this!

I have try it out more and can not get it work soo not mc-lokalt not end up on discord. If i join mc-lokalt channel, if I use command "/channel send mc-lokalt test" it not send too discord.

I have an other strange bug, This when i try send messenger from discord to the game [DiscordSRV] [DEBUG] DiscordGuildMessagePreProcessEvent was cancelled, message send aborted 

Discord claiming it is the plugin some  hooking to discordsrv.

**Comment by kangarko** [comment]
Ensure you have these options in config.yml of DiscordSRV set:

- DiscordChatChannelDiscordToMinecraft: true
- DiscordChatChannelMinecraftToDiscord: true

Then set Debug key in settings.yml to [discord] and restart the server (do not reload). Post me the console message when you send a message to mc-lokalt and it won't end up on Discord, and also when you send message on Discord and it won't end up in the game.

**Comment by broken1arrow** [comment]
> Ensure you have these options in config.yml of DiscordSRV set:
> 
> * DiscordChatChannelDiscordToMinecraft: true
> * DiscordChatChannelMinecraftToDiscord: true
> 
> Then set Debug key in settings.yml to [discord] and restart the server (do not reload). Post me the console message when you send a message to mc-lokalt and it won't end up on Discord, and also when you send message on Discord and it won't end up in the game.

Yes I have set this to true.


27.10 16:27:23 [Server] INFO broken_arrow1 issued server command: /ch send mc-lokalt test
27.10 16:27:23 [Server] INFO [ChatControl 8.8.18] Command /ch send mc-lokalt test took 10.86 ms
27.10 16:27:34 [Server] INFO broken_arrow1 issued server command: /ch join mc-lokalt
27.10 16:27:42 [Server] INFO [mc-lokalt] broken_arrow1: test
27.10 16:27:42 [Server] INFO [DiscordSRV] [DEBUG] Chat message received, canceled: false

**Comment by broken1arrow** [comment]
> Ensure you have these options in config.yml of DiscordSRV set:
> 
> * DiscordChatChannelDiscordToMinecraft: true
> * DiscordChatChannelMinecraftToDiscord: true
> 
> Then set Debug key in settings.yml to [discord] and restart the server (do not reload). Post me the console message when you send a message to mc-lokalt and it won't end up on Discord, and also when you send message on Discord and it won't end up in the game.

Yes I have set this to true.

27.10 16:35:23 [Server] INFO broken_arrow1 issued server command: /ch send mc-lokalt test
27.10 16:35:23 [Server] INFO [discord] > Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false.
27.10 16:36:05 [Server] INFO [discord] > Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false.
27.10 16:36:05 [Server] INFO [mc-lokalt] broken_arrow1: test
27.10 16:36:05 [Server] INFO [DiscordSRV] [DEBUG] Chat message received, canceled: false

If i send from DC I get this (hm I have 3 Channels in DiscordSRV config, I seams like not use first channel).
27.10 16:36:54 [Server] INFO [discord] > Message not being sent to admin chat (configuration requires admin chat name: mc-admin)
27.10 16:36:54 [Server] INFO [DiscordSRV] [DEBUG] DiscordGuildMessagePreProcessEvent was cancelled, message send aborted

**Comment by kangarko** [comment]
It says:

> Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false

To fix that, simply write "Discord: true" option for mc-lokalt in your channels.yml

Then it says:

> Message not being sent to admin chat (configuration requires admin chat name: mc-admin)

To fix that, change your Admin_Chat Discord name in settings.yml from mc-admin to the channel where you want your messages to end up when they are sent from Discord's admin chat

**Comment by broken1arrow** [comment]
> It says:
> 
> > Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false
> 
> To fix that, simply write "Discord: true" option for mc-lokalt in your channels.yml
> 
> Then it says:
> 
> > Message not being sent to admin chat (configuration requires admin chat name: mc-admin)
> 
> To fix that, change your Admin_Chat Discord name in settings.yml from mc-admin to the channel where you want your messages to end up when they are sent from Discord's admin chat

If I set it true it not end up in discord from mc-lokalt?

**Comment by broken1arrow** [comment]
> It says:
> 
> > Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false
> 
> To fix that, simply write "Discord: true" option for mc-lokalt in your channels.yml
> 
> Then it says:
> 
> > Message not being sent to admin chat (configuration requires admin chat name: mc-admin)
> 
> To fix that, change your Admin_Chat Discord name in settings.yml from mc-admin to the channel where you want your messages to end up when they are sent from Discord's admin chat

https://bin.scarsz.me/0e22785b-11f4-40f5-b71e-78fcce7b06d0#DxX99Rknxe3uOT1rkoB3i4Q2lPnh2l0d

channels settings https://pastebin.com/ET4i2StY

**Comment by broken1arrow** [comment]
> It says:
> 
> > Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false
> 
> To fix that, simply write "Discord: true" option for mc-lokalt in your channels.yml
> 
> Then it says:
> 
> > Message not being sent to admin chat (configuration requires admin chat name: mc-admin)
> 
> To fix that, change your Admin_Chat Discord name in settings.yml from mc-admin to the channel where you want your messages to end up when they are sent from Discord's admin chat

I get this when i post ingame, and way it end upon discord. Strange is I use same settings om my testserver (soo long I can see and I only have problem with local chat leaking to discord).

28.10 22:20:53 [Server] INFO [discord] > Sending channel 'mc-globalt' message to a like-named Discord channel..
28.10 22:20:53 [Server] INFO [discord] [MC->Discord] broken_arrow1 send message to 'mc-globalt' channel. Message: 'Hej'
28.10 22:20:53 [Server] INFO [DiscordSRV] [DEBUG] Chat message received, canceled: false
28.10 22:20:53 [Server] INFO [mc-globalt] broken_arrow1: Hej
28.10 22:20:53 [Server] INFO [DiscordSRV] [DEBUG] Chat message received, canceled: false

**Comment by broken1arrow** [comment]
> It says:
> 
> > Message from channel 'mc-lokalt' not sent to Discord because the Discord option is missing or false
> 
> To fix that, simply write "Discord: true" option for mc-lokalt in your channels.yml
> 
> Then it says:
> 
> > Message not being sent to admin chat (configuration requires admin chat name: mc-admin)
> 
> To fix that, change your Admin_Chat Discord name in settings.yml from mc-admin to the channel where you want your messages to end up when they are sent from Discord's admin chat

I try  8.8.19 now and even my testserver get problems and now send two msg to discord one not get canceled and it still send MSG from mc-lokalt to discord (It should not do it).



31.10 14:52:45 [Server] INFO [DiscordSRV] [DEBUG] Chat message received, canceled: false
31.10 14:52:45 [Server] INFO [mc-globalt] broken_arrow1: he
31.10 14:52:45 [Server] INFO [DiscordSRV] [DEBUG] Chat message received, canceled: false
31.10 14:52:51 [Server] INFO [Discord->ChatControl] Ignoring Discord message from channel 'test-mc-global'. Available ChatControl channels: [mc-admin, mc-bedaborg, mc-globalt, mc-lokalt, mc-✆hjälp, town2]

**Comment by kangarko** [comment]
Hey,

Try disabling one, or both of these options in DiscordSRV/config.yml:

DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true

Let me know if it makes it work.

**Comment by broken1arrow** [comment]
> Hey,
> 
> Try disabling one, or both of these options in DiscordSRV/config.yml:
> 
> DiscordChatChannelDiscordToMinecraft: true
> DiscordChatChannelMinecraftToDiscord: true
> 
> Let me know if it makes it work.

It stop MSG completely, but I what it work on some channels.

**Comment by kangarko** [comment]
I'll contact their dev team regarding this, sorry that it's taking this long.

**Comment by kangarko** [comment]
Alrighty so I need to ask you to wait a little bit until ChatControl 9 is out, we're going to have a completely new discord setup there that should get the job done.
