### ISSUE TITLE
Modify bungee jumping information

### ISSUE THREAD

**Issue by Score2** [kangarko/ChatControl-Pro#2035]
I want to know whether bungee information can be modified in the plugin?
For example, this server is running the BungeeCord version of md_5 git: BungeeCord-Bootstrap: 1.16-R0.4-SNAPSHOT: 1520413: 1535
Or more information about bungee jumping commands

If it can be modified, the server customization will be more thorough

**Comment by kangarko** [comment]
No sorry, we can only modify messages produced on Spigot not Bungee.
