### ISSUE TITLE
1.16.2: Event Error 

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#2037]
Chatcontrol v8.8.12
Paper 1.16.2
Not quite sure what's causing the error https://pastebin.com/1NfXF6de
[error.log.zip](https://github.com/kangarko/ChatControl-Pro/files/5397915/error.log.zip)

**Comment by BobbyMere** [comment]
This error comes up whenever someone does `/r` and replies to someone dming the person using the plugin deluxechat

**Comment by BobbyMere** [comment]
Ihttps://pastebin.com/2yK4Yx3S

**Comment by kangarko** [comment]
Thanks, that was fixed yesterday, please comment below if you still experience issues or need my assistance.
