### ISSUE TITLE
Remove chatcontrol antipiracy check or use whitelist system

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#204]
Hi, i just get dossed and my server crashed because it can't comunicate for updates, and then chatcontrol get disabled because the comunication port, please use another system check like whitelist server ip...
Is the only premium plugin that cause these issue few times

**Comment by kangarko** [comment]
Hey, I have adjusted the system. the plugin should work in offline mode now. Please let me know if there are any issues with the next release (ETA: tonight)
