### ISSUE TITLE
1.16.3: Sounds and spy message.

### ISSUE THREAD

**Issue by OperatorValexio** [kangarko/ChatControl-Pro#2040]
I had a couple of issues that I wanted to see if I could get help on. Firstly, is there a way to disable the sound on join with the MOTD feature? And secondly, is there a way to disable the "You are now spying players' commands. Use /spy to disable." message every time I join?

**Comment by kangarko** [comment]
For the first, set Motd.Sound to "none" to disable it.

For the second, give yourself negative chatcontrol.spy.autoenable permission to prevent spying being toggled on when you join automatically.
