### ISSUE TITLE
1.16.3: Admin chat, chat color, and channel disabled message

### ISSUE THREAD

**Issue by OperatorValexio** [kangarko/ChatControl-Pro#2047]
Every time I restart my server, I seem to always join in the admin chat even though I was never in it before I restarted the server, as well as my chat color seems to be different (/chc color) even though I haven't changed my chat color. I my chat and chat color every time I relog, however once I restart again, the problem persists. In addition, I have channels disabled in my configuration, and upon typing /channel, I get the message: "ChatControl // Channel functionality is disabled. Set 'Enabled' to 'true' in channels.yml to turn it on.". I want to change this message and I've looked in the localization file, and the only thing I can find remotely similar is the "Channels_Disabled" option which reads: "Channels are disabled. To enable, set Enable to true in channels.yml.", but this is not the same message as mentioned therefore you cannot change it. Is there any way to change the message?

**Comment by james-d-elliott** [comment]
Will probably help if you supply some version information such as:

CCP Version
Spigot/Paper Version

**Comment by kangarko** [comment]
Admin and global chat are not channels. Ensure you have Bungee_Chat.Enabled_By_Default on false in settings.yml and don't have any autojoin permissions.

Unfortunately you can't change that message in this version but we'll plan to add this ability soon.
