### ISSUE TITLE
1.16.3: Symbols not working after Update

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Pro#2049]
When trying to use this symbol ► here:

Format_PM: "&cSPY &7{player} &c► &7{receiver} &8»&7 {message}"

It no longer works after update, before this was working appropriately

Error thrown:
https://hastebin.com/xeyijinahe.md

This is only happening on one mode as well... while all my other modes with the same config file work.

**Comment by Skizzles** [comment]
Seems when trying to use » in that same line it strips the formatting as well. Again only on this specific mode.

**Comment by kangarko** [comment]
There's a problem with your encoding, please see https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
