### ISSUE TITLE
Error ChatControl v7.3.5 wont load

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#205]
Heya, got stuck with this error in my server. The plugin wont load and immediately closes after this.

https://pastebin.com/1c4S3hBy

-Frank

**Comment by kangarko** [comment]
You are using some kind of plugin reloader (PluginAPI). Those are unsupported and cause problems.

**Comment by FrankHeijden** [comment]
o. thanks. didnt know that that was causing the problem. Thanks!
