### ISSUE TITLE
1.16.3: Admin chat not showing server placeholder

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Pro#2050]
Even with Server name setup appropriately, along with having the same exact config on all modes just changed server name.... the plugin does not show "Survival" as the server name in Admin chat.

![image](https://user-images.githubusercontent.com/30563757/96861516-0f65cd80-1419-11eb-9e38-4e1367f0a9eb.png)

**Comment by james-d-elliott** [comment]
AdminChat is treated completely differently to every other channel (format with DiscordSRV for example). My personal workaround is to use a channel the appropriate groups have access to, this solved all my issues with it.

**Comment by Skizzles** [comment]
> AdminChat is treated completely differently to every other channel (format with DiscordSRV for example). My personal workaround is to use a channel the appropriate groups have access to, this solved all my issues with it.

This is unrelated to a placeholder not working... lol

**Comment by james-d-elliott** [comment]
So if the placeholder works with a channel setup for admins/staff, and it doesn't when you use /chc adminchat.. it's unrelated. Gotcha lol.

**Comment by Skizzles** [comment]
> So if the placeholder works with a channel setup for admins/staff `/ch send admin`, and it doesn't when you use `/chc adminchat`.. it's unrelated..... gotcha lol.

Because it still needs fixed for the chc adminchat.... I am not reporting an issue about channels, only about the adminchat. Not sure how that is difficult to understand.

**Comment by kangarko** [comment]
ChatControl 9 will remove admin/bungee "special" chats completely and those will be treated as other channels with their appropriate variables.
