### ISSUE TITLE
Backport RGB from 9.1.0?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#2051]
Is it not possible to backport the new RGB support? This has been an issue for months, a few weeks ago you asked us through a poll whether to support it now or with 9.1.0 in a few weeks, it's really not nice to have this bug for potentially ''a few months'' more..

Or atleast the part to fix the issues below:

![image](https://user-images.githubusercontent.com/5664135/96869490-d147c880-146f-11eb-9fe9-640cfad636cf.png)

![image](https://user-images.githubusercontent.com/5664135/96869501-d442b900-146f-11eb-8930-c1634c17b749.png)

**Comment by kangarko** [comment]
No sorry, the original deadline for 9 was supposed to be October 1st actually but I had to leave my workspace since then. I only have time for one release.
