### ISSUE TITLE
1.16.3: PlayerJoinEvent being heavy

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#2052]
It seems the PlayerJoinEvent is a bit heavy. Any optimizations that can be done regarding this?

![image](https://user-images.githubusercontent.com/5664135/96869630-0522ee00-1470-11eb-8512-3df302f5fceb.png)

![image](https://user-images.githubusercontent.com/5664135/97153950-95fd1080-1773-11eb-92fb-06a35b51bf55.png)

https://timings.aikar.co/?id=5a045632cf3b40119457e3acdbfe947b#plugins

https://timings.aikar.co/?id=14ff65bf2da64725888ce3abe831205e#plugins

**Comment by HexedHero** [comment]
Same issue here, wish it was open source so I could help.

**Comment by kangarko** [comment]
It's the V8 way of doing things where we have to connect to MySQL on the main thread. V9 will connect on another thread so this won't happen.

To verify you can disable MySQL temporarily to see if this lag drops,
