### ISSUE TITLE
8.8.18: Discord_Format Removal

### ISSUE THREAD

**Issue by james-d-elliott** [kangarko/ChatControl-Pro#2053]
In 8.8.18 the Discord_Format option was apparently removed. I was previously using this to customize the format of each channels messages from Discord -> Channels. This was useful because we can strip values that cannot be obtained in this instance. Is there a replacement for this functionality?

**Comment by kangarko** [comment]
Where did it say it was removed? It is still there but not mandatory right now.

**Comment by james-d-elliott** [comment]
In the update notes, though it wasn't crystal clear hence the question: https://i.imgur.com/VFaBXY6.png

**Comment by kangarko** [comment]
Okay, sorry about the wording!
