### ISSUE TITLE
1 16 3  Ignore SuperVanished players in ranged chat

### ISSUE THREAD

**Issue by zhenaxel** [kangarko/ChatControl-Pro#2054]
Hello, I'm looking for cheaters on my server, I use the supervanish plugin and chatcontrol, all plugins of the latest version. the problem is this: when I follow the cheater, he writes to the chat (local) and he does not write what there are no players nearby, so he understands that he is being followed and turns off the cheat. I need to even if I followed the cheater, and he would write to the local chat, he would be written that there are no players nearby who could see his message. Please help me, how to implement this?

**Comment by zhenaxel** [comment]
?(

**Comment by kangarko** [comment]
Thank you, ChatControl 9 coming in a few weeks will have better support for vanished players and ranged chat.

**Comment by zhenaxel** [comment]
ok. thank you!

**Comment by zhenaxel** [comment]
> Thank you, ChatControl 9 coming in a few weeks will have better support for vanished players and ranged chat.

Thank you
