### ISSUE TITLE
Log Death Coords to Console

### ISSUE THREAD

**Issue by SiuanSong** [kangarko/ChatControl-Pro#2055]
Please consider adding logging abilities for deaths to console which includes the death location and cause.  I would much rather see that information in console than just the death message that gets put in chat as it's set up now.  I used to use DeathMessagesPrime for this, but it has been discontinued and stopped working properly on my server anyways.  It was a very useful feature to find death locations, if my custom death position plugin failed, or in the case of someone being spam killed.  It'd also be beneficial to NOT include the location in the chat message as, on our server, we don't want others running to someone else's death point to take their items.
Thanks for your consideration!
- Siuan

**Comment by kangarko** [comment]
Sure, in ChatControl 9 you will be able to create a log parameter for your death message including location variable:

![a](https://i.imgur.com/DCNHnwZ.png)

**Comment by SiuanSong** [comment]
Awesome, thanks!
