### ISSUE TITLE
1.16.3: How to use Formatting?

### ISSUE THREAD

**Issue by JHiroshige** [kangarko/ChatControl-Pro#2056]
So I enabled the feature "Formatting" but now the names are "messed up". I can only see the actual Username but I want the Essential Nick. I also check in the formatting.yml if there's something with the names.

Version: 8.8.15

**Comment by ArtelGG** [comment]
Refer to the [wiki](https://github.com/kangarko/ChatControl-Pro/wiki/Variables).

**Comment by JHiroshige** [comment]
I mean I already read through the entire wiki. I just checked every config file again and fixxed my problem
