### ISSUE TITLE
BungeeControl config resetting on server load, using latest Waterfall and latest BungeeControl

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#2057]
After updating to latest ChatControlPro and BungeeControl, my BungeeControl config resets each time I change "Lobby" or add another line under it to make another server alias:
```
#
Server_Aliases:
  #
  # Name in config.yml : Your alias
  #
  Lobby: hubasd

#
```

As you can see, I am able to change the value of "Lobby: " from "hub" to "hubasd" or whatever, but If I change the key "Lobby" to "lobby" or add another line, the config resets! 
This only started happening when using version 2.3.8 of BungeeControl
I have tried deleting the entire plugin folder to let it regenerate, but it still happens...
Thanks

**Comment by rumplepusscat** [comment]
Same issue here!

**Comment by LeehamElectronics** [comment]
Did you get any error codes on startup?? @rumplepusscat

**Comment by kangarko** [comment]
Thanks, will be fixed.
