### ISSUE TITLE
Double join message

### ISSUE THREAD

**Issue by Kedarin** [kangarko/ChatControl-Pro#2058]
Hey I have a problem I use the join message by ChatControlPro and only the join message ( [+] %player% ) are duplicated ( two times )
not the leave message I don't understand why, this is my config : https://pastebin.com/11MSRYL8

Thank's

Version: 1.8.8
Chatcontrol Version: 8.8.18

**Comment by kangarko** [comment]
I cannot reproduce this. Try removing other plugins in case they cause this or remove the empty message condition or replace it with "none".

<img width="282" alt="Skjermbilde 2020-10-27 kl  11 28 31" src="https://user-images.githubusercontent.com/1918426/97289510-94048180-1847-11eb-9539-3d5d79e35fc0.png">
