### ISSUE TITLE
[request] Enable tab-fillign before @ symbol for tagging in chat

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#206]
Allow you to use tab auto fill for @ messages in chat, its impossible to auto tab their username then move curser back to put the @ before it, drives me mad.

**Comment by kangarko** [comment]
Hey,

as per the current system, tagging does not support auto-completing. It is not possible unless I completely rewrite the system (up the river, in a way), which I currently don't have time for unfortunately.

**Comment by FrozenBeard** [comment]
Tagging is useless without auto complete, nobody uses it and just uses usernames instead, ditch the @ and tag usernames in chat if there online? Or remake it properly.
