### ISSUE TITLE
1.16.3: Regex rule interpreting "ñ" as "n"

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#2062]
Hey, this is probably more of a regex question, but still had to ask:

in rules.yml:

```
# Blocks 'coño'
match \b(c+(\W|\d|_)*o+(\W|\d|_)*ñ+(\W|\d|_)*o+(\W|\d|_)*)
handle as swear
```

but if you write "cono", you get censored, any idea why?

**Comment by MithrandirCraft** [comment]
Closing. Just added an exception so it's ok anyway. Still don't get why n = ñ though, must be regex things or character set.

**Comment by kangarko** [comment]
Set Translate_Diacritical_Marks to false in settings.yml to prevent accents from being removed and matched

**Comment by MithrandirCraft** [comment]
Actually I think I might wanna keep it true, since vocals being interpreted with or without accents can really help. Just not the ñ though.
