### ISSUE TITLE
1.16.3: Factionsx/towny support?

### ISSUE THREAD

**Issue by GenericGames** [kangarko/ChatControl-Pro#2063]
Hello, I'm interested in getting ChatControl pro but had some quick questions. I wanted to know if it supports faction/ally channels with factionsx and town/nation channels for TownyAdvanced? If so does it just work or would each faction/town/nation need their own channel?

**Comment by kangarko** [comment]
TownyAdvanced is supported in that you can create ChatControl Pro channels only speaking to people in the same Town. We also can ignore TownyChat channels.

FactionsX is unlikely supported (I have not tested it).

**Comment by kangarko** [comment]
Yes, we will have a channel party option to only show channel to FactionsX same players.
