### ISSUE TITLE
1.16.3: Player trying to send message channel results in error

### ISSUE THREAD

**Issue by NerdyBirder** [kangarko/ChatControl-Pro#2064]
https://pastebin.com/MDceQsYH

After setting up channels in the server, they work perfectly when an admin is opped but when a player tries to use the channel this error is sent. Permissions are correct for the player to use that channel but it is still sending the error. The player is able to send messages back and forth and the global chat works fine.

![image](https://user-images.githubusercontent.com/32281657/97110589-5faa8d00-16b0-11eb-9c7a-247aaaafb653.png)

**Comment by kangarko** [comment]
Hi Nerdy,

I apology for the problem. Please wait and update to 8.8.19.

Matej
