### ISSUE TITLE
Paper 1.12.2 MAJOR Regex crashes server for certain words used in global chat

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#2065]
This is a major bug with your regex system, I had a crash last night where a user spammed the / character which caused the Regex in ChatControl pro to go mental and crash the server,It seems to have triggered my "lag" regex, but directly before it gets stuck a user uses this in chat which may be the cause `////////fffffffffffffffffffffffffffffffff/`
Using ChatControl 8.8.9 on Paper 1.12.2

The regex in question I have used for **YEARS** is to give the user a message when they spam "lag" but I cant see the user Secret_88 write lag anywhere in the logs, but I do see the user the_duke_ell use that weird //// thing in chat that could be the cause?
Either way, this is a regex ive used for years, and "lag" is very commonly spammed, this is the first time ive seen regex crash the server.
```
# LAG Filter
match \b[Ll]+\s*[Aa]+\s*[Gg]+
#then warn &cDon't spam lag. Check your /ping and check your FPS (F3).
then warn &a&lPlease don't spam. Check your &9&l/ping&a&l for your internet connection (Anything over 300 won't be helpful!) and also check your F3 for FPS Client Lag. Use our MineCraft lag guide to diagnose and solve your issues&d http://bit.ly/MinecraftLag
```

When the user used  `////////fffffffffffffffffffffffffffffffff/` in chat, this was the errors it caused before crashing the server.

https://gist.github.com/TomLewis/6a99da219a7a38dcc494cd185e4dea04

**Comment by TomLewis** [comment]
There was a second crash, and it looks like its to do with the spam of the same letters, `Username issued server command: /r fifffffffffffffffffffffffffffffffffffffffffffffffffteen`

Which again crashed the server.

Either that or something to do with both users spamming "F"

**Comment by kangarko** [comment]
Hi Tom,

We haven't changed the regex system since 2015, in fact we have no control over parsing regular expressions since this is on on Java's side. And this can't be moved off of the main thread because we could not cancel the message nor edit it.

Not sure why it started to happen. I'd perform basic checks such as updating Java. Worst case you'd have to remove or alter the filter. I apology I was not able to help.

**Comment by TomLewis** [comment]
It wasnt actually that first regex for Lag that I posted, as the second time it happened it was for "fifffffffffffffffffffffffffffffffffffffffffffffffffteen" which leads me to believe its the check to check for stopping people from spamming, which is built into chatcontrol pro.
It isnt the rules I created and have used for years.

**Comment by kangarko** [comment]
I apology but I can't yet reproduce this problem. Going to set up a test environment in 24 hours. Would you be so kind and send over your whole folder except for logs and mysql to kangarko at SpigotMC?

**Comment by TomLewis** [comment]
Yeah no sweat.

**Comment by kangarko** [comment]
Thanks! On it!

**Comment by kangarko** [comment]
Alrighty so I got the main lag when player is joining/quitting solved. Also tested the rules, and when I typed the message you mentioned, it really seemed the rules are processing something in cycle. I found that it freezes after this rule:

(?!(f|F)ake|(f|F)aking)(f|F)+(?:(?:[^a-z]*([^l\s])\1*[^a-z]*(c|C)+[^a-z]*(k|K)+)|(?:(?:u|e|a|c|U|E|A|C)+(k|K)+[^e])|(?:(u|[^a-z])(c|[^a-z])k+))

I made the plugin now correctly output this problem so that you can solve it easily.

Next time check rules after editing them using regex101, don't default to blaming me for bugs in the plugin.

<img width="1022" alt="Skjermbilde 2020-11-05 kl  12 45 33" src="https://user-images.githubusercontent.com/1918426/98237202-d2dfb900-1f64-11eb-9559-cdda6ef0c5cb.png">

**Comment by TomLewis** [comment]
How do I debug the rules its processing? 

We do check all our regex in Regex101 first, its how they Regex is made, but we do not get the error.

![Screenshot 2020-11-05 at 11 54 21](https://user-images.githubusercontent.com/144046/98238003-aaa08c00-1f5d-11eb-8527-58e8d0a5834b.png)

**Comment by kangarko** [comment]
The next version will have detailed information on fixing this. You also need to enable insensitive and unicode matching. Also next version will bring the option to disable insensitive (which then also disables unicode) matching.

<img width="981" alt="Skjermbilde 2020-11-05 kl  12 59 11" src="https://user-images.githubusercontent.com/1918426/98238487-b6dd1700-1f66-11eb-8b74-641ed4e6c28c.png">

**Comment by kangarko** [comment]
But even now, you see it has 30,000 steps, which is huge and will suck performance. The rule is dangerous and I recommend you stick with our \b(f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*) filter that has 29,950 CPU cycles less.

**Comment by TomLewis** [comment]
Oof, this is key information that should be written in the rules.txt, how on earth are people suppose to know that!

I don't even know what insensitive and unicode matching does differently? 

Also quick note can you please rename all your /rules to `rules.yml` instead of rules.txt so that Code Editors auto color the syntax, its so annoying have to change it every time I open a file.

I just checked our rules.txt and our `fuck` filter has changed since this ticket was made, its currently;
```(?!(f|F)ake|(f|F)aking)(f|F)+(?:(?:[^a-z]*([^l\s])\1*[^a-z]*(c|C)+[^a-z]*(k|K)+)|(?:(?:u|e|a|c|U|E|A|C)+(k|K)+[^e])|(?:(u|[^a-z])(c|[^a-z])k+))``` Which still breaks it with these odd settings you have insensitive and unicode.

30k Cycles are a hell of a lot, But since we never know that you had "insensitive" somehow on, we have had to test EVERY SINGLE regex with case sensitivity, we assumed you forgot and re-wrote all the regex for nearly all your regex....

Thats quite key information you forgot to tell anyone...

**Comment by kangarko** [comment]
I will include that to the wiki and the docs. Thanks for letting me know. 

Rules will use a new .rs format starting CCP9, if someone makes a syntax highlighter for it I will add it to the docs. The yml format would highlight things poorly since it's not yml.

**Comment by TomLewis** [comment]
Whats a .rs? rust?
We just need omething that treats comments as comments and the rest as code.

You should look into what regex syntax highlighting in VSCode, everyone will be using VSCode and its the best thing to recommend people to edit their configs, then pick an extension for that which it defaults to.

https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019

**Comment by kangarko** [comment]
Thanks for the feedback!

**Comment by kangarko** [comment]
@TomLewis are you okay with me including some rules from your configs such as smileys into the default CCP 9 rules? They are hilarious!
