### ISSUE TITLE
1.16.3: Is there a vault balance variable for this plugin (%vault_eco_balance%)?

### ISSUE THREAD

**Issue by JHiroshige** [kangarko/ChatControl-Pro#2066]
So I want to use some more variables than just this here [Variables](https://github.com/kangarko/ChatControl-Pro/wiki/Variables)
I really need this here %vault_eco_balance% but I dont know how to write a JavaScript.
I would be thankfully if someone could help me here

**Comment by kangarko** [comment]
We don't have an economy system in ChatControl. You can use PlaceholderAPI and {vault_eco_balance} syntax.
