### ISSUE TITLE
Multiple join messages with permissions isn't working.

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#2069]
Minecraft: 1.16.3
Paper: 247
CCP: 8.8.18

in messages.yml i am trying to setup different join messages with permissions for each premium rank. i set three different join messages and three different permissions, with the corresponding permission in each group.

The result is that the join message is always the same message from one of the permission groups i set. it's the same message even when i change premium ranks or use the default rank (the default rank is supposed to the default join message, which has no permission).

there is no error.

**Comment by AngellitoX** [comment]
Hello, this issue sounds like you have a weight issue on your permissions config. A quickfix would be something like this:

1. If Rank A has chatcontrol.joinmessage.A, and you want B to have a different one, the add `chatcontrol.joinmessage.B to` to Rank B, but also **negate** `chatcontrol.joinmessage.B` into B.

This would help you to display the permissions correctly, as you actually need to work on your permission groups and also check the inheritance between them.

Hopefully this will work for you. Have a nice day! 

I'm closing this in favor it gets resolved. In case it doesn't, comment below and we can keep following it.

**Comment by KasearMC** [comment]
that didn't work. man... i'm dead. i've been at this all day. it's broken.
it seemed to be working somewhat well recently until i made more changes. i don't know what's wrong. maybe it's my fault, dammit i hope it's my fault because then it's an easy fix; but to me it looks like it's configured perfectly.

like... i don't know. let's just get to the bottom of this.

i refreshed the plugins, restarted the server, etc. everything. this is what i have now:
https://pastebin.com/7jdSVrAm

my groups are set up so that the default group is separate from the premium groups. the premium groups do not inherit from the default group. when a player buys a premium group they will have both the premium group and the default group. the stronger premium group inherits from the first lower level premium group.

when i give the corresponding permissions to those ranks, it only prints:
[https://i.postimg.cc/BnJF4177/9078i798yj.jpg](url)
it doesn't even print the other message in the same list.

when i switch between any of the premium groups, it's the same result.

when i add the weaker join permissions to the stronger premium groups and set them to false, it's the same result.

when i remove myself from premium groups entirely, it's the same result.

when i completely remove all join permissions from all of the groups, it's the same result in each group i join.

when i make the messages double quote instead of single quote, it's the same result.

i should have been in bed over 4 hours ago. i've been dead for hours.

**Comment by KasearMC** [comment]
any insight into what's going on?

**Comment by KasearMC** [comment]
look, i don't care if it's a bug in the plugin.
all i want from this is to know if this is an issue on my end or not.
if the former, what did i do wrong?

**Comment by kangarko** [comment]
Do not use any special letters like + in your Permission. try using vip_1 then vip_2 instead.

If you have:

- chatcontrol.joinmessage.vip
- chatcontrol.joinmessage.vip_1

Then you must give the vip_1 group negative chatcontrol.joinmessage.vip permission (the one with a value of false if using LuckPerms)
