### ISSUE TITLE
'?autoReconnect=true' blocking '?useSSL=false'

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#207]
Hey, could you maybe add custom arguments for connecting to a mysql database? because when i use database= chatcontrol?useSSL=false it will complain about the useSSL argument, because thats not working well with the standard ?autoReconnect=true argument. 

In this case it should be ?useSSL=false&autoReconnect=true

Hope there is a fix! 👍

**Comment by kangarko** [comment]
Hey, I'll add an option to customize the connection option entirely in the next version (ETA: tonight)

**Comment by FrankHeijden** [comment]
Cool, thanks. Console is full of those SSL connection failure messages :x
