### ISSUE TITLE
ChatControl Pro 8.8.19

### ISSUE THREAD

**Issue by srrawr11** [kangarko/ChatControl-Pro#2072]
I don't know how to fix this, could you help me please?
https://pastebin.com/tvRVe25j

Thanks!

**Comment by kangarko** [comment]
Thanks, ensure you have latest BungeeControlBridge.

Next version of chatcontrol will have a more informative error when that happens, just report your error below and I fix it then.

**Comment by srrawr11** [comment]
https://pastebin.com/fPVaAG95

**Comment by kangarko** [comment]
Redownload the plugin and if you still have error, contact me through the account you purchased the plugin with at SpigotMC.

**Comment by srrawr11** [comment]
Perfect, now seems that si working fine, but let's see, if there are any errors, I will let you know!
Keep going, you doing a great job! My respects!

**Comment by srrawr11** [comment]
Hi, do you know how can I block these for users?
For example I put / and it shows these commands?

https://imgur.com/vFzIiCE

**Comment by kangarko** [comment]
Sorry, you cannot right now, but it's coming into ChatControl 10 that will be out very soon.
