### ISSUE TITLE
Using a chat channel to chat across servers on the bungee netwrok

### ISSUE THREAD

**Issue by cobrex1** [kangarko/ChatControl-Pro#2074]
Verison 1.16.3, Waterfall Bungee Control version 2.3.9, Chatcontrol 8.8.19.

I have been struggling with this for 3 hours now and I cannot get chatcontrol to do what I would like it to do.

I want to use Global channel as speaking to all servers and standard channel for the server the player is on. I would players to choose if they want to see all chat, just bungee wide chat or just the server chat they are on.

I cannot see how to configure it to work as everything I try does not work. 

This is my channels yml: https://hastebin.com/jozonejuho.yaml

This is my formatting yml: https://hastebin.com/riruwasuyi.yaml

This is my settings yml: https://hastebin.com/uhaxedoroq.yaml

The server-name in the server.properties matches the name in the config.

Any help would be great. I do not want to use the BungeeChat option because you cannot join or leave that chat channel and I want player so choose to chat in global (cross server) or standard (local server).

Hope this all makes sense

**Comment by kangarko** [comment]
How exactly it does not work?

**Comment by cobrex1** [comment]
Hi Kangarko, thank you for taking the time to reply to my query.

When I have the above settings set, others cannot see the message I send in the global chat channel from the hub server to players on the survival server, even though the Bungee option is set to true in the global channel in settings yml. I am sure I have missed something really simple, just cannot see/find it. 

Can I use the global channel across servers or do I have to use the bungee channel for cross server chat?

**Comment by cobrex1** [comment]
and I cannot get out of this. I am op'ed and negated the bungee channel permission.

https://gyazo.com/e25fcbde7d0f932cb4724cfdb1213e23

**Comment by kangarko** [comment]
Can you try disabling the Bungee_Chat from settings.yml and having a "global" channel in channels.yml instead?

**Comment by cobrex1** [comment]
Bungee_Chat:
  Enabled_By_Default: false
  Log_To_Console: true
  Write_To_File: true
  Shortcut: '!'

I have this set:
BungeeCord:
  Enabled: true
  Prefix: '&8[&5server_name&8] &7'

But when I join with my non-op'ed account I get this:
https://gyazo.com/320df767f677e032091b9879fd787b65

and I cannot get out of this - even though I have the options of Global and Standard open to me also.

**Comment by kangarko** [comment]
Try doing /chc bc toggle or /chc bc switch

**Comment by cobrex1** [comment]
Brilliant, ok that worked, ty. However, now when I use the Global channel on the the server and my alt is on the global channel on the hub I cannot see the chat cross-server?

Is there a way to ensure all players do not need to do the /chc bc switch command on join?

**Comment by kangarko** [comment]
Thanks! Closing, if you need any help just comment below.

**Comment by kangarko** [comment]
You can also check the wiki page about Channels and autojoin permissions to automatically join players there on join.
