### ISSUE TITLE
1.16.3: show name colors with formatting/bungee chat enabled

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl-Pro#2075]
Is this possible in anyway? Players can change their name colors on my server but they're not showing up in chat with bungeechat enabled, any workaround for this would be super appreciated:) 

May I suggest a /chc NameColor perhaps?

**Comment by LucidAPs** [comment]
When i have bungee chat enabled, users will loose their prefixes and name colors. Any way to fix this?

**Comment by kangarko** [comment]
You can create a "global" channel in channels.yml instead of using the Bungee_Chat. There, it should retain both colors and prefixes if the format you configure for that channel has them.
