### ISSUE TITLE
1.16.3 : Discord Admin Chat not working (DiscordSRV)

### ISSUE THREAD

**Issue by JHiroshige** [kangarko/ChatControl-Pro#2076]
30.10 11:22:47 [Server] INFO JHiroshige issued server command: /chc ach test
30.10 11:22:47 [Server] INFO test
30.10 11:22:47 [Server] INFO [MC->Discord] Could not find Discord channel 'mc-staff-chat'. Available: global. Not sending: test

I put the exact same name from the discord channel
![image](https://user-images.githubusercontent.com/67478052/97700579-610ef780-1aac-11eb-805e-6adb066cf549.png)

**Comment by kangarko** [comment]
See the wiki on how to pair channels. You need to connect mc-staff-chat with your DiscordSRV and chatcontrol first.
