### ISSUE TITLE
About the translation language of the plugin

### ISSUE THREAD

**Issue by mA0w0** [kangarko/ChatControl-Pro#2078]
I haven't translated everything yet,
There is a part that seems untranslatable.
'and' looks for a language file but doesn't seem to be there.
Can I add items to translate?
![87d8368700f8f225491390c97cf1108d](https://user-images.githubusercontent.com/72402669/97781085-58154780-1bcc-11eb-9ece-b5b100f9cd2c.png)

**Comment by kangarko** [comment]
Thank you, for ChatControl 9 we will add the ability to translate everything.
