### ISSUE TITLE
Channel Messages send across bungee sporadically

### ISSUE THREAD

**Issue by NerdyBirder** [kangarko/ChatControl-Pro#2080]
We have a bungeecord network and use ViaVersion to run different minecraft versions on different bungeecord instances. 
We are using plugin version: 8.8.19 and Bungeecontrol 2.3.9.

The issue we have been having for multiple versions of the plugin is that messages in channels only sometimes send across bungee. A player can send a message in one instance and it will be seen by everyone in that same instance but it might not be seen in another instance. When I send a channel message in one instance most of the time it is not seen in any other instance by anyone else. I have rewritten the config files for my server's update to 8.8.19 and reset all permissions to try to fix this.

There are no console errors with this issue.

[ChatControl 10-31.zip](https://github.com/kangarko/ChatControl-Pro/files/5471123/ChatControl.10-31.zip)

**Comment by kangarko** [comment]
Could you isolate the case when that happens? OP/non-OP? Any special attributes the player may have?

You can also set the Debug option to [bungee] and post me the console log when that happens vs a normal case.

**Comment by c0wg0d** [comment]
I'm having this same problem since updating from 8.8.6 to 8.8.19.

**Comment by NerdyBirder** [comment]
I have not noticed any kind of pattern with player permissions or if they are OP or not.

Here I have two pastebins of us trying to send messages between two bungee instances. Sorry they are not the same format but one is from console and one is from logs. 
https://pastebin.com/s2bFG8dV (my staff was in this instance sending messages in our Staff channel, he is not OP)
https://pastebin.com/cgvx92QL (I was in this instance trying to send messages in the staff channel, i am OP)

**Comment by kangarko** [comment]
Just to confirm you are not using Admin_Chat nor Bungee_Chat right?

**Comment by NerdyBirder** [comment]
I am using bungee_chat for our global chat system across instances i think. But we are not using admin_chat.

**Comment by kangarko** [comment]
Let's continue here: https://github.com/kangarko/ChatControl-Pro/issues/2081
