### ISSUE TITLE
Cannot see chat in some channels from group of players

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#2081]
I updated ChatControl from 8.8.6 to 8.8.19. and BungeeControl from 2.3.4 to 2.3.9.

I have not changed my ChatControl configuration in years, so when I update and things break, it is extremely frustrating.

I am not seeing chat from my other moderators in channels that I am spying, but I see the chat from regular players.

I can also send chat to a different channel that I am spying, but nobody will see it but me.  Also those messages no longer get sent to Discord like they used to.

In each server, all players are given the following permissions (I am saying {channel} but it's specific to each server, like 'skywars' for our Skywars server chat channel):

chatcontrol.channel.{channel}
chatcontrol.channel.{channel}.join.write
chatcontrol.channel.autojoin.{channel}.write

Moderators are also given the following permissions in ALL servers for all available chat channels we have:

chatcontrol.channel.{channel}
chatcontrol.channel.{channel}.join
chatcontrol.channel.{channel}.join.spy
chatcontrol.channel.{channel}.leave
chatcontrol.channel.{channel}.send
chatcontrol.channel.{channel}.spy

As I said, I haven't changed these permissions or my config in years, and it used to work fine with 8.8.6.  Please let me know what other info you need.  My configs are attached.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5471730/ChatControl.zip)

**Comment by astirling** [comment]
What chatcontrol.bypass permissions are you assigning these groups?  I had similar issues due to staff being OP and had to negate chatcontrol.bypass.* until I could configure permissions to allow for non-OP administration.

**Comment by c0wg0d** [comment]
None of us have OP permissions.  We have several bypass permissions set:

chatcontrol.bypass.capitalize
chatcontrol.bypass.caps
chatcontrol.bypass.channellimit
chatcontrol.bypass.clear
chatcontrol.bypass.dupe.chat
chatcontrol.bypass.dupe.commands
chatcontrol.bypass.ignore
chatcontrol.bypass.limit.chat
chatcontrol.bypass.limit.commands
chatcontrol.bypass.move
chatcontrol.bypass.mute
chatcontrol.bypass.punctuate
chatcontrol.bypass.rejoin
chatcontrol.bypass.rules
chatcontrol.bypass.rules.books
chatcontrol.bypass.rules.chat
chatcontrol.bypass.rules.commands
chatcontrol.bypass.rules.global
chatcontrol.bypass.rules.items
chatcontrol.bypass.rules.packets
chatcontrol.bypass.rules.signs
chatcontrol.bypass.signduplication
chatcontrol.bypass.spamkick
chatcontrol.bypass.tabcomplete
chatcontrol.bypass.time.chat
chatcontrol.bypass.time.commands

**Comment by kangarko** [comment]
Thank you, apology for the delay, will prioritize this

**Comment by kangarko** [comment]
Sorry I was not able to reproduce this: 

<img width="703" alt="Skjermbilde 2020-11-05 kl  13 47 55" src="https://user-images.githubusercontent.com/1918426/98242981-8f3d7d00-1f6d-11eb-8edc-c69e14918cb7.png">

Please test using the next latest version coming up tonight.

**Comment by kangarko** [comment]
Also can you send me the full permissions list for the sending and receiving players?

**Comment by kangarko** [comment]
alrighty boyz, got fixed finally!

**Comment by c0wg0d** [comment]
How did you get it fixed if you couldn't reproduce it?  I'll try out the latest version and report back when I get it installed and tested.

**Comment by kangarko** [comment]
I did end up reproducing at the end :) Some of these odd bugs are just odd so it won't always show up
