### ISSUE TITLE
Discord channel not binding to Minecraft channels

### ISSUE THREAD

**Issue by ShkaiSenpai** [kangarko/ChatControl-Pro#2082]
Hello, I am running minecraft version 1.16.3

I'm been trying to connect my discord channels to each of my minecraft channels.

I have this setting enabled. "Control_Incoming_Messages: true"
Discord on left / Minecraft on right

standard <----> standard
Minecraft sends to discord, discord doesn't send to minecraft

mod <----> mod
Minecraft mod sends to discord standard and mod, discord doesn't send to minecraft

admin <----> admin
Minecraft admin sends to discord standard and admin, discord doesn't send to minecraft

There are no errors in the console when using the channels from discord. When restarting the server, the console does say this: INFO [DiscordSRV] No chat plugin hooks enabled. 

I have my DiscordSRV setup with the 3 channels. Stand alone, it works fine with the standard or global, it won't work with more than one without a chat plugin. ChatControl-pro is a chat plugin with channels however does DiscordSRV not recognize it as one? 

What I also don't understand if why there is discord formatting in the formatting.yml and the channels.yml. The "Admin_Chat" channel the plugin came with is formatted in the formatting.yml however some settings are in the settings.yml which also include a discord channel. Can any of these be overlapping and be the cause why the discord channels aren't working properly?

Edit: When I change this to false: "Control_Incoming_Messages: true" I get the DiscordSRV format which I'm able to send messages from my discord to in-game however only works for entire Minecraft chat. Not what I want.

**Comment by astirling** [comment]
Without knowing what is in your channels.yml, I'm guessing you might not have two values set for your channels.  Channel configuration should look something like:
`  ingamechat:
    Format: Chat
    Bungee: true
    Console_Format: '[CHAT {player}] {message}'
    Discord: true
    Discord_Format: '&8[&3Discord&8] &7{player}: &f{message}'`

Without Discord and Discord_Format chat between Discord and ChatControl won't work as expected.

**Comment by kangarko** [comment]
Post your channels.yml file please

**Comment by ShkaiSenpai** [comment]
Ok, I've got the channels to post however my when I type a message into my mod channel, it sends them to my discord mod channel and public channel. I have DiscordSRV Minecraft channels set to their own discord channels.

Example what's happening.
Main chat ------> Discord Main
Mod chat -------> Mod discord and discord main.

I don't want my mod channel getting display in my main public channels on discord.

**Comment by c0wg0d** [comment]
> Without knowing what is in your channels.yml, I'm guessing you might not have two values set for your channels. Channel configuration should look something like:
> 
>   ingamechat:
>     Format: Chat
>     Bungee: true
>     Console_Format: '[CHAT {player}] {message}'
>     Discord: true
>     Discord_Format: '&8[&3Discord&8] &7{player}: &f{message}
> 
> Without Discord and Discord_Format, chat between Discord and ChatControl won't work as expected.

**When on earth was this added???**  Discord was working fine in 8.8.6, and it doesn't in 8.8.19 and I saw NOTHING about these settings in the changelogs.  It doesn't even mention it on this tutorial page: https://github.com/kangarko/chatcontrol-pro/wiki/Discord

THIS ALL USED TO BE AUTOMATIC.  Why are there Discord settings in 3 different places now?!  This is infuriating!

**Comment by kangarko** [comment]
I totally understand it's frustrating. We'll change how we setup Discord with CCP9. Until then, you can just have the "Discord" option on "true" for those channels you wish to be linked. The "Discord_Format" is not mandatory longer.

**Comment by kangarko** [comment]
Also, use the [discord] option to the Debug key in settings.yml to make the plugin tell you what's going on, it'll help you set it up right now.

**Comment by c0wg0d** [comment]
The Discord_Format is required with 8.9.0-BETA.  With the option omitted, I was getting the following debug message:

[discord] > Message from channel 'admin' not sent to Discord its format is empty or 'none'

After I added Discord_Format, it worked as expected.
