### ISSUE TITLE
Minecraft Version: 1.8.8 Chat color

### ISSUE THREAD

**Issue by BRIXER86** [kangarko/ChatControl-Pro#2083]
Hi, I apologize for my English but I do not speak it well, the plugin in some servers the chat color menu does not work correctly, I would like to know how to solve the problem.
I attach the video to demonstrate the problem

[Minecraft 2020.11.02 - 18.24.58.01.zip](https://github.com/kangarko/ChatControl-Pro/files/5476815/Minecraft.2020.11.02.-.18.24.58.01.zip)

**Comment by kangarko** [comment]
What CCP version are you using? Any console errors?

**Comment by BRIXER86** [comment]
I am using ccp version 8.8.20, no problems are reported in the console

**Comment by kangarko** [comment]
Sorry but some other plugin of yours is making this incompatible, test on a test server with just ChatControl Pro and it will work.
