### ISSUE TITLE
Minecraft Version Server: 1.8.8 (Chat color/Chat color menu)

### ISSUE THREAD

**Issue by BRIXER86** [kangarko/ChatControl-Pro#2084]
Hi, I apologize for my English but I do not speak it well, the plugin in some servers the chat color menu does not work correctly, I would like to know how to solve the problem.

[Minecraft 2020.11.02 - 18.24.58.01.zip](https://github.com/kangarko/ChatControl-Pro/files/5476820/Minecraft.2020.11.02.-.18.24.58.01.zip)

**Comment by kangarko** [comment]
Closing since you made another ticket similar to this
