### ISSUE TITLE
Minecraft Version: 1.16.3: I think the plugin is clashing with essentials chat, how do I fix this please?

### ISSUE THREAD

**Issue by UnknownPendragon** [kangarko/ChatControl-Pro#2085]
How do I make ChC not clash with essentialschat?

**Comment by Kbryst** [comment]
Chat control is a chat system with a ton of extra stuff, essentialschat is a chat system,

you need to pick one bud

**Comment by kangarko** [comment]
Pick one. Both are incompatible together.
