### ISSUE TITLE
Paper-252 1.16.3: Error loading configuration in data.db

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl-Pro#2088]
Installing ChatControl-8.8.20 fails on startup on Paper-252. I have tested versions of ChatControlPro down to ChatControl-8.8.18, and Paper versions Paper-252 and Paper-252, with the same results. 

Plugin is disabled on startup with the plugin-generated configs. https://pastebin.com/vG8sKRcR

**Comment by kangarko** [comment]
Remove data.db. Probably changing versions have updated it incorrectly.

**Comment by BakiDance** [comment]
Hello, I just tried this and received the same error. This is a fresh installation of ChatControlPro, so all configs and files were generated by the plugin on startup. Currently, I'm using ChatControl-8.8.20 on Paper-252 (MC: 1.16.3) (API version 1.16.3-R0.1-SNAPSHOT).

If it helps, here is a .zip containing the contents of the /plugins/ChatControl/ folder, and includes the error.log. (plugin .jar not included.) 
[ChatControlConfigs-8.8.20.zip](https://github.com/kangarko/ChatControl-Pro/files/5489825/ChatControlConfigs-8.8.20.zip)

**Comment by BakiDance** [comment]
I was able to find a "fix". The only way I was able to get ChatControl to enable was to completely empty out my plugins folder so that ChatControlPro-8.8.20.jar was the _only_ thing in the directory (including folders) and restart. The plugin successfully generated its config folder and enabled properly. Next, I stopped the server, and re-added all my previous plugin jars and folders, keeping the new, working, ChatControl folder in place. 

Having done this, ChatControl is working now. However, if I move the "working" ChatControl folder to my desktop and allow the plugin to generate a fresh folder and configs _while my other plugins are loaded_ ChatControl fails with the "Error loading configuration in data.db!" error. This is with the same .jar loaded on the same server.

I essentially now have a working ChatControl folder and one that causes the plugin to disable, despite the fact that both folders were generated by the plugin on server-launch; the only environmental difference is the number of plugins in the plugins folder on first launch (server and plugin jars remained the same).

Here's a new zip containing the "working" folder and the one that causes the plugin to error. Again, neither were modified by me.
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5490010/ChatControl.zip)

**Comment by BakiDance** [comment]
I went ahead and compared the files within both directories, and as expected there's a difference between the two data.db copies. The "working" copy's data.db has a section that the broken one lacks.

Simply adding:
`Updates:
  Lowercase: true
  Essentials_Ignore_Import: true`
to the data.db on the broken install fixes it, although I'm unsure why these lines are missing when ChatControl is loaded alongside my other plugins.

**Comment by kangarko** [comment]
I am sorry, next version should have this odd glitch solved. Comment below if you experience otherwise. Also it may be that another plugin of yours is interfering with our files. You can drop plugins one by one to find which.
