### ISSUE TITLE
1.16.4 UI Ignore system.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl-Pro#2089]
Ahoy

With 1.16.4 adding a built in client ignore system, could chat control Pro listen out to this and use this for 1.16.4 client's.

**Comment by kangarko** [comment]
Thanks, will see what I can do but my top priority is making the plugin stable (aka not crash) and then releasing ChatControl 9 with the same stability level. Would rather have less feature rich plugin that doesn't crash/lag servers than feature-packet shit.

**Comment by TomLewis** [comment]
Thanks. I have player use 1.16.4 an they are asking me "Why does the ignore feature not work".
They expect it to work.
