### ISSUE TITLE
Cross channel messages.

### ISSUE THREAD

**Issue by DrBaja** [kangarko/ChatControl-Pro#209]
Hey, I would like to know if I can make chat channels that can listen to each other. Basically, I want to have three channels:
Global
Server
Local

Global: This is global to all bungee servers. This channel can see the Server Channel but not local unless in a 612 block range.
Server: This is global to only the server on the bungee server, It can always view the server channel and not local unless in a 612 block range.
Local: This is local to 612 block radius and can always view Server and Global channels.

Help would be appreciated.

**Comment by kangarko** [comment]
Hey,

at present, channels are completely independent. You may spy on a channel via /ch spy or send messages globally via /chc g or by prepending your message with !, but messages in channels only stay in the channel where they were originated.
