### ISSUE TITLE
Error when using command

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#2090]
Minecraft: 1.16.3
Paper: 253
CCP: 8.8.20
CoreArena: 2.8.2

https://pastebin.com/SyGVyGiW

so i'm not 100% sure if this error originates with CCP or CoreArena, but i assume it's CCP.

this error occurs when i use the command "/ca new".
it does not occur when i give a name like "/ca new Test".

**Comment by kangarko** [comment]
Thanks, will be fixed in the next version.
