### ISSUE TITLE
Discord messages are duplicated

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl-Pro#2096]
I just updated to 8.9.0-BETA and BungeeControl 2.4.0.

The Discord messages are finally working again (sort of) when I add Discord: true and a Discord_Format to the channels.yml file.

However, now there's 2 new problems.

To make things easy to explain, let's talk about having 2 servers, server1 and server2, one chat channel for each, both BungeeCord enabled.

Problem 1: Discord messages are duplicated.

If I add Discord: true and a Discord_Format to server1 and server2 in channels.yml, now every time someone chats in a server, Discord gets 2 of the same message.

If I remove those options, the chat will correctly be sent once per message to Discord, but if I send a message to the server2 chat channel from server1, it won't be sent to Discord.

Problem 2: It seems to be a requirement to specify ALL Discord channels in ALL DiscordSRV configs across all servers now.  This wasn't the case before.

Before, in my DiscordSRV config for server1, I only specified server1 and admin chat channels.  In server2, I only specified server2 and admin chat channels.  Even though I only set those 2 channels in the config, if I sent a message via BungeeCord to server2 from server1, it would still go to Discord in server2's Discord channel.  Now it doesn't unless I also add server2's channel ID to the DiscordSRV config.  This isn't too big of a deal, but I don't understand why it was changed, and I don't want to change my configs until the duplication issue is resolved.

**Comment by kangarko** [comment]
Thanks, I'll have a look asap within 24-48h

**Comment by kangarko** [comment]
https://www.loom.com/share/51650099d2f44cc496c0397377130790?from_recorder=1
