### ISSUE TITLE
1.16.3 Timings

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#2098]
While player join/quit events seem to be much lower, another (new?) task is introduced that is rather heavy.

![image](https://user-images.githubusercontent.com/5664135/98373164-232b4980-203f-11eb-93fa-84eb969c6c9b.png)

https://timings.aikar.co/?id=91e826ea62314a1d83d771d752d544d5#plugins

What is this new task exactly?

**Comment by Sikatsu** [comment]
![image](https://user-images.githubusercontent.com/5664135/98400564-84194880-2064-11eb-8e49-584edfde2407.png)

**Comment by kangarko** [comment]
Loading and managing what was previously done in these events. Won't be fixe until CCP9 is out, not possible with our current system. But it no longer hangs the join event.
