### ISSUE TITLE
1.16.4 | Players with /chc adminchat access are put into the channel on login with no way to prevent

### ISSUE THREAD

**Issue by Penvmbra** [kangarko/ChatControl-Pro#2099]
Myself and two of my admins are forced into /chc adminchat on login after the server reboots every time, without fail. The latest update indicates that this feature (adminchat) is deprecated, and this behavior is not something I ever wanted to begin with. Removing permissions from player changes nothing. Deleting entries from the player in the database file does nothing. Please advise on either a solution or a fix for this.

**Comment by kangarko** [comment]
Thanks, next version you'll be able to disable admin chat completely.
