### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by ZoefyC** [kangarko/ChatControl-Pro#21]
Hi,
I tried to configure the chat.txt, but everytime a change something, ChatControl stops working.
Please help, I have no idea what I'm doing wrong. :(

chat.txt -> http://pastebin.com/5y7ESsPL
error log -> http://pastebin.com/01myqYrM

**Comment by EvilOlaf** [comment]
Seems like a codepage issue.
Get yourself Notepad++ and try converting the file to UTF-8.
If this does not work out try converting to ANSI.

**Comment by ZoefyC** [comment]
Thank you! I tried both, but I still get the same error message.

**Comment by EvilOlaf** [comment]
That's odd. Looks pretty much like an existing error which has been fixed this way: https://github.com/kangarko/ChatControl/issues/73

**Comment by kangarko** [comment]
This is clearly an encoding-related issue.

Different systems accept only ANSI or only (UTF-8 without BOM) encodings. Always ensure the server is stopped while changing the encoding and saving the file.
