### ISSUE TITLE
1.16.4: How do Channels actually work....

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Pro#2100]
Hello,

Trying to setup ChatControl channels as I never have before... I would like the below:
- Global chat channel that players automatically are able to read and write and not leave. (Cross server)
- Standard chat channel that is for the specific mode they are on, able to read and write and not leave.
- Staff chat channel for Helpers+ to be able to read, write, and not leave. (Cross server)

- Town and Nation chat for towny (not sure how these work), able to read and write for those specific towns, and not leave those chats.

All these would need to be able to be logged into DiscordSRV for discord logs.

I attempted to set these up before but then people could leave channels and such... not very sure how these get setup fully. Help would be appreciated :)

**Comment by kangarko** [comment]
Can you show me your channels.yml what you have now? I'll guide you through it

**Comment by Skizzles** [comment]
Okay i got channels setup.... but no matter what I try to do they can not talk in these channels xD it keeps wanting so many perm nodes....

**Comment by kangarko** [comment]
Follow the error message and give players these nodes
