### ISSUE TITLE
Minecraft Version: 1.16.3

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl-Pro#2103]
I don't know why I have to ask this, it never happened to me, I mean, this is the first time that a dev wants to re-upload his plugin to get more money and I'm sorry if I'm direct but I think we're all grown up to play dumb and not know what we're talking about ok .

Among other things, I wanted to know if I, since I completed the plugin about 30 days ago or so this year, I will have permissions to the new version 9 of chatcontrolpro.

In something else I hope I will never go through this again I wish anyone and I will give my personal opinion on that maybe you don't even care  Kanguroo

I think it is bad for those who supported you since ChatControl was released until now as I do, I mean, it is unfair that not everyone has the version of chatconrolpro V9.

I am Spanish and my English is not very good.

**Comment by kangarko** [comment]
It either that or I'll have to abandon the plugin. You can stay using ChatControl 8 as it will continue receiving updates for some time after 9 to keep it stable.
