### ISSUE TITLE
Turning Off Auto Spy

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/ChatControl-Pro#2107]
since v8.8.1.8 the auto spy continues to turn on after a restart. How do I turn off the auto spy?

I've tried both 
     -chatcontrol.channel.default.autospy
     -chatcontrol.chat.spy
Neither work

**Comment by kangarko** [comment]
use -chatcontrol.spy.autoenable

**Comment by BobbyMere** [comment]
-chatcontrol.spy.autoenable doesn't work
