### ISSUE TITLE
1.16.4 - Settings.yml server_name stopped working

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl-Pro#2109]
In ``settings.yml`` an option ``Server_Name: '&7[&2S&7]&r'`` was used. I used this placeholder as a chat prefix for my servers using ``{server_name+}``. However it seems that placeholder is now reading server-name from server.properties? So i've had to hard code the option. Is this intentional.

Also. Please re-open discord chats. Let your community support people or just ask simple questions rather than raising issues.

**Comment by kangarko** [comment]
We had to change it due to other unrelated problems. You can just create a javascript variable such as {server_title} and return what you need there instead.

Thanks for your feedback regarding Discord.
