### ISSUE TITLE
ChatControl v9 Quick Request

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/ChatControl-Pro#2112]
Hey, I would love to see the option for chat control to display the users head skin avatar in the chat (for only them) when joining the server like this plugin does:
https://www.spigotmc.org/resources/joinavatar-display-your-head-on-join-config.42640/

Picture Example:
<blockquote class="imgur-embed-pub" lang="en" data-id="a/a7j34we"  ><a href="//imgur.com/a/a7j34we">ChatControlPro v9 Feature Request</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

And if possible make it customizable for `"First Join avatar message"` and "`Normal join avatar message"`
Thanks!

**Comment by kangarko** [comment]
Thanks, but we're already closed our feature phase, feel free to resuggest this in a few months.
