### ISSUE TITLE
Chat settings.

### ISSUE THREAD

**Issue by WIDELEC-X** [kangarko/ChatControl-Pro#2113]
Hello, here I have good idea:

1) How it would benefit others: give bigger functionality.

2) What would happen if we won't implement this feature: limited functions.

3) Can the old system be modified/improved instead?

4) Idea: add aliases commands for chats settings or delete whole shortcut from messages in chat.

Now there is limit for shortcut if u don't want use standard letters like A, B, C but use #, @, e.g.
U can use shortcut for example '@342' but message will show as: 342{message}.
If u cen set it up to delete whole shortcut from settings.

Second solution is to add function aliases for chat settings to use commands to write in chat.
Then u can simply use for example command: /f or /f8.

Thanks in advance! Can't wait for respond. Best regards, WIDELEC.

**Comment by kangarko** [comment]
Thank you for your suggestion!
