### ISSUE TITLE
MCMMO CLASSIC QUESTION

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#2116]
You keep posting patch notes without enough information, and we need more clarity on your content.

So can you please explain what will happen to mcmmo classic support for servers on 1.12.2. We have to keep updating to keep bungee stuff so what will happen to us?

"Improve | Updated to support mcMMO 2.1.153. Unfortunately, due to breaking changes we cannot support mcMMO Classic."

What breaking changes, can you provide more information so we can get a head start if there is an issue?

**Comment by kangarko** [comment]
I apology for not clarifying this enough, as of right now I don't have the capacity to support both mcMMO classic and reworked. That means only the reworked is supported. Which means it will break if you update. We may look into this in the future when we have time.

**Comment by Kbryst** [comment]
You dropped support for something that doesn't even get updated too often.
What happens if you decide to make us update bungee shit?

**Comment by kangarko** [comment]
Foundation is open source, anyone can contribute to the HookManager class and make biversion compatibility

**Comment by Kbryst** [comment]
I'm not a developer, thats why I paid you for a plugin.

I gave you $500 and learned nothing.

**Comment by kangarko** [comment]
a) Where did you give me $500?
b) We pushed an update to add this today

**Comment by Kbryst** [comment]
Thanks for adding it back.
