### ISSUE TITLE
1.16.4: Suggestion to add Custom chatcolors

### ISSUE THREAD

**Issue by JessePesse123** [kangarko/ChatControl-Pro#2117]
I think it would be nice if we could create custom chatcolors with hex codes. So for example a config chatcolor.yml where you could add chatcolors, name them and give them an icon.   

Or is this already possible?

**Comment by kangarko** [comment]
Thank you for your suggestion! We will add this to ChatControl Red when it comes out. You can join our testing at mineacademy.org/chatcontrol today
