### ISSUE TITLE
1.16.3 One server refuses to broadcast swears CHC 8.9.1

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#2118]
I noticed that one of the game modes refused to broadcast swears to staff.
Instead an error appears.
When the server should have notified staff, this error appeared: https://pastebin.com/raw/LdENQ8bR
Error.log: https://pastebin.com/raw/m8BJJ9ar

**Comment by kangarko** [comment]
This is an odd Java bug, you can try updating to 1.16.4 and updating your Java distribution if possible. I will silence this in the next version.
