### ISSUE TITLE
Case insensitive Performance question

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#2119]
Version update 8.9.0 beta reported:

> Added "Regex_Case_Insensitive" key to settings.yml to increase rules performance by disabling case insensitive matching, if your rules are already coded that way.

Do I understand it correctly that making every single rule case insensitive is better for performance than enabling `Regex_Case_Insensitive` via settings?

**Comment by kangarko** [comment]
No, it's the opposite. Don't make your rules case insensitive, and use Regex_Case_Insensitive flag (have this on true).
