### ISSUE TITLE
Channel permission not working?

### ISSUE THREAD

**Issue by Porama6400** [kangarko/ChatControl-Pro#212]
How this thing work?

``
Permission` required to see the messages inside the channel.
Permission: 'chatcontrol.channels.example-permission'
``

I already set a channel permission and give the permissions to my players but It seem to not working
What did i do wrong?

I also tried autospy permission but it's not working too, why?

**Comment by kangarko** [comment]
It allows players to receive messages within the channel.

What exactly it's not working?

**Comment by Porama6400** [comment]
Player don't receive the message

**Comment by Porama6400** [comment]
So is this a bug or I'm just not config it properly?

**Comment by kangarko** [comment]
Hey, 

I am sorry for the delay. I just tested and I unfortunately can't reproduce it. Which other plugins do you have that may affect chatcontrol? DeluxeChat / TownyChat / FactionsChat / etc... ? Also, please post me the relevant permissions from your permission plugin (e.g. PermissionsEx). Thank you.

Note that if you have an operator status, you may get assigned all channels to autospy.

**Comment by Porama6400** [comment]
I use PEX (MySQL for data storage)
I guess there are no other chat affected plugin

**Comment by Porama6400** [comment]
When I want everyone to spy on channel called "global" I have to add 2 permissions?

'chatcontrol.channel.global
chatcontrol.channel.global.autojoin'

Is that correct?

**Comment by Porama6400** [comment]
I think I solved it

I remove this permission and everything seem to work fine
> chatcontrol.channel.default.autojoin

(Channel "default" is not exist)
Is that why autospy broken?

**Comment by kangarko** [comment]
You can either give chatcontrol.channel.<name>.autospy or chatcontrol.channel.<name>.autojoin, not both. If you are using MySQL and a player makes changes in their channel configuration, this is saved and prioritized over the autojoin/autospy permissions, that's why they may seem "not working"

**Comment by Porama6400** [comment]
No, I'm sorry, it's not autojoin it's autospy
I wrote wrong example

**Comment by Porama6400** [comment]
I mean I gave these permissions to player

```
chatcontrol.channel.default.autospy
chatcontrol.channel.global
chatcontrol.channel.global.autospy
```

and it's not working
and after I remove `chatcontrol.channel.default.autospy`
It seem to work fine

**Comment by kangarko** [comment]
Yes it may be that the channel does not exist, only give permissions to existing channels.
