### ISSUE TITLE
ChatControl error

### ISSUE THREAD

**Issue by W4RSID** [kangarko/ChatControl-Pro#2122]
Hi, I have this error in chat control pro. Can you fix it please?
https://pastebin.com/T93fFQeQ

**Comment by kangarko** [comment]
Are you using any modified spigot version? How to reproduce this bug?

**Comment by W4RSID** [comment]
Yes, I am using a jar for my factions server. I have not noticed when this error appears, it appears randomly on the console and is quite common. For example when I open chests it appears sometimes.

**Comment by kangarko** [comment]
Thanks, will solve to the next release
