### ISSUE TITLE
ChatControl settings.yml error

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#2123]
I changed something in formatting.yml, I reloaded the plugin using /chc reload and it gives me an error about settings.yml and breaks the complete plugin.

https://pastebin.com/BvvdSmEs

**Comment by kangarko** [comment]
ChatControl was not installed correctly, something manipulated the jar such as plugman, or reloading and changing the jar. Reinstall.

**Comment by Sikatsu** [comment]
No plugman was used, I performed one server restart and it never happened again though..

**Comment by kangarko** [comment]
Let me know if that happens on the next release, and it if does, please ZIP me your whole folder so I can reproduce
