### ISSUE TITLE
1.16.4: Capital placeholders no longer working

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#2124]
I updated to I think 8.9.0-BETA and ever since one placeholder no longer works, I feel because of it containing capitals.

{VotingPlugin_alltimetotal}

When I parse using /papi parse me %VotingPlugin_alltimetotal% it works completely fine.

![image](https://user-images.githubusercontent.com/5664135/98967485-d1863180-250c-11eb-8cee-fc1452a66d12.png)

Edit: Confirmed this, making the V and P lower case makes the placeholder work again.

**Comment by kangarko** [comment]
Thanks, yeah just use lowercase placeholders then
