### ISSUE TITLE
1.16.4: Formatting only private messages?

### ISSUE THREAD

**Issue by Mjeeeks** [kangarko/ChatControl-Pro#2125]
Hi!
Is it possible to use formatting.yml just for select things and not the whole chat?
I want to only format the Private_message_sender and Private_Message_Receiver, but when i enable the formatting, it formats everything, including the chat. I want my chat to be handled by a different plugin. Deleting those sections doesn't seem to help either.

**Comment by kangarko** [comment]
Yes, you can disable formatting and enable Private_Messages and we'll still use formats from that file.
