### ISSUE TITLE
MC 1.16.3, tab completion.

### ISSUE THREAD

**Issue by WIDELEC-X** [kangarko/ChatControl-Pro#2127]
Hello there.

Looks like there is issue with tab completion tool for permissions.
In spigot.yml I have this function enabled. Then I see suggested commands.
But when I enable tab completion function from plugin then it's off completely.
Even for main admin with all of permissions '*'.
In the end I can disable function for all of players or for nobody.

Thanks in advance for respond! Best regards, WIDELEC.

**Comment by kangarko** [comment]
This is broken on ChatControl 8, however we already got it working for ChatControl 10 that's coming very soon.
