### ISSUE TITLE
1.16.4: /chatcolor persistence bug

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#2129]
/chatcolor seems to be inconsistent when restarting. E.g. if i set my colour to blue and restart the server upon restarting i lose my colour. Some people have colours already and when they click "reset" after a restart it goes back to the previous colour.

paper 1.16.4 build 275
chc 8.9.2 (though it has been happening for a while)

**Comment by JessePesse123** [comment]
We're having the same issue

**Comment by JessePesse123** [comment]
With staffchat also

**Comment by kangarko** [comment]
Thanks. Our system in 8 is pretty inconsistent saving these, but we already got it working to ChatControl 10 which is coming very soon and can be tested at mineacademy.org/chatcontrol
