### ISSUE TITLE
Packets not responding

### ISSUE THREAD

**Issue by Johandrex** [kangarko/ChatControl-Pro#213]
The packets.txt rules isn't working anymore, using the recent ChatControl version and spigot 1.11 + 1.8.8. The console says the packet rules have been loaded, but they're not working anymore. They worked perfectly fine around 2 weeks ago and haven't made any changes whatsoever to them. 

Packets.txt: https://pastebucket.com/562287
ChatControl version: 7.3.6
ProtocolLib: 4.2.1

**Comment by kangarko** [comment]
Everything works just fine for me. That's weird. Please test on 7.3.8.

![pic](https://i.imgur.com/bjcaPIC.png)

I also noticed you are using packets to translate some messages that can easily be translated via localization. Please read the Localization section in documentation on how to do that.

**Comment by Johandrex** [comment]
Thanks, using the new version and most regexes seems to work when removing the "^". But these two regexes doesn't seem to work for some reason. https://gyazo.com/c2d5097e0b3a7f74ac081ea233fca460



`match The menu "keys.yml" was not found.
then rewrite &cThis server doesn't sell ultra crate keys

match You are no longer ignoring set swear.
then rewrite &aEnabled swearing! &7You can now see messages with swear words

match You are now ignoring set swear.
then rewrite &cDisabled swearing! &7You can no longer see messages with swear words`

**Comment by kangarko** [comment]
Hey,

the first, one, I am not sure why this is not caught. Please test against some regex test services such as regexpal.com, or try to omit " with a backslash: \"

Regarding the last two, please configure the message via localization in this plugin. See the Wiki for tutorial on how to do it.
