### ISSUE TITLE
1.16.3 How does Bungee / Discord work now?

### ISSUE THREAD

**Issue by rumplepusscat** [kangarko/ChatControl-Pro#2132]
Apologies if this has been asked before/covered elsewhere, but I really can't understand how Bungee (& Admin) chat works now/with Discord, now that it's been moved over to channels. Some of the wiki seems to be outdated/conflicting too which is confusing, though I of course appreciate your efforts are now looking towards CHC v9!

Essentially, I would like to enable a main chat for everyone on Bungee/all servers, that is also directed to a Discord channel for two-way communication.

On top of this, I would like to have a separate admin channel that staff can view and can send messages to with either a command (e.g.` /a [text]` - though I know how to set this up) or to toggle writing with something like `/a switch`. If possible, this would be ideally linked with Discord too, but this is less of a priority.

Is there also a way to disable the message on join saying "you're in X channel(s)"?

I appreciate your support! Many thanks,

Rumple

**Comment by kangarko** [comment]
Where did you find the Wiki conflicting? I just checked it and you should be able to get things going with the formatting.yml file being used as one global chat.

You can then use Admin_Channel feature to have admin channel connected to Discord too, which is shown in that article. You can enable this debug option to see in the console how the plugin was connected: https://github.com/kangarko/ChatControl-Pro/wiki/Discord#important-before-continuing-set-debug-key-in-settingsyml-to-discord-and-restart-this-will-save-you-hours-and-print-out-what-is-happening-to-the-console-after-you-are-finished-with-your-setup-you-can-remove-the-value

Let me know if you have any questions below!
