### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by pedaldev** [kangarko/ChatControl-Pro#2133]
**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
Velocity is a growing in popularity as an alternative to BungeeCord, it would allow people to take advantage of the performance improvements Velocity offers while still being able to utilize the power of ChatControl. 

**2) What would happen if we won't implement this feature? How's your server being affected?**
We'll definitely switch to a different plugin, as cross-server chat is syncing is required due to our setup.

**Comment by kangarko** [comment]
Thanks, it's planned 👍
