### ISSUE TITLE
1.16.3: ChatControl Anti-Bot Protection?

### ISSUE THREAD

**Issue by NovaPixell** [kangarko/ChatControl-Pro#2134]
Hi guys, a day ago I was going to host more than 200 players on my server, but at some point many players got kicked with this message "Bot Protection:

Please wait 2 seconds before logging in again. "

is it caused by the ChatControl plugin?

**Comment by kangarko** [comment]
Yes, however I am unsure why did these players got kicked. We only show this message when they tried to join again, not when they are kicked.

**Comment by kangarko** [comment]
Yes
