### ISSUE TITLE
1.16.3/4: No announcements when a new player joins

### ISSUE THREAD

**Issue by TNTUP** [kangarko/ChatControl-Pro#2135]
Using BungeeControl v2.4.0 with ChatControl v8.8.20 doesn't announce when a new unique player joins on the server.

Note: I'm not using the latest of ChatControl as it has issues or improper plugin testing as I always downgrade when I notice something. Not Chatcontrol's issue but rather BungeeControl. Again, planning to downgrade

**Comment by kangarko** [comment]
This is working fine on latest BungeeControl and ChatControl

Ensure to set First_Join_Message to true in settings.yml of BungeeControl
<img width="483" alt="Screenshot 2020-11-16 at 17 44 36" src="https://user-images.githubusercontent.com/1918426/99281974-694c8e00-2833-11eb-895d-54b6ba1fce7a.png">

**Comment by TNTUP** [comment]
Weird, the setting is always at true, noticed it when upgrading BungeeControl
