### ISSUE TITLE
BungeeCord: Error when 1 server doesn't have ChatControl installed

### ISSUE THREAD

**Issue by Pab64x** [kangarko/ChatControl-Pro#2138]
https://pastebin.com/Cz3pQg8J

4 servers: one bungecoord and 3 paper where one doesnt have chatcontrolplus. This error always drop when someone message smth on server. Also its not working

**Comment by kangarko** [comment]
Thanks, I will investigate. Are you using redis btw?

**Comment by Pab64x** [comment]
Fixed
