### ISSUE TITLE
1.16.4: Bentobox Placeholderapi don't work in chat anymore

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl-Pro#2144]
I just noticed after i upgraded chatcontrol, placeholder and minecraft from 1.16.3 to 1.16.4, papi placeholders don't work anymore..

**Comment by kangarko** [comment]
No console errors?

**Comment by Malachiel87** [comment]
nope

**Comment by Malachiel87** [comment]
it was working fine in 1.16.3, chatcontrol version 8.8.20

**Comment by kangarko** [comment]
Sorry, this appears to be a problem outside of ChatControl. I updated everything including bentobox etc. and the latest version works. 

However I made a few changes to ChatControl earlier so I will push the version I have on my disk later today.

<img width="770" alt="Screenshot 2020-11-20 at 09 08 01" src="https://user-images.githubusercontent.com/1918426/99775656-ee73c380-2b0f-11eb-8ba2-06e48e72115d.png">

**Comment by Malachiel87** [comment]
try to use this in chat format:  %Level_acidisland_island_level%
--

**Comment by kangarko** [comment]
Use lower case %level_acidisland_island_level%

**Comment by Malachiel87** [comment]
I confirm using lowercase placeholder it work again :)
