### ISSUE TITLE
Paper-253 1.16.3: PlayerRegisterChannelEvent Console Spam

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl-Pro#2145]
Since updating to ChatControlPro 8.9.4 since (now fixed) issue #2137, the console is spammed with `PlayerRegisterChannelEvent` messages when a player joins the server. https://pastebin.com/aBMKz19S

Configs are the same as what was supplied in the previous issue.

**Comment by kangarko** [comment]
Sorry but this is not coming from us, we dont even have such event
