### ISSUE TITLE
1.16.4: Adding actions to broadcasts

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#2146]
Hey, a plugin called "AutoMessage" has a feature where it's automatic messages can receive click and hover action effects.

Can the same be done with ChatControl's Broadcaster feature? If not, could it be implemented?

**Comment by kangarko** [comment]
Yes, we will have this in ChatControl Red: https://github.com/kangarko/ChatControl-Red
