### ISSUE TITLE
1.16.4: /msg giving away vanished users

### ISSUE THREAD

**Issue by JohnS19** [kangarko/ChatControl-Pro#2147]
ChatControl version 8.9.5

Issue:
If mod1 is vanished and player1 attempts to find out, player1 can simply do '**/msg mo**' and the error message they will receive is: '! **mod1** is not online' instead of '! **mo** is not online'

ChatControl is autocompleting the /msg parameter into a full username when the mod is online but vanished. If the mod was actually offline, it would not autocomplete into a full username.

**Comment by kangarko** [comment]
Thanks, that will be fixed in https://github.com/kangarko/ChatControl-Red
