### ISSUE TITLE
Channel admin/global removed

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl-Pro#2148]
Hi, i read on future version of chatcontrol these default channel on setting will be removed, and we will be forced to  enable channels (thing that i don't want, they look messy and confusing i think...

**Comment by kangarko** [comment]
Thanks for your feedback, but actually having 1 system is infinitely easier to maintain than four systems we have right now. You will be able to get 100% same setup.

**Comment by Malachiel87** [comment]
but you are forcing the users to use channel too...
