### ISSUE TITLE
(Updated) Unknown files in main server directory.

### ISSUE THREAD

**Issue by KasearMC** [kangarko/ChatControl-Pro#2149]
EDITED:

after getting some more info it seems like these files are most likely generated by CCP.
https://i.postimg.cc/k5wNvhfy/2.jpg
https://i.postimg.cc/hGKbxqbj/1.jpg

if so, what causes these files to generate and why? they can eventually clutter the directory a lot and take up a lot of disk space. is it fine for them to be deleted?

**Comment by kangarko** [comment]
No sorry we do not generate such files, at all.

**Comment by kangarko** [comment]
Never seem them appearing since 2013, I am afraid I can't help
