### ISSUE TITLE
Ability to hide chat or ignore all players

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl-Pro#2150]
Sometimes there are players who want to mute the ENTIRE chat for themselves except for personal messages. It would be nice to implement such a command for them.

#### 1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)

It will benefit any server with people who sometimes want to play with their fiends without seeing messages from other players.

#### 2) What would happen if we won't implement this feature? How's your server being affected?

Nothing bad will happen, but I think it is not that hard to implement the command or extend the existing `/ignore` command.

#### 3) If suggesting something new - Can the old system be modified/improved instead?

Old command `/ignore` can be extended to support `/ignore all` syntaxis and `/ignore ?` will show `Ignoring: ALL`

**Comment by kangarko** [comment]
Thank you, will add to ChatControl Red https://github.com/kangarko/ChatControl-Red
