### ISSUE TITLE
1.15.2: JavaScript Possibility

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl-Pro#2151]
I was wondering if it is possible within the javascript.txt to make it when a player does /ch join [channelname] and a message after it will do the /ch send [channelname] (message) to that channel?

To summarise it a bit easier. I would like to make an extension to /ch join 
to allow players to send a message after the channel name 

so /ch join standard (message) - and it sends whatever the player types after the channel name to the specified channel without hafting to do /ch send [channelname] (message)

hope this summarises everything and I hope this will be achievable with some help! <3

**Comment by kangarko** [comment]
Sorry I am afraid that's not possible right now :/

**Comment by Ash10744** [comment]
Not any other way it could potentially be done ?

**Comment by kangarko** [comment]
Yes, if you have a developer then you can use our API and listen for that event or command and do your thing.
