### ISSUE TITLE
1.16.3 Paper: Death Messages not sending into Discord Channel

### ISSUE THREAD

**Issue by JHiroshige** [kangarko/ChatControl-Pro#2152]
So I have enabled this here 
![image](https://user-images.githubusercontent.com/67478052/100131492-65002080-2e84-11eb-9a70-faf2e274c62d.png)

Thats the DC Chat
![image](https://user-images.githubusercontent.com/67478052/100131899-efe11b00-2e84-11eb-925b-9f67e1691af2.png)

And thats the error code
![image](https://user-images.githubusercontent.com/67478052/100131939-01c2be00-2e85-11eb-8b44-9924cc50d2fa.png)

Please help me fix this!

**Comment by kangarko** [comment]
You need to put your mc-server-chat to DiscordSRV/config.yml file, seems you only have "global" there. Check out our Wiki on linking channels
