### ISSUE TITLE
1.8.8: Cannot get channels to work.

### ISSUE THREAD

**Issue by iwentafk** [kangarko/ChatControl-Pro#2153]
I'm having issues getting channels to work, my players are getting the message "You have no channel to write into. Type /ch for help.

I have allocated the following perms to them:

**chatcontrol.channel.autojoin.global.write
chatcontrol.channel.global.join.write**

However, they still get the error, my configs are default since I'm testing the channel feature. But I cannot seem to get it to work.

I'm using ChatControl Pro Version: **8.9.4**

Thanks!

**Comment by kangarko** [comment]
Can they join global with "/channel join global"? If not then give them the perms required to join that channel - they should see what these are in their perms message

**Comment by iwentafk** [comment]
I can try, but I want them to be able to auto join so they're not having to type that every time a new person joins.

**Comment by iwentafk** [comment]
Alright, so I've gotten it to automatically place users in the channel. But I'm trying to link with DiscordSRV, however, when I send a message in the channel on the server, it sends it to Discord, but sending a message to Discord does not send anything to Minecraft, instead gives me this error:

**> [15:37:25 INFO]: [discord] > Message not being sent to admin chat (configuration requires admin chat name: admin)
> [15:37:25 INFO]: [Discord->ChatControl] Ignoring Discord message from channel 'factions-feed'. Available ChatControl channels: [admin, discord, global, ranged, standard]**

To better understand, I'm starting up a network, with multiple servers, each server will have their own feed in the Discord, to keep everything seperate, I'm naming my feeds these names, however, I just want the #factions-feed Discord channel to send messages into the "discord" chat channel on the Minecraft server. However, as you can see, it isn't. Just completely negates the message altogether.

**Comment by iwentafk** [comment]
Actually, I figured it out. Was fully reading the Discord info, they have to be the same names.

**Comment by kangarko** [comment]
If you are using Admin_Chat, then you need to ensure your Discord channel is named exactly "admin". 

We will solve this limitation in ChatControl Red: https://github.com/kangarko/ChatControl-Red

**Comment by TomLewis** [comment]
@iwentafk how did you do this? I too have followed the Wiki setup guide and it does not explain how to make it actually work past the 2 initial permissions that you stated in the first ticket.

**Comment by kangarko** [comment]
@TomLewis what is it you're looking for, specifically? Happy to help, I just need to know more, probably see your debug file which we now provide with one click, /chc debug, and probably your permissions too
