### ISSUE TITLE
Your Suggestion Title

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl-Pro#2154]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Well, if some use lands they could have a modified channel to spy on the lands chat, nation or to make the lands easier to configure the entire lands chat system in / lands chat.

2) What would happen if we won't implement this feature? How's your server being affected?

affected I do not think that this alone that it will look normal and a little ugly the truth.

3) If suggesting something new - Can the old system be modified/improved instead?

the simple chat lands system may be vastly improved.

**Comment by kangarko** [comment]
Thanks, we will get this working for https://github.com/kangarko/ChatControl-Red
