### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl-Pro#2155]
26.11 01:18:53 [Server] INFO ______________________________________________________________
26.11 01:18:53 [Server] INFO Reloading plugin ChatControl v8.9.5
26.11 01:18:53 [Server] INFO [PlaceholderAPI] Successfully registered expansion: chatcontrol
26.11 01:18:53 [Server] INFO Warning: Admin_Chat feature is deprecated. You can create an admin channel in channels.yml. If using Discord, you can put 'Discord: true' key there to connect it with Discord channel by the same name.
26.11 01:18:53 [Server] INFO Hooked into: DiscordSRV
26.11 01:18:53 [Server] INFO Hooked into: ProtocolLib
26.11 01:18:53 [Server] INFO Warning: Detected both channels.yml and formatting.yml enabled - only channels will function. You can still create and use formats from your formatting.yml file.
26.11 01:18:53 [Server] INFO [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.fo.model.DiscordListener$DiscordListenerImpl unsubscribed
26.11 01:18:53 [Server] INFO [DiscordSRV] API listener org.mineacademy.chatcontrol.lib.fo.model.DiscordListener$DiscordListenerImpl subscribed (1 methods)
26.11 01:18:53 [Server] INFO ______________________________________________________________

wtf  minecraft server spigot paper 1.16.3 ggg

**Comment by kangarko** [comment]
There is nothing wrong with your console logs.
