### ISSUE TITLE
1.16.4 How to exclude standard and ranged chat from discordsrv?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl-Pro#2156]
So basically I just want global chat to communicate with discord srv, I had to disable control_incoming_messages in channels.yml because they just weren't sending at all, kept getting a console message reminding me of existing channels. I checked the wiki but it only seems to describe how to integrate admin chat with no real way of replicating the process for global

_May I suggest a config option like:
"Channels:
   standard:
      Discord: true/false"_

**Comment by kangarko** [comment]
You can write the Discord key anywhere for any channel, so just write it under standard and ranged:

```yaml
standard:
  Discord: false
```
