### ISSUE TITLE
1.16.4: DiscordSRV both-ways not working

### ISSUE THREAD

**Issue by EventCubeMap** [kangarko/ChatControl-Pro#2157]
Hi,

I've been trying to set up DiscordSRV both ways on my server, but I've been unable to get Discord -> ChatControl working properly whatsoever. I've been able to get messages coming from the server to be displayed in Discord, not the other way around. Here are my channels in DiscordSRV:` Channels: {"skysurvival": "771027259389116506","help": "771487473841995776","announcement": "766771375704375327","trade":"771487511385473075","admin":"773569935804596244"}`
Here is my channel config: https://pastebin.com/H5XwTka8

Thank you.

**Comment by kangarko** [comment]
Have you followed our Wiki guide? If yes, please post me the console message that appear when you send a message from Discord. Ensure your channel names are exactly the same.

**Comment by EventCubeMap** [comment]
I have double-checked that the channel names are the same. When I send a message in a discord channel that's one of the ones stated in the top code snippet, in prints `> Message not being sent to admin chat (configuration requires admin chat name: admin)` in the console.

**Comment by kangarko** [comment]
Set Admin_Chat.Enabled to false in settings.yml and that should disable that message and let the plugin continue matching incoming Discord messages with your channel names.

Also you are welcome to upgrade to ChatControl Red https://github.com/kangarko/ChatControl-Red which soon replaces ChatControl Pro and has much better Discord setup with my personal video explaining how that works.

**Comment by EventCubeMap** [comment]
After updating to ChatControl Red, all issues were resolved. Thank you for providing support, and I wish you luck on future endeavours. Goodbye.
