### ISSUE TITLE
1.16.x & 1.12.2 - Connecting Chats of Two Servers?

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [kangarko/ChatControl-Pro#2158]
Version: Paper 1.16.x & Forge + SpongeForge 1.12.2
Question: Does this plugin support SpongeForge by any chance? If possible, I'd like to allow players to chat globally between two servers: a Paper one and a Forge one (that also uses SpongeForge). If this isn't possible with this plugin, do you know of a way?

Thank you!

**Comment by kangarko** [comment]
Apologies, SpongeForge is not yet supported.
