### ISSUE TITLE
Spy issue

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#216]
@kangarko, how can I block the self private messages? :D

and the Spy is not working for me :O
I am op and with * permission but I dont see others' private messages and commands.

(but the private messages now works with the new placeholders, thanks :))

**Comment by kangarko** [comment]
Hey,

Sending messages to self is a feature, that cannot be currently disabled.

To enable spying commands and PM's, use the /spy command, or give yourself 'chatcontrol.spy.autoenable' permission to enable it automatically.

**Comment by rErEaT** [comment]
It's not working for me :-|

**Comment by kangarko** [comment]
The /spy only works for the commands you specify in your settings.yml, make sure you've tested for these:

```
Spy:   
  Command_List: 
    - /tell
    - /msg
    - /t
    - /whisper
    - /r
    - /reply

```

**Comment by rErEaT** [comment]
I used /msg.
So I don't know whats my problem :-|

**Comment by kangarko** [comment]
Do you get the message saying that the spy is enabled or disabled when you run /spy? Check the console for errors on startup and when you run the command.

**Comment by rErEaT** [comment]
Sure I get the message and no errors in the console :(

**Comment by rErEaT** [comment]
Oh works with the latest version.

But can u make a message spy and command spy ?
Because I need just the message spy. :)

And can you make a variable for "command"?
![1](https://cloud.githubusercontent.com/assets/2604798/26520570/a02c465a-42d5-11e7-8e82-710b19ae7b6d.png)
I wanna remove the "command" from the spy message and idk how but can u make the receiver placeholder to work in spy?

**Comment by kangarko** [comment]
The message and command spy is one feature. You can simply choose which commands to spy, and remove all the others you don't need. You can change the spy format in chat.yml.

The receiver placeholder doesn't work by design, there's nothing I can do about it at that position. Same with sending to self, although I may disable it in the future releases.

**Comment by rErEaT** [comment]
spy format is in the settings.yml :O

hmm I hope u can disable the self messages and create the private message spy with sender and receiver :)
(like in deluxechat)
