### ISSUE TITLE
1.16.4 - Chat Formatting Stopped After Updating

### ISSUE THREAD

**Issue by Jimmy-Painter** [kangarko/ChatControl-Pro#2163]
After updating Chat Control versions the formatting on my server has ceased to work. The formatting will only work if I have channels enabled, otherwise, it just uses the default Minecraft format. I really don't want to use channels and I'd prefer to just have the formatting work without using channels. I've combed through all my config files for the plugin and as far as I can tell it should be working. I have formatting enabled in the formatting.yml file and the default format set to 'Chat' but for some reason, it's not using it. This issue has occurred on several versions of Chat Control now and on every server in my bungee network. I am currently running version 8.9.6 on all servers.

I'm not getting any errors in the console, just these warnings. 

Warning: Bungee_Chat feature is deprecated. You can create a bungee channel in channels.yml and put 'Bungee: true' key there to connect it with your network.
[00:59:01 INFO]: Warning: Admin_Chat feature is deprecated. You can create an admin channel in channels.yml. If using Discord, you can put 'Discord: true' key there to connect it with Discord channel by the same name.

I've attached the contents of the plugin file. Hopefully, you can spot some issue that I didn't catch. 

Thank You!

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5610335/ChatControl.zip)

**Comment by AngellitoX** [comment]
Hello there, this looks a little bit odd. I'll test this later tonight. Could you please jump to 8.9.7 and see if it helps in any case?

As a friendly warning, the new ChatControl branch which is incoming soon is attempting to only use channels method for better performance, probably @kangarko did something there on the latest updates to work on compatibility.

**Comment by kangarko** [comment]
Update to latest version. If the problem persists, let me know below.

**Comment by Jimmy-Painter** [comment]
Updating to 8.9.7 did not fix the issue, unfortunately. Since the plugin seems to be heading towards using channels more I have just decided to go ahead and retrofit my chat to utilize channels. With channels, my formatting works without issue. But without channels, the formatting is still not being applied. I should be all set though, thanks for looking at it.

**Comment by kangarko** [comment]
Thanks for letting me know. I will rest assured record a video on migrating to channels when the next major ChatControl Red version is out, you can test it already today: https://github.com/kangarko/ChatControl-Red
