### ISSUE TITLE
How to link when the channel name is different from Discord

### ISSUE THREAD

**Issue by mA0w0** [kangarko/ChatControl-Pro#2167]
What should I do if the Discord channel name and ChatControl channel name are different?

I was able to send a chat from ChatControl to Discord.
However, the chat is not sent from Discord to ChatControl.

I used to send and receive without problems, but now I can't.
Where should I fix it?

[discord] [Discord->ChatControl] Ignoring Discord message from channel 'Chat'. Available ChatControl channels: [DiscordChat]

DiscordSRV
DiscordChat: "0"

ChatControl
Channel name
ChatControl: DiscordChat
DiscordChannnel: Chat

**Comment by kangarko** [comment]
Not possible right now, will come with ChatControl Red: https://github.com/kangarko/ChatControl-Red
