### ISSUE TITLE
1.16.4: Players dont autojoin the global channel

### ISSUE THREAD

**Issue by jaboy** [kangarko/ChatControl-Pro#2168]
Hello

I have a problem with chatcontrol, i just updated it.

Players dont auto join the new "global" channel i created, they can join it manually with /ch join global.

Players do have "chatcontrol.channel.autojoin.global.write"

Enabling pex to show all permissions checked, and rejoining shows that the auto join permission is not even being checked, making me think that i may not have enabled something somewhere, but auto join at the bottom of channels.yml is set to true

Added "channels-join" to the settings.yml does not seem to add anything to the server log when joining the server or doing a /ch join global

**Comment by kangarko** [comment]
Hey, I recommend you upgrade to https://github.com/kangarko/ChatControl-Red, autojoin works much better and more like you'd expect there, We also have better wiki for this there.

**Comment by Malachiel87** [comment]
same issue here, the autojoin permission don't work only in 1.8.8 server, it work only 1.16 server

**Comment by kangarko** [comment]
It's free to download: https://github.com/kangarko/ChatControl-Red/releases

I looked into the code, and it's actually "channels" you need you set your Debug option to, not "channels-join". Then it will print out why it does not work, but it should. I also updated Pro wiki.

**Comment by Malachiel87** [comment]
i tried to set
Debug: [channels]
is not showing any usefull info

**Comment by kangarko** [comment]
Can you please post me what it shows? Also what permissions does the player have?

**Comment by Malachiel87** [comment]
![image](https://user-images.githubusercontent.com/3611852/100732636-49899e00-33cd-11eb-9e62-6cb52671dc6d.png)
![image](https://user-images.githubusercontent.com/3611852/100732721-67ef9980-33cd-11eb-9dfc-a0a313d5be50.png)

**Comment by kangarko** [comment]
Thanks, I will fix that. Spigot gave us the information that the player was invalid at the time of his joining, so I just removed that safety check and it works now.

**Comment by Malachiel87** [comment]
so the red wil stay free? or it will cost?

**Comment by kangarko** [comment]
You will get it for free. It's a separate product built from scratch so it'll be as a new premium plugin.
