### ISSUE TITLE
Errors with entity's in message.yml

### ISSUE THREAD

**Issue by TyrellPlayz** [kangarko/ChatControl-Pro#217]
The plugin won't run because it can't find the killer EVOKER_FANGS in messages.yml
I remove it and it can't find the killer of another entity
Please respond quickly my server has no chat system

**Comment by kangarko** [comment]
Hey,

it seems you're Minecraft version is older and thus is missing some entities that are used in the default messages. I have updated the new version so they are silently ignored. A new release will be available shortly.
