### ISSUE TITLE
Paper 1.16.4: Discord Channel Problem (maybe bug, maybe my misunderstanding)

### ISSUE THREAD

**Issue by Tomasan7** [kangarko/ChatControl-Pro#2172]
So, I have DiscordSRV and ChatControl Pro installed.

my channels.yml:
  ```
default:
    Discord: false
  discord:
    Discord: true
  a-team
    Discord: true
```

my channels in DiscordSRV's config.yml:
  ```
Channels: {"discord": "781961011993378896", "a-team": "782677848099913778"}
  DiscordChatChannelDiscordToMinecraft: true
  DiscordChatChannelMinecraftToDiscord: true
```

other discord options:
  formatting.yml:
    `Integration.Discord_Channel: ""`
  channels.yml:
```
    Compatibility.Discord.Control_Incoming_Messages: true
    Compatibility.Discord.Deny_Unknown_Channel: true
    Compatibility.Discord.Apply_Natural_Format_If_Online: false
```

(discord in "" means minecraft channel and without, means the program Discord)
The thing is, When I send message in minecraft in "default" channel (which is not set in DiscordSRV config), it sends the message to channel corresponding to "discord" channel (set in DiscordSRV config). And messages **from** discord are ignored completely.

Discord Debug message when sending message on discord to channel connected with "discord" channel:
```
  [20:32:39 INFO]: [discord] > Message not being sent to admin chat (configuration requires admin chat name: a-team), moving 
  forward...
  [20:32:39 INFO]: [discord] [Discord->ChatControl] Ignoring Discord message from channel 'minecraft-chat'. Available 
  ChatControl channels: [a-team, default, discord]
```

**Comment by kangarko** [comment]
When it comes to Discord compatibility, I highly recommend you upgrade to https://github.com/kangarko/ChatControl-Red and then follow our new guidelines here: https://github.com/kangarko/ChatControl-Red/wiki/Discord

**Comment by Tomasan7** [comment]
I just bought ChatControl Pro, and you are telling me there is better and free version? Or what even is ChatControlRed, I don't understand. Why it isn't on spigotmc?
