### ISSUE TITLE
Bypass swearing in specific channels?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl-Pro#2173]
So I'm trying to do an adult channel where cursing is allowed, but I also want swears to censor in the global channel. Is there an operator that allows you to ignore specific channels for certain rules?

**Comment by kangarko** [comment]
I apology, this is not yet possible but will come very soon with the new ChatControl Red https://github.com/kangarko/ChatControl-Red where you can simply add "ignore channel" rule operator for that channel.
