### ISSUE TITLE
What are the values for each Hover_Event's action?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2174]
Based on the wiki, I know that SHOW_TEXT action has textstring values (ex. Values: "This player is VIP").

What are the values for SHOW_ACHIEVEMENT, SHOW_ENTITY and SHOW_ITEM actions? (i'd appreciate examples)

**Comment by kangarko** [comment]
I apology, these are unsupported right now. ChatControl Red will come with support for SHOW_ITEM, you can join our testing today at https://github.com/kangarko/ChatControl-Red
