### ISSUE TITLE
How to make different hover_events for different chat nicknames?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2176]
For example,

I want to apply a hover_event to the first_part. But I want my helpers have another hover event for their first_part. How to implement it?

**Comment by nikitushu2** [comment]
Oh, ig Ranked Formats is the solution?

**Comment by nikitushu2** [comment]
If I add Ranked Formats and give myself "my.rank.admin" permission, the prefix does not appear

**Comment by kangarko** [comment]
The easiest way is to have two first_part's, "First_Part_Default" and "First_Part_Helper" and assign them different Sender_Permissions: https://github.com/kangarko/ChatControl-Pro/wiki/Formats#conditional-format
