### ISSUE TITLE
How to resolve the conflict of /tell command with Essentials?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2177]
I tried setting Essentials permission essentials.msg (includes /tell command) to false.
I set all the ChatControl's priorities to HIGHEST.
I tried enabling Essentials /tell command back.
I put /tell command into disabled-commands section in Essential's config.

But still when I type /tell, ChatControl does not react to it. What to do?

**Comment by kangarko** [comment]
Enable ChatControl's private messages by setting Private_Messages.Enabled to true and checking what Tell_Aliases you have in that settings.yml section
