### ISSUE TITLE
Changing command for admin channel messages

### ISSUE THREAD

**Issue by SiuanSong** [kangarko/ChatControl-Pro#218]
I'd really like to be able to change the command for sending a message to the admin channel (so I can get rid of StaffChat), but currently it just tells me:
Usage: /chc ach <message> yadda yadda

I know I could just make a shortened command to toggle the chat, but we'd really prefer not doing that. 

bukkit commands.yml
 
aliases:
  icanhasbukkit:
  - version $1-
  a:
  - chatcontrol ach

**Comment by kangarko** [comment]
Hey,

using bukkit.yml is the most convenient and the safest way to do that. Here is a working example that transform /chc ach to /a. I am sorry if you prefer not to use it, but unfortunately I have no easy alternative for you then.

```
aliases:
  a:
    - chc ach $1-
```
