### ISSUE TITLE
A /chc NameColor for ccp 9?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl-Pro#2180]
Though it’s great I finally got name colors to work in chat channels, I would much prefer if ccp handled name colors instead of the outdated, ghetto name color plugin I use today. 

I feel like many other server admin’s could make good use of it, hope you consider:)

Edit: Also can't seem to figure out if this is possible: The ability to show the home server's prefix in global chat. Right now it's showing other server prefixes but for players on the home server it doesn't show anything, gives the chat a bit of an uneven look. it'll be like:

[PV] player1: wb
player2: ty

**Comment by kangarko** [comment]
Hey!

Yes we do have /chc color command for player chat colors. You can even use the /tag command to let players choose their own prefix or nick.

Regarding your other question, I recommend you read our wiki, it is totally doable with our formatting system.

**Comment by Squeej** [comment]
Yes and I love it, was able to replace our original chat color plugin with ccp, among a few other plugins

But I meant one for **name** colors also, so players can change both their chat and name colors all through ccp. No biggie though if it's too much, just figured if theres a chc color for chat colors, something for name colors would compliment the plugin further. I don't use essentials btw, all of my chat management is done through ccp and I use an old plugin called coloredplayernames for name colors.

And thanks for the tip, I'll read through the wiki and see what I can do:) Keep up the good work, it's inspiring

**Comment by kangarko** [comment]
Thanks for the feedback! I will look into this in the future when I have time.
