### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AlfreDGR** [kangarko/ChatControl-Pro#2182]
People in my chat can link and spam!

**Comment by arturek1666** [comment]
Do you have protocollib installed?

**Comment by arturek1666** [comment]
+ Check if you type in /plugins chatcontrol pro is in green + any error on console xD + plugin and server version would help as well.

**Comment by kangarko** [comment]
You haven't followed our instructions when creating an issue.

**Comment by kangarko** [comment]
And also see Common Issues on our wikipedia regarding links.
