### ISSUE TITLE
DiscordSRV Integration Not Working

### ISSUE THREAD

**Issue by Darien5** [kangarko/ChatControl-Pro#2183]
Hello! I recently installed discordsrv onto my server and the messages from Minecraft to discord aren’t working. I followed some instructions online to mess around with the formatting.yml file. The discordsrv now works but it’s double messaging. How do I fix this?

**Comment by kangarko** [comment]
Have you followed this? https://github.com/kangarko/ChatControl-Pro/wiki/Discord

If yes, please post me the console message as instructed there.

**Comment by Darien5** [comment]
Yes, I followed those instructions and what console messages do you mean?

**Comment by Darien5** [comment]
I turned on formatting because that's the only way I got Minecraft to discord messages too

**Comment by kangarko** [comment]
Hey, sorry, there are some limitations to our Discord hook but we already improved it to ChatControl Red which you can download from here: https://github.com/kangarko/ChatControl-Red we also have a Wiki tutorial on its Wiki page regarding Discord
