### ISSUE TITLE
1.16.4: Was staffchat finally killed? And should I use a private channel instead (which would make sense)

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#2184]
So basically what the title of this question says.

Recently after a CC update, staffchat got disabled, and is no longer accessible using /staffchat
![imagen](https://user-images.githubusercontent.com/6623704/101071097-6f18d200-359c-11eb-9f39-17b7e980e69d.png)
This is actually something quite common, since every update usually something gets inexplicably reverted in the config.

Could staffchat have finally been killed? And should I use a private channel instead, which would make sense?
> Could staffchat have finally been killed?

I looked for relevant configs on staffchat, but couldn't find anything, which makes me think so. I've left this feature propperly configured a few times already, but can't remember where it was.

I've checked the updates section on spigot, and there's no mention on staffchat being removed, so idk.

**Comment by kangarko** [comment]
You can enable Admin_Chat by setting Enabled to true in settings.yml back.

We will remove admin chat because this works like channels, so it was a duplicate and took us extra time to maintain. I recommend you use channels if you want admin chat.
