### ISSUE TITLE
1.16.4: Transitioning to ChatControl-red

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#2185]
Question: How smooth will transition be?

I don't mind paying for a new version, but I wouldn't want to have to configure everything again.

**Comment by kangarko** [comment]
You can test it yourself https://github.com/kangarko/ChatControl-Red/wiki/Upgrading#upgrading-from-chatcontrol-pro-8th-generation and just download the JAR from Releases and do the migration :) If anything open a ticket and I help you.
