### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl-Pro#2186]
Hi there ive just upgraded to java v15
Papermc version 312

and now all your plugins are no longer working. BOSS and ChatcontrolPRO

My console log
[https://hastebin.com/raw/dewilezeda](https://hastebin.com/raw/dewilezeda)

**Comment by kangarko** [comment]
Java 15 is not yet compatible, I apologies. I recommend staying with Java 8-14. We plan to update after the 1.17 launch.
