### ISSUE TITLE
chinese translation?

### ISSUE THREAD

**Issue by martin1194** [kangarko/ChatControl-Pro#2189]
Chinese have 2 types.
One is simplified Chinese.
Another one is Traditional Chinese.
I hope u may send the messages_cn.yml in the .docx file to me.
I can't open ur messages_cn.yml with any mention. 
It can't show any words.
Traditional Chinese systems can't open simplified Chinese is a very common problem. I hope u may send me messages_cn.yml in the .docx file and I can open it in MS word. 

martinc1194@gmail.com
![image](https://user-images.githubusercontent.com/18354205/101212767-a41c4600-36bc-11eb-9c43-cfb8973023cd.png)

**Comment by kangarko** [comment]
Here is it: https://pastebin.com/sRuVQL5X

**Comment by martin1194** [comment]
Thank you 👍
