### ISSUE TITLE
Feature block bad nicknames

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl-Pro#219]
Hi, I wasn't sure if this is possible that's why i am writing about it. So i know that this plugin blocks if someone swear but what about if someone join a server with a bad nick, that is a swear but it does not block it. Is it possible with this plugin that if nickname has a swear he will be kicked from server

**Comment by kangarko** [comment]
Hey,

yes you can find the feature at Anti_Bot.Disallowed_Nicknames in settings.yml
