### ISSUE TITLE
Error: Report: Value 'org.mineacademy.chatcontrol.lib.fo.model.DiscordListener$DiscordListenerImpl@7543e344' is already in the list!

### ISSUE THREAD

**Issue by martin1194** [kangarko/ChatControl-Pro#2190]
I am really dont know what happen. Can u help me to find out? It have some error.

![image](https://user-images.githubusercontent.com/18354205/101214856-0f1b4c00-36c0-11eb-8423-1fa1a6257aba.png)

**Comment by kangarko** [comment]
Seems like you had multiple ChatControls installed. Check your plugins/ folder and only have 1 jar.

**Comment by martin1194** [comment]
No. It's not!!  After I use ChatControl-8.8.8 version. It's work!!
 It seems ur new version can't support 1.12

**Comment by kangarko** [comment]
I will have a look right now

**Comment by kangarko** [comment]
It loads fine for me: 

![a](https://i.imgur.com/Uq5ERxc.png)

Ensure you do a clean start. Do not use plugman, do not /reload or /chc reload or anything else. Just stop the server, place the new JAR and start it again. 

Also, try using just Paper not anything else.

**Comment by martin1194** [comment]
![image](https://user-images.githubusercontent.com/18354205/101390129-b210d780-3905-11eb-82d0-48272ae83d18.png)
![image](https://user-images.githubusercontent.com/18354205/101390154-bccb6c80-3905-11eb-91f2-dfa7f2beccb8.png)
I using magma server. It only 4 plugin also error.

**Comment by kangarko** [comment]
Sorry for whatever reason this doesn't work. I had to travel so I'm unable to investigate before 14-21 days. Let me know your email address so I can refund you so you don't have to wait.

**Comment by martin1194** [comment]
return this issue to open and i wait for your reply

**Comment by kangarko** [comment]
Please ZIP me your entire test server without worlds and I can test this.

**Comment by martin1194** [comment]
here you are

https://drive.google.com/file/d/1Rfgot2TzKT4uBfQXH9LA-QTBnx84ymKG/view?usp=sharing

**Comment by kangarko** [comment]
Requested access

**Comment by martin1194** [comment]
Accepted

**Comment by kangarko** [comment]
There's a problem in Magma with one of their ways of calling the class loader. They have "getSytemClassLoader()" which has a typo, it should be System not Sytem.

You need to contact their developers to fix this, or you can get a refund on this plugin since I am unable to fix this myself.

**Comment by martin1194** [comment]
Great. I will connect to Magma's developer. Thank you for find the problem out. I will use v8.8.8 first. This is a good plugin too when it was v8.8.8. :D
