### ISSUE TITLE
Java 15 support

### ISSUE THREAD

**Issue by maartenvr98** [kangarko/ChatControl-Pro#2192]
Will there be Java 15 support? The only major issue I can found is that Java 15 drops Nashorn support for JavaScript placeholders. But there is a alternative: https://golb.hplar.ch/2020/04/java-javascript-engine.html 

Paper suggest running Java 15 for paper 1.16.4 to improve performance.

**Comment by kangarko** [comment]
Thanks, we'll plan adding J15 support when MC 1.17 is out.
