### ISSUE TITLE
1.12.2 | Discord.Listener

### ISSUE THREAD

**Issue by martin1194** [kangarko/ChatControl-Pro#2193]
ChatControl-8.9.9 version isn't support Magma-50f320e-server
![image](https://user-images.githubusercontent.com/18354205/101288131-372dbb00-3838-11eb-97bd-293d91fbcf5a.png)

https://github.com/kangarko/ChatControl-Pro/issues/2190
If I downgrade to ChatControl-8.8.8. It's work!!! U haven't wait my reply and close the issue? 
What? Is this the way to make a bug away? I'm sure I only have 1 jar inside the folder.

**Comment by kangarko** [comment]
Please just comment below and I will reply there.
