### ISSUE TITLE
1.16.4 - TAB Complete

### ISSUE THREAD

**Issue by MattDeakin** [kangarko/ChatControl-Pro#2194]
Hey, you asked me to submit a ticket about the auto complete not working. Hope this is the right place

Not too sure what it is but here's an example of the subcommands not showing, this happens with every command.

Problem - https://imgur.com/a/oh5HxI0

settings.yml - https://pastebin.com/X8MJRqzX

ChatControl Pro - 8.9.9

Hope this is enough information about it, cheers 👍

**Comment by kangarko** [comment]
Tab completion is broken on Pro, but we already got it working in https://github.com/kangarko/ChatControl-Red which you can download from that site too
