### ISSUE TITLE
Channel and discordsrv problems

### ISSUE THREAD

**Issue by o0sh4d0w0o** [kangarko/ChatControl-Pro#2196]
Hi,

I have a problem with the channel feature and discordsrv support,

I have 3 channels : 
- standard (where all player can chat)
- modo (a private modo channel)
- admin (a private admin channel)

I have same of these channel created in discord, all messages send from MC -> Discord are OK and goes to the right discord channel, otherwise, Discord -> MC only work for admin channel.

Standard and modo channels seems ignored and debug mode said me in console  : 
 [INFO] [discord] > Message not being sent to admin chat (configuration requires admin chat name: admin), moving forward..

I need to display messages like that : 

- Discord standard channel should send a message in minecraft standard channel
- Discord admin channel should send a message in minecraft admin channel
- Discord modo channel should send a message in minecraft modo channel

Can you help me about how to solve this problem, or can you add a feature to allow this please ?

Best regards,

**Comment by kangarko** [comment]
Thank you. Our system is unfortunately pretty limited on Pro, but I recommend you upgrade to ChatControl Red: https://github.com/kangarko/ChatControl-Pro

**Comment by o0sh4d0w0o** [comment]
Hmm, chatcontrol red ? Where i can get this upgrade, can u give me and explicit link please ?

I Hope that's free for chatcontrol pro customer, I really need this feature.

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Red
