### ISSUE TITLE
1.12.2 PlotSquared compatibility.

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2198]
As you may know, Plotsquared comes with public and plot chats.

How do I set CC's chat channels exactly like those? I want my public chat to be moderated and the plot chat to be free from moderation.

**Comment by kangarko** [comment]
Thanks, assuming you wish to have a public channel that's moderated and a plot channel that's not, we've already got a system like that for https://github.com/kangarko/ChatControl-Red which is an upgrade to Pro.

You can just create two channels and set the other channel to have a Party option to "plotsquared-plot", and then use "ignore channel {name}" operator for the rules/ads handler (called groups.rs in Red)

**Comment by nikitushu2** [comment]
Thanks, this is amazing! Noone has chat support for plotsquared yet on the market. Do I just put chatcontrolred jar file instead of the chatcontrol one?

**Comment by kangarko** [comment]
Yes, leave ChatControl folder but remove ChatControl jar. Then you can use our /chc migrate command after you get yourself known with the plugin using /chc tour ;)
