### ISSUE TITLE
1.16.4: Players do not leave a channel after they no longer have permission

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Pro#2199]
https://screenshots.skizzles.me/wAnA3/GecalISA34.png

Currently I have a ex-staff member that was removed from their role, after removing their Helper rank they were still able to see the staff chat. The Helper rank has auto join, but after the role was removed it kept the person in the channel.

Ideally I would like them to be removed from channels they do not have permission to.

If more details are needed please let me know.

**Comment by kangarko** [comment]
Thank you for your suggestion, I can put this onto our todo list. However, we already got a system like that for https://github.com/kangarko/ChatControl-Red which you can download free

**Comment by Skizzles** [comment]
Hello @kangarko Thank you very much for the quick response.

With this download will all my old files work etc?

**Comment by kangarko** [comment]
Do make a backup and then leave your ChatControl folder there, and use the migration command.
