### ISSUE TITLE
ChC see command's param as chat message

### ISSUE THREAD

**Issue by AngelDeaD** [kangarko/ChatControl-Pro#22]
If I type two times 
/tpa player1   first time everything is ok, but second time it says "Please do not repeat same (or similar) message."
Then if I type
/tpa player2  first time it work, but second it display "Please do not repeat same (or similar) message."

In case where player1 and player2 has similar nicks it won't send tp to another player, but it does not matter, I just want to know how to fix this, because ChC see commands as chat message.

I want forbide players from spaming chat (including chat commands) but rest like tpa, warp, home, spawn.. they can use that as many time as they want.

**Comment by kangarko** [comment]
You can add commands that will be ignored from the duplicate check in **Anti_Spam.Commands.Whitelist_Similarity** in settings.yml.
