### ISSUE TITLE
[git] Put the latest configs in this repo

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#220]
Chatcontrol dousn't seem to populate any new config options when they are added, please put in the main config files into this repo so we can see when they are updated.

**Comment by kangarko** [comment]
Hey,

cannot reproduce. When you update ChatControl, your configuration is updated automatically as well. Make sure there are no errors and that you're running on the latest version.

**Comment by FrozenBeard** [comment]
I have never had my configs auto updated, i've had to manually change mine.

**Comment by kangarko** [comment]
That's weird, because the plugin has an auto updater. You can watch it prints messages into the console on statup when something in your settings.yml changes.
