### ISSUE TITLE
1.16.4:Shortcut

### ISSUE THREAD

**Issue by SmallFood1026** [kangarko/ChatControl-Pro#2200]
Sorry... for bad english
This is translated from Google

How can I use shortcuts for multiple channels
Because it still cannot be used after setting

![23](https://user-images.githubusercontent.com/75075197/101913443-f77f1e80-3bfd-11eb-8f33-95dd306f84bc.PNG)

**Comment by kangarko** [comment]
You can create a rule for these that you put into chat.txt file instead:

```
# This will send all messages starting with ! to the global channel.
match ^(\!)(.*)
then command channel send global $2
then deny
```

**Comment by SmallFood1026** [comment]
I put this string into the rules
Still not working...

**Comment by kangarko** [comment]
<img width="556" alt="Screenshot 2021-01-20 at 16 04 26" src="https://user-images.githubusercontent.com/1918426/105193786-2e1f5180-5b39-11eb-9456-e8713c93769a.png">
It works fine if you follow instructions

**Comment by SmallFood1026** [comment]
![擷取](https://user-images.githubusercontent.com/75075197/114893069-ea8a6a00-9e3f-11eb-8d4c-d620da7a0344.PNG)
![擷取2](https://user-images.githubusercontent.com/75075197/114893151-03931b00-9e40-11eb-8b52-0060c4897dc5.PNG)

sorry, I follow your way, it's still the same

**Comment by kangarko** [comment]
Yes because rules are checked after we evaluate a chat message, if there's no channel to send the message to, we prevent that.
