### ISSUE TITLE
1.16.4: Rules aren't applied in msgs

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl-Pro#2201]
Hi, I have problem that msg normally allow swears etc even when it shouldn't be allowed as you can see in settings, rules etc. Could you please check what's wrong there? 
[chatcontrol.zip](https://github.com/kangarko/ChatControl-Pro/files/5681012/chatcontrol.zip)

**Comment by kangarko** [comment]
Kde sa tie spravy neblokuju?

<img width="500" alt="Screen Shot 2020-12-15 at 13 01 17" src="https://user-images.githubusercontent.com/1918426/102212505-a1e49380-3ed5-11eb-897e-23d426aa8bb1.png">

**Comment by kangarko** [comment]
Vyskusaj dalsiu verziu, ked stale nepojde napis dole.
