### ISSUE TITLE
1.16.4 / 8.8.9 (chatcontrol pro): How does the chat ignorer section work

### ISSUE THREAD

**Issue by Tobi-Jakka** [kangarko/ChatControl-Pro#2203]
So I have been wondering how this section works:
![image](https://user-images.githubusercontent.com/42676160/101991163-37500f80-3cab-11eb-9f36-9de70bce5e56.png)

I want to make it so that I can type /chc ignore swear to toggle swear on & off (so that if swear is toggled off you can see swear words, but if not you cannot see them) but I just cant get it to working. My swear rules are located in the rules.txt file

**Comment by kangarko** [comment]
I apology, this section has never worked as intended and has been removed in the upcoming ChatControl update.
