### ISSUE TITLE
1.12.2. ChatControlRed. Forwarding message of the /helpop command does not work

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2206]
I have a channel called `chathelpop` and I send a message after `/helpop <msg>` to that channel ([everything](https://ibb.co/MG7HjGn) is configured in the chat.rs).

And I get [this error](https://ibb.co/MRwvzxL).

How to fix this?

**Comment by kangarko** [comment]
It works fine, just make sure there are no other rules interfering with this one. Remove the other /helpop rules and move yours on the top of the file:

<img width="1135" alt="Screen Shot 2020-12-15 at 13 45 49" src="https://user-images.githubusercontent.com/1918426/102216725-dce9c580-3edb-11eb-8056-4fe226136910.png">

**Also, next time please post into the appropriate issue page and follow our template:**
https://github.com/kangarko/ChatControl-Red
