### ISSUE TITLE
1.12.2. ChatControlRed. I give perms for joining a channel but players still can't access it.

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2207]
I give the [following perms](https://ibb.co/jh5DBWY) for my players.

But they still [cant access](https://ibb.co/yhxh92C) them (they are not even put into `chatplot` channel automatically on join as one of the perms states).

How to fix this?

**Comment by kangarko** [comment]
Also give them chatcontrol.channel.join permission. Next time please post into https://github.com/kangarko/ChatControl-Red
