### ISSUE TITLE
ChatControlRed. When I recover my email via Authme, CHR blocks my email as an attempt of advertising.

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl-Pro#2208]
How to allow using emails in recovery command from authme?

**Comment by Help3rL** [comment]
You can simply add command to ignore in handlers.yml

**Comment by nikitushu2** [comment]
I can't find handlers.yml in ChatControlRed

**Comment by kangarko** [comment]
If you use Red, post into https://github.com/kangarko/ChatControl-Red 

You can use "ignore command" operator from rules/groups.rs in Red:

```
# Do not filter ads in the commands below.
ignore command /brush|/auction|/auc|/register|/reg|/login|l
```

And simply append your commands there using | as a separator
