### ISSUE TITLE
1.16.4: Adminchat Chat_Mode: ADMIN turn on again after server restart

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#2210]
If I write first /chatcontrol adminchat switch the Chatcontrol writes to the database: Chat_Mode: ADMIN
If I write again /chatcontrol adminchat switch Chatcontrol no removed from database: Chat_Mode: ADMIN

ChatControl version 8.9.9

**Comment by kangarko** [comment]
Are you using MySQL?

**Comment by andris155** [comment]
> Are you using MySQL?

No. I use the default database settings.

**Comment by kangarko** [comment]
Thanks so much, next version will fix this

**Comment by andris155** [comment]
Thanks!
