### ISSUE TITLE
1.16.4: If I unignore the player ignore again after server restart

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#2211]
If I write first /ignore player the Chatcontrol writes to the database: Ignored_Players: player
If I write again /ignore player no removed from database: Ignored_Players: player

ChatControl version 8.9.9

**Comment by kangarko** [comment]
Are you using MySQL?

**Comment by kangarko** [comment]
Closing since this looks similar to https://github.com/kangarko/ChatControl-Pro/issues/2210
