### ISSUE TITLE
JSON Formatting for Join + Leave Messages

### ISSUE THREAD

**Issue by Ash10744** [kangarko/ChatControl-Pro#2212]
Overall I'd like the hover_events to be possible in leave and join messages and even the click events. It'll improve customization 

(If this is already a thing I am sorry lmao)

1. This would increase the customization of leave and join messages and expand on an already great feature.

2. My server wouldn't personally be affected much. But I use the leave and join messages as a feature within my donation packages and it'd only enhance them more.

3. Not suggesting anything new just an improvement on an already great feature (Which may already be a thing and I'm being stupid)

**Comment by Help3rL** [comment]
You can add them [JSON wiki](https://github.com/kangarko/ChatControl-Pro/wiki/JSON) 
I tried making simple one and it worked 
in messages.yml line 121 I wrote in 
`Message: '[JSON] {"text":"{player} joined?","bold":true,"color":"dark_blue","hoverEvent":{"action":"show_text","contents":{"text":"Simple text","color":"dark_red"}}}'`

**Comment by kangarko** [comment]
Thanks, as Help3rL said, you can use JSON for ChatControl Pro 

Or use https://github.com/kangarko/ChatControl-Red where you can use any format in player-related messages that can have these events nativelly.
