### ISSUE TITLE
Minecraft Version: Looking for a Chat Plugin that will do what i need it to do.

### ISSUE THREAD

**Issue by SirCraftypants** [kangarko/ChatControl-Pro#2214]
I'm on Paper 1.16.4

Currently using Chat Manager, I see that you and the Dev of Chat Manager have had a run in in the past, I was pretty happy with what Chat Manager does but it lacks just one thing I need, the ability to setup click commands for world/rank/playername prefix's.

I also liked the fact Chat Manager allowed for each multiverse world to have it's own chat channel. 

Now I've requested the the Dev of Chat Manager added click commands and they were quite blunt to be honest, their reply was a simple NO.

I inquired as to why and their answer was, quote "because i'm going to add it in to a premium version when i feel life it". Can't say i was too impressed but there you have it.  Now I am not afraid to pay for good plugins, in fact I own some quite pricey Plugins around £16 area. 

Now my issue is, is the click command option worth the £18 outlay, i'm not really interested in the bells and glitter, i just need to do antibot, antiadvert, spy, world channel and click command.  So my question is, do i buy your plugin if it can do what i need it to do for £18 or do i wait and see how much the other Dev sells his for? it's a tough one.

Also, do you have a Discord Server for support?

**Comment by Help3rL** [comment]
Well ChatControl pro does things you need to but i also can suggest [CMI](https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/) (content managment plugin) it can manage chat way you need and offers quite a few other features but i use both because i am fimilliar with CC pro, and it offers more chat features that CMI doesnt offer

**Comment by kangarko** [comment]
I recommend getting ChatControl Red: https://mineacademy.org/chatcontrol-red

You can easily create per-world channels with multiverse prefixes, add you can easily add click/hover events for ANY part of your chat for each channel differently.

Best of all, it's only 9.97€ right now on sale!
