### ISSUE TITLE
I do not know if is the right section to report.. but here we go

### ISSUE THREAD

**Issue by srrawr11** [kangarko/ChatControl-Pro#2215]
Minecraft Version: 1.8.8
MySQL: false
BungeeCord: true

Hi basically I was trying to block the /about + TAB and it works perfectly.. but when I do /about W + TAB it shows plugins that I got starting with the letter W.. I was trying to see the config of the ChatControl if I blocked any section wrongly..

I would send you a video and you can have a quick look ^^
In the free version for the ChatControl I think there is a option called 'Allow_When_Message_Has_Space: true/false'
Where with that section it works, but If I am not wrong in the PRO version is not any section of that.

I was going through with this Spanish guy https://www.youtube.com/watch?v=DPsZ2F_9Fbg&ab_channel=Ajneb97

This is my video: https://mega.nz/file/gy4gSRJK#QP95fOuE0vYBu7ka9v1HeW8YZxbUcl6DzD-cEl7c6Qg

Thanks, sorry for my bad English..

**Comment by kangarko** [comment]
Thank you, unfortunately the tab system we have in Pro is severely limited, I recommend you download ChatControl Red that has much more powerful tab blocking mechanisms from https://github.com/kangarko/ChatControl-Red

**Comment by srrawr11** [comment]
Thanks for reply my message.
So I need to but again this plugin or just I can download it as normally?

**Comment by kangarko** [comment]
Check out mineacademy.org/chatcontrol-red to see if you're eligible for a free upgrade :)

**Comment by srrawr11** [comment]
It says that I have to pay 10usd or something like that..

**Comment by kangarko** [comment]
what's your mcmarket username? I'll add you

**Comment by srrawr11** [comment]
This is my name in the mc-market: Sr_Rawr
https://www.mc-market.org/members/163824/

Thanks.

**Comment by kangarko** [comment]
Thanks, added!
