### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by Help3rL** [kangarko/ChatControl-Pro#2216]
hey i would like to ask if its needed for me to purchase chat control red if i want to upgrade( test out new features) i am currently using chat control pro?  I am using mc version 1.16.4

**Comment by kangarko** [comment]
If you fulfill the criteria for a free upgrade outlined at https://mineacademy.org/chatcontrol-red/ then no, simply fill out the form and you will get free access. If not, then you can get Red for 3 coffees for 9 bucks total.
