### ISSUE TITLE
1.16.3-4: ChatControl bypassing built-in game chat hiding measures.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#2217]
This applies to two specific situations: first one can be see by (while in game) pressing ESC, "Options..." and then "Chat Settings...".  The setting in question which is being circumvented by ChatControl is the very first, try switching to any option other than "Chat: Shown" and neither other option has any effect.

Second one can be experienced by pressing "p" while in game (not in chat... as like any set game or navigation key).  This accesses the new feature implanted by Microsoft which gives you the currently online user list and allows users to block chat from specific users, much like ChatControl's mute feature would.  If you click the button next to one of the names, there is text placed in chat: "Chat messages from [name] will be hidden"  but you quickly discover that this is entirely untrue since any messages sent through ChatControl completely bypass this feature placed by Microsoft, so you will see everything you are trying to avoid.  It would be nice that since it is possible for your plugin to accomplish this that staff members or users of a certain rank are not able to be hidden via this method, but it should probably still work in general.

**Comment by kangarko** [comment]
Unfortunately, there are no API's we can use for these two functions right now from Spigot.
