### ISSUE TITLE
[Request] /chat to switch channel quickly

### ISSUE THREAD

**Issue by Porama6400** [kangarko/ChatControl-Pro#222]
Example
**/chat global** will switch player into global channel (even when they spying on it)
and
**/chat standard** will switch player back to standard channel and autospy on global

**Comment by kangarko** [comment]
Hey,

you can easily create command shortcuts via commands.yml file in the root server folder, see
https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands
