### ISSUE TITLE
1.16.4 : messages_ru.yml is automatically broken

### ISSUE THREAD

**Issue by BabelSolea** [kangarko/ChatControl-Pro#2220]
1.16.4 PaperMC

2) Russian localization file broken by default.

3) Info and steps i tried:
0. install chatcontrol+ latest release in english locale +protocolLib +placeholdersAPI
//didn't change anything in plugin
1. shutdown server
2. check what localization folder created
3. changes settings.yml with all tips i found in your wiki
`Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: false
Locale: ru
Translate_Diacritical_Marks: false`
4. launch server
5. check localization folder >>> found 30kb messages_ru.yml broken data with abrakadabra inside
6. found somewhere in wiki what we can found some default files inside .jar by open its with WinRar
7. found inside 19kb messages_ru.yml with not broken data and place in localization folder.
8. profit!

Please fix that situation or even publish localizations files in github like doing many other author's. ty

❤❤❤❤❤❤❤❤❤

**Comment by Envel-Nikita-Gutsenkov** [comment]
в моем случае все нормально

**Comment by kangarko** [comment]
Remove your broken messages_ru.yml and let ChatControl place it again.

When you open that file make sure you use the right program that supports it: https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

**Comment by BabelSolea** [comment]
I did it few times.
I found about true encoding.
and anyway even with out open our any touching file after server launch this file already 30kb size and with broken data.

that's why i create this issue.

but when i place this file from plugin .jar manually - all fine and i can open edit and save file with out breaking data.

**Comment by BabelSolea** [comment]
> Remove your broken messages_ru.yml and let ChatControl place it again.
> 
> When you open that file make sure you use the right program that supports it: https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

upd.

I did it few times.
I found about true encoding.
and anyway even with out open our any touching file after server launch this file already 30kb size and with broken data.

that's why i create this issue.

but when i place this file from plugin .jar manually - all fine and i can open edit and save file with out breaking data.

**Comment by kangarko** [comment]
Then unfortunately it's your hosting's issue with encoding, try reaching out for their support. Or the operating system's issue somewhere.
