### ISSUE TITLE
1.13.2: Death Messages

### ISSUE THREAD

**Issue by RobZenTL** [kangarko/ChatControl-Pro#2221]
Hey, short question: We are using death messages. We have a specific world that has minigames etc and the death messages are shown even when the gamerule for deathmessages is set to false. Is there any chance to disable death messages for a specific world? So players in all other worlds aren't spammed with death messages from that one world where minigames are played? Didn't find any option in the configs until now. Thanks!

Paper 1.13.2
ChatControl Pro 8.6.6 + 8.9.10

**Comment by kangarko** [comment]
Hey!

With Pro we did not have that option back when I was coding it, but it came along with ChatControl Red (mineacademy.org/chatcontrol-red) where you can easily open messages/death.rs file to edit your death msgs and place "ignore sender world X" to not send if the dead player is in the given X world.
