### ISSUE TITLE
1.8.8: Getting problems with color menu

### ISSUE THREAD

**Issue by DJDanTheMan** [kangarko/ChatControl-Pro#2222]
I'm currently experiencing issues with the color menu, I want to make it so when players have selected their chosen color, but for some unknown change made to the plugin, it makes it so the active color after active color is still remaining active, I want to make so when a player either logs out or the server reboots the currently active color in the color menu is automatically disabled. I had no issues with an older version of the plugin except for the change that happened in version 8.8.2. What can I do to resolve this issue so I can resolve the issue?

**Comment by kangarko** [comment]
This is intended. We save this data permanently since new versions. In [ChatControl Red](http://mineacademy.org/chatcontrol-red), you can just install a third party plugin to schedule automatically to run a command `/chc color <player> reset reset` when they join.
