### ISSUE TITLE
1.16.4: Not able to use /chc color menu

### ISSUE THREAD

**Issue by YTMrSnipa** [kangarko/ChatControl-Pro#2223]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

I can't seem to be able to use /chc color menu to customize my colors. Also, it was not saving the color I chose, and would always go back to bold neon. Now, I can't use /chc color at all.

[ChatControl - 21st December 2020.zip](https://github.com/kangarko/ChatControl-Pro/files/5721356/ChatControl.-.21st.December.2020.zip)

**Comment by kangarko** [comment]
Please update to https://github.com/kangarko/ChatControl-Pro/releases/tag/8.9.10
