### ISSUE TITLE
1.16.4: Changing the {player} name color with formatting, depending on their custom permission

### ISSUE THREAD

**Issue by Craven2** [kangarko/ChatControl-Pro#2224]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Hey there, I need to change the color of the player names depending on which permission they were given. I'm using LuckPerms to assign said custom permissions to specific groups, i.e.: staff groups, rank groups, etc.

I've tried adding extra 'First_Part', 'Second_Part' and 'Third_Part' bits with the Sender_Permission attached to the parts of the standard chat format, from which ChatControl could easily choose which parts belonged to which group. (Or so I think..)

The 'First_Part' works flawlessly without any issues, but whenever I try adding a new 'Second_Part' or 'Third_Part' with the Sender_Permission attached, it won't show your username or any of your own chat messages whatsoever, legit a blank line. Ranked users and staff members still retain the correct format, so I'm not quite sure what causes this.

The reason I'm trying to change the username color in the chat is to make it aligned with the player (tab) list, in terms of format. I also tried a quick and dirty solution to this issue before, by simply adding **prefix.0.&7** to the default group, but that sadly leaves the automatic space in front of the usernames.

I may have misread or didn't understand some parts from the documentation, since I simply don't know where the problem lies. Added the config paste below, as well as an in-game screenshot of what it looks like after applying the conf. 

Pastebin: https://pastebin.com/z3SmK2zn

Screenshot: https://i.gyazo.com/8ad56f9ee33480113fbaf916212783c3.png

Note: If I leave out the extra 'Second_Part' bits, everything is a-okay, though without the desired effect as described above.

**Comment by kangarko** [comment]
@ElBananaa can you please look into this?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.4
> MySQL: true
> BungeeCord: true
> 
> Hey there, I need to change the color of the player names depending on which permission they were given. I'm using LuckPerms to assign said custom permissions to specific groups, i.e.: staff groups, rank groups, etc.
> 
> I've tried adding extra 'First_Part', 'Second_Part' and 'Third_Part' bits with the Sender_Permission attached to the parts of the standard chat format, from which ChatControl could easily choose which parts belonged to which group. (Or so I think..)
> 
> The 'First_Part' works flawlessly without any issues, but whenever I try adding a new 'Second_Part' or 'Third_Part' with the Sender_Permission attached, it won't show your username or any of your own chat messages whatsoever, legit a blank line. Ranked users and staff members still retain the correct format, so I'm not quite sure what causes this.
> 
> The reason I'm trying to change the username color in the chat is to make it aligned with the player (tab) list, in terms of format. I also tried a quick and dirty solution to this issue before, by simply adding **prefix.0.&7** to the default group, but that sadly leaves the automatic space in front of the usernames.
> 
> I may have misread or didn't understand some parts from the documentation, since I simply don't know where the problem lies. Added the config paste below, as well as an in-game screenshot of what it looks like after applying the conf.
> 
> Pastebin: https://pastebin.com/z3SmK2zn
> 
> Screenshot: https://i.gyazo.com/8ad56f9ee33480113fbaf916212783c3.png
> 
> Note: If I leave out the extra 'Second_Part' bits, everything is a-okay, though without the desired effect as described above.

Hey! Sorry for the delays! Could you please try to use a different identifier for each part?

**Comment by kangarko** [comment]
Yep, I checked that too and you need to name your parts First_Part First_Part First_Part differently such as First_Part_1 First_Part_2 and First_Part_3.
