### ISSUE TITLE
1.8-1.16: Players able to bypass rules and chat controls by pressing F2 and spamming enter

### ISSUE THREAD

**Issue by JuliCarles** [kangarko/ChatControl-Pro#2227]
Minecraft Version: 1.12.2 (server) also 1.8.8 (server)
MySQL: false
BungeeCord: false
ChatControl version: Latest

As the title says, it seems players are able to bypass the rules.txt and settings.yml controls by pressing F2 (screenshot) and immediately spamming enter with the message they want to send. This allows them to bypass speed controls, Unicode characters controls, etc.

In the video I provide as evidence, you can see how when typing a message normally I can't bypass the repeat rules. However, when pressing F2 and spamming enter, I was able to type 3 messages instantly bypassing the repeat control; the same goes for rules and other controls.

Hope this can get fixed.
Thanks.

https://user-images.githubusercontent.com/15850628/103103554-8c234c80-4600-11eb-8a00-810c06036c5f.mp4

**Comment by kangarko** [comment]
Thank you, this looks like an issue with Paper how they delay the chat event that we receive, I will contact them.

**Comment by kangarko** [comment]
Can you please fill an issue with their team? https://github.com/PaperMC/Paper/issues/new?template=behavior-bug---plugin-incompatibility.md

**Comment by JuliCarles** [comment]
Thanks for the reply, however, if that was the case: how come the chat formatting is still there? "[Usu]", etc.

Shouldn't that be affected as well? Would you mind giving more information into the exact event you think is causing this issue?

**Comment by electronicboy** [comment]
Paper does not change how chat events or packets themselves are processed/dispatched in the server, this would more scream like a concurrency issue in how your limiter works or something

**Comment by kangarko** [comment]
Investigating

**Comment by ElBananaa** [comment]
> Investigating, thanks for replying electronicboy

Hey!
I just tried to reproduce this issue as asked by kangarko on discord, but I couldn't.
Test was made on a completely fresh setup using paper-1618, ChatControlPro v8.9.11, LuckPerms v5.2.35, ProtocolLib v4.5.1 and Vault v1.7.3-b131.

**Comment by JuliCarles** [comment]
Hey there.

I have tried reproducing this with the exact same setup you mentioned and wasn't able to reproduce it with the default ChatControl configuration.
However, when trying the same setup but with the settings and rules we use in our server, I was able to reproduce it. Seems config related, but this shouldn't be happening either way (maybe this is related to the repeat time setting?). Is there any way we can test privately with our configuration to sort out the issue?

**Comment by ElBananaa** [comment]
> Hey there.
> 
> I have tried reproducing this with the exact same setup you mentioned and wasn't able to reproduce it with the default ChatControl configuration.
> However, when trying the same setup but with the settings and rules we use in our server, I was able to reproduce it. Seems config related, but this shouldn't be happening either way (maybe this is related to the repeat time setting?). Is there any way we can test privately with our configuration to sort out the issue?

Hey,
Happy New Year!

Thanks for your answer.
If you don't mind, you could send me your chatcontrol configurations on discord: Bananaa#1471
I'll see if I can try to reproduce your issue. Of course, don't forget to remove any sensitive informations.

**Comment by kangarko** [comment]
@JuliCarles please paste your ZIP of your folder as Banana suggested, I can trace it down to the individual config option. You can use uploadfiles.io and send it privately over to matej@mineacademy.org

**Comment by JuliCarles** [comment]
@kangarko They were sent to the email address you provided. Thanks.

**Comment by kangarko** [comment]
Received, thanks!

**Comment by kangarko** [comment]
Continued via email
