### ISSUE TITLE
Im trying to use Item2Chat plugin, and is not working.

### ISSUE THREAD

**Issue by JorgeSilvarredonda** [kangarko/ChatControl-Pro#2228]
When typing [itemtochat] or {item} no item is linked to chat.
http://prntscr.com/w9kglp

**Comment by JorgeSilvarredonda** [comment]
I figured out that When Chat formatting is turned On, doesnt work, and when turning off Chat formatting, the plugin of item2chat is working fine

**Comment by kangarko** [comment]
I apology, this plugin is incompatible with our formatting system.

**Comment by JorgeSilvarredonda** [comment]
Am ok, which one i can use? Bcs i didnt understand how to use the integrated variable

**Comment by kangarko** [comment]
ChatControl Pro doesn't have such a system. This system was introduced in https://github.com/kangarko/ChatControl-Red

**Comment by JorgeSilvarredonda** [comment]
Bought it! 👍
