### ISSUE TITLE
1.8.9: Plugin dont start

### ISSUE THREAD

**Issue by thefrogline** [kangarko/ChatControl-Pro#2229]
Hello, I have a problem with the plugin, what happens is that I have all the dependencies and when I want to start it it tells me that I need jdk 8, and I have it installed and it throws me this error in the files, I did not touch the settings or anything
![image](https://user-images.githubusercontent.com/76601496/103143084-d2021280-46dd-11eb-9414-78f26c799545.png)
![image](https://user-images.githubusercontent.com/76601496/103143085-e514e280-46dd-11eb-8d70-c0dd1c42813a.png)
Thanks for reading and I hope there is a solution, I suppose that I am doing something wrong since I did not find the error in other pages

Minecraft Version: 1.8.9
MySQL: false
BungeeCord: false

**Comment by kangarko** [comment]
Install Java 11 or Java 14. Java 15 is not supported yet.
