### ISSUE TITLE
Minecraft 1.12-pre2

### ISSUE THREAD

**Issue by TheChampTF** [kangarko/ChatControl-Pro#223]
Hey

On latest version (Pre version released from Spigot) http://paste.yu8.me/?e86eb962f2024f2d#2QmtRm/IMrI9Tn11gaNahAaAwUx71MTMPd9LIS1aPjk=

Just giving you a heads up before 1.12 is released

**Comment by kangarko** [comment]
Thanks, fixed. New version will be available tonight.
