### ISSUE TITLE
/pvp command not working

### ISSUE THREAD

**Issue by JasmineWMCM** [kangarko/ChatControl-Pro#2231]
I own a server and I have the plugin PvPManager and Chatcontrol Red blocks it and makes it say "unknown command"

**Comment by kangarko** [comment]
Open files in rules/  and check if there's a command that's blocking it, if so remove it. If it's not there then see settings.yml. You will find something that you need toggle off, I can' tell what that is since that appears not to be with the default settings.

**Comment by JasmineWMCM** [comment]
Still issues persist. No commands are blocking. Nothing settings. Please help. Thanks <3

**Comment by kangarko** [comment]
Will reply in the other tickethttps://github.com/kangarko/ChatControl-Red/issues/475
