### ISSUE TITLE
1.16.4: Admin chat and message toggle automatically on

### ISSUE THREAD

**Issue by M0diis** [kangarko/ChatControl-Pro#2234]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Plugin version:  8.8.20

Having message toggle (receiving messages - off) and admin chat automatically toggled on on log-in.
Not sure if this is a bug or permission issue.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5766918/ChatControl.zip)

**Comment by kangarko** [comment]
There's no way to turn these on automatically in Pro as far as I'm concerned, sorry
