### ISSUE TITLE
minecraft 1.12.2 : ChatControl-Red-10.1.11 didn't support localization of "cn"

### ISSUE THREAD

**Issue by martin1194** [kangarko/ChatControl-Pro#2235]
Error: Report: ChatControlRed does not support the localization: messages_cn.yml (For custom locale, set the Locale to 'en' and edit your English file instead)

It seen can't support cn?

![image](https://user-images.githubusercontent.com/18354205/103768582-1e4a3c80-5066-11eb-855d-b32e8f00dc69.png)

**Comment by kangarko** [comment]
We don't have Chinese localization in ChatControl Red yet. You're free to customize the English one and send your translation when you create it!
