### ISSUE TITLE
1.16.4: High amounts of lag

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Pro#2236]
https://screenshots.skizzles.me/wAnA3/NETewiPE32.png

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Per timings ChatControlPro is causing high amounts of lag.

**Comment by itaquito** [comment]
I can confirm this, here is a screenshot of my timings
![image](https://user-images.githubusercontent.com/30180886/103934303-601cc680-50ea-11eb-8496-4c6d19c080e0.png)

**Comment by kangarko** [comment]
ChatControl Pro is performing mysql save operations on the main thread, this has been resolved by rewritting the entire handling in ChatControl Red.

**Comment by kangarko** [comment]
Not suggesting you must purchase to get this fixed, just saying that we've rebuilt the paradigm from the ground up to make async db calls. In Pro it works on the main thread so it will necessarily cause drains if mysql is on or you have a large data.db file.

**Comment by Skizzles** [comment]
No offense @kangarko but I highly dislike having to re-purchase for the updates. This is pretty bad for lag.... I can't warrant repurchasing a plugin and have to fix all the issues with migrating.

**Comment by itaquito** [comment]
After doing a heapdump. I can see that MySQL is consuming an insane amount of RAM. 
![image](https://user-images.githubusercontent.com/30180886/104270816-0c4e0c80-545f-11eb-83bf-952c821dcd97.png)

**Comment by kangarko** [comment]
I understand, I will give you a free license so you can see if Red has improved performance over your setup. Apply through mineacademy.org/chatcontrol-red and I'll approve both of you. Just put your old transaction ID for ChatControl Pro there.
