### ISSUE TITLE
1.16.4:Rule not working

### ISSUE THREAD

**Issue by JHiroshige** [kangarko/ChatControl-Pro#2237]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

So I added a new rule with /chc addrule --> @everyone
Since DiscordSRV doesent block pings from the mc chat I thought I could try it with this plugin. But players can still type @everyone.
![image](https://user-images.githubusercontent.com/67478052/104077635-dd475900-521a-11eb-9771-8d36b98bb926.png)

I've tested it with an account which doesen't have a bypass

**Comment by kangarko** [comment]
Change the whole match to

```
match \@everyone
handle as swear
```
