### ISSUE TITLE
7.3.14 Points are not added up

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#224]
the points system seems to be broken. 2 issues:

example 1:
A new player swears and gets 2 points Set Player's 'swear' points from 0 -> 2
He swears again and gets 2 points Set Player's 'swear' points from 0 -> 2
He swears for the 3th time and gets 2 points Set Player's 'swear' points from 0 -> 2

example2:
Player reaches 28 points:
3 actions are taken:
6 points -> mute 10m
12 points -> mute 20m
18 points -> skips this action
24 points -> mute 45m
This level of 28 points is not associated with any action at all. But nevertheless, it should not take 3 actions.

Greetings x1p

**Comment by kangarko** [comment]
PM'd. Thank you for taking time to create an account here. We can continue your old dialog at the forums, and if you have new issues next time feel free to post here, or just PM me.
