### ISSUE TITLE
1.16.4: MOTD messed up

### ISSUE THREAD

**Issue by ElTodoFull** [kangarko/ChatControl-Pro#2240]
Minecraft Version: 1.16.4
MySQL: false
BungeeCord: false

Installed the plugin like any other and now the motd is all messed up.
I tried to look for a config that changed the motd but found nothing, apart from one in settings.yml, but seems to be a welcome message and is false by default.
I have no other plugins that affect the motd, I use vanilla server.properties
![motd fail](https://user-images.githubusercontent.com/22697982/104608460-aaf58b80-5660-11eb-8351-bd0d61ccad43.png)

As an extra, Rank-prefix RGB colors worked well after removing the "&"s, but
I can't write in chat RGB colors, not with &# nor with #. I try mayus and lower-case #FF0000 or &#00ff00 and those combinations and nothing, it shows what I write.

**Comment by kangarko** [comment]
That looks like an encoding issue, refer to https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding and make sure you saved your server.properties in the proper format.

Send it to me using pastebin.com and I will check it for you. Also try fixing it back and seeing if it gets corrupted again. Just comment below.
