### ISSUE TITLE
1.16.4:Join Messages not Showing

### ISSUE THREAD

**Issue by JHiroshige** [kangarko/ChatControl-Pro#2241]
So today I realised that players dont get any join messages anymore but there are still leave messages. I havent touched the messsages.yml in a while and it worked perfectly fine. I recently added perms for me so I dont get any join messgaes anymore but this shouldnt have a impact on other players. I checked their perms, even gave them this perm "chatcontrol.messages.join" value: true and its still not working. Any Idea why?

**Comment by Incoconut** [comment]
Im having this issue 1.17.1

**Comment by kangarko** [comment]
@Incoconut ensure players got the right permission, there is no errors in the console, and that no other plugin is interfering
