### ISSUE TITLE
ChatControlPro Tab_Complete

### ISSUE THREAD

**Issue by Dima1Statham** [kangarko/ChatControl-Pro#2242]
Hello, I set the value to Tab-Complete: true. But now I have absolutely unnecessary commands in Tab_Complete, can I edit them? For example add / menu

**Comment by kangarko** [comment]
No sorry, the tab-complete feature is severely limited in ChatControl Pro and it's been this way since 2015. We've improved it in ChatControl Red when we rewrote everything about the plugin, you can learn more about it at mineacademy.org/chatcontrol-red
