### ISSUE TITLE
Admin Chat - /ac - /ach

### ISSUE THREAD

**Issue by OnKava** [kangarko/ChatControl-Pro#2243]
Hi, Just Non-Priority Question,
1) Do you have some way to show visually you have admin chat On/Off
2) If not I think that's not a bad idea, you can make it as Placeholder, or as Bossbar/Action Ban
 Just I, and I hope I am not one, many times accidentally write in bad chat, in result, leak some info/plan, or just took longer to answer to player Question
3) We run on 1.16.3

Just Thanks

**Comment by kangarko** [comment]
Thanks, however we're not open to ChatControl Pro suggestions any more.
