### ISSUE TITLE
1.12.2: Antispam often blocks messages in Russian.

### ISSUE THREAD

**Issue by MaxIsV** [kangarko/ChatControl-Pro#2245]
Minecraft Version: 1.12.2
MySQL: false
BungeeCord: false

Hello, I ran into a problem that almost any messages in Russian are blocked by a plugin, a request appears not to repeat the same or similar messages. While for messages in English, it is enough to add one letter and it will not be blocked. I tested this on completely default plugin settings.

Video: https://imgur.com/L23rRJr
ChatControl-8.9.12

**Comment by milutinke** [comment]
The plugin also counts some words written in Serbian Cyrillic as curse words while they are not, and long sentences too.
This needs to be fixed.

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#rules-dont-work-for-my-non-english-server---i-use-cyrillic--special-characters-but-they-are-not-matched
