### ISSUE TITLE
Command for profanity filter

### ISSUE THREAD

**Issue by IPv5** [kangarko/ChatControl-Pro#2247]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
Allow players to filter profanity when they don't want to see it, and allow other players to not filter profanity when they don't mind.
2) What would happen if we won't implement this feature? How's your server being affected?
Would require the server to be fully filtered.
3) If suggesting something new - Can the old system be modified/improved instead?
Possibly

A command for players to enable/disable the profanity filter.

**Comment by kangarko** [comment]
We're no longer accepting suggestions to ChatControl Pro
