### ISSUE TITLE
1.16.4 [Group channels problem]

### ISSUE THREAD

**Issue by FourKingdoms** [kangarko/ChatControl-Pro#2248]
<!---
To ask us anything, please follow these directions:

1) Please include your Minecraft version in your title:
Example: 1.16.4: **How to setup the groups with global chat as well?**

So I installed the plugin i can make channels and everything. But now i can show u a example.
There are 4 kingdoms:
Crania
Lewindor
Thralia
Edolian.
And then i want a global channel with ! but that doesnt work at all.

Secondly when I am in lewindor and i switch to a channel called global i cannot see the channel lewindor anymore. it doesnt switch to read lewindor while i am typing in global.

**Comment by kangarko** [comment]
No description = I cannot help
