### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by FourKingdoms** [kangarko/ChatControl-Pro#2249]
1) Please include your Minecraft version in your title:
Example: 1.16.4: **How to setup the groups with global chat as well?**

So I installed the plugin i can make channels and everything. But now i can show u a example.
There are 4 kingdoms:
Crania
Lewindor
Thralia
Edolian.
And then i want a global channel with ! but that doesnt work at all.

Secondly when I am in lewindor and i switch to a channel called global i cannot see the channel lewindor anymore. it doesnt switch to read lewindor while i am typing in global.

**Comment by kangarko** [comment]
Hey!

These things were addressed in ChatControl Red, I understand it's frustrating and I don't want to force you to pay so just email me at matej@mineacademy.org with your MCMarket username and I figure something out for you.
