### ISSUE TITLE
Channel permissions issue when player changes minecraft username

### ISSUE THREAD

**Issue by calamityy** [kangarko/ChatControl-Pro#2250]
Whenever a player who has previously played on the server (with no prior issues accessing channels) changes their minecraft username, it causes them to lose permissions to join any channel other than global (the main issue with this is that they cannot join the local plot chat channel).

Permission missing when they do `/ch j local` is `chatcontrol.channel.join.others`, which is the permission to join another person to a channel, which unless I'm mistaken, is an admin permission?

Any help would be much appreciated, thanks :)
If you need any more information, I'm happy to give more.
I'm using ChatControlRed.

EDIT: A server restart fixed the issue, however I'm guessing it's still a problem, since this would mean we are required to restart the server each time a player changes their username.

Error:
![image](https://user-images.githubusercontent.com/65677257/105892840-4cd68a00-600a-11eb-9c34-5f708648eba1.png)

**Comment by kangarko** [comment]
Will likely get patched, if not please follow up here: https://github.com/kangarko/ChatControl-Red/issues/548
