### ISSUE TITLE
1.16.5: Enable but doesn't work

### ISSUE THREAD

**Issue by LordSiix** [kangarko/ChatControl-Pro#2251]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

My ChatControl enable but doesn't do nothing, y try with 1.9.11 and 1.9.12
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5877836/ChatControl.zip)

**Comment by kangarko** [comment]
What's your startup console log?

**Comment by LordSiix** [comment]
[latest.log](https://github.com/kangarko/ChatControl-Pro/files/5883422/latest.log)

**Comment by LordSiix** [comment]
I saw the real problem, the plugin works but only the half of that, the plugin doesn't change me the prefix type, or the toolstrip when i pass the mouse on the message of someone

**Comment by LordSiix** [comment]
[SOLVED]
1.- i don't see all the things bcouse i bypass all
2.- i don't see the format in the chat bcause when i update, the formate turn enable to : false
