### ISSUE TITLE
ChatControlRed questions regarding chat filter and channel spy

### ISSUE THREAD

**Issue by calamityy** [kangarko/ChatControl-Pro#2252]
I've looked for support for ChatControlRed, and it seems the only way is to use GitHub, apologies if this is wrong place to ask- I've done as much research beforehand as I can. Running CHCRed ver. 10.1.15

**_1st question:_ Whitelisting certain unicode characters from the preset (not english) unicode filter**
I'm having trouble with formatting the `ignore` operator in _ChatControlRed/rules/chat.rs_ to ignore a select few of unicode symbols, associated with the apostrophe. I've tried doing:

> match [^\u0000-\u007F]+  
ignore string [u0027]|[u2019]|[u2018]|[u0060]
then warn {prefix_error}Unicode characters are prohibited.  
then deny

and also

>match [^\u0000-\u007F]+
ignore `‘’'
then warn {prefix_error}Unicode characters are prohibited.
then deny

neither seem to work- they either don't let all the symbols through the filter, or when booting the server, gives this error: 
>Error: Report: Unrecognized operator 'ignore string [u0027]|[u2019]|[u2018]|[u0060]' found in Rule {
>.... [11:30:05 INFO]: 'Type' = 'chat'
>.... [11:30:05 INFO]: 'Match' = '[^\u0000-\u007F]+'
>.... [11:30:05 INFO]: }
>.... [11:30:05 INFO]: !-----------------------------------------------------!

I've tried using `string` and `strings`, and using the wiki page on rules to help me. I'm guessing I'm just using the format incorrectly.
I'm happy to give more info if you require it.

**_2nd question:_ Disabling spy on global channel but not messages**
I've also encountered an issue where using `/spy toggle chat global` means anything sent from another server (running a creative and survival server connected by bungee) in global chat (which I can see without spy) is duplicated, as it is displayed when using spy, too:
![image](https://user-images.githubusercontent.com/65677257/106023868-1eff4d00-60bf-11eb-9948-61681d2e3bd0.png)
(Screenshot taken from creative, user zmba is on survival, talking in global chat.) I've looked in the config, and I can't find a way to prevent this from happening.

Any help will be greatly appreciated, thanks :)

**Comment by kangarko** [comment]
This channel is for Pro, for Red issues post here: https://github.com/kangarko/ChatControl-Red
