### ISSUE TITLE
1.16.5 Tunity: Chatcontrol Crash my Mysql Database

### ISSUE THREAD

**Issue by Timoisvergeben** [kangarko/ChatControl-Pro#2253]
Hey, when I start a server, everything is fine until chatcontrol tries to connect to mysql, then the mysql database crashes, the mysql data is correct besides to be sure I let chatcontrol start without mysql and the database did not crash. Sorry if I do something wrong am new to Github LG Timo.

Minecraft Version: 1.16.5 Tunity
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Please post me the crash log....

**Comment by Timoisvergeben** [comment]
https://prnt.sc/ynrsd9

**Comment by kangarko** [comment]
This doesn't look like an issue on our end, I recommend contacting your hosting or resetting your database. Also see the header of MySQL to ensure you have the right driver and encoding.

**Comment by Timoisvergeben** [comment]
ok thanks
