### ISSUE TITLE
RGB chat

### ISSUE THREAD

**Issue by Danielpeter-99** [kangarko/ChatControl-Pro#2255]
How could I have players talk using RGB colors?

I believe it is not possible yet.

Also, I have filled out the Pro -> Red, would love to try it out and become a beta tester for future features but haven't gotten a reply.

**Comment by kangarko** [comment]
Thanks, I believe to have accepted you now. Red has support for that if you give players the right permissions which is described in Colors section in settings.yml

**Comment by Danielpeter-99** [comment]
Im sorry but I have checked all my emails and have found nothing about chatcontrol red.

Would love to give it a go.

**Comment by Danielpeter-99** [comment]
> Thanks, I believe to have accepted you now. Red has support for that if you give players the right permissions which is described in Colors section in settings.yml

Im sorry but I have checked all my emails and have found nothing about chatcontrol red.

Would love to give it a go.
