### ISSUE TITLE
1.16.4: Placeholders with DiscordSRV

### ISSUE THREAD

**Issue by TheBlazingFlames** [kangarko/ChatControl-Pro#2256]
Hi,

I'm trying to use Placeholders in my KitPvP chat to show player's levels. I've managed to get the placeholders to work but they also seem to affect DiscordSRV chat.

I'm wondering if there's a way to make it so that the DiscordSRV chat isn't affected by prefixes/suffixes as Discord users can't have them anyways?

![Chat](https://user-images.githubusercontent.com/76907781/107285315-dd738800-6a56-11eb-9169-0e37d750901b.png)

This is my current formatting:
`  prefix:
    Message: '&8(&9Lvl {kitpvp_stats_level}&8)&r {player_prefix+}'`

Thank you.

**Comment by kangarko** [comment]
I apology, right now we can't support these when coming from Discord. I recommend you set up an alternative Discord format without these when a message comes from Discord.
