### ISSUE TITLE
Tab Complete

### ISSUE THREAD

**Issue by tptuaasn** [kangarko/ChatControl-Pro#2258]
i get this error when player use tabcomplete
https://pastebin.com/w4ipqZw2

Minecraft Version: 1.16.5

**Comment by kangarko** [comment]
You're using outdated or unsupported ProtocolLib

**Comment by tptuaasn** [comment]
i use lastest dev build protocolib and lastest release build chatcontrol pro

**Comment by kangarko** [comment]
Still, even when using latest (not lastest) yields this, it is an error in ProtocolLib, contact their team.
