### ISSUE TITLE
1.16.5: Chatcontrol Pro Log Chat Not Working

### ISSUE THREAD

**Issue by Fakhri1999** [kangarko/ChatControl-Pro#2259]
I used chat control free a month ago, and the chat log is working. Then I changed to the pro version because it is free, but the chat log is not working anymore. I check in the config of the pro version and I can't found any option to enable the chat log, while in the config of the free version there is an option to enable the chat log.

**Comment by kangarko** [comment]
Please ZIP me your ChatControl folder (except mysql logins) and I will have a look.

**Comment by Fakhri1999** [comment]
where should I send the zip file?

**Comment by kangarko** [comment]
Drag and drop it here

**Comment by Fakhri1999** [comment]
[chatcontrol-folder.tar.gz](https://github.com/kangarko/ChatControl-Pro/files/6060467/chatcontrol-folder.tar.gz)

**Comment by kangarko** [comment]
Set Writer.Enabled to true to enable the chat log for Pro :)
