### ISSUE TITLE
Prevent multiple death messages from a player in X minutes

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#226]
Heya,

Some people like to spam their deaths a lot by going to the nether and anger a zombie pigman, or to fall into the void on skyblock. So I was thinking, could there be a feature that prevents multiple deathmessages from the same person in "X" minutes?

I hope what I have requested is possible 👍

**Comment by kangarko** [comment]
Great suggestion and yes, totally possible (there's already a similar feature in Sound_Notify preventing spamming tagging players)! I am totally down to adding this in the near future :)

**Comment by FrankHeijden** [comment]
Thank you so much :)

**Comment by kangarko** [comment]
No problem. I have exams right now so please mind a little delay :)

**Comment by FrankHeijden** [comment]
Good luck with your exams, I'll stop messaging because thats more distraction xD

**Comment by kangarko** [comment]
Thanks!

**Comment by kangarko** [comment]
Addressed in https://github.com/kangarko/ChatControl-Pro/issues/343
