### ISSUE TITLE
How to clear BungeeChat? Minecraft Version: 1.16.5, BungeeCord 1.16-R0.5

### ISSUE THREAD

**Issue by Kolgrath** [kangarko/ChatControl-Pro#2261]
I see **/chc clear** will clear the chat of the server I'm on.
What is the command to clear chat across all BungeeCord connected ChatControl servers?

**Comment by kangarko** [comment]
ChatControl Pro did not come with BungeeCord-wide chat cleaning when we made it in 2015, so there's no option for that sorry. We do have support for this over ChatControl Red which was released in December 2020.
