### ISSUE TITLE
1.16.5 Chatcontrolred /nick

### ISSUE THREAD

**Issue by TenReeez** [kangarko/ChatControl-Pro#2263]
Hey. 
 I cant work out how players can nick themselves in main chat. I have worked out how players nick themselves in msgs. But i have followed the same format for main chat ( i think) and i cant for the life of me with my limited abilities work out nick in main chat. ( I have tried for a week now :/)

Sorry to bother you i know your busy

thankyou.

**Comment by kangarko** [comment]
I unfortunately see this as a missing feature to Pro where we don't support /nick feature natively nor make them possible to be used in private messages. We've completely redone the plugin from the ground up in Red and so should you consider enrolling there you'll get this feature.

**Comment by TenReeez** [comment]
hey i must of posted this in the wrong plugin, I have purchased red, and
have asked for support there.

sorry
