### ISSUE TITLE
1.16.5: i can get the source code?

### ISSUE THREAD

**Issue by VasilModerator** [kangarko/ChatControl-Pro#2264]
Hello Matej Pacan, I can please get the source code of your java ChatControl Pro plugin for the Minecraft server so that I can edit it for myself, because decompiling the plugin through utilities such as jd-gui and luyten only spoil the source code when extracting it, and from this code there is only the rest of this code with which almost nothing can be done, and I'm just starting to learn the java programming language, and on your github source code is unfortunately not even more freely available, so I'll be very grateful to you for that if possible you give me the source code of this plugin, because I once bought it on the forum spigotmc.org for 9.90 euros

**Comment by kangarko** [comment]
For the time being you can access the source code to ChatControl Free at https://github.com/kangarko/ChatControl-Free
