### ISSUE TITLE
Profile issues

### ISSUE THREAD

**Issue by 2580crq** [kangarko/ChatControl-Pro#2265]
When I try to send a private chat message to myself, the pop-up message cannot be changed in the configuration file. Please solve this problem. Thank you.

**Comment by 2580crq** [comment]
![image](https://user-images.githubusercontent.com/60396495/110207164-a741f080-7ebc-11eb-8dac-7b6e7e572a4e.png)
This message cannot be changed.

**Comment by kangarko** [comment]
This message is not found in ChatControl Pro.
