### ISSUE TITLE
BungeeCord

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl-Pro#2266]
Hi,

How to put BungeeChat as the default chat ?
Moreover when I do /chc bungeechat it says that Bungee Chat is disabled whereas I have enabled it.

Best regards.

**Comment by kangarko** [comment]
We found we had too many issues with this so we have depreciated this feature. I believe it should still work tho, check your config...

You can turn on chat channels and only have one chat channel active where you enable Bungee mode for that channel.
