### ISSUE TITLE
1.16.5: How to cancel checking messages via the API

### ISSUE THREAD

**Issue by Kiteflow** [kangarko/ChatControl-Pro#2267]
Hello,
I'm currently using a custom chat plugin, and am wondering whether it's possible to cancel checking messages via the API? 
I'm currently checking them with the API, but for certain things (Advertisements) it's checking them twice.

Thanks

**Comment by kangarko** [comment]
Yes, there is PreRuleMatchEvent that is fired to check rules, you can listen to that and cancel it

**Comment by Kiteflow** [comment]
Sorry for reopening this but this also seems to cancel checking messages via the API.
Is there a way to block the plugin checking them but also manually checking them?

**Comment by kangarko** [comment]
You can manually check the message using
ChatControlAPI#checkMessage

**Comment by Kiteflow** [comment]
This also appears to fire the prerulematchevent though

**Comment by kangarko** [comment]
Yeah that's intended behavior.

**Comment by Kiteflow** [comment]
Is there anyway to stop it, as I am trying to only check messages via the API. Or is it impossible

**Comment by kangarko** [comment]
Not right now sorry, but you could set the player an invisible metadata and then ignore said event if the metadata are present.

**Comment by kangarko** [comment]
make sure to remove them right after the method
