### ISSUE TITLE
1.12.2: Doesn't work with advanced ban

### ISSUE THREAD

**Issue by xYouPvP** [kangarko/ChatControl-Pro#2268]
Hello, I am using the advancedban plugin for penalties. However, the user can write to the chat even though I have a silencing penalty with the advancedban plugin.

**Comment by kangarko** [comment]
This is because of a priority issue, we don't support that plugin, however as last resort you can try this advice: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
