### ISSUE TITLE
ChatControl stability error

### ISSUE THREAD

**Issue by Tyloon1e** [kangarko/ChatControl-Pro#2269]
Since the plugin is still in a maintenance mode, I'd report the following bug when using /kick with Essentials to kick someone:

> 12.03 13:38:25 [Server] INFO Tyloon1e issued server command: /ekick SuperBrugsen
12.03 13:38:25 [Server] ERROR Could not pass event PlayerKickEvent to ChatControl v8.9.10
12.03 13:38:25 [Server] INFO java.lang.NullPointerException: null
12.03 13:38:25 [Server] INFO at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:211) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:122) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.mineacademy.chatcontrol.listener.ListenerPlayer.onKick(ListenerPlayer.java:295) ~[?:?]
12.03 13:38:25 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor197.execute(Unknown Source) ~[?:?]
12.03 13:38:25 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:299) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:281) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:493) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at com.earth2me.essentials.commands.Commandkick.run(Commandkick.java:51) ~[?:?]
12.03 13:38:25 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:202) ~[?:?]
12.03 13:38:25 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:197) ~[?:?]
12.03 13:38:25 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:693) ~[?:?]
12.03 13:38:25 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:600) ~[?:?]
12.03 13:38:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2093) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1908) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1861) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1199) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1168) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.5.jar:git-Tuinity-"c303521"]
12.03 13:38:25 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by kangarko** [comment]
Thanks, will suppress this. If you want this solved properly you need to contact the PaperSpigot dev team.
