### ISSUE TITLE
1.12.2: Bungee chat not working

### ISSUE THREAD

**Issue by nicklly** [kangarko/ChatControl-Pro#2270]
Hello. is same as https://github.com/kangarko/ChatControl-Pro/issues/2094
Using BungeeCord + Redis

https://pastebin.com/y9GFp5sn

is already install RedisBungee and BungeeControl  
is already stop work Bungee_Chat

that is my ChatControl settings.yml https://pastebin.com/Wq1w5AF0

**Comment by kangarko** [comment]
Cannot reproduce, try the reuploaded version:

![a](https://i.imgur.com/wRxNXye.png)

If this is caused by Redis we unfortunately do not provide updates for that integration.

**Comment by kangarko** [comment]
I will reupload the next version later today, thank you.

**Comment by nicklly** [comment]
Still getting an error, I reinstalled redis and all plugins, but it didn’t work

**Comment by nicklly** [comment]
isn't caused by Redis.This problem only occurs after I installed redisbungee and enabled redis, I don’t know what to do, I need your help

**Comment by nicklly** [comment]
the BungeeContrl is hook redisbungee, But I don’t know why the spigot server cannot receive the chat messages forwarded by bungee

**Comment by kangarko** [comment]
I apology, I am not the developer of the part of the code responsible for the Redis integration, I am unavailable to provide a fix for Redis and global chat at the moment.
