### ISSUE TITLE
1.16.5 Change the Private Message format? 

### ISSUE THREAD

**Issue by FATGUY46** [kangarko/ChatControl-Pro#2271]
Hey is it possible to change the format for private messages? I'm looking for a more straightforward messaging system, ex: 
[Bob -> You: Hi]
[You -> Bob: Hello]

Not that there's anything wrong with this default one: 
![image](https://user-images.githubusercontent.com/40724602/113497515-9b047f80-94ca-11eb-9713-e577e50c59cf.png)

I just don't prefer it. Thanks 👍

**Comment by kangarko** [comment]
You can just edit the outlook in formatting.yml file.
