### ISSUE TITLE
1.8.8 //  /chc addrule error.

### ISSUE THREAD

**Issue by Konzol47** [kangarko/ChatControl-Pro#2274]
Minecraft Version: 1.8.8
MySQL: false
BungeeCord: false

After reaching a certain amount of handlers, trying to use `/chc addrule` will get you kicked, whereas normally two messages should pop up, first one being, "Usage: /chc addrule \<handler>" and the other one being the "Available handlers: ..." message / list.

Client side message that pops up: [Image](https://i.imgur.com/0qTbJ3E.png)
Console side message that pops up: [Pastebin](https://pastebin.com/HDtUR7Lh)

YSK that this was tested in an environment with no other plugins present besides ChatControl Pro v8.10.3, and that every setting / file is default, excluding anything mentioned below.

[Complete ChatControl folder](https://github.com/kangarko/ChatControl-Pro/files/6381720/ChatControl.zip)

Steps to reproduce:

1. Remove everything in `handlers.yml` besides the `swear` handler.
2. Copy the swear handler, and paste it properly 18 times, for a total of **19** handlers.
3. Rename the handlers in a numerical order, or any other way, as long as they're not identical by name. [Example, also what I'm using.](https://pastebin.com/WSY5dxuq)
4. Due to editing the default handlers, `rules.txt` has to have all its contents erased, more specifically, has to not have any `handle as` line pointing to other handlers. Simply leave it empty.
5. Grant yourself ability to run `/chc addrule`, and simply try to run it.

**Comment by kangarko** [comment]
Thanks so much for sharing, looks like some odd bug I haven't noticed before. We're on bug-fix only but I'll do my best to investigate and fix this within a few days.

**Comment by kangarko** [comment]
Thanks, too many handlers, Minecraft overflows. I've made it turn into a warning message so you see the handlers but without their hover effect.
