### ISSUE TITLE
Pay for global chat

### ISSUE THREAD

**Issue by Demonas** [kangarko/ChatControl-Pro#2275]
Hi , i enabled ranged mode it works fine but i want to make that players need to pay to use global chat 
example 
Player types ! Hello world
Player will pay 150

**Comment by M0diis** [comment]
Read rules.txt

There is an option to "fine" a player for something.

You can simply check if the message starts with "!" and make sure they have appropriate permission with require perm.
# match ^!\w+ # this is just a regex to match if the start of the message starts with a "!" and words after.
# then fine <amount> (If plugin Vault is installed - take specified amount of money from the player.)
# require perm <permission> [message] (Only execute the rule if the player has specified permission.

**Comment by kangarko** [comment]
Thanks to M0diis for an excellent tip — I think that's the closest you can get for this without the need for a developer to make an extension for our plugin!

**Comment by MrBrights** [comment]
I happened to be studying this problem for a long time
But I found that when the player has no money, he can still speak normally
Is there any way to solve this problem?
I was wondering whether it is possible to add a matching placeholder or a character that requires money?

**Comment by kangarko** [comment]
No sorry I am afraid you would need a custom development works for this or I am unsure of a way going forward with this.

**Comment by kangarko** [comment]
We are no longer shipping feature updates to ChatControl Pro

**Comment by M0diis** [comment]
> We are no longer shipping feature updates to ChatControl Pro

Any plans on making it Open-Sourced/Community maintained?

**Comment by kangarko** [comment]
Not right now, we already made tons of our other plugins open source.
