### ISSUE TITLE
1.16.4 How I can setup range chat in only one world

### ISSUE THREAD

**Issue by EdyMeleon** [kangarko/ChatControl-Pro#2277]
How I can setup range chat in only one world?

**Comment by kangarko** [comment]
You can use chat channels for that. Your main chat channel can have no range and then you can have a special channel with a range and even linked worlds together.

**Comment by EdyMeleon** [comment]
And how I can do that?

**Comment by kangarko** [comment]
By enabling the channel functionality and following through https://github.com/kangarko/ChatControl-Pro/wiki/Channels especially: https://github.com/kangarko/ChatControl-Pro/wiki/Channels#range
