### ISSUE TITLE
Packet Permissions (pt. 2)

### ISSUE THREAD

**Issue by skylerberry** [kangarko/ChatControl-Pro#228]
Using "ignore perm (perm)" does not work in packets.txt, as when reloading the plugin I get the error of: http://prntscr.com/f928q0

Config section:

match ^DeluxeMenus*
ignore perm chc.dm
then deny

Again, this is in my packets.txt, not rules.txt file.

ALSO, another question:

Is it possible to replace multiple lines into one line? Example: Executing command /dm displays two multiple lines of text in chat "DeluxeMenus version\nCreated by extended_clip", and I would like to replace both of them into one line of text to be displayed in chat with a custom message such as "No permission".

**Comment by kangarko** [comment]
Hey,

sorry for the delay. I cannot reproduce, all the major operators work on packet rules as well. Ensure you're on the latest ChatControl Pro version.

It is possible to catch those two lines by making two rules, where only the second rule would print a warning message to the player.

Please comment below if you have any more questions.
