### ISSUE TITLE
1.16.5: Console error in player kick event

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#2281]
I use ForceResourcePack plugin. When a player delices the resource pack, we kick him, with a multi-line LiteBans kick message.
But when the player got kicked an error occours in ChatControl 

https://pastebin.com/ZPF5FgY4

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/6417528/ChatControl.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Update chatcontrol https://github.com/kangarko/ChatControl-Pro/releases/tag/8.10.4
