### ISSUE TITLE
1.16.5 - Thread dump when switching servers

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#2285]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Noticed server dumps when a player switches from one server to another. In the paste is the first server he leaves from, and then the second server he joins to. 

https://pastebin.com/wySGZStv

**Comment by kangarko** [comment]
Please update to me your data.db

**Comment by kangarko** [comment]
Clear your data.db, it probably got too large or corruptd
