### ISSUE TITLE
1.16.5: packets not always working

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#2288]
[chatcontrol.zip](https://github.com/kangarko/ChatControl-Pro/files/6485642/chatcontrol.zip)
Minecraft Version: 1.16.5
Chatcontrol: 8.10.4
MySQL: true
BungeeCord: false

I have a problem with the packets.txt inside the rules folder. The hard part is: I actually don't know what's the problem. It looks like a random stuff. The packets randomly not working for me. I noticed this problem almost always on my main, operator account, but the permission negate isn't working. After deop, permission and parent group clean the packets still not working.
No visible error in console, or anywhere.
What am i doing wrong?
I negated theese:

![image](https://user-images.githubusercontent.com/13710574/118359129-47ce2400-b582-11eb-800f-7db081bf214b.png)

**Comment by download042** [comment]
theese are negated too:
![image](https://user-images.githubusercontent.com/13710574/118359175-94196400-b582-11eb-854c-02c5b852e721.png)

**Comment by kangarko** [comment]
I can't tell for sure but it seems like an issue with ProtocolLib, or even with messages themselves how they are packed. If you use ViaVersion or any other packet-related plugin then unfortunately it's unsupported.
