### ISSUE TITLE
"Error loading ChatControl v8.10.5, plugin is disabled!"

### ISSUE THREAD

**Issue by yourlocalvirgo** [kangarko/ChatControl-Pro#2289]
Hiya! I'm having a problem with ChatControl that I can't pinpoint.

I've installed the latest version (uploaded 6 days ago, I believe), and configured the rules.txt, settings.yml, and handlers.yml files to my liking. However, when re-starting my server, I get the error that the plugin is disabled, and that the handler "advertisement" doesn't exist (even though it's built-in to the handlers.yml file and I didn't change it whatsoever)

Any guidance would be greatly appreciated - I've just recently started working with Minecraft plugins, so I'm very new to all of this. Thanks in advance!
<img width="547" alt="Screen Shot 2021-05-20 at 11 14 00 PM" src="https://user-images.githubusercontent.com/84248996/119081173-11006f80-b9c1-11eb-84a0-542f3de7df4a.png">
<img width="1118" alt="Screen Shot 2021-05-20 at 11 15 54 PM" src="https://user-images.githubusercontent.com/84248996/119081303-54f37480-b9c1-11eb-997b-5e607469467b.png">
<img width="1163" alt="Screen Shot 2021-05-20 at 11 16 18 PM" src="https://user-images.githubusercontent.com/84248996/119081327-62a8fa00-b9c1-11eb-9955-ff8f7ac103de.png">

**Comment by kangarko** [comment]
Maybe there's a syntax error somewhere in handlers.yml? You can use https://yaml-online-parser.appspot.com/ to copy paste your file content there to see if it compiles correctly.

If not then please upload your whole ChatControl Pro folder as a ZIP here directly and I have a look.

**Comment by yourlocalvirgo** [comment]
> Maybe there's a syntax error somewhere in handlers.yml? You can use https://yaml-online-parser.appspot.com/ to copy paste your file content there to see if it compiles correctly.
> 
> If not then please upload your whole ChatControl Pro folder as a ZIP here directly and I have a look.

You were right! I wasn't formatting things correctly. Like I said, I'm new to this/new to coding/etc so I just had things a little screwy. Thanks so much for your help!
