### ISSUE TITLE
Advancedban-chatcontrol conflict

### ISSUE THREAD

**Issue by Demonkid1112** [kangarko/ChatControl-Pro#229]
So this issue isn't to important however I recently converted the chat system on my server over to chatcontrol instead of essentials chat. All is going good except the mute/tempmute feature in advanced ban doesn't work which is causing some issues to arise. I don't know if this is on your end or advanced bans end but I figured I would start here.

**Comment by Demonkid1112** [comment]
The tempmute/mute features says they are muted however the players are still able to talk in game

**Comment by kangarko** [comment]
Please adjust your priorities as specified per
https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
