### ISSUE TITLE
Minecraft Version: Censor Not Working

### ISSUE THREAD

**Issue by KolakZ** [kangarko/ChatControl-Pro#2291]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/6550660/ChatControl.zip)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Just out of nowhere, the censor for the word "fuck" stopped working. I tried rebooting several times with no luck.

**Comment by McSwede** [comment]
Can confirm the free version is also affected. All of my packet rules that deny messages are not working.

**Comment by kangarko** [comment]
Fuck

**Comment by kangarko** [comment]
<img width="553" alt="Screenshot 2021-05-29 at 18 50 48" src="https://user-images.githubusercontent.com/1918426/120078248-cb256480-c0ae-11eb-8228-92b126e15f79.png">
I am kidding. Your rules/rules.txt file had `#` in front of the fuck filter, remove those.

**Comment by KolakZ** [comment]
Oh sorry, I did not see that. Thanks so much!
