### ISSUE TITLE
1.16.5: "ignore string" with "match .*" not working?

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#2294]
Hi,
in my chat.txt i have the following:

**match .*
ignore string \.mivan|\.xd
dont verbose
then console sound entity_player_breath -all -v:0.1**

But the rule was triggered for both ".xd" and ".mivan" words in chat.

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

**Comment by kangarko** [comment]
Use

`ignore string \.mivan|\.xd`
