### ISSUE TITLE
1.16.5: Server Freeze

### ISSUE THREAD

**Issue by coco0325** [kangarko/ChatControl-Pro#2296]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

When a lot of players(>10) join the server same time, ChatControl might freeze the server.
Stacktrace: https://pastebin.com/ac80aAt5

**Comment by kangarko** [comment]
Remove your data.db and clean your ChatControl MySQL tables to reset them, seems like it did not get cleaned up properlly
