### ISSUE TITLE
add a support for itemadder emojis

### ISSUE THREAD

**Issue by Jennlovee** [kangarko/ChatControl-Pro#2297]
First of all I want to thank you for releasing chatcontrolpro for users like me who have a small network with little income and who pay more than what we earn.
I also wanted to ask you if it is possible to add a compatibility or talk to the itemadder dev so that chatcontrolpro and itemadder are compatible since I can't get the emojis to be seen.
thank you very much again!

**Comment by kangarko** [comment]
Thanks! In ChatControl Red this has been added, we're no longer shipping feature updates to Pro.
