### ISSUE TITLE
Java 16 support

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl-Pro#2298]
Actually chatcontrol pro don't work on java 16  that is required for upcoming 1.17 
This is the startup log:
https://pastebin.com/stx1W6d0

I tried also nashornplus, it seem to don't work

**Comment by YellowZaki** [comment]
Same happening for me when I upgraded to java 16

**Comment by kangarko** [comment]
Install nashornplus from mineacademy.org/nashorn

**Comment by kangarko** [comment]
If that still won't work then post the relevant error after you've installed NashornPlus.

**Comment by Wolfbros** [comment]
I have installed NashornPlus and get this error: https://pastebin.com/vm0PtVgk

plugman info NashornPlus
 [PlugMan] Plugin Information: NashornPlus
  Version: 1.1.0
  Author(s): kangarko
  Status: Enabled

**Comment by kangarko** [comment]
Thanks, will be patched
