### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by Malachiel87** [kangarko/ChatControl-Pro#2299]
Minecraft Version: 1.1.7
MySQL: false
BungeeCord: false

This is the error that i got at startup https://pastebin.com/7LCJhCKN

**Comment by mango63** [comment]
Having the same issues,
is your plugin checking the version and stopping if higher then 16

 https://pastebin.pl/view/bc35ff62

**Comment by kangarko** [comment]
Coming, no ETA

**Comment by kangarko** [comment]
If you will still encounter this issue on the next release, please let me know below.

**Comment by Malachiel87** [comment]
did you  related to RED version? because i see a update here and nothing on chatcontrol pro

**Comment by kangarko** [comment]
Other plugins will be updated today :)
