### ISSUE TITLE
Unable to parse viaversion PlaceholderAPI variable

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl-Pro#2305]
![Snipaste_2021-07-02_18-02-49](https://user-images.githubusercontent.com/83099762/124258323-d95c1a00-db5f-11eb-9af4-f39386b0b14f.png)

AnimatedScoreboard can load viaversion PlaceholderAPI variable

Versions before 1.17, this variable works normally (viaversion_player_protocol_version)

![Snipaste_2021-07-02_18-06-03](https://user-images.githubusercontent.com/83099762/124258621-3526a300-db60-11eb-8ae8-602219950903.png)

Extra [i] when using the reload command
There is no such symbol in the language file

**Comment by kangarko** [comment]
Please update to the next version coming up tonight. Seems like you are on ChatControl Red which also has a different support channel at https://github.com/kangarko/ChatControl-Red
