### ISSUE TITLE
Unable to parse viaversion PlaceholderAPI

### ISSUE THREAD

**Issue by SheerYin** [kangarko/ChatControl-Pro#2308]
As of ChatControl Pro-running 8.10.7, it still can’t resolve %viaversion_player_protocol_version%
Other plug-ins can be parsed, such as AnimatedScoreboard

ChatControl Pro -8.10.7 is still unclear [i] [x]
Cannot modify in language file

ViaVersion-4.0.1.jar
PlaceholderAPI-2.10.10.jar
ChatControl-8.10.7.jar 

![Snipaste_2021-07-14_17-53-12](https://user-images.githubusercontent.com/83099762/125602711-b68453a4-955b-44b0-bb5b-a737353a2b2d.png)
![Snipaste_2021-07-14_17-54-25](https://user-images.githubusercontent.com/83099762/125602845-f10acfb2-7340-4b43-947b-6337f6716f2b.png)

**Comment by kangarko** [comment]
If other expansion packs work properly then unfortunately it's the problem of the expansion pack or an incompatibility we're unable to fix.
