### ISSUE TITLE
Chat formatter not working on DiscordSRV

### ISSUE THREAD

**Issue by Porama6400** [kangarko/ChatControl-Pro#231]
Please make chat formatting work with DiscordSRV
DiscordSRV formatter is really useless and it can't be different on different channel

**Comment by kangarko** [comment]
Hey,

ChatControl supports DiscordSRV. Can you please describe your issue more precisely and include the expected input?

**Comment by Porama6400** [comment]
Chat output is in DiscordSRV format
Is it possible to use ChatControl Channel Format for message that sent to Discord via DiscordSRV?

**Comment by kangarko** [comment]
Please post me your settings.yml so I can see which feature you're using for Discord. Chat channels are differently formatted per channel, but for regular interactive chat, Discord takes over the formatting.

**Comment by kangarko** [comment]
Closing. Please comment below if you still have issues.
