### ISSUE TITLE
1.17.1: Struggling to filter "Anal"

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl-Pro#2312]
So I was recently made aware that the word "anal" was no longer filtering , however I have not touched my match in weeks. 
I was originally using this match - 
# Blocks 'anal'
match ((\ba|\B\@)+(\W|\d|_)*n+(\W|\d|_)*(a|\@)+(\W|\d|_)*(i|1|l|\!)+(\W|\d|_)*)
ignore string a an|an a|analog|an all|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator|a na|ana|anas|anakin
group swear

Then tried this one - 
# Blocks 'anal'
match \b(a+(\W|\d|_)*n+(\W|\d|_)*a+(\W|\d|_)*l+(\W|\d|_)*)
ignore string a an|an a|analog|an all|an almost|an alt|an alarm|an algorithm|an albino|an alot|an almond|an album|analyze|an alligator|a na|ana|anas|anakin
group swear

it's not seeming to block the word despite it being in there, i'm not sure where i went wrong on it and i'm still struggling to figure out regex.

**Comment by SecretarySami** [comment]
I also have a couple questions regarding grammar filtering as well if you guys have time for that :)

**Comment by kangarko** [comment]
For ChatControl Pro you need to replace "group swear" with "handle as swear"

**Comment by SecretarySami** [comment]
> For ChatControl Pro you need to replace "group swear" with "handle as swear"

i just realized i did this for chatcontrol pro instead of red WOOOPS
sorry kangarko xD
