### ISSUE TITLE
1.17.1: Player join won't show up

### ISSUE THREAD

**Issue by Incoconut** [kangarko/ChatControl-Pro#2314]
After changing the command's Similar_Percentage_Block: 80 to 0
because Player can't join properly.

Player Join message won't show up after.

**Comment by Incoconut** [comment]
https://pastebin.com/DBA6naCC - settings.yml

**Comment by Incoconut** [comment]
... well i guess you can't help me.. uninstalling the plugin is my last resort.

**Comment by kangarko** [comment]
Your paste is private so I cannot access it. We are here to help and typically answer to custom questions in 1-5 days.
