### ISSUE TITLE
DiscordGuildMessagePreProcessEvent was cancelled, message send aborted

### ISSUE THREAD

**Issue by dimitriscr** [kangarko/ChatControl-Pro#2315]
Hello, I am running Chat Control Pro on a bungeecord server. Messages sent from minecraft get to the Discord channel properly but not the other way around.

After enabling Debug Mode on DiscordSRV I am left with this message when someone types a message with discord "DiscordGuildMessagePreProcessEvent was cancelled, message send aborted".
When Chat Control Pro is disabled and only DiscordSRV is left the messages from discord work fine.

Here is my channels.yml, I only use the global channel and plan on removing the admin channel. https://pastebin.com/bpF34Hjn

**Comment by dimitriscr** [comment]
Also I didn't notice this until I left for a bit but 5-10 minutes after the messages are sent from discord this shows up:
Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:guild_id:627952783563423765:webhook_id Retry-After: 600000 ms

**Comment by kangarko** [comment]
Hello!

Please set Debug key in ChatControls settings.yml to ["discord"] and report the message it says from our end.

> Encountered 429 on route PATCH/channels/{channel_id} with bucket 9852e1a53c06ffc5a89d65fef85ca4ce:guild_id:627952783563423765:webhook_id Retry-After: 600000 ms

I do not thing this is triggered by us, in the last six years of maintaining this plugin I was yet to see a message like this. Could be "HTTP 429 Too Many Requests response" which means Discord is throttling your connection.

**Comment by dimitriscr** [comment]
There are a few extra messages but none of them seem like errors.

These seem like the most relevent:

Warning: Admin_Chat feature is deprecated. You can create an admin channel in channels.yml. If using Discord, you can put 'Discord: true' key there to connect it with Discord channel by the same name.

[DiscordSRV] [DEBUG] Tried aggressively stripping blank message

[DiscordSRV] API listener org.mineacademy.chatcontrol.lib.fo.model.DiscordListener$DiscordListenerImpl unsubscribed

[DiscordSRV] API listener org.mineacademy.chatcontrol.lib.fo.model.DiscordListener$DiscordListenerImpl subscribed (2 methods)

**Comment by dimitriscr** [comment]
If I rename the discord channel to something different than the Chat Control channel, this shows up:

[discord] > Message not being sent to admin chat (configuration requires admin chat name: admin), moving forward...
[discord] [Discord->ChatControl] Ignoring Discord message from channel 'ingame'. Available ChatControl channels: [admin, global]

And if i name it "global" like the Chat Control channel I just get this:

[discord] > Message not being sent to admin chat (configuration requires admin chat name: admin), moving forward...

**Comment by dimitriscr** [comment]
Having resorted to switching all of the discord related settings until it works I have managed to get it to show up by disabling these two values in channels.yml

  Discord:
    #
    # If true, messages from Discord will be only send into a ChatControl channel
    # with exactly the same name, in the format below.
    #
    Control_Incoming_Messages: false
    #
    # If the option above is true, and channel is not installed on the server,
    # should be block the message from appearing in the chat? If not, DiscordSRV
    # will handle it and it will display to all players on your server.
    #
    Deny_Unknown_Channel: false

And since it doesn't seem to have broken anything else I guess the issue is solved?

**Comment by kangarko** [comment]
Okay that can do. Thank you for reporting. Let me know if there is anything else I can help you with.

By the way we have a far better discord integration in ChatControl Red, let me know your MCMarket username and I give you test access so you can test it out if you like it.
