### ISSUE TITLE
1.17.1: Plugin Disables Itself

### ISSUE THREAD

**Issue by arttwart** [kangarko/ChatControl-Pro#2316]
Minecraft Version: 1.17.1

1. Download NashornPlus and ChatControl.
2. Put them into **plugins** folder.
3. Start the server.
4. See the error.

Error log: https://srcb.in/crGNdoP6KB

I believe this is because of language of my computer. Recently I had some issues with language conflicts but I'm not sure. I tried using English (US) but it's still not working. 

I didn't upload any file because I'm using the most recent version (8.10.7) and it directly doesn't work. So I couldn't edit any files.

**Comment by kangarko** [comment]
I apology, this is an internal bug, I will fix this asap today.

**Comment by arttwart** [comment]
It still does not work. https://srcb.in/mHf7p07X1K
