### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by galenamc** [kangarko/ChatControl-Pro#2317]
1.16
the /mute plugin no longer works to mute an induvidual player after using this plugin. They are still able to talk

**Comment by gone-incognito** [comment]
Hey, try changing ``Listener_Priority.Checker`` and ``Listener_Priority.Formatter`` in ``settinigs.yml`` in chat control.
You will most likely need to change the following:

``Listener_Priority.Checker`` changed to ``LOW``
and
``Listener_Priority.Formatter`` changed to ``NORMAL``

Remember, you will need to restart the server after changing the priority of the listeners for these changes to take effect.
For more info about the listeners check out [this page](https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities)

**Comment by gone-incognito** [comment]
Also make sure to check the listener for the mute plugin you are using, as chances are chatcontrol is listening to messages before the mute plugin gets a chance to cancel the message.

**Comment by kangarko** [comment]
Closing, invalid section, this issue tracker is for ChatControl Pro not ChatControl Red. Thanks to gone for helping anyways, hope it helped, if not, please open a new ticket at the appropriate tracker.
