### ISSUE TITLE
1.17.1 | Multiple chat channels

### ISSUE THREAD

**Issue by Woodpecker123** [kangarko/ChatControl-Pro#2319]
Is it possible to make global, local, trade chat channels?
And so that the formatting for them is in formatting.yml

**Comment by kangarko** [comment]
You can make chat channels that are global, meaning messages go to BungeeCord, or local, meaning messages only get sent to players within a given block radius, or trade channels althought I am unsure what you mean.

This is configurable in settings.yml.

Read our config files and see our Wiki for more details.

**Comment by Woodpecker123** [comment]
> You can make chat channels that are global, meaning messages go to BungeeCord, or local, meaning messages only get sent to players within a given block radius, or trade channels althought I am unsure what you mean.
> 
> This is configurable in channels.yml.
> 
> Read our config files and see our Wiki for more details.

I want it so that when a player puts a"! " symbol in front of a message, all players would see this message.
And if he does not put this symbol, then players within a radius of 100 blocks have seen this message.

And so that the chat format is from formatting. yml

Can you please throw off an example of configurations, I do not know how to do this...

**Comment by kangarko** [comment]
Set Range.Global_Shortcut to "!" for writing with ! to go to all players, and without ! only to go to a distance. See the Range section in formatting.yml file for examples and help.

**Comment by Woodpecker123** [comment]
And why don't you support your ChatControl pro resource anymore spigotmc.org ?
Why do such bad reviews appear there?

**Comment by Woodpecker123** [comment]
I'm sorry that I bought your plugin there and it became free(

**Comment by kangarko** [comment]
https://mineacademy.org/the-death-of-spigotmc/
https://mineacademy.org/all-plugins-available/

**Comment by Woodpecker123** [comment]
> https://mineacademy.org/the-death-of-spigotmc/
> https://mineacademy.org/all-plugins-available/

It says that people who bought ChatControl Pro can get a free update.
I bought a plugin that summer, somewhere at this very time, I have receipts, I can throw it off from PayPal if necessary.

**Comment by Woodpecker123** [comment]
Do you have discord to make it easier to communicate?

**Comment by kangarko** [comment]
You can apply to obtain a free upgrade at mineacademy.org/chatcontrol-red, there is a form in the middle of the page

**Comment by Woodpecker123** [comment]
> You can apply to obtain a free upgrade at mineacademy.org/chatcontrol-red, there is a form in the middle of the page

I applied

**Comment by Woodpecker123** [comment]
Now I can download ChatControl Red.
Did you give access so quickly?)

**Comment by Woodpecker123** [comment]
And how to implement all this, what I wanted above in ChatControl Red?
I put a radius (Range) of 100 on the "standart" channel, but the message is visible everywhere( I've already tried a lot of things, but it doesn't work as it should...

**Comment by Woodpecker123** [comment]
I did, it works, I just didn't know that after each reboot of the plugin I need to re-log in to the server.

Thank you for your help, Kangarko!
In the future, I will contact issues ChatControl Red on GitHub
