### ISSUE TITLE
1.16.5: Why are my formatting parts being removed?

### ISSUE THREAD

**Issue by srnyx** [kangarko/ChatControl-Pro#2320]
Here's my `formatting.yml`: https://paste.srnyx.xyz/kiyenodiza.yaml
The default is three parts, but I wanna have four. Whenever I reload the plugin or restart my server, either the third or fourth part is removed and put into the `unused` folder.
Here's the warning that comes up in console: https://paste.srnyx.xyz/miluhigupe.cs

**Comment by kangarko** [comment]
Sorry, will be fixed in todays update.
