### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by Xcalibur3000** [kangarko/ChatControl-Pro#2325]
When I use the command : "/chc color"

------------------------------------[ 31.08.2021 08:43:56 ]-----------------------------------
ChatControl 8.10.10 encountered a FoException
Running CraftBukkit 1.17.1-R0.1-SNAPSHOT and Java 16.0.2
Plugins: ServerRestart v2.3.0, InventoryRollbackPlus v1.6.1, PlaceholderAPI v2.10.10, PluginManager v1.7, SkinsRestorer v14.1.3, PL-Hide v1.5.19, LightAPI v3.5.2, LuckPerms v5.3.47, ClearLag v3.2.2, ConditionalEvents v3.7.1, Votifier v2.7.3, LoneLibs v1.0.14, ProtocolLib v4.7.1-SNAPSHOT-b531, LibsDisguises v10.0.26, Minepacks v2.4.2-Release, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, BKCommonLib v1.17.1-v3-SNAPSHOT, Vehicles v12.3, Maintenance v3.0.7, LagAssist v2.24.1, WorldEdit v7.2.6+4b2d1e7, IllegalStack v2.4.0, LightCleaner v1.17.1-v1, HeadDatabase v4.14.1, Multiverse-Core v4.3.1-SNAPSHOT-b857, AsyncWorldEdit v3.9.1, TAB v2.9.2, AuthMe v5.6.0-SNAPSHOT-b2488, WorldGuard v7.0.6-beta1+0b66f3e, VTitleAuth v1.2, Multiverse-Inventories v4.2.3-SNAPSHOT-b519, EpicHoppers v4.6.22, GSit v[6.0.2.1], NexEngine v2.0.7.4, CoreProtect v20.1, UltimateShops v2.2, SimpleClans v2.15.3, Citizens v2.0.28-SNAPSHOT (build 2364), GoldenCrates v3.11.0, EliteMobs v7.3.5, Minecord v1.7.15, InteractionVisualizer v1.16.3.9, PremiumVanish v2.7.2, DiscordSRV v1.23.0, UltimateTimber v2.2.5, CMILib v1.0.3.6, Jobs v5.0.0.6, CMI v9.0.2.9, ChatControl v8.10.10, VotingPlugin v6.6.1, Residence v5.0.0.2
----------------------------------------------------------------------------------------------

More Information: 
Cannot generate NMS container class to update inventory of size 0
FoException Report: Cannot generate NMS container class to update inventory of size 0
	 at org.mineacademy.chatcontrol.lib.fo.remain.Remain.updateInventoryTitle(Remain.java:1459)
	 at org.mineacademy.chatcontrol.lib.fo.PlayerUtil.updateInventoryTitle(PlayerUtil.java:600)
	 at org.mineacademy.chatcontrol.lib.fo.menu.Menu.setTitle(Menu.java:759)
	 at org.mineacademy.chatcontrol.menu.MenuColorContainer.<init>(MenuColorContainer.java:38)
	 at org.mineacademy.chatcontrol.command.ChatControlCommand.onCommand(ChatControlCommand.java:479)
	 at org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:404)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	 at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:776)
----------------------------------------------------------------------------------------------
-->

Minecraft Version: 1.17.7
MySQL: false
BungeeCord: false

Remove this and type your issue description here with steps to reproduce: 1-2-3.

**Comment by kangarko** [comment]
Thanks, fixed!
