### ISSUE TITLE
How can i prevent my player use color in my chat, My Format is enabled

### ISSUE THREAD

**Issue by boristran03** [kangarko/ChatControl-Pro#2326]

**Comment by boristran03** [comment]
they don't have permission chatcontrol.color.{color} but they can use color code in my chat (sry for my english)

**Comment by kangarko** [comment]
If you don't use our formatting system then we can't prevent that, sorry.

**Comment by boristran03** [comment]
> If you don't use our formatting system then we can't prevent that, sorry.

i mean i enabled your format @@ sry for my english

**Comment by kangarko** [comment]
It looks like they still have chatcontrol.color.* somehow, try giving them negative / false permission "chatcontrol.color.*"
