### ISSUE TITLE
How can i setup Ranked_Formats?

### ISSUE THREAD

**Issue by AnonymousUploader** [kangarko/ChatControl-Pro#2327]
Hello, i would like to know how to setup an a Ranked Formats because it don't work when i put it like this 
https://pastebin.com/4nJDdwag

**Comment by kangarko** [comment]
What exactly does not work?

**Comment by AnonymousUploader** [comment]
Nevedel som to nastaviť ale už je to v pohode možeš zavrieť tento ticket
Rozhodne by som avšak dal na github nejaký template pre ranked formát pretože nevie úplne ako na to

 My config for ranked format should work (100%): https://pastebin.com/zyCHbMTX

**Comment by kangarko** [comment]
Dakujem!
