### ISSUE TITLE
How to enable placeholders

### ISSUE THREAD

**Issue by Arthuuurr** [kangarko/ChatControl-Pro#2328]
Hello good, I come to ask how the placeholders are activated when you hover the mouse over the name of a person, I have tried to do it several times but it tells me that the placeholders are not enabled, can you help me?
Thanks!

**Comment by kangarko** [comment]
I am not sure if I understand you, but in most causes you need to install PlaceholderAPI and download the appropriate expansion pack with your placeholder.
