### ISSUE TITLE
API Improvement suggestion

### ISSUE THREAD

**Issue by Porama6400** [kangarko/ChatControl-Pro#233]
- **ChatViolationEvent** which will be call when someone break the rule
- **ChatChannelJoinEvent** which will be call when someone join the channel
- **ChatChannelLeaveEvent** which will be call when someone left the channel
- API to check custom String

**Comment by kangarko** [comment]
PreRuleMatchEvent has been added.

ChannelJoin- and ChannelLeaveEvent event will be added in the next version.
