### ISSUE TITLE
Adding /chc color <COLOR_OR_FORMAT_NAME>

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2335]
i think that the title is enough, i will just give examples
if player has permissions `chatcontrol.command.color` & `chatcontrol.color.RED`, he would, be able to do `/chc color red`
and would do exact same thing if he did the `/chc color` and opened GUI menu and selected RED color (with adequate permissions of course)

now i see that on the wiki there is permission for colors like `chatcontrol.color.<color>`
and then i see there is permission for color gui `chatcontrol.gui.color.<color>`

now i don't understand the point of `chatcontrol.color.<color>` permission because it isn't used anywhere, because for color GUI usage we need `chatcontrol.gui.color.<color>` permissions

then it's logical for `chatcontrol.color.<color>`, when user has that permission (for example for color "RED"), his messages by default should be colored that way? or am i doing something wrong, is there some command to toggle color formatting on/off for user if he has `chatcontrol.color.<color>` permission?

**Comment by kangarko** [comment]
Thanks, however we're not adding new features to ChatControl Pro as this already has been added to https://mineacademy.org/chatcontrol-red
