### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by catfishua** [kangarko/ChatControl-Pro#2344]
Good evening, I can ask you for the source code of the ChatControl Pro plugin, because I need to change something there, and you obfuscated the source code of this plugin so that when compiling the plugin (after decompilation) an error appears due to the fact that the source code confused beyond recognition due to obfuscation and the source code of the free version of the ChatControl-Free plugin is not enough for me, and I need specifically the source code of the ChatControl Pro plugin because you almost never do it, but I need to fix something in this plugin and it is obfuscated ... I hope you understand me and make an unbeatable decision.

**Comment by kangarko** [comment]
We are not publishing source for ChatControl, I am sorry.
