### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2346]
I have simple question.

How to chat in color, like a donor perk, what permission is used:
user: "`&eHello`" <-- it'll display colored yellow

Now i know there is force color chat (`/chc (set)color`), but i don't want that, i want direct coloring messages.
is this possible?

**Comment by kangarko** [comment]
Yes it's possible, you can see our color permissions here: https://github.com/kangarko/ChatControl-Pro/wiki/Permissions#chat-formatter
