### ISSUE TITLE
Question about ticks

### ISSUE THREAD

**Issue by AnonymousUploader** [kangarko/ChatControl-Pro#2347]
Hello, chatcontrol says it use 20% of tick can you please check whats the problem?
Here are my timings https://timings.aikar.co/?id=7f84a827218641d794c7601f054548a3
I use 1.17.1 from paper, if you need more information tell me
Thanks.

**Comment by kangarko** [comment]
Looks like your /save-all command is causing mismeasurements, I advise run another series to confirm this. Also it could be a slow mysql database connection. Let me know below if this will show up regurarly.
