### ISSUE TITLE
Announcer JSON

### ISSUE THREAD

**Issue by iamharrymc** [kangarko/ChatControl-Pro#235]
Hey,

I'm trying to setup the global message broadcaster to send JSON text messages, which, when clicked, open URLs. I have tried lots of different combinations, including the example in the config, but it just results in the JSON being broadcast as raw text.

Thanks for the help

**Comment by kangarko** [comment]
Please configure your timed messages as specified by: https://github.com/kangarko/ChatControl-Pro/wiki/JSON#json-in-timed-messages-in-messagesyml
