### ISSUE TITLE
1.18.1: A possible typo

### ISSUE THREAD

**Issue by F8ER** [kangarko/ChatControl-Pro#2354]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

Dear Developers,

Thank you very much for the project.

# Steps

1. Launch Paper `v1.18.1 77` server;
2. Copy the plugin Jar (`v8.11.3`) to `./plugins/`;
3. Relaunch the server;
4. Open `./plugins/ChatControl/messages.yml`.

# Issue

Currently, line 175 in `messages.yml` includes a possible typo:
> Configure custom `death` messages.

instead of 

> Configure custom `quit` messages.

Best and kind regards

**Comment by kangarko** [comment]
Thanks, will fix!
