### ISSUE TITLE
Last update before going abanodned

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2355]
Hello there

I wanted to ask, would you implement support for upcoming release of PAPI (2.13.0)

Deprecated methods are scheduled for removal in PAPI 2.13.0 are listed here
https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/PlaceholderAPI.java#L292-L622

Thank you in advance even if you don't do this.

**Comment by kangarko** [comment]
When it will become a problem I will have a look, I don't think we are using these methods
