### ISSUE TITLE
Just to remove one line of sendMessage()

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2357]
Hello!
![image](https://user-images.githubusercontent.com/56804505/147839987-f71b379c-f626-4397-8b4f-293fda0f90cc.png)
I've noticed this, even if update notifications are enabled or disabled, this happens
I've been playing with CHC since it was free, I can guarantee (i even posted some other hardcoded stuff that is something that anyone should be able to change) that there is NO MORE things like this! At least I guarantee that because of how much time i've spent playing with it.

That said, I wanted to ask you would you be kind to simply just remove this line of code that is sending this message, much appreciated!
Not that big thing, it can just bother some staff users.
If you do/don't do this, either way, thank you so much!

(I know CHC is reaching end of life today, however, i hope you won't look at that because this is really simple thing, but either way i respect your answer even if you deny...)

Have a nice New Year!

**Comment by kangarko** [comment]
The message "Update checking disabled in config" is non existent in ChatControl Pro. This has to be coming from another plugin.
