### ISSUE TITLE
Replying to console

### ISSUE THREAD

**Issue by DanielVasquez4155** [kangarko/ChatControl-Pro#236]
When the console messages players, the players have the chance to reply to them. I feel like this should be disabled, but having it in the config would be config would be better. 
![image pasted at 2017-5-23 20-38](https://cloud.githubusercontent.com/assets/22107830/26382511/8040b6ce-3fe1-11e7-9850-c8431b9b4259.jpg)

**Comment by Porama6400** [comment]
It would be nice if there is a permission for reply to console

So technician can secretly communicate to admin but player can't

**Comment by kangarko** [comment]
Thank you for noticing, this was originally a feature but I see the point.

A new release will include the two following permissions, disabled by default:

* chatcontrol.commands.tell.console
* chatcontrol.commands.reply.console
