### ISSUE TITLE
Death messages totally messed up 

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2364]
There is a problem when player gets killed by another player, it'll always throw death message like he was killed by `Elder Guardian`.
Same for -> if player is killed by zombie, it'll throw `Drowned`  mob (that don't even exist in the server version where i tested this -> 1.8.8)
![image](https://user-images.githubusercontent.com/56804505/153749085-8677f9c5-61d5-4ebb-934d-8f8935078e00.png)

Minecraft Version: 1.8.8
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
Please send me your debug file as instructed when creating the issue.

**Comment by kangarko** [comment]
Please send me your messages.yml file

**Comment by TheJoshue** [comment]
i am sorry, i've messed up and didn't delete new death messages for mobs from 1.9+ (my server was 1.8.8)
hey thank you so much however!!!
