### ISSUE TITLE
Make URL links from /whisper (private messages) clickable

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2366]
Very simple explained in title!

**Comment by kangarko** [comment]
Thanks! However we're no longer maintaining ChatControl Pro :( but you can give ChatControl Red a try! See mineacademy.org/chatcontrol-red

**Comment by TheJoshue** [comment]
> Thanks! However we're no longer maintaining ChatControl Pro :( but you can give ChatControl Red a try! See mineacademy.org/chatcontrol-red

man... URLs in global chat are clickable
why not in private messages?
