### ISSUE TITLE
Hex Support

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2374]
Will you at least add basic spigot HEX support?
no need to add gradient, we'll somehow manage to do it
at least hex support

**Comment by kangarko** [comment]
I am sorry, ChatControl Pro is not receiving feature updates, only critical security ones, we have already added this to ChatControl Red.

**Comment by TheJoshue** [comment]
ok thanks for answering
btw i have multiple plugins of your and my friend has CHCRED purchased from you (we share server) so i actually appreciate your CHCRED and me and my friend shared paying of it (i paid half of it) but it's on his account.

Still, i think you should keep CHCPro for free for people who want to use it in their test environment or really don't have money to buy CHCRED

I think you should consider only these major improvements to be added to the plugin, I understand that you are focused on CHCRED and said that CHCPRO is not receiving anything new, but CHCPro is still very versatile for home network and it lacks compound thing that is since 1.16 standard - RGB/HEX support

For sure these things happen once in 10 years, there won't be any new EXTREMELY INNOVATIVE things coming up because we already got one in last 2 years - RGB support

Thank you for understanding! we appreciate your time.

**Comment by kangarko** [comment]
Thank you! Yes we will keep ChatControl Pro available and update it to Minecraft 1.19 soon, but no other feature changes.
