### ISSUE TITLE
1.18.2 Formatting not working

### ISSUE THREAD

**Issue by M0diis** [kangarko/ChatControl-Pro#2377]
I'm using 1.18.2 paper. No MySQL, no bungee. 8.11.7 plugin version.
Not sure what is the problem and how to reproduce it.

![image](https://user-images.githubusercontent.com/53468997/177598049-d9f83d79-d469-4bd2-a284-44f63396e1d5.png)

Formatting does not work for my staff, but does for me. The other player has the same permissions.

**Comment by kangarko** [comment]
If it does not work for your staff but it does for you, A) it is caused by another plugin or B) you have not given staff the right permissions. Check if it is properly enabled in formatting.yml > Enabled should be set to true.
