### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by wellnesscookie** [kangarko/ChatControl-Pro#2378]
Minecraft Version: 1.19 / 1.16
MySQL: true
BungeeCord: true

1. We have multiple servers that vary from 1.16 up to 1.19 version
2. We wanted to use ChatControl's Pro latest version for all of our servers, but when we updated to the latest version on our 1.19 server, the error popped up: Error: This registration already exists

We are not sure what's causing this. We've tried stopping all of the servers, and keeping only the one that has the upgraded version installed ON, but there were no differences. We use the second-to-latest version on all our 1.16 - 1.17 servers, but we are unable to have CHC installed at all on 1.19 due to this.

Log: https://pastebin.com/MLe9sALL

**Comment by kangarko** [comment]
Thanks, fixed: https://github.com/kangarko/ChatControl-Pro/releases/tag/8.11.8
