### ISSUE TITLE
1.8.8: Messages are being sent in the wrong order

### ISSUE THREAD

**Issue by PureMC** [kangarko/ChatControl-Pro#2379]
Minecraft Version: 1.8.8
MySQL: false
BungeeCord: false

Hello,
on ProtocolLib 5.0 messages are being sent in the wrong order. What I mean by that is that leaderboards are broken for example. And yes, it caused by this plugin. I have disabled every plugin after each other and there I am. On ProtocolLib 4.8, it's working.

That's what it should look like: 
![2022-07-13_21 38 02](https://user-images.githubusercontent.com/109244524/178820951-8694a41e-d6d0-43c0-9fc6-b1596c61ae0a.png)

And that's what it actually looks like: 
![2022-07-13_21 43 01](https://user-images.githubusercontent.com/109244524/178821100-a831182d-b933-485e-989d-a4d49863f1b4.png)

**Comment by kangarko** [comment]
Try the latest dev build of ProtocolLib: https://ci.dmulloy2.net/job/ProtocolLib/

Unfortunately ChatControl Pro is end of life for over half a year now, I don't have time to manage all plugins
