### ISSUE TITLE
Moderation: Checkmark After Messages

### ISSUE THREAD

**Issue by DuckCraftPvP** [kangarko/ChatControl-Pro#239]
Hi, Can you please add a moderation gui? Basicly a checkmark shows beside each persons msg for people with the right perms and it brings up a gui that allows u to mute / unmute / delete there msg.

https://www.spigotmc.org/resources/venturechat.771/ Has it but i like your plugin alot better. 

It would be great!

**Comment by kangarko** [comment]
Hey.

thank you for your suggestions. As per the current system, this is not possible, but when I rewrite the way messages are received, I can surely add this as well.

**Comment by kangarko** [comment]
Closing, as this is mentioned in the road-map already.
