### ISSUE TITLE
Can't seem to send /msg to players with the plugin loaded

### ISSUE THREAD

**Issue by Kadell** [kangarko/ChatControl-Pro#24]
Running kcauldron,(Infinity evolved modpack v2.4.2) fair bit of plugins, Can include a server log if needed. Running latest paid version of cc-p as of 4/6/2016 (6.8.7)

When i do a /msg <player name> <msg>   example /msg DanUnk test
What I get back when the plugin is enable is the help content (obviously it works when the plugin is disabled.)
/msg <to> <message>
![2016-04-06_21 20 46](https://cloud.githubusercontent.com/assets/10009286/14337695/3cb69460-fc3e-11e5-8187-5e7d8fa413e3.png)

It does this with the default config after having just been installed, If I enable the "Private message" section of the config then I get an error about an error having occurred during the process.(can send a screen of that as well. 

What can I send you that might best help you to pin point.

**Comment by Kadell** [comment]
just saw your message from yesterday https://www.spigotmc.org/threads/chatcontrol-pro-paid.82298/page-60

**Comment by Kadell** [comment]
can you elaborate on the example for redirecting to emsg? I have this so far
match ^/msg
then warn &dredirecting to emsg?
before replace ^/msg with /emsg

is this right? can you show a good redirect example?

**Comment by kangarko** [comment]
I would recommend:

match ^/(msg) (.*)
then rewrite /emsg $2

**Comment by kangarko** [comment]
Messaging features has been temporary disabled.
