### ISSUE TITLE
fake messages

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#240]
![1](https://cloud.githubusercontent.com/assets/2604798/26520805/ec86763e-42d9-11e7-84b4-d2185ec38611.png)
I have found an error.

What the difference beetween this messages?
First of all, the serverdate time placeholder only works if the player is really online on the server.
If the player is online and I use the /chc fake kick command, its works, but If I wanna use /chc fake leave/join
it wont works perfectly. this commands also have to leave the following formats:

> Join_Message:
> 
>   Enabled: true
>   Message: '&7[&e{server_date_HH:mm:ss}&7] &e{player} &acsatlakozott a szerverhez!'
>   Conditions:
>     staff_message:
>       Permission: chatcontrol.joinmessage.staff
>       Message:
>       - none
> Quit_Message:
>   Enabled: true
>   Message: '&7[&e{server_date_HH:mm:ss}&7] &e{player} &ckilépett a szerverről!'
>   Conditions:
>     staff_message:
>       Permission: chatcontrol.joinmessage.staff
>       Message:
>       - none
> Kick_Message:
>   Enabled: true
>   Message: '&7[&e{server_date_HH:mm:ss}&7] &e{player} &ckirúgva a szerverről!'

But some messages uses the format from the message_(localization).yml
How can I make it custom then or why it has 2 format?

(fake messages should use the default quit, kick, join format from the message.yml I think)

**Comment by kangarko** [comment]
Hey,

the variables require an online player to be present on the server. This is something PlaceholderAPI require and there's no way around it. So if the player is offline, only a small part of variables is replaced.

When it displays the format from localization and when it displays the format from messages.yml?

**Comment by rErEaT** [comment]
when the player is not online it will displays the fromat from localization.
kick messages are display the format from the messages.yml anyway.

**Comment by rErEaT** [comment]
Can you make your own {server_date_HH:mm:ss} placeholder from the server's date-time? :)
It would be nice and I hope it can add to the offline player!

**Comment by kangarko** [comment]
Hey,

I apologies to the delay. I can't reproduce myself. When the player is online, the proper message is selected from the conditions specified in messages.yml. In case he's offline, the default condition is used. Compare:
![img](https://i.imgur.com/3Z4pcxw.png)

**Comment by rErEaT** [comment]
And how can I define the {timestamp} placeholder to show only the time? :D
Not like the date :)

**Comment by kangarko** [comment]
This is a hardcoded timestamp, that cannot be altered. See, you can use all placeholders from PlaceholderAPI on normal join/quit/death messages, but when they are fake and the player is offline, we can do very little about it.

**Comment by rErEaT** [comment]
Ah okay.
{server_date_HH:mm:ss} leave the correct form of time, but doesnt work with offline player

**Comment by kangarko** [comment]
Yes, this is the intended behaviour, and sadly there's little I can do about it.
