### ISSUE TITLE
click issue with .today domain in chat.

### ISSUE THREAD

**Issue by JokerLiuPro** [kangarko/ChatControl-Pro#241]
all URL with .today is not able to click in chat
(I tested it clickable in server without chatcontrol)
![tbe6s1n](https://cloud.githubusercontent.com/assets/20258210/26523187/bed73c6c-4344-11e7-9fbb-b055e7343bf4.png)

**Comment by kangarko** [comment]
Hey, 

thank you for letting me know. I will look into it.

**Comment by kangarko** [comment]
Hey,

sorry for the delay, I have raised an issue on Spigot regarding this, because I could not find a cause to it myself. I will get back to it as soon as I receive their response.

**Comment by kangarko** [comment]
https://www.spigotmc.org/threads/some-urls-not-clickable-after-json-formatting.247011/#post-2482053

**Comment by kangarko** [comment]
Hey, so this turns out to be unsolveable for now. I'll look forward into the future for possible fixes, but I am closing this right now because sadly there's little on my end what I can do.
