### ISSUE TITLE
Question/Request: points as a placeholder?

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#243]
I would like to set "Verbose_Rules" to "false" and be able to set a custom console message as defined in handlers.yml something like:
Console_Message: "Anti swear: player: {player} ID: {ruleID} Points: {points} Message: {message}"
where points are the amount of points given like:
2 --> 4
Example:
>Anti swear: player: Notch ID: 3 Points: 2 --> 4 Message: No shit sherlock.

**Comment by kangarko** [comment]
Hey,

the points have very dynamic message making it hard to customize by you, so I rather keep it hardcoded. It is only displayed in console so it's not obtrusive to normal users.
