### ISSUE TITLE
ChatControl <username> was disallowed from running a command from book: /login pass

### ISSUE THREAD

**Issue by YellowZaki** [kangarko/ChatControl-Pro#245]
There is a user who can't execute authme commands. The console shows this error:

ChatControl Moralespkr was disallowed from running a command from book: /login <pass>

**Comment by rErEaT** [comment]
same here!
but /login is whitelisted :/

**Comment by kangarko** [comment]
Hey,

I apologies for the delay and inconvenience. I have resolved this bug and a fix will be available within the next release (eta: tonight).
