### ISSUE TITLE
Handle advertisments with spaces in between

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#246]
Hey there,

is there a way to adjust the advertisement rule to detect advertisements with whitespaces in between?
like
`e x a m p l e c r a f t . c o m`

Version 7.3.18

**Comment by kangarko** [comment]
Hey,

I apologies for the delay. Yes it is absolutely possible, simply set the 'before strip' operator in your domain rule in rules/rules.txt to:

`before strip [\(\[\]\)]|\s*`

The new part is \s* that will strip any whitespace before evaluating the message for ads.

**Actually** I have it just tested for you, and I noticed the operator needed a slight retouch. I have pushed the necessary changes for it to work to the next release (eta: tonight).

**Comment by EvilOlaf** [comment]
Thank you .
