### ISSUE TITLE
Auto-Update System

### ISSUE THREAD

**Issue by dnickLP** [kangarko/ChatControl-Pro#247]
Can you implement an Auto-Update System so on a Server Restart ist automaticly updates the Plugin.
If user doesn't want the feature they should disable it in the config!
We have a BungeeCord Network and ChatControl is creating the most Updates to us. 
We have to go in each Server and Update the Jar manually so with an Auto-Update System it would me much easier foir us like FastAsyncWorldedit which actually has this Feature implemented!

**Comment by LogGits** [comment]
I had the exact same thought xD But it was pointed out to me by Kangarko that Fast Async Worldedit is a free plugin. Hence, it can be downloaded from anywhere. That is why its not a difficult process for free plugins to add an updater. However, ChatControl Pro is a premium plugin which require uses user credentials and spigots policies currently don't allow that or even provide a simple way to auto update plugins.

**Comment by x1p** [comment]
Keeping up to date is time demanding :) But: many updates strips your comment lines in the settings.yml. So this has to be repaired as well or you'll lose the comments.

**Comment by kangarko** [comment]
Hey,

I understand your concerns and if there was a simple way to implement an automatic updater I would have done it long time ago. LogGits is right, Spigot policy do not allow nor provide a simple way of logging you in their site automatically to download an updated version of (any) premium plugin.

The YAML comments are removed by the design of the Bukkit library. I have no control over how the file looks like from within the plugin. You can view the commentaries on the Wikipedia.
