### ISSUE TITLE
Can't seem to stop chatcontrol from filtering out console info

### ISSUE THREAD

**Issue by Kadell** [kangarko/ChatControl-Pro#25]
I can no longer call functions from the server console, and see their output. Command runs, but the out put no longer shows in the console.
things like /pex commands or /gc none of the normal output shows anymore,

my config http://pastebin.com/PPDWK8bU

**Comment by kangarko** [comment]
ChatControl does not do that by default. I see you have Console Filter disabled, so I don't believe this is caused by this plugin.

**Comment by kangarko** [comment]
Closing, as it is most likely not caused by ChatControl.
