### ISSUE TITLE
/msg issue

### ISSUE THREAD

**Issue by Demonkid1112** [kangarko/ChatControl-Pro#253]
I recently updated to 1.12 on a small bungee server. After updating one of the servers encourtered the issue of the chat control message formatting isn't working. Whenever I message on that server it does "You whisper to (user): (message)" Which I believe is the default. However On my other server with the exact same chat control configurations and plugin version the PM formatting area works

**Comment by Demonkid1112** [comment]
update: 
So I asked around on the spigot forums about it I found a handy plugin which lets me fix up command conflicts. The issue is no matter how high I set the priority in your config, for some reason default minecraft likes to hijack /msg and /tell. 

my main question now, is how do you handle /tell and /reply?

**Comment by kangarko** [comment]
Hey,

please ensure you have enabled PM's explicitly by setting 'Private_Messages.Enabled' to 'true' in settings.yml and that no other plugin is registering those commands.

ChatControl should take over the commands unless you have Towny, Towny interferes with the technique we use so I added an exception there that may result in the command not always being registered.

**Comment by Demonkid1112** [comment]
Looks like towny is one plugin i don't have across all servers, I will look into it, but thank you!
