### ISSUE TITLE
/spy turns off when switching servers on BungeeCord

### ISSUE THREAD

**Issue by Kolgrath** [kangarko/ChatControl-Pro#254]
This is not an issue for admins (since they have all (*) permission nodes). 
But for the rest of my staff they have to re-engage /spy each time they switch servers. 

That leads me to believe there is a permission node somewhere that allows spy to always be on.

What is the best way to keep spy turned on between servers for my non-admin staff? Thank you.

**Comment by kangarko** [comment]
Hey,

the permission node is `chatcontrol.spy.autoenable`. By the way, there's a list of all the permissions on the wikipedia. You can navigate with CTRL+F and search for key words.

**Comment by Kolgrath** [comment]
Thank you for that node. 

I dod check here first before posting:
https://github.com/kangarko/ChatControl-Pro/wiki/Permissions

The permission you speak of isn't on the list.

**Comment by kangarko** [comment]
Oh I see, I apologies! I have edited the page immediately :)
