### ISSUE TITLE
Compatibility question.

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#255]
Hey there,

at the moment we have a quite ugly setup to have everything work properly through bungee.
HeroChat with BungeeChatProxy for normal and staff chat
and BungeeMSG for Broadcasts through all servers as well as allowing users to send msgs across servers.
CHC Pro is running side by side to all of this right now with bungee option disabled. Basically for chat filtering only.

The main goal is to remove all but CHC Pro with BungeeControlBridge and Bungee option enabled.
I think that this should work as expected. Just wanted to make sure that is before opening a construction site with big potential to frustration ;).
Needed especially is an adjustable chat prefix for the server a player is currently on. Also msgs from player to player should include senders and receivers world prefix. (stupid question: CHC supports basic msg/wisp/r stuff, right?)

As always thanks for reading.
Olaf

**Comment by kangarko** [comment]
Hello,

You may use {server_name} variable to show the server from which the message is sent. The name is customizable, more information [here](https://github.com/kangarko/ChatControl-Pro/wiki/Server-Name-Alias).

In a recent update, a sender and receiver placeholders have been added. Feel free to use {sender} and {receiver} in chat.yml file.

Yes, ChatControl has /tell and /reply command. Support for /mail and /ignore is planned, but not in the very near future. Also I still keep in mind your suggestion from last year from the free issue channel, just it seems every time I have time I work on a completely different project :)

To be honest, it should work, but it's just a machine. From my personal experience it tends to be frustrating a little when getting used to something new but the payoff is greater. I have used ChatControl on production server with all features enabled for a few years, until about 7.x release. From users' reports, features seems stable, but I am open to complains and suggestions.

**Comment by EvilOlaf** [comment]
Thank you for your detailed answers.

I guess the most common aliases to tell (wisp,w,msg,m,t) can be achieved by creating a rule for them and should work as before.

No concerns about /mail and /ignore as I do not plan to remove EssentialsX which supports those features. Not through servers but that is not important in my case.

**Comment by kangarko** [comment]
Btw, you can create aliases directly within the settings.yml file. See Private_Messages section.

**Comment by kangarko** [comment]
Closing, if you have any more questions please comment below.
