### ISSUE TITLE
Channel bug

### ISSUE THREAD

**Issue by BlueSoapTurtle** [kangarko/ChatControl-Pro#258]
Made a town channel

  town:
    Format: '{pl_prefix}{player}:{pl_suffix} &e{message}'
    Party: town

started the server, did /ch join town, and it said
"Cannot have more than one channel to write to. Please leave channel: standard"
so I did /ch leave standard

then did /ch and then /ch join town and this happened
https://i.gyazo.com/3f9785a012af671c68b6d30324e363d4.png

"You are already in this channel. Type /ch l town to leave"

**Comment by kangarko** [comment]
Spying channels are also counted as the channels you are in, but only you cannot write to them. You can to leave the towny channel by the same command and then rejoin with the same command to put it to your main writing channel.
