### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BlueSoapTurtle** [kangarko/ChatControl-Pro#259]
Townychat has this and its' quite nice for their channels, 

    town:
        commands: [tc]

doing /tc <message> sends a message to the town channel
doing /tc, joins the town channel and leaves the rest.

would really be awesome to have something like this to make it easier on players

**Comment by kangarko** [comment]
ChatControl has an alternative command "/chc send" that sends the message only to a certain channel. 

Players may currently be only in one channel, although this might change in the future.
