### ISSUE TITLE
CHC book block bypass?

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#260]
```
# Prevent running commands from books? (Misused by hackers to trick admins)
  #
  # [NOTICE]: There is no other possibility to do this check then just blindly assume the command
  # is coming from a book (because it is client side), so we check if the player holds a book.
  # If they execute a command from the chat while holding a book, it will be blocked as well.
  Block_Book_Commands: true
```
It seems like this feature is working well as long as I am not an operator which in my eyes does not make sense. If this feature should work efficiently it should always block commands while holding a book, regardless if op or `*` permission.
So if a player which as op or `*` permission (I know that is not a good idea anyways but that is not the point here) gets a prepared book he would not be protected by CHC as their permission overrides this protection.
This makes this protection completely useless.

7.3.19

**Comment by kangarko** [comment]
Hey,

I undestand, but no matter how the feature is implemented there's always going to be requests and complains from users, so I just added the 'chatcontrol.bypass.bookcommands' permission beforehand that affects whether or not you're checked.

Give operators or users having '*' permission that negative permission:

Example:
`/pex group Owner add -chatcontrol.bypass.bookcommands`

**Comment by EvilOlaf** [comment]
I see.... well, we will figure something out to handle this.
Thank your for your answer.
