### ISSUE TITLE
Swears with whitespaces

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#262]
I really wonder that I did never notice this after several years with CHC and CHC pro....well, maybe I'm getting old.

Anyway.

I recently noticed that a player tried to use inappropriate language, for the example here the word `pimmel`. There is a rule for this
```
# Blocks pimmel
match (p+(\W|\d|_)*i+(\W|\d|_)*m+(\W|\d|_)*e+(\W|\d|_)*l+(\W|\d|_)*)
handle as swear
```

which works perfectly as long as there are no white spaces in between.
So `p i m m e l` is not getting filtered.

By thinking about that the example rules for this are designed this way for good reason, because simply adding `\s` to the matching stuff in between the characters this could generate tons of false positives.

So the best way to solve this (in my guess at least) is to duplicate all the rules and replace the matching stuff with `\s` like this:

```
# Blocks pimmel with whitespaces
match p+\s*i+\s*m+\s*m+\s*e+\s*l+
handle as swear
```
Should catch with one or unlimited space in between characters.

Just want to confirm my thinking about this.

As always thanks for reading.

**Comment by x1p** [comment]
If you would change you rule to:
(p+(\W|\d|_)*i+(\W|\d|_)*m+(\W|\d|_)*m*(\W|\d|_)*e+(\W|\d|_)*l+(\W|\d|_)*)
It would catch p i m (m) e l (or any number of m, like pimmmmel
You can test any rule with this site: http://regexr.com/
Good luck!

**Comment by kangarko** [comment]
In a recent update, the operator 'before strip' has been improved, so you may now insert it under each rule you want to affect and all whitespaces will be stripped:

```
match <regex>
[...]
before strip \s*
[...]
```

**Comment by EvilOlaf** [comment]
Ah yes, great idea. Thanks
