### ISSUE TITLE
Whitelisting phrases.

### ISSUE THREAD

**Issue by wizy123** [kangarko/ChatControl-Pro#264]
im having an issue where i have "tits" as a warn word. people are typing "but its" or "isnt it" and its giving the warn. i want to know if we can whitelist phrases without removing the rule to search for the white spaces inbetween words. cause the aholes on my server like to use those white spaces alot. i see where you can whitelist phrases for Caps but not for the swear words themselves.

**Comment by x1p** [comment]
ignore string worldthatispermitted

**Comment by kangarko** [comment]
Hey,

I have updated the wikipedia with tips on how to whitelist certain words:

https://github.com/kangarko/ChatControl-Pro/wiki/Rules#whitelisting-phrases
