### ISSUE TITLE
Filter acting odd

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#266]
Hey there,

recently I noticed that some swear is not handled properly.

```
[18:20:42] [Async Chat Thread - #23/INFO]: MATCH: (spast|spasst)
[18:20:42] [Async Chat Thread - #23/INFO]: CATCH: s p a s t i s
```
The rule for this:
```
match (spast|spasst)
before strip \s*
handle as swear
```
The `swear` handler usually censors the detected text which did not happen here.

The same user tried another swear which has been handled properly:
```
[18:22:41 INFO]: MATCH: (f+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*z+(\W|\d|_)*e+(\W|\d|_)*)
[18:22:41 INFO]: CATCH: maul f o t z e
[18:22:41 INFO]: FINAL: maul *****
```

The matching rule:
```
# fotze
match (f+(\W|\d|_)*o+(\W|\d|_)*t+(\W|\d|_)*z+(\W|\d|_)*e+(\W|\d|_)*)
before strip \s*
handle as swear
```

As a side note what I found weird is that the first event was handled as `Async Chat Thread` while the 2nd one is logged as `INFO`. Both has been catched from the `latest.log`.

Thanks for taking a look into.

7.3.19

**Comment by kangarko** [comment]
Good notice, thanks! I'll probably get to it by Monday, ich hoffe das kein Problem ist :)

**Comment by EvilOlaf** [comment]
No worries about the delay

**Comment by EvilOlaf** [comment]
This may be a stupid question but has this issue already been addressed in one of the recent builds?

**Comment by kangarko** [comment]
Hey, honestly I don't know (I am on holidays I do a quick hotfixes only), can you please test to see if it's still present in the 7.4.7? Thanks!

**Comment by EvilOlaf** [comment]
Relax, enjoy your holidays. 
I'll test this somewhen next week.

**Comment by kangarko** [comment]
Thanks alright!

**Comment by EvilOlaf** [comment]
Issue not solved.

```
# test
match (test|tesst)
id TESTING
before strip \s*
ignore string \best
handle as swear
```

`test` got successfully censored
`t e s t` was detected but not censored

**Comment by EvilOlaf** [comment]
Excuse me? I did not comment anything?

**Comment by kangarko** [comment]
I removed comments of type "Thanks" / "I have holidays" in favor of more readibility when quick-reading.

**Comment by EvilOlaf** [comment]
Ah okey. Totally forgot about those comments. Never mind.

**Comment by kangarko** [comment]
Solved. Will be fixed in the next release in few days.

**Comment by EvilOlaf** [comment]
Nice.

**Comment by kangarko** [comment]
Released today. Sorry for the delay, I got distracted with a brand new plugin and was hoping to include Redisbungee support to ChatControl asap, unfortunately this got delayed. Thank you for your patience EvilOlaf!

**Comment by EvilOlaf** [comment]
Thank your for fixing this. I'll give it a shot ASAP.

**Comment by kangarko** [comment]
I have received some complaints since the update, and changed some logic. From my testing it still works but the logic underneath is different. Please let me know if you run into inconsistencies.

**Comment by EvilOlaf** [comment]
Will do. Probably tomorrow or something. Thanks for keeping me up to date.
