### ISSUE TITLE
Private Message Vanish Compatibility

### ISSUE THREAD

**Issue by SioWolf** [kangarko/ChatControl-Pro#269]
I use the PremiumVanish plugin and players can still message me when I am vanished. This allows players to detect whether you are invisible or if you've actually logged off.

**Comment by kangarko** [comment]
I have edited the plugin so when Bukkit says the sender cannot see the receiver, the message is not sent. This only works if PremiumVanish uses certain methods within the server. If it doesn't, we cannot fix that. If it does, it should work automatically.
