### ISSUE TITLE
Launch Error: Volanie nastaveni [...]

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl-Pro#270]
![efh fio 0njps5_cm xui91](https://user-images.githubusercontent.com/15712089/27369229-9a87187a-5689-11e7-85d7-19d1f5607e7d.png)

**Comment by kangarko** [comment]
Use the latest version.

**Comment by xyblues** [comment]
![image](https://user-images.githubusercontent.com/15712089/27811153-78a72694-6095-11e7-97a3-a8d0c46e16d9.png)
Still not working

**Comment by kangarko** [comment]
Are you running on localhost or a live server? Make sure your firewal allow internet access.

**Comment by kangarko** [comment]
I have tracked the cause of this issue and I am working on a fix.

**Comment by xyblues** [comment]
I'm in China, maybe there's a the Great FireWall.

**Comment by kangarko** [comment]
Yes it may be the cause. I have edited the plugin slightly, please test out the latest version now.

**Comment by xyblues** [comment]
It still doesn't work.
But the 7.3.5 version is working, and higher than the 7.3.6 version does not work.

**Comment by kangarko** [comment]
Please use the version **7.4.18**.

**Comment by xyblues** [comment]
![image](https://user-images.githubusercontent.com/15712089/29000616-1d23b832-7aa3-11e7-90d4-8bc6c945427e.png)
**It still doesn't work.**

**Comment by kangarko** [comment]
I see, thank you for the report and I am very sorry for the problems. I come home tomorrow so I'll look at it asap.

**Comment by xyblues** [comment]
Hello, is there anything new?
![image](https://user-images.githubusercontent.com/15712089/29502582-af978114-8663-11e7-8b7a-90078b2375ab.png)

**Comment by kangarko** [comment]
Hey, what's you user ID on SpigotMC.org please ? You can find it in your profile page at the url bar in the https://www.spigotmc.org/members/<yourname>.<your_id>/ format

**Comment by xyblues** [comment]
https://www.spigotmc.org/members/xyblue.145972/

**Comment by kangarko** [comment]
PM'd.
