### ISSUE TITLE
Redis support CC - BungeeControlBridge

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#271]
Please add redisbungee support.

BungeeControlBridge is installed on every (redis)bungee. However, swears are only broadcasted if the player and the staff (with the right permission) is connected on the same bungee.
Please add redisbungee support so the broadcast is redirected over all the connected RedisBungee servers.

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. I am leaving this open for the future.

**Comment by Beags** [comment]
Hey,
I would also love it if this was enabled to work on redisbungee.

**Comment by Fluxty** [comment]
We could also use support for this :)

**Comment by x1p** [comment]
6 months has passed and its not even on the roadmap.
According to our developer its as simple as adding a few lines of code. Maybe this will help to speed up the process?
https://github.com/minecrafter/RedisBungee/wiki/API

**Comment by Fluxty** [comment]
@x1p It seems to be working across multiple bungees for us, actually. Same with the chat channels. I haven't really fully tested it but it seems alright.

**Comment by x1p** [comment]
@Fluxty No I just see the notifications of the players connected to the same redis bungee as me.
This is very annoying for staff, because they miss crucial indications about bullying and intrusive sexual harassment.

**Comment by kangarko** [comment]
Added some basic support (https://github.com/minecrafter/RedisBungee/issues/56).

I could not do testing directly with Redis so please be kind to tell whether this works out or not ;)

@x1p @Fluxty @Beags THANK YOU for your patience!
