### ISSUE TITLE
Plugin Support / Suggestion

### ISSUE THREAD

**Issue by DuckCraftPvP** [kangarko/ChatControl-Pro#273]
Hi, I was wondering if you would add built in place holders for https://www.spigotmc.org/resources/legacyfactions.40122/ with colour relation specific system?

If you could that would be great since i know you have default factions support.

**Comment by EvilOlaf** [comment]
Just curios: Why should these placeholders be a part of CHC if they can be provided using PlaceholderAPI?

**Comment by kangarko** [comment]
Use PlaceholderAPI please.

**Comment by DuckCraftPvP** [comment]
It does not support faction colours yet. Like the factions have not added placeholderapi color tag support.

**Comment by kangarko** [comment]
There's basic support for {faction} from that plugin, see wikipedia for all native placeholders. 

Btw, the color relation placeholder is impossible with the current chat rendering system, I am sorry. I am plan to rewrite it in the summer, you can follow up on the roadmaps here at the Issue Channel.

**Comment by DuckCraftPvP** [comment]
Ok, Thank you! I look forward to the recode. 💯
