### ISSUE TITLE
@ Doesn't work , Someone can help me?

### ISSUE THREAD

**Issue by diolegend** [kangarko/ChatControl-Pro#275]
I have default settings , and the notify is enabled to true.

I type @Diolegend , it doesn't apper the color or the sound.

**Comment by kangarko** [comment]
Ensure you have **Sound_Notify.Notify_Only_When_Afk** to false, otherwise it won't work unless the player is afk. Also set **Sound_Notify.Cooldown_Seconds** to 0 to make it always work. If it won't work that way, post me your settings.yml
