### ISSUE TITLE
Rules on bungeecord

### ISSUE THREAD

**Issue by SeDark** [kangarko/ChatControl-Pro#277]
I would like to ask that you could create rules in bungeecord (if I want to have the same on all servers)

**Comment by EvilOlaf** [comment]
I solved this by removing all but one of CHC plugin folders on all Bungee servers and creating symlinks to the remaining config. So when you change a rule you can apply `chc reload` on all server and you are good to go.
The only downer is that you cannot apply `chc reload` to all servers with a single command.
My work around for this is a simple shell script which sends a particular command to all screen sessions.

**Comment by kangarko** [comment]
Brilliant solution EvilOlaf!

For now there's unfortunately no automatic synchronization of settings between servers. ChatControl is a Bukkit plugin, so all it does must be done with a Bukkit server. The BungeeControlBridge extension links only certain aspects of the plugin, but does nothing on its own.

In the future I am planning to add synchronization of both settings, logs and rules.
