### ISSUE TITLE
Players can use color into tell chat

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#279]
I noticed players can use any kind of characters into tell and private message (managed by chatcontrol)

**Comment by kangarko** [comment]
Hey, make sure players don't have the "chatcontrol.chat.format.*" permissions like "chatcontrol.chat.format.color".

If they don't, and you have Essentials, make sure players don't have the "essentials.chat.color" permission.

If it still doesn't work, then it's coming from another plugin.
