### ISSUE TITLE
Improvement bypass permission

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#280]
Is it possible to get a bypass like chatcontrol.bypass.fastmessages?

Use: certain players, like mods and helpers are permitted to chat superfast whithout getting points which result in mutes.

**Comment by kangarko** [comment]
Yes, please see the **Groups** option in settings.yml

**Comment by x1p** [comment]
With groups I can only make an exception like this:
    staff: 
      Message_Delay: 0
Where my question was to make an exception for the collecting of points if a message is within the range as defined like:
message delay = 1
collecting a point if message is sent within 2 sec.
This forces me to make the default delay to 2 sec and staff 1 sec. Workable, but not what I have asked.

**Comment by kangarko** [comment]
Would you like to disable warning points for your staff?

**Comment by x1p** [comment]
Yes, but preferable only the fastmessage warning points. Is that already built in somehow?
The message_delay cancels the original message. So this is no option. For now I just disabled any punishments. (It is not that bad....)

**Comment by kangarko** [comment]
Hey, in the next version, I'll add the "chatcontrol.bypass.warnpoints" permission to not receive warn points completely. It's pretty complicated to split the permission to parts since you can make your own warn points types many places around the plugin.

**Comment by x1p** [comment]
Understandable. This should work good enough in most cases.
Good work :+1:
