### ISSUE TITLE
Compatibility with essentials ignore list

### ISSUE THREAD

**Issue by Phoetrix** [kangarko/ChatControl-Pro#286]
Hello kangarko! 

Is it possible to add compatibility with Essentials ignore list of players ? (/ignore playername)
When I use EssentialsChat, ignored players messages is not showed. I want the same with ChatControl if it's possible.

Thank you very much. :)

**Comment by kangarko** [comment]
Hey,

the /ignore feature is planned. When it's done, I may add compatibility with Essential's /ignore command.
