### ISSUE TITLE
Error Spam in my console

### ISSUE THREAD

**Issue by MrJesseZ** [kangarko/ChatControl-Pro#287]
Hey kangarko,

I am getting a error spammed in my console. I am using bungeecord and I am getting al my servers this error. 

https://pastebin.com/HE01yXTQ

- Jesse

**Comment by kangarko** [comment]
Hey,

please post me your rules/ folder. You can archive it to a single .zip file and upload for example to expirebox.com

**Comment by MrJesseZ** [comment]
Hey kangarko, 

Here I got a link for you.

https://expirebox.com/download/98bad962339b32529f792e8b105818f4.html

**Comment by kangarko** [comment]
There's an error in your console at the server startup.

Open rules/rules.txt, scroll to the bottom and see this rule:

```
# NOTICE: Created using a command at 09.07.2017 18:24:50
# Blocks 'f*ck'
match (f+(\W|\d|_)**+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
handle as swear
```

This rule causes the problem due to the * letter in the fuck word. You don't need to need to create such rules, **or,** if you want to have it, replace the ** with \**.
