### ISSUE TITLE
Epic's Minecraft Language Filter Support?

### ISSUE THREAD

**Issue by KensonPlays** [kangarko/ChatControl-Pro#289]
Does Chat Control Pro support EpicATrain's RegEx word filter?

https://pastebin.com/QRKCWdzc <-- This is a very in-depth filter. Almost 3200 lines.

It does more than language, it can also filter stuff like hellll!!o and turn it into "hello."

I probably wouldn't need the full filter, but the language bit and anti-advertising bits would be used.

**Comment by kangarko** [comment]
Hey,

as far as I know, this filter is four years old. It is outdated including for the original PwnFilter plugin.

ChatControl shares similarities in syntax, but some operators are different or don't exist.

You can always compare the syntax and import the rules you need manually. The 'match', 'then deny', 'then warn' operators are the same, for instance (see the header in rules.txt file).

**Comment by KensonPlays** [comment]
Yea, I tried adding a simple modification to the filter yesterday and it wouldn't filter it out.

I copied 'boob' and tried making it 'boobs.'

It didn't seem to pick it up.

I put it right under the singular version of the word, and here is the code:
`# Blocks 'boobs'
match \b(b+(\W|\d|_)*o+(\W|\d|_)*o+(\W|\d|_)*b+(\W|\d|_)*s+(\W|\d|_)*)
handle as swear`

**Comment by kangarko** [comment]
Yes it won't match on my server either. It seems that the regex filter is disorded, because our filter has _ after the d|

`\b(b+(\W|\d|_)*o+(\W|\d|_)*o+(\W|\d|_)*b+(\W|\d|_)*)`

**Comment by KensonPlays** [comment]
I'd want the filter to block both singular and plural form of any of the foul language in the chat. Is that possible to do with a simple addition to each word in the filter?

**Comment by kangarko** [comment]
The filter in the top of my comment above will catch " boob" and anything that comes after it, which means that boobs, boobies boobz and other derivates are also being caught.

**Comment by KensonPlays** [comment]
You sure? It didn't seem to catch them when I was testing. I don't use OP in game, I do OP stuff from console, so its not permissions negating the filter. It worked with singular, but not plural. (on mobile for most of the day)
