### ISSUE TITLE
Ignore command

### ISSUE THREAD

**Issue by DJDan193** [kangarko/ChatControl-Pro#29]
You've probably gotten alot of requests for this. But can you add ignore command for players who don't want to see other player's chat

**Comment by tspringst33n** [comment]
Forgot an example Dan. 
Example:
PlayerA can do a command like `/ignore playerB` or `/chc ignore playerB` and all chat from playerB would be hidden from playerA.

**Comment by kangarko** [comment]
This is already planned with high priority.
