### ISSUE TITLE
Error Starting Up. MC 1.12

### ISSUE THREAD

**Issue by iTIsKeiFeR** [kangarko/ChatControl-Pro#290]
WARN java.lang.IllegalArgumentException: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
17.07 13:00:39 [Server] WARN at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
17.07 13:00:39 [Server] WARN at me.kangarko.chatcontrol.ChatControl.throw(SourceFile:529)
17.07 13:00:39 [Server] WARN at me.kangarko.chatcontrol.ChatControl.strictfp(SourceFile:476)
17.07 13:00:39 [Server] WARN at me.kangarko.chatcontrol.  .....coM6.onEnable(SourceFile:83)
17.07 13:00:39 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
17.07 13:00:39 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
17.07 13:00:39 [Server] WARN at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215)
17.07 13:00:39 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
17.07 13:00:39 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378)
17.07 13:00:39 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
17.07 13:00:39 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
17.07 13:00:39 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
17.07 13:00:39 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
17.07 13:00:39 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
17.07 13:00:39 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
17.07 13:00:39 [Server] WARN at java.lang.Thread.run(Thread.java:745)
17.07 13:00:39 [Server] INFO _   _                       _ 
17.07 13:00:39 [Server] INFO | | | | ___   ___  _ __  ___| |
17.07 13:00:39 [Server] INFO | |_| |/ _ \ / _ \| '_ \/ __| |
17.07 13:00:39 [Server] INFO |  _  | (_) | (_) | |_) \__ \_|
17.07 13:00:39 [Server] INFO |_| |_|\___/ \___/| .__/|___(_)
17.07 13:00:39 [Server] INFO |_|          
17.07 13:00:39 [Server] INFO !-----------------------------------------------------!
17.07 13:00:39 [Server] INFO Error loading ChatControl v7.4.11, plugin is disabled!
17.07 13:00:39 [Server] INFO Running on 1.12-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_91
17.07 13:00:39 [Server] INFO !-----------------------------------------------------!
17.07 13:00:39 [Server] INFO Error: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
17.07 13:00:39 [Server] INFO !-----------------------------------------------------!
17.07 13:00:39 [Server] INFO Disabling ChatControl v7.4.11

**Comment by EvilOlaf** [comment]
Duplicate https://github.com/kangarko/ChatControl-Pro/issues/270
