### ISSUE TITLE
Massive error

### ISSUE THREAD

**Issue by DuckCraftPvP** [kangarko/ChatControl-Pro#291]
https://hastebin.com/fefaxedafo.md

[20:49:51 INFO]: This server is running Paper version git-Paper-1146 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by EvilOlaf** [comment]
Is the internet access of your server restricted in any way?

**Comment by DuckCraftPvP** [comment]
no

**Comment by DuckCraftPvP** [comment]
api was down. its working again.

**Comment by kangarko** [comment]
Hey DuckCraftPvP!

I am very sorry for the issue. It lies in that I use some basic antipiracy solutions that are dependent on an external server. You were right, my hosting provider was experiencing downtimes. I am contacting the hosting as this is not the first time, or eventually change it so it is (more) stable. I apology for the inconvenience.

**Comment by DuckCraftPvP** [comment]
Thank you.

**Comment by DuckCraftPvP** [comment]
its down again.

**Comment by kangarko** [comment]
I am currently in the process of finding another hosting, it should take a few days before it is switched. I hope they at least maintain somewhat stability until then.

**Comment by DuckCraftPvP** [comment]
ok, Thank you. Seems to go down at night only. Its annoying though :P

**Comment by EvilOlaf** [comment]
I don't know how much resources the API actually needs but just as suggestion the OVH Cloud VPS series offers 99,95% SLA.

**Comment by kangarko** [comment]
Currently it's just a website hosting with some php scripts and static files, just a normal website would be. The API is quick but the Czech hosting provider fails to provide stable connection to the outland.

**Comment by DuckCraftPvP** [comment]
why dont u host it off ur pc then?

**Comment by kangarko** [comment]
That's practically impossible. My PC can't run 24/7 besides it would raise the electricity bill long above what I pay for the hosting :)

**Comment by DuckCraftPvP** [comment]
mine always run 24/7
