### ISSUE TITLE
AntiSpam don't work

### ISSUE THREAD

**Issue by OriginersMc** [kangarko/ChatControl-Pro#292]
Hello,

My chat, when you writte an ip or domain, it only delete dots (and plugin chatcontrol pro don't detect spam and prevent it)

How I can fix that?

I want say, how I can fix chat don't delete dots and allow chatcontrol do him work?

Have a nice day

**Comment by kangarko** [comment]
Hey OriginersMc & thank you for using Issue Tracker!

Please see this short tip and try whether it is related to your problem:
https://github.com/kangarko/ChatControl-Pro/wiki/Frequent-Problems#ad-filter-doesnt-work-all-dots-are-removed-from-domains-example-wwwgooglecom-becomes-www-google-com

I hope it will get solved quickly!

Cheers!

**Comment by kangarko** [comment]
I am closing this, please comment below if you're still experiencing issues!
