### ISSUE TITLE
Factions Placeholder Support 

### ISSUE THREAD

**Issue by FreeKillGR** [kangarko/ChatControl-Pro#294]
Is there any way to add support for the massivecraft factions placeholders?

i know i can download the faction extension from the ecloud but it doesnt support this (factions_relcolor) placeholder and also massivecraft factions placeholders have some other cool features like adding space after the placeholder or before if the placeholder is not empty.

Thank you for you time.

**Comment by kangarko** [comment]
Hey & thank you for using the Issue Tracker!

The current system does not allow relation placeholders, but this feature is on the road-map and will be implemented in the future:
https://github.com/kangarko/ChatControl-Pro/issues/267

Cheers!
