### ISSUE TITLE
Chatcontrol 7.4.12 breaks /Chatcolor plugin

### ISSUE THREAD

**Issue by Fonzee9** [kangarko/ChatControl-Pro#295]
After updating my players do /chatcolor &6 (works if opped..) and it says type a chatcolor instead of working after downgrading to 7.4.11 this problem was solved and people could use chatcolor.

Link https://www.spigotmc.org/resources/chatcolor-custom-plugin-from-hexacraft-network-great-donor-perk-eula-comliant.22470/

**Comment by kangarko** [comment]
Hey Fonzee9 & thank you for using the Issue Tracker!

I am very sorry for the issues, you are correct. I have fixed the problems in 7.4.13.
