### ISSUE TITLE
Swear censoring not functioning with DeluxeChat

### ISSUE THREAD

**Issue by Tsuser1** [kangarko/ChatControl-Pro#297]
With DeluxeChat we're having issues getting CHCPro to censor the chat, it gives a swear ID in global chat and even censors properly in PMs but refuses to censor global chat.

**Comment by EvilOlaf** [comment]
Did you try to lower the priority in CHC settings?

**Comment by kangarko** [comment]
Hey Tsuser1!

Please take a look at this quick article down below and try to adjust the priority of Checker. Make sure to try all the LOWEST, NORMAL, HIGHEST and even MONITOR priorities and the restart server after each change:
https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

**Comment by Tsuser1** [comment]
We are using the HIGHEST priority already.

**Comment by kangarko** [comment]
Have you tried changing according to my guidelines? Including MONITOR?


> ** Mon, 24 Jul 2017 00:18:24 -0700 - "kangarko/ChatControl-Pro" <chatcontrol-pro@noreply.github.com>, "kangarko/ChatControl-Pro" <reply@reply.github.com> **
>
> We are using the HIGHEST priority already.
>

**Comment by Tsuser1** [comment]
Yes, but I'll try again **just to be sure** that it isn't working properly.

**Comment by EvilOlaf** [comment]
HIGHEST priority means that CHC will process the chatevent LAST, not FIRST. To fix this try LOW or LOWEST priority.

**Comment by Tsuser1** [comment]
I'll give it a go
