### ISSUE TITLE
Users can make spam

### ISSUE THREAD

**Issue by OriginersMc** [kangarko/ChatControl-Pro#298]
Hello,

Users, can make send ips or links.
If user write: ANYTEXT IPSERVER/DOMAIN ANYTEXT
it allow spam/domain.

How I can fix that? 

Problem I was say:
![image](https://user-images.githubusercontent.com/13259577/28522026-9c9d62a2-7076-11e7-9f88-308b872210d7.png)

My chatcontrol rules configuration:
![image](https://user-images.githubusercontent.com/13259577/28522044-b8999e44-7076-11e7-9d9f-a3072057bb74.png)

Have a nice day

**Comment by EvilOlaf** [comment]
It seems like you explicitly allowed those domain names using `ignore string`.

**Comment by OriginersMc** [comment]
I want block that spam. Now, it only detect if users only say ip or domain.
But, if user add text beafoure or then ip/domain chatcontrol don't detect
it.

What I need do to fix that?

El dia 24/07/2017 2:21 p. m., "Very Evil Olaf" <notifications@github.com>
va escriure:

**Comment by EvilOlaf** [comment]
That's odd. The way the rule is designed advertisements gets detected regardless if there is any text or whatever added before or after.
Do you use any other chat plugins hat might interfere with CHC?

**Comment by OriginersMc** [comment]
I don't use any other chat plugin.

Where I need add "ignore string" to prevent spam?


Thanks for you time!

**Comment by EvilOlaf** [comment]
You simple don't. 
As described in the header of your `rules.txt` the `ignore string` pattern is used to explicitly whitelist certain URLs. For example the URL to your own homepage which you probably do not want to censor.

**Comment by OriginersMc** [comment]
Sorry, I use factions chat. I will try disable it and check if it work.

Have a nice day

El dia 24/07/2017 2:46 p. m., "Originers Mc" <originersmc@gmail.com> va
escriure:

I don't use any other chat plugin.

Where I need add "ignore string" to prevent spam?


Thanks for you time!

**Comment by EvilOlaf** [comment]
CHC can coexist with most other Chat solutions. Play around with the listener priorities option that CHC pro offers. To get an idea how this works check out this wiki article: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

In any case it is always a good idea to use only one of such plugins (if possible) to prevent irregularities.

**Comment by OriginersMc** [comment]
Hello,
I disabled factions chat (now is ussing EssentialsChat).
It continue without work.
If user add text then IP/DOMAIN, chc don't block it.

How I can fix that?

Best regards, Alex

El dia 24/07/2017 2:52 p. m., "Very Evil Olaf" <notifications@github.com>
va escriure:

**Comment by kangarko** [comment]
Have you tried changing the priority of the Checker as Olaf suggested? Try LOWEST, HIGHEST and even MONITOR priority and **restart** the server, do _not_ reload, after each change.

**Comment by OriginersMc** [comment]
Who priority I need use?

El dia 26/07/2017 10:41 p. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by kangarko** [comment]
Try MONITOR first, then HIGHEST and finally LOWEST. Restart server after each change. If it starts to work, leave it that way.

**Comment by OriginersMc** [comment]
Ok, when I can, I will try it :)

Have a nice day

El dia 27/07/2017 12:28 p. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by OriginersMc** [comment]
Hello, I tryed all levels you suggered me. User continue say spam of
ip/domain if it add an text then spam.

Best regards, Alex

El dia 27/07/2017 12:29 p. m., "Originers Mc" <originersmc@gmail.com> va
escriure:

**Comment by kangarko** [comment]
Can users make spam with other messages than those containing your server domain?

Also, do you mean that you want to them to wait certain amount of time before their next message, or not being able to write two similar messages?

Either way, please upload your settings.yml to pastebin.com

**Comment by OriginersMc** [comment]
Hi, users can writte spam if there writte any text then spam, example:
- Hello my server mc.anserver.com (CHC BLOCK THIS MESSAGE)
Hello my server mc.anserver.com join now (CHC DON'T BLOCK IT)

That is my problem.
Have a nice day


El dia 31/07/2017 11:32 a. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by kangarko** [comment]
Post me your settings.yml

**Comment by OriginersMc** [comment]
Oh yes, take it.

El dia 31/07/2017 11:46 a. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by OriginersMc** [comment]
Hello, are you here? I waiting an answer...

El dia 31/07/2017 12:24 p. m., "Originers Mc" <originersmc@gmail.com> va
escriure:

**Comment by kangarko** [comment]
I need to see your settings.yml so I can determine the cause.

**Comment by OriginersMc** [comment]
Hello, I attached days ago, but I attach it again:


El dia 05/08/2017 8:28 p. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by kangarko** [comment]
I can't see any attachments, sorry. You can just upload them to expirebox.com or to pastebin.com

**Comment by OriginersMc** [comment]
https://pastebin.com/3bE2jQkf

El dia 05/08/2017 8:38 p. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by OriginersMc** [comment]
Hi, any solution for my problem?

El dia 05/08/2017 8:56 p. m., "Originers Mc" <originersmc@gmail.com> va
escriure:

**Comment by kangarko** [comment]
Hey & sorry for the delay (I was in the outland).

The solution:

1. Open ChatControl/rules/rules.txt file.
2. Find the Domain/URL filter (usually around line 74) and replace everything that is there with:

```
# Domain/URL filter.
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b
ignore string minecraft:|youtube.com|imgur.com
id 2
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement
```

**Comment by OriginersMc** [comment]
And with ip filter same?

El dia 08/08/2017 8:45 p. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by kangarko** [comment]
No you only need to update the domain filter as it was the only filter that needed rework.

**Comment by OriginersMc** [comment]
Ok

El dia 08/08/2017 8:50 p. m., "kangarko" <notifications@github.com> va
escriure:

**Comment by OriginersMc** [comment]
Hello,

Actually I've
`# Domain/URL filter.
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b
ignore string minecraft:|youtube.com|imgur.com
id 2
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement`

If I want block new domains, for example .nu, .io, .gs, where I need writte?

have a nice day

**Comment by kangarko** [comment]
Answered on your new ticket.

**Comment by OriginersMc** [comment]
Hi!

When I restart my server, plugin CHC don't block any spam and don't do
anything...

How I can fix that?

My settings plugin:
https://paste.originersmc.com/19/

My rules plugin:
https://paste.originersmc.com/20/



2017-09-05 21:29 GMT+02:00 kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
Hey, please post me your server startup log.

**Comment by OriginersMc** [comment]
Hi!

How I can add the next rule:
Prevent use &l and &k on command /rename, /relore, /setname, /setlore

I wait impatient you answer.

2017-12-04 7:51 GMT+01:00 kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
Hey, that would be:

```
match \/(rename|relore|setname|setlore) .*(&l|&k)
then warn Characters &-l and &-k are blocked in this command.
then deny.
```

**Comment by OriginersMc** [comment]
Ok, thanks!

**Comment by OriginersMc** [comment]
Hi,

When I add that rule, and try use
/rename name1

Without &l or &k characters, it deny command...

2017-12-08 19:49 GMT+01:00 Originers Mc <originersmc@gmail.com>:

> Ok, thanks!
>

**Comment by OriginersMc** [comment]
Solution?

2017-12-08 20:17 GMT+01:00 Originers Mc <originersmc@gmail.com>:

> Hi,
>
> When I add that rule, and try use
> /rename name1
>
> Without &l or &k characters, it deny command...
>
> 2017-12-08 19:49 GMT+01:00 Originers Mc <originersmc@gmail.com>:
>
>> Ok, thanks!
>>

**Comment by kangarko** [comment]
Hello,

please set **Regex_Strip_Colors** to **false** in settings.yml.

**Comment by OriginersMc** [comment]
Hi!

I try block ips, but it don't work.
I've the next:
# IP filter.
# (Notice the operator strip which removes specified characters BEFORE the
message is checked.)
match
\b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
id 1
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]|\s*
handle as advertisement

If you add text beafoure IP (192.168.1.1 for example), it don't block.
Solution?

2017-12-09 14:21 GMT+01:00 kangarko <notifications@github.com>:

**Comment by OriginersMc** [comment]
Hi!

I try block ips, but it don't work.
I've the next:
# IP filter.
# (Notice the operator strip which removes specified characters BEFORE the
message is checked.)
match \b[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}
(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(
dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}\b
id 1
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]|\s*
handle as advertisement

If you add text beafoure IP (like "hello 192.168.1.1" for example), it
don't block. Solution?


2018-02-16 15:24 GMT+01:00 OriginersMc <originersmc@gmail.com>:

**Comment by kangarko** [comment]
Sorry I don't see any obvious mistake, and I right now don't have time configuring individual regexes. Regular expressions are international universal programming language so you can search google or ask out at Spigot forums.

**Comment by OriginersMc** [comment]
You can't say me solution please?
That is only problem I've.

2018-02-22 12:57 GMT+01:00 kangarko <notifications@github.com>:
