### ISSUE TITLE
Not compatible with Denizen

### ISSUE THREAD

**Issue by C4BR3R4** [kangarko/ChatControl-Pro#299]
ChatControl don't compatible with https://www.spigotmc.org/resources/denizen.21039/ plugin.
When you write to an NPC, it receives no response.
No errors.

**Comment by kangarko** [comment]
Hey,

please try to remove ChatControl first to test whether it is the absolute cause of the problem.

If it is, please read this quick article on priorities and try changing the priorities of both Listener and Checker to LOWEST, HIGHEST and MONITOR. Restart, **do not reload**, after each change.
https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
