### ISSUE TITLE
Message of the Day

### ISSUE THREAD

**Issue by xikage** [kangarko/ChatControl-Pro#3]
Allow people to set up a "Message of the Day" message that will fire once when a player logs on, only to that player, maybe with a configurable delay option.

**Comment by kangarko** [comment]
MoTD, Death Messages and more is planned.

**Comment by rErEaT** [comment]
nice, would be nice :D

possible to make compatible with BossBarAPI? :D

**Comment by Sikatsu** [comment]
I hear DeathMessages? /sub

**Comment by kangarko** [comment]
There are planned since 2015, but I never get to them, really.

**Comment by Sikatsu** [comment]
I see! I had a couple of Death Messages plugins but they get discontinued often, if it's integrated in ChatControl it will spare a plugin too. Being able to add more deathmessages for a certain death cause would be nice, so it picks a deathmessage randomly.

**Comment by kangarko** [comment]
Yeah I am planning to make them as advanced as the world broadcaster is, plus random messages.

**Comment by Sikatsu** [comment]
Awesome! Waiting for that feature, it would be a really nice addition!
