### ISSUE TITLE
Support for longer sentences

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#30]
The usual limit for messages or commands in chat is 100 characters. This can only be bypassed by using the console or command blocks.

My idea was to add an option to split messages longer than 100 characters into multiple messages and let CHC them glue together and send the new built string.

A command will put the chat for the executing player into collect mode until a special character, string or another command completes the input. Like this:

`/longmsg` - collecting messages till `EOF`
Player enters `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt`
Then player enters `ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et`
As the last message he enters `EOF` which will disable collect mode and sends the two messages stuck together as one to the chat.
The chat output will be `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et`

As a minor note: There should be an extra space added by CHC to the end on each of the input lines. Otherwise the last word and the first word might stick together.

Thanks for reading.

**Comment by kangarko** [comment]
Good idea. Marking as an long-future improvement.
