### ISSUE TITLE
Inconvenient problem

### ISSUE THREAD

**Issue by Neclok** [kangarko/ChatControl-Pro#300]
You should do like the other chat plugin ... use the /g to use the global ...

**Comment by kangarko** [comment]
Hello,

please read this quick article on shortening commands:

https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands

**Comment by Neclok** [comment]
Making the command is not the problem but you have the option to block the! No, so it's no good for me to create a command and for a delay if they can still use the "!"
