### ISSUE TITLE
Problem editing chat.txt

### ISSUE THREAD

**Issue by juju78660** [kangarko/ChatControl-Pro#301]
Hello,
I'm having a problem when I try to edit chat.txt, it says "Cannot define operator when nothing is beind created! File: ... Line 0: '[strange thing]#---...".
I don't know what's wrong, can you help me?
Thanks.

**Comment by kangarko** [comment]
Hello,

please read this quick article and save the file under the correct encoding:

https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
