### ISSUE TITLE
Removes hover menu from DeluxeChat

### ISSUE THREAD

**Issue by Tsuser1** [kangarko/ChatControl-Pro#302]
ChatControl Pro seems to be removing the hover menu from our chat, I have tried all the priorities and still the issue is occurring. The message comes out properly formatted, just inherently non-JSON.

**Comment by kangarko** [comment]
Hello,

ChatControl and DeluxeChat cannot format the chat at the same time. You can either use ChatControl for a) interactive formatter or b) chat channels, while DeluxeChat do not touch the chat, or vice versa.
