### ISSUE TITLE
Incovenient Problem

### ISSUE THREAD

**Issue by Neclok** [kangarko/ChatControl-Pro#304]
***I**: You should do like the other chat plugin ... use the /g to use the global ...
***You**: Hello,

please read this quick article on shortening commands:

https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands
***I**: Making the command is not the problem but you have the option to block the! No, so it's no good for me to create a command and for a delay if they can still use the "!"

**Comment by Neclok** [comment]
In addition to that global chc is global bungee, not the global server what would it be with "!" ...

**Comment by kangarko** [comment]
I am sorry but I partially don't understand the question.

If you have ranged chat enabled, either in chat channels or in Chat.Formatter.Ranged_Mode in settings.yml, players may prepend their message with ! to write globally. This is **not** sent to Bungee (unless configured in the chat channel). Only the command "/chc g" for global chat sends the chat to the Bungee.

**Comment by kangarko** [comment]
I assume the problem has been resolved, please comment below if not.

**Comment by Neclok** [comment]
That's what I'm trying to say, it's not supposed to be! " To speak in global should be / global with aliase of / g. Should have an option, this "!" Has passed from time to time.

**Comment by kangarko** [comment]
Hey, to clarify, there are two global chats actually:

1. The per-server global chat: This is when the ranged chat is enabled and the message starts with "!".
2. The bungee global chat: This is run by the command "/chc global" or "/chc g".

**Comment by Neclok** [comment]
The per-server global chat: This is when the ranged chat is enabled and the message starts with "!".
It was meant to be "/g <message>".

**Comment by Neclok** [comment]
...

**Comment by Neclok** [comment]
@kangarko...

**Comment by kangarko** [comment]
The /g is reserved for the fact that many people make an alias to it from "/chc g". ChatControl will keep on using the "!" syntax for the near future, however I am open to changes in the future.
