### ISSUE TITLE
Custom fake messages

### ISSUE THREAD

**Issue by dartasen** [kangarko/ChatControl-Pro#305]
Is it possible to add custom fake messages (in messages.yml for example) ? Without using chat format.

**Comment by kangarko** [comment]
You can use the "/chc fake" command **without** chat formatter or a format and you can customize the outlook of the messages in the messages.yml file you've mentioned.

```
Join_Message:
  Message: Hello everyone! {player} has joined"
```

**Comment by dartasen** [comment]
Oh thanks, I didn't see that.

Solved!
