### ISSUE TITLE
Chat format for Staff alert?

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#306]
I would like to know if there is a way to add these 3 interactive buttons to warn/ban/mute to spam server allerts,
![immagine](https://user-images.githubusercontent.com/3611852/28757965-9a6ca494-758e-11e7-9082-8feabd2a1d5d.png)
I know how do these via handler but i can't setup these only for these type of messages managed by handlers, with Staff alert
![immagine](https://user-images.githubusercontent.com/3611852/28757976-d871e164-758e-11e7-9a0d-73586d412c26.png)

If is possible, how i do it?

**Comment by kangarko** [comment]
What plugin is that?

ChatControl has "Permission" part in chat.yml, see the comments for examples. But currently this is determined from the player, meaning he will be able to see the boxes as well. An update that will make it possible to only show for admins, is planned.

**Comment by xion87** [comment]
is your plugin, i used the chat.yml format for admin chat, and added these three parts that "suggest the command" for warn, mute or ban that player

`
  Admin_Format:
    Parts:
      message:
        Message: '&3STAFF&b▐&3{player} &b{message}'
        Hover_Event:
          Action: SHOW_TEXT
          Values:
          - '&eNick: {nick}'
          - '&eNome: &f{player}'
      Warn:
        Message: "[Warn]"
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/warn {player} "
      Mute:
        Message: "[Mute]"
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/mute {player} 1h "
      Ban:
        Message: "[Ban]"
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/tempban {player} 10d "

`

**Comment by kangarko** [comment]
Hey, I am sorry I have to disappoint you, but the advertising alert does not support those formats. Those are only for the chat formatter.

**Comment by xion87** [comment]
there is a way for make these configurable (like in chat.yml) would be cool :)

**Comment by kangarko** [comment]
It's possible to customize them in handlers.yml, but without the JSON support for now.

**Comment by xion87** [comment]
any plain to add it in future?
