### ISSUE TITLE
ChatControl Pro should keep peoples chatcolors for :) and other stuff.

### ISSUE THREAD

**Issue by Fonzee9** [kangarko/ChatControl-Pro#307]
If i type a sentence and add a emoji like <3 the chatcolor turns white and i was wondering if you could make it so it keeps the chatcolor that chatcolors plugins give.

**Comment by Fonzee9** [comment]
People also lose there chatcolor from auto correct so if i type i am gonna it will type i am going to with no chatcolor

**Comment by kangarko** [comment]
Hello,

please set **Regex_Strip_Colors** to false in settings.yml
