### ISSUE TITLE
Pull rules from file location

### ISSUE THREAD

**Issue by BlackBeltPanda** [kangarko/ChatControl-Pro#308]
Hello,

I use ChatControl Pro on multiple servers and would love the option to specify a file location for the different rule configurations. Currently I have to apply any changes to each rule file on each server. I think a great way to make it work would be to first pull from the specified custom location and then append any rules in the default ChatControl plugin rules directory afterword (assuming they're different). This would give server owners the ability to specify rules that apply to all servers (like a swear filter) while also adding in specific rules for each server (like an automated help system).

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. I plan a system not exactly as you describe, but it will be a synchronization between servers under a bungeecords, and with your suggestion I can just include rules/bungee.txt file with the rules to be synchronized. Does that sound good? :)

**Comment by BlackBeltPanda** [comment]
As long as it accomplishes the goal of only having to configure rules in one place, while also being able to append to them per-server, I'm happy with whatever method. =)

**Comment by kangarko** [comment]
Addressed in https://github.com/kangarko/ChatControl-Pro/issues/308
