### ISSUE TITLE
Spy on Signs and Books

### ISSUE THREAD

**Issue by TastyBlueberry** [kangarko/ChatControl-Pro#316]
We are able to spy on commands but unfortunately we can't spy on signs and books. It would be really awesome if you could implement a feature like this. So, if someone types text on a sign or in a book, the people with the right permission can read in their chat what the player typed on the sign or in the book.

**Comment by kangarko** [comment]
I see, sounds like a great suggestion!

**Comment by Tsuser1** [comment]
I can see this being a great feature I'd use frequently

**Comment by kangarko** [comment]
Addressed in https://github.com/kangarko/ChatControl-Pro/issues/343

**Comment by kangarko** [comment]
Thanks, I will check it out!
