### ISSUE TITLE
[Critical] Plugin stopped loading on clean server

### ISSUE THREAD

**Issue by UberMC** [kangarko/ChatControl-Pro#317]
Hi,

No plugins other then Chat control, regenerate clean ChatControl folder.
https://hastebin.com/akibowizut.md

No ChatControlPro versions are working. On my dedicated servers or home computer.

**Comment by UberMC** [comment]
tried 1.12 and 1.12.1
stopped working suddenly.

**Comment by EvilOlaf** [comment]
```
 The enum 'EventPriority' does not contain 'MON?TOR'! Available values: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
```
Check for this typo in your `settings.yml`

**Comment by UberMC** [comment]
It's not that, it's some kind of DRM

**Comment by kangarko** [comment]
Closing, see https://github.com/kangarko/ChatControl-Pro/issues/315#issuecomment-322337719
