### ISSUE TITLE
Issue: Sudden change in mechanics for special character blocking

### ISSUE THREAD

**Issue by Tsuser1** [kangarko/ChatControl-Pro#318]
So in ChatControl 7.4.20 our emoji system (which uses special characters) worked fine, now in version 7.4.21 there appears to have been a change where special characters are denied **after** the rules have been parsed. An option to change this functionality would be great.

**Comment by Tsuser1** [comment]
Screenshots proving this issue:
http://i.imgur.com/XqE5on2.png **Working, 7.4.20**
http://i.imgur.com/4fCtPdB.png **Not working, 7.4.21**

**Comment by kangarko** [comment]
Hey,

if the sudden change appeared without altering ChatControl, it's not coming from ChatControl. ChatControl does not by default include the message in any of its files.

**Comment by Tsuser1** [comment]
Well the issue is that our custom configuration suddenly stopped working
once we updated, were there any unlisted changes?

**Comment by kangarko** [comment]
How it stopped working? Any errors? I always list every change except for code cleanups.


> ** Fri, 18 Aug 2017 22:21:34 +0000 (UTC) - "kangarko/ChatControl-Pro" <chatcontrol-pro@noreply.github.com>, "kangarko/ChatControl-Pro" <reply@reply.github.com> **
>
> Well the issue is that our custom configuration suddenly stopped working
> once we updated, were there any unlisted changes?
>

**Comment by Tsuser1** [comment]
No errors or anything, just randomly stopped working and oddly enough fixed
itself two days later. I checked the file permissions and the configuration
files hadn't been modified in two weeks!

**Comment by kangarko** [comment]
Was the other parts of the plugin working or was the entire plugin disabled? I would suggest that you check out the startup logs for errors from these days. But if it's working right now, I assume it will continue to work.

**Comment by Tsuser1** [comment]
Actually its stopped working again and this time for good. It looks like
operators have no issue with it but players do (bypass permission I
assume). There is no errors on startup and it works fine with older
versions.

**Comment by kangarko** [comment]
May I see the effective parts of you emoji system?

Operators have no issue and players do? Shouldn't it be the opposite? (Because OP's have bypass by default, not the players).

**Comment by Tsuser1** [comment]
I know, it seems counterintuitive, here's an excerpt of the handlers from chat.txt:
```
match \:irritated\:
require perm chatcontrol.emojis.ultra
then replace （♯▼皿▼）

match \:rageface\:
require perm chatcontrol.emojis.ultra
then replace （♯⓪益⓪）

match \:annoyed\:
require perm chatcontrol.emojis.ultra
then replace （ノಠ益ಠ）ノ
