### ISSUE TITLE
Handlers.yml modifications

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#319]
Trying to make my own section like swear. In my case with the exception with:
    Warn_Points: swear 0
But ChatControl can't handle zero points. The plugin crashes:
    Report / Points must be positive!
Commenting out this line also results in a crash.

**Comment by x1p** [comment]
Once crashed it keeps crashing no matter what. After server reboot: committing out this line seems to work.

**Comment by kangarko** [comment]
You can't add 0 points, simply comment this line out or remove it completely.
