### ISSUE TITLE
Color format URLS in chat.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#321]
Can you give us an option to color format URLS in chat. so they show up with a color code we can pick.
Also Ive used this custom regex URL for a long time, you may want to update yours, mine covers more TLD's.

```

# Domain/URL filter.
# ROK - Added new filter to find http:// like urls
match (?:^|[^a-z])https?:(?!//(?:\w+\.)?piratemc\.com)
id 7
handle as advertisement

# ROK - Added new filter to find domain.me like urls without matching, me english
# You can add new domains to be blocked by inserting '|your_domain' after '|me' (e.g. '|me|io' for also blocking '.io' domains)
#match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|ru|net|org|de|jp|uk|br|pl|in|it|fr|au|info|nl|cn|ir|es|cz|ca|biz|ua|eu|za|kr|co|gr|ro|tw|se|vn|mx|ch|tr|at|be|hu|tv|dk|me|ar|us|no|sk|fi|id|cl|xyz|nz|by|pt|ie|il|kz|my|hk|cc|lt|sg|io|edu|su|pk|bg|th|lv|hr|pe|rs|az|ae|tk|ph|si|club|ee|pro|ng|mobi|asia|ws|xxx|gl)\b
match (?<=^|[^\w\-])[\w\-]+\.(com|ru|net|org|de|jp|uk|br|pl|in|it|fr|au|info|nl|cn|ir|es|cz|ca|biz|ua|eu|za|kr|co|gr|ro|tw|se|vn|mx|ch|tr|at|be|hu|tv|dk|me|ar|us|no|sk|fi|id|cl|xyz|nz|by|pt|ie|il|kz|my|hk|cc|lt|sg|io|edu|su|pk|рф|bg|th|lv|hr|pe|rs|az|ae|tk|ph|si|club|ee|pro|ng|mobi|asia|ws|xxx|gl)(?=$|[^\w\-\.])

# ROK - Permutations removed above but excluding the '.me' and '.us' suffix
match (?<=^|[^\w\-])[\w\-]+(;|,|-)(com|ru|net|org|de|jp|uk|br|pl|in|it|fr|au|info|nl|cn|ir|es|cz|ca|biz|ua|eu|za|kr|co|gr|ro|tw|se|vn|mx|ch|tr|at|be|hu|tv|dk|ar|sk|fi|cl|xyz|nz|by|pt|ie|kz|hk|cc|lt|sg|io|edu|su|pk|рф|bg|th|lv|hr|pe|rs|az|ae|tk|ph|si|club|ee|pro|ng|mobi|asia|ws|xxx|gl)(?=$|[^\w\-\.])
id 8
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement
```

**Comment by kangarko** [comment]
Hello & thank you for the contribution!

I am not sure what you mean, you can try setting **Regex_Strip_Colors** to false so colors are not removed and then you can simply replace the matched part with the group from your match $x (replace x with a number, try which is correct) and add some color to it.

**Comment by FrozenBeard** [comment]
When a player puts in a website in chat, www.piratemc.com (An allowed website) I would like that URL to be a different color, so it would be:

> useranme» Hello check out my post on &6www.piratemc.com&r something else
Where &6 and &r are automatically added to the url to give it color.

**Comment by kangarko** [comment]
I just typed off of my head, but the logic should be:

```
match <url regex>
then replace &6$1&r
```

try replacing $1 with $0, $2, $3 etc. to find the matching group.

**Comment by kangarko** [comment]
I am closing this in faith that this has been resolved.

**Comment by FrozenBeard** [comment]
Tried adding it on line 76, didn't do much, I tried all the parameters and nothing, it just displays the URl normally, im not sure im putting it in the right place.
https://pastebin.com/06wm1UzB

**Comment by kangarko** [comment]
Hey, you have to experiment with the regex, I got it somewhat working with:

    match ((http(s):\/\/|)piratemc\.com)
    then replace &6$1&r

I am sorry but I don't have time and resources to guide through regex creation, honestly I am not very good at themselves
