### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LiamtjuhhZ** [kangarko/ChatControl-Pro#322]
Hello, I love your plugin! But I have a question, can I allow players to make channels and invite people to their channel? So only invited people can join it. (unless they are op)?

**Comment by kangarko** [comment]
Hello and thank you!

Currently, only you can create new channels via the chat.yml file. The feature you suggested is in the to-do list, but unfortunately I already have many other tickets so I cannot add it so very near future. Thank you for your understanding.

**Comment by LiamtjuhhZ** [comment]
Hi, so if I add factions or towny, will it work then?

**Comment by kangarko** [comment]
It should! There's article about priorities in case it will interfere: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

**Comment by LiamtjuhhZ** [comment]
OK, thanks (and sorry if I'm annoying)
