### ISSUE TITLE
Country placeholders not working in Bungeecord?

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl-Pro#324]
Hi there!

I'm trying to use ChatControl Pro to set up a custom cross-server join message that says where the player is from ('&c{player}&6 comes from &c{country_name}&6.'). However, even with IP-forwarding enabled in my Bungee config, the country_name always ends up being "local", regardless of whether I have custom variables enabled or not in the ChatControl config

I have not yet been able to test if the case is the same when not using Bungee, since I am on the road.
Any ideas that might help me figure this out would be greatly appreciated.

**Comment by kangarko** [comment]
Hey,

by default, we get the IP address of the player via Bukkit libraries. I sadly have no control over how it is handled there, and thus don't know whether it provides accurate results.

To be really honest if it doesn't work there's little chance I can fix it atm, I highly recommend you try to look for a Bungeecord-only plugin that'll provide the same functionality.

**Comment by PsychoLynx** [comment]
Alright, thank you for the information! I will see if I can't find a working placeholder somehow!

**Comment by kangarko** [comment]
I wish you good luck :) I am sure there are good plugins for bungee out there. I apology again for the inconvenience.
