### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Neclok** [kangarko/ChatControl-Pro#326]
Even without permission, players can talk colorful so it's on the global {  **!(message)**  }

**Comment by kangarko** [comment]
Hey!

Can the players use colors in the normal chat? Also please verify that you don't have color permissions from Essentials.

**Comment by Neclok** [comment]
No, in ranged chat players can't talk with colors

**Comment by kangarko** [comment]
Do they have "chatcontrol.chat.format.color" permission?

**Comment by kangarko** [comment]
I cannot reproduce. Please check your permissions precisely. For me, players cannot use colors unless they have "chatcontrol.chat.format.color" permission.

![a](https://i.imgur.com/rDjuJg9.png)

**Comment by kangarko** [comment]
I assume this is a permission issue and that you could fix it with my advice. If not feel free to comment below.
