### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LiamtjuhhZ** [kangarko/ChatControl-Pro#327]
Hi I'm sorry if im silly or annoying, but this is my last question, can I disable admin chat and: only enable
- towny/faction
- near
- normal chat
?

**Comment by kangarko** [comment]
I assume you're talking about Chat Channels. In that case, simply open up the chat.yml file and remove the admin chat channel completely.

The native "/chc ach" you can't disable, but you can simply not give anyone permission to use it.
