### ISSUE TITLE
Placeholder support for BungeeControlBridge?

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl-Pro#328]
Hi again!

So I'm back now with a custom commissioned placeholder for showing player GeoIP and it works fantastic with ChatControl in the Spigot side of things, however, I am finding that I am unable to use any placeholders (even Chatcontrol's internal ones) in BungeeControlBridge's config (with the exception of {player}). 

Tl;dr Is there any way to add PlaceholderAPI / other support for messages originating from BungeeControlBridge?

**Comment by kangarko** [comment]
Hey,

it's basically like a flowing river downstream, where BungeeControlBridge cannot see the things above (ChatControl).

In order to do that, I'd need to copy the entire code responsible for this.

Btw, is PlaceholderAPI also a bungee-only plugin? If it is, then it's way simpler to add.

**Comment by PsychoLynx** [comment]
PlaceholderAPI doesn't seem to want to run on the Bungee side of things, unfortunately - just Spigot. I was hoping there'd be some way the message could travel downstream with some sort of flag that CC can pick up and say "Hey, that's a placeholder!" and then replace the part on the Spigot side, but I don't know if that's possible or efficient.

**Comment by kangarko** [comment]
Hey,

I believe it's possible, although I have no experience doing it. Currently I am preparing a brand new plugin and there's bunch of things in the real life going on, so I have to be really honest and say I cannot add it in the near future. Thank you very much for your understanding.
