### ISSUE TITLE
DiscordSRV  - broken hook

### ISSUE THREAD

**Issue by osimer** [kangarko/ChatControl-Pro#334]
Hi there,
discordsrv debug: https://gist.github.com/873eab7ee7df5f16f89f5fc47a414eb7
chatcontrolpro config: https://pastebin.com/adK8iwpF

I have ChatControlPro and DiscordSRV, but synchronization is broken. I want to synchronize channel "at" (ingame) to channel 316311386---5 on discord, but it does not work at all.

**Comment by kangarko** [comment]
I am currently rewriting this plugin, will look upon it when it's done :)

**Comment by osimer** [comment]
When approximately it will be done?

**Comment by kangarko** [comment]
As soon as possible. Few days at max.

**Comment by kangarko** [comment]
@osimer, hello, the new release is out, please make sure to test it.

**Comment by osimer** [comment]
It does not work and this was why we bought this plugin. We are switching to VentureChat.

**Comment by kangarko** [comment]
I am closing this. I cannot personaly test Discord but I had a customer reporting it working. Here is a general advice for troubleshooting:
* **Ensure the channel names are exactly the same as in channels.yml and your discord settings.**
* Ensure the ChatControl printed out that DiscordSRV was recognized in the console during start-up.
* Ensure that no errors are in the console and you are running the latest DiscordSRV.
