### ISSUE TITLE
Different reply behavior 

### ISSUE THREAD

**Issue by domas9000** [kangarko/ChatControl-Pro#336]
I recently started using the private messaging system of ChatControl and the reply function only replies to the last message received, so I have a little suggestion - add different reply behaviors:
in the config you would be able to set the behavior (something like reply-bahavior: 1, 2 or 3).

1 would reply to the last message you received (as it works now)
2 would reply to the last person you sent a private message
3 would reply to the last message you were involved in (either you sent one or got one)

**Comment by kangarko** [comment]
Hey, this is a feature by logic and proper linguistics. The /reply can only be used when you **receive** the message, not send one.
