### ISSUE TITLE
Block domains in ChatControl

### ISSUE THREAD

**Issue by OriginersMc** [kangarko/ChatControl-Pro#337]
Hello,

Actually I've
```
# Domain/URL filter.
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(c(| +)o(| +)m|o(| +)r(| +)g|n(| +)e(| +)t|c(| +)z|c(| +)o|u(| +)k|s(| +)k|b(| +)i(| +)z|m(| +)o(| +)b(| +)i|x(| +)x(| +)x|e(| +)u|m(| +)e|i(| +)o)\b
ignore string minecraft:|youtube.com|imgur.com
id 2
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]
handle as advertisement
```

If I want block new domains, for example .nu, .io, .gs, where I need writte?

have a nice day

**Comment by kangarko** [comment]
Hey,

you can add new domains after the **|i(| +)o)**\b

For example, if you want to add nu domain, just write:

|i(| +)o)**|nu**\b

Btw, the io domain is already blocked.
