### ISSUE TITLE
Chat color issues

### ISSUE THREAD

**Issue by IronMangos** [kangarko/ChatControl-Pro#340]
I suspect this may be caused by an issue similar to the Discord synchronization issues previously mentioned. I am using a chat color plugin that changes your chat formatting with a gui menu. I'll link it here: https://www.spigotmc.org/resources/chatcolor.1546/

However, to my frustration after switching over from ChatControl to ChatControl Pro, this plugin no longer worked. I find that if I use a single global channel all works as intended, however switching my config to multiple channels prevents it from working at all, though I assume the plugins should still work together nicely with channels.

Was hoping you'd have some insight into the problem, knowing the code as you do. I use this function as a donor perk on my server, so I'd like to get this back up as soon as possible.

Thanks in advance!

**Comment by kangarko** [comment]
Hey,

I recommend you wait for the big update 7.5.0, and then install PlaceholderAPI and use the variable {chatcolorplus_namecolor} in formatting.yml file (upcoming file) in your formats to inject the color to the the message format.
