### ISSUE TITLE
Per Group Death Messages

### ISSUE THREAD

**Issue by PinoyLifeCraft** [kangarko/ChatControl-Pro#341]
Hello there @kangarko ,

Just like the chat range we can group them like
.faction:
.  - faction
.  - faction_the_end

Is it possible to set the death messages in that way?
**>** cuz kitpvp death messages is so annoying at creative :slightly_frowning_face:

**Comment by kangarko** [comment]
Hey,

you can just use the Permission key in the Conditions section in death messages and group them that way. I recommend you take a look at the default examples in messages.yml.
