### ISSUE TITLE
Error Quit Messages

### ISSUE THREAD

**Issue by PinoyLifeCraft** [kangarko/ChatControl-Pro#342]
Hello there @kangarko ,

I got this error after I put this placeholder -> {kitbattle_player_rank}

https://hastebin.com/poyihowozo.sql

**Comment by kangarko** [comment]
Hello,

I am very sorry, but as we can see from the line n. 14, the error is caused by PlaceholderAPI's kitbattle hook. I recommend you take contact with the developer of that expansion pack.
