### ISSUE TITLE
Factions Placeholder colour relation

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#344]
Hi, i just noticed, placeholder api added a recently these two placeholder on Faction MCORE: %rel_factions_relation%
%rel_factions_relation_color%

The problem if i try to use these with chatcontrol it will just show the code without nothing (instead must become the relation color based on relation of that faction)
Here there is the istructions https://www.spigotmc.org/resources/placeholderapi.6245/update?update=167267

Hope that you can implement it...

**Comment by kangarko** [comment]
Hey, this will be added in 7.5.0 :)
