### ISSUE TITLE
[7.5.0] AD_Info format

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#346]
Hi i noticed you added ad info format, but is not working, when a player spam i keep to see the classic warn on chat... how i do it? is buged?
  Ad_Info: 
    Info: 
      Message: |-
               &6&m----------------------------------------------
               &r              &7&o(( Messaggio di Spam! ))
               
                 &6x &eGiocatore: &f{player}
                 &6x &eMessaggio: &f{message}
    
    More_Info: 
      Message: |- 
               &r
                 &8[&9x&8] Mostra ulteriori info."
               &6&m----------------------------------------------
      Hover_Event: 
        Action: SHOW_TEXT
        Values:
          - "     &8~ &3Informazioni &8~     " 
          - "&3Time: &f{timestamp}"
      Click_Event: 
        Action: SUGGEST_COMMAND
        Value: "/ipban {player} spam server!"

**Comment by kangarko** [comment]
Please edit your handlers.yml file and redirect the warning message to the Ad_Info formatter as per https://github.com/kangarko/ChatControl-Pro/wiki/Handlers#player_warn_message

**Comment by xion87** [comment]
i have to use this in handler?
"Staff_Alert: Ad_Info"

**Comment by kangarko** [comment]
You must specify the permission first

Staff_Alert: chatcontrol.staff.alert Ad_Info

**Comment by xion87** [comment]
i figured that later, amazing it work!!!

**Comment by kangarko** [comment]
Good! Thank you :)
