### ISSUE TITLE
/tell Register Reply to Self

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#348]
There should be an option to use the essentials like messaging system.
/msg should set the recipient to the person they /msg.
(you could make this optional and it wouldnt be hard to implement) "msg-sets-reciever: true" for example. 
e.g.:
user1: /msg user2 
user3: /msg user1
user1: /r - goes to user2
user2: /r - goes to user1

**Comment by kangarko** [comment]
Hello,

ChatControl implements a system that makes sence in the human's world. You can reply to the last person from whom you have received the message. You cannot reply when you yourself send a message because that does not make any logical sence.

**Comment by LogGits** [comment]
Well its not really about logical sense its about convenience to the end-user (the players), which is far more important. Its such a simple thing to add and given that people are already used to it from essentials (plugin with over 10million downloads) it would make perfect sense to add it into ChatControl Pro. It is becoming such an inconvenience that players are getting annoyed. I like how flexible and functional this plugin is but its rather inconvenient that this simple thing isn't a feature. It would be an option in the settings to enable (true or false), all it does is if enabled make /msg set the user.

**Comment by kangarko** [comment]
I see your point. Yes, it is relatively easy to add locally, a bit harder on bungee but definitely possible. I leave this open for the near future implementation :)

**Comment by kangarko** [comment]
Pulled.
