### ISSUE TITLE
Inverse Variables.Vault.Multi_Prefix?

### ISSUE THREAD

**Issue by Madszinader** [kangarko/ChatControl-Pro#35]
**Examples:**
Default (what it is now)
![](http://i.imgur.com/BA6rtea.png)
The group "Ejer" has the weight 1 and the group "A" has the weight 1000 (its called calories in PEX xD)

Inverse 
![](http://i.imgur.com/ES1gopr.png)
The group "Ejer" has the weight 1000 and the group "A" has the weight 1

**The point with this is:**
I would like to have a section in the config where its possible to inverse the multi_prefix option.
And by inverse i mean: The group with the highest weight are first. (>)

**Comment by kangarko** [comment]
Hello,
I am sorry but this is not possible, because ChatControl is out of control of this. It only uses Vault to fetch groups, and Vault does not provide that info neither.
