### ISSUE TITLE
Announcement localisation issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#351]
The announcer says ". . . A N N O U N C E M E N T . . ." regardless of what i have set in the localisation file.

**Comment by kangarko** [comment]
Hey,

* what is your Locale key in settings?
* please stop your server, ensure you have the proper file in localization/ folder and start it again.
* ensure no errors appear in the console and you are on the latest version.

**Comment by LogGits** [comment]
Locale: en
the file is called: messages_en.yml

**Comment by kangarko** [comment]
That's odd, I just tested and it works fine for me. Does the plugin say 'Using locale from file: messages_en.yml' at startup?

Lastly, please try using Notepad++ to edit that file and save it using UTF-8 format (with or without BOM, try one at the time)

**Comment by LogGits** [comment]
It doesn't say 'using locale from file: messages_en.yml' on startup. I deleted the messages_en.yml inside the Localization folder and restarted the server. The weird thing is a new messages_en.yml file didnt generate.

**Comment by LogGits** [comment]
I found out the issue. It appears that i was using "Localization" instead of "localization". Sorry for the hassle i didn't know it was case sensitive.
