### ISSUE TITLE
NoCheatPlus kicks players if in multiple channels

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#352]
Since updating the testing environment to CHC 7.5.0 player getting kicked from NoCheatPlus for spam. This does not happen in 7.4.x. Rollin back to 7.4 fixes this.

When sending one message to global chat players get notification that they should stop spamming from NCP. This usually occurs when player really spamming four or five messages in chat in a short period of time. 
I am not sure how NCP detects this  but I assume that it listens to kind a PlayerChatEvent which might be fired multiples for each message since CHC 7.5.0

No CHC related output in console.

CHC 7.5.0 and 7.4.24
NCP 3.15.1-RC-sMD5NET-b1084
Tested on Spigot 1.10 (assuming this happens in any other version as well)

**Comment by kangarko** [comment]
Is the player in multiple channels? If so, we fire AsyncPlayerChatEvent for each message in each channel specialy via ChatControl.

**Comment by EvilOlaf** [comment]
If I am correct the player is in one channel only. However even the player IS in multiple channels this causes severe incompatibility with NCP.

**Comment by kangarko** [comment]
Oh, I never thought of that this will happen.  I am sorry.

I am on it.

**Comment by kangarko** [comment]
Resolved in 7.5.4 by adding an option to fire multiple events which is disabled by default.
