### ISSUE TITLE
[7.5.1] Colors codes don't work

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#353]
After the upgrade to 7.5.1 colors code in chat do nothing. I tryed also the new permission and seem do nothing

**Comment by LogGits** [comment]
Confirmed. Permission has been given to player and "&cTest" results in "&cTest".

**Comment by xIPad3Zockerx** [comment]
&1 Hello -> 216 Hello

**Comment by kangarko** [comment]
What exact permission have you tried? Do you use formatter or channels?

@xIPad3Zockerx  please update, this has been resolved.

**Comment by LogGits** [comment]
I use the formatter and have channels disabled and "&cTest" prints out "&cTest" not "Test" in red.

**Comment by xion87** [comment]
I using formatter, and i used chatcontrol.chat.format.color.*

**Comment by xion87** [comment]
You are fixing this? or ignored? colors are not working...

**Comment by kangarko** [comment]
This is being worked on :) I am trying to reduce the file size and it takes time to write my own implementation of some libraries that I have been using, please allow me additional 24h for a new release.

**Comment by kangarko** [comment]
Fixed just now, new release coming in 1h :)

@LogGits please use **chatcontrol.chat.format.color.*** not chatcontrol.chat.format.color in the next release.

**Comment by xion87** [comment]
There is also some isssues with factions colors, is related?

**Comment by kangarko** [comment]
Please try 7.5.2 and if it persists, let me know exactly how to reproduce it.
