### ISSUE TITLE
Error not sure whats causing.

### ISSUE THREAD

**Issue by DuckCraftPvP** [kangarko/ChatControl-Pro#354]
Hi, I am having this error. Not sure what is causing it.

https://hastebin.com/ozunecigug.sql

**Comment by kangarko** [comment]
Hey ,

do you remember where in configuration you have set 0.8 ? If it is a range, then it must be a whole number like 1, 2, 3 etc. not a decimal.

Please go through your settings.yml, formatting.yml, handlers.yml, channels.yml and try to find it and correct it :)
