### ISSUE TITLE
Styling /me messages

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#355]
I can't find anywhere in the config how to style the /me messages. I searched online and essentials chat handles that but of course I don't have essentials chat as I use chatcontrol pro.

Am I overlooking something or does chatcontrol not control that part of chat?

**Comment by LogGits** [comment]
/me is controlled by essentials not essentialschat. If you want a custom /me message please see [this](https://www.youtube.com/watch?v=9Uan2oJ9zK8)

**Comment by kangarko** [comment]
Hey,

I sincerely apology, ChatControl does not have support for /me natively.

**Comment by gerardvanschip** [comment]
Can it get that? When I was googling I found that various other chat plugins all have support for styling /me

Like ichat, bchat herochat etc

**Comment by kangarko** [comment]
Sure! I have added this to the work-map: https://github.com/kangarko/ChatControl-Pro/issues/343
