### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Neclok** [kangarko/ChatControl-Pro#356]
Change "!" to "/g" for global message... "!" is very old...

**Comment by Neclok** [comment]
cause server problem that there is no permission separation per server eg permissions plugin example permissionsex.

**Comment by Neclok** [comment]
All server canal speak with "!"

**Comment by EvilOlaf** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Getting-Help-the-Right-Way

**Comment by kangarko** [comment]
ChatControl has two global chats.

The first is per-server, that is with ! in front of a message.

The second is for bungee, that is with /chc g but can be easily changed to /g as per wikipedia.
