### ISSUE TITLE
Channel messages do not show

### ISSUE THREAD

**Issue by DuckCraftPvP** [kangarko/ChatControl-Pro#357]
settings.yml | https://hastebin.com/sasiruvazu.php
formatter.yml | https://hastebin.com/hepogifipo.php
channels.yml | https://hastebin.com/akuvoqavix.php

MC Version: paperspigot(1.8.8)
ChatControl version: 7.5.1 beta

http://prntscr.com/gkvx2i | screenshot in game
https://hastebin.com/rirebonoke.vbs | log from console for this time

**Comment by DuckCraftPvP** [comment]
also for the party format can u add an option for party: factionally and factiontruce

**Comment by MarkehMe** [comment]
@kangarko if there is any way I can help please let me know 😃 

I would love to have ChatControl Pro and LegacyFactions working flawlessly together. But I'm not quite sure how far you've gone already. Is there anything on my end I could add to improve it for you? Is the API ok?

I have realised I haven't documented these parts very well. 😞 

You can actually take over the faction chat modes all together using [EventFactionsChatModeChange](https://github.com/redstone/LegacyFactions/blob/master/src/main/java/net/redstoneore/legacyfactions/event/EventFactionsChatModeChange.java).

So if a player was to type `/f chat` then `EventFactionsChatModeChange` would be fired and you could fetch the chat mode from `EventFactionsChatModeChange#getChatMode()`.

From here the best thing to do would be:
```java
event.setCancelled(true);
event.getFPlayer().setChatMode(event.getChatMode()); // does not call event, just updates value in the entity

String channel = "factions_" + event.getChatMode().name(); // or whatever way you want to do this

// etc
```

**Comment by kangarko** [comment]
Hey, sorry for the delay, please allow additional 24h-48h to solve this.

**Comment by kangarko** [comment]
Alright, I have now updated the plugin and the issue should be fixed. @DuckCraftPvP please test it out on 7.5.4.

@MarkehMe thank you for being so helpful! Great developer <3

**Comment by kangarko** [comment]
Closing this in faith that this has been resolved. Please remind me if not.
