### ISSUE TITLE
[7.5.3] Own Factions Relation Color  is wrong

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#359]
Hi, now factions color work, but i see all members of my faction in chat with red tag instaed, it must be green.

**Comment by kangarko** [comment]
Please post me your settings.yml and formatting.yml with the variable.

What factions plugin are you using?

**Comment by xion87** [comment]
I am using Factions Mcore
Settings: https://hastebin.com/qixejevopo.php
Format: https://hastebin.com/hazufeqifu.php

My prefix for example was white, and when somesone do /f enemy me, my factions it will became red for myself, or purple or green when they do the relation command

**Comment by kangarko** [comment]
Sorry for the delay, I am currently setting a support team because of the load, please allow me additional 1-2 days to resolve your issue.

**Comment by kangarko** [comment]
Sorry I have to delay it again due to stay in the outlands. Thanks. I will get to it 3nd of October.

**Comment by kangarko** [comment]
@malon could you be able to reproduce this bug please?

**Comment by malonnnn** [comment]
@kangarko 

I'm sorry I don't know anything about factions.

**Comment by kangarko** [comment]
Closing because we are investigating this issue in https://github.com/kangarko/ChatControl-Pro/issues/406
