### ISSUE TITLE
[7.5.2] Replace World in swear is not following the lenght

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#363]
I just have this config set
Replace the swear word with a censor.
 If you only specify one letter, it will be automatically stretched to match word's length.
Replace_Word: "*"

When i say a bad world it will keep to censor with one "*"  instead following the world lenght.

**Comment by LogGits** [comment]
@xion87 Change it to "@prolong *" should fix this.

**Comment by xion87** [comment]
"@prolong *" or "@prolong*" ?

**Comment by LogGits** [comment]
"@prolong *" dont forget the character. After changing it type /chc reload

**Comment by xion87** [comment]
yah that is the soluction thanks!
