### ISSUE TITLE
Upgraded to 7.5.2 from 7.4 and autojoin no longer working

### ISSUE THREAD

**Issue by braceyourself07** [kangarko/ChatControl-Pro#365]
Hi there.  I could be missing something ridiculously simple, but after upgrading to the new 7.5.2 (from 7.4.x) despite adding the following perms, autojoin is no longer working when a player logs in to a particular server:

chatcontrol.autojoin.lobby.write
chatcontrol.channel.lobby.join.write
chatcontrol.channel.lobby
chatcontrol.channel.lobby.autojoin (old autojoin perm from 7.4.x and prior)

This is what I see when logging into a server that has been updated with the new 7.5.x version:
https://shareit.d3v.no/storage/uploads/4/javaw_2017-09-16_23-23-32.png

Anything I can double check?

**Comment by braceyourself07** [comment]
And just to mention, if I type /ch list, I do see appropriately available channels

https://shareit.d3v.no/storage/uploads/4/javaw_2017-09-16_23-28-38.png

And if I type '/ch join lobby' it will allow me to join it.  But I can image an influx of confused players who are unable to chat after logging in.

**Comment by braceyourself07** [comment]
I noticed in the update log entry that the join perm has changed.  I added the following perm:

chatcontrol.lobby.join.write

But still cannot get players to autojoin. 

Also to mention, when a player manually joins by typing '/ch join lobby' they will remain in the channel when logging back in after leaving the server.

**Comment by braceyourself07** [comment]
In the update log entry, it says to use:

chatcontrol.autojoin.<channel>.<mode>

In the wiki on page: https://github.com/kangarko/ChatControl-Pro/wiki/Channels# 
It says to use:
chatcontrol.channel.autojoin.{channel}.{mode}

I'm trying nearly every combination of perm node I can think of with no success

**Comment by kangarko** [comment]
Hello,

I have updated the wiki, thank you for that information.

There are two permissions you need to give your players in order that they can join (I apology for the confusion in updating). You can more here:
https://github.com/kangarko/ChatControl-Pro/wiki/Channels#auto-join

Please let me know if the article did help.

**Comment by braceyourself07** [comment]
Hey kangarko thanks for the update and clarification on the permission nodes.  I was indeed missing some. Troubleshooting at 1am didn't help either!  I've made the updates to the perms and awaiting a convenient time to restart and will report back if all is successful.

As always you provide great and timely support and I thank you for that!  Also, our players really appreciate the /ignore and /togglepm commands added in 7.5.x, again thank you

**Comment by kangarko** [comment]
Thank you for the kind words :) Look forward to hear back if it works!

**Comment by braceyourself07** [comment]
Thanks so much, it works.  I think I just had my perms mixed up, rookie mistake!

**Comment by kangarko** [comment]
No worries, everyone makes mistakes, including me (I will fix mine tonight :1st_place_medal: )

Feel free to open a new issue if there will be anything more.
