### ISSUE TITLE
Error AsyncPlayerChatEvent 7.5.3

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#367]
After forcing this update >:( the chat contains an error in default chat.txt

18.09 14:24:08 [Server] INFO MATCH: (.)(?=([a-z])\1{3}) 18.09 14:24:08 [Server] INFO CATCH: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 18.09 14:24:08 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v7.5.3 18.09 14:24:08 [Server] INFO java.lang.StringIndexOutOfBoundsException: String index out of range: 2 18.09 14:24:08 [Server] INFO at java.lang.String.substring(String.java:1963) ~[?:1.8.0_121] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Com3.const(SourceFile:724) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Com3.const(SourceFile:718) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Com3.const(SourceFile:422) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Com3.const(SourceFile:286) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Lpt2.const(SourceFile:182) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Lpt2.const(SourceFile:48) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.Lpt2.const(SourceFile:30) ~[?:?] 18.09 14:24:08 [Server] INFO at me.kangarko.chatcontrol.null.nUL.execute(SourceFile:26) ~[?:?]

**Comment by kangarko** [comment]
Hey,

I apology for the situation. It was never the intention to force the update, but I found the message pointing to downgrade pointless especially when the newer versions are stable...pretty much.

You can read more at https://github.com/kangarko/ChatControl-Pro/issues/371

I will fix this issue tonight.
