### ISSUE TITLE
Chat formatter need plugin?

### ISSUE THREAD

**Issue by Allnoob007** [kangarko/ChatControl-Pro#368]
When i start the Server all PL's start and work, after start i get this error.

 [0;30;1mChatControl[0;37;22m [0;37;22m*-----------------------------------------------*[m
>[2K
 [0;30;1mChatControl[0;37;22m  [0;31;1mChat formatter requires a plugin for player's[m
>[2K
 [0;30;1mChatControl[0;37;22m  [0;31;1mprefix and suffix, that is compatible with Vault.[m
>[2K
 [0;30;1mChatControl[0;37;22m  [0;31;1mRun /vault-info and check what is missing.[m
>[2K
 [0;30;1mChatControl[0;37;22m  [0;31;1mPlugin is now disabled.[m
>[2K
 [0;30;1mChatControl[0;37;22m [0;37;22m*-----------------------------------------------*[m
>[2K
 [ChatControl] Disabling ChatControl v7.5.3

**Comment by EvilOlaf** [comment]
CHC grabs players pre- and suffixes from your permissions plugin. It seems like your current permission management solution is not compatible to Vault.
What permission plugin do you use? Vault version?
Did you run /vault-info? What output do you get?

**Comment by Allnoob007** [comment]
Argh, i forgot the permission pl.... setup a new server and no perm pl
