### ISSUE TITLE
Global chat

### ISSUE THREAD

**Issue by Allnoob007** [kangarko/ChatControl-Pro#369]
Is it now normal, that i geht the "!" then i will write in Global?

Local:
Allnoob: test

Global:
[Global] Allnoob: !test

Pic:
https://i.imgur.com/PeOOjb0.png

**Comment by kangarko** [comment]
Do you have ranged chat enabled ?

Do you have channels or interactive chat enabled?

**Comment by Allnoob007** [comment]
formatting.yml : 

Enabled: true

Range: 
  Enabled: true

  Distance: 500000.0

  Linked_Worlds: 
      normal:
        - world
        - creative
      farmwelten:
        - farmwelt
        - farmworld
        - world_nether
        - farmwelt1
        - world_the_end

**Comment by kangarko** [comment]
Confirmed. Will be fixed tonight.
