### ISSUE TITLE
Essentials malfunction getting essentials user.

### ISSUE THREAD

**Issue by KevinEssence** [kangarko/ChatControl-Pro#37]
States in the console that there was an error or malfunction getting essentials user , not sure if this is breaking anything.

**Comment by kangarko** [comment]
It is not breaking the plugin as a whole, it only disables certain features like {nick} variable, which is from Essentials. What's your server version? Are you on Essentials or EssentialsX? Does it happen after you've reloaded?

**Comment by KevinEssence** [comment]
Paperspigot 1.8.8, essentialsx, after a server restart.

**Comment by kangarko** [comment]
Tested both 1.8.8 and 1.9.2, and unfortunately I cannot replicate. However, I've made some changed, so please test the latest release which will be pushed tonight.

**Comment by kangarko** [comment]
Most likely fixed within the latest release. Let me know if the message appears again.
