### ISSUE TITLE
[7.5.3] Can't use special character in config

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#370]
Hi, i just trying to use "**è**" in the motd section of chatcontrol, but when the config load, that character will be autoconverted into "**?**"
This issuse never happened in old configs (7.4.x)

**Comment by kangarko** [comment]
Hey,

please open the file with the correct program and save it as unicode encoding as per this short article:

https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
