### ISSUE TITLE
[7.5.3] Strange archiviement messages

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#373]
![immagine](https://user-images.githubusercontent.com/3611852/30584804-31981fec-9d2b-11e7-8e79-dd9fc3c9c079.png)
I just noticed these messages  when somesone do rchievement

**Comment by kangarko** [comment]
I am pretty confident in that this is not coming from ChatControl.

Please test out without ChatControl so you can confirm with 100% certainty that the plugin is the cause of this message.

**Comment by xion87** [comment]
that one is caused by different minecraft version (1.8 to 1.12) is true.
