### ISSUE TITLE
[7.5.4] Click event stopped to work

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#374]
After upgrade to 7.5.4 i noticed click event stopped to work, for example i have this 
https://hastebin.com/hodusekolo.php
When i click the nick or factions nothing happen

**Comment by kangarko** [comment]
You have extra indentation of the click event:

´´´´
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - '&eRelazione: {rel_factions_relation}'
          - '&ePot.Fazione: &f{factions_factionpower}&e/&f{factions_factionpowermax}'
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/msg {player} "
´´´´

just move it two spaces to the left :)
