### ISSUE TITLE
New formatting, where has the Click events for Suffix and Message gone?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#376]
So I've been spending some time trying to figure out these new configs that have completely changes, and there is a worrying change in the formatting for the main chat.
So in formatting.yml
Im editing my main chat. Now I want to have clicking a username do one thing, and clicking the message of theirs do another thing. Both with their own separate hover overs.
Now this worked fine in the old configs, You had a, Prefix, Player, Suffix, Message "parts". This makes sence, build each section you want! Perfect. 
Now this latest version of formatting, there is a Prefix, Player and some really obscure "The_Rest". The hell is this? It was fine as it was, where has the customization for Suffix and Message gone?

**Comment by FrozenBeard** [comment]
No. I'm asking where **Suffix** and **Message** customisation went, and why its bundled to **The_Rest** this is utterly awful.

**Comment by kangarko** [comment]
The_Rest is just an example if you don't need to add extra elements.

You can just remove it completely and create new configuration sections just as you had in your previous config.

**Comment by malonnnn** [comment]
@FrozenBeard 

As I look through the wiki on formatting (https://github.com/kangarko/ChatControl-Pro/wiki/Formats) I don't see anything about The_Rest or Suffix and Message.

You can name each part whaever you want. For example, in mine, I named one of my parts "hero". You can name each part whatever you want.

**Comment by malonnnn** [comment]
@kangarko 

wtf I was just responding to the dude and you closed this xD I saw it change in front of my eyes as I was typing lol

**Comment by kangarko** [comment]
I see, my bad. I am reopening this until further notice.

**Comment by FrozenBeard** [comment]
@malonnnn I just assumed the Wiki wasn't updated yet and that that Suffix and message on-hover and on-click customisation has disappeared, I just gave up with the update when i saw these were removed from the config, I will have to find some time in the week to get back to it and finish it and re-test it.

Ahh I didnt know It was named whatever!! That is where Im getting confused them! I was thinking it had to have that name structure, like the plugin would know that suffix goes last and prefix goes first! oh my god! This needs to be explained in the config! 

Alright then I should be fine to format exactly the same then!

**Comment by malonnnn** [comment]
@FrozenBeard I absolutely agree with you and it was very confusing that they could be named whatever you want. It took me a while too.

**Comment by kangarko** [comment]
I understand. When making the plugin I tried to keep it as customizable as possible. Generally speaking, channel names in channels.yml, format parts in formatting.yml and a few other things in settings.yml are very loose, meaning you don't even need to specify all keys if you do not need them. This is to save enormous space and effectivity, but it may be confusing at the start. I am here if you have any more questions.
