### ISSUE TITLE
ignore and togglepm data are not sync correct

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#379]
I use multiple server on mysql chatcontrol, the issue is if you do /ignore somesone on server1 and go in server due and do /ignore ? (you will not see the new ignored),

**Comment by xion87** [comment]
I also notice togglepm at next server restart is not enabled....

**Comment by kangarko** [comment]
Hey,

I am terribly sorry for the delay. In the next version, please set MySQL.Aggressive to true. It should produce more traffic to MySQL but will fix the issue.
