### ISSUE TITLE
Chat Channels

### ISSUE THREAD

**Issue by KevinEssence** [kangarko/ChatControl-Pro#38]
There is a chat channel issue that requires a permission to even us it..my suggestion is to make it so it doesn't state we need permission..towny uses channels too and we can't use it because it requires permissions from chatcontrol. Or even support if you can.

**Comment by kangarko** [comment]
The permission is there to not let players write into any channel, for example into the admins' channel. Simply add them the proper permissions and it should work with Towny, too.

**Comment by KevinEssence** [comment]
Thank you.
