### ISSUE TITLE
Channel problem

### ISSUE THREAD

**Issue by HORTEXX** [kangarko/ChatControl-Pro#380]
I have a problem and I do not know how to deal with it. I mean the channel that I turned off, but I can not write in chat because the channel is off. And I do not want to use the channel just want to have a normal chat. And in this problem I do not know how.
Please help me.

**Comment by kangarko** [comment]
Hello!

1. What do you mean by channel turned off ? Muted channel?

2. To disable channels, set Enabled to false in channels.yml and to have a normal chat set Enabled to true in formatting.yml
