### ISSUE TITLE
[7.5.7] ChatControl disabled

### ISSUE THREAD

**Issue by BorussiaMG** [kangarko/ChatControl-Pro#381]
Hi I have installed ChatControl Pro [7.5.7]. After a complete restart there are some errors and ChatControl is disabled.

Here is the error message.

https://pastebin.com/Vh5UBXfr

Thanks for your support. 

SpigotAccount: BorussiaMG1994

**Comment by kangarko** [comment]
Will fix!

What's your Essentials version btw? Essentials or EssentialsX? What is /ver Essentials ?

**Comment by BorussiaMG** [comment]
[Essentials] Loading Essentials vTeamCity

**Comment by kangarko** [comment]
Can you open Essentials.jar file and send me the version of the "version" key in plugin.yml file inside that jar please?

**Comment by BorussiaMG** [comment]
Hi I have opened the plugin.yml and the version string is 
`# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: Essentials
main: com.earth2me.essentials.Essentials
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: TeamCity
website: http://tiny.cc/EssentialsCommands
description: Provides an essential, core set of commands for Bukkit.
authors: [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally]`

Hope this helps ;)

**Comment by kangarko** [comment]
I see, thank you!
