### ISSUE TITLE
Error on load chatcontrol with essentials

### ISSUE THREAD

**Issue by Espantonius** [kangarko/ChatControl-Pro#382]
When loading chatcontrolpro it gives an error. The error says:
![screenshot_7](https://user-images.githubusercontent.com/14083246/30762900-2a479ac2-9fe4-11e7-8b0d-92ae7e4ac4f5.png)

This error happens to me since version 7.5.5. Any solution?

Info:
7.5.4 Works perfectly. 7.5.5 onwards does not work.

**Comment by malonnnn** [comment]
Did you redownload 7.5.5, possibly it's a corrupt download?

**Comment by kangarko** [comment]
I see, what is your Essentials version? This will be fixed anyway in the next release. Apology for the inconvenience.
