### ISSUE TITLE
Request: Receiver_Permission for format-/channel-parts.

### ISSUE THREAD

**Issue by SilberRegen** [kangarko/ChatControl-Pro#383]
I don't know whether you already planned on adding something like this, but I would love to have the option to add parts with an receiver-permission, where only players with this permission can see the part.

This could be used for an administrator/staff infobox for example, containing information about the chatting player not to be viewable by everybody else. A quick /mute or /ban-button only visible to staff or maybe a Teleport-to-button for players with permission would be possible, too. Without cluttering the format with unusable stuff for players without the permission.

If you did plan on this, you're awesome and I hope the feature comes soon.
If not, you're still awesome and I hope you'll consider it :)

**Comment by malonnnn** [comment]
This sounds like a pretty cool feature to me, especially the idea of putting "buttons" near player names in chat.

**Comment by kangarko** [comment]
Yes, this is planned, hence the Permission was changed to Sender_Permission so there is space for Receiver_Permission to the very future :)
