### ISSUE TITLE
7.5.6 /ch set doesn't clear previous channels

### ISSUE THREAD

**Issue by braceyourself07** [kangarko/ChatControl-Pro#384]
Not sure if this is intended usage, but using /ch set does not clear the player's previous channels but just simply makes the player join a channel (even if the channel is one they are already in).

For example, using this command twice: /ch set player global
Results in the player being in the channel twice.  They don't double speak, but they would have to type /ch leave global twice in order to leave it.

**Comment by malonnnn** [comment]
Kangarko has been doing some channel work. Please upgrade to 7.5.8 and report back if the issue continues.

**Comment by braceyourself07** [comment]
Yep ^ was just about to post that it persists in 7.5.8 too.  Thanks!

**Comment by kangarko** [comment]
Thanks. I will get to it 3nd of October due to stay in the outlands.

**Comment by kangarko** [comment]
Will be included in a today's hotfix.
