### ISSUE TITLE
Nothing is Working

### ISSUE THREAD

**Issue by RJM123** [kangarko/ChatControl-Pro#386]
Hi, I anti-spam, anti-swear, anti-advertise, anti-caps, and all the features simply don't work. I dragged the plugin into the plugins folder, read the rules.txt, and added some nicknames to the blacklist. But none of the features work. 
Settings.yml: https://hastebin.com/iqigomesew.php
Handlers.yml: https://hastebin.com/xixemoseze.bash
I can Spam, Swear, Advertise, All Caps, and chat right after login. And nothing happens. I thought that it could be because I had other chat plugins, so I removed Anti_Swear and Anti-Spam, but still it wouldn't work.

**Comment by malonnnn** [comment]
@RJM123 Sorry to hear about your troubles.

I am on 7.5.8 and I can confirm that all options are working for me - Anti-Caps, Anti-Swear, etc. So for us to figure out what's going on, I'm going to ask you for a lot of information. Please provide as much as you can.

1. Please provide your permissions for your default group of people that should have chat rules (as well as any parent groups they inherit from)
2. Please provide a full list of plugins on your server
3. Please provide the full server version (found by typing "version" in console)
4. Please provide a complete startup log of your server

Hopefully with those, combined with your settings and handlers from your 1st post, we can see what's going on.

**Comment by LogGits** [comment]
Everything is working for me.

**Comment by MADS0LADEN** [comment]
Are you swearing from your own (OP) account? because then it is possible, try with another account that doesn't have OP.

**Comment by RJM123** [comment]
Thank you! That was it, now it works!

**Comment by RJM123** [comment]
The issue was resolved
