### ISSUE TITLE
Detection bug in "handle as chat" in settings [v: 7.5.8]

### ISSUE THREAD

**Issue by Axel63MC** [kangarko/ChatControl-Pro#387]
When you write /msg Notch CAPSLOCK IS BAD it detects it for CAPS and if you write it again for similiar message
but if you write /Msg Notch CAPSLOCK IS BAD it detects nothing so you can bypass that protection with a capital letter at the command.

**Comment by kangarko** [comment]
Thanks. I will get to it 3nd of October due to stay in the outlands.

**Comment by kangarko** [comment]
Hey, sorry for the late reply, this has been resolved in the last version.
