### ISSUE TITLE
7.5.9 Fails to load if DiscordSRV is not present

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl-Pro#388]
Log:
https://pastebin.com/yme0nuRt

Temp solution:
Install DiscordSRV

**Comment by mrcoffee1026** [comment]
should have a way to disable this in the config file imo... while chatcontrol having discord support is nice, having a discord necessity is quite a different thing.  I do have a discord server but don't really want to have to install another plugin just for communication with that between the minecraft server to happen.  I actually want them treated as separate entities (banning a user from the server in game may not necessarily cut that user off from the discord, nor do I want it to).

**Comment by LogGits** [comment]
I agree with @mrcoffee1026. This should be disabled by default. A config option to enable the feature would be appropriate. I'm certain this issue is a bug.

**Comment by kangarko** [comment]
I apology, was caused by this line:

`registerEventIf(new DiscordListener(), CompatProvider.hasDiscord());
`
Did not know that it would initialize the class even if the other parameter is false.

Fixed immediatelly.
