### ISSUE TITLE
Add some new operators into rules

### ISSUE THREAD

**Issue by Hdadaw** [kangarko/ChatControl-Pro#389]
"then command_as_op" to execute certain commands by the player as op
"then random_warn" to randomly display presetted messages to the player

**Comment by kangarko** [comment]
Hey!

1. For "then command_as_op" simply use "then console"
2. For "then random_warn" simply use "then warn firstmessage|second message|third message" for randomly selected messages

For more info, see rules/rules.txt header.

**Comment by Hdadaw** [comment]
`# then warn <message> (A message that is displayed to the player. TIP: Use | to split message into multiple lines (when \n is not working for you))`

**Comment by Hdadaw** [comment]
@kangarko 
`# then warn <message> (A message that is displayed to the player. TIP: Use | to split message into multiple lines (when \n is not working for you))`

**Comment by kangarko** [comment]
Yes?

**Comment by Hdadaw** [comment]
@kangarko 
Yes, this is not a random
![javaw_2017-09-26_18-53-48](https://user-images.githubusercontent.com/32250813/30856797-161dae14-a2ec-11e7-8c73-fced0ce42e40.png)
