### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by renzotom** [kangarko/ChatControl-Pro#390]
Hello, I have some suggestions:

**Signs**
```
# Player will be unable to place two signs with the same text.
  Block_Signs_With_Same_Text: true
```

- [ ] Add here option to enable specific words, like "Event", etc... (so whitelisted same text on signs)

**Commands in configuration**
Hey, there is:
`  Commands_To_Apply:
    - /msg`
`    Handle_As_Chat:
    - me`

- [ ] I am suggesting make all commands in configuration with / or without /, beacuse now, somewhere / is and somewhere isn't...

**MOTD**

- [ ] Add way to add special MOTD for first logged players

**Formatting file**

- [ ] Small typo, another free blank here:
`Prefix example: - "&7Groups&8: &b{pl_group}"      (here is free blank)`

**Message, what isn't allowed by rules**
Message like that will be printed red to the sending player only and we can add hover effect on it, where mistake was, etc....
Is that possible?

- [ ] Dissalowed message printing

**Messages**

- [ ] Way to add special permission to every message

- [ ] Maybe add something like is in Formatting file, instead of need to use JSON in messages.file. 
Ex. that is too much better:
`    Vip: 
      Message: "&6[VIP] "
      Sender_Permission: "chatcontrol.groups.vip"
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&6This player is VIP"
          - "&6Check out &e/web &6to obtain VIP"`
Than:
`    global: 
      - '{"text":"&cInformace o zatezi serveru","hoverEvent":{"action":"show_text","value":["",{"text":"&6Cas: &l{server_time_EEE, d MMM yyyy HH:mm:ss Z}"],"\n&aPocet hracu: &l{server_online}&a z &l10&a, na spawnu &l{server_online_Void}&a, ve svete &l{server_online_world}&a, v pekle &l{server_online_world_nether} &aa v Endu &l{server_online_world_the_end}"},"\n&bServer jede: &l{server_uptime}","\n&cPouzita ram &l{server_ram_used} &cz &l{server_ram_max}&c, &czbyva &l{server_ram_free}","\n&4TPS &l{server_tps}"]}}'`

**Comment by kangarko** [comment]
Hello!

* Signs: Thank you, I have noted it.
* Commands in configuration: Changed.
* MOTD: Marked, but there are special plugins just for that.
* Formatting file: Fixed.
* Message, what isn't allowed by rules: Currently not possible, already planned :)
* Messages: Thanks, marked.

Dakujem za tipy!
