### ISSUE TITLE
Feature Request:  toggle join/quit/switch messages

### ISSUE THREAD

**Issue by braceyourself07** [kangarko/ChatControl-Pro#393]
Our server is in that awkward stage between small and medium where we have about 50-60 concurrent players at peak.  Sometimes the join/quit/switch messages from ChatControlBridge get a little spammy... but if I remove it, players complain they can't tell if their friend logs in.  Could there be a method to allow players to toggle this on/off?

**Comment by kangarko** [comment]
Hey,

I have marked that down, great suggestion!
