### ISSUE TITLE
Splitting permission

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#395]
requesting a split of a permission;

`chatcontrol.bypass.rules` into:

`chatcontrol.bypass.rules`
`chatcontrol.bypass.packets`
`chatcontrol.bypass.sign`
`chatcontrol.bypass.commands`
`chatcontrol.bypass.chat`
`chatcontrol.bypass.books`
`chatcontrol.bypass.items`

Requesting this because i only want some players (such as moderators) on my server to bypass the rules.txt

**Comment by kangarko** [comment]
Good idea, pulled.
