### ISSUE TITLE
Chat Formatting [Priority Glitch]

### ISSUE THREAD

**Issue by GameHoundInteractive** [kangarko/ChatControl-Pro#398]
Hi, So i have chatcontrolpro and legacy factions and chatcontrolpro formatter is overriding the chat for legacy factions, It only started to happen after your recent recode but i was taking a break from mc so i did not notice till now.

http://prntscr.com/gskyaa - Examples:
My configs : 
Settings.yml: https://hastebin.com/ulofecoyeq.php
Formatting.yml: https://hastebin.com/wufifadiye.php

Version: 7.5.10
http://prntscr.com/gskzew

~Thx DuckCraftPvP

**Comment by kangarko** [comment]
Try setting Listener_Priority.Formatter to HIGHEST or MONITOR.

**Comment by DuckCraftPvP** [comment]
i have, It does not work.

**Comment by kangarko** [comment]
From your settings.yml, I see you had it on LOWEST. Please see away from this if you 'have' tested it with the other priorities.

Try setting Compatibility.Cancel_Event to true in channels.yml

**Comment by kangarko** [comment]
Closing in faith that this has been resolved.
