### ISSUE TITLE
Player without code permission can spam free in chat

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#399]
I noticed player without color permission in chat or something like this
they can spam &L without being blocked for repeat

**Comment by kangarko** [comment]
Cannot reproduce
![a](https://i.imgur.com/XioCDxD.png)

**Comment by xion87** [comment]
these player are using a colored suffix (from luckperms) i am testing it and as you can see
![immagine](https://user-images.githubusercontent.com/3611852/31242450-5fd8c3b4-aa07-11e7-8086-1b5c5ac6b0d6.png)

**Comment by kangarko** [comment]
Are you sure that other, similar messages, are blocked? You can increase the strictness of the filter by setting Anti_Spam.Commands.Similar_Percentage_Block to a higher number like 90, or try to decrease it to set it to 60.

**Comment by xion87** [comment]
other messages are blocked except for these codes

Il 06 ott 2017 9:15 PM, "kangarko" <notifications@github.com> ha scritto:

**Comment by kangarko** [comment]
Try to decrease the strictness as I mentioned above, to 60.

Is the message green because the prefix has the green color? Do you have any other plugin for chat color or similar?

**Comment by xion87** [comment]
same result, if i write lo or something else, it block, instead using &L (without any letter) it willpass if you are using any suffix

**Comment by kangarko** [comment]
Can you try removing LuckPerms for one round to test if the problem will be solved? I have another ticket regarding to that plugin, so I am interested in knowing whether it causes incompatibility.

**Comment by xion87** [comment]
no luckperms = no prefix/suffix = so the issue don't exist

**Comment by kangarko** [comment]
May you please upload your entire ChatControl folder to expirebox.com? Make sure to remove MySQL information.

**Comment by xion87** [comment]
here there is the zipped folder
https://expirebox.com/download/b9f8d2800e9efbacf174446d7e70ed28.html

**Comment by kangarko** [comment]
Thanks, fixed.
