### ISSUE TITLE
Inability to post links in chat...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#400]
Periods replaced with blank space " " instead... this is even after turning this feature off?  OP can still post links but no one else.

**Comment by malonnnn** [comment]
try giving the permisson

`chatcontrol.bypass.replace`

to see if that helps

**Comment by mrcoffee1026** [comment]
Except that would disable ALL replacements, and all I want to do is enable links, not disable all replacements.

**Comment by kangarko** [comment]
This change is not coming from ChatControl, see

https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com

**Comment by mrcoffee1026** [comment]
oh brilliant!  Thanks :D
