### ISSUE TITLE
[7.5.10] 'An unhandled error occured' when using Admin chat (/chc ach )

### ISSUE THREAD

**Issue by braceyourself07** [kangarko/ChatControl-Pro#401]
Several hours after a server restart, when using the admin chat channel (/chc ach) there is an "unhandled error occurred during executing the command" error.  The message does go through, but my staff is asking me about the error and I have no idea why it occurs.  Restarting the server does fix it until it happens again.

Here is the console error relating to the command: https://hastebin.com/dacivagube.md

I assume since it doesn't happen until several hours into the day, and that a server restart temporarily fixes the problem that it has to do with memory allocation.  But not sure if that is helpful to you.

Thanks so much,

Mike

**Comment by kangarko** [comment]
Please PM me at Spigot and try using 7.5.11.

If it happens again, please post me the recent console log from that time.

**Comment by braceyourself07** [comment]
Actually I think that solved it (7.5.12) as we've been running it for more than 24 hours now and it looks like it works just fine!  Thanks so much! 10/10 developer
