### ISSUE TITLE
How can I enable case sensitivity for "match" or "ingnore string"

### ISSUE THREAD

**Issue by Hdadaw** [kangarko/ChatControl-Pro#403]
I need to replace "xD" or "XD", not "xd", to another character.
I tried to do this through "ignore string" but the rule completely stops catching.
```
match \bxD\b
then replace 䨄
```
Please, help.

**Comment by malonnnn** [comment]
try

`match xD|XD`

**Comment by Hdadaw** [comment]
@malonnnn it's continues catching "xd"

**Comment by LogGits** [comment]
try new line with:
ignore string xd

so it would look like this:
```
match xD
ignore string xd
then replace 䨄
```

**Comment by Hdadaw** [comment]
@LogGits catching for any xd, xD, XD does not work with ignore string, because ignore string also case insensitivity

**Comment by kangarko** [comment]
To protect from bypasses (FuCK instead of fuck), ChatControl is written to be case-insensitive. There is little to do at this point because it is hardcoded in the code, but I may add a toggle option in the future. Thank you.
