### ISSUE TITLE
Toggle swearing visibility (WITHOUT REMOVING THE MESSAGES)

### ISSUE THREAD

**Issue by TheIronMinerLv** [kangarko/ChatControl-Pro#405]
Hi!

I would like to create a command that would "toggle" full visibility of blocked swearings. Like if you swear, for you the message shows as normal (nothing changed, not even a "warning"), but for other players - that hasn't used the command, for them the swear words will be "censored", but for the ones who will have used it - they will see the message without censoring.

How could I do that? Thanks.

**Comment by kangarko** [comment]
Hello,

currently, ChatControl offers a feature named Chat Ignorers that allow each users to toggle whether or not they want to see blocked rules - in your case - swear words. You can read about this in

https://github.com/kangarko/ChatControl-Pro/wiki/Chat-Ignorers

I am not sure if you were the one asking this in the free issues channel, if yes, then Chat Ignorers are the only and the best way to achieve this.
