### ISSUE TITLE
Relation + Chat issues with Legacy Factions

### ISSUE THREAD

**Issue by ipr0james** [kangarko/ChatControl-Pro#406]
I'm not entirely sure if this comes down to ChatControl or not however when looking in LegacyFactions wiki it says it should be the plugins providing it's issue. When looking at the relation placeholders for LegacyFactions they seem to change. For example I can be enemy with a faction and see them as a red tag in chat. Yet them still see me as green, then if someone logs in who is an ally to them then they'll display as green to me as well as the other player. 

I can provide screenshots or examples of this if necessary. 

Also,
Before when using FactionsUUID I was able to use ChatControl to handle public chat and then faction/alliance chat still worked with the format provided from FactionsUUID, However since switching to Legacy and the latest version of ChatControl this is now only using the main format from ChatControl rather than the format setup in Factions. This could more likely be an issue with LegacyFactions however I am currently unsure.

Thanks.

**Comment by kangarko** [comment]
Seems similar to https://github.com/kangarko/ChatControl-Pro/issues/359, I am on it.

**Comment by ipr0james** [comment]
Thanks dude, tryna finish an update and wanna get this sorted before release I hope. 

If you need to see it first hand in game I can show and all configs of course.

**Comment by kangarko** [comment]
It's good thanks; I've put lots to my hands so had to delay support (usually it's faster).

**Comment by ipr0james** [comment]
Yeah no worries, just putting the offer out there if you needed to easily recreate the issues.

**Comment by kangarko** [comment]
What placeholder are you using, in ChatControl, to display the relation with LegacyFactions?

**Comment by ipr0james** [comment]
I had been using rel_factions_player_chattag when testing.

**Comment by kangarko** [comment]
I am testing now but cannot get that placeholder replaced. What extension of PlaceholderAPI have you downloaded?

**Comment by xion87** [comment]
%factions_chat_tag% is from factions UUID

**Comment by ipr0james** [comment]
https://gyazo.com/80b6a51753455ec5d4f2db9ec25b99fc

I use Legacy Factions, For some reason although named the same will not download with ecloud download, I just restarted server to get auto install. I can send the expansion.jar if required.

**Comment by kangarko** [comment]
Yes please send me the expansion pack.

**Comment by ipr0james** [comment]
Could you accept me on Discord. names ipr0james should have a pending request as it'll be easier to send there rather than uploading somewhere.

**Comment by xion87** [comment]
or just give him the direct download http://api.extendedclip.com/media/Expansion-FactionsUUID_2d2mdwu.jar

**Comment by kangarko** [comment]
Accepted

**Comment by ipr0james** [comment]
After further investigation (been a while without internet..)

Can find that:
- Issue with factions chat/alliance chat being formatted is an issue within LegacyFactions..
- Issue with Relational placeholders is an issue in ChatControl (pm'd kangarko about it, is looking into)

**Comment by ipr0james** [comment]
After further testing can confirm the issues are fully in relation to LegacyFactions.
