### ISSUE TITLE
Can you add auto-mute system for swear?

### ISSUE THREAD

**Issue by Pluginsel** [kangarko/ChatControl-Pro#409]
Can you add auto-mute system to ChatControl Pro on the next updates?

TYPE:
On player swear: mute automatically for 10-20 minutes.

Config.yml option:

Auto-Mute:
   Enabled: true

      Swaer-mute: true
      command: "/tempmute (player) 10m (reason)" 

      capslock-mute: false
      command: "/tempmute (player) 10m (reason)" 
     
      spam-mute: false
      command: "/tempmute (player) 10m (reason)" 
   
And other options...

For the mute commands like a LiteBans and AdvancedBan plugins.

**Comment by kangarko** [comment]
Hey!

Thank you! There's already a feature named Warn&Point system, you can check that out in settings.yml in Points configuration section. I recommend you see the default config with headers in Configuration Wiki page.

**Comment by Pluginsel** [comment]
@kangarko can you add thia feature with a command?
Because I don't understand the rules.txt

**Comment by kangarko** [comment]
You don't need to modify rules.txt, you can just set "Points.Enabled" to "true" in settings.yml and it will enable itself automatically, including the auto-mute commands.
