### ISSUE TITLE
Bug in "handle as chat"

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#410]
I run into a bug in this section:
Anti_Spam:
  Commands:
    Handle_As_Chat:
    - /me
    - /msg
    - /m
    - /pm
    - /reply
    - /r
    - /tell
    - /t
    - /whisper
    - /w
I hoped this will handle commands like "/t Hey here's my message" as chat. But this also blocks multiple commands starting with those characters as well. Example:
/tpa playername
/tpa playername --> Dont spam please!
Tried to bypass it with a space behind /t command but this does not work.
Another example: /w blocks all /warps if done twice.

**Comment by kangarko** [comment]
Good notice! I apology for that and will fix it tonight.
