### ISSUE TITLE
Issue with packets

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#411]
We (me and FrankHeijden) have tried literally everything to hide /aac with the following in packets.txt
https://hastebin.com/ubaramozal.scala

Both didnt work Tested on all latest versions. no output either
Protocollib version: 4.3.0
Chc Version: 7.5.12
AAC Version: 3.3.3

Server version 1.12.1
Client version 1.12.2

**Comment by kangarko** [comment]
Hey,

can you post me a picture of that message in the game chat please?

Also ensure you have **Regex_Strip_Colors** to **true** in settings.yml

**Comment by AmazedMender16** [comment]
This is what im getting..
http://prntscr.com/gytwxv

Also Regex_Strip_Colors is set to true

https://pastebin.com/mEVJ7VPc = Packets.txt

**Comment by kangarko** [comment]
Hello,

I have tested those two rules and they work for both messages:

```
match \[AAC\] \> AAC
then deny

match \[AAC\] \> ID:
then deny
```

However, I have made some changes to ChatControl. Please wait till the next release (tonight). I am closing this, but surely let me know if there's anything.

**Comment by AmazedMender16** [comment]
Thanks,

That got it to work!
