### ISSUE TITLE
Sound notify doesn't work in main chat

### ISSUE THREAD

**Issue by vipersonic** [kangarko/ChatControl-Pro#413]
Here's my config:

Sound_Notify:
  Enabled: true
  Cooldown: 3 seconds
  Require_Afk: false
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Color: '&a'
  Require_Prefix: '@'
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r

Sound doesn't work in the main chat, while names don't get highlighted at all, even with '@', or 'none'.

**Comment by ipr0james** [comment]
It could be to do with your MC Version, the sounds Enum was changed between 1.8 and 1.9. Which version are you using?

**Comment by vipersonic** [comment]
1.12.2. I receive sounds in private messages.

**Comment by ipr0james** [comment]
Ah not sure then. Won't be sound as thats the correct for 1.12.2. Sorry man :D

**Comment by kangarko** [comment]
Do you use chat channels or interactive formatter, or other plugin for chat formatting like DeluxeChat, TownyChat or similar?

From your config, you have to wait 3 seconds. Try to setting the Cooldown to 0 and Require_Prefix to "" instead of "@" to test it it will work.

**Comment by vipersonic** [comment]
Only essentialsChat. 
But I’ve had it since forever and it has never interfered before.
And recently, Discord SRV. But ChatControl is compatible with that.
And yes, setting the delay to 0 and prefix to “” doesn’t do anything differently.

**Comment by kangarko** [comment]
Do you use **chat channels** or **interactive formatter** in ChatControl?

**Comment by vipersonic** [comment]
Not that I know of.

**Comment by kangarko** [comment]
Ah, I see. I am sorry, but Sound Notify is tied to either chat formatter (formatter.yml) or channels (channels.yml). It won't work in chat unless one is enabled.
