### ISSUE TITLE
Private message commands not fully overwriting

### ISSUE THREAD

**Issue by Managering** [kangarko/ChatControl-Pro#415]
Hi,

Goldenorange on spigot, user of ChatcontrolPro.

Long story short:
I have a chat system, custom made, has it's own /r, /reply, /msg, /message commands. They overwrite essentials' commands perfectly. 

I wanted to switch to allow bungee support, so I did.
Now /tell is registered to chatcontrol
/reply is registered to chatcontrol on one server, and to customchat on the other
msg is registered to custom chat, however /message (on one server) is registered to chatcontrol.

If I disable customchat commands for private messaging, essentials takes over. 

config server 1 https://hastebin.com/fatizivako.php
config server 2 https://hastebin.com/ecovuzodox.php
They might look identical, as they probably are :p 

I've checked the wiki and found about prioritizing, however I am not sure if they apply for private message commands?

Using version 7.5.12 on both servers.

**Comment by malonnnn** [comment]
I compared your configs using text-compare.comand they are different.

Config 1 is missing "message" at line 135. (Private_Messages: Aliases: Tell:)

Config 1: Disable_Only_In_Commands: true
Config 2: Disable_Only_In_Commands: false

Config 2 is missing "/t" at line 195. (Sound_Notify: Enabled_In_Commands:)

**Comment by kangarko** [comment]
What are you asking us about exactly?

You must disable private messages in ChatControl if you are using your custom plugin for them, otherwise they will interfere.

Priorities do not apply for commands.

**Comment by Managering** [comment]
Hi,

/t is removed because we use Towny.


The issue is. When I disable my custom chat private message commands be re-assigning them, essentials takes over and not chat control.

I'd like to use bungee private messages and so Id like to use chat control.

**Comment by kangarko** [comment]
I see. There's an exception, if ChatControl detects that Towny is running, we do not unregister the commands and thus they may get overrided by another plugin.

Please open Essentials.jar, then open plugin.yml file and remove the 'msg' key completely (line 254) and also the 'r' key (314). You shall repeat this step each time you update Essentials.
