### ISSUE TITLE
Add /chc ignoreword <word> command

### ISSUE THREAD

**Issue by Pluginsel** [kangarko/ChatControl-Pro#416]
Please add /chc ignoreword (word) command on the 7.6 (future) updates.

**What is this?**

I like block the swears with qwerfew(swear)wedse words. But many words is receiving swears in the words.
This command is for ignore the words with swear and advertisements.

**Example:**
/chc addrule swear
(swear)
Block with wer(swear)qwe? YES

**After this:**
/chc ignoreword (word) : with this command is will ignore the words from swear and advertisement (is receiving swear is ignore) NOT BLOCKING THE WORDS! (Translated by google: this command will not prevent the word we write if it contains profanity in a glove)

Sorry for my bad english.

**Translated by google:**
This command will not perceive the word as blasphemy if we have curtailed it and if it contains profanity in a veil. This command works.

**Comment by kangarko** [comment]
Hey,

if you would like to ignore certain word from a filter, you can do this already by inserting a "ignore string <word>"  operator in your rule in rules/rules.txt file (open that file to see examples).

Thank you for the suggestion.

**Comment by Pluginsel** [comment]
Ok thanks.

**Comment by Pluginsel** [comment]
@kangarko can you add this feature with a command?
Because I don't understand the rules.txt

**Comment by kangarko** [comment]
There's already rules' creator via "/chc addrule", that's the closest you can get in regards of rules creation in-game.

**Comment by Pluginsel** [comment]
I think you do not understand what I want...
Read #436

**Comment by Pluginsel** [comment]
@kangarko 
I think you do not understand what I want...
Read #436

**Comment by kangarko** [comment]
Okay, lets continue there
