### ISSUE TITLE
Multichat - not compatible

### ISSUE THREAD

**Issue by R4zzer** [kangarko/ChatControl-Pro#417]
Can you add support for the Bungee Plugin Multichat?
https://www.spigotmc.org/resources/multichat.26204/

**Comment by kangarko** [comment]
What kind of support for what ? Is anything not working as it should?

**Comment by R4zzer** [comment]
all Features doesn't work (Pointssystem not tested)

**Comment by R4zzer** [comment]
Hello?

**Comment by kangarko** [comment]
Hey,

if Multichat offers the same functionality, it is overridden by it and there's nothing I can do.

You can try adjusting priorities of both Checker and Formatter to HIGHEST or MONITOR as specified [here](https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities), but if it won't work, then I am sorry it's incompatible.
