### ISSUE TITLE
Chatcontrol causing infinite threads

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#419]
I just noticed in my hub where i use the following plugins:
**LuckPerms, WorldEdit, Carousel, Skript, PlayerSettings, LampControl, PlaceholderAPI, VoidW
orld, BuycraftX, WorldGuard, SimpleTPA, Nicky, DeluxeMenus, SQLibrary, ViaVersion, Vault, ClickWarp, TitleManager, Stickers, PlayerPoints, ProtocolLib, LibsDisguises, Citizens, CommandNPC, MineSync, CustomPayloadFixer, FlickeringPumpkinsLite, GadgetsMenu, AuthMe, ChatControl, HolographicDisplays, CarlTheCreeper, AuthMeBridge**

Chatcontrol seem to causing to open infinite threads without closing them, at end of day i have like 14000 threads opened only in hub at end of day (i do restart every day) (i get threads number by using the command **ps -o nlwp PID** in ssh)
I have also enabled the java profiler (if you want i can share with you the data)
![immagine](https://user-images.githubusercontent.com/3611852/31537976-4300a84e-b004-11e7-919e-c4e8f0b89dfb.png)

I tried the old version 7.4.23 (before the BIG UPDATE) and threads now are back to human levels. And the issue "seem" to exist only at hub (where player enter). Also in other server will use high number thread in later hours, all these are caused by chatcontrol that is not closing correct the threads

Here there is the thread opened in hub after 2 hour
![immagine](https://user-images.githubusercontent.com/3611852/31538069-ac30bb06-b004-11e7-98e6-f662d96cd699.png)

**Comment by kangarko** [comment]
Hello,

I apology for the delay. Thank you for a such extensive report and included data. Those have been sufficient for me to trace down and solve this issue. A new release will be available tonight. I am closing this in faith that this has been resolved (I have tested the release and it seems;), but please comment below if there will be anything.

Thank you for your patience.

**Comment by xion87** [comment]
Great, all fixed ^^

**Comment by kangarko** [comment]
Awesome glad to hear!
