### ISSUE TITLE
7.5.14 New handlers.yml option

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#420]
The 7.5.14 update speaks about "Added "Only_In_Commands" key option to handlers.yml file".
I generated new default files but this option is not to be found as text or comment. Please provide information for those who might consider using this.

**Comment by kangarko** [comment]
Hey,

ChatControl is flexible and you only need to write down the key you use. If the default settings do not include that option, just write it manually as per https://github.com/kangarko/ChatControl-Pro/wiki/Handlers
