### ISSUE TITLE
[Info] Formatter Listener_Priority for Denizen scripts with chat-triggers

### ISSUE THREAD

**Issue by SilberRegen** [kangarko/ChatControl-Pro#421]
`Listener_Priority:
  Formatter: HIGH
  Checker: NORMAL`

Just in case someone asks or you would like to add it to your wiki.
This is my settings for the Listener-Prioritys, which will allow the Citizens2-Addon Denizen to catch chat-triggers for it's scripts.
With Formatter on NORMAL, my NPCs didn't react anymore after I installed ChatControlPro. On HIGH it works.

**Comment by kangarko** [comment]
Thanks, added!
