### ISSUE TITLE
/chc global switch Not functioning properly

### ISSUE THREAD

**Issue by SpiderRobotMan** [kangarko/ChatControl-Pro#426]
Hi, When attempting to utilize the `/chc global switch` command on my server, it will properly switch to Bungee chat, but then when running the command again it tells me that it has turned off Bungee chat but all messages are still sent to global using the global formatting. If I manually set the chat mode back to `DEFAULT` on my MySQL server while the user is logged off it does properly switch them back. There are no errors in the console associated with this error.

The message saying it is no longer sent to bungee is simply repeated over and over again upon each use of the command once it switches you to global. See image here: http://i.spiderrobotman.com/8oPCI.png

**Comment by kangarko** [comment]
Hi!

It appears that you must have Bungee_Chat.Enabled_By_Default enabled. I have edited ChatControl so, even if you have that enabled, it'll allow you to opt-out.

Cheers!
