### ISSUE TITLE
Bug: Fastmessages is handled as swear

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#428]
Since recent update got a weird error. 

Player chats a little fast

Console:
Set PLAYERNAME 'fastmessages' points from 8 -> 10

Player gets punishment for swear category!!

**Comment by kangarko** [comment]
Hey,

I cannot reproduce. Please post me Points part from your settings.yml.

**Comment by x1p** [comment]
I will pm you
