### ISSUE TITLE
Ignore toggle is case sensitive.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#430]
Player is named SuperRabbit.
You want to ignore them so you type ```/ignore superrabbit```.
It outputs 'You are now ignoring SuperRabbit.' in chat.
You decide you don't want to ignore them anymore so you re-type ```/ignore superrabbit```.
It outputs 'You are now ignoring SuperRabbit.' again in chat and doesn't remove them from the ignore list.

You have to specify their exact name case (```/ignore SuperRabbit```) to be able to remove the ignore.

**Comment by kangarko** [comment]
Hey,

oh I missed that! This will be fixed.
