### ISSUE TITLE
Would it be possible to allow messaging players globally by their displayname / nick & non-case sensitive name matching?

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#431]
With essentials, you are able to message someone by their current displayname / nickname. As well as use parts of a name for best guess matching for who you actually were trying to reach. However with ChatControlPro, you are required to type their full player name or the very specifically beginning parts of their actual name to be able to message someone.

A player is named iMxFollyy.
You want to message folly by typing ```/msg folly hi```.
This works with Essentials, doesn't work with ChatControlPro.

A player changes their displayname with the command ```/nick test```.
You want to message 'test' by typing ```/msg test hi```.
This works with Essentials, doesn't work with ChatControlPro.

This is with BungeeCord private messaging enabled on ChatControlPro, BungeeControlBridge installed on Bungee, and vault installed on each bukkit server.

**Comment by kangarko** [comment]
Hey!

In short, no. Such methods rely on heuristics and may provide fail results. Imagine there are two players named Folly and MyFolly, and you type "folly" - it would produce two results from the Bukkit#matchPlayer method. I am aiming to keep ChatControl as stable and reliable as possible.

But, I have marked that down as a future suggestion.

**Comment by mibby** [comment]
What about if there was a config option to opt into such functionality? I believe Essentials does message multiple players if the part of the name exists in others when trying to message a specific part of a name, but with more unique names such as xXxSuperExamplexXx, players and staff have informed me they far prefer the openness of having options of using any bit of a name to message someone rather than being required to use the full name or beginning characters.

Being able to message players by the section of name they are known for and the nick they may have shown are two options that are heavily requested by my community coming from essentials. :)

Perhaps seeing how essentials handles it could help provide some insight for how to process the heuristics check with BungeeCord?
https://github.com/drtshock/Essentials/tree/2.x/Essentials/src/com/earth2me/essentials/messaging

**Comment by kangarko** [comment]
Thank you for that information. Btw you can use tab-complete if you're on the same server. I totally understand that it is difficult to manually fill out some names, and that's why I will look into it as per the roadmap schedule.
