### ISSUE TITLE
Would it be possible to have an alternative {sender} placeholder for displaying the sender's current displayname + vault color rather than their account name white?

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#432]
Would it be possible to have an alternative {sender} placeholder for displaying the sender's current displayname + vault color rather than their account name white? You can use {display_name} in the private_message_sender configuration, but there doesn't seem to be an alternative placeholder for displayname showcase of the sender for private_message_receiver configuration.

**Comment by kangarko** [comment]
Hello!

I totally see your point! (Btw thank you for reporting issues, I am on them) At this current moment, however, such addition is not achievable with the current system. 

I have marked it down as a suggestion, thank you!

**Comment by mibby** [comment]
> (Btw thank you for reporting issues, I am on them)

Sure, no problem. :P I was mainly just trying to get the sender and receiver messages as close to essentials' formatting as possible so the chat backend is more of a silent swap with same (and greater) functionality with cross server support. 

If such an addition is possible in the future, I'd greatly appreciate it.

**Comment by mibby** [comment]
Just out of curiosity, how hard would it be to get this implemented? It would help a lot in making messages look prettier since currently display_name can only be used one way (Private_Message_Sender - not Private_Message_Receiver).

**Comment by kangarko** [comment]
I don't know because the list (https://github.com/kangarko/ChatControl-Pro/issues/343) is pretty large and I am currently busy with two new products and exams next month.
