### ISSUE TITLE
Question: where is /me formatted?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#434]
I'm assuming it's formatted with this plugin but I cannot locate it anywhere?  Sets the nick to red (&c) and the message (action) itself to &5.  Let me know or if I need to track this down elsewhere (other likely candidate is Essentials, but if that's it, it can't be edited).

**Comment by LogGits** [comment]
Its essentials and yes it can be edited with the use of a locale file.

**Comment by kangarko** [comment]
Hello,

currently, ChatControl does not offer native /me command. It must come from elsewhere, such as Essentials.

**Comment by mrcoffee1026** [comment]
Thanks to you LogGits, perfect info there... had to do some looking into how to get the locale file where it could be edited, but that's what I needed.  Thanks for taking the time anyway kangarko, much appreciated.
