### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by Pluginsel** [kangarko/ChatControl-Pro#436]
Can you add ignore-word system in the version 7.7.0 ?

NOTE: This is NOT block the SWEARS or ADVERTISEMENT! Because is already have.

This feature, is for ignore the words from swear and advertisement.

Example: (I creating new swear)

-chc addrule swear
-fuck
-yes

And DONE! But wait... 
ChatControl is blocking this swear:
sdfdFUCKwedfr

for this, can you add /chc ignoreword <word> command?
Example:
-chc ignoreword sdfdFUCKwedfr
And chatcontrol is blocking the FUCK or qwewswerFUCKwere, but is NOT blocking this: sdfdFUCKwedfr

**With this command, if the inside of the sheath contains any kind of profanity it will not perceive it.**

Sorry for my bad English.

**Comment by ipr0james** [comment]
I believe this is already possible. However I'm unsure if there is a command to do it, but through the rules file itself instead. 

match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu)\b
id Advertising2
ignore string (www.google.com)|(www.youtube.com)
handle as advertisement

I took this example directly from one of my configs. This is for blocking website links. By adding 'ignore string' then the string you'd like to be ignored you can ignore a certain word that would've been filtered.

In your example using

ignore string sdfdFUCKwedfr

I hope this works for you. Please let me know if it doesn't :D

**Comment by Pluginsel** [comment]
Hmm... Ok.
But I need this feature with a command-in-game.
I don't like the rules.txt
@ipr0james

**Comment by ipr0james** [comment]
Just read your previous ticket. At this current time I don't think it's a feature tho I'm sure it could be planned for a future addition if Kangarko feels it's worth an addition. 

Currently the only way I can see would be directly editing the rules.txt, If you'd like assistance in directly editing let me know and we can work it out.

**Comment by Pluginsel** [comment]
@ipr0james Well. But do you understand what I want?
If it contains profanity in a glove, it will not hinder it because it is a different word.

**Comment by ipr0james** [comment]
I think so.

However I'm unsure on one thing, So you want the filter to not pickup all words using for example 'fuck'.

Do you want:

1.
Only fuck on it's own to be picked up

2.
'fuck' and 'fwefuck', but not 'fuckergwfe'

**Comment by Pluginsel** [comment]
@ipr0james Yes!

**Comment by ipr0james** [comment]
I mean which of these is it you're looking to do :D 1 or 2.

**Comment by Pluginsel** [comment]
@ipr0james 2.

**Comment by Pluginsel** [comment]
@kangarko Can you add this for 7.7.0?

**Comment by ipr0james** [comment]
The only way this is currently possible is through the file.
Also after speaking with kangrako last night the way the files are currently iterated it's not possible to add it currently. However I think it could be possible in the future.

Or maybe during creation/addition process it could be possible to specify ignored words for the rule there.

If you need help editting your rules for ignored words. You can hit me up and I'll talk you through/show you how to add ignored words into the rules.txt for now until(if) this feature is added in the future.

**Comment by kangarko** [comment]
Hey!

With the current system, you can add 'ignore string' operator to each rule manually. In the future we may have a command for that.

If you want to make a rule for 'fuck' and you **do not** want it to block 'qwe_Fuck_werf' for example, just follow this procedure:

1. /chc addrule swear
2. Type "fuck" to the game chat.
3. Type "no" to the game chat.

But I understand what you mean - to add ignore for only specific words. As mentioned, currently this is possible via "ignore string" operator and in the future we are open towards adding it as a command :)

**Comment by Pluginsel** [comment]
@kangarko is not:
/chc addrule swear
Type "fuck" to the game chat.
Type "no" to the game chat.

I need for 'ignore string' operator.

**Comment by Pluginsel** [comment]
@kangarko can you re-open this issue?

**Comment by kangarko** [comment]
We already explained to you that such system is not currently possible, as ChatControl cannot manipulate with your rules/ files, only write at the end of them. I take that as a suggestion however, my plate is currently full so unfortunately I cannot give you an ETA.
