### ISSUE TITLE
Feature compatibility

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#437]
Suggesting a feature which would enable users to reply to vanished players using the plugin PremiumVanish. Currently, when a non-vanished player gets messaged by a vanished player and he would reply to the vanished player, he would get the message `Player named X is not online`. Suggesting a feature where the non-vanished player would be able to use `/r` but not `/msg <vanished_player>` as that last one would be a bugg in the vanish system.

**Comment by Sikatsu** [comment]
Would like to see this too. While it is a premium plugin, you should be able to use the SuperVanish API if i'm correct.

**Comment by kangarko** [comment]
Hey,

ChatControl hooks into Bukkit#canSee method. You can enforce sending the message by giving the sender "chatcontrol.commands.pm.vanished" permission ;)
