### ISSUE TITLE
Private message suggestion

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#441]
Hey,

Is there anyway to show the nickname of a player within the private messages, instead of the actual player name?

----

And if a player has an nickname, /w <nick> says the player isn't online. Anyway to make it compatible with essentials nicknames?

http://prntscr.com/h0w5zg

----

Turns out if someone is called AToxicFish and you do /w ToxicFish or /w Fish it doesn't work, need to use the start of the actual playername. Are you able to improve this?

**Comment by kangarko** [comment]
Hey,

sounds good. I have added this into the road-map. 

Sincerely,
kangarko
