### ISSUE TITLE
Missing translation messages?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#442]
Somehow I can't seem to be able to translate the /togglepm messages and /ignore messages?

**Comment by FrankHeijden** [comment]
They’re in the jar > locale

**Comment by Sikatsu** [comment]
Even then i'm unable to find the ''{player} is no longer receiving private messages..'' and ''{player} is now receiving private messages.''

Same for the /ignore command messages.

**Comment by ipr0james** [comment]
I have also checked and can see that the message is missing from the localization files. Must still be hardcoded from before it was configurable.

Hopefully it'll be added to localization soon.

**Comment by kangarko** [comment]
Confirmed. Will fix in the next release. Sorry for the inconvenience.
