### ISSUE TITLE
Broadcast bugged?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#443]
My broadcast seems to be kinda bugged after I enabled private message stuff.

These are my settings:

Broadcaster:
  Enabled: true
  Mode: 2
  Prefix: '[JSON]'
  Suffix: ''
  Delay_Seconds: 300

Yet it's kinda spamming and sending 2 messages at a time.

https://pastebin.com/KrH0bDQb

**Comment by ipr0james** [comment]
Have just used your broadcaster configuration and enabled private messaging however not seeing the bug? Could you send over your settings.yml and just remove sql and any other information

**Comment by Sikatsu** [comment]
I haven't seen nor had this bug before I enabled private messages. Which is the only setting I turned on/changed.

settings.yml: https://pastebin.com/X1BGNkDE

**Comment by ipr0james** [comment]
I just checked using your files and same result as my previous test I don't get duplicate messages?

My suggestion would be
- Check you're using the latest version, however possibly an issue wit this version
- Setup a plain server and just run chatcontrol using that broadcaster setup and try to change things until the issue reoccurs if it does.

If it's an issue within the latest version it'll be fixed. I'm running a bit of an older version at the moment

**Comment by Sikatsu** [comment]
Server restart seems to have fixed the issue. Means it broke using /chc reload.

**Comment by kangarko** [comment]
Confirmed, caused by /chc reload. Will fix.
