### ISSUE TITLE
Reloading via '/cc reload' does not remove old broadcaster messages from cache.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#445]
ChatControlPro v7.6.6

Making changes to the broadcaster message list, reloading via ``/cc reload`` does not seem to remove the old messages from the rotation in the cache. It still displays the old messages.

Edit: I think reloading also breaks the broadcaster timer as reloading multiple times, I have messages occurring really frequently on top of each other. It might be creating a new timer every time it is reloaded rather than killing the existing one.

**Comment by CrashOverrideMC** [comment]
/chc reload refreshes all settings including the broadcast in case you added/modified them. so it would start broadcasting like it hasn't broadcasted any messages before.

I have done a reload for /chc many times back to back, each time you do reload it will broadcast one of the messages from your list right away, cause it is starting the broadcaster all over, but after it does that first message the spacing between each message is still what you have it set to in the setting

**Comment by MrHumblePie** [comment]
I can confirm that making changes to broadcaster settings or messages then reloading has no effect, even if you disable the broadcaster and then reload the settings it still broadcasts old messages.

**Comment by mibby** [comment]
Weird, as I'm able to reproduce the issue with it keeping old messages in the rotation, as well as creating a new timer every reload so messages occur more often than desired. Perhaps it breaks with BungeeCord enabled if you guys don't use BungeeCord?

**Comment by MrHumblePie** [comment]
I'm not using BungeeCord at all and I am getting these errors.

**Comment by kangarko** [comment]
Possibly can confirm. Will fix in the next release :)
