### ISSUE TITLE
Option to disable anti_spam and anti_bot settings similar to anti_caps.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#449]
Would it be possible to add an option to disable Anti_Spam and Anti_Bot similarly to the Anti_Caps section?

**Comment by kangarko** [comment]
There are separate keys to disable features you don't use:

https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#how-do-i-disable-anti-spam--messages-please-waitdo-not-repeat-similar-commandmessage
