### ISSUE TITLE
Spam / Similarity subcommand

### ISSUE THREAD

**Issue by sigmaroot** [kangarko/ChatControl-Pro#450]
Hello,

Is it possible to whitelist a command like "/mail read" but NOT to whitelist "/mail send" in the spam / similarity check?

**Comment by kangarko** [comment]
Yes, simply put the commands with their arguments to the config:

    Whitelist_Similarity:
    - /mail read

**Comment by sigmaroot** [comment]
Sorry, when were this introduced?
I'm currently on version 7.4.24

**Comment by sigmaroot** [comment]
Running 7.6.8 your solution **is not working**.

My settings.yml: https://pastebin.com/uYYjPBvc

It is not possible to use **/mail read** multiple times due to anti spam.

**Comment by kangarko** [comment]
Hello,

you was right, I apology, I have fixed that.

**Comment by sigmaroot** [comment]
Hey,

Thanks, I will give it a try this week :)

**Comment by sigmaroot** [comment]
It's working fine, thank you :)

**Comment by sigmaroot** [comment]
Okay, next issue...

Because of that, players using **/home myhome** for example cannot use that if **/home** is whitelisted, because I have to whitelist every **/home xyz** to make that work

Is it possible to add something like **/home \*** ?

**Comment by sigmaroot** [comment]
I think you check actually for the **exact match**, so whitelisting **/home** does not has any effect for **/home xyz**.
It should be fixed if you change it to an **at least / at the beginning match**. In this case I could use **/home** to whitelist all **/home xyz** and I could whitelist **/mail read**, but this would not take effekt to **/mail send** or just **/mail**.

If you know what I mean 😄

**Comment by kangarko** [comment]
Fixed by adding regex option to whitelists ;)

**Comment by sigmaroot** [comment]
Works perfectly, thanks again 😄
