### ISSUE TITLE
Kick message for BungeeControlBridge.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#451]
Would it be possible to implement a kick message for BungeeControlBridge to have a custom kick message if you were kicked from the BungeeCord instance itself? Such as with LiteBans which supports plugin message channeling kicks directly to BungeeCord.

Or are the local ChatControlPro messages sent globally over BungeeCord regardless to allow for custom kicks as well as the random variety selection / custom display perms?

**Comment by kangarko** [comment]
Hey,

I take that as a suggestion. My plate is currently full, so you'll have to stick with the plugin you use for kicking players.
