### ISSUE TITLE
Multiple matches

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#454]
Hey there,

I noticed CHC stops searching for additional matches once it hits any rule.
As an example for  this behavior you can use multiple swears in the same  chat message. One match only will be matched and replaced.

I also noticed this by trying to colorize some specific matches in chat
```
match /test
then replace &b/test&r

match /asdf
then replace &b/asdf&r
```
If I use `/test` and `/asdf` in the same chat message only one is replaced with `&b` color.

How can I tell CHC to keep searching for matches once it its a specific rule?

As always thanks for reading.

7.4.24

**Comment by kangarko** [comment]
Hey!

Can you try setting Regex_Strip_Colors to false?

P.S: The functionality may have been slighly altered in 7.5.x, I strongly encourage you to migrate to 7.6.x. I can migrate your chat.yml (it is now in both channels.yml and formatting.yml) for you to save you time if you upload it.

**Comment by EvilOlaf** [comment]
`Regex_Strip_Colors` seem to do the trick for the colorization at least. Will test with swears later.

**Comment by kangarko** [comment]
I see, ChatControl must remove colors before each evaluation, hence this behaviour. There's little I can do about it due to the replace system, either the colors are removed, or they aren't, but that exposes potential bypasses.

**Comment by kangarko** [comment]
Closing in faith that it has been resolved.

**Comment by EvilOlaf** [comment]
Did not further investigate but I may remember that this truly did the trick for swears as well.
I'll catch up if not.
