### ISSUE TITLE
Request for points reset task

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#455]
Is it possible to make different reset periods for different points sets?

Something like:

Points:
  Reset_Task:
    Repeat_Every_Seconds: 100
    Remove: 
      fastmessages: 2
    Repeat_Every_Seconds: 900
    Remove: 
      swear: 20
    Repeat_Every_Seconds: 9900
    Remove: 
      example123: 200

**Comment by kangarko** [comment]
Hey!

You can specify how much points to remove from each set when the task hits in 'Points.Reset_Task.Remove', that way, you can emulate that behaviour by removing less points from sets that should be delayed more.
