### ISSUE TITLE
Discord and Admin_Chat

### ISSUE THREAD

**Issue by CrashOverrideMC** [kangarko/ChatControl-Pro#457]
I have recently linked the "/chc ach" chat with a discord channel for my staff. When someone is on mine craft and does "/chc ach #message#" it shows up in discord in correct channel but if a staff member replies from discord staff channel goes to regular channel in minecraft

**Comment by kangarko** [comment]
Sorry for the delay, did not get to it due to exams and such. Will get to it when I get home 28th December.

**Comment by kangarko** [comment]
Next version should finally cover this. I had to rewrite more than I thought and real life prevented me from implemented this earlier, sorry.
