### ISSUE TITLE
Apply Rules to Discord Messages

### ISSUE THREAD

**Issue by CrashOverrideMC** [kangarko/ChatControl-Pro#459]
Messages that are said in Chatcontrol are being filter and sent to discord, but ones that come from discord don't go through the same filter process before going to ChatControl. not sure if this is by design or a limitation.

**Comment by kangarko** [comment]
Yes, this is by design. There is a possibility to prevent it, I am taking that as a great suggestion!

**Comment by kangarko** [comment]
Added to when a player with the same nickname is online. Otherwise this is not possible since we rely on player's data for rules and antispam.
