### ISSUE TITLE
ChatControl Pro disabled due to MySQL, but MySQL isn't enabled.

### ISSUE THREAD

**Issue by Hry-** [kangarko/ChatControl-Pro#46]
Randomly getting this error on startup, worked fine for the past month (and no changes in configs):

17.05 12:32:45 [Server] INFO *----------------------------------------------*
17.05 12:32:45 [Server] INFO MySQL database connection malfunction. Have you reloaded?
17.05 12:32:45 [Server] INFO Plugin is now disabled.
17.05 12:32:45 [Server] INFO *----------------------------------------------*

settings.yml:

# ----------------------------------------------------
# MySQL connection allows to store same information
# over multiple servers.
# ----------------------------------------------------
MySQL:
  Enabled: false
  
  # [NOTICE] There is no automatic updater if you change the prefix!
  Table_Prefix: 'ChatControl_'
  
  Enabled_In:
  
    # Store which channel player was in when they logged out?
    Channels: true

**Comment by kangarko** [comment]
Update to the latest version please (6.9.2).

**Comment by Hry-** [comment]
Fixed it, cheers
