### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by DJKenzo** [kangarko/ChatControl-Pro#461]
Hey ^^

i have a idea for multi world servers: 
to make chat channels and fix it to a world and every player who joins the world joins automatic in the channel
another idea for multi world servers:
to create eq: 3 chat channel per world (admin supporter and user) and joins a admion on the world he joins auto to this world admin chat channel and so on

Have a nice Day,

DJKenzo

**Comment by kangarko** [comment]
Hello and thank you for your suggestions!

ChatControl already supports Auto Join for Chat Channels, so I believe you can use that feature right away.

Using your favourite permission plugin such as PermissionsEx you can add those auto-join permissions to your world. Tutorial for PermissionsEx is here: https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#multiworld--top

You can find more information here: https://github.com/kangarko/ChatControl-Pro/wiki/Channels#auto-join

Cheers!
