### ISSUE TITLE
\n does not work for multi-line messages in automatic broadcaster

### ISSUE THREAD

**Issue by MrHumblePie** [kangarko/ChatControl-Pro#462]
Pretty much as the title says, I am trying to make multi-line messages for the automatic broadcaster but \n (or anything else I've tried) does not work. 

While I'm at it - would it be possible to make it so you can set a noise to play when a message is broadcast? [Feature Request!]

**Comment by MrHumblePie** [comment]
Actually never mind - \n works if you surround your message with " rather than the default ' displayed in config file. I would close this but I'm not sure how!

**Comment by MrHumblePie** [comment]
In saying that, would still like the feature request of being able to play a sound when broadcasting a message! :)

**Comment by kangarko** [comment]
P.S: You can already play a sound using the Announcer feature, "/chc a". But I understand your question and take that as a suggestion.
