### ISSUE TITLE
[bug] Command Delay update broke all alias plugins. "please wait 1 second before your next command"

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#469]
I finally got the time to go through all the configs to update my configs today and update chatcontrol after it broke with a spigot update.
This latest version has an extremely annoying bug that it never used to have. 
Command_Delay: 1
Similar_Percentage_Block: 0

I have a ton of custom commands using commands.yml and also using mycommand, where if I run something like /checkrank it will be an alias and run that as /lp user USERNAME info. ChatControl just broke this EVEN THOUGH both commands are in the Whitelist_Delay. 

Which means my only way to get around this is to set Command_Delay: 0, which now means my server is open to scripts to spam commands.

Please fix this issue.

**Comment by kangarko** [comment]
Hey,

I am sorry you have issues! It just appeared that there was an issue in the reload command related to a (likely) Bukkit but of re-registering events. If you ever used /chc reload during your server's run course, please re-test using the next version.

**Comment by kangarko** [comment]
Closing in faith that this has been resolved.

**Comment by FrozenBeard** [comment]
Was a push made to fix this? I had to completely disable my command delay, so i've not been able to test if it was fixed?
is it safe to make changes and use /chc reload in game now?
