### ISSUE TITLE
/reload breaks swear filters

### ISSUE THREAD

**Issue by SentryTheDefiant** [kangarko/ChatControl-Pro#47]
I know /reload states that not all plugins can handle it, but the /reload command is really useful, and did not break the plugin on the previous free version. 

Perhaps this is already something you are aware of, but I thought I'd mention it. Thanks again for all your hard work

**Comment by kangarko** [comment]
Cannot replicate. What exactly has been broken after the use of the command? Ensure you are running latest both Spigot and ChatControl.

**Comment by SentryTheDefiant** [comment]
When I used /reload to apply changes to a plugin without restarting the server, ChatControl would no longer filter blocked words. This was under spigot 1.9.2 and the latest version of ChatControl

I've since reverted to the free version of ChatControl, as it still works after /reload, and also because in the premium version, even when channels are disabled, the plugin still takes control of the /ch command that some other chat channel managers use, so the other plugins lose functionality.

**Comment by kangarko** [comment]
So you have applied changes to an another plugin, and after reload ChatControl stopped filtering words? If I misunderstood and you've made changes to CHC, of which type they exactly were? E.g. editing XY in settings.yml, adding new rule in rules.txt,...

The /ch command is registered in plugin.yml within the plugin jar and it is not possible to remove automatically. You can easily disable it by inserting # (commenting out) the lines in plugin.yml (Just open ChatControl.jar with WinRar or similar, find the chc in commands section in plugin.yml and comment it out, and then finally save it. Do a server restart ;) ).

**Comment by SentryTheDefiant** [comment]
If I remember correctly, the only changes I had made to chc were adding new rules/words, but I had done that while the server was offline, 

Thank you for the instructions on the command registration. I will try that in the future.

**Comment by kangarko** [comment]
Did it happen since then?

**Comment by kangarko** [comment]
Closing. Please remind me if the problem re-occures.
