### ISSUE TITLE
EssentialsX's /msg Controlled Private Messaging

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#470]
I was the one that requested this to the Essentials team originally, it works and it works well, it needs to be part of Chat Control so I can switch from Essentials Messaging system and use Chat Control.

Please read this extract from their Wiki for how it works.

https://github.com/drtshock/Essentials/wiki
Controlled Private Messaging

This feature was added in build 210.

There is a configurable feature you may set called last-message-reply-recipient that if set to true makes your reply-recipient whoever you messaged last and not whoever messaged you last, with the exception that if you do not have a reply-recipient then whoever messaged you last will be your reply-recipient.

Here's a formatted scenario of the new last-message-reply-recipient feature:

    SupaHam: /msg Kakifrucht Hi

    SupaHam -> Kakifrucht: Hi

    Kakifrucht: /r Hi

    Kakifrucht -> SupaHam: Hi

    EvilOlaf: /msg Kakifrucht Hi

    EvilOlaf -> Kakifrucht: Hi

    Kakifrucht: /r Hi back to you, SupaHam!

    Kakifrucht -> SupaHam: Hi back to you, SupaHam!

If this feature is enabled, EssentialsX will take into account the last-message-reply-recipient-timeout setting. This setting allows you to configure the duration, in seconds, that the reply-recipient will not change, when receiving replies. If after this duration the recipient receives a message, the recipient's replies will start going to the latest message sender.

**Comment by kangarko** [comment]
Hey,

thank you for this suggestion! I take that as a 'delicate' suggestion, due to exams, so please kindly allow me to postpone it to the December, and then it'll be implemented :)

Cheers!

**Comment by kangarko** [comment]
Added.

> It is now possible to disable automatically setting your private message's receiver yourself as the last reply. With this option disabled, you can register a player to your /r only when you yourself send a private message.
