### ISSUE TITLE
[bug] Discord bug FULLY breaks the chat plugin.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#472]
Im not sure if this is something to do with me reloading configs, my syntax and configs are fine, I was just testing a permission for groups to bypass the same message spam. and BAM all of a sudden the plguin shuts itself down with a discord error.
https://pastebin.com/aacwXX7f

**Comment by kangarko** [comment]
Hey, oh I actually pushed a new release - including some changes in behaviour of the /chc reload command. Please re-rest that release :)

**Comment by kangarko** [comment]
Hey, I have done extra testing with DiscordSRV 15.4, and it appears to be fixed. I am closing this in this faith that this is the case, but please let me know if anything comes up again. Also I have lowered the console spam, only the most relevant error is printed.

![img](https://i.imgur.com/dY1jGoE.png)
