### ISSUE TITLE
Chat rules removes swedish characters

### ISSUE THREAD

**Issue by TomasOlsson** [kangarko/ChatControl-Pro#473]
The chat rules remove åäö from the text when writing smiley

![chc](https://user-images.githubusercontent.com/16115707/32471084-d2201d92-c35b-11e7-8e3f-b9db7f969df1.jpg)

**Comment by kangarko** [comment]
Hey,

this is a feature to make it harder for people to bypass the filter.

If you wish to disable it, set 'Translate_Diacritical_Marks' to **false** in settings.yml
