### ISSUE TITLE
[major][bug] After latest update /msg from chatcontrol crashes server.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#474]
After 7 crashes this morning and destroying some of my data, I was alerted that this was happening, I turned on /msg from chatcontrol yesterday as an alternative to essentials, and low and behold its crashing my server!
Not only that but it gave a bunch of players a multitude of achievements https://i.imgur.com/lQNeiQZ.jpg
https://pastebin.com/UJdd9i8R

Not only that SOMEHOW its interacting with my LuckPerms ranks!!!!! for some unknown reason whatever the hell ChatControl is doing just wiped all my temporary ranks (My fucking donators) from LuckPerms, what the hell is chatcontrol doing touching my LuckPerms?

**Comment by kangarko** [comment]
Hello,

thank you for letting me know. I am sorry you have such severe issues. I undestand it must be frustrating if the donators lost their perks because of my plugin. While I don't understand how LuckPerms is being affected by ChatControl (ChatControl cannot modify it's permissions by the nature of the plugin), there was detected a major problem in the Toasts' update from yesterday. I apology for this huge inconvenience. I will soon arrive home and push a proper fix, until now, please stay on the previous version.

More information at: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro-format-and-filter-your-chat.10258/update?update=195824

**Comment by kangarko** [comment]
How is the situation now, after (I assumed) you downgraded back to the previous version?

I understand your frustration, and I did my best to find a code in ChatControl that may have been the cause - but ChatControl does not even hook into any permission/chat plugin - we use Vault, which hooks to those plugins themselves. [Vault ](https://dev.bukkit.org/projects/vault)is a very stable and trusted plugin. LuckPerms isn't explicitly stated in its support list, so it is probably that LuckPerms uses the native Bukkit API to manage permissions and Vault falls back onto that, but still, ChatControl _only_ checks if the player has a permission or not.

**Comment by FrozenBeard** [comment]
Im assuming it was the crashing the server continuously for people using /msg that caused stress on the database, which in turn somehow broke the data. If you crash a production server, its designed to come back up, so it gets stuck in a loop, I work full time, this is a hobby, I cant keep my eye on the server 24/7. Obviously players will use /msg to message each other a hell of a lot, its a very basic and important communication method for players. its outstanding something this basic was creating such a bad crash and wasn't tested.
I tested the Toast system with the players and their feedback was that it was so annoying they wanted it removed instantly. 
So loose loose loose for me.
I just disabled the message system again, this is the second time I have tested it over essentials to see if the original bugs with it sending the wrong /r to people was fixed and I was greeted with crashes that caused more damage.
I reverted back to essentials as a fix.

**Comment by kangarko** [comment]
Hello, I am sorry for the trouble (actually a small) bug caused for your and many other servers. I have done testing but it required more time then I had at the time. I make sure this won't happen the next time.

As talking about the /r issue, if you decide to give ChatControl's PM system a try, and it appears again, please open a ticket.
