### ISSUE TITLE
Server Crashes!!

### ISSUE THREAD

**Issue by MatheweB** [kangarko/ChatControl-Pro#475]
I am on the latest 7.6.9 version of ChatControl Pro, and my server crashes whenever I attempt to start it up. I have the crash logs attached here: https://pastebin.com/a71jZiW7

Please let me know if you can get a fix out for this, as I have downgraded to an earlier chat control made in October to remedy this bug.

Thanks!

**Comment by kangarko** [comment]
Hey,

I am aware of the situation - the crash may be unrelated by ChatControl, but there was a major problem in how achievements were handled in the last update. I apology for the inconvenience. For now, please stay on the previous version.

More information at: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro-format-and-filter-your-chat.10258/update?update=195824
