### ISSUE TITLE
Broadcaster sounds not working

### ISSUE THREAD

**Issue by MrHumblePie** [kangarko/ChatControl-Pro#476]
Hello, unfortunately the new sound feature of broadcasts don't appear to be working (rest assured yes I have my mc sounds and volume up haha). I did notice though that when I updated my chatcontrolpro plugin that my config file wasn't automatically updated with the new code in the yml, I had to ask on Discord about that and then I basically copied the new code from a new copy of the yml. I'm on 7.6.9, spigot 1.12.2. 

I have included my messages config and other configs just incase you need them. Please note that yes messages are set to false right now however when I test this they are set to true. Thanks!

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/1450649/ChatControl.zip)

**Comment by kangarko** [comment]
I see, my bad, there are ways of sending the timed message, I totally forgot to implement the sound to one of those. This is now fixed!
