### ISSUE TITLE
Using multiple permission-based formats does not work

### ISSUE THREAD

**Issue by leNicDev** [kangarko/ChatControl-Pro#477]
I have my formatting.yml configured like this: https://gist.github.com/leNicDev/8280d43fa9556cc9b92c371ddb97c2cb

The LuckPerms group 'admin' has the following permissions:
- -chatcontrol.groups.*
- \*
- chatcontrol.groups.admin

The result is the following when sending a chat message: 
![ghnib3l](https://user-images.githubusercontent.com/9200820/32509045-80752fbe-c3ec-11e7-9c92-41b031de5932.png)

No prefix will be attached to the message.

(Using ChatControl Pro 7.6.8 second release)

**Comment by kangarko** [comment]
Hey!

The group permissions from ChatControl should not be used that way - you need to give your players prefix from LuckPerms directly.

Also, please make sure you gave that group the Admin format in Groups section in settings.yml.

**Comment by leNicDev** [comment]
Okay, I've changed it to this:
settings.yml: https://gist.github.com/leNicDev/88daeb41fb7e03092c3f5fa7d87aa51d
formatting.yml: https://gist.github.com/leNicDev/efa743f9f6f978ff363b090ea694f291

Every group has the following permissions:
- \-chatcontrol.group.*
- chatcontrol.group.\<group\>

Now every chat message contains the prefix of the group that is the lowest in the inheritance hierarchy.

**Example:**
Inheritance hierarchy (lowest to highest): Guide > Supporter > Mod

In this case a player assigned to the group "Mod" will have the "Guide" prefix.

**Comment by kangarko** [comment]
I have personally never used ChatControl like this, and had the prefixes come from PermissionsEx or LuckPerms and then just have {prefix} in the formatting.yml in chat.

Anyways, that's odd what you experience. I would say you also need to deny the previous permission explicitly:

```
Admin:
  -chatcontrol.group.guide
```

**Comment by separatio** [comment]
@leNicDev I've used LuckPerms and I found that the best way to go was to configure the meta in LuckPerms. Therefore, if I recall correctly, you should be able to use the following for LuckPerms prefixes:
`lp group default setprefix DefaultTitle`
LuckPerms does not add the group name by default to the chat, so you do have to use that.

**Comment by leNicDev** [comment]
Thanks for your help @kangarko and @separatio!
I managed to get everything working by negating the permissions of the child groups.

**Comment by kangarko** [comment]
Great news, happy to hear that!
