### ISSUE TITLE
Message priority issue

### ISSUE THREAD

**Issue by Managering** [kangarko/ChatControl-Pro#478]
Greetings, 

I've made a ticket about this before, in which I was adviced to disable things in essentials plugin.yml.

So I did.

However, after every reboot /msg turns into /whisper from essentials. Even though I've disabled it and configured Chatcontrol to take over.

By unloading chatcontrol, /msg becomes unregistered, so no whispering either. 
By reloading chatcontrol using /chc reload, /msg becomes /msg, as it is intended.

Config:
https://hastebin.com/nenavimevi.php

Please advice,
Managering

**Comment by kangarko** [comment]
Do you have Towny?

**Comment by Managering** [comment]
Yes

**Comment by kangarko** [comment]
Can you check whether the /t command from Towny still works after you do /chc reload?

**Comment by Managering** [comment]
Yes it does, as I did not add it as a command in the chc configuration.

**Comment by kangarko** [comment]
I see, clever move! I have adjusted some behaviour and it should be fixed in the next version. If not, please let me know.

**Comment by Managering** [comment]
Thank you.
