### ISSUE TITLE
Anti-Caps issue with YouTube URL's

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#48]
I'd like to keep the Anti-Caps feature enabled, however it's blocking YouTube URL's.

As for example: https://www.youtube.com/watch?v=Pz8LU4-JVtA

Will make it unclickable because of it. Any solution you can make or I can make? Would be ever so nice. ^^

**Comment by kangarko** [comment]
Thanks for an awesome video.

The issue shall be resolved in the next release.

**Comment by Sikatsu** [comment]
Haha hilarious :D

Thanks !!
