### ISSUE TITLE
[Suggestion] Offline Messages

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#481]
I think it can be a nice feature to add (it was requested by a lot of user on my server)
basically if you send a message to a user and that user is offline, it will be converted into a offline message and it will be keeped until X time or when that user is loaded by chatcontrol, that he will receive a offline messagge:
Greeting, you have the following offline messages:
- [From Tim]: Hi dude i miss you
- [From Anna]: hello here

I know this is can be a replacement for essentials, but it would be a cool addiction i think :)

**Comment by ipr0james** [comment]
I feel like it would be a better suggestion to have Mail as offline messaging could just confuse many players as to if the player is online or not, even with a message to say like "that user is offline so it's been sent as an offline message", Mail might be a better suggestion.

**Comment by kangarko** [comment]
Yes, mail system has been requested several times. It lies on the roadmap https://github.com/kangarko/ChatControl-Pro/issues/343 in Normal section, but I don't know if I get to it this year, sorry.
