### ISSUE TITLE
Command support to /ignore 

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#482]
On public chat messages, on private messages, tp requests... etc.  It would be nice if this feature did something, but does not appear to.

**Comment by separatio** [comment]
Hello @mrcoffee1026. Can you please send us some minimal configuration you have?
Mainly, we're interested in:
- the group you have issues with and its permissions
- other plugins that affect chat, such as Essentials, multiverse, etc...
- ChatControl configuration

Thank you! :)

**Comment by mrcoffee1026** [comment]
All groups / All permissions.  I tried /ignore (ing) a player using my admin account with /op... when that failed to work I asked another player to ignore my alt (with regular perms) and had it try sending the user private messages as well as talking directly into chat... the user saw all of their messages, as did I, and this is not a case where /spy is being used to circumvent the ignore (the user i had help me test doesn't even have /spy perms).

Essentials "affects" chat in some way but I don't know what you need to know from that.  Multiverse has no effect that I am aware of.  There is some option to affect prefixes by "world" but I have that disabled.  Jobs Reborn adds prefixes to chat.

I feel like /ignore should also contain configuration options to add certain commands that it would also filter beyond just messaging to the main "channel" -- no channels in this case since I've not enabled that yet -- along with private messages (/r /tell /whisper) such as /tpa <player>, /tpahere <player>, /pay <player>... which could be run using other plugins to circumvent the /ignore and be used to further harass the person attempting to be left alone.  Not sure if this was planned or not, or if I've just not located this area of the configuration.

I've included my settings.yml, let me know what else you need:
```
# !---------------------------------------------------------!
# ! File automatically updated at 15.10.2017 22:07:57
# ! to plugin version v7.5.15
# !---------------------------------------------------------!
# ! Unfortunatelly due to how Bukkit handles YAML
# ! configurations, all comments (#) were wiped. 
# ! 
# ! For reference values and comments, open
# ! settings.yml in the plugin .JAR file.
# !---------------------------------------------------------!

Anti_Bot:
  Cooldown:
    Rejoin: 4
    Chat_After_Login: 2
    Command_After_Login: 2
  Block_Chat_Until_Moved: true
  Block_Commands_Until_Moved:
  - /afk
  - /me
  - /rc
  Show_Quit_Message_Only_If_Logged: true
  Block_Signs_With_Same_Text: false
  Disallowed_Nicknames:
  - (f+(\W|\d|_)*u+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
  - bitch
  - asshole
Anti_Caps:
  Enabled: true
  Enabled_In_Commands: false
  Commands_To_Apply:
  - /msg
  - /tell
  Points:
    Warn_Set: spam
    Amount: 4 * ({capsPercentage} / 2)
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 75
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL
  - SOF
Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: true
    Ignore_Duplicate_Characters: false
  Commands:
    Command_Delay: 1
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 3 - {delay}
    Similar_Percentage_Block: 0
    Similarity_Points:
      Warn_Set: spam
      Amount: 4 * ({similarityPercentage} / 2)
    Whitelist_Works_Like_Blacklist: false
    Whitelist_Similarity:
    - tell
    - pm
    - t
    - w
    - r
    Whitelist_Delay:
    - spawn
    - hello
    Handle_As_Chat:
    - me
    - minecraft:me
    - action
    - eaction
    - describe
    - edescribe
    - eme
    - etell
    - tell
  Chat:
    Message_Delay: 1
    Delay_Points:
      Warn_Set: fastmessages
      Amount: 2 - {delay}
    Similar_Percentage_Block: 90
    Similarity_Message_Check_Count: 2
    Similarity_Points:
      Warn_Set: spam
      Amount: 4 * ({similarityPercentage} / 2)
    Whitelist_Similarity:
    - :D
    - xD
    - ty
    - yw
    - brb
    - ha
    - haha
    - hahaha
    - welcome
    - wb
    - hey
    - hi
    - sof
    - thanks
    - thnx
    - thanx
    - hello
    Whitelist_Delay:
    - test
Grammar:
  Insert_Dot:
    Enabled: false
    Min_Message_Length: 5
  Capitalize:
    Enabled: false
    Min_Message_Length: 5
Clear:
  Broadcast: true
  Do_Not_Clear_For_Staff: true
  Console_Lines: 300
Mute:
  Broadcast: true
  Prevent:
    Writing_Books: false
    Placing_Signs: true
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Death_Messages: true
  Disabled_Commands:
  - me
  - tell
  - msg
  - w
  - minecraft:me
  - action
  - eaction
  - etell
  - emsg
  - describe
  - edescribe
  - whisper
Announcer:
  Bungee: true
  Ignore_Self: false
  Log_To_Console: true
  Sound: ENTITY_ARROW_HIT_PLAYER, 1.0, 0.1
Admin_Chat:
  Bungee: true
  Log_To_Console: true
  Write_To_File: true
  Discord_Channel: admin
Bungee_Chat:
  Enabled_By_Default: false
  Log_To_Console: true
  Write_To_File: true
  Discord_Channel: global
Private_Messages:
  Enabled: false
  Bungee: false
  Aliases:
    Tell:
    - tell
    - msg
    - t
    - whisper
    Reply:
    - reply
    - r
    TogglePM:
    - togglepm
    - ignorepm
    - nopm
  Format_Sender: Private_Message_Sender
  Format_Receiver: Private_Message_Receiver
Ignore:
  Enabled: true
  Aliases:
  - ignore
  - ign
  Chat: true
  Private_Messages: true
Packets:
  Enabled: true
  Tab_Complete:
    Disable: false
    Disable_Only_In_Commands: true
    Allow_When_Message_Has_Space: false
    Allow_When_Length_Above: 0
Rules:
  Verbose: true
  Bungee: true
  Chat: true
  Commands: true
  Packets: true
  Signs:
    Check: true
    Block: true
    Drop: true
  Books:
    Check: true
    Replace: true
  Anvil:
    Check: true
    Replace: true
  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false
Console_Filter:
  Enabled: false
  Log: false
  Filter_Console_Messages:
  - Reached end of stream for
  - Connection reset
Sound_Notify:
  Enabled: true
  Cooldown: 10 seconds
  Require_Afk: false
  Require_Prefix: '@'
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Color: '&a'
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r
Groups:
  Enabled: false
  List:
    vip:
      Message_Delay: 0
      Command_Delay: 0
Points:
  Enabled: true
  Repeat_Last_Action: true
  Smart_Warnings: true
  Reset_Task:
    Repeat_Every_Seconds: 20
    Remove:
      global: 5
      spam: 1
  Warn_Sets:
    global:
      '5':
      - warn &7Please obey the &2rules &7otherwise you will be &4punished&7.
      '15':
      - |-
        warn &c**** &lHey &c{player} ****
         &7-> &cThis is your &6final &cwarning!
      '30':
      - kick {player} &cKicked for breaking the rules
    swear:
      '4':
      - warn &cYou have received first warning for swearing.
      '6':
      - warn &cPlease do not swear, otherwise an action will be taken!
      '8':
      - kick {player} &cInappropriate language (last warning)
      '30':
      - tempban {player} 30m autoban for swearing
    spam:
      '6':
      - warn &cPlease do not act like spammer.
      '10':
      - warn &cPlease do not spam, otherwise you will be banned.
      '30':
      - kick {player} &cSpamming the chat (last warning)
      '40':
      - tempban {player} 10m autoban for chat spam
    fastmessages:
      '6':
      - warn &cPlease slow down chat messages.
      '10':
      - warn &cSlow down chat, otherwise you will be banned.
      '30':
      - kick {player} &cSlow down chat (last warning)
      '40':
      - tempban {player} 10m autoban for chat spam
Variables:
  Custom_Enabled: false
  Vault:
    Multi_Prefix: false
    Multi_Suffix: false
Writer:
  Enabled: true
  Ignore_Players:
  - ignoredAdmin
  Commands:
  - me
  - msg
  - m
  - tell
  - t
  - reply
  - r
  - mail
Motd:
  Enabled: false
  Delay_Ticks: 2
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
  - '&8*--------------------------------------------------*'
  - '&fHello {player}, we kindly welcome you to &e{server_name}&f and wish you great
    experience :)'
  - \n
  - '&6Version: &f{nms_version} &7/&f 08.04.2017'
  - '&6Changelog:'
  - ' &7- &fAdded ChatControl Pro plugin'
  - \n
  - '&6Help &7- &f/help &6Settings &7- &f/menu &6Web &7- &f/web'
  - '&8*--------------------------------------------------*'
Spy:
  Enabled: true
  Command_Aliases:
  - spy
  - socialspy
  Format: '&c[spy] {player}: &7{message}'
  Channel_Prefix: '&c[spy] '
  Bungee: false
  Command_List_Works_Like_Blacklist: false
  Command_List:
  - /tell
  - /msg
  - /t
  - /whisper
  - /r
  - /reply
BungeeCords:
  Enabled: false
  Prefix: '&5[Bungee/{server_name}] &7'
MySQL:
  Enabled: false
  Connection:
    Host: localhost
    Database: chatcontrol
    Port: '3306'
    User: chatcontrol
    Password: SecureMy1Chat
    Table_Prefix: ChatControl_
    Connector_Advanced: jdbc:mysql://localhost:3306/chatcontrol?autoReconnect=true&useSSL=false
  Aggressive: false
Debugger:
  Sections: []
  Keys: ''
  Save: true
  Log: false
Listener_Priority:
  Formatter: NORMAL
  Checker: NORMAL
  Signs: HIGHEST
Command_Aliases:
- chatcontrol
- chc
- cc
Translate_Diacritical_Marks: true
Locale: en
Regex_Timeout_Milis: 100
Log_Lag_Over_Milis: 100
Silent_Startup: false
Regex_Strip_Colors: false
Reset_Cache_On_Quit: false
Enforce_New_Line: false
Server_Name: default
Check_Updates: true
Debug: false
Version: 18

```

**Comment by kangarko** [comment]
Hey, I could not reproduce from an early testing, will do more.

Can you please test with **MySQL.Aggressive** on **true**?

**Comment by mrcoffee1026** [comment]
This had no effect.  Also since doing the chc reload... /msg /w /whisper all cease to be commands... psh, nice.

**Comment by mrcoffee1026** [comment]
thanks saw you fixed the reload issue already!

Still, /ignore having no effect even with the MySQL.Aggressive on true.

**Comment by kangarko** [comment]
I am sorry, it works fine for me with or without MySQL. Btw, tp request cannot be supported because ChatControl does not see the plugin upstream.

![img](https://i.imgur.com/g3WkdF5.png)
![img](https://i.imgur.com/42DUrHi.png)

Do you have enabled Private_Messages in ChatControl? Do you have Channels or Formatter enabled? Any other plugins that may interrupt such as DeluxeChat, etc?

**Comment by mrcoffee1026** [comment]
I don't have private_messages, channels, nor formatter enabled.  However, since turning all of these on would not cause other commands to be not run/ignored through essentials on other players, it wouldn't fully resolve the issue either.  I need some way to simply disable the chc ignore feature entirely so that the one in essentials or griefprevention can take over as those can actually ignore tp requests as well.  And no I don't have DeluxeChat.

**Comment by mrcoffee1026** [comment]
Ok this got it, you do have a 
```
Ignore:
  Enabled: false
```
option.. doing this combined with putting the essentials ignore in their command override list solved the problem (along with granting everyone essentials ignore permission and revoking their chc ignore permission).  Would have been nice to use the one here but... there are a lot of essentials commands, if it can't filter out those well... it isn't going to do a lot... and I'm not ready to enable channels yet which may be a requisite of using the chc one... I'm not sure what is needed, but one of the 3 or all 3 of the items you mentioned is likely, and that maybe more changing to chat than we want right now.

Thanks for the help.

**Comment by kangarko** [comment]
Oh I see, ChatControl's ignore requires either Channels or Formatter to be enabled.

Another user opened an issue about it, I actually found the cause and fixed it ;)

What do you use for chat formatting?

**Comment by mrcoffee1026** [comment]
Well nothing?  I mean a few things put their 2 cents in along the way and in the end the format is "blah", but I have no one thing altering everything and spitting it back out.  Jobs reborn adds a bunch of letter prefixes to the front of everyone's chat lines signifying their job and rank therein... LuckPerms adds group tags to the front of those lines also (appears after the jobs stuff).  Essentials used to do that, but LuckPerms - thankfully - was able to just take that part over.  There was also some stuff with Essentials to format the chat lines further... same with LuckPerms.. but in either case making changes to either would cause the jobs stuff to simply stop appearing, or error wherever I tried to use placeholders that plugin said would be available.  In the end I basically shut off any "formatting" options made available in every plugin... except some tweaking in LuckPerms with the group displays... this seemed to be the appropriate approach since it caused the fewest headaches... downside would only be if I want to change the order of where the jobs noise shows up as there is no way for me to change that.

I may enable the channel system down the road, but I'd have to experiment with the formatter and see if it is able to steal the prefixing being applied from other plugins and still USE that information for it to be of much use to me.  Since it's an either/or situation, it's possible I could use it later... but on the other hand, I do want people's /ignore command to silence tp requests from the person they ignored as well... and it seems to me the only way to accomplish this is to use the ignore function in Essentials for the task (since that's the plugin providing the tp function also).

Thanks again for the help.

**Comment by kangarko** [comment]
Thank you for providing such extensive information. Just to clarify, the /ignore function has been improved in the last version to work regardless of channel and/or formatting system.

Into the next version I can support commands support into /ignore as well.

**Comment by mrcoffee1026** [comment]
SWEET!  Yeah if you get it to where commands like /tpa, /tpahere and /mail can also be ignored, I'd rather use the one you have in chc.  I notice the one in essentials doesn't notify people they are being ignored... which might result in them escalating things just to make themselves noticed.  Appreciate the help once again, I did notice your update adding the ignore functionality without the formatting/channel stuff active which I greatly appreciate.  We'll likely use channels at some point but are small enough I don't want to split up chat right now, and I don't know when/if we will be.  Thank you again for the time and attention to detail!

**Comment by kangarko** [comment]
Hey,

I got into implementing it, when I realized that the closest it can get is by defining a manual list of commands to ignore with their argument that we replace and evaluate against ignored players:

```
Ignored_Commands:
  - /tp {1}
  - /mail send {2}
```

Which has its limitation as specified above. Unfortunately I don't think hooking into Essentials' internals is possible and I don't have time for that due to exams.

Shall I try to add this feature as specified, would it be usable for you?

**Comment by mrcoffee1026** [comment]
Also wonder if you'd consider adding donate buttons or if spigot makes that against the rules on premium plugins... but as little as I've paid for this I picked up the Confiscate plugin for no other reason than to pay for it, and that's not nearly enough given as much work going into these.  Thanks again!

**Comment by kangarko** [comment]
Ow I am grateful! Actually you had a brilliant idea and I had a person asking me for this as well recently, so I decided to make up a banner over all of the sales pages, you can find a link at the bottom of https://www.spigotmc.org/resources/10258/. Thank You!

**Comment by kangarko** [comment]
Forgot to close :)
