### ISSUE TITLE
JSON lines in MOTD

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#483]
Hey! :)

Is it posibble to make more lines than 1 on the MOTD section? (JSON)

Thank you in advance for your answer!

Motd: 
  Enabled: true
  Delay_Ticks: 20
  Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F
  Message:
   '[JSON] ["",{"text":"Facebook","color":"dark_aqua","bold":true,"clickEvent":{"action":"open_url","value":"https://www.facebook.com/risingempiremc/"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Kattints ide a facebook oldalunk megnyitásához","color":"red"}]}},"insertion":"123"}]'

**Comment by kangarko** [comment]
Hey!

Yes, you can make it inside of your json file with \n, but not using multiple [JSON]'s.
