### ISSUE TITLE
Reloading forcefully disables message commands from other plugins.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#485]
ChatControlPro 7.6.10
Paper dev 1250 (Spigot 1.12.2)

Reloading ChatControlPro post start-up forcefully disables message commands from other plugins. I have the messaging system in ChatControlPro disabled (due to needing suggested features for cross-server pming functionality) to use EssentialsX's local PMing system in the meantime. When the server starts up. essentials messaging commands work fine (/msg, /tell, etc.). However if you reload ChatControl, the commands stop working. My guess is ChatControlPro is trying to re-disable its own messaging system and the commands associated with it even though it was picked up for use in another plugin.

**Comment by kangarko** [comment]
Hey,

your assumption were correct, since /chc reload supports enabling or disabling private messages, we un- and then re-register the commands. I have adjusted it so we only unregister them when PM's are enabled.

Thank you!
