### ISSUE TITLE
1.7.10 - ChatContol doesn't work

### ISSUE THREAD

**Issue by le0-minelandeu** [kangarko/ChatControl-Pro#486]
Hello,

after some time we wanted to play some mods. Unfortunately, the oldschool mods are on 1.7.10 so we had to use that version. But it looks like the ChatControl doesn't work.

[latest.log](https://github.com/kangarko/ChatControl-Pro/files/1464130/latest.log)

I know it is old version and I hope that it could be fixed. 😄 

Have a nice day.

Edit: I wasn't using BungeeChatAPI, but it still crashes on startup.

**Comment by kangarko** [comment]
Hello,

with BungeeChatAPI, I cannot replicate the problem. Please re-post me the log using the 7.6.11 version.
![a](https://i.imgur.com/8oQ3dYn.png)

**Comment by le0-minelandeu** [comment]
Hello, the plugin was loaded, but the chat isn't working.

I am using Cauldron 1.7.10 (mods+plugins) so if you don't provide support for 1.7.10 modded version, don't try to fix it.

[error.log](https://github.com/kangarko/ChatControl-Pro/files/1467705/error.log)
[latest.log](https://github.com/kangarko/ChatControl-Pro/files/1467706/latest.log)
![screenshot 2017-11-13 18 00 01](https://user-images.githubusercontent.com/31539367/32738356-e759eac6-c89c-11e7-8107-28614806acfd.png)

**Comment by le0-minelandeu** [comment]
Hello, I have another problem. It looks like ChatControl is working fine on 1.7.10 Cauldron (after I found fix for lib SpecialSources-1.7-SNAPSHOT). The plugin normally loades with default settings but when I use mine, there is that wierd SPECTAROR error. I am really sorry but I haven't found what causes it.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/1467842/ChatControl.zip)
[latest.log](https://github.com/kangarko/ChatControl-Pro/files/1467843/latest.log)

P.S. Tentokrát jsem již přístupové údaje k MySQL vymazal 😄

**Comment by le0-minelandeu** [comment]
Never mind this issue. The KCauldron 1.7.10 is really old version and many mods cannot just work with plugins. Mark this issue as solved.

**Comment by kangarko** [comment]
Closing per request. Good found with SpecialSource, I have added it to the wiki, thanks!
