### ISSUE TITLE
Messages are randomizing

### ISSUE THREAD

**Issue by GibsonVS** [kangarko/ChatControl-Pro#489]
Hi was having an issue on some of my servers. Chat messages, such as the announcer and essentials motd, seem to be randomizing every time I used chatcontrol. This is what the message is supposed to look like:
https://gyazo.com/5fe090164730aa43499c2fa37579c1f1 
and this is what it comes out as:
https://gyazo.com/dcae70c49f546b3c5d2df3b8d21d1d7f

I tried messing with the listener priorities but none of them seemed to change anything :(
Thank you for reading and let me know if there is a fix!

**Comment by kangarko** [comment]
Hello,

by Essentials' MoTD you're talking about the MoTD from that other plugin, right? Are you sure it's ChatControl that's messing up the messages?

You can try disabling Packet rules to see if it helps.

**Comment by separatio** [comment]
@GibsonVS I can see that those are also voting messages. Please check if the vote plugin you have sends any messages to the chat as well and please send a configuration for the server our way so we can help out better and faster.

Thank you! :)

**Comment by GibsonVS** [comment]
So I disabled the packet rules and it seemed to fix the issue! Thank you guys very much for the quick help!
