### ISSUE TITLE
Anti-Spam is very strict

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#49]
The Anti-Spam is very strict with basically everything. Any solution to keep it enabled but being less strict? I get a lot of complains about it ..

**Comment by kangarko** [comment]
Can you be more specific please? What messages are caught that should not be, etc..?

**Comment by Sikatsu** [comment]
If multiple people join and you say ''Welcome'' twice, or if you get multiple questions and say ''Yes'' I think.

I really get a lot of complains about the Anti-Spam feature that it's way to strict and ''whining'' about simple things :/

**Comment by Sikatsu** [comment]
It would be nice if you can say everything twice and it'll only block it when you say it for a third time.

**Comment by kangarko** [comment]
You can workaround this using Warning Points.

Implementing such memory system requires another resources, but I will see what I can do. I'll put a low priority mark on that.

**Comment by frizzbee30** [comment]
Agree'd with Kangarko, managing rules/points/whitelists is very much the server admins role! The rules/points need to be reviewed/adjusted regularly by staff, following feedback and analysis of efficacy, the plugin isn't designed to be an AI!  :)

**Comment by kangarko** [comment]
Closing, with following added to todo:

> It would be nice if you can say everything twice and it'll only block it when you say it for a third time.
