### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by MsArtix** [kangarko/ChatControl-Pro#491]
I did not see any open tickets about this so here it is. If possible implement some sort of [item] {item} [i] {i} where it takes the item in your hand and shows it in chat for people to hover over and see what you got. Why? I have a plugin that does this but its an extra plugin that I dont want to have when this is something to make chat control even better. (make this toggle so server owners can decide if they want it active or not)

Second improvement is a reaction game (once again this plugin already exists but would be a great addition to have within chatcontrol so 3-5 plugins are not needed for chat). Simply have a timer (configurable of course) and have the admin put a list of words and then then the first person to type the word has a command run (possibly random command from a list or not). Also if this could have a timer saying "kangarko typed the word in 7.45 seconds!" or something when someone does type the correct word. 

Thats all I got. Thanks for reading this and hopefully we will see one or both of these implemented in the near future!

**Comment by kangarko** [comment]
Hello!

Thank you for both of your suggestions. While they look absolutely great and would be welcomed by many, I am currently having exams so I have to say no for now. In the future I may look forward to expand the functionality as you described.

**Comment by MsArtix** [comment]
Here is a link to a WORKING plugin that allows [i] to show the item in hand in chat. https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/

**Comment by kangarko** [comment]
Thanks.
