### ISSUE TITLE
New Feature Request Auto Response Messages

### ISSUE THREAD

**Issue by hazycraft** [kangarko/ChatControl-Pro#492]
Can you please add like Auto Response messages. A settable message that is auto sent whenever the player receives an incoming private message while it is on. So it can auto reply a set message almost like email auto reply but with in-game chat.
An example for command could be /chc arm set Hey, I'm not available right now.
/chc arm on     ( which turns it on)
/chc arm off     ( which turns it off)

**Comment by kangarko** [comment]
Hey, thank you for that suggestion, I have added it to the roadmap. Having exams right now but after I may look into it.
