### ISSUE TITLE
[Suggestion] Better /ch set or "remote" join/leave commands.

### ISSUE THREAD

**Issue by SilberRegen** [kangarko/ChatControl-Pro#493]
I would love to have a bit more control about setting channels for players. Especially setting the mode of several channels for the player.
Currently I am switching my players channel modes (e.g. channel1 (write), channel2 (read) -> channel1 (read) channel2 (write)) with a rather convoluted script which executes /ch j and /ch l commands for the player. I feel this could be much easier with a /ch set command where one could specify the mode.

Since /ch set will set one channel and remove all others though, maybe having the option to execute join/leave for another player with the right permissions or as console would be more "intuitive" to use.

As it is, it does not feel like I am in control and can aid my players getting into the right channels for events and other occasions.

I hope you'll consider adding such a functionality, thanks in advance for your reply :)

**Comment by kangarko** [comment]
Hey,

thank you. I have expanded /ch switch and /ch set command to add the [mode] argument.
