### ISSUE TITLE
/calc triggers the advertising. 

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#495]
https://i.imgur.com/J9Y2GEB.png

**Comment by separatio** [comment]
Hey @FrozenBeard - You can add the calc command to the command similarity whitelist in order to quick fix this issue on your server.
I will forward this to @kangarko.

Thanks for the report!

**Comment by FrozenBeard** [comment]
Nah, it still flags.
It seems to only do it when players use spaces in it /calc 1 + 2 + 3 + 4
I do have a bit of a different adversing regex tho;

https://pastebin.com/xNrqzHVk

**Comment by kangarko** [comment]
Hey, I cannot reproduce, but you can always add the /calc commands to ignored commands in your handlers.yml

![img](https://i.imgur.com/ON03OUm.png)
