### ISSUE TITLE
1.13 Bonus Request

### ISSUE THREAD

**Issue by Pluginsel** [kangarko/ChatControl-Pro#497]
I love the 1.13 new command system. Because have the colors. :)
My request is.
After the release of 1.13, can you add 1.13 command colors system?

How to work ? 
editable commands in-game (or from settings)

> /chc command (command) set color to (color)
Example: /chc command /gamemode set color to Green
and after this command, the /gamemode command is will work with the Green color for all players. :)

And the example of syntax in-game:
> /chc command syntax of (command) syntax (syntax of command) set color to (color)
Example: /chc command syntax of /gamemode syntax creative set color to Yellow

Or add the ALL for the syntax, this ALL is will set to color for all syntax of this command.
> /chc command syntax of (command) syntax all set color to (color)
and with this, the /gamemode is will have the green color and the syntax (creative, 1 etc.) is will have the yellow.

Multiple Syntax?
> /chc command syntax of /gamemode syntax-1 set color to (color)
the syntax-1 is the part of syntax, because the many commands have the multiple syntax. 
Example:
> /chc command syntax of /gamemode syntax-1 set color to (purple)
and with this, only target player syntax is will have the purple color.

So:
/gamemode is green - survival,creative,spectator,adventure etc. is yellow and the target player is purple.

I waiting for your respond. :)

**Comment by Pluginsel** [comment]
NOTE: 1.13 isn't released.

**Comment by kangarko** [comment]
Hello,

thank you for your suggestion. I don't think it would be possible exactly as you wished to. Currently I don't have as much time as I used to have, but I can place it to my todo list.

**Comment by Pluginsel** [comment]
@kangarko Thanks. But you do understand exactly what I want, do not you? My english is not very good. 🥇

**Comment by kangarko** [comment]
If the Bukkit provides an API, a way for developers to do this, I can give it a try. I think so, colored commands are reasonable and understandable addition.
