### ISSUE TITLE
Enhance Tab-Complete Manager

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#498]
My idea for an enhancement: 

Allow tab completion of player names across a bungeecord network. Detect and remove players from this feature if the server/bungeecord using SuperVanish/PremiumVanish/VanishNoPacket.

**Comment by kangarko** [comment]
Awesome suggestions!

The first has been added to the road map (not sure when I get to it). The second was implemented right away :)
