### ISSUE TITLE
ChC doesn't tempban/mute if command has more than 2 attributes 

### ISSUE THREAD

**Issue by Rurdo** [kangarko/ChatControl-Pro#5]
Hi!
We are currently trying to set up our Chatfilters.
We tried literally every kick/ban Plugin but every Plugin needs the command format like this "/tempban {player} {amount} {Unit} {Reason}"

But ChatControl doesn't allows more than 2 Attributes, so Plugins with this format "/tempban {player} {Amount&Unit} {Reason}" will work, but all other won't. It just doesn't ban/tempban the player. 
Kicking or permanently banning (where you dont need so much Attributes) works fine. 
So the command looks like this, but just doesn't do anything:
"tempban {player} 15 M Testreason"

Any Ideas?

**Comment by Rurdo** [comment]
We just found a working Plugin which provides the needed functions.

**Comment by kangarko** [comment]
ChatControl does not provide tempban/mute features. 
You can execute command of any length or any amount of parameters from it, though.
