### ISSUE TITLE
Cant use /ch <channel> due to CCP. 

### ISSUE THREAD

**Issue by rbland96** [kangarko/ChatControl-Pro#50]
Hello there. I love your plugin and its doing great. The only issue im having is players are not able to use /ch <channel>. We use herochat and that command allows players to talk in local chat. So im wondering. Is there a way to disable the CCP channel commands?

**Comment by kangarko** [comment]
Hey, it is possible disabling that command by editing plugin.yml within the plugin jar.
See my post: https://github.com/kangarko/ChatControl-Pro/issues/47
