### ISSUE TITLE
initial plugin installation error

### ISSUE THREAD

**Issue by Megaro96** [kangarko/ChatControl-Pro#502]
When I try to install the plugin for the first time (clean spigot server -> drag n drop into "/plugins" folder) it will throw an error message which is probably related to the default configuration.

The plugin won't startup and doesn't create a config directory (or any config files).
Due to the error message I assume that there is a misspelling in the plugins default config which is leading to stop it immediately. As a result I do not have the option to correct it (due to missing config-directory). Therefore a initial installation is not possible with this version of the plugin.

Server version:  git-Spigot-3d850ec-f46ccd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Plugin version: ChatControl v7.6.15

Error:
https://pastebin.com/HAse1fdj

**Comment by separatio** [comment]
Thank you for this report. We will look into it as soon as possible. It seems pretty serious.

**Comment by ipr0james** [comment]
Hi,

This issue seems to have come up a couple of times.
Until further investigation it's likely an issue with when the plugin was compiled.
For now I'd suggest downgrading by one version until the issue is resolved.

**Comment by kangarko** [comment]
@Megaro96 please contact me on Spigot.

@ipr0james do you also experience this issue for yourself?
