### ISSUE TITLE
CombatTagPlus Plugin Support

### ISSUE THREAD

**Issue by Pluginsel** [kangarko/ChatControl-Pro#503]
I using the CombatTagPlus for pvp on my server and I activated the kill-messages from CombatTagPlus and ChatControl Pro plugin.
But if player escape from the combat, the ChatControl Pro kill messages is: 
Player killed by (nickname) with (item)

Bug is: does not write the name of the player who flees from the war.

Test this bug with CombatTagPlus plugin.

**Comment by separatio** [comment]
Hello @Pluginsel - can you please send some of your server configuration our way?
It is pretty hard to test with no other details provided.
As I see it, this is a Placeholder issue which have not been properly placed.

Can you at least provide the line in which this message is configured?

Thank you.

**Comment by Pluginsel** [comment]
@separatio Yes.
CombatTagPlus kill message line (latest version from SpigotMC, 1.3.1):
From 117 to 121 lines.
`# This message is displayed when a player is killed by another player. Set this to '' to display nothing.
kill-message: '&8&l>> &c{victim} was slain by {attacker}'

# Same as above, this is displayed when a player is killed by another player with an item in hand.
kill-message-item: '&8&l>> &c{victim} was slain by {attacker} with a {item}'`

ChatControl Pro kill message(s) lines/names:
Contact kill message (Line 225-226-227) - and all PvP messages of ChatControl Pro.

In short, the measurement messages of the CombatTagPlus plugin conflict with ChatControl Pro. So if a player flees, the fugitive does not write his name. What I want is either to fix this error, or add a setting to turn off PvP messages via ChatControl Pro.

I can not tell you exactly because my English is not good, I can install the plugin and test the error by setting the messages for the lines I threw. It's easy to test:
enter the server and open the sidebar, make all the death messages of the CombatTagPlus and ChatControl Pro plugin active (and use the version version of both plugins).
Once you hit your side, your battle shield will be active, then avoid fighting over a tsar before the end of the battle, and you will see the error in the conversation. Test this at least 3 times, sometimes it is not the error but sometimes it happens.

Thanks.

**Comment by kangarko** [comment]
Hello,

after reviewing this, I see that this is a major compatibility that sadly cannot be fixed on ChatControl's side.

Since death messages include all messages, even if you would remove the pvp messages on lines 400-445 in messages.yml, the pvp messages would still be handled by us, but then just as generic messages.

Unfortunately to avoid this bug, you have to completely disable death messages from ChatControl by setting Death_Messages.Enabled to false in messages.yml, and look for an alternative death messages plugin or continue to use CombatTag+.

**Comment by Pluginsel** [comment]
@kangarko So, can not you add a shutdown setting for each death message? For example: 
Skeleton_Kill_Message: false

**Comment by kangarko** [comment]
No sorry it does not work that way.
