### ISSUE TITLE
Customazation of command /chc switch global

### ISSUE THREAD

**Issue by Managering** [kangarko/ChatControl-Pro#504]
Greetings Sir,

I'd like this change in order to make it fit to my current custom chat setup. 
We use our own channel system using the /ch <channelname> command. 
We like to keep things short and neat, and /chc switch global is a bit long to perform in some cases. 
A custom command option would be great :)

Thanks in advance,
Daniel

**Comment by ipr0james** [comment]
You could setup a custom command inside of the commands.yml built in with bukkit/spigot.

**Comment by kangarko** [comment]
Please read https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands
