### ISSUE TITLE
Please fix Mvdw Placeholders

### ISSUE THREAD

**Issue by hazycraft** [kangarko/ChatControl-Pro#505]
Ever since I updated to new Mvdw updates
https://www.spigotmc.org/resources/mvdwplaceholderapi.11182/updates
None of my Mvdw placeholders will work in chatcontrol, but they work in featherboard and other plugins fine.
![](https://i.imgur.com/8EvmdgP.png)
the 2 that are working are placeholderapi placeholders btw
was working great before mvdw updated his stuff.

**Comment by ipr0james** [comment]
if I'm thinking correctly it's using the mvdw placeholders through PlaceholderAPI, meaning you'll need to download the module in PlaceholderAPI, /papi ecloud dowbload mVdW. 
ChatControl does supportt mVdW so I'm unsure if the mvdw is required at the start.

**Comment by kangarko** [comment]
I haven't noticed any changes in the API we use, please contact Maxim regarding this.

ChatControl uses own integration with that plugin:
![a](https://i.imgur.com/I7m7vQX.png)
