### ISSUE TITLE
TacoSpigot 1.8.8 ChatControl Randomly Disables

### ISSUE THREAD

**Issue by Fluxty** [kangarko/ChatControl-Pro#507]
Hello,

Our entire network runs on the latest build of TacoSpigot 1.8.8. Only ONE of our servers is having this issue, and that is SkyBlock Pandora (The other two SkyBlock servers work without issue!?!).  Upon our daily reboot, ChatControl randomly decides it's not going to enable.. sometimes. 60% of the time it works fine, the other 40% it disables itself. A simple /plugman enable or server reboot fixes the issue, no changes necessary. So what's going on?

https://hastebin.com/enunepuyej.md

**Comment by kangarko** [comment]
Hello, please contact me on SpigotMC.

**Comment by Fluxty** [comment]
@kangarko I've shot you a PM over on Spigot
