### ISSUE TITLE
Spying and ignore is not working

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#509]
https://prnt.sc/hh0qa3
Default settings for spying..
Hope u can take a look!

**Comment by AmazedMender16** [comment]
http://prntscr.com/hhx2sa

**Comment by AmazedMender16** [comment]
have send u a PM on spigot with all the files.

**Comment by AmazedMender16** [comment]
i have generated new files. Changed everything again and it stopped working. All i did was added 2 commands to spy, and changed the look of the spy message. Hope u can look into it.. Will send a PM with the newest files.

**Comment by separatio** [comment]
Hey there. I also double checked this with @AmazedMender16 and made a few other configs to see what's going on. It seems that pretty much nothing other than the original works.

**Comment by kangarko** [comment]
@separatio where? I tested formatting and /spy command, all works, can you post the exact configuration?

![a](https://i.imgur.com/bjYH3vu.png)

**Comment by separatio** [comment]
I followed up on some talks with @AmazedMender16 and it seems that there's a conflict somewhere, with his plugins. The problem that still remains, as far as I can tell, is that the default config still works, while anything different, doesn't. I will test it out as soon as possible (tomorrow or possibly the day after) with most, if not all of his plugins and will let you know of the results.

**Comment by kangarko** [comment]
@separatio okay let me know, have the final exam on Wednesday 13th so if you don't find it I can take it after then.

**Comment by kangarko** [comment]
@AmazedMender16 is the issue still present?

**Comment by AmazedMender16** [comment]
When using /chc reload it all stops working

**Comment by kangarko** [comment]
Just testing, works for me on the latest version, are you sure you only used /chc reload and not plugman?

![a](https://i.imgur.com/mA0ZjnB.png)

**Comment by AmazedMender16** [comment]
Yes i dont use plugman it happends with /chc reload! Also make sure im running it on a bungeecord network

**Comment by kangarko** [comment]
Tested over Bungee, /spy and /ignore works for me. Are you sure you have the latest both ChatControl and BungeeControlBridge?

**Comment by AmazedMender16** [comment]
Yup always up to date on chatcontrol

**Comment by kangarko** [comment]
Responded on Discord.

**Comment by kangarko** [comment]
@AmazedMender16 is this issue resolved?

**Comment by kangarko** [comment]
Closing in the hope that this has been resolved.
