### ISSUE TITLE
Invalid settings.yml resets the whole file

### ISSUE THREAD

**Issue by totokaka** [kangarko/ChatControl-Pro#51]
I just tried configuring the plugin, and after going through the whole `plugins/ChatControl/settings.yml` file, I made a small mistake by missing quotation marks around a message (The message began with `§`), and the plugin 'fixed' this by resetting the whole file.

When a formatting error occurs, I think the plugin should either just shut down, or backup the original file before trying to fix the problem.

Plugin version: `v6.9.3`
Server version: `git-Paper-754 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)`

**Comment by EvilOlaf** [comment]
Or cancel the reload and use the old (cached)  and valid settings. However if the the server gets restarted with invalid settings it needs to fall back on the default settings. 
As written above the invalid file could be backed up though.

**Comment by totokaka** [comment]
Just to make it clear, I was starting the server with an incorrectly formated settings.yml, not reload. I do think the plugin would have reacted in the same way either way, though.

When the plugin registered the error, it printed all the fields from the config with their new/reset values in the console. This wasn't very helpful, though, as it didn't print the values I had written, only the ones it reset them to.

**Comment by kangarko** [comment]
Hours spent on the "smart" configuration and you are telling me that? Well, confirmed & fixed. One line fix :) Thanks for reporting.

A new release will be available soon, I just need to push some more changes so I won't waste release numbers before we hit 7.0.0.

**Comment by kangarko** [comment]
Forgot to close the issue.
