### ISSUE TITLE
Join And Quit Messages Are Not Working.

### ISSUE THREAD

**Issue by andrew121410YT** [kangarko/ChatControl-Pro#511]
i gave the permission for join and quit messages but all it's showing is the default join and quit messages.

**Comment by andrew121410YT** [comment]
Here is my plugins list https://ibb.co/k1Jfeb

**Comment by kangarko** [comment]
Hey, make sure you enabled them in messages.yml - Join_Message.Enabled and Quit_Message.Enabled.
