### ISSUE TITLE
CHC not recognizing Multiple Names in a message

### ISSUE THREAD

**Issue by MsArtix** [kangarko/ChatControl-Pro#513]
In a message if I type "Hey PLAYER1 you know PLAYER2 is nearby" it will only highlight one of their names not both. Link is to a SS of it. BlankYD is a player as well as JungleSayN so both should be green and not just one. 

[https://gyazo.com/08f4e6a8161fe906eaaf18fb0186a014](url)

**Comment by kangarko** [comment]
Hey, at this current point, you can only tag one player at the time.
