### ISSUE TITLE
Auto update language file

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#514]
Is it possible to auto update the language file instead of manually needing to add it to the language file? I don't need these lines, yet it makes the console less clear.

https://pastebin.com/6aScyRuG

**Comment by kangarko** [comment]
Good evening,

I have identified this problem, thank you for the report. It appears in the underlying library all of my plugins are using, so you may have to update all of mine plugins having localization. I apology for the inconvenience.
