### ISSUE TITLE
/ignore Improvement

### ISSUE THREAD

**Issue by MsArtix** [kangarko/ChatControl-Pro#516]
I am working on my servers /ignore feature cause of some issues with players and because I use essentials and chc, CHC overrides /ignore for essentials so it can block chat messages (I figure this will block PM's only if chc pm's are enabled) so it doesnt block essentials msg's. May I suggest adding the following features for /ignore to make it more true of an ignore command. 
Under
  Chat: true
  Private_Messages: true

Add something like
  Ess_Private_Messages: false 
  TPA_Requests: true 

(default Ess_Private_Messages to false because you assume the server will be using CHC pm's)
(TPA_Requests would block any kind of TPA requests sent from that player however it would not block /tp which is basically forcetp)

Biggest reason I suggest these added (at least the TPA requests) is because if someone ignores a player and they can still recieve TPA requests its still annoying for the player who ignored the other person. The Ess_messages part is completely optional as I am working on switching over to CHC msg's. I know last time I tried there was an issue with it interfering with towny commands because towny is based off of /t

**Comment by kangarko** [comment]
Thanks, added.
