### ISSUE TITLE
Error on latest version

### ISSUE THREAD

**Issue by TWSSYesterday** [kangarko/ChatControl-Pro#517]
https://hastebin.com/kifunufacu.sql
Using latest PaperSpigot version and latest ProtocolSupport if that helps, won't even load files.

**Comment by TWSSYesterday** [comment]
I've attempted to use multiple versions of ChatControlPro and same result.

**Comment by TWSSYesterday** [comment]
Reverting back to 7.5.1-BETA works.

**Comment by kangarko** [comment]
Hello,

I apology for the issues. The cause may be twofold: either this error is hiding the real one, in which case I would recommend re-downloading the latest version, putting it on the server. In other case, you'll need to contact me on Spigot for further instructions (please also include a startup log to where it's relevant from the first launch after re-downloading). Thank you.

Have a great day/evening,
kangarko

**Comment by TWSSYesterday** [comment]
Sorry, didn't include the startup. Running on a production server so can't really revert. When the issue presents itself and gives that error, it downloads the plugin again with a "_" prefix. This beta version is one of the latest that works without issues for me.
