### ISSUE TITLE
Packet's rules less efficient

### ISSUE THREAD

**Issue by Heliosard** [kangarko/ChatControl-Pro#520]
ChatControl Pro: **7.6.18**
ProtocolLib: **4.3.0**
Server version: **CraftBukkit version git-TacoSpigot-"c2835dfc" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)**

I used until a few days an old version of ChatControl Pro in which packets rules worked perfectly. Since the update, some messages such as those of EssentialsX are no longer taken into consideration. In addition, I noticed that this rule no longer applies for operators.

**Comment by kangarko** [comment]
Please post out a specific rule so I can compare. Also, what older version were you coming from, noticing this change?

**Comment by kangarko** [comment]
Closing as a similar issue was resolved some time ago.
