### ISSUE TITLE
Select chat color ability

### ISSUE THREAD

**Issue by MsArtix** [kangarko/ChatControl-Pro#523]
What if ChatControl let you change your chat color completely without having to type "&b" or "&c" every time before you type your actual message. 

[A similar plugin](https://www.spigotmc.org/resources/chatcolor.1546/) brings up a menu (or commands) and you need certain permissions to see each color and be able to click on them and activate them.

**Comment by kangarko** [comment]
Hello and thank you for the suggestions! I am currently having exams so I suggest you use Skript programming language for the first suggestion. For the second suggestion I may look into it, but for as long the ChatControl+ plugin works you can just use it for the time being.

**Comment by kangarko** [comment]
Implemented.
