### ISSUE TITLE
 Error loading latest ChatControl

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#525]
[11:10:47 INFO]: [ChatControl] Enabling ChatControl v7.6.22
[11:10:49 INFO]: % java.lang.NullPointerException

Same as yesterday

**Comment by x1p** [comment]
Error log:

------------------------------------[ 10.12.2017 11:10:49 ]-----------------------------------
ChatControl 7.6.22 encountered a NullPointerException
----------------------------------------------------------------------------------------------
% java.lang.NullPointerException
NullPointerException(Unknown cause)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
I apology. I enabled https secure connection that connects to the antipiracy server, and it seems that not all systems support the driver. Will revert back.

**Comment by x1p** [comment]
With your clues where this error comes from, I tried a test server on our real server instead of my little test system. It runs well on our real server. So for me personally it runs. :-)

**Comment by kangarko** [comment]
Hmm yes that may be the difference between the systems causing this. New releases are on the way, they should work as usual.
