### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by Qinak** [kangarko/ChatControl-Pro#526]
Hello!

Characters like Å, Ä and Ö can't be used in words for recognition.
Will there be any support for these characters in the future?

**Comment by kangarko** [comment]
What do you mean by recognition?

You can set the key below to false to allow such characters to be included in the antispam:
![a](https://i.imgur.com/m6bmuRY.png)

**Comment by Qinak** [comment]
For example, if I want to block the letter Å. In rules.txt I've done this:

match \b(Å+(\W|\d|_)*)
handle as swear

but it won't recognize the letter and the players can still post it in chat.
If I change the letter Å to for example G, they can't type G in chat. So is it just the plugin that doesn't work with this kind of characters or am I doing something wrong?

Thanks for the fast support!

**Comment by kangarko** [comment]
Hello,

maybe it's because we strip diacritic marks. To disable that, you can set **Regex_Strip_Colors** to false and **Translate_Diacritical_Marks** to false in settings.yml.
