### ISSUE TITLE
"ChatChannel" class???

### ISSUE THREAD

**Issue by Hdadaw** [kangarko/ChatControl-Pro#527]
Hello, why i can't find a "ChatChannel" class, that described here:
https://github.com/kangarko/ChatControl-Pro/wiki/Developer-API
Or how can i create a channels for party chats?

**Comment by kangarko** [comment]
Hey,

good notice. The article has not been updated in a while, I have re-written it: https://github.com/kangarko/ChatControl-Pro/wiki/Developer-API

You can just download that jar and open it with any decompiler such as Luyten or JD Gui to see the possibilities.
