### ISSUE TITLE
Randomly disabled

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#528]
This morning 1 random server was disabled for no reason
```
[ChatControl] *-----------------------------------------------*
[ChatControl]  ChatControl could not check for an update!
[ChatControl]  Plugin is now disabled.
[ChatControl] *-----------------------------------------------*
[ChatControl] Disabling ChatControl v7.6.23
[ChatControl] Saving player data to MySQL..
```
License key is present. So I don't know why it is disabled at once.
After restart it works normally. Can chatcontrol maybe get more time to check connection in case internet is a bit buggy (due to maintenance)?

**Comment by kangarko** [comment]
That's weird, but I apology for the inconvenience. From the yesterday's release any errors are logged in errors.log, do you have that file in ChatControl folder please?

**Comment by x1p** [comment]
No errors at all. (Yes I know the existence of the error.log file.)

**Comment by kangarko** [comment]
Okay. Please allow me to test the error reporting service and track the cause when it happens again - remove the key I gave you. It'll work without any change since servers are patched from yesterday.

**Comment by x1p** [comment]
Ok. So I remove the key and nothing to change?

**Comment by kangarko** [comment]
Correct. If anything appears to happen please contact me privately on SpigotMC.
