### ISSUE TITLE
Command matches for /spy and "similarity" checks

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#529]
I have spy enabled and the 'treat as blacklist'...
```

  Command_List_Works_Like_Blacklist: true

  Command_List:
     - /sf elevator.+

```

I've tried some variations on this... /sf elevator by itself (without regex .+), for instance... when the command does run it will include three numbers delimited by spaces.  Ideally, I would like to not see this command showing up in [spy] with this setting, but it does.  I'm not sure what magical arrangement is needed to get this to work as expected.

I have also attempted to add the same cammand in this list:
```
    # Commands that the player can run them multiple times after each other.
    Whitelist_Similarity:
    - /sf elevator

```
However, this directive appears to be either ignored or... never matched.  Again, when the command is entered it will appear like this in [spy]:
[spy] playername: /sf elevator -71 71 50

I feel like that should be a matchable thing.  I'm not sure if it's getting some magic done to it since the command is run when stepping onto a SlimeFun pressure plate or what, but even if spy isn't showing this, the similar command thing is still being triggered either way and I need for people to move on and off these plates as frequently as they want.

**Comment by mrcoffee1026** [comment]
The blacklist normally works... I have an alias for chc ach set to /sc... and realized that [spy] was going to show me the command entered so I added /sc to the blacklist... and this had the desired effect.  The commands appearing incessantly are from... not typing.

/sf elevator [coords here]

Command is entered each time someone steps on a Slimefun elevator pressure plate.

/cs_triggerinterface [some string here]

Command is entered each time someone clicks a link in the Slimefun guide.

Ignoring either of these has no effect... possibly because the commands are not being typed, It seems like it should be possible to mute these sorts of things since the spy feature was able to capture the text and display it, however.  As far as I can tell, other commands entered on this list ARE being ignored properly, it's just these sorts of plugin-specific commands that are failing.

**Comment by kangarko** [comment]
Hello,

actually, if you disable `Regex_In_Whitelists` it will ignore all commands starting with the phrase, making /sf block as if it would be /sf .*

I am sorry, I cannot help you with third party plugins. We listen to the even normally and catch commands run by players, not by the console. If the SlimeFun casts the command to the player then it should be delegated to the "playercommandevent" which we further handle and the command should be ignored from whitelist or blacklist respectively. If that's not the case and commands executed by hand typting /... works, I apology but there's little I can do about it.

Last solution may be to change Listener_Priority.Checker to HIGHEST or MONITOR, although I am not sure if this will have the desired effect.

**Comment by mrcoffee1026** [comment]
regex_in_whitelists was already false.
I'll try the other 2 settings on the Listerner_Priority: Checker and let you know if that takes care of it.

**Comment by mrcoffee1026** [comment]
neither of these settings stopped them from showing up but I guess I can live with it.  Appreciate the help on this anyway, thanks!

**Comment by kangarko** [comment]
Just traveling tomorrow until 28th, I am closing this but please tag me after then if you don't find a better solution so I personally dig into it.
