### ISSUE TITLE
Lagg

### ISSUE THREAD

**Issue by elpedriyo** [kangarko/ChatControl-Pro#53]
Chacontrol is lagging my server could you please fix it: 
http://prntscr.com/bfacxm

**Comment by kangarko** [comment]
The actions of the plugin are not lagging the server. From the information provided, I see that you or someone else executed the /chatcontrol command which caused the server to hold a bit. 

I don't know what arguments were used in that commands and thus I am unable to resolve this. If it happens, please let me know and state the arguments you've used in your command (e.g. /chatcontrol mute).

PS: Using PaperSpigot and his timings can get you even more accurate results.
