### ISSUE TITLE
Improvement MySQL database

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#532]
Please introduce unique index id's to:
- enhance the overall performance of the database
- enable search query's
- easy editing the data in case of problems

**Comment by kangarko** [comment]
Thank you for your suggestion.

**Comment by kangarko** [comment]
Pulled to the roadmap.

**Comment by kangarko** [comment]
@x1p so you just want another column to the table with ID from 0 increasing up, basically from the first player being logged?

**Comment by x1p** [comment]
I think so. Unfortunately I can't translate this into java.
From what I'm told via a plugin developer, it's something like saying to the database connection to use an indexed database.

**Comment by kangarko** [comment]
Okay I had included it to the next roadmap, thanks.
