### ISSUE TITLE
Send yourself pm

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#533]
Danielabou: hello i have bought chatcontrol, i would like to know how can i stop to players send auto-pm msg 
http://prntscr.com/ho3pio
i want to block: You cannot send messages to yourself
you understand ?
thank you

kangarko: Hey, you can create a command rule for that. For more support please open an GitHub Issue and I gladly help you.

**Comment by kangarko** [comment]
Hey, actually I just reviewed the plugin, it's not currently possible to deny self-messaging.

**Comment by dabou0** [comment]
can you make and update, pls, so it would be able, bc if not may cause issues, and dont look professional :(
