### ISSUE TITLE
MOTD Json Format

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#535]
An option to use JSON format (click/hover) within the MOTD.

**Comment by kangarko** [comment]
Works for me, just prepend it with [JSON] like this:

![a](https://i.imgur.com/6Vr3mnN.png)

**Comment by Sikatsu** [comment]
How would I use one line in JSON and the others just as normal?

**Comment by kangarko** [comment]
No I don't think that's possible, although you can try:

```
Message:
  - |-
    [JSON]
    {...json...}
   - "Normal message"
```

**Comment by Sikatsu** [comment]
That didn't work. Even multiple JSON messages didn't work. Everything needs
to be on one line for some reason.

Op do 4 jan. 2018 12:36 schreef kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
Post that excerpt.

**Comment by kangarko** [comment]
Going to test it later.

**Comment by Sikatsu** [comment]
Hopefully it can be improved so that I can use multiple lines, not one. Thanks.

**Comment by Sikatsu** [comment]
Managed to get it in someway, not sure how efficient it is since the JSON is very long now.

http://prntscr.com/hw6wd3

**Comment by kangarko** [comment]
Added formatting support in MoTD:

settings.yml
![a](https://i.imgur.com/1aNECxv.png)

formatting.yml:
![b](https://i.imgur.com/0at3j8v.png)
