### ISSUE TITLE
[Bug] Chat random lose the format

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#536]
Sometimes when normal chatting (really rare cases) the chat format will go away and a error will appaer:

Console error: https://hastebin.com/goliguhola.vbs 
(paperspigot 1.8.8+viaversion)

Screenshot:
 
![index](https://user-images.githubusercontent.com/3611852/34120333-870256c8-e425-11e7-8d47-786dc20dabb0.jpg)

**Comment by LogGits** [comment]
:O!!!! i have seen this issue in 1.12.2. It appeared to fix after the player that wasn't added to the map rejoined.

**Comment by kangarko** [comment]
Seems like concurrency issue, I have made the player map synchronized to the next version. Please let me know if it happens again.

**Comment by xion87** [comment]
it happend again

**Comment by kangarko** [comment]
Please repost the error.

**Comment by xion87** [comment]
https://hastebin.com/ukuzexenoj.vbs

**Comment by kangarko** [comment]
You're on 7.6.26. Please update to 7.6.30 where it has been already patched.
