### ISSUE TITLE
Force apply

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#537]
As a suggestion for a new operator I would like to see an option to force apply a specific rule overriding any permission including `*` and/or OP  status.

This operator could be named `ignore op (rule will always apply and completely bypass any given permission or operator status)`

**Comment by x1p** [comment]
OP's bypass all rules already.
I'd rather see the opposite. Rules which cannot be bypassed by OP.

**Comment by EvilOlaf** [comment]
Misapprehension. This is what I suggested.

**Comment by x1p** [comment]
Ah. In that case: Nice!

**Comment by kangarko** [comment]
At present we do not plan changing our system, however, rules that apply for OPs or people with * permission are possible.

You just need to give them negative "-chatcontrol.bypass.rules.*" permission, and all rules will apply for them (except those further bypassed by their special bypass permission in handlers.yml). Then, simply use "ignore perm" or "require perm" operators for the specific rules.
