### ISSUE TITLE
AdvancedBan mute and tempmute commands incompatibility?

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl-Pro#538]
Hi. I suspect that ChatControl is causing a mute bypass with muted players.
Players with AdvancedBan's mute or tempmute being applied to them has no effect, players can still speak.
I suspect this only happens some times, since I've seen some muted players actually not being capable of speaking.
I'm not 100% this is CC's fault, but the AdvancedBan developers confirmed their mute feature is fine. Therefore, my main suspect is CC.

CC: 7.6.7
Spigot for MC 1.12.2

**Comment by Roy416** [comment]
try testing it out by disabling chatcontrol and checking if it still works

**Comment by kangarko** [comment]
Hey,

that's a priority issue. Please read and adjust accordingly: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
