### ISSUE TITLE
Question/possible bug

### ISSUE THREAD

**Issue by friishon** [kangarko/ChatControl-Pro#540]
Hi, i have kingdom + plugin but the placeholders doesn't work
I would like to show the rank icon and kingdom's player, but in the chat only appear the variable with % 

Can you fix or add something to show that in the chat?
Plugin: https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-12-2.11833/

Free version: https://www.spigotmc.org/resources/kingdoms-plugin-demo.6392/

Plugin has the same api, maybe you can test it with the free version, merry christmas and have a nice holidays

**Comment by kangarko** [comment]
Hello,

have you tried using PlaceholderAPI extension? You also must use {syntax}, not %syntax%. If that does not work, change the priority of Listener_Priority.Formatter to MONITOR.

**Comment by friishon** [comment]
thanks, i will test it later
