### ISSUE TITLE
[Script] Undefined variable when used in other script bodies

### ISSUE THREAD

**Issue by v3Monsta** [kangarko/ChatControl-Pro#545]
I wanted to create a custom variable and used the example provided by the javascript.txt file, however nothing seemed to work. Then I decided to enable the example to see if maybe I had done something wrong and sure enough an exception was thrown. Both Example 1 and 2 found in javascript.txt were enabled.

**Spigot Version:** git-Spigot-b66ad9e-b5a10a9 (MC: 1.12.2)
**ChatControlPro Version:** 7.6.26
**Exception:** https://hastebin.com/kuzozepasu.vbs

Edit: I was able to accomplish what I wanted to do by putting everything in a single script body, however it would be nice if this was fixed so I could reuse my code.

**Comment by kangarko** [comment]
Good notice, it has been disabled during the development process. I have enabled it again via a new Replace_Own_In_Custom option in Variables in settings.yml in the next version.
