### ISSUE TITLE
mcMMO party spying

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#546]
Mcmmo has an api that allows for such a feature to be easily implemented. The plugin has almost 3million downloads. That is more than towny and factions combined. Hence, it would be worth looking into. Mcmmo doesn't offer a means of spying on party messages. This feature would be a great addition to ChatControl Pro. Keep up the great work @kangarko 🙂

**Comment by kangarko** [comment]
Good suggestion. I am leaving it open to the future.

**Comment by Sikatsu** [comment]
Yes please! Awesome feature request.

**Comment by LogGits** [comment]
This is the event used for mcmmo party chat:
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/events/chat/McMMOPartyChatEvent.java
@kangarko you can also download mcmmo from the jenkins: https://popicraft.net/jenkins/job/mcMMO/

**Comment by LogGits** [comment]
Any news on this addition?

**Comment by kangarko** [comment]
Currently not. I have less time then expected due to moving lands. Next month the situation should be different.

**Comment by Sikatsu** [comment]
Hope this will be implemented soon.

**Comment by kangarko** [comment]
I am going through and implementing most of the suggested since 2016 these days.

If it won't be implemented then I will let you guys know, but it seems promising.

**Comment by kangarko** [comment]
Done!

**Comment by Sikatsu** [comment]
Is it a seperate command? For example I use social spy from essentials.

**Comment by kangarko** [comment]
It will require the /spy command to be enabled.
