### ISSUE TITLE
Double clear msgs

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#547]
typing /chc clear 1 time causes this:
https://gyazo.com/0d0e4e077dec9e207b1d06c33ab676ec

**Comment by kangarko** [comment]
That's what is should be like, anything after "clear" is considered as the reason unless it begins with a "-":

![a](https://i.imgur.com/7ch8qUs.png)

**Comment by kangarko** [comment]
My bad, I have identified the issue when more then one admin players are online. Will fix.
