### ISSUE TITLE
Feature request: catch

### ISSUE THREAD

**Issue by Mxra** [kangarko/ChatControl-Pro#548]
Similar to "ignore string", we could have a "catch string" and maybe even a "catch regex". This might improve a lot of redundancy with having two sections that catch an alias or common bypass.

Something similar to the following:
```
match memes
catch string meme|m3m3
handle as memer
```
```
match \b(m+(\W|\d|_)*e+(\W|\d|_)*m+(\W|\d|_)*e+(\W|\d|_)*s+(\W|\d|_)*)\b
catch regex \b(m+(\W|\d|_)*(e|3)+(\W|\d|_)*m+(\W|\d|_)*(e|3)+(\W|\d|_)*)\b
handle has memer
```

This might be especially useful for people who don't know REGEX yet still want an effective anti-swear.

**Comment by kangarko** [comment]
Hey, currently such addition would require the system to run in cycles (recursive), which with the current system could lead to race conditions. At present I do not play to rewrite it. Thank you for your understanding.
