### ISSUE TITLE
ProtocolLib problem

### ISSUE THREAD

**Issue by md79** [kangarko/ChatControl-Pro#55]
Could you restore compatibility with protocollib on version 1.7.10? Preventing tab complete is very important for me. http://pastebin.com/mYbnSerX

**Comment by EvilOlaf** [comment]
If you are using Spigot you can disable tab complete in your `spigot.yml`.

**Comment by md79** [comment]
I don't want to completely block. Anti tab in ChatControl works better because blocking tab only for specific commands.

**Comment by kangarko** [comment]
Please read the error message. Use a valid ProtocolLib version for that version.
