### ISSUE TITLE
Statistics on Rules' Usage

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#550]
Hey there,

I wonder if it would be possible to add something like a statistics feature which will count how often a specific rule has been matched within a given period of time and when the most recent match of any rule happened. For example to get an idea if there are rules which are completely useless as they never matched any message.

The required data could be stored within the MySQL database.

As always thanks for reading.

**Comment by kangarko** [comment]
Good suggestion! Leaving it open for the future.

**Comment by kangarko** [comment]
I am going through and implementing or delaying all suggestions since 2016.

This one will be delayed due to lack of time, but we provide API with the event PreRuleMatchEvent that can easily be caught by a developer and they can add their own statistics system easily.
