### ISSUE TITLE
[Bug] Login/Logout Message not showing anymore.

### ISSUE THREAD

**Issue by SilberRegen** [kangarko/ChatControl-Pro#551]
On Version 7.6.26 the custom Login/Logout-messages won't show anymore. Instead if set to true nothing will show in chat, when someone logs in. I tried it with the default-config with the same outcome.
There is no error message in the console.

**Comment by kangarko** [comment]
Hey, the default file messages.yml has messages disabled, so if you cannot see them also in that case, it is not coming from ChatControl.

**Comment by SilberRegen** [comment]
I sort of figured out, that it's probably due to an older spigot-build on my main-server, as it works fine on my test-server. 
Sorry to bother you :)

**Comment by kangarko** [comment]
No problem!
