### ISSUE TITLE
[Script] ECMAException after successful variable replacement

### ISSUE THREAD

**Issue by v3Monsta** [kangarko/ChatControl-Pro#552]
Hello again, new update fixes the issue of variables in other script bodies however I'm still seeing the same ECMAException in console despite successfully being able to talk in chat.

**ChatControlPro Version:** 7.6.27
**Related Issue:** [#545](https://github.com/kangarko/ChatControl-Pro/issues/545)

**Comment by kangarko** [comment]
Cannot reproduce. Repost the error just to be sure + post me your javascript.txt file.

![a](https://i.imgur.com/qKN6e3v.png)

**Comment by v3Monsta** [comment]
I'm unable to reproduce it now too.. Strange... If it happens again I will let you know.  This is my js file anyway.

```
#########################
## Permission provider ##
#########################
define $permission
script:
	var bukkit = Java.type("org.bukkit.Bukkit");
	var permission = Java.type("net.milkbowl.vault.permission.Permission").class;
	
	bukkit.getServicesManager().getRegistration(permission).getProvider();

#######################
## Staff chat format ##
#######################
define {staff_prefix}
script:
	supplyStaffChatFormat();
	
	function supplyStaffChatFormat() {
		if ($permission.playerInGroup(player, "administrator")) return "&8«&4Admin&8»";
		if ($permission.playerInGroup(player, "moderator")) return "&8«&1Mod&8»";
			
		// Return an empty string if the player isn't staff
		return "";
	}
```

**Comment by kangarko** [comment]
Okay, closing in faith that it has been resolved. Lmk when it comes again please.

**Comment by v3Monsta** [comment]
Logs:
[javascript.txt](https://github.com/kangarko/ChatControl-Pro/files/3049836/javascript.txt)
[error.log](https://github.com/kangarko/ChatControl-Pro/files/3049837/error.log)
