### ISSUE TITLE
Partial name matching

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#556]
This is a feature that is really useful and also very simple to implement. It would work in this way:
Two users are online: User1 and User2.

With this feature implemented User1 could type /msg ser2 <msg> and it would send the message to User2. This feature would only need to search online players (its upto you if you decide to introduce this with bungee support). This feature would not be used with tab complete as it just requires them to type the string and it would compare it with all online players and send the message to the first match.

**Comment by kangarko** [comment]
Thanks, will strongly consider.

**Comment by kangarko** [comment]
Update: Just checked. We already rely on Bukkit's method for partial matching. If you type /msg sial for SialLP it will match. Not if you type /msg lLP though. I don't know how to write a better and at the same time fast enough algorithm, sorry.

**Comment by LogGits** [comment]
You are only going to be checking this everytime the user types /msg. Which is assumed to be one time followed by /r. I don't see anything wrong with using a for loop iterating through Bukkit.getOnlinePlayers and doing string.contains matches on usernames (breaking when finding a match) for such a feature. In terms of performance Contains method should suffice. 
While testing with this configuration:
```protected static Player partialMatch(String s)
    {
        for(Player p : Bukkit.getOnlinePlayers())
            if(p.getName().contains(s)) return p;
        return null;
    }```
And this try setup:
```
long startTime = System.nanoTime();
try {
Player search = methods.partialMatch(name);
long endTime = System.nanoTime();
Bukkit.broadcastMessage("Completed in " + Long.toString((endTime - startTime) / 1000000) + "ms : ");
Bukkit.broadcastMessage(Long.toString((endTime - startTime)));
}catch(NullPointerException e)
{
long endTime = System.nanoTime();
Bukkit.broadcastMessage("Completed in " + Long.toString((endTime - startTime) / 1000000) + "ms o ");
Bukkit.broadcastMessage(Long.toString((endTime - startTime)));
}
```
I found the timings to be relatively low. Not to mention you could easily utilise caching to also help with performance. Keep up the great work I love the plugin!

**Comment by kangarko** [comment]
Thanks for it, but it will cause ambiguity problems when the match is too short or two+ players have the same name partial match. 

I was talking about that I am relying on Bukkit's method to intelligently find the best match (this is in ChatControl already):

![a](https://i.imgur.com/YneSOqP.png)

Performance in the method is not a problem, but perhaps adding a percentage check and pull the value with most percent would add on (I dont know, probably not that much). Let me know if you wish to add this.

**Comment by LogGits** [comment]
> Thanks for it, but it will cause ambiguity problems when the match is too short or two+ players have the same name partial match.

Yes but this is a known thing with partial name matching it is not 100% accurate. There is no way to get the exact player if there are more than 2 players using the same name. However, with the method I provided it would simply iterate through online players **(ordered alphabetically)** stopping at a partial match. Which is how it should be. There is no need for percentage checks it would add an unnecessary amount of checks. Also ensure the text is .toLowerCase().
Something like:
```
protected static Player partialMatch(String s)
    {
        for(Player p : Bukkit.getOnlinePlayers()) //Maybe sort the getOnlinePlayers() Alphabetically to make it consistent
            if(p.getName().toLowerCase().contains(s)) return p;
        return null;
    }
```
Also do some testing with this feature to ensure it is working as intended.

**Comment by kangarko** [comment]
I implemented a percentage comparation where the value with highest match will return.

Example: "ous" matches "house".

Diacritic is ignored, so "stuka" matches "šťuka" as well.
