### ISSUE TITLE
Factions relation placeholders support

### ISSUE THREAD

**Issue by baticag** [kangarko/ChatControl-Pro#557]
Can you add option for Factions (from MCore) to parse chat tags or something similar so relations between factions players can be shown in chat?

Tried PlaceholderAPI's rel placeholders and they aren't working!

Thank you in advance!

**Comment by baticag** [comment]
Not necessary if you implement #558

**Comment by kangarko** [comment]
ChatControl has relation placeholder support via PlaceholderAPI. If they do not work, please contact the author of PlaceholderAPI of the relevant extension for support. We only pass through the functionality.
