### ISSUE TITLE
AsyncPlayerChatEvent setFormat support

### ISSUE THREAD

**Issue by baticag** [kangarko/ChatControl-Pro#558]
Many plugins use AsyncPlayerChatEvent to listen to it and then they replace their placeholders or add something new to format. EssentialsChat has this.

This is used by many popular plugins (like Factions for example) and is a must feature of this chat plugin if you ask me.

Can you please add this?

Thank you very much!

**Comment by ipr0james** [comment]
Factions relational placeholders are already supported? Using PlaceholderAPI atleast which is the easiest way. Only issues I've had with them came from LegacyFactions.

**Comment by kangarko** [comment]
Hey, change ChatControl's listener priority of formatter so your plugin replaces the message before we do. Tutorial: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
