### ISSUE TITLE
Whitelist_Works_Like_Blacklist true don't work

### ISSUE THREAD

**Issue by Slaand** [kangarko/ChatControl-Pro#559]
I dont know how, but yes. Commands which are not in list, they're still throw similarity error.
Config part:

> Anti_Spam:
>   Similarity_Check:
>     Ignore_Special_Characters: false
>     Ignore_Duplicate_Characters: false
>   Regex_In_Whitelists: false
>   Commands:
>     Command_Delay: 2
>     Delay_Points:
>       Warn_Set: fastmessages
>       Amount: 3 - {delay}
>     Similar_Percentage_Block: 80
>     Similarity_Points:
>       Warn_Set: spam
>       Amount: 4 * ({similarityPercentage} / 2)
>     Whitelist_Works_Like_Blacklist: true
>     Whitelist_Similarity:
>     - /mail
>     - /msg
>     - /m
>     - /whisper
>     - /w
>     - /t
>     - /tell
>     - /reply
>     - /r
>     Whitelist_Delay:
>     - /sell
>     - /menu
>     Handle_As_Chat:
>     - /me
>     - /say
>   Chat:
>     Message_Delay: 1
>     Delay_Points:
>       Warn_Set: fastmessages
>       Amount: 3 - {delay}
>     Similar_Percentage_Block: 80
>     Similarity_Message_Check_Count: 2
>     Similarity_Points:
>       Warn_Set: spam
>       Amount: 4 * ({similarityPercentage} / 2)
>     Whitelist_Similarity:
>     - ddss
>     Whitelist_Delay:
>     - ddzz

**Comment by kangarko** [comment]
All works for me, make sure you actually restarted and not just reloaded:

![a](https://i.imgur.com/YRUk7OE.png)

**Comment by kangarko** [comment]
Closing in faith it has been fixed.
