### ISSUE TITLE
Get error with SignChangeEvent

### ISSUE THREAD

**Issue by JavituRec** [kangarko/ChatControl-Pro#568]
Error:

https://hastebin.com/ocipezozup.vbs

Server version 1.8.8 and last version of chantcontrolpro.

**Comment by kangarko** [comment]
Hey,

I am sorry, but I cannot reproduce the problem. Please upload me your formatting.yml.

**Comment by JavituRec** [comment]
Sure

https://hastebin.com/uqisugaqik.php

Sincerely.

**Comment by kangarko** [comment]
Thanks, fixed.
