### ISSUE TITLE
No clear configuration for Bungeeperm Prefixes

### ISSUE THREAD

**Issue by gaRt3n** [kangarko/ChatControl-Pro#57]
As above. I can't find any clue to get the prefixes from BungeePerms working.

**Comment by kangarko** [comment]
If Vault support them, you can use {pl_prefix} and {pl_suffix} variable. If not, you can try using PlaceholderAPI and see if it supports them, or you can create a custom variable. But I am afraid, since it's a bungee plugin, that it is not that simple to get to know the prefix on the server itself.

**Comment by kangarko** [comment]
Please remind me you wonder on anything
