### ISSUE TITLE
Replaced message containing nothing

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#570]
When a swear is replaced by "" or "none" leaves nothing to show, a empty message is displayed. I tried to make a chat rule to deny if the message contains nothing but this does not work.

Example:
player types in "bitch"
message is "bitch"
handler replaces bitch --> ""
Message is: "[Rank] Player: "

How can make an empty message disappear?

**Comment by kangarko** [comment]
At present I do not plan to change the replace system. You can use insert a [BLOCKED] or **** replacement there.
