### ISSUE TITLE
Anvil question default settings.yml

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#571]
The default settings.yml speaks about anvil behavior:
    # Replace item name if a rule changes it? If false, denies creation.
    Replace: true
I assume this has to be true to be canceled. But according to the description it must be set to false to be denied?
Could you please clarify?

**Comment by kangarko** [comment]
I am sorry, some things inside ChatControl are older and my English is not the best. Please let me know if you find anything more.

Corrected description:
![a](https://i.imgur.com/x4rxQl5.png)
