### ISSUE TITLE
Center Messages (MoTD, etc..)

### ISSUE THREAD

**Issue by BigMinnie** [kangarko/ChatControl-Pro#574]
Can we get option to center the message in similar way plugin [RAWMSG](https://www.spigotmc.org/resources/rawmsg.35864/) is doing?

**Comment by kangarko** [comment]
Where/how would you like to center it?

**Comment by BigMinnie** [comment]
In chat, for instance motd. Making spaces before and after message will not work, if you want to use any placeholder as {player}.

**Comment by kangarko** [comment]
I see, I am leaving this open for future implementation.

**Comment by kangarko** [comment]
Added.

Use <center> in a beginning of a line in MoTD to center it in the next version:

![a](https://i.imgur.com/nRhLYmo.png)

**Comment by Sikatsu** [comment]
How do you center JSON?

**Comment by kangarko** [comment]
It's unfortunately not possible to center JSON due to how the formatting is split and sent in the packets internally.
