### ISSUE TITLE
Bungie Join and Leave Messages

### ISSUE THREAD

**Issue by Xgoldenman16X** [kangarko/ChatControl-Pro#575]
Hi! 

I currently can't get cross server join and leave messages working? I have modified the bungie bridge plugin and made sure everything is enabled. Am I missing something? Any help would be amazing!

Thanks!

**Comment by kangarko** [comment]
Hey,

I am sorry, at present ChatControl does not provide cross-server player-related messages.

However, BungeeControlBridge does have such feature. Set messages.enabled to true in that plugin's config.yml and configure it from there.
