### ISSUE TITLE
Primary group variable

### ISSUE THREAD

**Issue by TheBrianiac** [kangarko/ChatControl-Pro#576]
The [wiki page](https://github.com/kangarko/ChatControl-Pro/wiki/Variables) for variables does not indicate that a variable for a user's primary group exists.

I would like to see this feature. It is possible through Vault: `Permission#getPrimaryGroup(Player player)`

**Comment by kangarko** [comment]
Hey, for the time being the only variable is {pl_prefix} that will retrieve player's main prefix as Vault sees it. You can enable Multi_Prefix option for multiple prefixes from each group, but not explicitly for the primary one. 

Lastly, please check if PlaceholderAPI includes that variable so I save time adding something that already is supported by a plugin we has support for. Thanks.

**Comment by kangarko** [comment]
{pl_primary_group} variable added.
