### ISSUE TITLE
1.13 Features for ChatControl Pro

### ISSUE THREAD

**Issue by Pluginsel** [kangarko/ChatControl-Pro#578]
1) New death messages:

Added a death message for when the player is blown up by a bed in the nether or end.
"Player was killed by [Intentional Game Design]"
Clicking on "[Intentional Game Design]" opens a link to MCPE-28723.
Added a death message for when a mob or player causes another player to die in the void.
"Player didn't want to live in the same world as Player/Mob"

2) New command system:
Ability to change command colors for the syntax. Related to #497

1.13 isn't out yet and this issue is will maybe updated again.

**Comment by kangarko** [comment]
Thanks for pointing that out. Death messages support JSON the hard way (you have to prepend a message with [JSON] and include the raw JSON code after it). I will keep an eye on the command system.

**Comment by Pluginsel** [comment]
@kangarko 1.13 is will merged with 1.14 verion (LOL)
I think this is will the big issue...

**Comment by kangarko** [comment]
I will check the API but won't use it because it breaks backwards compatibility. No command labels for now, sorry.
