### ISSUE TITLE
SocialSpy doesn't work well with /r

### ISSUE THREAD

**Issue by oflords** [kangarko/ChatControl-Pro#579]
When you use the social spy, it can get really annoying to figure out who the person using /r is talking to. Example: https://gyazo.com/65919d7574476329054a8513eaf6c665

**Comment by kangarko** [comment]
Hey, sorry this is not something we can send to your HeroSpy plugin.

**Comment by oflords** [comment]
HeroSpy is the SocialSpy built into chatcontrol... It's not my plugin

**Comment by kangarko** [comment]
Oh I see!

Well, unfortunately ChatControl's social spy doesn't see the recipient now, but I have added this on the roadmap.
