### ISSUE TITLE
Suggestion: Make one command for switching and sending to channels

### ISSUE THREAD

**Issue by Roy416** [kangarko/ChatControl-Pro#581]
The suggestion I have is to make one command for "/ch switch channel" and "/ch send channel". Just so it's easy and more intuitive for players. Or at least make an option for both of them to be combined. For example if only /ch standard is typed, then it would switch to the standard channel, but if it's '/ch standard iamtypinghere', then it would say something in that channel without you having to switch channels. 
Similar to the standard Admin Chat.

**Comment by Roy416** [comment]
You left me a message on Spigot, I'll try it and see if i can get it to work

**Comment by Roy416** [comment]
So you said this : "Yes, you can combine commands and make your own ones, just read this quick article over here: https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands (you can add multiple commands for each "- " line."

https://pastebin.com/52HG699T

So I did what you suggested but that doesn't work for when I do "/tc  text , since both commands are run it also sets the channel as town. Instead of only sending the text to the channel.

**Comment by kangarko** [comment]
I see. For the time being I am not planning to change the current system, but what you can do is that you give players `chatcontrol.channel.autojoin.town.spy` permission to the town channel so they see all messages in there, and you remove the /ch switch command from commands.yml file so /tc only run one command, /ch send.
