### ISSUE TITLE
[Suggestion] Disable death messages per region

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#582]
It would be awesome if one could disable death messages per region. You could hook into worldguard or add own region coordinates to ChatControl. 
I would love to see this feature because I have some Minigames/Adventuremaps were player can and need to die quiet often. Obviosly its very annoying if they spam the Chat with death messages. 
Alternativly you could add region support for channels, so that if a player enters or leaves a region he would join and leave a channel automatically. This would be awesome not only to prevent death-messages spam but also for some events. 
I appreciate your hard work and any help you can provide :)

**Comment by kangarko** [comment]
Hey, I am very sorry I don't plan this feature right now due to lack of time, but you can move your minigames over to a different world where you give players negative '-chatcontrol.messages.death' permissions so they don't make the message.
