### ISSUE TITLE
SuperGuilds Chat

### ISSUE THREAD

**Issue by NeedHelperino1** [kangarko/ChatControl-Pro#585]
Hello, I can't get the plugins "SuperGuild" chat toggle to work. It will send the message to general chat AND guild chat. I've talked with the plugin developer of SGuilds and he told me "event cancelable is not working with your plugin".  This is my channels.yml file -> https://pastebin.com/JdLHw4w7
Trying to kill 2 birds with 1 stone, how do I totally disable the swear detector/sensor in your plugin?

**Comment by kangarko** [comment]
Hello!

For the first issue, there is not much we can do, but you can try changing the priority of formatter as per https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities to LOWEST, HIGHEST or MONITOR.

About the second one; you can simply remove all filters for swears you don't need in your rules/rules.txt file.
