### ISSUE TITLE
ChatControl PRO | Questions

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#588]
Hi, I would like to Purchase ChatControl PRO. Before purchasing, I have two questions:

I would like to add Global Chat on my Bungeecord Server. If I install this plugin on my Spigot Servers, I Need to configure MySQL with this plugin?

How do I add Global Chat with / g instead of / chc g?

Thanks a lot!

**Comment by kangarko** [comment]
Hello,

thank you for your interest!

1) You can use global chat with /chatcontrol global command or using the Channel system. That does not require MySQL.

2) It's very simple, here's a tutorial: https://github.com/kangarko/ChatControl-Pro/wiki/Shortening-Commands
