### ISSUE TITLE
Please help ignore Craftbook [Pipe] signs

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#589]
ChatControl Pro blocked [Pipe] signs because advertisement. Please help how to ignore this.
[30.01.2018 13:12:04] yghrt: [Handler=advertisement, Rule ID=1] [Pipe]
[30.01.2018 13:12:04] yghrt: 14,15,12,12:1

**Comment by kangarko** [comment]
Hello,

you can add [Pipe] to the "ignore string" operator in that rule in rules/rules.txt. It's the first one on the top of the file:

`ignore string \[Pipe\]`

**Comment by andris155** [comment]
This is not work. :/
