### ISSUE TITLE
Make the plugin compatible with FactionsUUID

### ISSUE THREAD

**Issue by Kira07** [kangarko/ChatControl-Pro#59]
Can you make ChatControl compatible with FactionsUUID ? (it's opensource).
I already asked the dev and he said that he would have to do a major recode for it to work, maybe it would be easier on your side.
A lot of people use FactionsUUID, I hope that you'll do something.

**Comment by kangarko** [comment]
What's not compatible?

**Comment by Kira07** [comment]
The chatcontrol filter doesn't apply to the factionchat, players can swear and advertise in their faction/alliance chat

**Comment by kangarko** [comment]
This seems like an issue with event priorities. Have you adjusted them according to ChatControl's Wiki?

**Comment by Kira07** [comment]
I tried to set the priority to high and to low, it seems uncompatible with the built in factionchat of FactionsUUID for some reasons (it's the same faction chat than the old versions of Factions)

**Comment by kangarko** [comment]
Have you tried HIGHEST and MONITOR priorities?

**Comment by Kira07** [comment]
Just tried, still doesn't work

**Comment by kangarko** [comment]
I will be working on this in the 7.0.0 release. Added to to-do list.
