### ISSUE TITLE
Incompatibility with Youtuberbridge URLS

### ISSUE THREAD

**Issue by JavituRec** [kangarko/ChatControl-Pro#590]
Hello,

I am using the plugin https://www.spigotmc.org/resources/youtube-bridge.35928/ that allows you to assign a range of youtuber to a user through the verification of your URL. The problem is that when a user hits their URL in the chat the points are deleted.

Any solution?

Sincerely.

**Comment by kangarko** [comment]
Hello,

please see https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#ad-filter-doesnt-work-all-dots-are-removed-example-wwwgooglecom-becomes-www-google-com
