### ISSUE TITLE
Formatting and Aliases

### ISSUE THREAD

**Issue by WittleRain** [kangarko/ChatControl-Pro#593]
I'm not finding a way to format the Announcements and i was wondering if theres a way to add command aliases for staff chat so i could do something like /s <text> or /a <text> instead of /cc ach <text>. Its not anything minor thats all.

**Comment by BloodshotPico** [comment]
I think I found the solution for your alias problem. 
Here you are:
https://github.com/kangarko/chatcontrol-pro/wiki/Shortening-Commands

**Comment by kangarko** [comment]
Thanks to @BloodshotPico for helping out! Yes, please see that page.

And for the announcements, see https://github.com/kangarko/ChatControl-Pro/wiki/Localization
