### ISSUE TITLE
ChatContol Pro | Payment Method

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#594]
Hi, thank you very much for the informations.
I have a last question: Can I pay ChatControl with Paysafecard?

Best Regards.

**Comment by kangarko** [comment]
Hello,

Unfortunately PaySafe only allows the codes to be applied from the same country as you are from. Where are you from?

I recommend you pay either with a credit card, or by sending money on an IBAN bank account, or by cash at your post office and they will send it to the IBAN bank account.

**Comment by FedericoGB25** [comment]
Hi! Thank you for reply. I come from Italy.

**Comment by kangarko** [comment]
Responded via PM.
