### ISSUE TITLE
Advanced Bans Support?

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#595]
Is there any way for this plugin to have support or be supported by the Advanced Bans plugin?

https://www.spigotmc.org/resources/advancedban.8695/

It seems when someone is temp-muted from advanced bans it doesn't carry over to Chat Control and they're still accessing chat with their messages showing still.

~ Blood

**Comment by kangarko** [comment]
Hello,

please see https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

Thank you.
