### ISSUE TITLE
Question about: "Ignore string"

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#596]
Is it possible to have multiple ignore strings?

example:
match ...
ignore string testing
ignore event book
ignore event signs
handle as ...

**Comment by kangarko** [comment]
Hello,

you can only have one operator of the same kind, per rule.

However, due to the nature of regex filters you can achieve this with "|" like so:

```
match ..
ignore string testing|testing2
```

Currently, you may ignore as many words as you wish, but you can only ignore one event in a rule.
