### ISSUE TITLE
Glitch/Bug ChatControl PRO - BungeeControlBridge

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#599]
Rarely people can see the spy chat from other servers when they DO NOT have any permissions to do so..

**Comment by kangarko** [comment]
Is there a way I can reproduce the bug so it's easier to test it out?

**Comment by AmazedMender16** [comment]
I believe its happening after i reloaded chatcontrol when i make a change to a config. Like a swearing rule, but sometimes really rare aswell hapening without any reloads. I have never had this issue before with 7.5.x

**Comment by kangarko** [comment]
I just pushed a new big update 7.7.0, please try testing it and see if it was fixed :)

**Comment by AmazedMender16** [comment]
The bridge doesnt need an update?? I will try it out and let you know!

**Comment by kangarko** [comment]
Closing in faith it has been resolved, if not please provide clear steps on how to reproduce, when does it likely to happen etc.
