### ISSUE TITLE
Rules not Applied on signs

### ISSUE THREAD

**Issue by maginka** [kangarko/ChatControl-Pro#6]
I have version 6.8.2 of Chatcontrol pro running on the very latest version of spigot on Java 8. 

Rules on signs is enabled in settings.yml

  Signs:
    Check: true
    Both_Directions: true

When a user writes a word that is in the rules.txt, they get a message saying swearing is not allowed, and staff receive the alert about what was written. 

However,  the word is still allowed to be placed on a sign, and not cancelled. No errors seen in the console. This applies to any word that is in the rules.txt.
 
Words are blocked if typed directly in chat as normal.

**Comment by kangarko** [comment]
Sorry I forget to answer here.

The bug has been resolved.
