### ISSUE TITLE
Sorry, but I have a problem with CC.

### ISSUE THREAD

**Issue by imyeah** [kangarko/ChatControl-Pro#60]
`[08:14:24 INFO]: ChatControl *----------------------------------------------*
[08:14:24 INFO]: ChatControl  ChatControl PRO requires
[08:14:24 INFO]: ChatControl  an internet connection.
[08:14:24 INFO]: ChatControl  Error: SocketException: Unexpected end of file from server
[08:14:24 INFO]: ChatControl  Plugin is now disabled.
[08:14:24 INFO]: ChatControl *----------------------------------------------*
`
I'm in China, and how to solve this problem?

**Comment by kangarko** [comment]
ChatControl needs a working internet connection. Check your host file or your firewall, whether one of these are blocking the server or its plugins to connect to the internet.

**Comment by EvilOlaf** [comment]
`ChatControl needs a working internet connection.`
Just a side question: Why?

**Comment by kangarko** [comment]
It checks for updates and anti-piracy.

**Comment by imyeah** [comment]
The reason why i said i'm in China is that there is a Great Firewall in China...
Great Firewall leads to users in China can not access websites like Dropbox, Google, Youtube, Facebook and many other website or services, maybe the URL used by CC for checking updates and anti-piracy is in the blacklist of Great Firewall.

**Comment by imyeah** [comment]
Other plugins like Authme, Residence are not plagued by this problem.

**Comment by kangarko** [comment]
I see. Can you access http://chatcontrol.6f.sk/ in your browser? If it says 403 and page displays, then it's loaded normally.

**Comment by imyeah** [comment]
Chrome page says:`chatcontrol.6f.sk 网页无法正常运作

chatcontrol.6f.sk 未发送任何数据。
ERR_EMPTY_RESPONSE`

**Comment by imyeah** [comment]
It means that i can not access this website.

**Comment by kangarko** [comment]
I understand. I shall fix this tonight in the next version.

**Comment by imyeah** [comment]
Thanks!
And sorry for the PM in spigotmc.org

**Comment by imyeah** [comment]
Hi, please tell me when you fix this.

**Comment by EvilOlaf** [comment]
Just have a look at spigotmc and check frequently for a new versions ;)

**Comment by imyeah** [comment]
I just don't know how long I have to wait.

**Comment by kangarko** [comment]
Closing. It'll be fixed in 6.10.0 when it comes out tonight.
