### ISSUE TITLE
Global chat | Problem

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#601]
Hi, I just bought ChatControl (Great and with lots of features)

I have 2 problems:

1: How can I implement Global Chat? (I have enabled the Bungeecord support, connected the plugin to MySQL and added all the required permissions)

2: How can I change Bukkit's "Insufficient permissions" message?

Thanks ^^
Regards

**Comment by kangarko** [comment]
Hello,

1) You can implement global chat either via a) chat channels (see channels.yml file), or via b) global chat that is /chatcontrol global, or /chc g, and that can you enable by default in your settings.yml -> Bungee_Chat.Enabled_By_Default

2) You can change that via packet rules, see rules/packets.txt

Have a great day/evening!
