### ISSUE TITLE
Party Chat

### ISSUE THREAD

**Issue by BloodshotPico** [kangarko/ChatControl-Pro#602]
So I've been looking around on the github about this issue and well i don't really understand it at all it's pretty confusing, although once I know how to do I'm probably going to punch myself.

Anyhow I was wanting to have all the features from normal chat, being JSON support and custom prefixes/colours within the FactionsUUID /f chat and well from what I understand it has something to do with Party chat or something?

I'm not really sure on how someone would set this up so I was wondering if someone would be able to help at all. ^^'

~Blood

**Comment by kangarko** [comment]
Hello,

I am sorry that you didn't receive support in time. ChatControl supports party chat only when using channels (see channels.yml file). The party mode can be enabled per each channel individually. When a player types a message to such channel, it will only be sent to other players in the same party, let it be factions, towny, etc. 

More information at: https://github.com/kangarko/ChatControl-Pro/wiki/Channels#party

An example of a normal channel and a party channel. I would advise you to create new format for those two to distinguish between them (in formatting.yml).

![a](https://i.imgur.com/K9jq3Wc.png)

**Comment by BloodshotPico** [comment]
Ah okay thanks for the info I'll try looking into it. :)

If I need help with the formatting, in setting it up I'll ask here after I look around the documentation.

**Comment by skyybender** [comment]
Is there any chance to create a own party-plugin and register it for the party-channel function or do you only support the plugins you listed in your wiki?

**Comment by kangarko** [comment]
@skyybender you can listen for our ChatChannelEvent and then use getChannel to get your channel and modify getRecipients appropriately.
