### ISSUE TITLE
Roll up files in logs/

### ISSUE THREAD

**Issue by astirling** [kangarko/ChatControl-Pro#603]
I would love to see the chat logs in the ChatControl/logs directory tree be rolled up daily (or defined interval).  

Currently the logs just keep growing and the most efficient way to clean them up is to delete them entirely.  I'd love to see a feature where they are saved off with a date/time stamp at intervals for easier reference, maintenance, and clean up.

**Comment by kangarko** [comment]
Good suggestion!

**Comment by kangarko** [comment]
Added to https://github.com/kangarko/ChatControl-Pro/issues/64
