### ISSUE TITLE
Global Chat | Formatting

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#604]
Hi! I have just added Global Chat on my server. But I have a problem with Chat formatting.

How can I remove the **[Bungee/Unknown Server]** from Global Chat formatting?
Regards ^^

![joffp8uvqyupxys5d-zk9a](https://user-images.githubusercontent.com/36126611/36345881-bd842e40-1433-11e8-8334-55c0499d7aee.png)

**Comment by FedericoGB25** [comment]
Hi, I have another problem.
By changing the various formats in the formatting.yml these are not applied (The plugin has the same with...

**Comment by FedericoGB25** [comment]
![rxwybwpkqxkqb3h2nznpvw](https://user-images.githubusercontent.com/36126611/36508650-905c5fe6-175d-11e8-8816-c8f35fade706.png)

My formatting.yml file (In all Servers)
https://pastebin.com/wwteYSqg

**Comment by kangarko** [comment]
Hello,

you can remove [Bungee/Unknown Server] by setting BungeeCords.Prefix to "" in settings.yml:
![a](https://i.imgur.com/LetZzsL.png)

For the other issue, try shutting the server down, placing the file there and starting it again. I cannot explain otherwise why the format wouldn't get changed.

**Comment by kangarko** [comment]
Closing, assuming fixed.
