### ISSUE TITLE
Cached Prefix / Suffix??

### ISSUE THREAD

**Issue by silencshadow** [kangarko/ChatControl-Pro#606]
Hello,

in the chat i used NameManager but it killed my prefix and suffix from LuckPerm... it shows the prefix and suffix of NameManager and now even after deinstallation NameManager stays the same???

**Comment by kangarko** [comment]
Hello,

please install Vault and use {pl_prefix} and {pl_suffix} variables in your formatting.yml to display prefix/suffix from that permission plugin.
