### ISSUE TITLE
Mathematical division in a received message? Is it posibble?

### ISSUE THREAD

**Issue by download042** [kangarko/ChatControl-Pro#607]
Hey!

I have a question.
If a player uses the /vote command, then receives a message like:
"You have currently 6 votes."

I would like to divide the received number with 2.

So if a player has for eg. 6 votes, then he receives:
"You have currently 3 votes." not "You have currently 6 votes."

Is it posibble to make this somehow? I see, chc has a builtin calc command, so he can count :D 

(I have ChatControl PRO.)

Thank you in advance for your answer!

Regards

**Comment by kangarko** [comment]
Hello,

I am very sorry but that's impossible in the way you wish it, as we use regular expressions for rules and they don't support this.
