### ISSUE TITLE
Suggestion: Separate MOTD config file

### ISSUE THREAD

**Issue by bc-hill** [kangarko/ChatControl-Pro#608]
MOTD is something that is updated often enough, that I think it should get it's own yml.  
Currently, MOTD is buried on line #630 of the main settings file.
Thank you!

**Comment by kangarko** [comment]
Hello,

at this point I don't plan to create more files in ChatControl/ folder, but I appreciate your suggestion. I will rather try to remove redundant and unused features from settings.yml so that file gets easier to read and understand.
