### ISSUE TITLE
Help with formatting user names

### ISSUE THREAD

**Issue by tccummings** [kangarko/ChatControl-Pro#61]
Ok so I am a little confused with the config, so I just figured I would ask for the answer.  I love everything this plugin does so far....except the usernames in chat.  The way I want it formatted is:

[GroupName] Playername: message 
And I want it to pull the group colors from GroupManager (it already pulls the username color from GroupManager...at least the colors stayed the same)

For example:

[Owner] KingHobey: message
 (red text) (red text) (white text) in my group manager
So I did figure out how to turn the message into white text in the chat.yml file.  But I wasn't sure how to get it to display the group name and colors as its pulled from GroupManager.  So would the group name go into the Prefix area with the {pl_prefix}?  I started out mimicking the default for A-Chat but then the Bracket Start: and Bracket End: part threw me off.

Thanks in advance for the help!

I do have essentials installed, but no other formatting plugin.  And chat control is superseding essentials because it changed the formatting to chat control's default

**Comment by EvilOlaf** [comment]
Essentials itself does not format the chat AFAIK. EssentialsChat does this. 
Anyway, I'm not sure if there is a variable to grab the users group from Vault. However using a prefix should be the simplest solution here as you can preformat those in your permission management plugin, E. G. Groupmanager

**Comment by tccummings** [comment]
Right,  I understand that. Group manager has the color in it and that has been pulled into Chat Control. But I haven't figured out how to make the groups get pulled in as the prefix.

**Comment by kangarko** [comment]
The next version will include {pl_group} variable, which might be the one that'll help you.
