### ISSUE TITLE
Could not pass event PlayerLoginEvent to ChatControl v7.7.3

### ISSUE THREAD

**Issue by StrangerFive** [kangarko/ChatControl-Pro#612]
Isn't this the same issue supposedly fixed with #611 ???

> 01.03 00:36:52 [Server] INFO UUID of player SuperAwesomePunk is 6f1bb701-effb-4bd4-92e2-cb55d0435048
01.03 00:36:53 [Server] ERROR Could not pass event PlayerLoginEvent to ChatControl v7.7.3
01.03 00:36:53 [Server] INFO org.bukkit.event.EventException: null
01.03 00:36:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:531) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:133) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
01.03 00:36:53 [Server] INFO Caused by: java.lang.NullPointerException: uuid
01.03 00:36:53 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_152]
01.03 00:36:53 [Server] INFO at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.hasPermission(VaultPermissionHook.java:120) ~[LuckPerms-Bukkit-4.1.5.jar:?]
01.03 00:36:53 [Server] INFO at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:132) ~[LuckPerms-Bukkit-4.1.5.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .lPT7.const(SourceFile:1065) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .lPt6.const(SourceFile:447) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .LPT8.const(SourceFile:400) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.super.native(SourceFile:204) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.super.native(SourceFile:113) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.ChatControl.const(SourceFile:499) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.ChatControl.const(SourceFile:485) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .throw.setPlayer(SourceFile:134) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .throw.joinPlayer(SourceFile:109) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.super.const(SourceFile:189) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .J.const(SourceFile:158) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.super.native(SourceFile:184) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.super.strictfp(SourceFile:131) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.super.const(SourceFile:104) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.ChatControl.const(SourceFile:497) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.ChatControl.const(SourceFile:485) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at me.kangarko.chatcontrol.final. .aJ.onPreLogin(SourceFile:66) ~[ChatControl-7.7.3.jar:?]
01.03 00:36:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
01.03 00:36:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
01.03 00:36:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
01.03 00:36:53 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
01.03 00:36:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
01.03 00:36:53 [Server] INFO ... 13 more
01.03 00:36:53 [Connect] User SuperAwesomePunk, IP 98.189.49.146
01.03 00:36:53 [Multicraft] SuperAwesomePunk ran command Message of the Day

**Comment by StrangerFive** [comment]
Did some tests and determined this issue, as well as #609 and #611, are all related to recent changes in LuckPerms 4.1.1+.  Backing down LP to 4.0.74 makes the issue go away. Per kangarko's request, I pushed the bug over to LuckPerms here: https://github.com/lucko/LuckPerms/issues/806

Can @kangarko and @lucko put their heads together and resolve this please?

**Comment by StrangerFive** [comment]
@lucko fixed this in LuckPerms 4.1.13.  Refer to https://github.com/lucko/LuckPerms/issues/806
You can close this.

**Comment by kangarko** [comment]
Good to hear! We use OfflinePlayer for the pre-login check for anti-bot, where the player himself isn't technically online yet.
