### ISSUE TITLE
Kingdoms+ Compatibility

### ISSUE THREAD

**Issue by JonCris** [kangarko/ChatControl-Pro#613]
Are there any plans to add compatibility with [Kingdoms+](https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-12-2.11833/)

If there are not, would you consider it?
Thanks, I really love chat control but would also love to use it in my Kingdoms Server.

**Comment by kangarko** [comment]
In what way should it be compatible?

**Comment by JonCris** [comment]
The same way it has compatibility with Factions, Towny, Feudal, etc
For kingdoms chat channels, Kingdom Chat, Allied Chat, etc

**Comment by kangarko** [comment]
Sorry I just checked that plugin and it doesn't provide sufficient API.

**Comment by kangarko** [comment]
@JonCris you can rather try changing priorities of Formatter to HIGHEST or MONITOR and use the chat from Kingdoms. Tutorial: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities
