### ISSUE TITLE
Handler Rewrite_To enhancement

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#614]
I've made Rewrite_To: message that contains a serverprefix and a message part.
The server prefix contains [Capitalized Server name] and then the message.
This message is de-capitalized in a unwanted way. So I have stated it on the whitelist to leave it as it is. No matter what I try, it is de-capitalized. I've tried to whitelist:
`- ABC`
`- [ABC]`
`- '\[ABC\]'` 
How can I make ChatControl to leave the message as it is rewrited by the handler?

**Comment by kangarko** [comment]
Sorry, I don't understand your question.

If you have a variable there in Rewrite_To, you cannot whitelist it because it always changes.

Try disabling Grammar section as well to see if it fixes it.

**Comment by kangarko** [comment]
Closing due to cleaning of the issues page. If you still have this issue please post below I will read it!

**Comment by x1p** [comment]
I'm sorry that I did not respond within a few hours.
Yes I still have this issue. Let me try to explain it better.
What I wanted was that if a player swears his message is replaced completly by a static text. "SERVERNAME I'm muted" in full color.

Example:
A player swears with a particular category of words. For example "nazi".
The filter picks it up and the following occurs.
`match nazi`
`handle as curse_war`
The handlers picks this up and the following ocurs.
`curse_war:
 ...
  Rewrite_To: "&6[&aSERVERNAME&6] &7I'm muted"
`
Because of the Grammer Section, the capitilized servername is replaced by servername. So I've tried to whitelist the servername in the settings.yml.
`- ABC`
`- [ABC]`
`- '\[ABC\]'`
`- '\[ABC\] I have'`
Non of this works so far. So I wonder how to set it up, so the `Rewrite_To'` will place the text as stated. The only thing I can think of right now is to whitelist it including color codes.

**Comment by kangarko** [comment]
I understand, will investigate today.

**Comment by kangarko** [comment]
I am sorry I have bad news for you. The current pipeline is pretty long and complicated, and no matter how I move the rules check in correspondence to the grammar check, there will always be some issue coming up. Right now, this is rather a minor issue considering the others like the annoying doubled warning messages or rules partially not working due to message being changed in the wrong order. 

As much as I hate to do so, I had to leave this on "wontfix" for the time being. Thank you for your undestanding.

**Comment by x1p** [comment]
Ok. Thanks for the effort.
