### ISSUE TITLE
Player data aren't saved into MySQL

### ISSUE THREAD

**Issue by kikelkik** [kangarko/ChatControl-Pro#615]
I wonder why ChatControl saves player data (like which channels they joined) in the data.db instead of loading them into MySQL although I enabled and configured MySQL in the settings.yml . 
Does the plugin still make any use of the mysql table 'chatcontrol_data'?

**Comment by kangarko** [comment]
Hello, data.db is used as a backup copy. MySQL is being used. Make sure you're on the latest version. You  can always check the table yourself to see if they are being saved.
