### ISSUE TITLE
A place for every default file

### ISSUE THREAD

**Issue by Mxra** [kangarko/ChatControl-Pro#617]
It'd be nice to have a place to store all of the default files and their settings somewhere on the Wiki. As of right now, you can only get the default "settings.yml". I feel like this could help a lot of people out who just want to reset their rules without having to restart the server and generate new files, or just grab one specific rule that they messed up on or something.

**Comment by kangarko** [comment]
Hello, you can easily open up your ChatControl.jar with Winrar or unzip it on Mac and copy files from there.
