### ISSUE TITLE
v7.7.3 and v7.7.4 do not allow a player to do /ch leave <channel>

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl-Pro#619]
Maybe my title isn't descriptive enough, but for some reason, every one of my players is now joining in both the local channel and global channel, and they are unable to /ch leave <channel>

v7.7.2 works fine.

in 773, something changed and all my players join in both the global channel and local channel. Running the command /ch leave local says "you have left the local channel" but they never really leave, always stuck in read/write mode of both.

774 is the same as 773. 772 does indeed work fine.

My configs, if needed:
https://github.com/malonnnn/ServerConfig2/tree/master/ChatControl

**Comment by kangarko** [comment]
Solved. Thanks for reporting and a great idea of posting your server configs publicly!

**Comment by malonnnn** [comment]
Confirmed fixed in 7.8.0

Thank you!

**Comment by kangarko** [comment]
+1 <3
