### ISSUE TITLE
Trying to change rules.txt / chat.txt - errors.

### ISSUE THREAD

**Issue by Loonyy** [kangarko/ChatControl-Pro#62]
Hello, I've had this error for quite a while, no matter what version of Chat Control I use. 

I'm simply trying to delete certain variables, such as:

match \bgonna\b
then replace going
or
match :-\)
then replace ☺

However, when I save the file and then preform /chc reload (also happens when I normally restart the server) the entire plugin just breaks. I get the message: 
"The error was: java.lang.NullPointException: Cannot define operator when nothing is being created! File: 'rules/chat.txt' Line 0: '#"
It also sends this error in console: http://pastebin.com/0QqnqCtV

I'm not even sure if this is a bug with Chat Control or if it's something I'm doing wrong? I'm using FileZilla to transfer the files. I've tried changing the transfer type in FileZilla, among other things to fix this issue and I've come up short, which is why I'm creating this here.
I'm using version 6.7.1-BETA. (Paid version) Please can I have some assistance with this?

**Comment by EvilOlaf** [comment]
Get yourself notepad++ and try again. This issue happens when you use common windows tools to edit the config files. 
You may also use the search function on github to find similar (closed) issue reports for further information.

**Comment by Loonyy** [comment]
This fixed the issue, thank you so much!!!

I thought because it was a text file I needed to use notepad and not notepad++
