### ISSUE TITLE
Two prefixes

### ISSUE THREAD

**Issue by ArrowFX** [kangarko/ChatControl-Pro#620]
So i'm using luckperms as a rank system and ChatControl-pro. And the problem i'm having is that my rank system gives me a prefix which i want but Chatcontrol-pro also creates a prefix for the rank i have for example "[owner] **[Owner]** Username: ". and i can't find a way to disable this.

**Comment by kangarko** [comment]
Hello,

you can remove {pl_prefix} variable in formatting.yml or disable inserting prefix from Luckperms.
