### ISSUE TITLE
No joining messages

### ISSUE THREAD

**Issue by Alejandrorr7** [kangarko/ChatControl-Pro#622]
Hey, first of al thank you for the plugin. Im having some troubles displaying to the users when someone joins, despite leave messages are shown to them. When I'm op I do see the join messages so I think its more of a permission problem, thing is I'm using ultra permissions and I have enabled the join and leave messages for users, but it still is not showing, am I missing something? 

Server is spigot with offline-mode, with authme and the delay settings in authme config deactivated.

**Comment by kangarko** [comment]
Hello,

Here is a list of steps you can take to fix this:

- Make sure no other plugin is hiding those messages for players without operator status.
- Also ensure you have Hide_Join_Quit_Kick_Messages to false in messages.yml.
- Check messages.yml for Permission keys and check whether they are assigned to the join message, if yes, give players that permission.
- Make sure that the players have chatcontrol.messages.quit permission.
