### ISSUE TITLE
[Improvement] New Features

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/ChatControl-Pro#624]
Another Redirect, Sorry.

https://hastebin.com/xoyuyuhuli.vbs

**Comment by kangarko** [comment]
Hello,

thank you for your suggestions. For the first and the third one, you can add them yourself by just copying the format of the existing Ad_Info formatter in formatting.yml. You can just copy and paste the variables that we use and modify them to work with the new format.

For the second suggestion, I am very sorry but that's currently not possible with the current system.

Sincerely,
kangarko
