### ISSUE TITLE
7.8.0 mcmmo party spy

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#628]
This error is being spammed in my console:
https://pastebin.com/Ecax3FFW

**Comment by kangarko** [comment]
Is this fixed? Just change the Party_Chat's format in formatting.yml.

**Comment by Sikatsu** [comment]
I had to manually add Party_Chat's format in formatting.yml for it to be fixed.

**Comment by kangarko** [comment]
Okay. There is a failsafe mechanism but apparently something went wrong, thanks for the notice.
