### ISSUE TITLE
Enhance channels/private messaging

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#63]
I recently had a suggestion by a fellow player that wanted to priv msg multiple players at once.
First I though this could be solvable with channels but rapidly found out that it seems like that staff has to create particular channels by adding permission nodes to them. Not very efficient, well, for this cause ;).

So what if players (a proper permission node) are able to do their own channel management?
For example player X wants to chat to player Y and Z all the time. So he can invite them to a new channel like `ch invite mycoolchannel Y Z`. To say `ch invite <channelname> <playername> [playername] ...`.

I could go far more into detail, like channel admin features for the inviter, accept/decline invite offer, particular permission nodes for all the stuff, hide all other chat messages except players with bypass permissions and so on but firstly I want to know what do you think about that.

As always thanks for reading.

**Comment by kangarko** [comment]
Hello,

Thanks for the suggestions, it sounds interesting. 
But there's the downside. I am currently working on version 7.0.0 and I takes more time than I've expected. I won't manage to implement all features and I don't want to leave everything at the to-do list even when I know I am most likely never going to add it. That's why I am closing this suggestion for now. Thank you for your understanding.

**Comment by EvilOlaf** [comment]
Well no one was asking for immediately implementation and I do not see an issue in leaving open suggestions in a to do list ;)
Yes, going from 6 to 7 is a major version jump but this should not mean that there won't be any new features till, for example version 8 ;).

**Comment by kangarko** [comment]
All right, if you do not mind waiting :)

**Comment by EvilOlaf** [comment]
Absolutely not. I am grateful that you are reading these suggestions and consider an implementation.

**Comment by kangarko** [comment]
Adressed in the roadmap. Feel free to continue the discussion here.
