### ISSUE TITLE
color permission

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#630]
Please add a permission PER color and decor (i want to disable super dark colors, underlines, bold and &k).

**Comment by kangarko** [comment]
You can, it is already there:

https://github.com/kangarko/ChatControl-Pro/wiki/Permissions#chat-formatter

**Comment by mrcoffee1026** [comment]
Oh good, I didn't see this comprehensive list before.  However when setting permissions, I notice it still displays items in this menu the user doesn't have permission to do.  Also while clicking a thing gives it an enchant shimmer... there is no evidence beyond that selecting a color has done anything as far as I can find.  Color of the chat text remains unaffected.

I notice the menu information says that this overrides the prefix from the group permission... and i'm kind of thinking this is where the problem may lie?  The prefix from the permission precedes the nickname and would have no effect on the text color that appears after... besides that the nick auto resets formatting anyway... either way the formatting would be gone before a chat message showed up.  I have chat set to "nick>chat message" in essentials I think we did that... the > is also not affected by the color settings... I'm not sure where else I might get a glimpse of it.  I"m using the old chatcolor plugin and it's able to change the chat color just fine, but I'd rather remove the plugin if functionality in yours can replace it.

**Comment by mrcoffee1026** [comment]
Tried again, enabled the formatter which solved the colors not changing... I still think the disabled ones (one a user has no permission to) should not display in the options, that's just confusing.

New issue, the Jobs Reborn plugin adds prefixes to everyone's chat messages, or did.  Thing is, with formatter active this goes away and there seems to be no way to re-enable.  The plugin documentation says: 
`If you're using a 3rd party chat manager, you may want to use their custom chat formatting. If you do this, set modify-chat in generalConfig.yml to false. Jobs will replace any instance of {jobs} in the chat formatting string with the appropriate title. This should work with the majority of the chat formatting plugins out there. If it doesn't work, contact the author, or try a different chat manager.`

I have tried using {jobs} with their setting updated to (modify-chat: false) as they've said but the result is that every messages just has "{jobs}" prepended to the string (no quotes).  Is there some way to make this work as advertised?

**Comment by mrcoffee1026** [comment]
Also what's going on with in-line color codes?  I can't find a permission for that in the documentation but it looks like if someone types something like "&fSomething" it just prints the character and the letter, not the color?  I have the permission to bypass this but no one else does and I can't sort out what it is.

**Comment by mrcoffee1026** [comment]
I then later realized the format permissions are what are disable inline colors.  When I added like 
chatcontrol.chat.format.color.white
then people could type the &f and it would be rendered as white text instead... but the /chc color gui seems to be ignoring these permissions so... still having a problem, just a different one now (made a different ticket for this).

**Comment by kangarko** [comment]
Hey, sorry for the delay.

The permissions were not effective in the /chc color menu, but they are now as per the latest update. The color and decoration from that menu are appended at the beginning of a {message}, so it is before the {pl_prefix} or other variables. 

By the way, the color menu is applied even if you have Formatter and Channels disabled, but in case of using another plugin such as that one you use(d) it may be incompatible.

For jobs, I highly suggest looking into PlaceholderAPI and using one of their placeholders. ChatControl handles chat in own way due to the interactive elements, and thus renders many plugins incompatible. A partial workaround for that would be if you try changing priorities of Formatter in Listener_Priority key (more on that in the Wiki) to HIGHEST or MONITOR so we will catch the message as last.

**Comment by kangarko** [comment]
I am closing this because the permissions for the color were added. If the advice for Jobs won't work out or you have any more questions, please post below, I will read it normally.

**Comment by mrcoffee1026** [comment]
I was able to sort out Jobs, it seems the placeholder they gave is a lie.  But I have PlaceholderAPI, it has a couple others for Jobs that could be added... I struggled doing anything with them outside of their PlaceholderAPI's javascript thing... partly since there doesn't seem to be a way to reload javascript for chatcontrol without a restart of the server... or maybe the placeholders are useless outside of PlaceholderAPIs javascript routines, I'm not really sure.  In any case I eventually got better than I wanted using the formatter to hide the results of a jobs placeholder in the pretty box that appears when you hover over someone's prefix.

I couldn't get the colors working without the formatter and I did kill our old plugin (chatcolor+) when trying that out, so I'm not sure what was going on there.  But using the formatter for 2 seconds, it's already indispensable, so I don't care if I have to have it on or not.

Thanks again for everything.

**Comment by kangarko** [comment]
Doing /chc reload will reload your variables/javascript.txt file and make chances in formatting.yml.

Actually, maybe you can "fix" the {jobs} placeholder by changing Formatter's priority (see Wikipedia) on Listener_Priority.Formatter to HIGHEST or even MONITOR (or LOWEST)...

**Comment by mrcoffee1026** [comment]
Hrm I must have just been doing something wrong then, it didn't seem to be reloading for me... there may also be some sort of understanding everyone but me has about placeholders and when to swap the brackets for percent signs (and vice versa) which I found also needed to be done at times for like the marriage reloaded placeholders... but I never got anything to display for {Jobs} which their wiki said should have worked.  They had a %jobs_format% that worked fine.  The marriage placeholders were a bit stranger , there's one that is a %gender_prefix% which returns ... the placeholder name for the icon instead of the icon itself.  They had an easier placeholder text to parse for male or female so I just made my own switch to return the unicode character the icon thing was supposed to give, but yeah once placeholders are placeholders of other placeholders I'm not really sure what a person has to do to get the "result" displayed.  I've got things displaying correctly now, and it worked out a lot better than I'd have hoped so thanks again for the help.

**Comment by kangarko** [comment]
Actually ChatControl does not support %syntax%, only {syntax}. Strange. Anyways, we support {syntax} from PlaceholderAPI but if any other plugin replaces variables in chat message before we catch it and JSONify it (add interactive chat elements), they are feel free to do so.

Sure, let me know if something goes wrong again and I will be here.
