### ISSUE TITLE
Report on ChatControl

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/ChatControl-Pro#631]
New Feature c.c I think it is quite inherent to the name of the plugin.  

Good evening to everyone! Today I wanted to propose a sort of Report embedded within the plugin itself, practically I propose the introduction of the command /chc report {USERNAME}.

Virtually when the user will do this command the CHC plugin will send a message.

Before this message is sent, a GUI is opened for Select the Reason for the Report. 

The default reasons are created by the Config with the file reports.yml, Once the pattern is selected, this message is shown below.

&6Are you Sure to report the player &e{USERNAME} &6With the Reason: &e{REASON}

 &6Are you sure you want to send this & eReport?             

               Click Here to Confirm! 

When the report is sent, the user receives this small message: 
Reported User: 
Schedule: 
Server: 
Status: Pending 

Now let's talk about the Staff side When a Report arrives, they receive this Message:

  Reported User: 
  From: 
  Report Time: 
  Server:
  Reason: 
  Status: Waiting           
Click Here to Modify Report and Report Status!

From here, a GUI will open, where you will find two objects: 

Changing Status Report: (lore) By entering this section of the Report menu the Staffer can update the Parameter status (Described first) the one with: Pending, then select from: Add Personal Message, Resolved, Not Resolved, Archived. 

Close Report: With this simple button the Help Request will be closed. And then a warning request is sent to the user.

N.B: When a Report arrives, the [x] key will also be available. See ChatLog. As soon as that Button is clicked the server will say, I'm loading the Chat ... Wait. 
[Time / Day] {USERNAME}>
[Time / Day] {USERNAME2}> 
[Time / Day] {USERNAME3}> 

Obviously there is something to be understood. The chat will not be shown this way but it will be like the one that actually happened on the day when this Report is sent. Soon I will probably make the most impossible proposition about this report and ChatLogs.

 Thanks and Good Evening c:

Attention: If you do not understand something, just ask under this Thread for Clarifications. c:

**Comment by kangarko** [comment]
Thank you for your suggestion, at present I am not planning to add it but I added it ot the Ideas roadmap.
