### ISSUE TITLE
[Error] Editing messages.yml 

### ISSUE THREAD

**Issue by NachoMans** [kangarko/ChatControl-Pro#632]
![screen shot 2018-03-12 at 9 43 22 pm](https://user-images.githubusercontent.com/20606454/37319789-8957f09e-263e-11e8-8567-8dcf214ebc8c.png)

This error spams in my console when I edited the messages.yml

**Comment by kangarko** [comment]
Post your messages.yml

**Comment by kangarko** [comment]
Closing, if you still have the issue please post your messages.yml.
