### ISSUE TITLE
Option to disable admin chat spy?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#633]
When I have /spy on, it says [Spy] [global] <name> <message> for the mcmmo adminchat.
Is there an option to disable mcmmo adminchat spying?

**Comment by kangarko** [comment]
Not currently, the /spy is equivalent to /socialspy from Essentials so we spy everything. There is another kind of spy when you have the "bypass ranged mode" permission, but that cannot be toggled by a command.

**Comment by kangarko** [comment]
Added a toggle to settings.

**Comment by Sikatsu** [comment]
I see. Because currently if we are talking in the adminchat of McMMO, all messages show up twice which is really annoying. With my previous PartyChatSpy plugin (which hooked into essentials /socialspy) it didn't spy on the adminchat of McMMO. Hoping there might be a fix somewhere around, actually.

**Comment by kangarko** [comment]
I think I have it solved in the next version, thanks.
