### ISSUE TITLE
Global chat color support to /chc color

### ISSUE THREAD

**Issue by boringwolf** [kangarko/ChatControl-Pro#636]
I have one BungeeServer and two sub Servers.
The version of BungeeServer is Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:2365554:167 by md_
Two Spigot servers is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

I update the plugin today, but I found that the "/chc color" doesn't work well.
The menu is good, but when I choose one color of them. Nothing changed.
Should I add any placeholder in formatting.yml ?

settings.yml https://pastebin.com/nVjGZLGA
formatting.yml  https://pastebin.com/Z4mUqPh9

**Comment by kangarko** [comment]
Do you use Bungee chat? The color feature currently lack bungee support.

**Comment by boringwolf** [comment]
OK I know, hope that the bungee support coming soon.

**Comment by kangarko** [comment]
As suggested in https://github.com/kangarko/ChatControl-Pro/issues/642
