### ISSUE TITLE
'<center>' not working on formatter.

### ISSUE THREAD

**Issue by AlaaZorkane** [kangarko/ChatControl-Pro#639]
I don't know if you've added the center thingie everywhere or just in MoTDs but if so, it's not working on my formatter,
IF you didn't add it then you can close this issue and i'll make a pull request.

Hover_Event:
Action: SHOW_TEXT
Values:
- '&0'
- '<center>&4&lX&c&leya'  <-- New way _(not working)_
- '&0 &0 &0 &0 &0 &8&m---------------------' <-- Traditional way _(working)_

**Comment by kangarko** [comment]
The center only works in the Motd, sorry.
