### ISSUE TITLE
Random "Network unreachable" 7.8.0

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#641]
Yesterday my staff informed that chatcontrol was not working on staff server (for now i upgraded to 7.8.0ì only here)
and you can see it get disabled at start for no reason https://hastebin.com/oxofifehup.md

**Comment by kangarko** [comment]
I apology for this, so far you are the first person who have this issue (again sadly). The new system should be much more fail-proof but nevertheless.. Please contact me on Spigot for backup activation codes in case this happens.

I am investigating this.
