### ISSUE TITLE
[Suggestion] Make chc color work across bungee

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#642]
I would like to see this feature:
- Using chc color in any server, it will reflect globally in all bungee (mysql)
- Add the permission for disable this special color

**Comment by kangarko** [comment]
Thanks.

**Comment by kangarko** [comment]
Closing as much of this was added :)

**Comment by xion87** [comment]
You don't added it :(

**Comment by kangarko** [comment]
Not on Bungee tho, sorry about that. Since you posted a separate suggestion I keep this closed
