### ISSUE TITLE
BungeeChat X DiscordSRV

### ISSUE THREAD

**Issue by Laurent-Sonny** [kangarko/ChatControl-Pro#645]
Does the DiscordSRV-Chat working meanwhile I use the BungeeChat? Now, the DC-Bot can send messages to the server and the joining/leaving messages and the deaths and achievements is still sending to the DC. But the chat from MC to DC is not working. I have been checked the config of DC many times for the senders and it is also activated.

**Comment by kangarko** [comment]
Sorry if you mean the BungeeChat plugin, that is unsupported.
