### ISSUE TITLE
Private Message to {nick}

### ISSUE THREAD

**Issue by locke-d** [kangarko/ChatControl-Pro#647]
Please add in the support to private message users with both their real ign, and their current nick.

if a player has the realname billy but is nicked as goat, you may pm billy, but you can't pm goat.

**Comment by kangarko** [comment]
Pending as improvement.

**Comment by locke-d** [comment]
thank you kangarko

**Comment by kangarko** [comment]
We would, however, only support what the {nick} variable returns (Nicky/Essentials).

**Comment by locke-d** [comment]
odd, I tested that I could message a player with both their nick, and their realname, with default spigot and essentialsX.

**Comment by kangarko** [comment]
Implemented.

**Comment by SuperiorCodeMonkey** [comment]
when I try to message someone with {nick} and their nickname contained chatcolor codes, the client crashes due to having invalid characters in the command. you might want to be careful with that. maybe add another variable called {nickname} or parse if it's being used in a command...

**Comment by kangarko** [comment]
@SuperiorCodeMonkey I will fix that in the next release, thank you for noticing!

**Comment by SuperiorCodeMonkey** [comment]
You're welcome!
