### ISSUE TITLE
Party spy issue

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#649]
If you're in a party with McMMO party spy on you receive double messages from party members. For admin chat this was fixed, for party chat not yet however.

**Comment by kangarko** [comment]
Alright thanks for reporting. I did a quick hotfix, let me know if it was fixed.

**Comment by Sikatsu** [comment]
I think it completely broke. Seems i'm unable to spy on mcmmo party chat now.

**Comment by kangarko** [comment]
Sorry for that one, fixed again.
