### ISSUE TITLE
/chc color, /chc ach switch

### ISSUE THREAD

**Issue by Linebeck** [kangarko/ChatControl-Pro#652]
I am using version 1.12 for all of my Spigot Servers, and 1.12 for my BungeeCord (SnapShot 1303). I currently have Bungee enabled, and everything works great as far as the chat and the features I originally had before the 7.8.1 update. The only issue I am having is in regards to /chc color & /chc ach switch. (Each Individual server does this btw. They all have different plugins.)

So when I click on a color that I want to select for my chat. The name of the inventory changes color, and the inventory cancels the event for me to pick it up like it would normally. However, I don't have that color I selected being used as my chat color. Nothing happens basically. I discovered if you toggle /chc ach switch you will actually start using the color that you picked. (As long as you have the formatting that I have in my config, I believe.) If you don't it won't do it.

Here are my configs:

BungeeCord: https://pastebin.com/7KPijTxn

Settings: https://pastebin.com/h4jFUiz0

Formattings: https://pastebin.com/nQuTwvQd

Everything else is the default config.

I also put the plugin into a clean version of 1.12 with nothing on it except ChatControl & ProtocolLib, and it did the same thing, so I know that it isn't another plugin causing this.

Any help would be great! Thanks.

![image](https://user-images.githubusercontent.com/25122665/37568632-3ff57dda-2aae-11e8-96ff-4236f122cd2b.png)

**Comment by andris155** [comment]
Color bug: https://www.youtube.com/watch?v=Y_VBS_oRb8E

**Comment by kangarko** [comment]
I have extended the support of /chc color menu to all other elements of chat.
