### ISSUE TITLE
Could you add configerable text for everything?

### ISSUE THREAD

**Issue by starwarsfreak219** [kangarko/ChatControl-Pro#658]
I do notice there is configurable text for a few things, but I can't seem to find a way to configure certain text like: "! You cannot chat until you move." Or similar things like that. I would like to configure mostly everything the player would see. Thanks!

**Comment by BlackGamer000** [comment]
Hey, Hello c: have You Created the Localization File? most of The Messages are in that file

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Localization
