### ISSUE TITLE
[MAJOR] ChatControl Pro causing disconnect on Bungeecord

### ISSUE THREAD

**Issue by BungeeTheCookie** [kangarko/ChatControl-Pro#66]
Hello @kangarko,

I am using ChatControl Pro on my Bungeecord setup. When I try to chat on any of my servers that run ChatControl Pro **with Travertine (1.7.10 - 1.10)**, I get sent to the hub with this error message in the Bungee console:

http://pastebin.com/VgqnkSMb

However, when I try to chat on my servers that run ChatControl Pro using a **HexagonMC Bungeecord (1.7.10 - 1.10)**, I get disconnected with this:

http://pastebin.com/F5UmYHtj

This does not happen when there is no ChatControl Pro installed on the servers. I am running Thermos (a fork of kCauldron) 1.7.10 servers, and a 1.10 Hub using ProtocolSupport. I do not get disconnected on the Hub, just the Cauldron/Thermos servers.

**Comment by BungeeTheCookie** [comment]
To further add, if I remove ProtocolLib and run ChatControl by itself, it works fine, it is only if I have ChatControl Pro and ProtocolLib running at the same time.

**Comment by kangarko** [comment]
Hello,

this is really rare, I've personally never experienced such issue.
Have you modified the packet.txt file at all? If so, I please you to do the following, as I don't have the necessary environment to test it. Remove rule, one by one, restart the server and see if it continues to happen. When you come across the problematic rule please send it to me. Thank you.

Also, can you please test against the latest version 7.0.1 ?

**Comment by BungeeTheCookie** [comment]
@kangarko 
I have not modified the packet.txt file at all. In addition, this error is not occuring on the server I have ProtocolSupport installed on. This is occuring on the servers where I have Thermos 1.7.10 installed on, using ChatControl Pro, that are under a Bungeecord. The ProtocolSupport is only for the Hub server (which runs PaperSpigot). The Thermos servers run both ProtocolLib and ChatControl Pro, but **NOT** ProtocolSupport.

**Comment by kangarko** [comment]
Oh ok. Then it seems to be most likely Thermos issue. It seems like it's modifying something under the hood (in vanilla server), that I cannot do anything about. I am sorry. CHC is guaranteed to be functional on Spigot, Craftbukkit and unofficially also PaperSpigot.

**Comment by BungeeTheCookie** [comment]
That's fine. All you have to do is disable Packet features and you're good.

**Comment by kangarko** [comment]
Allright. I am closing this because it's an incompatibility and it cannot be fixed without making a special derivation for those projects, to which I don't have time for. Thank you for your understanding.

**Comment by BungeeTheCookie** [comment]
Thank you for your help :+1:
