### ISSUE TITLE
Double chats?

### ISSUE THREAD

**Issue by viocu** [kangarko/ChatControl-Pro#663]
Hi! I am trying to configure this plugin to replace DeluxeChat as it doesn't have channels, which is what I need for my server. My issue is that I am having a hard time wrapping my head around all the configs. I have channels enabled (one is a survival chat channel, the other is admin chat) and when I type a message that is meant to go to survival (default autojoin for all players goes to survival channel) it duplicates and also goes to admin chat (shown in pic)
https://gyazo.com/c67cb58049b788871220171890657ef1

Maybe I have permissions wonked, I don't know. I want people with the permission to see the admin chat to be able to write there with /mb message here (aliasing the /chc send admin, which works fine without duplication) and people who can see both survival chat and admin chat to be able to write to survival straight without having to add any extra commands (like /chc send survival message here...I don't want that). I've read over the wiki and still am confused, can you help, please? :(

**Comment by malonnnn** [comment]
This doesn't really answer your question directly, but maybe it can be of assistance, all my Chat Control configs are public, so maybe you can use those as reference to help you along
https://github.com/malonnnn/ServerConfig2/tree/master/ChatControl

My server uses 2 chat channels, Global and Local (limited to 100 blocks speaking distance)

My permissions file is gigantic, but you can still look through it if you want
https://github.com/malonnnn/ServerConfig2/tree/master/PermissionsEx

**Comment by viocu** [comment]
Sweet, thanks! I'll check it out and see if it helps :)

**Comment by viocu** [comment]
I looked over it, and made some adjustments, but still getting duplicated chat messages.

**Comment by malonnnn** [comment]
Post your configs & plugins list

**Comment by viocu** [comment]
https://pastebin.com/Cn73UsuH <- Settings.yml
https://pastebin.com/gBjWjN9y <- channels.yml
https://pastebin.com/TL9iCi3E <- formatting.yml

Plugins (59): CleanroomGenerator, PlaceholderAPI, GetInventory, OldCombatMechanics, DeluxeTags, LogBlockQuestioner, DropEdit, ViaVersion, ViaBackwards, ChatColor, LuckPerms, ChatAPI, WorldEdit, ClearLag, Heads, WorldBorder, MessageAnnouncer, Multiverse-Core, CS-CoreLib, mcMMO, Vault, CrazyCrates, LogBlock, HeadHunting, DabCore, LWC, WorldGuard, Slimefun, Multiverse-NetherPortals, MyCommand, BungeeTabListPlus, OneTimeItem, Essentials, SpigotLib, Jobs, PointsAPI, Fe, ProtocolLib, Feudal, LibsDisguises, TreasureChest, Citizens, Shopkeepers, ExoticGarden, RedeemableMcMMO, ChestShop, HolographicDisplays, CommandNPC, Warps, WorldGuardExtraFlags, TitleManager, ChatControl, mcMMOAction, SilkSpawners, BossShopPro, CitizensIntergration, LimitedUses, TrickyShops, ThirdCurrency

Permissions are done through luckperms and is set in a database. https://gyazo.com/2ab55aaf892e5eca49dfeb9a5aabfe7f there are all teh permissons  I have associated for that.

Let me know if you need anything else. :)

**Comment by kangarko** [comment]
Hello viocu and thanks for using ChatControl,

to give you a short answer: ChatControl allows writing in unlimited amount of channels at the same time. So, if you autojoin two channels for write mode, each time you type a message, it will be sent to both of them:

I can see the cause here as you have two autojoin write permissions:
![a](https://i.imgur.com/nCVhFNv.png)

You can either remove those or limit the amount of channels per player to 1 in channels.yml.

**Comment by viocu** [comment]
But will the person who also has the ability to see the admin chat able to write in it using the /chc send admin messagehere command (or the alias I want to use, /mb?)

**Comment by kangarko** [comment]
If the person has the "read" permission he will be able to read messages if he is in the channel in the read mode (aka /ch join admin read, or has the ....autojoin.admin.read permission).
