### ISSUE TITLE
Priority handling of swears

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#667]
Which priority is present in handling different types of swears?

Fictional example:
The rules file contains 2 swears in this order:
#rule 10:
match shit
handle as swear
...
#rule 200:
match stinky
handle as rude
...

The handlers file:
swear:
  Warn_Points: swear 1
  Block_Message: true
rude:
  Warn_Points: rude 1
  Block_Message: true

When a player's message is like this:
player123: stinky shit
The swears are matched as follows:
match stinky
Message denied.

So the player is not punished for the most heavy swear.

A 'swear' is to be punished harder than a 'rude'. Therefor the most heavy swears are to be matched first and are placed first in the rules file.

Question: how can I make sure that the players message is matched according to the most heavy swear first?

**Comment by kangarko** [comment]
Ohh, those hashmaps change their order in Java. Sorry, I changed it to LinkedHashMap. Anyways, it should now be processed from top to bottom.
