### ISSUE TITLE
ChatControl | Problem

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#668]
Hi, I have two problems with ChatControlPro
From different version, the plugin give me these errors:

https://pastebin.com/gKUiutH9

https://pastebin.com/kfsZX93A

How can I solve?
Thanks

**Comment by kangarko** [comment]
Sorry seems like you have corrupted jar. Please redownload and do not use plugman or the /reload function. Restart instead. Also, try with the next version.
