### ISSUE TITLE
API jar mistake + need help with chat event

### ISSUE THREAD

**Issue by CaptnSisko** [kangarko/ChatControl-Pro#669]
I found a mistake in the API jar file -- the ChannelAPI class is in me.kangarko.chatcontrol.api.channel.ChannelAPI in the API jar, while the in the plugin the class is in me.kangarko.chatcontrol.api.ChannelAPI.

Also, I can't figure out how to make the ChatChannelEvent fire whenever someone talks to the default channel or whenever someone talks from another server. Am I doing this wrong, or is this a limitation of the API?

```
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;
import me.kangarko.chatcontrol.api.event.ChatChannelEvent;
public class Main extends JavaPlugin implements Listener {
	@Override
	public void onEnable() {
		getServer().getPluginManager().registerEvents(this, this);
	}
	
	@EventHandler
	public void onChat(ChatChannelEvent e) {
		getLogger().info("Message!");
		getLogger().info(e.getMessage());
	}
}

```
This only fires when I explicitly chat to a non-default channel.

**Comment by kangarko** [comment]
Thank you, I moved the class in the official jar. Always compile against the official Jar :)


The ChatChannelEvent only fires locally with no bungee support at the moment, and requires Channels enabled.
