### ISSUE TITLE
Permission for specific chat rules

### ISSUE THREAD

**Issue by AndrewRed67** [kangarko/ChatControl-Pro#67]
Hello, I want to request a feature...
We have some chat rules, for some smileys and such, but we want those rules only to be activated when you have a specific permission. If you have the permission, it will activate, otherwise it won't.

For example:
Knight Rank - free - no permission - doesn't activate rule
VIP Rank - 5 dollars - has permission - activates rule

And in the rules/chat.txt, it looks like this:
match \\:paper\:\
then replace (paper-emoticon)
permission [enter permission]           # will result in chatcontrol.chat.custom_permission
Or something like that.

If you are able to create this (possibly as soon as possible, but I know you're busy as well :P) that would be great! Maybe even worth a donation. ;)
Otherwise, thanks for the amazing plugin! -Andrew
PS: we use  version 6.9.10

**Comment by kangarko** [comment]
There is already an operator

require perm <permission>

which will only allow the rule if the player has the permission.
