### ISSUE TITLE
[Suggestion] Tab bungee player's name

### ISSUE THREAD

**Issue by Linebeck** [kangarko/ChatControl-Pro#670]
I may or may not know what I am talking about, so correct me if I am wrong. I was wondering if it would be possible to tab complete a player's name that is on another server? I know you can do this with Litebans. The only way I can tab that player's name with ChatControl is when I am on the exact same server as them. It would be cool to have it for bungee and be on any server. Just a thought.

**Comment by kangarko** [comment]
Hello,

sure this is confirmed and the roadmap already, although with no ETA.
