### ISSUE TITLE
Potential matcher issue?

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Pro#671]
I don't really know how to explain this other than the fact that I'm trying to hide certain commands from regular players and ignore anything past that, for example, a colon command `/command:command` or something like `/commandasdasdasd`, however, they don't seem to be matching correctly.

I'm not sure if this is an issue with my REGEX or something else, so I'll just post this here in hopes to get it resolved, whatever it may be.

All of these matches are located within my commands.txt rules file. I will be referencing them all using their ID's for simplicities sake.

```
match (spartan|reflex|ncp|nocheatplus)
ignore string (spartan|reflex|ncp|nocheatplus).(.*)
id AC
handle as hidden

match (luckperms|lp|permission|permissions|perm|perms)
ignore string (luckperms|lp|permission|permissions|perm|perms).(.*)
id LP
handle as hidden

match (litebans)
ignore string (litebans).(.*)
id LB
handle as hidden

match (chatcontrol|chc|ch)
ignore string (chatcontrol|chc|ch).(.*)
id CC
handle as hidden
```

Those are all of my matches, however, for some reason, the LP and CC ID's are not being matched correctly, whereas the other ones are just fine.

Examples:
> CC match will only catch "ch", the rest will be ignored and will only function correctly at the `ignore string` at the caught matches.

> LP match will only catch "perm" and "lp", the rest will be ignored and will only function correctly at the `ignore string` at the caught matches.

> AC match will catch everything fine and break accordingly at the `ignore string`.

> LB match will catch everything fine and break accordingly at the `ignore string`.

I have no idea why one would work just fine and the other one wouldn't when they're using the same REGEX patterns, so I'm out of ideas.

If you need any additional information just let me know.

**Comment by x1p** [comment]
These rules simple match all containing the words and again ignore everything with those words. Sounds a little contradictory

Did you take a close look at the default examples of commands.txt?

**Comment by ArtelGG** [comment]
I think you misunderstood what the point of my matches are. I'm trying to effectively ignore everything after the original catch, i.e `/command` will be caught, then anything/everything else will be ignored such as `/commandabcde`, `/command:blah` `/command:/command`.

I gave the default `commands.txt` a look over and changed my REGEX in hopes to at least improve it:

```
match ^/(spartan|reflex|ncp|nocheatplus)\b
ignore string ^/(spartan|reflex|ncp|nocheatplus).(.*)
id AC
handle as hidden

match ^/(luckperms|lp|permission|permissions|perm|perms)\b
ignore string ^/(luckperms|lp|permission|permissions|perm|perms).(.*)
id LP
handle as hidden

match ^/(litebans)\b
ignore string ^/(litebans).(.*)
id LB
handle as hidden

match ^/(chatcontrol|chc|ch)\b
ignore string ^/(chatcontrol|chc|ch).(.*)
id CC
handle as hidden
```

Still having the same issue with the same matches.

**Comment by x1p** [comment]
Why don't you try something like:
match ^/(chatcontrol|chc|ch)$
ignore perm chatcontrol.commands.mute
id CC
handle as hidden

**Comment by ArtelGG** [comment]
I tried that once before and it didn't work, however, this time it did for some reason. 🤔 Thanks for the help.
