### ISSUE TITLE
Changing Channel Join message

### ISSUE THREAD

**Issue by SiuanSong** [kangarko/ChatControl-Pro#675]
I was wondering how I can possibly change or disable this message for channels:
https://i.imgur.com/zrAzbWs.png
**[+] Player [playername] joined this channel (main)**
It just creates more spam in our chat and isn't useful for us.
I'm not seeing that message or an option for it anywhere in the configs.
Thanks!!
Siuan

**Comment by kangarko** [comment]
Please see the Wikipedia about Localization.
