### ISSUE TITLE
Suggestion: Command to reset player points.

### ISSUE THREAD

**Issue by bc-hill** [kangarko/ChatControl-Pro#677]
This is mostly for testing purposes, but I would like to have a command (expansion of the "/chc points" command?) to reset points for a player.  I do not have swear points automatically removed, but there are times where I would like to manually reset them.
This is not high priority, but I am guessing that it would be easy to implement?
Thank you!

**Comment by kangarko** [comment]
Hello,

this is a great suggestion and I look forward to add it soon.

**Comment by x1p** [comment]
I have suggested this too, months ago in https://github.com/kangarko/ChatControl-Pro/issues/530

**Comment by kangarko** [comment]
Added to the next version.
