### ISSUE TITLE
Config GUI + Improve RulesCreator

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/ChatControl-Pro#679]
Good evening! c:

Today I'm here to offer a great Feature on CHC Pro.

Let's talk about the setup of the whole plugin in Game.

So, let's start with settings.yml settings

Through the command /chc setup will open a GUI with all the settings that are available to set the plugin, So we talk about AntiSpam AntiCaps, Points, Warn, and All the Rest. So basically it will be possible to activate some settings simply through the game (permission: ChatControl.commands.setup)

Other Feature. Would it be possible to add a third STEP during the Chc addrule (both advertisement and Swear)? That of the code to be executed in a certain message, then an example: then console ban {player} 30d Test.
So before closing the RuleCreator Wizard you can do this step which is not mandatory. Just make the parameter 'skip' to avoid it without inserting commands.

I finished c:

Good evening.

**Comment by kangarko** [comment]
Hello,

thank you again for posting so many suggestions! Right now I am busy with real life projects outside of Minecraft, but I am leaving this open for the future.
