### ISSUE TITLE
BungeeControlBridge 2.2 bug

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#680]
BungeeControlBridge 2.2 has a nasty bug which concerns the bungeeconsole command executed by ChatControl.
These bungeeconsole commands are no longer executed.
This means that no punishment is executed by litebans!
Tested with chatcontrol 7.8.5 and 7.8.4. BungeeControlBridge 2.1 functions as normal for the time being.

**Comment by kangarko** [comment]
Hello, sorry for a late reply.

Please use the incoming 2.3 of BCB and set debug to "[commands, packets]". The first will print out bungee commands incoming from ChatControl, the second will print out everything incoming (lots of spam). This is just to test where the error may lie as there is literally no difference between 2.1 and 2.2 in this code.

**Comment by x1p** [comment]
I'm not able to reproduce it under BCB 2.3 + debug // CHC 7.8.5
The commands are well received so far.
16:40:58 [INFO] [BungeeControlBridge] Incoming message from ChatControl: BUNGEE_COMMAND
16:40:58 [INFO] [BungeeControlBridge] Executing command on bungee: tempmute Player123 -N 1m Reason blah blah blah
Weird that it is not reproducible. We didn't change anything. Since BCB 2.2 no command was executed for a few days. So no accidental mistake. I downgraded tot CHC 7.8.4. Still no mutes/bans. So I finally downgraded to BCB 2.1 and instantly all commands were executed as normal.

What I did notice was a lot of spam for every player connected to all bungees:
16:40:58 [INFO] BungeeControlBridge failed to find server associated with redis player 'Player123'!
16:40:58 [INFO] BungeeControlBridge failed to find server associated with redis player 'Player567'!
etc etc.

Btw: Issue #643 seems to be still present in BCB 2.3

**Comment by x1p** [comment]
This 'BungeeControlBridge failed to find server associated with redis player' only happens if a bungeeconsolecommand is executed and the players listed are pretty random as far as I can see.

**Comment by kangarko** [comment]
I have made the message about server not found only show when debug contains "redis" section, and it now shows the output more correctly (i.e. less often).

BungeeControlBridge relies on an external method to get a player's server. I have no control over that so I cannot warranty the result. I talked with the developers of RedisBungee to use that method, so if it doesn't work 100% there is little I can do, sadly.

So, is it working for you now? I just tested freshly 7.8.6 and BCB 2.4 and all works as expected:
![a](https://i.imgur.com/eQdvaUe.png)

**Comment by x1p** [comment]
Up till now it functions. I still have no clue why it didn't worked before as stated in the initial issue.
I will replace BCB 2.3 for 2.4 soon.

**Comment by kangarko** [comment]
Alright, I sincerely wish for both of us that it will persist so. Please let me know if anything arise.

PS: In case anything arise, try to observe whether it is related to the receiver being (or not being) on the same Bungeecord network as the sender (of a message), if this is relevant.
