### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fred112f** [kangarko/ChatControl-Pro#682]
Is there is a way to send messages with prefixes like @sc (staff chat) that broadcast to the staff_chat channel that are sent instantly?(without the player needing to join and quit the channel, just sending one message that doesnt have to do with what channel you are in,(doesnt add you to the channel), you only need the permission for it)

Is there any way to obtain private message sender's displayname and receiver's displayname?

**Comment by kangarko** [comment]
Answered on the free channel. Next time please post here ;)
