### ISSUE TITLE
when i enter into my server, i joined into all channels in write mode

### ISSUE THREAD

**Issue by friishon** [kangarko/ChatControl-Pro#684]
when i enter in all my server i'm joining in all channles as a writer and is too annoying

i use luckperms and i give that permission trying to prevent my problem, but doesn't work

![captura de pantalla_2018-04-07_20-44-54](https://user-images.githubusercontent.com/19889173/38459002-924c8afa-3aa4-11e8-8ed8-b9e0bdb9389b.png)

but when i join i enter in all channel as a writer
![captura de pantalla_2018-04-07_20-47-11](https://user-images.githubusercontent.com/19889173/38459033-e6ec7944-3aa4-11e8-9ae1-e189f55cfbd8.png)

**Comment by kangarko** [comment]
It may be because you are an OP so you get all permissions by default.

Try giving yourself negative -chatcontrol.channel.autojoin.* permission.

**Comment by friishon** [comment]
in luck perms, if the permission is in false it means that is negative, i can't use -chatcontrol.channel.autojoin.*

**Comment by kangarko** [comment]
I understand. Please test it as I told above but without "-"

**Comment by friishon** [comment]
i think i have to leave all channel again, then when i enter i only in the standard channel, it seems to work for the moment...

**Comment by kangarko** [comment]
Closing, let me know if issues arise again.
