### ISSUE TITLE
Private message issue with essentials

### ISSUE THREAD

**Issue by SpartanPride7** [kangarko/ChatControl-Pro#685]
Hello. Recently I tested the private message feature of chat control. After examnining it, I felt the essentials was better to use so I tried to turn Private Message off in console. After reloading both essentials and chat control, no message commands are working at all. This is a very important part of the server so if you can tell me what to do, that would be great. Thanks!

**Comment by kangarko** [comment]
Hello, please restart the server if you toggle private messages in ChatControl.

May I ask, what specifically have you been missing in private messages in our plugin?
