### ISSUE TITLE
Messages in Conversation Mode aren't logged

### ISSUE THREAD

**Issue by kikelkik** [kangarko/ChatControl-Pro#686]
Hey, we very appreciate the new conversation mode, where you can send private messages via @<player> . Sadly, we cannot announce this feature for all players because private messages send during conversation mode aren't logged into the console log, but just into chatcontrol's log file which is not statisfiying. 

So could you please add an option to enable logging or just allow it by default? 

By the way: I haven't tested it, but it could be possible that private messages in @-mode might not be tracked by essentials socialspy. 

Thanks a lot!

**Comment by kangarko** [comment]
Added, sorry for the delay.
