### ISSUE TITLE
auto join

### ISSUE THREAD

**Issue by kronk888** [kangarko/ChatControl-Pro#687]
how do i get it to stop auto joining me to admin etc when i do a reload ? and how do i change the colour it type in chat ? does this plug have a discord i can join got sooo much to ask lol

**Comment by kangarko** [comment]
You can change your chat color in /chc color. You can give yourself negative permissions (example: -chatcontrol.blahbla, starting with an -) to prevent autojoin, see: https://github.com/kangarko/ChatControl-Pro/wiki/Channels#auto-join

There is no discord at the moment, sorry.

Please read the Wiki (see the menu tabs above) for all useful information.
