### ISSUE TITLE
Essentials /me disabled when ChatControl-Pro is in the server.

### ISSUE THREAD

**Issue by chasedig** [kangarko/ChatControl-Pro#689]
I own a bungeecord network, two of which my subservers have chatcontrol pro. The one that doesn't, /me (essentials me) works. I have even attempted to bring back my /me by disabling me in the config, yet, it says unknown command. Help? | I just noticed it disabled /emsg as well. Fix this!! Now, I attempted to use /essentials:me and it worked! This is definitely on ChatControl's side.

**Comment by kangarko** [comment]
Hello,

when you are disabling the /me command in ChatControl's settings.yml, you need to restart your server and not use reload or /chc rl, as this can cause problems.

ChatControl has bungee support for /me.

How exactly did the command not work?

**Comment by chasedig** [comment]
I think this worked. Thank you very much!
