### ISSUE TITLE
unable to disable bungee connect messages 

### ISSUE THREAD

**Issue by TheFluffyWalrus** [kangarko/ChatControl-Pro#69]
BungeeCords:
  Enabled: false
  Enabled_In:
    Rule_Alerts: true
    Handler_Alerts: true
    Admin_Chat: true
  Prefix: ''
  **Server_Switch_Broadcast: false**

we had to disable all bungee messages to false the line that is bold does not function correctly

**Comment by kangarko** [comment]
I'll fix that in the next version.
