### ISSUE TITLE
Improvement of new ways to spam with whitelisted words

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#691]
In the Settings, chat section, there is a possibility to whitelist certain words:
Example:
  Chat:
    Whitelist_Similarity:
    - hello
etc etc.

Clever players notices this and spam with it:
Player123: Hello
Player123: Hello
Player123: Hello
...(more repeats)...
Player567: Please stop!

It would be nice if this whitelist can be a certain maximum number of repeats within a certain time span. There is of course the Limit setting but this is more annoying then normal chat, so this requires a tighter timer. Better imho would be a separate "Limit timer" or a separate "Whitelist_Similarity_Count" after which a different message must follow other then "hello".

**Comment by kangarko** [comment]
Hey, thank you for that suggestion. I put it to the low priority due to time constrains, but I may return to it in the future. Thank you for your understanding.
