### ISSUE TITLE
ChatControl Format is overwriting a name colour plugin.

### ISSUE THREAD

**Issue by MrWardy** [kangarko/ChatControl-Pro#692]
As the title says, Chat Control Formatting is overwriting a name colour plugin that I'd like to use but can't because Chat Control. On the other hand I would really like to use Chat Control formatting. I tried setting formatting priority to 0 and it didn't work either. Could someone please help? If you need to know, the name colour plugin is https://www.spigotmc.org/resources/epicnamecolor.55604/

**Comment by MrWardy** [comment]
Also, was the discord deleted cause I can't find the link on the spigot page anymore.

**Comment by kangarko** [comment]
Hello,

if you tried to change Listener_Priority.Formatter in settings.yml to all values (with restart after each change), and it didn't work, then I am sorry but I cannot unfortunately fix it.
