### ISSUE TITLE
Ignores resetting on restart

### ISSUE THREAD

**Issue by fyrmftw** [kangarko/ChatControl-Pro#694]
Hello,

Recently we've had an issue with multiple of our players /ignores are resetting upon restart, i've updated Chatcontrol, protocollib and essentials to latest but players are still having the same issue.

I'm not sure what could be causing it to make /ignore ? reset

Many Thanks

**Comment by kangarko** [comment]
Hey, sorry for a late reply, 

do you have MySQL enabled, and do you use Bungeecords?

**Comment by fyrmftw** [comment]
Hey,

No worries, I know how busy you're atm with IRL and other stuff, and no MySQL is not enabled and we don't use bungee.

**Comment by kangarko** [comment]
Sorry I tested but I cannot reproduce the problem. Please upload me your settings.yml to pastebin.com.

Couple of hints:
* How often does it happen?
* Does it only happen to players that have OP or any special permissions?

Finally, please use a text editor (like Notepad++) to open up your data.db to see Players.PLAYER_NAME.Ignored_Players section when it happens. If the ignore is reset, see if that section is reset as well or if it still contains the name. 

Thank you for your cooperation.

**Comment by kangarko** [comment]
@fyrmftw please use the next version and set Ignore.Report_To_Essentials to false. This should solve the problem. 

If the problem is not solved, please comment below and upload your settings.yml to pastebin.com.

**Comment by fyrmftw** [comment]
Hey,

Alright, i'll start adding the new version to the server and get back to you with the results, thank you.

**Comment by fyrmftw** [comment]
Hi, i'm still experiencing the same issue with the ignores and i'm also noticing that I think data.db is resetting sometimes too.

Here's my settings

https://pastebin.com/WPt4e29c
