### ISSUE TITLE
[7.8.6/7.8.7]People write randomly on admin channel

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#697]
I notice like from latest two version, i see on admin channel some people writing here, without any permission...., these people will write in normal (but they don't see the sended message) instead it will be send on admin chat without reason... fo fix it i have to give them the perm to toggle admin chat and anable and disable adminchat toggle....

**Comment by kangarko** [comment]
The next version will check for permission each type the player is about to write and put him off the admin channel if he lacks the chatcontrol.commands.adminchat permission.
