### ISSUE TITLE
Permission nodes for /chc colour

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#699]
Is it possible to make it so each item in /chc colour has its own seperate permission.

e.g. chatcontrol.command.chatcolour.green or something. (seperate from regular colour permission nodes)

**Comment by kangarko** [comment]
The menu already only shows colors that the player has permission to. The permissions checked are all permissions beginning with _chatcontrol.chat.format_, see Permissions on Wiki.

**Comment by LogGits** [comment]
Yeah I know about this permission. However, we give out access to all chatcolours to type in chat. This would allow all users to do `/chatcolor x`, it would be cool if they had a permission node to actually click the button for an auto colour. Hence, different permissions for regular chatcolour and the gui would be useful.

e.g. `chatcontrol.chat.format.color.red.gui`
