### ISSUE TITLE
Join/leave message

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#7]
in the 6.8.2

when someone join or leave it will show my name (or random name)

**Comment by kangarko** [comment]
Cannot replicate.

Can you post the effective part of your settings.yml ?

**Comment by rErEaT** [comment]
http://pastebin.com/LkW4uHgR

I give you the whole settings.yml - I demoted to 6.8.1 and works well again

**Comment by kangarko** [comment]
The {player_name} variable is not from ChatControl. I highly suggest using {player} variable instead.

**Comment by rErEaT** [comment]
oh sorry, then the vault permissions placeholder will work?

I test it

**Comment by rErEaT** [comment]
tested.
if I change that to {player} the name is good but the vault permission is not

**Comment by rErEaT** [comment]
hmm working with the latest version!

but still get this error :D

**Comment by kangarko** [comment]
What is the vault placeholder?

**Comment by rErEaT** [comment]
{vault_rankprefix}
