### ISSUE TITLE
[7.8.7] Chatcontrol causing infinite threads again

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#706]
Like the old issue that i reported some month ago, with latest version that issue is coming nback, causing infinte threads (right now i have 30000 threads open caused by chatcontrol)
The issue seem not present in 7.8.6

**Comment by kangarko** [comment]
Do you have more information regarding the threads? Any dumps or debug info so I can track it down?

**Comment by kangarko** [comment]
Please continue the discussion at https://github.com/kangarko/ChatControl-Pro/issues/695
