### ISSUE TITLE
[7.8.6/7.8.7] Failed to stuffs from MySQL

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#709]
Randomly i see this
https://hastebin.com/oqunetutiv.md
and this
https://hastebin.com/efepuwerop.md

Sorry for too many bug report ^^

**Comment by kangarko** [comment]
I will get to it in 24h, working on the freezing now.

**Comment by kangarko** [comment]
Hello,

this should be patched in the next version. Have you manipulated with MySQL manually?

If you have a minute, you can check your MySQL ChatControl's table and look for anything suspicious in the Chat_Mode column (it can only be DEFAULT, ADMIN, or BUNGEE, nothing else). Thanks.

**Comment by xion87** [comment]
the coloumn chat_mode contain only DEFAULT
