### ISSUE TITLE
MessageRemover

### ISSUE THREAD

**Issue by rErEaT** [kangarko/ChatControl-Pro#71]
Can you add this feature to your plugin?
https://www.spigotmc.org/resources/messageremover.1400/
This plugin is abandoned so no more updates and not working on 1.8+

But I think its very good to remove one or more messages from one by one so I dont have to delete the whole chat

**Comment by kangarko** [comment]
Firstly, CHC is not taking (major) suggestions as mentioned per changelog page. Secondly, this is already addressed in the road-map.
