### ISSUE TITLE
Filter Loophole

### ISSUE THREAD

**Issue by sgort87** [kangarko/ChatControl-Pro#711]
Prefacing a swear with 4 letters will let it slip through. If changing the rules would fix this, I feel like it should be the new default rules file, but if people add in new words, this would probably be an issue, as they probably wouldn't know how to add that in properly. I think an adjustment to the filtering code might be best.

[![Screenshot from Gyazo](https://gyazo.com/ff684618f019684e0c53109ffb736d30/raw)](https://gyazo.com/ff684618f019684e0c53109ffb736d30)

**Comment by kangarko** [comment]
Hello,

this is a known case where some rules only apply when the word has a whitespace " " in front of it. You can remove the initial \b after "match" operator to that specific rule in rules/rules.txt manually to make it also apply there.

This is to prevent false catches and has been optimized through-out the years to reduce false catches to a minimum while keeping the match rates high.

Read more: https://github.com/kangarko/ChatControl-Pro/wiki/Rules#whitelisting-phrases
