### ISSUE TITLE
Cannot properly spy PMs

### ISSUE THREAD

**Issue by oflords** [kangarko/ChatControl-Pro#712]
When socialspy is active, PMs don't get formatted into the way they should in the settings.yml.

Instead of using "Format_PM: "&8[&5SPY&8] &7[{player}] -> [{receiver}]: &7{message}"" it uses "Format: "&8[&5SPY&8] &7{player}: &7{message}""

This is really annoying. I would recommend adding a section called PM_Command_List to go along with Command_List to fix this issue.

**Comment by kangarko** [comment]
Hello,

I am sorry but at present the Format_PM is only applied for the /reply command. Other commands are handled for the standard spy format.
