### ISSUE TITLE
Error: AsyncPlayerChatEvent to ChatControl v7.8.10

### ISSUE THREAD

**Issue by QualityNodeNet** [kangarko/ChatControl-Pro#715]
01.05 05:22:09 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v7.8.10
01.05 05:22:09 [Server] INFO java.lang.NullPointerException: null
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .bi.const(SourceFile:54) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .bi.const(SourceFile:38) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .bi.const(SourceFile:34) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .bl.const(SourceFile:527) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .bl.const(SourceFile:444) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .bl.const(SourceFile:281) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .ba.const(SourceFile:214) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .ba.const(SourceFile:51) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .ba.const(SourceFile:33) ~[?:?]
01.05 05:22:09 [Server] INFO at me.kangarko.chatcontrol.final. .coM5.execute(SourceFile:26) ~[?:?]
01.05 05:22:09 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1386) [TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1301) [TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [TacoSpigot-latest.jar:git-TacoSpigot-"fe7806b0"]
01.05 05:22:09 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
01.05 05:22:09 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
01.05 05:22:09 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
01.05 05:22:09 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
01.05 05:22:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by kangarko** [comment]
Thanks, that'll be fixed :)
