### ISSUE TITLE
Link feature

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#716]
Requested the same thing to dev of cmi. Essentially, this feature uses regex to catch urls. It then replaces the url with a "[link]" which is ofcourse changeable in the locale. When you hover over the link its tells you the url. When you click the "[link]" it takes you to the website that was linked. If you plan to add this, ensure that it also shows the link in the console instead of "[link]" when a user chats.

**Comment by kangarko** [comment]
Hello,

it is unfortunate but adding clickable elements it's not possible with the current system at all, and I don't have time resources to majorly rewrite rules atm. Thank you for your understanding.
