### ISSUE TITLE
[7.8.10] Chatcontrol timings

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#718]
I noticed chatcontrol is pretty haavy on the hub and all the server, dropping it around 19.40 tps (i know but i feel it need some better performance)
https://timings.aikar.co/?id=cdbac6677e324e8db4f90745f72cceea

**Comment by xion87** [comment]
Recording now a nice java report so you you can investigate

**Comment by xion87** [comment]
Here i recorded 15 minutes
[flight_recorder--2018-05-03-14-11-11.zip](https://github.com/kangarko/ChatControl-Pro/files/1972106/flight_recorder--2018-05-03-14-11-11.zip)

**Comment by xion87** [comment]
tps go to 6 today in one of my hub
https://timings.aikar.co/?id=5ba62f0d92b748b08c924fbcddbf8de7
chatcontrol seem to be the cause

**Comment by AmazedMender16** [comment]
@xion87 is the issue still not resolved on 7.8.11?

**Comment by kangarko** [comment]
I am on it, should release a fix tomorrow evening. Thank you for your patience and for providing the dump files.

**Comment by kangarko** [comment]
Closing, the latest version had fixed a severe race condition that caused an infinite loop when checking if the player had /spy enabled, flooding the server over time. This bug occured some time ago so downgrading wouldn't help. I apology for this and it is now resolved.
