### ISSUE TITLE
Random Messages Is Throwing An Exception and Not Functioning

### ISSUE THREAD

**Issue by locke-d** [kangarko/ChatControl-Pro#72]
When setting the Broadcaster to Mode 2 I am getting an exception.

settings.yml: http://pastebin.com/pr6FdaDN
messages.yml: http://pastebin.com/vmMuvRzy - note i have since changed the value back but if you put it as 2 then it will fail
error: http://pastebin.com/qYMxG0jZ

**Comment by Sikatsu** [comment]
Same bug here.

**Comment by kangarko** [comment]
Sorry I cannot test from such a paste. Use pastebin.com to upload 

a) The error message
b) messages.yml file

**Comment by locke-d** [comment]
settings.yml: http://pastebin.com/pr6FdaDN
messages.yml: http://pastebin.com/vmMuvRzy    - note i have since changed the value back but if you put it as 2 then it will fail
error: http://pastebin.com/qYMxG0jZ

**Comment by kangarko** [comment]
Broadcaster issues were fixes as of 7.0.5

**Comment by locke-d** [comment]
Thank you much for taking care of this issue.
