### ISSUE TITLE
[7.8.10] Mysql fail to load

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#720]
https://pastebin.com/U3yTFPHw
https://pastebin.com/yCsNUHYV

**Comment by kangarko** [comment]
Hello,

I donňt want to seem ignorant, but it seems that CHC is not the cause of the issue as it got that "Unexpected token END OF FILE at position 0" from parser, and your MySQL data has {} (nothing) in Points column for that plugin (please verify!)

I have silenced this error as I believe the parser library got updated and it does not allow empty values to be parsed.

**Comment by kangarko** [comment]
We can continue the discussion below.

**Comment by xion87** [comment]
Here there is the row of BudinoBlu (is my builder)
![image](https://user-images.githubusercontent.com/3611852/39662832-5ac5a89e-5068-11e8-9a49-9c42f9da6eff.png)

**Comment by kangarko** [comment]
I see, thanks. He has no warning points. The currently latest version should have that error message solved, please correct me if I am wrong.
