### ISSUE TITLE
[7.8.10] Checkers unders "rules" don't work on channels

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#723]
I have merged two channels into one of two hub, now people can spam any server ip, or regex codes (that was blocked if used without channels).
I noticed swear antiblock work fine, only the folder rules don't work on these channels

**Comment by kangarko** [comment]
I will get back to this once I receive the files I mentioned https://github.com/kangarko/ChatControl-Pro/issues/719

**Comment by kangarko** [comment]
@xion87 can you reproduce under the version 7.8.17 ?

**Comment by kangarko** [comment]
Let's continue this at https://github.com/kangarko/ChatControl-Pro/issues/717

**Comment by xion87** [comment]
i can't test the latest versions on my hub because it stuck the server (as reported on #756 )
