### ISSUE TITLE
Duplicate IP Messages

### ISSUE THREAD

**Issue by sgort87** [kangarko/ChatControl-Pro#725]
For BungeeControlBridge, could you add join-target-duplicate-ip: and switch-to-duplicate-ip: for specifying a different message for players that log in on the same IP as someone logged in on that same server? This would allow people to help differentiate players from alt accounts. A permission to see this message _instead of_ the default may be helpful for users who don't care to use this function.

**Comment by kangarko** [comment]
Hello, I am sorry but at present I don't plan on adding this feature. I appreciate your suggestion.
