### ISSUE TITLE
Discord Join/Leave/Switch

### ISSUE THREAD

**Issue by sgort87** [kangarko/ChatControl-Pro#726]
Could you add a section in the Spigot settings file to specify each message sent to Discord for Join, Leave, and Switch?

**Comment by sgort87** [comment]
Also duplicate IP join is you add #725

**Comment by kangarko** [comment]
I am sorry, but BungeeControlBridge does not support Discord because DiscordSRV does not support Bungee: https://github.com/Scarsz/DiscordSRV/issues/34

**Comment by sgort87** [comment]
Oh right, it's handled by BungeeControlBridge. Well the next DiscordSRV update is a big one, and bungee is a major feature of it, so you may want to keep this on the back burner instead of closing.
