### ISSUE TITLE
MOTD JSON error v7.8.6

### ISSUE THREAD

**Issue by Jast3r** [kangarko/ChatControl-Pro#728]
I want to use the follwoing tellraw JSON message as my MOTD:
/tellraw @p ["",{"text":"You can use ","color":"gold"},{"text":"/day","bold":true,"color":"yellow","clickEvent":{"action":"run_command","value":"/day"},"hoverEvent":{"action":"show_text","value":"Click to vote for day time"}},{"text":" and ","color":"gold"},{"text":"/night","bold":true,"color":"yellow","clickEvent":{"action":"run_command","value":"/night"},"hoverEvent":{"action":"show_text","value":"Click to vote for night time"}},{"text":" to vote for day/night time!\nYou can only do this once every 10 min tho!","color":"gold"}]

Now when i try to do this the first method specified [here](https://github.com/kangarko/ChatControl-Pro/wiki/JSON) I can get the hello world message to work, But with the second method, The Plugin crashes and give me a 'Malformed YAML file settings.yml' error message

https://pastebin.com/cLhx78Di

Now, i can try to get it to work with the first method, which gives me this:

https://pastebin.com/GPMRPjQ1

It gives no output.

Now, is the second method broken? Does the Motd JSON not support the "hoverEvent"? I'm not sure what is going on here, and the logs tell me little to nothing,. And i did find a previous issue on the Spigot forums but that was about the announcer, and your answer there did not help me

Thx in advance

**Comment by kangarko** [comment]
I have fixed that, thank you for reporting.

![a](https://i.imgur.com/lqSW0RD.png)

But you had an error on the second line (use http://json.parser.online.fr/ to check), so I removed a part of it.
