### ISSUE TITLE
[v.7.8.11] DiscordSRV hook not working properly again

### ISSUE THREAD

**Issue by le0-minelandeu** [kangarko/ChatControl-Pro#729]
Hello,

you haven't heard from me for a time. So, after few updates, the DiscordSRV hook is not working properly. The messages from game are sent to the right discord channel but from discord to game is sent to global chat.

This time, we are using only default Global_Chat and Admin_Chat, so we don't use the channels.yml feature for simplicity. In settings.yml, there is an option to set discord chat, but it doesn't work with the latest version of DiscordSRV and I don't want to use old version of ChatControl because it worked. 

Thanks (as always) for you time :)

Hodně štěstí!

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/1976940/ChatControl.zip)

**Comment by kangarko** [comment]
@le0-minelandeu sorry for getting late back to you, can you please test on the next release?

**Comment by le0-minelandeu** [comment]
It looks like it wasn't fixed at all. No progress "in game".

**Comment by kangarko** [comment]
I apology. Will do more investigation in 36h.

**Comment by kangarko** [comment]
It should work now, sorry for the delay was off the country :)

I noticed that the Discord integration was dependend on channels, so I moved the admin part outside of it. In then next bigger update I will include full DiscordSRV support for interactive chat without channels.
