### ISSUE TITLE
Error occurred while enabling ChatControl v7.0.3 (PaperSpigot-1.7.10)

### ISSUE THREAD

**Issue by md79** [kangarko/ChatControl-Pro#73]
Logs from console: http://hastebin.com/ujapadapak.md

**Comment by kangarko** [comment]
Please upload to pastebin.com your settings.yml file and messages.yml file

**Comment by md79** [comment]
I nothing changed in configuration of plugin. Simply I copied the plugin to FTP and I start the server.

**Comment by kangarko** [comment]
Please test against 7.0.5 and re-paste the error when it occurs again.

**Comment by md79** [comment]
Thanks! Now everything works!
