### ISSUE TITLE
Is chatcontrol doing this one?   java.io.NotSerializableException: org.bukkit.Color

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#731]
https://pastebin.com/KXiaWnLb

**Comment by kangarko** [comment]
No, it's CoreProtect, see the stack trace from top to bottom you'll see it.

**Comment by mrcoffee1026** [comment]
thanks i'm not sure how i missed that

**Comment by kangarko** [comment]
Sure, if anything pops up, I will answer :)
