### ISSUE TITLE
ChatControl | Rules and config problem

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#735]
Hello,
I've been using ChatControl for a long time, but recently there was a problem:

I noticed that the Delay to send messages and / or commands is disabled. The rules and the words censored too.

Also, the / g (chc g) and / tell commands are also disabled

How can I solve? Thank you

**Comment by kangarko** [comment]
Hello, please post me your settings.yml.

What happens when you do /chc g ? Nothing? Any error? Any message you get?

**Comment by kangarko** [comment]
Also, what is your MC version and plugin version?

**Comment by FedericoGB25** [comment]
Solved, I did not realize it was my problem.

Sorry and thanks
