### ISSUE TITLE
Tab Complete

### ISSUE THREAD

**Issue by Linebeck** [kangarko/ChatControl-Pro#739]
My config is here:

Packets:
  Enabled: true
  Tab_Complete:
    Hide_Vanished_Players:
      Enabled: true
      Maximum_Length: 20
    Disable: false
    Disable_Only_In_Commands: true
    Allow_When_Message_Has_Space: false
    Allow_When_Length_Above: 0

I have it set to Disable_Only_In_Commands to true, however if a player who isn't a admin etc joins, they can do "/" and tab to see all of my plugins.

Any ideas on what it could be?

I am using Spigot 1.12
ChatControl version 7.8.12

**Comment by kangarko** [comment]
Set Packets.Tab_Complete.Disable to true as well.
