### ISSUE TITLE
MOTD broken after latest update.

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#741]
After the update, this is what my MOTD looks like: http://prntscr.com/jhn1xv

**Comment by kangarko** [comment]
Please post your MotD.

**Comment by Sikatsu** [comment]
I updated it using some other github issue here. Seems the old method I
used doesn't work no longer.

Op wo 16 mei 2018 om 14:00 schreef kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
I assume it works now, closing.
