### ISSUE TITLE
[7.8.11] Suggestion: allow bungee channels to be runned without chatcontrol

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#743]
I would like to have this feature, the channel like admin chat, global to be used in server without chatcontrol, this can be really usefull for example spongeforge server and write and read  on these chat (logically you will need the permission and you can only write/read these chat)

**Comment by kangarko** [comment]
I am very sorry but I don't plan to make another chat-related plugin or to separate channels at the moment. Thank you for your understanding.
