### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by UnrealisticBeing** [kangarko/ChatControl-Pro#744]
I can't figure out if I'm doing something wrong, but I'm resorting to this so... please help.
I am trying to set up chat formatting with chatcontrol, and I set up all of the formats but this keeps happening: 
![](https://unrealisticbeing.citrusmc.net/source/275d071387f4d951120c81551d0c02ed.png)
Now, I figured it would be something with my ranks set up and inheritance, but that doesn't make sense because my inheritance for that rank doesn't include half of those formats... but regardless I don't understand how a simple permissions mixup would lead to it printing like that, it's just so bizarre.

I have referred to the documentation on formatting but there's nothing there that looks like it would help me, and on the same note I was hoping I could help redoing that documentation... as it's outdated and very confusing.

Here's my formatting.yml: https://pastebin.com/1bfXYzWs

**Comment by UnrealisticBeing** [comment]
Sorry, for the most part I figured this issue out, I'll get back to this with a detailed explanation of what I did wrong for reference to others

**Comment by kangarko** [comment]
Sure, you can just post it below :)
