### ISSUE TITLE
Cannot Cancel Chat Event

### ISSUE THREAD

**Issue by sgort87** [kangarko/ChatControl-Pro#745]
I hadn't noticed until recently that I can no longer cancel chat event from the Skript plugin since switching to the Pro version. Is there some way to allow other plugins to intercept chat?

**Comment by kangarko** [comment]
You can try messing around with Listener_Priority.Formatter (set it to LOWEST or HIGHEST or MONITOR), and in the next version it will be renamed to Listener_Priority.Chat.

**Comment by sgort87** [comment]
Just back from a trip and gave this a try with no luck. The discord message properly cancels in all Listener_Priority.Chat conditions, but still shows in game.

**Comment by kangarko** [comment]
@sgort87 I recently split the Chat priority to Formatter and Checker. Try playing with Formatter to see if any combination works. Restart after each change. Thanks.
