### ISSUE TITLE
ChatControl won't override "/w"

### ISSUE THREAD

**Issue by Aerocet** [kangarko/ChatControl-Pro#748]
```
Private_Messages:
  Aliases: 
    Tell: [tell, w, msg, t, whisper]
```

Adding "w" to this list does not actually work. /w still references the default Mineraft whisper behavior.

**Comment by Aerocet** [comment]
Adding 
```
aliases:
  w:
  - []

```
to commands.yml in server directory fixes this.

**Comment by kangarko** [comment]
Closing, thanks for providing the solution.

If you have Towny, we could not unregister the /w because of the /t command, hence you had to workaround it that way.
