### ISSUE TITLE
java.sql.SQLException: Operation not allowed

### ISSUE THREAD

**Issue by Splashins** [kangarko/ChatControl-Pro#753]
> [15:49:35 WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
> [15:49:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
> [15:49:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
> [15:49:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
> [15:49:35 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
> [15:49:35 WARN]:        at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
> [15:49:35 WARN]:        at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6288)
> [15:49:35 WARN]:        at me.kangarko.chatcontrol.final. .bh.const(SourceFile:268)
> [15:49:35 WARN]:        at me.kangarko.chatcontrol.final. .bh.const(SourceFile:211)
> [15:49:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
> [15:49:35 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
> [15:49:35 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [15:49:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:49:35 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:49:35 WARN]:        at java.lang.Thread.run(Thread.java:748)

Version - 7.8.15

**Comment by kangarko** [comment]
Thanks for reporting, will be solved withing a 1 hour.
