### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by FedericoGB25** [kangarko/ChatControl-Pro#754]
Hi, I just updated ChatControl to latest version:
I have this error on the player join/quit event:

https://hastebin.com/afijofovug.md

How can I solve? Thanks ^^

**Comment by x1p** [comment]
Same as #752 & #753 

We are all still waiting for the fix.

**Comment by FedericoGB25** [comment]
I didn't read, 
Sry dx

**Comment by kangarko** [comment]
Will be fixed now.
