### ISSUE TITLE
[7.8.17] This release stuck certain server

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#756]
I noticed this release stuck the server (no error crash or logs)
https://gist.github.com/xion87/aed030435482ca05522bd64448305f45
The servers become unresponsive and player can't join

It stucked all my hubs and kitpvp server (other server seem to work fine) and i resolved only with the downgrade of the plugin on these server

**Comment by kangarko** [comment]
What's your IG on Spigot?

**Comment by kangarko** [comment]
Also set "Debug" to [data, mysql] just to be sure it's not that. Honestly from that log I cannot tell the reason and (so far) you're the only one reporting this, but I will investigate.

**Comment by kangarko** [comment]
PM'd.
