### ISSUE TITLE
JSON Join messages

### ISSUE THREAD

**Issue by TheWranger** [kangarko/ChatControl-Pro#758]
I'm trying to create JSON style join messages but they don't seem to be registering.
This is what `[JSON] {"text": "Hello World"}` comes out as in-game:
![image](https://user-images.githubusercontent.com/24642838/40601464-b58f083c-6298-11e8-91e2-6c5743d5cd72.png)
Config section (that I was using to test json join messages):
  Conditions: 
    #
    # The name if the condition set does not matter.
    # 
    staff_message: 
      #
      # Permission player must have for messages below when they join.
      #
      Permission: "chatcontrol.joinmessage.staff"
      
      Message: '[JSON] {"text": "Hello world"}'

What am I doing wrong here?

**Comment by kangarko** [comment]
Fixed.
