### ISSUE TITLE
Channel switching...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#760]
It's really sad that I can't figure this out at all.. but I"m about to implement channels on my server and I can't sort out one of the simplest things which should be /channel switch... which I take it to be a command to do something like this... being a user with permission to * it has joined me to every channel including the admin channel... which is sorta ok but every time I type I do not want to write to all 3-5 channels.  So it seems to me I should be able to do something like... /ch switch admin read <-- to switch to read mode.  Except it just says "You can only switch if you are already joined to a channel"... except, I AM Already joined to ALL of the channels.  To experiment, I left several and tried switching from ones I was joined in to ones I was not... or switch from ones I was joined in to ones I was also joined in, that message displays under EVERY condition so it seems to me this command works exactly NOT AT ALL or I have no comprehension as to what it is supposed to do.  It seems to me it should be allowing me to switch modes between write/read/spy for a channel I am in without leaving and rejoining that channel, but it will not allow me to do that.  Let me know how to make this work or what I need to be doing instead, thanks!

**Comment by kangarko** [comment]
Apologies for getting late back to you.

 Yes, having the "*" permission will join you to all channels. To prevent this, give yourself negative permissions as per https://github.com/kangarko/ChatControl-Pro/wiki/Channels#auto-join

I apologies for the outdated switch message, it should say "You can only switch if you are exactly in one chat channel", that is now fixed, however, this feature remains.

If you need more clarification please let me know.

**Comment by mrcoffee1026** [comment]
Alright that makes some more sense now... I'll have to double check though since I Thought I got the message while in only one channel at least once.  Is there another command or a simple way of switching from "read" to "write" mode without leaving and rejoining the channel, because I'm not seeing a way to do that (I'd intend to have all staff in "read" in all channels including #admin, but then they'd want to switch to "write" mode without leaving the channels and missing things).

**Comment by kangarko** [comment]
Hey,

there is currently no way to do it natively, but you can create a command alias in [commands.yml](New / Added an option in messages.yml to hide join, quit and death messages for vanished players (true by default).) file that will run the two: leave and join commands.

Let me know how it goes and if you have any questions.

**Comment by mrcoffee1026** [comment]
I feel like I REALLY NEED a command to be able to switch modes for the channels I'm currently in.  I don't see how an alias would be of much of any benefit here as I'd have to make an alias for every mode (spy|read|write) for every channel I have and would need to recall that stuff on the fly to rejoin the channel I'm in or need some ridiculous scripting to determine what channel I'm in and what mode I currently have for that channel... and in all of those cases... chat control knows this information and should just be able to switch my mode without making me rejoin the channel... I shouldn't have to package that information up and serve it up to minecraft basic commands and write some customized alias that borrows placeholders and javascript to pull off.  Heck just alter the "switch" command to allow it to switch the mode of a channel you're in, that'd make the most amount of sense here.  (/ch switch standard read, for example).  Anway that's my suggestion, but not having that I have no idea where to begin with trying to make aliases since I have no method - that I am aware of - of letting spigot know what channel I'm in and what mode I have in that channel, that's going to make for... with 4 channels at 3 possible modes each I'd need a minimum of 12 aliases, none of which I'm likely to be able reference with any agility.

I believe there should be a simple setting here to just disable join/leave commands from the channels altogether.  It's sorta alright getting that notice... but since people will likely want to read 2 channels and write in one... it's incessantly spammy all the joins and leaves.  And I don't need staff only being hidden when they're in v they should just be able to peak in channels without letting people know.  That was a good idea, but my better one is... hey, players can list who is in the channel if they want to and find out that way, I don't think anyone needs it echoed to their screen everytime they leave a channel... rejoin as read and leave and rejoin the main channel to talk to "everyone" once again, they aren't trying to be that noisy, they're just wanting to keep track of what's happening in more than one place.  By making it so spammy, people aren't all that likely to even use the channels.

Anyway, those are my thoughts so far, let me know what yours are, it might alter how I deal with this going forward.

**Comment by mrcoffee1026** [comment]
ok there was a simple setting for that though i had to find that locale file area to delete the lines there too.  So I guess this is all resolved so never mind.  Thanks!
