### ISSUE TITLE
Anti Swear

### ISSUE THREAD

**Issue by digishield** [kangarko/ChatControl-Pro#762]
Ahoj,

Snad neporuším nějaká pravidla, když budu psát česky?! Ono to možná bude i lepší, protože problém se týká pravidel anti swear. Nějak se mi nedaří aby to bralo český a slovenský nadávky? Má to co dělat s prioritou? Mám jí teď na HIGHEST protože jinak to dělá neplechu s DiscordSRV - jakmile je to na nižší tak to přestane psát chat jak do roomky na discordu tak do konzole. Nebo nevím kde dělám chybu.

Každopádně je to divný. Když jsem přes in-game příkaz /chc addrule swear přidal nějaký slova, který obsahujou háčky a čárky tak je do chatu stejně pustí :( 

Omlouvám se za vulgárnosti, ale jinak nevim jak to udělat 😄 Příklad: Píča ... tak pravidlo se přidá úspěšně a i po reloadu nebo restartu se slovo do chatu propustí. 

Ale dneska třeba jsem měl na serveru nějaký trolly, kteří se snažili regnout s nickem obsahující tohle slovo a zablokovalo je to. Takže tomu nerozumím, kde je chyba?

Nebo to nebere naše a vaše nadávky? 

Předem díky za odpověď

digi

**Comment by digishield** [comment]
Ahoj,

Omlouvám se, ale přesouval jsem server na nový hosting a poslední dva dny byly docela náročný na čas. Zjistil jsem, že to nebere jen slova s háčky - č, ě, š, ž ... atd. 

[rules.txt](https://github.com/kangarko/ChatControl-Pro/files/2070405/rules.txt) přikládám.

Checker a Formatter mám nastaveno tak jak si psal a žádný jiný plugin na chat nemám, pouze ten tvůj.

S pozdravem

digi

**Comment by kangarko** [comment]
Skús nastaviť Anti_Spam.Similarity_Check.Ignore_Special_Characters na false v settings.yml a tiež Translate_Diacritical_Marks v tom istom súbore na false a otestuj znova.

**Comment by digishield** [comment]
Ou! Luxus! Funguje! Naprosto super. Tak teď už nebudou mít šanci.

Díky ti moc! 

Měj se hezky.

digi

**Comment by kangarko** [comment]
Nech sa darí :)
