### ISSUE TITLE
Formatting issues with "then replace"

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#764]
This:
```yaml
match \bdis\b
then replace this
```
Removes chatcolours. Is there a way to prevent it from changing the colour? 

To reproduce, use:  `&cdis` in chat.

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#rules-remove-colors-from-the-chat-message
