### ISSUE TITLE
Error in commands.txt 

### ISSUE THREAD

**Issue by Swigglez** [kangarko/ChatControl-Pro#765]
We are having a error on my server where when players exectute /rules it is saying 

> [19:49:01 INFO]: *--------- ChatControl rule match on Beefaroo --------- ID UNSET
> [19:49:01 INFO]: MATCH: ^/rules
> [19:49:01 INFO]: CATCH: /rules
> [19:49:01 INFO]: Original message cancelled.
> [19:49:01 INFO]: Invalid json: Unterminated object at line 1 column 1983 path $[53].clickEvent

On my server we setup our rules in the commands.txt file is there something wrong with my config or is this a error?

Here is my commands.txt config 
https://pastebin.com/2t4Fj1g4

**Comment by kangarko** [comment]
I am sorry, that looks like a JSON syntax error that is not reflected in validator (https://jsonlint.com/) but only in game.

Anyways, I can make it so you can use formats from formatting.yml to display as messages, would that help?

**Comment by Swigglez** [comment]
We eventually got it thanks though
