### ISSUE TITLE
Delay join message a few ticks to gather player displayname data.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#769]
RE: https://github.com/kangarko/ChatControl-Pro/issues/757#issuecomment-394991020

ChatControlPro v7.8.24
Paper dev 1441 (Spigot 1.12.2)

@kangarko The Join message is being sent before it can get the player's full displayname changes - i.e. any nicknames and colors set by the person's primary rank group. It displays their name white and without any nickname.

Would it be possible to delay the join message a couple ticks until all prefix / display_name data is registered on the player? Essential's join message does not have this issue when players login, only ChatControlPro does.

**Comment by kangarko** [comment]
Do not double-post please, I reply to all messages roughly at the same time.
