### ISSUE TITLE
CC-pro integration to BAT[bungee admin tools]

### ISSUE THREAD

**Issue by econowill** [kangarko/ChatControl-Pro#77]
- bungee admin tools [link](https://www.spigotmc.org/resources/bungee-admin-tools-basics-edition.444/)

I want to integrate my server's cc-pro to BAT.
For example, if harassing others, they take their punishment by mute, temp ban or etc from BAT.

But, cc-pro seems to be running punishment command macro by Bukkit/spigot command
So, is there any configuration example or help for cc-pro send bungee command for BAT?

**Comment by kangarko** [comment]
Please try using bukkit alias system when running commands:
You can use command '/? aliases' to lookup for the alias of that plugin. For instance, the command /minecraft:me would run me command from vanilla server and /essentials:me from Essentials. You need to use the prefix from your plugin alongside with the actual command, for example:

match XY
then console thatplugin:ban {player}

**Comment by econowill** [comment]
It doesn't works for me. Bukkit console can run only bukkit commands, can not run Bungee commands in Bukkit console.

However, I found some bungee integration configs. 

in rules.txt
# then bungeeconsole <command|command2|command3> (Commands sent to be executed on BungeeCord. Divide multiple commands by |)

and handler.yml
  # A list of commands to be executed on Bungee. You need to have bungee support enabled in settings.yml and an additional plugin on bungee.
  #Execute_Bungee_Commands:
  #  - alert The {player} has violated a rule on {server}!

So i tried these.
>at handler.yml
 swear:
  Bypass_With_Permission: "chatcontrol.bypass.swear"
  Ignored_In_Commands:
    - // # WorldEdit
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
  **Execute_Bungee_commands:
    - alert {player} is swearing!

Also tried at rules.txt like your comment.
> match bungeetest
then bungeeconsole alert {player} is testing ChatControl

These are not working. and i installed ControlBridge.jar in Bungee proxy.

**Comment by kangarko** [comment]
Have you enabled BungeeCords.Enabled in settings.yml in each bukkit server?

**Comment by econowill** [comment]
Thanks! It Finally Working!
