### ISSUE TITLE
Admin and party chat issues (mcmmo compatibility)

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#770]
When you write something in the adminchat or partychat it will also write it to the normal chat for everyone to see. This seems to be an issue since one of the latest ChatControl versions.

As you can see: http://prntscr.com/jsi14l

**Comment by kangarko** [comment]
Hey,

the priority system has been changed, twice. Have you tried playing with Listener_Priority.Formatter (it was removed and then re-added, so the value is reset) ? Try LOWEST, HIGH, HIGHEST or even MONITOR.

**Comment by Sikatsu** [comment]
That solved the issue.

**Comment by kangarko** [comment]
@Sikatsu What is the priority you use? Just for reference to put it in the Wiki ;)
