### ISSUE TITLE
Using JSON in chat formatting

### ISSUE THREAD

**Issue by Kolgrath** [kangarko/ChatControl-Pro#771]
Not sure if this is possible. The JSON wiki page didn't specifically discuss chat formatting.

What I'm trying to do:
The chat format uses the player's nickname. However when someone hovers their mouse over the nickname it will display their IGN.

For example
[Owner] Kollywood > Hey what's up guys?
When I hover my mouse over Kollywood I want to see that the realname is Kolgrath. Bonus points if I can click it and send a message to Kolgrath instead of Kollywood because that only has been working if we're on the same instance of Spigot.

This is the part of my formatting.yml I'm trying to change:

  Bungee_Chat:  
    Everything: 
      Message: "{pl_prefix}{nick} &7>&f {message}"

Thanks for your consideration. I love this plugin. Probably the best money I've ever spent on a plugin.

**Comment by kangarko** [comment]
Hello and thank you for your feedback!

In ChatControl, you can edit your formats as simply as typing them directly in the formatting.yml file.

The Bungee_Chat format has only one part, "Everything", that literally contains all parts together without any JSON.

The way you add JSON is to split the message into components, in your case "Prefix", "Player", "The_Rest", and add click / hover events as appropriate.

Please see this example of Chat format as a reference point (that format is present as one of defaults in formatting.yml). You can reuse 90% of the code, except that {player} should be replaced with {nick} to get the user's nickname.

<img width="649" alt="skjermbilde 2018-06-14 kl 05 57 14" src="https://user-images.githubusercontent.com/1918426/41390846-cf4fd542-6f97-11e8-9f24-75d7dde004e8.png">

If you have any more questions, please drop them below (I am closing this but still will get notified).
Thank you.

**Comment by Kolgrath** [comment]
Just wanted to follow up in case anyone finds this via a search engine... the instructions provided here worked perfectly. Thank you!

**Comment by kangarko** [comment]
Thanks, I included a link to this in the Wiki as well.
