### ISSUE TITLE
Chat formatting groups broke with 7.8.25.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#772]
ChatControlPro v7.8.25
Paper dev 1448 (Spigot 1.12.2)

After updating from ChatControlPro v7.8.24 to 7.8.25, all my chat formats no longer seem to work in-game.

**Comment by mibby** [comment]
Sorry, ignore. ArcadeGames plugin update decided to break chat formatting.

**Comment by Sprungente** [comment]
Please reopen it. I contacted Fr33stylerRO to see and check up the issue.

**Comment by Sprungente** [comment]
let is close, it was fixed with the last update :P
