### ISSUE TITLE
Option to disable vanish hooking for join/quit messages.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#773]
ChatControlPro v7.8.25
Paper dev 1448 (Spigot 1.12.2)

ChatControlPro v7.6.15 added vanish support for join and quit messages. However, it seems to be forced on so if players login vanished, they do not get a join message. Would it be possible to add an option to disable the hooking so I can continue to force guests vanished but still have a join message for them?

Using VanishNoPacket for vanish plugin. Essential's join message didn't have this problem with Essential's hook disabled in the VanishNoPacket settings.

**Comment by kangarko** [comment]
You're right, that WAS hardcoded and is now added as a toggle in messages.yml :)
