### ISSUE TITLE
Random players able to see a custom channel without having the permission node

### ISSUE THREAD

**Issue by Kolgrath** [kangarko/ChatControl-Pro#774]
We're having an issue where random players are able to see a custom channel they don't have permission for.

We created called **admin_chan** (not to be confused with the built in Admin chat which seems to work fine. We use that for all staff, and the custom channel is supposed to be for admins with the * permission only. 

It's only a handful of players but I can't figure out how ChatControl is giving them access randomly to the channel when they shouldn't have permission in the first place.

All of the admins can see the channel fine because they have the * node. 
Nobody has been given the permission node since * on admins make it unnecessary. 

I'm not even sure how to track this since there's no error involved, it just randomly throws a player into the **admin_chan** channel without rhyme or reason. Maybe 2-3 times a day. 

We're using MySQL to keep track of player chat settings. Could this be part of the problem?  Just scratching my head all around on this one. I don't know what I can do to even trace this since it's so random.

Is there something else I should be doing to ensure the channel can't be joined and is absolutely private?

**Comment by kangarko** [comment]
Hello,

I apologies you have issues. The best and the fastest way of solving complex issues like this, is that you ZIP me your entire ChatControl folder and attach it to this window (make sure to remove MySQL information).

In addition, I wonder about the following:

1. What permission plugin do you use? Perhaps you can explicitly give the negative autojoin permission "-chatcontrol.channel.autojoin.admin_chan.*"  (starts with a -).

2. Yes. MySQL has something to do with automatic joining. When it happens, HOW does it happen exactly that the player is "thrown"? Is he thrown when he joins, switches a server (if you have a bungee network) etc.

**Comment by Kolgrath** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/2102407/ChatControl.zip)

1. We are using BungeePerms. We've tried setting the negative permission "-chatcontrol.channel.admin_chan" _(It has since been removed)_ to the default group but I will go back and apply the node you've suggested.  

2. I will have to test this with the next player this happens with and get back to you. What we've observed is shortly after posting a message random players have reported seeing what was sent. /channel list adminchan reveals that they're on the list.

Here are the current permissions our Default group get for ChatControl:

chatcontrol.commands.channels
chatcontrol.commands.channels.list
chatcontrol.commands.channels.leave
chatcontrol.commands.channels.join
chatcontrol.channel.global.join
chatcontrol.channel.global.leave
chatcontrol.channel.global
chatcontrol.notify.globalchat
chatcontrol.commands.calc
chatcontrol.commands.list
chatcontrol.commands.globalchat
chatcontrol.commands.channels.send
chatcontrol.commands.channels.help
chatcontrol.commands.tell
chatcontrol.commands.reply
chatcontrol.notify.whenmentioned
chatcontrol.notify.announcements
chatcontrol.channel.rp
chatcontrol.channel.rp.join.write
chatcontrol.channel.rp.join.read
chatcontrol.channel.rp.leave
chatcontrol.channel.rp.send

**Comment by Kolgrath** [comment]
Is there a command to remove another player from a channel?

**Comment by kangarko** [comment]
@Kolgrath, I apology for the infinite delay. As a compensation, I am offering you one of my premium plugins for free, just contact me on Spigot.

Regarding the issue, I believe I got it solved but, I kindly ask you to set your Debug to "[channel_join]" in the next version and when it happens again just go to the file logs/channel_joins.log and find the line where he joined. It will contain more information so we can track it down.

Lastly, there was no way to really remove a player from a channel until the next version. Use the /channel set command for a channel where the player is already joined, and the command will put him out of the channel.

Best,
kangarko
