### ISSUE TITLE
DiscordSRV & Chatcontrol Pro chanel problem

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#776]
I'n having a problem where the chat of ALL channels in chc go to the main channel on discord on top of going to their own channel. I supplied the below information to the dev of DiscordSRV who said it has to be a CHC problem. I hope someone can assist. 

In Chatcontrol Pro I created 4 channels, english, nederlands, japanese and admin. I also set:
Control_Incoming_Messages: true

In DiscordSRV I set:
Channels: {"english": "channelID1", "nederlands": "channelID2", "japanese": "channelID3", "admin": "channelID4"}

DiscordConsoleChannelId: "channelIDforconsole"

Game commands like restart server and players joining go to the english discord channel
english in game channel goes to the english discord channel
nederlands in game channel goes to the nederlands AND english discord channels
japanese in game channel goes to the japanese AND english discord channels
admin in game channel goes to the admin AND english discord channels

**Comment by kangarko** [comment]
Hello,

this may seem trivial, but I believe you need to set Compatibility.Cancel_Event to true in channel.yml

If you have any questions or it didn't work, please comment below.
