### ISSUE TITLE
Chat filter not work with other language

### ISSUE THREAD

**Issue by econowill** [kangarko/ChatControl-Pro#78]
Chat filter not work with other language. especially Korean.

**Comment by econowill** [comment]
I dont know where to start discuss this problem related with special charactor system.

First of all. Chatcontrol pro works well. But theres some bugs. To understand this, You need to understand Korean language charactor system

The korean use Korean. It is a speaking language. And for writing they use Hangul. One of the most special things is this. Hangul is consisted with seperated part of charactor.

To easy to understand.  Alphabet has A. B. C ... XYZ. And combine this makes word and meaning
But Hangul should combine part of charator before make word.
Hangul has ㄱ ㄴ ㄷ ㄹ and ㅏ ㅑ ㅓ ㅕ
Combine them you get this 가 나 다 라. 갸 냐 댜 랴

Chatcontrol has a bug at this point
Your baby know how to filter ㄱ ㄴ ㄷ ㄹ consisted by one charator. But dont know about combined charator.

**Comment by Scorpionvssub** [comment]
가 나 다 라. 갸 냐 댜 랴 NO idea what that means but  i just tried it and no issues whatsoever

**Comment by econowill** [comment]
in rule.txt has custom rules
> match 안녕
> handle as swear
> 
> match ㅎㅇ
> handle as swear

**Comment by kangarko** [comment]
Hello,

please set **Anti_Spam.Similarity_Check.Ignore_Special_Characters** to false and **Translate_Diacritical_Marks** to false in settings.yml and remove the ## from the rules.

So the the look like:



    match 안녕
    handle as swear

    match ㅎㅇ
    handle as swear

**Comment by econowill** [comment]
Thanks.
I'll try it.
however ## just only inserted to explanation for git

**Comment by econowill** [comment]
Thanks.
It seems solved!
