### ISSUE TITLE
Resets my channels

### ISSUE THREAD

**Issue by Curtis73** [kangarko/ChatControl-Pro#780]
Whenever I'm playing, ChatControl occasionally adds me to all of my channels - even though I do not run any commands.
http://prntscr.com/jvobws
No error is printed in console.

**Comment by kangarko** [comment]
It's probably due to autojoin permissions, which one you have? https://github.com/kangarko/ChatControl-Pro/wiki/Channels#auto-join

**Comment by Curtis73** [comment]
All of them, because I'm opped, it seems.

**Comment by kangarko** [comment]
Give yourself the negative (starting with an -) permission:

`chatcontrol.channel.autojoin.*`
