### ISSUE TITLE
chatcontrol and autme reloaded issue

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl-Pro#782]
I had notice that if in authme I setup email system when players want to change their password the command /verification (code) is blocked by chat control. The thing is that it say that command does not exits. How i know it's chat control issue well when removed the plugin it was 100% fine :). There was no error in the console with is strange.

Mc version: 1.12.2 paperspigot

**Comment by kangarko** [comment]
That's strange, since ChatControl does not remove that command. You can try whitelisting it in handlers.yml:

![a](https://i.imgur.com/Ul6RhFl.png)

And make sure you restart, not /reload, as that can cause issues.

**Comment by arturek1666** [comment]
The problem is that I had add it already before reporting the issue and it's still happening when player types I got this message when typed: [ID UNSET] NICKNAME:verification 40158192

**Comment by kangarko** [comment]
It doesn't seem that it's coming from ChatControl. But have you tried to edit the handlers? There is a chance that we catch it as an ad.

**Comment by arturek1666** [comment]
YEP i add:
`advertisement:
  #
  # Ignore players with a proper permission.
  #
  Bypass_With_Permission: "chatcontrol.bypass.ad"
  #
  # Do not filter ads in the following commands:
  #
  Ignore_Commands: 
    - // # WorldEdit
    - /brush
    - /auction
    - /auc
    - /register
    - /reg
    - /login
    - /l
    - /email
    - /verification
  #
  # Warn the player.`

**Comment by arturek1666** [comment]
I add to swear ignore  as well

**Comment by arturek1666** [comment]
Still same message: 
![wtf](https://user-images.githubusercontent.com/1558228/41527205-4898311c-72de-11e8-9f5c-64c6a84aeaba.png)

**Comment by kangarko** [comment]
It's coming from some rules, please screenshot me your console when that happens, there will be a longer message.

**Comment by arturek1666** [comment]
Ok next time will check properly console this is what it don't likes:
[10:55:07] [Server thread/INFO]: *--------- Rule match (command) for artudituisfake01 --------- ID UNSET
[10:55:07] [Server thread/INFO]: MATCH: ^/ver
[10:55:07] [Server thread/INFO]: CATCH: /verification 119867

**Comment by arturek1666** [comment]
Fixed :) sorry for time wasting if I checked  the console more carefully i would not have to message an issue here ;(
