### ISSUE TITLE
Issue at Start

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/ChatControl-Pro#783]
Hello! i have a problem with ChatControlPro :c 

https://hastebin.com/osusivayap.md

When i start the server the plugin doesn't work :c 

Thanks a lot and good bye!

**Comment by kangarko** [comment]
You have an error somewhere in your rules.

Search files in rules/ for the following and fix that error:
`m+(\W|\d|_)*i+(\W|\d|_)* +(\W|\d|_)*b+(\W|\d|_)*o+(\W|\d|_)*o+(\W|\d|_)*s+(\W|\d|_)*t+(\W|\d|_)*i+(\W|\d|_)*?+(\W|\d|_)*`

**Comment by BlackGamer000** [comment]
Ok Thanks a lot! c:
