### ISSUE TITLE
Custom deathmessage for tamed wolves

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#785]
Could you add the possibility to define custom death-messages for the death of tamed wolves. It would be awesome if you could make a variable for the name of the tamed wolf and for the killer (playername) of the wolf. Player love their pets and having custom death messages would be great.

Happy Holiday!

**Comment by kangarko** [comment]
I am sorry this is not planned at the moment.

**Comment by kangarko** [comment]
But I can leave this open for the future.
