### ISSUE TITLE
Chat Control Pro to Discord channels not working correct

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#789]
I have 4 channels in game and on my Discord server. Talk back and forth between the 4 channels works 100% apart from one big problem. The chat from any channel also goes to the first channel in the list.

Example:
Channel 1 to 1
Channel 2 to 2 and 1
Channel 3 to 3 and 1
Channel 4 to 4 and 1

The whole point of channels is to keep certain chat out of the main channel. In my case Languages and the staff channel. I created an issue with DiscordSRV plugin who says its a Chat Control Pro bug or misconfiguration.

**Comment by kangarko** [comment]
I apology for the big delay. Let's continue on https://github.com/kangarko/ChatControl-Pro/issues/778 as I believe the issues are related.
