### ISSUE TITLE
channel leaving...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#791]
Notice that users are listed in the channel long after they've logged off the server.... shouldn't leaving the server automatically cause them to leave any channels they might have joined while online???  The /ch list <channel> command provides a never endingly growing list of users since it does not... making it virtually impossible to see who is actually in any given channel...

**Comment by kangarko** [comment]
What a discovery, thank you so much for reporting! I apology for the lack of attention when coding that section, I forgot to remove players from channels when they quit. Fixed asap.
