### ISSUE TITLE
need a color clear command

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#793]
For the chat color option /chc color option.... I can't determine where this information is actually stored, it doesn't seem to be being placed in the database.  Anyway, if I have a donor rank (who has this perk) cancel their account, their color would be stuck there, no way for them to change it... and no way for me to do it either.  And I can't /sudo change it since it's done entirely through the GUI.  Please add this!  Thank ya.

**Comment by kangarko** [comment]
Chat color is for now stored in data.db (you can open it with Notepad++).

I added that chat colors and decoration are removed automatically when the player logs in and lack the permissions that are required to set them.
