### ISSUE TITLE
Cannot remove player from admin channel

### ISSUE THREAD

**Issue by Kolgrath** [kangarko/ChatControl-Pro#794]
Running ChatControl-Pro 7.8.26

Recently removed a player from staff. By taking them out of the staff group, that would also remove their access to the chatcontrol.commands.adminchat node. Server has been restarted since that time.
When we do **/channel list admin**, the player who is no longer staff still shows as being in the channel with **(write)** permission. 

Made double sure the player does NOT have permission chatcontrol.commands.adminchat. 
In BungeePerms:
**/bp user PlayersName check chatcontrol.commands.adminchat** returns FALSE.

I can't find a kick command for removing someone from a channel. There has to be a simple way of taking a player out of a channel where they don't belong.

**Comment by kangarko** [comment]
Sorry, there was a bug with /channel list. I fixed that in the next version.
