### ISSUE TITLE
Suggestion: Move Server_Name out from settings.yml

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/ChatControl-Pro#795]
Hi! 
I have multiple server network and it will be much more comfortable for me to type Server_Name once in particular file and then just copying one main settings.yml instead having different settings.yml per each server.
Thanks for considering my request.

**Comment by kangarko** [comment]
Hey,

thank you for the request, I have noted it down but not planning to include it very soon, because most people name their servers uniquely so it makes sense to store it in settings.
