### ISSUE TITLE
Suggestion: /chc ach

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#796]
To my humble opinion staff needs to communicate without censorship. I want to discuss with staff without being corrected. This can be e.g. a chat about what someone said under the *beep*.

So why don't I use the normal bypasses then?
Well, staff itself also needs to talk normally with players and need to be corrected when not appropriate words are used, but without the punishment. Staff needs to be a good example for players. This can be easily created using the bypass points. But among staff, there is no need for a censorship. Sure some chat replacements are usefull, but writing exclusions for every rule with (then replace) with the right ingore is more work.

**Comment by kangarko** [comment]
Thank you for your suggestion.

While I totally see the value in it, the current system is way out of the way of implementing it. Having said that, I am not planning to include it until the next major feature update. Thank you for your understanding.
