### ISSUE TITLE
Hide vanished players from ranged chat

### ISSUE THREAD

**Issue by Rbot48** [kangarko/ChatControl-Pro#798]
Could you please add the possibility to hide vanished players from ranged chat? Right now players can see if there is any staff member around by just typing anything in the local chat.

**Comment by kangarko** [comment]
Great suggestion, I noted it down for implementation!

**Comment by kangarko** [comment]
Added. The message "&6There is nobody within your chat range who may have seen your message." is no longer showed if only vanished players are around.
