### ISSUE TITLE
spigot 1.7-1.8

### ISSUE THREAD

**Issue by mustafamasoodm** [kangarko/ChatControl-Pro#8]
ChatControl-Pro not working on spigot 1.7-1.8 (protocol hack) with bungeemode on. its working fine if u turn off bungeemode.
error on bungeemodeon "java.lang.IllegalArgumentException: BungeeCords requires Spigot 1.7.10 or newer."
spigot: SandmanPlayss

**Comment by kangarko** [comment]
BungeeCords and interactive chat requires some libraries that are only present on Spigot 1.7.10 and newer.
