### ISSUE TITLE
Custom deathmessage for lingering damage potion and damage potions

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#801]
Could you add the possibility to define custom deathmessages for lingering damage potion, at the moment no deathmessage at all appears if somebody dies because of the effect. 
It would be awesome if you could also add deathmessages for dying because of trinking damage potions, at the moment trinking a damage potions just triggers the "pvp x" deathmessages, this is slightly unconvincingly.
Both deathtypes appear more often than one would think because of the enderdragon and because player tend to have fun with weird stuff. So I would be delighted if you could manage to add this!

Reading this probaply in some weeks I hope you had a cool vacation.

**Comment by kangarko** [comment]
Thank you for your suggestion, I noted it down to the roadmap.
