### ISSUE TITLE
Custom deathmessages - disable separate killer message pvp_x

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#802]
This ticket is more a question regarding the custom deathmessages for pvp-action (pvp_x). Is there any particular reason for splitting up the message for the killer and for all other players. It turned out, that the messages broadcastet for all player are way more interesting than the ones the killer gets. So I wonder if I there is any way/if you would build a way to show the same messages to killer and player. I know that I could just use the same deathmessages for the killer and the players, but as there is a random selection killer and player wouldn’t see the same message, which is basically what player request more frequently nowadays.

**Comment by kangarko** [comment]
The reason for split was another user's request. You can just use the same message two places.
