### ISSUE TITLE
chatcontrol.bypass.ignore Not working

### ISSUE THREAD

**Issue by redeye08** [kangarko/ChatControl-Pro#804]
Hello like the title said the chatcontrol.bypass.ignore permission isn't working, you still can't see messages from a player that someone has ignored even if they have the ignore bypass permission.
Both in global and /tell

The permission plugin we use is PermissionsEX running on a spigot server.

The player doing the ignoring has chatcontrol.commands.ignore

**Comment by kangarko** [comment]
Hello,

apology for a late reply. I am not sure if you are using the permission correctly, the permission "chatcontrol.bypass.ignore" enforce sending a message to the player that is ignoring the sender.

**Comment by kangarko** [comment]
Closing, if you still need help, please write below and I get back to you.
