### ISSUE TITLE
How to change chat format

### ISSUE THREAD

**Issue by RixZtha** [kangarko/ChatControl-Pro#805]
ChatControl version:7.8.11
Minecraft version: 1.11.2 and 1.12.2 

I looked up in all files, but I can't find chat format, I have installed it in 2 server, 1 of each version.
In 1.11.2 chat format is Name - Message
whereas in 1.12.2 char format is <name> message
how to add variables like faction name and etc

**Comment by WizzleBear** [comment]
{faction} is the ChatControl Pro placeholder, but I'd suggest using the FactionsUUID placeholders with PlaceholderAPI.

**Comment by kangarko** [comment]
Update your ChatControl, set Enabled to true in formatting.yml and you will find the chat format in that file.

To use more variables, install PlaceholderAPI.
