### ISSUE TITLE
Support for essentials.silentjoin/quit

### ISSUE THREAD

**Issue by WizzleBear** [kangarko/ChatControl-Pro#806]
I am not sure if this has been added, but when I join and have the essentials.silentjoin permission, people see me join, but when I leave they don't see it. I think this has to do with the vanish coming on AFTER ChatControl registers the message.

**Comment by TheWranger** [comment]
I imagine it's because ChatControl is handling the join/leave messages instead of Essentials.
You could set up a ChatControl condition that makes it so that users with a certain permission don't have a join/leave message.

**Comment by kangarko** [comment]
Essentials' permission has nothing to do with us; you need to give the vanished player these as well:

- -chatcontrol.messages.join
- -chatcontrol.messages.quit

Make sure they begin with an "-" to be negative.
