### ISSUE TITLE
Error when editing config.

### ISSUE THREAD

**Issue by MrWardy** [kangarko/ChatControl-Pro#808]
I have an error about a malformed YAML file.
[error.log](https://github.com/kangarko/ChatControl-Pro/files/2168287/error.log)

**Comment by ArtelGG** [comment]
This is a user error.

**Comment by TheWranger** [comment]
I'd put your config through something like codebeautify or yamllint to verify that you haven't broken something.
https://codebeautify.org/yaml-validator

**Comment by kangarko** [comment]
Replace the single quotes in 'Have you joined our discord...' to double quotes: "Have you joined our discord..." and then you can use the single quotes inside of the file.

@TheWranger thank you for help as well!
