### ISSUE TITLE
Configuration translations missing

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Pro#810]
The caps, spam and similarity (there's probably more) messages do not appear to be configurable whatsoever.
Either these messages are hardcoded, are not obviously present in the configuration file(s), or am I just blind?

**Comment by TheWranger** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Localization

**Comment by ArtelGG** [comment]
Thank you.
