### ISSUE TITLE
Tab complete packet refuses to be blocked

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Pro#812]
The tab completion breaks seemingly for no reason. One way I've found to make this occur occasionally is to go from `tab complete = blocked -> make a rule catch -> tab complete = no longer blocked`. Even then that sometimes doesn't work, so I have no idea what's causing it 100% of the time.

Would it be possible to make a manual rule for this?

> P.S: The entire (or large majority of the) configuration file is default aside from a few settings being reduced/increased/disabled.

**EDIT:** It seems I've managed to isolate it. If the following setting (`Packets.Tab_Complete.Allow_When_Length_Above`) is anything other than 0 it will not properly block it.

**Comment by kangarko** [comment]
Hey,

thank you for your feedback. Tab complete section was among the older ones in ChatControl dated back to 2015. I have recoded it to meet latest standards and I am very confident in that it will work as expected now.

This is the section as per the next release:
![a](https://i.imgur.com/xWo4vdL.png)
