### ISSUE TITLE
ASkyBlock TeamChat

### ISSUE THREAD

**Issue by baticag** [kangarko/ChatControl-Pro#814]
TeamChat from ASkyBlock plugin gets flagged as normal chat where filters happen.
I want to make that team chat excluded from ChatControl checks, is that possible and how?

This is how ASkyBlock does this TeamChat:
https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/listeners/ChatListener.java

**Comment by kangarko** [comment]
Sorry that's not possible unless they change the priority in https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/listeners/ChatListener.java#L97 to LOW. Then, you can change the Listener_Priority.Checker to LOWEST in ChatControl so it will come before that plugin.

**Comment by baticag** [comment]
I recompiled ASkyBlock and changed the priority of the listener to LOW, then changed Checker Priority in ChatControl to LOWEST, but still having an issue.

Any other recommendation?

**Comment by kangarko** [comment]
Try the other way around - make the Askyblock listen on NORMAL and put HIGHEST to ChatControl's Listener_Priority.Checker. Restart server after each change in ChatControl.
