### ISSUE TITLE
Request to extend similar message spam

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#818]
Hacked clients have the ability to turn on a annoying parrot function. This means that a player with a hacked client instantly repeats everything a certain player says. This is childish but above all: very annoying!

Can the Anti_Spam.Chat. similarity  function of chatcontrol be extended so every duplicated message of all players will be prevented if the message is exactly the same?
Possible criteria/bypases:
- Only if the similar message is more than a configurable number of characters.
- Except for the whitelisted words.
- Only if within a number of milliseconds

Is this possible to make? Would be nice.
Thanks in advance.

**Comment by kangarko** [comment]
Implemented!
