### ISSUE TITLE
Error when msg another member

### ISSUE THREAD

**Issue by UncleM0** [kangarko/ChatControl-Pro#819]
13.07 20:53:23 [Server] WARN java.lang.IllegalArgumentException: key
13.07 20:53:23 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
13.07 20:53:23 [Server] WARN at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)
13.07 20:53:23 [Server] WARN at me.kangarko.chatcontrol.final. .e.<init>(SourceFile:1109)
13.07 20:53:23 [Server] WARN at me.kangarko.chatcontrol.final. .h.native(SourceFile:862)
13.07 20:53:23 [Server] WARN at me.kangarko.chatcontrol.final. .bB.const(SourceFile:149)
13.07 20:53:23 [Server] WARN at me.kangarko.chatcontrol.final. .this.const(SourceFile:105)
13.07 20:53:23 [Server] WARN at me.kangarko.chatcontrol.final. .prn.onCommand(SourceFile:57)
13.07 20:53:23 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13.07 20:53:23 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
13.07 20:53:23 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
13.07 20:53:23 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13.07 20:53:23 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
13.07 20:53:23 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
13.07 20:53:23 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by kangarko** [comment]
What ChatControl version are you running?

**Comment by kangarko** [comment]
Nevermind, solved. Caused by somehow your /tell message being empty.
