### ISSUE TITLE
Several Questions/issues

### ISSUE THREAD

**Issue by Scorpionvssub** [kangarko/ChatControl-Pro#82]
I was wondering if there was a way to spy on any command performed over bungee, a wildcard basicly like /* or something. Instead of doing 100 types of commands.

also i  have an issue with the server name bit, when joining or switching between servers it says i joined from <Server Name> example Scorp joined from Survival. Which is good

What i cannot figure out is the bungee/<server name> where server name is always unknown?

**Comment by EvilOlaf** [comment]
Hm not sure if this is possible. You can add a rule that matches `^/` and add a notice which will be received by players with proper permission (staff member and so on) but no idea if this would work over Bungee.

Did you install the BungeeBridge for CHC?

**Comment by Scorpionvssub** [comment]
yea i got pro + the bungee bridge which allows me to chat over bungee to other servers notify a server change for a player and broadcasts to all where someone joined or even joined the server, on top of that it tells you which server they came from like: <playert> has left the network to Lobby(Which is the hub but with custom name) or when they leave from prison it says that too so yea i got that installed.


As for the spy i do know how to make it command specificly read over bungee aswell as that it does the rules for swearing over bungee corretly via other servers to those with perms

**Comment by kangarko** [comment]
The spy command cannot read commands issued on bungee, only on the bukkit server. It does, however, include bungee feature so the alert from one server is transferred to all the others.

For setting server name aliases in general usage, configure Server_Name in settings.yml for each server.

If you would like to change server name in the server switch messages, you'll need change it from withing BungeeControlBridge's config.yml:

# Server name aliases used when broadcasting server switch from ChatControl
server-names: 
  lobby: "hub"
  world: "survival"

**Comment by kangarko** [comment]
Closing. Let me know if you have any more questions.
