### ISSUE TITLE
Double prefix when using luckperms.

### ISSUE THREAD

**Issue by MrWardy** [kangarko/ChatControl-Pro#820]
So I fixed this issue, but it's more of a bug report for future users.

I'm using luckperms for my permission plugin, and I setup prefix stacking from this wiki page https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking using the luckperms config. After setting up that and my tracks then assigning myself both my owner and guest role, I ended up getting two Guest prefixes and one Owner prefix for whatever reason. This seemed to be because of the {pl_prefix} placeholder. After switching the placeholder to the luckperms placeholderapi placeholder {luckperms_prefix} it all worked fine.

**Comment by kangarko** [comment]
Thanks! I wrote that note to https://github.com/kangarko/ChatControl-Pro/wiki/Variables
