### ISSUE TITLE
Block Commands

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#821]
can you make to block the execution of the command, bc if only say dont spam, but the command appears, for example like /help, it would spam, ty

**Comment by kangarko** [comment]
See rules/commands.txt.

Here is an example of blocking the command /heal:

```
match ^/(heal)
ignore perm essentials.heal
then warn &cThis command is blocked.
then deny
```

**Comment by dabou0** [comment]
but i dont want to block the command, i want for when the player is spamming commands, to dont execute the command, only say that msg, wait another time to execute this commands, it shows this message but it dont block the command,

**Comment by kangarko** [comment]
You can configure "message delay" in Anti_Spam.Commands.Command_Delay section. Player won't be able to spam commands rapidly but must wait between each time they run one.

ChatControl blocks the command and warns the player, you cannot allow the command to be run and the warn message be sent at the same time.
