### ISSUE TITLE
/ch commands gets interrupted by townys /ch commands

### ISSUE THREAD

**Issue by axemwa** [kangarko/ChatControl-Pro#823]
It's as the title says, townys channel commands are overriding chatcontrols channel commands how do I fix this?

**Comment by kangarko** [comment]
Sorry you can't unless you edit Towny's plugin.yml file inside of its jar. Or you can just stick with /channel command instead.

**Comment by axemwa** [comment]
its ok I edited the alias of townychat now I can use /ch etc

**Comment by kangarko** [comment]
You can configure /channel aliases in Command_Aliases in channels.yml

**Comment by axemwa** [comment]
Yeah I just noticed that yesterday silly me!
