### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bukkit/Particle

### ISSUE THREAD

**Issue by Splashins** [kangarko/ChatControl-Pro#829]
Error - https://hastebin.com/ebejidacax.md
Version - git-PaperSpigot-"4c7641d" (MC: 1.8.8)

**Comment by ArtelGG** [comment]
Duplicate error of #828

**Comment by kangarko** [comment]
Thank you very much for reporting. This is solved in 7.9.2 rev.2 update.
