### ISSUE TITLE
EzPrestige prefixes

### ISSUE THREAD

**Issue by Scorpionvssub** [kangarko/ChatControl-Pro#83]
Does anyone know if chc pro and its bungee channels works with the prefixes created by  EzPrestige i know it works with pex and nicknames but :P

**Comment by kangarko** [comment]
There are multiple solutions for getting a prefix:

a) If you are using Vault alongside with that plugin, you can try using {pl_prefix}, {pl_suffix} and {player} variables.
b) If you are using nicknames from Essentials, use {nick} variables instead of {player} variable.
c) Creating a custom variable in JavaScript. Unfortunately I cannot help you with that.

**Comment by Scorpionvssub** [comment]
EzPrestige i think uses asyncchat to controle those prefixes like i do in survival for boss prefixes that player can earn.

So it doesn't run along with protocollib but just when a player chats

**Comment by Scorpionvssub** [comment]
It does have an API but it doesn't seem like its doing much

**Comment by kangarko** [comment]
Allright, but have you tried {pl_prefix} ? And also check if PlaceholderAPI has support for that, because CHC is compatible with PlaceholderAPI

**Comment by Scorpionvssub** [comment]
It doesn't say if its compatible with placeholderAPI + never tried to work with it as i only have as some plugins require it. The {pl_prefix} apperantly only shows those prefixes recorded by pex not async chats and ontop of that the plugin ezprest only works with essentials setup meaning the {prestige} var is only read by essentials.

**Comment by Scorpionvssub** [comment]
Scratch that, it appears by default to have ezprestige checks. by that i mean ezprestige: false/true just dont know how to implement it

**Comment by kangarko** [comment]
You simply install PlaceholderAPI and follow the installation instructions. Then you enable Variables.Enabled in settings.yml and use the following variables across the plugin:

{ezprestige_prestige}
{ezprestige_prestigetag}
{ezprestige_nextprestige}
{ezprestige_nextprestigetag}

**Comment by Scorpionvssub** [comment]
i don't get this at all :P ive got placeholder and enabled the plugin ezprestige: false to ezprestige: true as in, enabled that. added {ezprestige_prestige} to the chat line, but in settings aint anything to do with variables apart from it saying "go to the var file for variables"

**Comment by kangarko** [comment]
What do you mean by nothing? The variable is just plainly displayed without being replaced? Have you setup the PlaceholderAPI properly? E.g. downloaded that package for ezprestiges

**Comment by Scorpionvssub** [comment]
What i did was: i've had the plugin ezprestige for ages, then i setup chatcontrol to put {ezprestige_prestige} witin the message as u said. THEN in the mean time i also loaded up this...placeholderapi by the same author went into the only file it has and at ezprestige: i switched false to true and  loaded up the server so idk whatever else is needed

**Comment by kangarko** [comment]
Have you downloaded the extension within PlaceholderAPI with the following command?
/papi ecloud download EZPrestige

**Comment by Scorpionvssub** [comment]
Command doesn't excist

**Comment by kangarko** [comment]
I mean this plugin: https://www.spigotmc.org/resources/placeholderapi.6245/
It has those commands I tested yesterday. Update your version.

**Comment by Scorpionvssub** [comment]
Yea i've done this still just shows {ezprestige_prestige}

**Comment by Scorpionvssub** [comment]
Got it :)
 
Just now learned regular users can't see the chats..? is there  permission im missing?
