### ISSUE TITLE
[7.9.1] Chat laggy?

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#832]
Chat seems to be more laggy under 7.9.1
Can this be confirmed?

**Comment by x1p** [comment]
Several messages appear on console
[ChatControl 7.9.1] Rules parse: chat.txt took 509 ms
...
[ChatControl 7.9.1] Rules parse: commands.txt took 561 ms
etc.

**Comment by ArtelGG** [comment]
Could you show us a rule that's being laggy?

**Comment by x1p** [comment]
Everything :)
[09:51:53] [Server thread/INFO]: PlayerXYZ issued server command: /spawn
[09:51:54] [Server thread/INFO]: [ChatControl 7.9.1] Command event took 514 ms

Even when it is not displayed (happens too sometimes) the chat takes about a second to get in game.

I have the feeling that 7.8.29 was much faster and accurate. My rules are not changed.

**Comment by ArtelGG** [comment]
That's not useful at all, if it is an issue with the plugin, debugging needs to be done. I do believe 7.9.1 is broken in many ways (#828) and so is 7.9.0-BETA (#825) I recommend switching to the last stable update you were on until @kangarko comments on these issues.

**Comment by kangarko** [comment]
Pretty much little was changed regarding the chat rendering and sending; this section is unchanged since 7.7.x or something.

@x1p how often that happens? If possible, PM me on Spigot with that rule files and an example messages that trigger them.

I highly recommend you test the new 7.9.3.

**Comment by kangarko** [comment]
Do you have Debug option set to anything?

**Comment by x1p** [comment]
No debug was enabled. Even if the "[ChatControl 7.9.1] whatever event took 514 ms" does not appear it is still markable slower.
Same rules and went back to 7.8.29 and the chat is much more snappy. Chat appears at once.
I will test with latest and let you know.

**Comment by x1p** [comment]
7.9.2 (rev 2) is much better. I would say: like normal.

Anyhow: I will take some time to further optimize my regex coding skills :-)

**Comment by kangarko** [comment]
Oh I see, that was caused by our obfuscator. Obfuscation changes classes and methods into unrecognizable mess, degrading performance in some cases. It took few releases to optimize it. I apology.
