### ISSUE TITLE
Error in console when typing a msg

### ISSUE THREAD

**Issue by UncleM0** [kangarko/ChatControl-Pro#837]
17.07 03:13:26 [Server] INFO [ChatControl 7.9.2] loading component part [Private_Message_Receiver.Everything] took 119 ms
17.07 03:13:26 [Server] INFO [ChatControl 7.9.2] creating component [Private_Message_Receiver] took 121 ms
17.07 03:13:26 [Server] INFO [ChatControl 7.9.2] loading component part [Private_Message_Sender.Everything] took 105 ms
17.07 03:13:26 [Server] INFO [ChatControl 7.9.2] creating component [Private_Message_Sender] took 106 ms
17.07 03:13:26 [Server] WARN java.lang.IllegalArgumentException: key
17.07 03:13:26 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
17.07 03:13:26 [Server] WARN at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)
17.07 03:13:26 [Server] WARN at me.kangarko.chatcontrol.final. .j.<init>(SourceFile:1114)
17.07 03:13:26 [Server] WARN at me.kangarko.chatcontrol.final. .m.native(SourceFile:864)
17.07 03:13:26 [Server] WARN at me.kangarko.chatcontrol.final. .bG.const(SourceFile:151)
17.07 03:13:26 [Server] WARN at me.kangarko.chatcontrol.final. .AUX.const(SourceFile:102)
17.07 03:13:26 [Server] WARN at me.kangarko.chatcontrol.final. .LPT4.onCommand(SourceFile:59)
17.07 03:13:26 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
17.07 03:13:26 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
17.07 03:13:26 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
17.07 03:13:26 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
17.07 03:13:26 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
17.07 03:13:26 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
17.07 03:13:26 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by kangarko** [comment]
Thanks, fixed.
