### ISSUE TITLE
Question about placeholders.

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl-Pro#838]
Hey kangarko,

What is the placeholder for essentials' nickname ? In fact, if we do /nickname dd, only the realname is written in the tchat.
And what is the placeholder for Marriage Master ? 

Thanks,
TheIntelloBox. :D

**Comment by UncleM0** [comment]
Just had this issue. 
    Player: 
      Message: "{player}:"        CHANGE TO    {nick}         
      Hover_Event: 
        Action: SHOW_TEXT
        Values: 
          - "&7Message issued: &b{timestamp}"
          - "&7Click to send a PM"
      Click_Event: 
        Action: SUGGEST_COMMAND
        Value: "/tell {player} "            
    The_Rest: 
      Message: "{pl_suffix} {message}"

**Comment by kangarko** [comment]
The variable for nicks is {nick}. Thanks UncleM0 for the answer.

**Comment by TheIntelloBox** [comment]
And what is the placeholder for Marriage Master ?

**Comment by UncleM0** [comment]
Heard of Google? 

https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders

**Comment by TheIntelloBox** [comment]
I didn't know that ChatControl supports PlaceHolderAPI.
