### ISSUE TITLE
Seperate enabled options for join, quit, kick and death messages

### ISSUE THREAD

**Issue by sigmaroot** [kangarko/ChatControl-Pro#84]
Please add seperated enable options for the following customized messages (at messages.yml):

- Join
- Quit
- Kick
- Death

Just being able to enable / disable the whole functionaltiy is not good (except timed messages).

**Comment by sigmaroot** [comment]
Oh, it's fixed with 7.0.8 :)

**Comment by kangarko** [comment]
That's what I call light-speed support, haha
