### ISSUE TITLE
/ignore no longer works?

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#840]
Changes made recently disabled Essentials /ignore feature completely.  Used to be that the chc /ignore had an option to "report to essentials" which went away too... doubt that was intentional.  However chc now ignores ignore status in essentials.  Now... I still need essentials ignore to work primary since it will disable things like /me, /tpa, /mail, etc to eliminate whatever harassment is going on... otherwise I'd let chc handle this.  However, it doesn't seem to be possible to disable every essentials command that is built into their /ignore... so I kind of have to use theirs.  This did work for me for a long time but stopped doing so in this later version if you could please look into it... currently on 7.9.2.  Thanks!

**Comment by kangarko** [comment]
Hello,

Essentials had some code changed to prevent players not being able to un-ignore themselves, see `https://github.com/EssentialsX/Essentials/pull/2065#event-1736884244`.

ChatControl now always reports to Essentials as it is now safe. Essentials should handle it correctly and not show messages on /tpa for when the player is ignored:

![a](https://i.imgur.com/uChHo4g.png)

Tested on 7.9.2rev2

**Comment by mrcoffee1026** [comment]
Does the ChatControl ignore also ignore /mail /me... and say... the entire list of commands I put in the /mute list from Chatcontrol?

**Comment by kangarko** [comment]
No. ChatControl's own /ignore command reports that the player has been ignored to Essentials, which saves it to their own data folder and they so check for this ignore when handling their command.

1. ChatControl /ignore is issued
2. ChatControl makes Essentials set a player to ignore
3. Essentials check their ignore for /mail, /me etc. and acts accordingly
