### ISSUE TITLE
Admin_Chat discord - messages show for all players

### ISSUE THREAD

**Issue by lewis2470** [kangarko/ChatControl-Pro#841]
ChatControl-Pro VERSION: 7.9.2

This issue is related to the Admin_Chat feature in ChatControl Pro. (/chc ach) and the ability to link it to a discord channel.

When users send from in-game using "/chc ach" or "/chc ach switch", it works as normal, no players can see the Admin_Chat messages without the permission nodes. However, when users communicate from discord inside the discord channel linked with Admin_Chat, their messages are sent to all players.

Is it possible to only allow players with a specific permission node to see the messages sent from discord in the Admin_Chat linked channel to the minecraft chat?

**Comment by kangarko** [comment]
Hey,

I cannot reproduce (see below), please ZIP me your ChatControl/ folder.

**Comment by kangarko** [comment]
@lewis2470 sorry for late response, but I am still not being able to reproduce. I believe it's a permission issue or other, unrelated to ChatControl.

Still, please set "Debug" to "[discord]" in your settings.yml and post me the output when someone writes in staff-chat on discord.

**Comment by kangarko** [comment]
Comment below. Closing due to cleanup of the Issues page.

**Comment by kangarko** [comment]
It refers to this:
![a](https://i.imgur.com/kPUYTcL.png)

Change staff-chat to server-staff in Discord_Channel option.
