### ISSUE TITLE
Disable showing permissions in permission messages

### ISSUE THREAD

**Issue by WizzleBear** [kangarko/ChatControl-Pro#842]
When typing a CC Pro command which you don't have the permission for, it displays the permission needed. I was wondering how to disable that and the exclamation mark at the start? If this is not possible currently, I'd really like it if you could add that feature. As an off-topic suggestion, adding the localization files so we can edit them would be amazing!

**Comment by kangarko** [comment]
It's possible to edit the message in the Localization, see Wiki.
