### ISSUE TITLE
Auto-disable character spam

### ISSUE THREAD

**Issue by Rasturize** [kangarko/ChatControl-Pro#843]
Is there a way to cancel/edit player messages that are spamming one character?

Example "aaaaaaaaaaaaaaaaaaaaa"

Would either be shortened to "a" or canceled.

**Comment by kangarko** [comment]
Yes,

there is even a default rule for that hidden in rules/chat.txt, remove # from the two lines after the first line and you be good to go:

![a](https://i.imgur.com/RIRrdkj.png)

**Comment by Rasturize** [comment]
Thank you very much <3
