### ISSUE TITLE
Variable issue

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#845]
Hej,
if I run a ChatControl version later than 7.8.27 the plugins fails to get variables. The chat and the hover messages look broken: https://imgur.com/a/QMS2tZY
Start: https://pastebin.com/N83hmeQ1
Error: https://pastebin.com/QQgYUzJx
Could you help me?

PaperSpigiot 1.12.2 #1499
ChatControl: 7.9.3

**Comment by kangarko** [comment]
Update your PlaceholderAPI to the very latest version.
