### ISSUE TITLE
Sign Mute... working yet not.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#846]
While muted, when a user places a sign it says something to the effect that you cannot place the sign while muted.  The sign is still placed - however - just whatever text was typed for the sign is removed and it will be placed as an empty sign.  I have my Listener_priority for signs set to HIGHEST.  It's not a deal breaker or anything but might be nice if they wouldn't place.

On my last ticket about the ignore stuff...  If chatcontrol either pays attention to the essentials ignore or reports to essentials that the ignore has been placed in chc, then it shouldn't matter which one I use.  However, does the chatcontrol /ignore - ignore the commands in that the /mute command is set up to mute?  While you did say it would ignore /tpa, that doesn't confirm if it would also ignore /tpahere, /mail, /me, etc.  If I have every command possible listed in the /mute section am I covered if I switch to chc's ignore?  Thought I'd ask before trying on a restart... the Essentials bug they were talking about seem to be the opposite problem where - if a player ignored themself - they could not unignore themself. But we didn't experience that... we just had the /ignore command having no effect of any sort (except that the /ignore list would get longer... all interaction from those players could still be seen by the person ignoring them).  Let me know thanks!

**Comment by kangarko** [comment]
@mrcoffee1026 sorry for late reply.

I fixed the signs issues.

When you issue /ignore from ChatControl, Essentials gets to know it and should apply it for its commands like /tpa, /me, /mail and all others that support ignore function (in Essentials).
