### ISSUE TITLE
Change .txt files to .yml

### ISSUE THREAD

**Issue by Rasturize** [kangarko/ChatControl-Pro#847]
Currently files in the rules folder are all text documents, and editing them can break the encoding which breaks the entire plugin. I'd like to see these files changed to .ymls, so that they can be properly edited.

**Comment by kangarko** [comment]
Hello,

.yml is the extension for YAML language. Rules have their own unique language invented for ChatControl and therefore have .txt.

There are 0 issues with encoding when right approaches are used: https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding
