### ISSUE TITLE
private messages "Goal Reached"

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#849]
Every time someone sends a player a message they get the indicator in the upper right that shows a book and says "Goad Reached!"  For myself - as staff anyway - this is often followed by another book indicator in the upper right but formatted in the style of chatspy with the person it was from -> myself with the message. 

Also are there any ways to clean up the private messaging a bit by way of formatting?  I'd rather not see a "message sent!" confirmation every time we send one.  Doesn't appear to be editable in the "Private_messages" section of the localization file but that's where I'd expect to find the formatting to how its displayed in a recipients chat screen.  In any case would like to minimize the screen real estate taken by the message system if possible, thank you!

**Comment by mrcoffee1026** [comment]
found some of this in "formatting" but can't remove the "message sent" part since it gives me a null error and chc crashes.  Can't find where the "goal reached" part is coming from, might have something to do with using the "book" area to display it or something... if there's some place this is set I can't find it.  Not a BIG deal to display the message there but the "goal reached" should not be showing I'm sure.

**Comment by mrcoffee1026** [comment]
https://imgur.com/a/FCujILq  <-- for what i'm talking about.
After having this for like 5 minutes... I actually like it so don't want it disabled but it might be nice to know where this is formatted... I don't see this in formatting.yml or anywhere else.  The "Goal Reached" message should go away along with probably the book icon if possible, but I don't know if it is.  But I like having some activity appear on the screen in the instances when I'm interacting with inventory and would otherwise miss that someone sent a message, these I can see, which is nice.

**Comment by kangarko** [comment]
You cannot remove "Goal Reached" or customize the Toast due to the nature of Minecraft (they are not intended for custom notifications at all).

The only format there is available for you to customize is found in settings.yml:
![a](https://i.imgur.com/BYf10As.png)
