### ISSUE TITLE
Listener priority changes

### ISSUE THREAD

**Issue by sigmaroot** [kangarko/ChatControl-Pro#85]
I've set both listener priorities to LOWEST to test something.
After that, I've set both back to NORMAL and do a couple of restarts but the whole plugin stops working.

It is enabling correctly, no error message.
But no command is working, no error message is shown, no handler is working.

What's going on?

**Comment by kangarko** [comment]
After changing priorities, shutdown and start server again. Changing priorities is not recommended because it might cause plugin to stop checking rules due to other plugins having different priorities and overlapping incorrectly.

**Comment by sigmaroot** [comment]
Like I said, I've done a couple of restarts but I does not work.

**Comment by sigmaroot** [comment]
Hmm, regenerating all .yml files and updating to 7.0.8 solved this problem. Dunno why O.o
