### ISSUE TITLE
msg name completion... should work on any portion of name

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#850]
for my nick "mr_coffee" and IGN "mr_coffee1026"... a msg to "coff" should come to me instead of saying "player coff is not online" which it does.  Tried some variations to this... the essentials message system handled completion of any portion of the nick or ign, chc auto complete seems to only work by using the starting characters of the actual IGN or there is not match, can this be remedied?

Thanks!

**Comment by AmazedMender16** [comment]
Same here... Worked fine in 7.8.x not working anymore in 7.9.x

**Comment by AntZaro** [comment]
I have the same concerns. Tab complete on usernames does not work, and you cannot message someone based on the beginning of their name nor their nickname.

**Comment by AmazedMender16** [comment]
Seems to be only happening for users with nicknames..
Users without nickname can be tabbed

**Comment by mrcoffee1026** [comment]
Even under that condition, you'd have to tab complete the full user name... you should be able to reference the name even if the tab key was not pressed, I believe... at least this is how it works in essentials and most other plugins.

**Comment by AmazedMender16** [comment]
Yeah thats correct @mrcoffee1026 just testing out what works and what doesnt. Makes kangarko hes work easier :)

**Comment by kangarko** [comment]
Tab-completion only works on the beginning of nicknames and real names.

Next version should correct issues with nicknames.

**Comment by mrcoffee1026** [comment]
Between that and the ability for users to bypass essentials' /mute by using /msg, I guess I'll have to disable chc's message system and go back to essentials for that.  Thanks.
