### ISSUE TITLE
Private Messaging Format Inconsistency

### ISSUE THREAD

**Issue by AntZaro** [kangarko/ChatControl-Pro#855]
When formatting private messages in the formatting file, there are two variables: {receiver} and {sender}. So it'll say "Message to Notch" (Notch is the receiver) vs "Message from Notch" (sender). 

The problem is that {receiver} is always username. So I see "Message to Notch" going out. However, the {sender} variable shows up as the person's nickname through Essentials. So I see "Message from Notchyy" or whatever the person's nickname may be. From what I can tell, there is no way to configure it for either option. It seems stuck like this. Is there no way to make both show the nickname or both show the username?

**Comment by kangarko** [comment]
Thanks for informing. The next version will translate {receiver} variable always to nickname if present, else to username.
