### ISSUE TITLE
"-" is stripped from staff chat channel.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#857]
ChatControlPro 7.9.4

For some reason `-` is always stripped from the staff chat channel. It works in public chat, just not in staff chat. It blanks out to an empty space instead of parsing the character. So you can't type negative numbers like ```-0``` or ```-_-``` or ```-----------```.

It outputs fine in public chat. Just staff channel gets stripped.

**Comment by kangarko** [comment]
Any console output when it happens? Rules being caught, etc.?

**Comment by mibby** [comment]
No console output or rules being caught as far as I can tell. Besides, wouldn't I bypass all rules by default as an OP / admin with * permission wildcard? No clue why the staff channel is stripping messages that start with -.

**Comment by kangarko** [comment]
Detected, fixed.
