### ISSUE TITLE
Various problems.

### ISSUE THREAD

**Issue by Golvore** [kangarko/ChatControl-Pro#861]
Hello, I have problems with ChatControl Pro, I tried to communicate with the Author, but after several messages it did not respond, so I created this ticket.

 1: AuthMe support for the join / quit messages does not work (Works good without ChatControl Pro, so AuthMe not is the problem).

 2:  There is a problem with the AutoJoin, the permissions join you to the channel, but some plugin features do not detect that you are in a channel when you join through the AutoJoin (channel switch and upon entering you receive a message that you are not on any channel, even if you are),

 3: When you use the /ch set and one player is on another channel, the player can write on both channels, exceeding the limit of channels on which you can write.

  I clarify that I have had a lot of time with these problems, for which I am sure that these problems occur.

 Sorry for my bad english.

**Comment by kangarko** [comment]
Hello Golvore,

1. What exactly do you mean?
2. So you are saying that, upon joining you are automatically put into a channel, but when you type /ch switch it does not work? 
3. This is intended, as the set command is manual and overrides the limits.

**Comment by Golvore** [comment]
If I enter channels with autojoin permissions, when I enter the server it tells me that I am not in any channel, but I am.

**Comment by kangarko** [comment]
What permissions do you have?

**Comment by Golvore** [comment]
31.07 11:12:57 [Server] INFO > chatcontrol.channel.autojoin.global.write (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.autojoin.local.read (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.ciudad (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.ciudad.join.read (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.ciudad.join.write (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.ciudad.leave (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.global (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.global.join.read (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.global.join.write (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.global.leave (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.global.send (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.local (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.local.join.read (true)
31.07 11:12:57 [Server] INFO > chatcontrol.channel.local.join.write (true)
31.07 11:13:33 [Server] INFO > chatcontrol.channel.local.leave (true)
31.07 11:13:33 [Server] INFO > chatcontrol.channel.nacion (true)
31.07 11:13:33 [Server] INFO > chatcontrol.channel.nacion.join.read (true)
31.07 11:13:33 [Server] INFO > chatcontrol.channel.nacion.join.write (true)
31.07 11:13:33 [Server] INFO > chatcontrol.channel.nacion.leave (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.channels (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.channels.join (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.channels.leave (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.channels.list (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.channels.switch (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.ignore (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.reply (true)
31.07 11:13:33 [Server] INFO > chatcontrol.commands.tell (true)

**Comment by kangarko** [comment]
Thanks, that should be okay. Let's continue on Spigot in PM's.
