### ISSUE TITLE
Problem with spaces.

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl-Pro#862]
Hey,

I'm using PerWorldPlugins, ChatControlPro, and Factions.
If a player has no faction: there are 2 spaces between the tag and the rank: http://www.noelshack.com/2018-30-5-1532699334-bug-chatcontrolpro.jpg

**Comment by TheTopCz** [comment]
config file?

**Comment by kangarko** [comment]
Hello, to avoid that, I recommend installing PlaceholderAPI and configuring a boolean condition that will give additional space if the player has faction, or do not give anything if he has not.

**Comment by TheIntelloBox** [comment]
I have PlaceholderAPI. How can I configure this boolean ?

**Comment by kangarko** [comment]
Sorry I do not know how to do it, I just know that it was possible.
