### ISSUE TITLE
No enum constant org.bukkit.Sound.ENTITY_FIREWORK_LAUNCH

### ISSUE THREAD

**Issue by MoCaveman** [kangarko/ChatControl-Pro#864]
After dropping the JAR file in plugins I can not get it to fully boot.  Below is the error log regarding a missing enum constant?  Ug.  Thanks for the great plugin, long time fan, first communication.  

> ------------------------------------[ 27.07.2018 12:49:17 ]-----------------------------------
ChatControl 7.9.4 encountered a IllegalArgumentException
Running CraftBukkit 1.13-R0.1-SNAPSHOT and Java 1.8.0_152
Plugins: ChatControl v7.9.4, dynmap v2.6-beta-1-Dev201807082003, GriefPrevention v16.8
----------------------------------------------------------------------------------------------
IllegalArgumentException No enum constant org.bukkit.Sound.ENTITY_FIREWORK_LAUNCH

[error.log](https://github.com/kangarko/ChatControl-Pro/files/2236777/error.log)

**Comment by kangarko** [comment]
1.13 is pending support, https://github.com/kangarko/ChatControl-Pro/issues/844#issuecomment-408295515
