### ISSUE TITLE
[Support] 1.13 support

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#866]
I just tested for curiosity what latest chatcontrol do with 1.13 (i used paperspigot) and it trow this long error (caused by material change)
https://gist.github.com/xion87/dc7430fcbc169064fab3c69d2b935d10

**Comment by TheTopCz** [comment]
Yes, i have the same problem ..

**Comment by TheIntelloBox** [comment]
Kangarko is working on this.

**Comment by xion87** [comment]
i don't see any RAW_FISH  on messages.yml

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/issues/844
