### ISSUE TITLE
 Overlay of prefixes

### ISSUE THREAD

**Issue by ImJosee** [kangarko/ChatControl-Pro#867]
Hi, i have a problem setting up the formattings.yml, the prefixes.

The problem is with a OP player, 
Because the player have the 2 permissions, the 2 prefixes appear with him
is there any way to change this?
Thank you

![2018-07-31_17 29 40](https://user-images.githubusercontent.com/41305322/43485347-5afafb84-94e7-11e8-806d-e29162fbeec0.png)

**Comment by WizzleBear** [comment]
Negate the permission

**Comment by kangarko** [comment]
As WizzleBear suggested, give the player negative permission for the format part (a negative permission starts with an "-" in front).
