### ISSUE TITLE
Channel must contain : sperator (1.13)

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#868]
Try to to copy paste my old configuration into a new config file (only copied the stuff between "") and this starts popping up 

https://pastebin.com/t1hVXnm6

**Comment by AmazedMender16** [comment]
It starts occuring when using color codes before/after : under spy

Format_PM: "&8[&5SPY&8] &7{player} -> {receiver}: {message}" - WORKS
Format_PM: "&8[&5SPY&8] &7{player} -> {receiver}&8: &7{message}" - BREAKS

**Comment by kangarko** [comment]
BungeeCords is unsupported in the 1.13 first test release. Are these issues resolved when you set Bungeecords.Enabled to false?

**Comment by AmazedMender16** [comment]
Only seems to happend when bungeecord is enabled.

Regards,

**Comment by xGlenor** [comment]
When the bungeecord is false, everything works

You can know when you will fix this function?

**Comment by kangarko** [comment]
This will be fixed as the part of regular update process towards 1.13.
