### ISSUE TITLE
chatcontrol.bypass.rules.global bypasses ALL rules, even if they are set to false

### ISSUE THREAD

**Issue by WizzleBear** [kangarko/ChatControl-Pro#869]
I am using LuckPerms and when I set `chatcontrol.bypass.rules.global` to true, I bypassed all of the .txt files in the rules folder. On the table, it says it only bypasses the rules.txt, not any of the other ones. When I added `chatcontrol.bypass.rules.commands` and set it to false, the commands.txt file was still bypassed. When I set them both to false, I could bypass the commands.txt files. I believe that the `chatcontrol.bypass.rules.global` permission should be renamed to `chatcontrol.bypass.rules.rules` and only bypass the rules.txt file.

**Comment by kangarko** [comment]
> when I set chatcontrol.bypass.rules.global to true, I bypassed all of the .txt files in the rules folder

This is the intended behavior, apology for mistyping it on the wiki. I edited it.

**Comment by WizzleBear** [comment]
Can you add a permission so that we can bypass only rules.txt as well?

**Comment by kangarko** [comment]
I am sorry but I am not taking feature requests at the moment.
