### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by Chris4418** [kangarko/ChatControl-Pro#87]
This is not an issue, but not sure where to put this. But im curious to know if there is a way to have the announcement thing as the welcoming message in chat.  Instead of using the MOTD, i found the announcement is far more effective in catching peoples attention. Is there any possible way that i could have it as the welcoming message that is automated rather than me typing /chc announce every time someone joins?

**Comment by locke-d** [comment]
In settings, there is a "Motd:" enable that and change it to fit your needs. Motd = message of the day, it's the message any player sees when they first join a server.

**Comment by kangarko** [comment]
You can change the motd in Motd.Message exactly to your needs, for example to have the same message as the announcer.
