### ISSUE TITLE
How to regex stop @everyone

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#872]
For some reason when I use DiscordSRV their regex to filter @everyone from chat using DiscordChatChannelCutPhrases gets ignored when im using ChatControl, so I need chatcontrol to ban the use of @everyone or replace it in-game, but when Im not sure on the Regex to find the @ symbol.

**Comment by kangarko** [comment]
You can create a rule for that in rules/chat.txt:

match \@everyone
then deny
