### ISSUE TITLE
"then warn" Not Working

### ISSUE THREAD

**Issue by lizardfreak321** [kangarko/ChatControl-Pro#874]
Hello,

In all of the rules files, when I add "then warn", the player cannot see it.
I know it catches it. I can see it in the console because verbose is enabled.

Example:
`match test`
`id test`
`then warn Worked`

I have tried disabling points: did not work. I have tried disabling smart warnings: did not work.
The warn feature of "handle as ..." does work. It also works in the point system.

I am on Spigot 1.12.2 and I tested this on versions 7.9.2, 7.9.5, and 7.9.7. It works fine on the old version I was using: 7.5.*. I cannot find any documented change to the "then warn" feature.

**Comment by kangarko** [comment]
Do you have any other chat-formatting plugin? Make sure you use 7.9.9.

**Comment by lizardfreak321** [comment]
There are no other chat-formatting plugins, and it does the same thing on 7.9.9.

This issue is annoying because players aren't realizing some of the stuff the filter is doing because of the lack of warnings.

**Comment by kangarko** [comment]
Thanks, fixed.
