### ISSUE TITLE
[Suggestion] Support TownyChat

### ISSUE THREAD

**Issue by Golvore** [kangarko/ChatControl-Pro#875]
I would like them to add support to the Towny channels as they are more convenient and easy to use for me.
 Here is a more detailed explanation: TownyChat has an option called "hooked", but it adds a "special event" then ChatControl handles the chat from the towny chat event instead of the normal spigot chat event and if chat is sent to a channel and its not firing the event, ChatControl doesn't process the chat.

Note: What I explained is not what happens, it is what I would like you to add.

**Comment by kangarko** [comment]
You can change our priorities to enable for more compatibility: https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

We are currently not planning to add special compatibility bridge for Towny.
