### ISSUE TITLE
[Suggestion] Make the ChatControl channels more comfortable and easier to use.

### ISSUE THREAD

**Issue by Golvore** [kangarko/ChatControl-Pro#878]
What do I mean? The ChatControl channels do received a write and read limit update, but when you are in a channel in mode and want to change to another mode in the same channel, you have to exit it and re-enter with the new mode you want, This is very uncomfortable.

When you are in more than 2 channels, the /ch switch does not work.

I think the best thing would be to eliminate the limits of writing and reading and only allow writing on one channel at a time, being the last channel that you have entered in the channel where you write and the other channels that you have entered only read.

**Comment by kangarko** [comment]
While I like your ideas I am sorry but I am currently not open to feature suggestions.
