### ISSUE TITLE
Chat bubbles.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#879]
Would it be possible to implement a feature to display chat bubbles above a player's head when they type?

Similar to this plugin which has defined height options, line length option, wordwrap, range, PAPI support, invisible / vanish support, and clear's the bubble after so many ticks / if you chat something new., 
https://www.spigotmc.org/resources/chatbubbles-1-8-1-12-factions-compatible-placeholderapi.49387/

Reason for the feature to be implemented into ChatControl would be so the chat bubbles abide by chat filter rules and worldguard region chat flags.

**Comment by kangarko** [comment]
Hello,

thank you for your suggestion but I am not taking them at the moment due to other works and priorities.

**Comment by mibby** [comment]
@kangarko Could it perhaps be a future suggestion? I do think Chat Bubbles would be a neat implementation and having it support everything else ChatControl does, like regex filtering, would be nice.

It is kind of like a social chat element that helps bring people together.
