### ISSUE TITLE
Commands.txt issue

### ISSUE THREAD

**Issue by Chris4418** [kangarko/ChatControl-Pro#88]
im having an issue with the commands.txt file. i have not touched or edited the file in anyway, but when i go to put it into the YAML Parser, it comes up with an error relating to nothing. i tried fixing the error by editing it, but that didnt work. I also tried to reset the file by deleting it and getting the plugin to create a new one, but the error is still there

This is the error im getting: 

ERROR:

mapping values are not allowed here
  in "<unicode string>", line 13, column 73:
     ... t &8[&7ID {ruleID}&8] &7{player}: &f{message}

Here is the file: http://pastebin.com/ewKeX7NJ
                                         ^

**Comment by locke-d** [comment]
try getting rid of the ":"

granted, my file does have that and works but i'm on a slightly older version, may be a locale issue.

**Comment by kangarko** [comment]
The YAML parser is only for files ending with .yml having yaml language. Those files have their own language.
