### ISSUE TITLE
Tab Complete Names

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#880]
Hello,

Still cannot tab complete users when they have nicknames (essentials) enabled.
Once they disable the nicknames it all works.

CHC - 7.9.7
Essentials - 2.15.0.17

**Comment by AmazedMender16** [comment]
Messaging like.
/msg amaze Hello, this is a test

Doesnt work either, you need to type the users entire name.

**Comment by AmazedMender16** [comment]
This does apply on server version 1.11.2-1.12.2-1.13

**Comment by kangarko** [comment]
Test 7.9.10 - tab complete will include both nicknames and regular player names.

**Comment by AmazedMender16** [comment]
Awesome! 

Will give it a try and report back.

**Comment by AmazedMender16** [comment]
Wouldn't call this a fix sorry...
https://pastebin.com/SZqpNApu

**Comment by kangarko** [comment]
Apology for this. I solved this in 7.9.11 and BungeeControlBridge 3.1.

I also added new debug option to ChatControl, "Debug" to "[bungee]", and BungeeControlBridge, "debug" to "[pm]". You don't have to enable them if all works, but you can do so for next time if anything happens to enable me a quicker fix. Thank you.
