### ISSUE TITLE
Exception when player attempted to tab complete

### ISSUE THREAD

**Issue by Heliosard** [kangarko/ChatControl-Pro#884]
Hello,
An error appears as soon as I enter"/m Hel..." for "Heliosard" and press the tab key.

Error: https://hastebin.com/letojuloxe.sql
error.log: https://hastebin.com/forijepuro.php

**Comment by FedericoGB25** [comment]
Same: https://pastebin.com/q6PU7BEM

**Comment by xion87** [comment]
same https://gist.github.com/xion87/7bbfdb45d6f374a271c30f8d41e1a192

**Comment by kangarko** [comment]
Thank you, fixed.
