### ISSUE TITLE
Block Commands,

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#886]
can you help, i need the commands to be blocked, for example, i want to execute the command and receive the message saying the message i want to show, but its not blocking the command, it executes it, ty

**Comment by kangarko** [comment]
What are you talking about? A specific rule?

**Comment by dabou0** [comment]
i mean to add like this
https://www.spigotmc.org/resources/commanddoesnotexist.2820/

**Comment by kangarko** [comment]
You can create a rule for that, see rules/commands.txt.
