### ISSUE TITLE
Server freezes on startup

### ISSUE THREAD

**Issue by Affixes** [kangarko/ChatControl-Pro#887]
Hi,

We've experiencing an urgent issue where ChatControl is freezing our server after the startup has completed (aka. `Done (xx.xxs)! For help, type "help" or "?"` message has displayed).

The issue can be resolved by deleting the `data.db` file from the ChatControl folder. Oddly enough the file still generates even though we have MySQL storage enabled.

```
[23:27:54 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[23:27:57 INFO]: ChatControl version 7.8.17
[23:27:57 INFO]: Author: kangarko
```

- handlers.yml: https://pastebin.com/bTBeB7w9
- settings.yml: https://pastebin.com/4S5biXAn
- rules.txt: https://pastebin.com/Nf74z1qS
- Every other file is at its defaults

Please let me know if you need any more information.

**Comment by kangarko** [comment]
Please update to 7.9.11.
