### ISSUE TITLE
Command Spamming

### ISSUE THREAD

**Issue by Deathbytray106** [kangarko/ChatControl-Pro#891]
Hi
Dont know where to look or ask so im asking here ive tried disabling the antyi spam aspect of this plugin especially regarding command spam ...id like to turn it off as i believe my players wont spam or want to just turn it off regardless 
anyway id like to know how to do this or which settings to effect as there doesnt seem to be a clear false flag or off switch for the anti spam feature 

ive tried changing the time of commands to 0 as well as well as give the user multiple commands to do before being called out but still nothing 

[Untitled document.txt](https://github.com/kangarko/ChatControl-Pro/files/2290941/Untitled.document.txt)
Here is my settings from chat control

**Comment by kangarko** [comment]
To disable antispam, please see https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#how-do-i-disable-anti-spam--messages-please-waitdo-not-repeat-similar-commandmessage
