### ISSUE TITLE
ChatControl & Nicky

### ISSUE THREAD

**Issue by Linebeck** [kangarko/ChatControl-Pro#892]
I am using a SQL database to store Nicky's data on my bungee server. The problem I am having is when I go to /msg a player and I tab over, it shows their name in a pre nametag form. Example being, if my nickname is Bob and it is colored gold and bold, then when I tab over it shows it as: &6&lBob instead of just my MC username.

Any ideas on what this could possibly be? Thanks. Let me know if you need any configs etc.

**Comment by kangarko** [comment]
Can you post me your formatting.yml file please?

**Comment by kangarko** [comment]
Also make sure you have the very latest version as this was getting fixed recently

**Comment by Linebeck** [comment]
Does the latest version require a update of the config? I am still on 7.8.30, because I didn't want to reconfigure the plugin again.

https://pastebin.com/5WVcaZER

**Comment by Linebeck** [comment]
I am running the latest version now. I honestly forgot all about what version I had in general. Sorry. I see where it has both the nicknamed name and my normal player name.

**Comment by Linebeck** [comment]
However, now that I updated my primary server. It will not show any messages or distribute any chat across all of my servers. My test server which is a direct copy of my multi-craft bungee setup, but on my local machine works just fine.

**Comment by Linebeck** [comment]
Never mind. Ignore me. I got it all figured out now, turns out I didn't have bungee-control updated on my last issue. Thanks anyways!

**Comment by kangarko** [comment]
No problem, best of luck and let me know if any issues arise!

We have fully automated configuration upgrade over all releases since 7.5.x, so updating is as simple as drag&drop the file into plugins/ ;)
