### ISSUE TITLE
Death messages not logging to console

### ISSUE THREAD

**Issue by SioWolf** [kangarko/ChatControl-Pro#894]
Enabling custom death messages in messages.yml causes deaths to no longer be logged to console. showDeathMessages gamerule is set to true.

Version: 7.9.12

**Comment by kangarko** [comment]
What's your MC version? If you modified messages.yml more than simply changing Death_Messages to true, post me the file

**Comment by SioWolf** [comment]
I've tried to get it to work on both 1.12.2 and 1.13. Here is my config: https://pastebin.com/5aw4WJSn

**Comment by kangarko** [comment]
Sorry for delays, I can confirm the message is not being shown. This will be implemented in a few days.

**Comment by cmoutafidis** [comment]
Hello SioWolf,
The issue was resolved accordingly, thank you for pointing out this issue.
