### ISSUE TITLE
&l makes other lines bold

### ISSUE THREAD

**Issue by WizzleBear** [kangarko/ChatControl-Pro#895]
My version is git-Paper-1523 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT). My ChatControl version is 7.9.13.

Screenshots:
![image](https://user-images.githubusercontent.com/22808172/44292653-e7381e00-a253-11e8-85d8-dcfae82dd093.png)
![image](https://user-images.githubusercontent.com/22808172/44292656-fa4aee00-a253-11e8-948a-1dfed8685b0f.png)

Try placing &l at the very first line and see if it modifies other lines when they don't have &l in the front.

**Comment by mibby** [comment]
@kangarko I can confirm this happening for me too with recent ChatControlPro versions. Current as of 7.9.13.

Setting a new color no longer resets text formatting, nor does &r reset the bolding placed after.

**Comment by TheoRetisch1** [comment]
Same problem here. After updating the hover messages look like this: https://imgur.com/a/fRth4TA

PlaceholderAPI: 2.9.1
ChatControlPro: 7.9.13 (doesn't happen with 7.9.10)
PaperSpigiot 1.12.2 #1523

**Comment by kangarko** [comment]
@WizzleBear sorry I wasn't able to reproduce (https://i.imgur.com/UVInEvC.png), please ZIP me your ChatControl/ folder.

**Comment by WizzleBear** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/2316613/ChatControl.zip)

**Comment by kangarko** [comment]
Thanks, Spigot changed their ChatComponent API in that the decoration colors are persistent when I used a certain method. 

Fixed.

**Comment by TheoRetisch1** [comment]
Awesome! Thanks
