### ISSUE TITLE
Packets.Tab_Complete.Enabled

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#898]
Can you tell when this functionality is coming back, approximately?

**Comment by kangarko** [comment]
Good point, I will be looking out to add this in the next release(s).

**Comment by x1p** [comment]
Define "next" please

**Comment by kangarko** [comment]
I am building a team right now, we will have a developer looking into it. Should be within 2 weeks maximum.

**Comment by kangarko** [comment]
Update: Working on it.

**Comment by kangarko** [comment]
Added base functionality, please see spigot.yml for more settings.
