### ISSUE TITLE
/ignore and /separate

### ISSUE THREAD

**Issue by jasjmorris** [kangarko/ChatControl-Pro#9]
I was curious while doing the. Ewes update with /reply /tell can you add /ignore for players to use

Also add /separate  feature for admins or staff  to allow us to make it so two players can see each other in regular chat. Reason for this would be if two players are fighting in chat you can make it so they can't see each others messages... no messages no fight... lol

**Comment by kangarko** [comment]
I appreciate your suggestions. The /ignore command will be implemented, however I most probably won't add the later since it seems to be out of my scope.
