### ISSUE TITLE
Help with Regex

### ISSUE THREAD

**Issue by Chalwk77** [kangarko/ChatControl-Pro#90]
Suppose I want to match and replace "**./warp** [warpname]" and print an exact copy (in color).

How do I do that? I've tried a few things but this was the closest I could get to actually achieving this:

#Regex expression:
match ^**./warp** ([a-zA-Z0-9_]{1,})
then replace &b$&

This does however, print the original text, just not in color.

#Desired Result:
When the player types **./warp** [warpname] into chat, it should appear in the color Aqua.

Why do I want to do this? - Just as an experiment, I wanted to make it so that any time a player types
**./warp** [warpname] in chat, it will print in color.

Any help with this would be appreciated, 
Thanks in advance!

Regards,
Chalwk

**Comment by kangarko** [comment]
Hello,

this works for me:

    match ^/(warp) ([a-zA-Z0-9_]{1,})
    then warn You want to go to &b$2
    then deny

**Comment by Chalwk77** [comment]
This is not a command. 

Here's the scenario:

1). PlayerX asks in chat what the warp is to the server shop.
2). PlayerY types the following in chat: ./warp shop

They have to put a period (.) before /warp, so it doesn't actually execute the command.

But I want the message "./warp <warpname>" itself to actually appear in Aqua.

**Comment by Chalwk77** [comment]
Please kindly disregard this. I have figured it out:

match ^.(/warp) ([a-zA-Z0-9_]{1,})
then replace §b$1 $2

**Comment by kangarko** [comment]
Oh I apologies, I missed the dot. I close this. If you have questions feel free to post them below or create a new issue.
