### ISSUE TITLE
Prefix refresh

### ISSUE THREAD

**Issue by glorying16** [kangarko/ChatControl-Pro#903]
So im having issues with my prefix not refreshing on change. I am using LuckPerms, and can confirm it is updated there, but it wont update in chat till the person relogs. Im using the {display_name} placeholder for my format. Im not sure if this would be an issue with LP or CHC. I am also using CMI if that makes any difference. Im not seeing any errors in console. Any ideas?

**Comment by kangarko** [comment]
We reach out for variables directly in Bukkit or PlaceholderAPI. You can try using PlaceholderAPI for that variable if that helps. If it does not, than I am sorry but I am out of control over how variables are updated since this is outside of ChatControl.
