### ISSUE TITLE
Random "Someone else said that just recently" warnings

### ISSUE THREAD

**Issue by AmazedMender16** [kangarko/ChatControl-Pro#906]
Hello,

My players are reporting (on 1.13.1) that when they type normally they see the message "someone else said that just recently" even tho parrot/anti_spam is disabled.

Regards,
Glenn R.

**Comment by AmazedMender16** [comment]
Hello Matej,

I disabled the parrot the other day, seems to have gone away since updating to the latest version

Regards,
Glenn R.

**Comment by kangarko** [comment]
Excellent!
