### ISSUE TITLE
Tab completion kicks people

### ISSUE THREAD

**Issue by Tyloonie** [kangarko/ChatControl-Pro#907]
Hello,

Trying to tab something with the newest version of CHC kicks the player.

Showcase: https://gyazo.com/e9e31e50b477c4bf89bcbba742a44f8a

Error: https://hastebin.com/ekocemamit.css

**Comment by kangarko** [comment]
Does not seem like ChatControl, neither can I reproduce this. Make sure you have the very latest 1.12.2 build (I use https://destroystokyo.com/ci/job/Paper/) and the very latest ProtocolLib (http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/).

**Comment by Tyloonie** [comment]
Hello,

I made sure to update Paper, Waterfall and ProtocolLib to the newest versions.
Every time someone tries to tab something on the server, I then get this error in the Waterfall console.

Error: https://gyazo.com/fc0d55adef20490c03f70c3f7e30e6a3?token=c719381a2815fcad3198a6d83000a556

I know this error may not be directly with ChatControl, but at the moment, the only solution seems to be disabling ChatControl. Then there are no issues tab completing - so it gotta be doing something. For the sake of it, I tried disabling BungeeControlBridge, but had no effect either - I also tried resetting all plugin data, but this didn't do the trick either. Installing the newest version of ChatControl on a localhost server has no issues though. So it must have something to do with BungeeCord/Waterfall.

Setting **Packets.Enabled** to false in the ChatControl **settings.yml** fixes the tab issue completely. Could you please investigate further?

**Comment by kangarko** [comment]
I see, there are some issue with Packets on 1.13.1, will investigate in a few days!

**Comment by Tyloonie** [comment]
I managed to narrow down the issue to **Packets.Tab_Complete.Hide_Vanished_Players.Enabled** - if this is enabled, it breaks tab completion.

**Comment by kangarko** [comment]
Vanish check in tab-complete had inverted parameter by mistake, which means reverted logic and broken functionality.

This is now fixed, apology for this.

Also, errors above are resolved by again updating your Paper, can't seem to get any of them right now.
