### ISSUE TITLE
Antispam malfunction

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#910]
After being quite for a while, and trying to write something in the chat again, I get the Anti_Spam.Chat_Wait_Message message.

I'm pretty sure everything is correct. No problems with older versions.
Seems to be a bug in one of the latest versions.

**Comment by kangarko** [comment]
Please post me your settings.yml. How long have you waited? Any more specific how-to-reproduce information please?

**Comment by x1p** [comment]
I've waited a few minutes. At least 3 minutes.
You have the file via spigot conversation.

Hope you find out. I've set it to 0 meanwhile.

**Comment by kangarko** [comment]
Continuing in PM.
