### ISSUE TITLE
[Feature] Tag Function for Users

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/ChatControl-Pro#912]
Hello! 

Basically with this idea i want to propose the addon of the Chat Mention

Example: i write in chat @Username 

Then in the other user's chat you will see: 

You have been mentioned by {Player}! Hover to see the message

If you hover you can the message written by the other user. 

Thanks a lot and good bye :)

**Comment by dabou0** [comment]
Good idea

**Comment by BlackGamer000** [comment]
Ty c:

**Comment by kangarko** [comment]
Like others said, good idea!

Will put into the road-map.
