### ISSUE TITLE
Crossover-chat

### ISSUE THREAD

**Issue by tw1xen** [kangarko/ChatControl-Pro#913]
How to set crossover chat? I´ll have de latest version of chatcontrol-pro and spigot and bungeecord. Thanks!

**Comment by kangarko** [comment]
Hey, if you mean crossover format, simply use &m in your formatting.yml.

If you mean Bungee integration, install BungeeControlBridge plugin and set BungeeCords.Enabled to true in settings.yml of ChatControl, and do CTRL+F to find other "Bungee" options.
