### ISSUE TITLE
permission to block talking in global chat

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#917]
I do not use channels just the basic chat, I have a world I want to denote a permission to stop them using the chat, reading and replying in the main chat, what is the permission node for this, I cant seem to find it.

**Comment by kangarko** [comment]
Added chatcontrol.chat.read and chatcontrol.chat.write permissions to the next version ;)

**Comment by FrozenBeard** [comment]
Awesome.
