### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#918]
how to make this ~ showing on edit names (essentials)
its enabled on essentials, 
currently using

Player:
      Message: '&7{essentials_nickname} &8>>&f'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&7Message issued: &b{timestamp}'
        - '&7Click to send a PM'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/tell {player} '

ty

**Comment by glorying16** [comment]
That is probably in your essentials file. Its one of the first few things in the config.

**Comment by dabou0** [comment]
http://prntscr.com/krxzgo
cant  you read it all before posting ?
ty anyways

**Comment by kangarko** [comment]
Use {nick} variable, if that does not help, than we have no control over adding that symbol.
