### ISSUE TITLE
incompatibility with showitem ( plugin )

### ISSUE THREAD

**Issue by signition** [kangarko/ChatControl-Pro#919]
issue: showitem doesn't work in chat when chat is printed in chatcontrol channel. Instead of showing item in json format, it shows some hash number like $showitem-123456

reproduction
1. have chatcontrol and set up some channel
2. have showitem installed
3. try to project item with showitem by typing %item% ( by default )

**Comment by kangarko** [comment]
Please read [this](https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities) article and try adjusting your Listener_Priority.Formatter to LOWEST, LOW, HIGH and HIGHEST. Restart after each change.

Are you using Chat Formatter (formatting.yml) or Chat Channels (channels.yml)?

**Comment by kangarko** [comment]
Assuming the advice above resolves that issue. Comment below if not.
