### ISSUE TITLE
Chat format compatibility

### ISSUE THREAD

**Issue by xan61789** [kangarko/ChatControl-Pro#920]
Hey, can you be compatible with the "Newtag" plugin in the chat format?
Because I am a person who uses Chinese, the current chat format is compatible with the nickname plugin
They can't support Chinese language, they will display garbled characters or not display
Sorry for the trouble, thank you for your reply

This is the plugin website I use, although it seems to be dead.
But they are still amazingly working for my 1.12.2 server
https://dev.bukkit.org/projects/newtag

**Comment by kangarko** [comment]
Please read [this](https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities) article and try adjusting your Listener_Priority.Formatter to LOWEST, LOW, HIGH and HIGHEST. Restart after each change.

This applies for both Chat Formatter (formatting.yml) or Chat Channels (channels.yml).

If that does not help then I am sorry but we are incompatible.
