### ISSUE TITLE
Double post after updating to 7.9.21

### ISSUE THREAD

**Issue by CypherPhyre** [kangarko/ChatControl-Pro#921]
After updating to 7.9.21 from 7.9.20 the chat gets doubled. I tried adding the new permission nodes but the issue continues. Downgrading back to 7.9.20 fixes the issue. I couldn't find any setting to change to correct the issue.

Spigot 1.13.1

**Comment by xion87** [comment]
I confirm the issue

**Comment by kangarko** [comment]
Confirmed, will be fixed.

**Comment by xion87** [comment]
The issue seem fixed partially, now instead giving double message it output only the message with server prefix....
![image](https://user-images.githubusercontent.com/3611852/45409943-da4ef480-b670-11e8-86bf-0aadc637ae72.png)
can you fix?

**Comment by xion87** [comment]
I correct: the double chat issue is still here :(  and the same error, you fixed nothing
https://gist.github.com/xion87/9dc4477fdf2fe1cac3ff5f5d69d7e37c

**Comment by xion87** [comment]
sorry was not related to this ticket but to https://github.com/kangarko/ChatControl-Pro/issues/914

**Comment by kangarko** [comment]
Next version should move things forward and remove the error.

Please set Debugger to [cache-channels] for 1 testing round. It will produce a hell lot of console spam but I just need it once so I finally can track the problem. You can disable it the soonest you will get few of them errors (not really errors just debug stack traces).

**Comment by xion87** [comment]
the cache-channels debug is already active? i enabled it but not generating any debug ( 7.9.22), is present in  7.9.23?

**Comment by xion87** [comment]
Ok i got some of these, here there is my server log and error.log generated by chatcontrol
[mylog.zip](https://github.com/kangarko/ChatControl-Pro/files/2380265/mylog.zip)
[error.log](https://github.com/kangarko/ChatControl-Pro/files/2380266/error.log)

**Comment by kangarko** [comment]
Next version fixes the error message, let me know if duplication will still occur.

**Comment by matt11matthew** [comment]
Are you still experiencing any issues?

**Comment by CypherPhyre** [comment]
I am no longer having a double post issue. The issue seems to be fixed. Closing
