### ISSUE TITLE
"First join" chat & command issue

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Pro#923]
**Plugin version:** 7.9.22
**Server version:** 1.8.8 PaperSpigot
**Configuration file:** All default aside from my rules and handlers.

[The issue](https://my.mixtape.moe/hvrdit.png)

**Comment by Optimusik** [comment]
same spigot 1.13.1

**Comment by kangarko** [comment]
Apologies that it did not came up from my testing,

Solved.
