### ISSUE TITLE
Chat formatting interferes with WorldGuard

### ISSUE THREAD

**Issue by Twiistrz** [kangarko/ChatControl-Pro#925]
ChatControl Pro v7.8.5

So i set my Listener_Priority.Formatter to LOWEST so TownyChat can be use, unfortunately this message shows up.

Chat formatting interferes with WorldGuard. We have changed listener priority of Formatter to HIGH to fix it for you.
Formatter listening at high priority.

In the previous version
![image](https://user-images.githubusercontent.com/25744238/45523820-c5ec3280-b7fd-11e8-865d-76b92bc027c9.png)

I can't use TownyChat Channels anymore lol.

![image](https://user-images.githubusercontent.com/25744238/45523851-fa5fee80-b7fd-11e8-9d98-b5d62cccffcc.png)

![image](https://user-images.githubusercontent.com/25744238/45523788-a0f7bf80-b7fd-11e8-8f1f-69239aab6b27.png)

**Comment by kangarko** [comment]
Update to the very latest version.
