### ISSUE TITLE
Issue with chat ignorer

### ISSUE THREAD

**Issue by MrWardy** [kangarko/ChatControl-Pro#926]
Hello, I'm unsure of where this should be posted since there is no longer a chat control discord, however I'm having trouble setting up a chat ignorer to allow seeing swear words via the /chc ignore swear command. All that happens is when ignoring the set, the starred out message doesn't appear in chat meanwhile the warning about swearing does, and when not ignoring the set, the starred out message as well as the warning about swearing appears, although the message never actually shows up and the warning always happens.
I've put all my related config files into separate hastebins.
[rules.txt](https://hastebin.com/awuwigayis.shell)
[handlers.yml](https://hastebin.com/ulibuyayon.shell)
[settings.yml](https://hastebin.com/oturaxucin.coffeescript)

**Comment by matt11matthew** [comment]
Hello, it seems that the hastebins no longer work are you able to upload them via gist.github.com or pastebin?

**Comment by matt11matthew** [comment]
So your issue is that it cancels the message sending instead of staring out the swearing EX: ****?

**Comment by MrWardy** [comment]
Oh? How do I change that.

**Comment by matt11matthew** [comment]
So that is your issue correct?

**Comment by matt11matthew** [comment]
I'm not to sure if you want it to you can try to set the event priority to LOWEST in the config

**Comment by kangarko** [comment]
Comment below if you still need help.
