### ISSUE TITLE
Question: Rule priorities (between different files)

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#928]
I wonder if there is a certain priority in handling the different files.
Example:
If there is a rule in rules.txt and a rule quite similar in chat.txt, which one will be handled first?
Fictive example:
Rules.txt contains a rule to flter "shit"
Chat.txt contains a rule to filter "no shit"
Which one will prevail if a player says "no shit sherlock"?

**Comment by matt11matthew** [comment]
Are you still in need of support?

**Comment by x1p** [comment]
That sounds like an answer.
I rather have the confirmation from the developer itself that chatcontrol has indeed a strict priority order.

**Comment by kangarko** [comment]
rules.txt goes first, than your respective file like commands or chat.xml

![a](https://i.imgur.com/TMQPzjZ.png)

Also, rules inside are applied from top to bottom.
