### ISSUE TITLE
Question on Multi platform servers.

### ISSUE THREAD

**Issue by InnuendoSA** [kangarko/ChatControl-Pro#929]
Hi
We got CC Pro from you and it is Awesome!
But.. We also have Sponge Forge servers on our Bungee network.
Is there any way I can link the chat on my Modded and my Spigot?
Do you know maybe of a mod/sponge Plugin that can "hook" in to the Global Chat?
Thanks for the Awesome Plugins!

**Comment by matt11matthew** [comment]
Hello, what do you mean by link chat between Modded and Spigot?

**Comment by InnuendoSA** [comment]
My Forge servers is also on my Bungee network.
I would like to know if there is a way to get my Forge servers to chat on global. 
By adding a mod or sponge plugin you support on the Forge servers.

**Comment by kangarko** [comment]
I am sorry but that is not possible.
