### ISSUE TITLE
Command to disable server broadcast messages

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#930]
Hey,

Is it possible to add a command so that players can decide whether they want to receive the broadcast messages or not?

**Comment by Sikatsu** [comment]
The automatic broadcast?

**Comment by kangarko** [comment]
I can add a toggle like /togglepm is. No ETA right now until we get a dev on our team, stay tuned :)

**Comment by Sikatsu** [comment]
Alright!

**Comment by kangarko** [comment]
Added.

**Comment by Sikatsu** [comment]
@kangarko I think after a restart it forgets about it and just shows the broadcast again. Also, is there any permission for it?

**Comment by Sikatsu** [comment]
I got it disabled yet I still see the broadcast messages..

**Comment by jascotty2** [comment]
There are two permission nodes for the toggle commands:

chatcontrol.commands.togglebroadcast
chatcontrol.commands.togglebroadcast.others

I found why the setting wasn't being loaded, so that'll be fixed in the next version when that is built (7.9.30)
