### ISSUE TITLE
Tab Complete

### ISSUE THREAD

**Issue by xGlenor** [kangarko/ChatControl-Pro#931]
Hi, i have a bug. Tab Complete option does not work either on a paid or free version

**Comment by ArtelGG** [comment]
Are you trying to block it or allow it? If you're trying to block it, the option `Packets.Tab_Complete.Allow_When_Length_Above` seems to cause issues if it's not set at 0. At least doing that fixed it for me.

**Comment by matt11matthew** [comment]
Has your issue been resolved?

**Comment by xGlenor** [comment]
No, and this option still doesn't work

**Comment by xGlenor** [comment]
but I have found a solution https://github.com/kangarko/ChatControl-Pro/issues/898

**Comment by kangarko** [comment]
Tab complete is currently in preparation for 1.13, stay tuned in that Issue Ticket.
