### ISSUE TITLE
Chatcontrol varius errors

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#932]
I see these strange errors with latest release:
https://gist.github.com/xion87/66e0a24b56d18e583b3edd4dac147be2
And the "already in channel" error is still here

**Comment by matt11matthew** [comment]
Were you running /reload to load the plugin?

**Comment by xion87** [comment]
i never runned that :), no reload, no /chc reload

**Comment by matt11matthew** [comment]
Try updating to the latest version and loading a fresh config also make sure you are rebooting the server if you have any issues with loading ChatControlPro plugin.

**Comment by xion87** [comment]
I am already using latest chc  version.... and using 1.12.2

**Comment by matt11matthew** [comment]
Can you attach your channel config?

**Comment by xion87** [comment]
# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 22.07.2018 05:01:04
#  to ChatControl 7.9.3
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologies.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the ChatControl.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/ChatControl/wiki
# 
# -------------------------------------------------------------------------------------------

Enabled: true
Command_Aliases:
- channel
- ch
Notify_On_Join: false
Channels:
  hub:
    Format: Chat
    Bungee: true
    Log_Format: 'NONE'
Compatibility:
  Multi_Event: false
  Single_Event_Format: '[{channels}] {player}: {message}'
  Cancel_Event: false
  Discord:
    Control_Incoming_Messages: true
    Deny_Unknown_Channel: true
    Format: '&8[&3Discord&8] &7{player}: &f{message}'
    Apply_Natural_Format_If_Online: false
Channel_Limits:
  Write: 1
  Read: 3

**Comment by matt11matthew** [comment]
Try disabling bungee config option by setting it to bungee: false

**Comment by xion87** [comment]
that is not helping me, please allow @kangarko to reply since he know better

**Comment by kangarko** [comment]
Seems very strange, to me your database may have a different encoding, make sure you use UTF-8.

Anyways, I hide the errors since the data we got seems useless anyways, should not be a problem.

**Comment by kangarko** [comment]
If you spot that "already in channel" one more time, set Debug to [cache-channels] and post the console spam from when it happens. All errors/stack traces together.

**Comment by xion87** [comment]
I use the db format latin or something... is that why i think

**Comment by xion87** [comment]
i have not see that error anymore but another one different, here is the server log with debug and errors.log 
[error.log](https://github.com/kangarko/ChatControl-Pro/files/2430417/error.log)
[2018-09-27-3.log.gz](https://github.com/kangarko/ChatControl-Pro/files/2430418/2018-09-27-3.log.gz)
