### ISSUE TITLE
Vip players, different color messages

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#933]
Player:
      Message: '&7{display_name} &b>>&7'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&7Message issued: &b{timestamp}'
        - '&7Click to send a PM'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: '/tell {player} '

this is the normal, so players messages are displayed on this color '&7'
i would like to make vip players messages appear in color '&f'
i tried but it didnt work, can anyone help me, thank you

**Comment by matt11matthew** [comment]
Can you please send me your whole config?

**Comment by LuisGVE** [comment]
Change on "VIP": Condition: '!player.hasPermission("chatcontrol.groups.vip")'

To: Condition: 'player.hasPermission("chatcontrol.groups.vip")'

Add to VIP group: chatcontrol.groups.vip

**Comment by dabou0** [comment]
i couldnt solve it, could you help me further ? ty
my discord is Dabou#9764

**Comment by LuisGVE** [comment]
That has to work, clearly you see the error in your configuration, but it works, you are the problem.

**Comment by kangarko** [comment]
Hey, I am not sure why the advice from @dabou0 should not work, but if you still have issues just replace the Condition to `Sender_Permission: "chatcontrol.groups.vip"` (the more official way on how to do it)

**Comment by dabou0** [comment]
ty everyone who helped me 
@LuisGVE 
@kangarko 
@matt11matthew  even tough you havent finished my plugin comission and said u had school, but i can see u have freetime to answer threads on github
