### ISSUE TITLE
Chat problem for TradeMe plugin

### ISSUE THREAD

**Issue by Duqino** [kangarko/ChatControl-Pro#934]
Hi,

Somehow the chat plugin wont show the trade request someone send to another player.

I know for sure the plugin sends it because /trade accept works fine. This means that or trademe plugin has a bug or your plugin is doing something funky.

I already posted this on the TradeMe plugin discussion forum.

Im not 100% sure which one is causing the problem. So posted it for both.

https://www.spigotmc.org/resources/trademe-with-api-to-create-custom-trades-1-7-10-1-13-x.7544/

Kind regards,

Duqino.

P.S

No errors just this -> https://pastebin.com/ZmAzU08b

**Comment by matt11matthew** [comment]
Hello, I don't think chatcontrol controls messages like that, I think it's an issue with your trademe plugin.

**Comment by kangarko** [comment]
Hello,

if you still have this issue, please try changing your listener priority of Formatter to either LOWEST or HIGHEST:

https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

**Comment by Duqino** [comment]
Did not fix my problem :(

**Comment by kangarko** [comment]
The pastebin log is not coming from ChatControl.

Sorry to tell but I suggest you write to that other developer. Not sure why ChatControl should be the cause of the problem, especially if you change the priority of Listener to HIGHEST or even MONITOR (try that one as well), or even try changing priorities for Checker

**Comment by Duqino** [comment]
Thank you so much for helping me even if your plugin is not causing the problem. Its pretty hard to get normal support these days :S

**Comment by kangarko** [comment]
Best of luck. Closing but you can comment below anytime you have issues. Make sure to leave a review if you are satisfied ;)
