### ISSUE TITLE
BungeeChat - Global Chat  - Hover Event

### ISSUE THREAD

**Issue by Imortalshard** [kangarko/ChatControl-Pro#935]
Hi,
I was wondering if it is possible to get a Hover_Event to target only the prefix when using Bungee Chat, as i'm wanting it so when players hover over any chat message (as i've forced global bungee chat) that it will show whatever is inside the Hover_Event in the formatting.yml

I've tried a few times but can't seem to get it to target the prefix only. It only worked when i didn't try to target the prefix.

**Comment by LuisGVE** [comment]
Show me your configuration

**Comment by kangarko** [comment]
Hey, you can just split it like so:

![a](https://i.imgur.com/voodoxo.png)
