### ISSUE TITLE
Kicked for Spamming

### ISSUE THREAD

**Issue by Linebeck** [kangarko/ChatControl-Pro#937]
I am not sure if it is this plugin 100% yet or not. But I have a 1.12 server, and I use ViaVersion to allow 1.13, and 1.13.1 users. When they type using their command system, or tab through the different commands. They get kicked for spamming.  It happens on various commands that are used. It's an odd issue, and I wondered if would have anything to do with this plugin.

https://youtu.be/7swA1Z_B9Sc

**Comment by kangarko** [comment]
I am sorry but ChatControl does not handle that spam-kick feature, but you can actually prevent it by giving players _chatcontrol.bypass.spamkick_ permission.
