### ISSUE TITLE
/msg useage message?

### ISSUE THREAD

**Issue by jakeroy** [kangarko/ChatControl-Pro#938]
Hi there,

This isn't so much of a problem but a question on how to customize the default Usage: msg <player> <msg> that chatcontrol seems to be providing (correct me if i'm wrong). 

Also on a side note, is it possible to allow auto tab completion for bungee messaging? When i press tab while doing /msg , nothing pops up unless a player is on the same spigot instance.

**Comment by kangarko** [comment]
Hey, see https://github.com/kangarko/ChatControl-Pro/wiki/Localization

Nope, Bungee does not cover that feature right now, sorry.
