### ISSUE TITLE
Support to other channel plugins

### ISSUE THREAD

**Issue by LuisGVE** [kangarko/ChatControl-Pro#939]
Add the option to change the format of other channel plugins or improve this channel system. Stop fleeing to suggestions!

Your channel system is too uncomfortable, because to change from reading to writing you need to exit the channel and enter again! So improve it since the survival servers that usually have several channels for users this is too uncomfortable.

Just make the last channel you have entered the channel where you write and the others only read, since the read / write system is disgusting. Thank you very much.

Best regards,

Luis

**Comment by kangarko** [comment]
Thank you for your suggestion. I am keeping this open as this has great value and I will be implementing this.

**Comment by LuisGVE** [comment]
When will it be implemented?

**Comment by kangarko** [comment]
Not sure, I cannot take more suggestions but our developer will.

**Comment by kangarko** [comment]
Channels were improved since, you can now switch modes by using /channel join command without the need of exiting.
