### ISSUE TITLE
Regular expression in Pro version does not work

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl-Pro#94]
I use this regular expression in ChatControl to be able to work very well.
But in ChatControlPro but can not work.
why don't you show the number 9
I tried ^/nick &&&9 and ^/nick &&\9 but it didn't work
![image](https://cloud.githubusercontent.com/assets/15712089/17720756/0dccf410-6457-11e6-9e06-6e909d1208c5.png)

```
match ^/[nN][iI][cC][kK]\b .*&[0-9,a-f,lmonk].*
id /nick
then warn &bYes, we are giving away OPs. Seriously, what did you expect?!
then notify chatcontrol.notify.rulesalert &8[&7ID %ruleID&8] &7%player: &f%message
then deny
then log
```
Nothing happens.I don't know where it went wrong.
![image](https://cloud.githubusercontent.com/assets/15712089/17720785/4c28d116-6457-11e6-8b05-f1c519a19c1b.png)
![image](https://cloud.githubusercontent.com/assets/15712089/17720803/8bc0dcc4-6457-11e6-8f9a-ebe8ea3ad3bb.png)

**Comment by kangarko** [comment]
Please test with having **Regex_Strip_Colors** set to **false** in settings.yml
