### ISSUE TITLE
/g<space> disconnects

### ISSUE THREAD

**Issue by cdmvirt** [kangarko/ChatControl-Pro#940]
Not sure if it a chatcontrol issue but when anyone on my server does /g and a space, they get kicked with this message:

![image](https://user-images.githubusercontent.com/6846286/46171165-fe0f5e80-c25c-11e8-96fd-964a085e8738.png)

**Comment by kangarko** [comment]
Make sure you have latest Spigot or PaperSpigot and ProtocolLib. Otherwise, not our issue. Set Packets.Enabled to false when on 1.13.1, as this part is not working for that version.
