### ISSUE TITLE
Placeholders don't parse in messages through discord to Admin_Chat

### ISSUE THREAD

**Issue by lewis2470** [kangarko/ChatControl-Pro#943]
When sending messages through a channel in my discord called #admin_chat which is connected to the Admin_Chat feature in ChatControl, it successfully sends but uses the Admin_Chat formatting for a player and does not parse any of the placeholders used in it.

Message output
![image](https://user-images.githubusercontent.com/12457072/46375074-4af29b00-c68a-11e8-9f2a-79cf0d632514.png)

Admin_Chat formatting for the player in formatting.yml
https://hastebin.com/iquyowidey.bash

Admin_Chat settings in settings.yml
https://hastebin.com/amenejodof.bash

**Comment by kangarko** [comment]
Hello,

Discord cannot translate variables since we need a player instance to do so. I am leaving this open so I will add an alternative format from messages sent from Discord so they are printed out nicely without the leftovers.

**Comment by xH3LLRAIZ3Rx** [comment]
@kangarko Seems to work with staff chat for me, its only admin chat that it doesnt work

**Comment by kangarko** [comment]
When you are connected to the server, we use your player instance to replace variables from there.

**Comment by xH3LLRAIZ3Rx** [comment]
Then it should work in admin chat as well, for some reason its not.

**Comment by kangarko** [comment]
Thanks, I added that.

**Comment by kangarko** [comment]
After going through this issue we decided not to expand it, there is some limited functionality to that already, sorry
