### ISSUE TITLE
Using /r for reply creates error in console

### ISSUE THREAD

**Issue by Zoneman1972** [kangarko/ChatControl-Pro#944]
Hey there. Just wanting to let you know that when a player uses /r to reply to a private message, I get the following error message pop up in the console.
There doesn't seem to be any other issue created other than that log in console. The players message gets through ok.

http://prntscr.com/l2st1a

Thanks
Zonemann

**Comment by CypherPhyre** [comment]
I too have this issue. Only happens when a player uses the /r command. All other commands work without errors.

**Comment by kangarko** [comment]
Apologies for this, should be fixed in the next version.
