### ISSUE TITLE
Comments removed

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#948]
I know, updating files can remove comments.
Every time I prepare a new settings according to the new standards.
I have my own settings file. Updating to 7.9.28 (and above) the toggle commands are forced.
You can't have a file without.
```
    Whitelist_Works_Like_Blacklist: true
 
    # Commands that the player can run them multiple times after each other.
    Whitelist_Similarity:
    #- /tell
    #- /pm
    #- /t
    #- /w
    #- /r
    #- /togglepm
    #- /togglebroadcast
```
I fully understand if it concerns a new option. But this part is optional.

**Comment by kangarko** [comment]
Sorry, but the YAML library that Bukkit/Spigot does not support comment saving.

**Comment by x1p** [comment]
I'm sorry but you missed the point.

I know that comments are removed if an option is added. Normally I would be able to enable or disable any item, or all item without deleting the comments. So previously it was ok to have all grayed out. Since the version which introduced the toggle, you need at least one item in this section. Otherwise it will force all these default lines here and remove the comments.
```
    - /tell
    - /pm
    - /t
    - /w
    - /r
    - /togglepm
    - /togglebroadcast
```

**Comment by x1p** [comment]
Introducing a not existing command will do the trick for me. But I'm convinced this should not be necessary.

**Comment by kangarko** [comment]
Are you sure that setting it to Whitelist_Similarity: [] will still generate defaults?

**Comment by x1p** [comment]
I have to admit I did not do the `[]` 
So just:
```
Whitelist_Similarity:
# - notthisone
```

**Comment by kangarko** [comment]
That is invalid syntax in YAML, use [] instead.
