### ISSUE TITLE
[Feature Request] Silent join/quit

### ISSUE THREAD

**Issue by glorying16** [kangarko/ChatControl-Pro#949]
I know we can set the join and quit messages to be silent when vanished, but I would like to be able to have a permission to silence them per person. I know other plugins can do this, but I would like to use chat control for it.

**Comment by kangarko** [comment]
Hey, we already have permissions for these:

![a](https://i.imgur.com/V77kEYh.png)

**Comment by glorying16** [comment]
Oh....I feel dumb. Thanks!
