### ISSUE TITLE
ChatControl Pro 7.0.9 not work

### ISSUE THREAD

**Issue by xyblues** [kangarko/ChatControl-Pro#95]
Spigot Version: PaperSpigot1.8.8
Java Version: JAVA8
Plugin Version: 7.09
https://ooo.0o0.ooo/2016/08/17/57b4ef3a02830.png

**Comment by EvilOlaf** [comment]
Make sure your firewall does not block outgoing connections from CB/Spigot.

**Comment by xyblues** [comment]
I am also in China
You said the 6.10 version has been fixed on this issue, but I now use 7.0.9 but not normal work

**Comment by EvilOlaf** [comment]
Probably the Chinese authorities adjusted their firewall xD

**Comment by xyblues** [comment]
Uh... I test the normal on the other server.
May be my connection is not good, thank you.

**Comment by kangarko** [comment]
According to my foundings, ChatControl is accessible in China. There are more then just two Chinese users, and this is only the second complain about this so please check your server firewall or connection in general.

http://www.greatfirewallofchina.org/index.php?siteurl=www.chatcontrol.6f.sk
