### ISSUE TITLE
Question on formatting

### ISSUE THREAD

**Issue by glorying16** [kangarko/ChatControl-Pro#951]
I use chat control for the login and log out messages for my server. I used to use EssentialsX for this, but im attempting to make the switch to CMI, and wanted to try to keep all my chat things with CC. The only issue is that I use the geoIP feature of EssentialsX which will show (based on permissions that track and show) the geo location of the user on login. Would it be possible to somehow connect that feature to the login of chat control? I only want it to be visible to those who I give permission to, and tracked by those I give permission to. This feature isnt available through CMI in the way I want it used, but it is tracked by it. Im sure I could probably use the placeholderAPI for the data itself, but im more concerned about the permissions factor. If this isnt possible in the current state, is this something you would consider implementing? Im not sure if it is just too far outside the chat realm for CC.

**Comment by kangarko** [comment]
We already have {country_code} variable(s), see https://github.com/kangarko/ChatControl-Pro/wiki/Variables#native-variables

**Comment by glorying16** [comment]
Cant believe I missed that! Is there a way to make it only visible to those with a specific permission? Im sorry if I am missing it somewhere.

**Comment by kangarko** [comment]
Sorry, that is not possible at the moment :(

**Comment by FrozenBeard** [comment]
Was this ever fixed? im also wanting to replace the Essentails login/out messages but we are reliant on GeoIP

**Comment by kangarko** [comment]
Hi,

I think so, you can use the {country_code} variable normally in a format part, and assign a Sender_Permission key to that part so it'll only be shown if the sender has a certain permission. Currently there's no Receiver_Permission key and that's something we're looking out to add in the future.

GeoIP is supported in player-event messages as well.
