### ISSUE TITLE
What shoud that

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl-Pro#954]
I've paid a lot of money for this plugin Now I want it to work It can not be that I get this error I've paid for it so I want it to work If this is not resolved I will file a criminal complaint for fraud

<0> An error occured: hamF2YS5pby5JT0V4Y2VwdGlvbjogU2VydmVyIHJldHVybmVkIEhUVFAgcmVzcG9uc2UgY29kZTogNDAzIGZvciBVUkw6IGh0dHA6Ly9rYW5nYXJrby5jb20vYXV0aC9wdXJpZnlfNC5waHA=
[00:37:32 INFO]: [ChatControl] Disabling ChatControl v7.9.25
[00:37:32 INFO]: Plugin might not shut down property. Got NullPointerException: null

Please fix that. my complete server is not working any more

**Comment by DevJoey** [comment]
Here the Screen i have buyed the Plugin -> http://prntscr.com/l853m7

**Comment by DevJoey** [comment]
#Fix Sorry for Swearing buddy

**Comment by kangarko** [comment]
Update to the latest version.
