### ISSUE TITLE
Private Messaging

### ISSUE THREAD

**Issue by iPintoBean** [kangarko/ChatControl-Pro#958]
I have been struggling to try and figure out how to get the private messaging formatting to work. I have given all the permission but every time I try to Message I get the default "whisper" format. I've spent hours on this so any help would be greatly appreciated.

**Comment by iPintoBean** [comment]
:) This whole time I overlooked that one setting. Thank you

**Comment by iPintoBean** [comment]
In order to get the PM to work over bungee I just need to set bungee to true on all my servers?

**Comment by kangarko** [comment]
Yes, and as well Private_Messages.Bungee to true and install BungeeControlBridge.
