### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by Slaand** [kangarko/ChatControl-Pro#959]
Hello,

There is an issue with negate chatcontrol.bypass.rules.commands (maybe not only .commands one) with **star permission**. Only chatcontrol.bypass.rules.* is working, which is not the best problem solution for me.

Permissions was taken from: https://github.com/kangarko/ChatControl-Pro/wiki/Permissions
Plugin version: ChatControl Pro 7.9.31
Permission plugin: PermissionsEX 1.23.4
In logs: nothing special
commands.txt (part): https://pastebin.com/aq3uQ5y2
permissions.yml (part): https://pastebin.com/MzyYDxAs

**Comment by kangarko** [comment]
@jascotty2 are you able to reproduce please?

I will get back to you in 48h

**Comment by kangarko** [comment]
Could not reproduce. I am traveling until November 2nd. Our developer will take a look on Monday.

**Comment by jascotty2** [comment]
Using command rules for `'*'` requires that you also have the negative perm `-chatcontrol.bypass.rules.global`
If you have the global bypass permission, none of the filters will be run for you
