### ISSUE TITLE
Color Code Issue

### ISSUE THREAD

**Issue by TheFluffyWalrus** [kangarko/ChatControl-Pro#96]
Best way i can describe the issue is with some pictures...
If you use a color code and ChatControl auto Corrects something it wipes the color code i don't know if this can be fixed
http://i.imgur.com/Ab2G3Jr.png

http://i.imgur.com/MbHNNXL.png

Won't should be red not white

**Comment by kangarko** [comment]
Cannot reproduce. Do you have proper permissions? Does it also happen if you turn the feature (Chat.Grammar.Capitalize and Chat.Grammar.Insert_Det) off?

If you are using Essentials, also ensure users have the chat colour permission from there as well (essentials.chat.color.*)
