### ISSUE TITLE
Handle_As_Chat breaks essentials messaging

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#961]
When I try to set commands like /msg, /w, /t, or /r in Anti_Spam.Handle_As_Chat, then try to message someone (i.e. /msg [playername] [message]) essentials gives Error: Player not found.

No idea what could be causing this, any help is appreciated :)

**Comment by kangarko** [comment]
It may be that we add colors & to the player name - if you enable private messages in ChatControl or disable Sound Notify that will be fixed.

**Comment by kangarko** [comment]
It may be that we add colors & to the player name - if you enable private messages in ChatControl or disable Sound Notify that will be fixed.
