### ISSUE TITLE
Same Error on all versions.

### ISSUE THREAD

**Issue by DevJoey** [kangarko/ChatControl-Pro#966]
I paid 10 euros for this plugin, so I want a plugin that works and not a plugin that is disabled at startup. Fix this error please

 <0> An error occured: ?amF2YS5pby5GaWxlTm90Rm91bmRFeGNlcHRpb246IGh0dHA6Ly9rYW5nYXJrby5jb20vYXV0aC9wdXJpZnlfNC5waHA=
[14:49:49 INFO]: [ChatControl] Disabling ChatControl v7.9.32
[14:49:49 INFO]: Plugin might not shut down property. Got NullPointerException: null

**Comment by Jerlag01** [comment]
having the same issue as this on versions from 1.8 till 1.7.10 and get this from 1.7.10
https://github.com/kangarko/ChatControl-Pro/issues/965

**Comment by DevJoey** [comment]
Absolutely fucking these drecks error. Why I buy a plugin, which is not .. I'll report if that goes on. is yes fraud.

**Comment by Slaand** [comment]
To be honest, I have the same problem, when at scheduled server restart CC Pro does not start at all. If @kangarko needs console error, I can provide a little bit later

**Comment by kangarko** [comment]
We had a recent downtime due to update servers being upgraded to more secure connections. Not sure why this is happening but the last downtime was few hours ago and is now over. I apology for the inconvenience.

Redownload the most recent jar and comment below if issues persist.
