### ISSUE TITLE
ChatControl can't parse Skript Placeholders.

### ISSUE THREAD

**Issue by xGioChR** [kangarko/ChatControl-Pro#967]
Hi,
I'm using ChatControl Pro v 7.9.32, with placeholderapi and every expansion I need.
When I use a placeholder from a Skript variable, the plugin seems to fail to parse it.
Example: {skript_test.{player_uuid}}
Am I doing something wrong?

**Comment by kangarko** [comment]
This is support channel for the free version.

I dont know, we take no responsibility for external plugins, sorry.
