### ISSUE TITLE
Assign a change on world change

### ISSUE THREAD

**Issue by nijayx123** [kangarko/ChatControl-Pro#97]
Is there a permission to FORCE join a channel? 

For example, say if you're in Lobby world and you just switch to a Pvp World. You will ForceJoin the channel for the Pvp world, and when your going back to Lobby, you ForceJoin back to the channel for Lobby. 

So basically, Its works like a Per World Chat, when switching between worlds, without having to use the channel join/leave command.

Permission Suggestion:
chatcontrol.channel.{channel}.forcejoin

**Comment by kangarko** [comment]
Hello,
currently you can force channel on join, but not change it on world switch. This is planned and thus I am leaving this open.

**Comment by kangarko** [comment]
Merged to road-map, closing.
