### ISSUE TITLE
Tabcomplete functionality

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#975]
The tab complete hinding functionality is pretty lame. Disabling the whole functionality is possible under spigot, so there is no sense in enabling it in CHC. (Packets.Tab_Complete)

If I want to turn on tab completion in spigot, plugins will start to show functionality of things, even if a player is not allowed to execute any of this. This is due to bad tab complete implementation of plugins. A plugin should not reveil information if a player has no permission. Negative permissions won't always help.
Even ChatControl itself show more than a player has the permission to use. Examples: `channel`, `chc`, `chatcontrol`

It would be nice if this functionality comes back in CHC as stated in issue #898 

If this is not possible, I would like to suggest a new functionality:
A blacklist to prevent certain plugins or commands.

Example:
Vault has two commands:
```
/vault-convert
/vault-info
```
Example blacklist:
`  - vault.*`

I hope this is clear enough. If any question may rise, please let me know.

**Comment by kangarko** [comment]
Thank you for your suggestion, I am aware of the limitations of tab-complete in ChatControl for 1.13. I cannot take any more suggestions now but will head this over to our developer.

**Comment by LogGits** [comment]
I also would like this. Atm I'm trying to hide commands that players don't have access to. Chatcontrol is one of them. There reason why its showing in tab-complete is because spigot isn't checking the plugin.yml after startup. You can also utilise spigots new `PlayerCommandSendEvent` to get the player and modify their tab-complete collection. You could even manually check perms for this however that's alot of permission checks.

**Comment by CypherPhyre** [comment]
I also had this issue. It is the new tab suggestions that 1.13 added. I have asked several plugin devs for a solution as it revealed my anti-cheat plugin. One dev has been able to implement a working solution that adds permission specific whitelists for what you want the players to see and nothing more. It is a premium plugin that Gasha has.

**Comment by kangarko** [comment]
We are already using the new event however checking permissions is impossible because each plugin has different permission names.

Cypher, thanks for suggesting that out.

**Comment by kangarko** [comment]
Could you add a new tab-complete list handler. Whereby we specify a few things:
1) blocking a command from showing up the tab-complete list.
2) blocking a command in the tab-complete list if a player has `x` permission.
3) blocking multiple commands from the tab-complete list if player has `x` permission
```yaml
BlockTabComplete:
   #Blocks commands in general for everyone.
   Commands:
   - help
   - spy
   - socialspy
   #Blocks commands if the user doesn't have the permission node specified.
   Permissions:
       test.permission.node: command
       test.permission.node2: command1, command2, command3
```
This should be relatively easy to implement as it would be done in something like this:
```java
 @EventHandler
    public void onSendCommand(PlayerCommandSendEvent event) {
        if(event.getPlayer().hasPermission(x)){
            event.getCommand.remove(x);
            // or event.getCommand.removeAll/removeIf(string -> string.equalsIgnoreCase(x))
        }
    }
```

**Comment by kangarko** [comment]
Personal note: see plugin AntiCommandSuggestions for potential solutions

**Comment by kangarko** [comment]
Pulled to the roadmap
