### ISSUE TITLE
[request] /motd RSS feed for blogs/forums

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#979]
Requesting a way to input a RSS feed into the MOTD message so I can have dynamic Forum thread input or blog input, it drives me mad having to write up all the posts for the forum & blog and then write the MOTD too.
Im currently using EssentailsX for my MOTD but I just saw this comment https://github.com/kangarko/ChatControl-Pro/issues/535#issuecomment-358360920 that mentions its possible to use the formatting to have JSON MOTD! this got me super excited as this means I could have a [Read More] instead of having to use bitly urls that take up so much room.

Another thing that drives me mad is the limit to 9 lines in the motd, if it goes over 9 mines, it should send it as a second message directly after so the user cannot tell its been sent twice.

Being able to accept RSS would allow input from most nearly all web apps people run, they could pull data from anything and would be incredibly handy.

But make sure we can customise the format of the RSS formatting ourselfves for the $title $link $description and $date 

Here is an example of my RSS feed for my updates forum https://piratemc.com/forums/piratecraft-server-development/feed/

I will later be moving my changelogs to the default wordpress blog which follows this structure https://piratemc.com/feed/ so if you were to only support 1 type of RSS feed, please make it Wordpress blogs as its the most universal out there.

Thanks

**Comment by kangarko** [comment]
Hello,

an amazing idea for sure, I will talk to my dev and see if this can be implemented. We are not very open to suggestions for a few months now, but I am definitely leaving this open.

Also, what do you mean with the 9 lines limit? This is something we cannot change and it is in the vanilla Minecraft.

**Comment by FrozenBeard** [comment]
For the 9 lines of text, if I say put in 2 line's it would just split it up into 2 messages and send them one after each other instead of pagenation.

**Comment by FrozenBeard** [comment]
I didn't even test it, I just use essentials! No worry then!

**Comment by kangarko** [comment]
Hey, I am closing this, our plate has been overflowing for over one year and I had to prioritize some features over another, otherwise I am stuck and nothing gets implemented. 

Features that I frequently receive suggestions about will be prioritized. Thank you for your understanding.

**Comment by FrozenBeard** [comment]
:(
