### ISSUE TITLE
[request] Formatting folder

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#980]
Request, where we have formatting.yml, this can get overwhelming with so many thigns inside it, if we could have it so any yml files inside a new ./formatting folder would be loaded, we could organise as we please. so I could have a motd.yml that I could keep all my MOTD information and copy/paste data in.

**Comment by kangarko** [comment]
Thank you for your suggestion, but we are not planning to include it any time soon.
