### ISSUE TITLE
Deathmessages for drowned and phantoms

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl-Pro#981]
Hejo,

could you please add the possibility of setting up death notices for drowned and phantoms? My players and I would really love that. You may also be able to add the death messages I requested a few months ago and which are still on your to-do list. I know you're very busy and need to prioritize, but maybe you'll have a few minutes left for this mainly industrious task. Death messages are a popular feature and gaps are often reported by players. Keep up your great work!

**Comment by kangarko** [comment]
Hello,

I haven't tested, but are you able to make a new condition for DROWNED and PHANTOM using the entity types at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html ?

You can add them in messages.yml -> Death_Messages.Entity_Attack.Conditions and make a new condition with a different killer and other properties than the highlighted part below:

[a](https://i.imgur.com/fjA2yyP.png)
