### ISSUE TITLE
Question about TownyChat

### ISSUE THREAD

**Issue by LuisGVE** [kangarko/ChatControl-Pro#983]
How works this update? https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro-format-and-filter-your-chat-1-7-10-1-13.10258/update?update=251813

I need TownyChat installed and list all channels of channels.yml of Towny?

**Comment by jascotty2** [comment]
If you're using TownyChat, this update helps bridge ChatControl formatting and Towny channel formatting.
For example, if you wanted ChatControl to handle formatting for general chat, but let TownyChat handle other channels, you could set

Towny_Chat: 
  Channel_Mode_Replace: true
  Channels: 
    - general
