### ISSUE TITLE
Get all players to Globalchannel

### ISSUE THREAD

**Issue by tw1xen** [kangarko/ChatControl-Pro#987]
Ive set Bungee to true in settings.yml but the chat dosent get cross-over, i need to type /chatcontrol g switch on me so my chat will get cross-over. I Dont understand how to get ALL players to get cross-over chatt. Ive read ALL info. I think it is something in channel.yml but i dont know what. Please help me i have been looking around for 2 weeks now

**Comment by kangarko** [comment]
Enable this option:

![a](https://i.imgur.com/c9NnH1V.png)
