### ISSUE TITLE
Console registers 2 messages when one is sent...

### ISSUE THREAD

**Issue by axemwa** [kangarko/ChatControl-Pro#989]
This is what appears when a player sends one message, shouldn't it only be 1 line? Or is the 2nd one discord?

[17:51:36 INFO]: [ChatControl 7.10.0] creating component [TownyChat] took 112 ms
[17:51:36 INFO]: [ChatControl 7.10.0] creating component [TownyChat] took 127 ms

Here's my [formatting.yml](https://pastebin.com/qDcnMqFA), [channels.yml](https://pastebin.com/BEdS1TkP) and [settings.yml](https://pastebin.com/bQWdcAEW) files

I'm using Minecraft 1.13.2 and Paper 451

**Comment by jascotty2** [comment]
The formatter is called for the different instances where it may be needed, so multiple calls per message are not too uncommon. 
The reason you're getting the messages seems to be that the formatting is not being completed in a timely manner, possibly because the server isn't fast enough to compile the format that's defined quickly.
To stop seeing these messages, you could change Log_Lag_Over_Milis in settings.yml to a higher value (ignores the problem), or lower the number of parts used in formatting the chat.

**Comment by axemwa** [comment]
I see how would I go about lowering the amount of parts used in formatting going by the formatting.yml paste i linked? And are u sure it might be that, as it's never done this before and server speed should be really good as I'm running it off my computer which runs really fast.

**Comment by axemwa** [comment]
Are these messages actually supposed to appear and/or is it just an indicator saying how long it took if it lagged?

**Comment by axemwa** [comment]
Also what does this part of formatting do?

Towny_Chat:
  Channel_Mode_Replace: true
  Channels:
  - '*'
  - general

**Comment by jascotty2** [comment]
The messages are logged if the formatter takes longer than it should (as defined in Log_Lag_Over_Milis), which generally indicates possible server lag.

The Towny_Chat section is a recent addition to add some handoff between TownyChat channel formatting and ChatControl formatting, should you want to use either of them depending on the TownyChat channel being used.

**Comment by kangarko** [comment]
Closing.

The more variables you put in, the more CPU cycle it takes to process them. Increase the lag threshold or ignore it.

Here are comments for the towny_chat part, let us know if you still dont understand a part (we still get notified even on closed tickets):

![a](https://i.imgur.com/R2nRv7R.png)

**Comment by axemwa** [comment]
Ok I think I understand it, so it basically allows you to be able to use townychat.jar formatting for town and nation chat channels and using chatcontrol formatting for standard/normal channels etc?

If this is the case and I understood your explanation correcty, I'd choose to keep using chatcontrol formatting for all channel types (standard, town and nation) rather than townychat.jar formatting because I don't think townychat formatting can interact with chat like chatcontrol does (click hover json etc)

**Comment by kangarko** [comment]
>Ok thanx for the explanations I think I understand it, so it basically allows you to be able to use townychat.jar formatting for town and nation chat channels and using chatcontrol formatting for standard/normal channels etc? Is that correct?
Yes that is correct :)
