### ISSUE TITLE
Issues with Socialspy

### ISSUE THREAD

**Issue by yooteri56** [kangarko/ChatControl-Pro#990]
I'm having an issue with SocialSpy: whenever I toggle /spy on, it just does not work. When a player use /msg, /tell or something like that, I just can't see their messages. 

Config: https://pastebin.com/4fUyRXWm

**Comment by jascotty2** [comment]
Cannot reproduce.

Is it possible that you're using a different plugin for /msg ?

**Comment by yooteri56** [comment]
No, I'm using ChatControl both for socialspy and messages, but the problem is that /spy just does not show when players use the commands I wrote in the settings.yml

**Comment by kangarko** [comment]
ZIP us your entire ChatControl (strip out the MySQL part of settings.yml for own security)

**Comment by yooteri56** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/2612386/ChatControl.zip)

**Comment by jascotty2** [comment]
Thanks for the additional information!

I figured out what's going on, and the next patch will have that fix included.

**Comment by yooteri56** [comment]
Okay, thanks <3
