### ISSUE TITLE
Feature request for channel switch

### ISSUE THREAD

**Issue by PlayDatblockCom** [kangarko/ChatControl-Pro#992]
The ability to use "/channel switch channel write" would be very useful, where you can switch write mode even though you're in read mode in multiple channels. 

This would make it possible to allow everyone to be in read mode in every channel and then let them easily chose write mode for 1 channel by using /channel switch channel write. 

I have tried setting up this system with the current commands, but I found it impossible to make it intuitive and I experienced a bug where it said I was in no channel when trying to chat, but when I tried to join a channel in write mode, it said I was already in that channel.

**Comment by jascotty2** [comment]
The channel system went through a functional overhaul as of 7.10: using `/channel join <channel>` to join a channel if there is only one write channel defined in the settings will switch to that channel and switch the current write channel to read mode (or kicks from channels until the read limit is satisfied).

Additionally, you can define `Commands` (as a bracketed list) under each command to provide shorthand switch or send commands. Eg, `/g` to replace `/channel join global` and `/g <text>` to replace having to type `/channel send global <text>`

**Comment by kangarko** [comment]
Closing, as @jascotty2 said the recent updates brought these long-awaited changes ;)
