### ISSUE TITLE
What is the /motd command?

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#993]
Trying to move from Essentails motd to Chat control.

- What is the /motd equivalent for chat control? There is no /chc motd or /chc news that I can see.
- With Essentails MOTD, there is no need to reload the plugin, you just update the motd file and its live, no need to do a plugin reload, can you please do the same for chat control.

**Comment by kangarko** [comment]
Added /motd command. You need to reload the plugin with ChatControl, this is by nature of our plugin.
