### ISSUE TITLE
Can you add a new permission for the color?

### ISSUE THREAD

**Issue by iskandarluqman** [kangarko/ChatControl-Pro#996]
**Suggestion**
So I want to use CHC color system for the chat. Just I got small problem. I dont want them to change to any colors they like. Maybe add permissions such as chatcontrol.color.red ? So basicly I want a specific color for each donor rank. If the the donor rank is green, I would make their chat color light green.

**Comment by kangarko** [comment]
Hey, please see the Wiki -> Permission and you can achieve that using "/chc color" menu, or creating individual chat format in formatting.yml with a part that only shows when the sender has that permission.
