### ISSUE TITLE
/chc setcolor

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#997]
When you type `/chc color green <username>`
and they dont have permission to use green, it doesnt set their colour to green.

**Comment by kangarko** [comment]
Such command argument does not exist at the moment, would you like to see that implemented?

**Comment by LogGits** [comment]
I thought this was added ages ago: https://github.com/kangarko/ChatControl-Pro/issues/767

**Comment by kangarko** [comment]
I see, we only implemented viewing ability but not changing, will be added soon. Sorry about that!

**Comment by kangarko** [comment]
@jascotty2 can you please implement a new command /chatcontrol setcolor <player> <color> [decoration]? Permissions will be ignored except for the base command permission, since this command is for admins allowing to override what players have set for themselves.

**Comment by kangarko** [comment]
I totally forgot to close this, this command has been added long time ago :)
