### ISSUE TITLE
Proper permissions not being given.

### ISSUE THREAD

**Issue by RogerPlaysMC** [kangarko/ChatControl-Pro#999]
I'm the dev working with iPintoBean from issue #976. On server restart ChatControlPro refuses to recognize anyone with perms as able to use /chatcontrol ach <message>.  We get the default Spigot no perm message.  Upon reloading the plugin via /chc reload it works fine, so there is an issue where ChatControlPro is either failing to read perms, or using a perm set that was generated before the perms plugin (we've used both LuckPerms and PEX) had a chance to kick in.  Before reloading, only op's can use /chc ach.

Using "/lp user <username> permission set chatcontrol.commands.adminchat" from LuckPerms so an individual is given the permission after everything is loaded, ChatControlPro still ignores the permission until it is reloaded.

Edit: Additionally I gave a user the permission “chatcontrol.*” and no change, ChatControlPro acted like there was no perm until it was reload, it which time it worked fine. 

Edit 2: This issue has actually started propogating through all of our 1.8.8 servers, not just the ones on BeerSpigot.

Running BeerSpigot (1.8.8)
LuckPerms (latest, but same issue with other perms plugins)

**Comment by jascotty2** [comment]
This is a curious issue, and doesn't happen on modern versions of minecraft server.

I'll take a look into this. As an aside, are you using Vault for permissions integration?

**Comment by jascotty2** [comment]
So far, I'm unable to get the permissions to load by reloading ChatControl after a reload, using the old version of PEX - The newest build seems to run fine in 1.8.8, and updating PEX solved the issue for my test. (Another solution was to have the user log out of the server and re-join)

This seems to either be an issue with the permissions plugin you're using (PEX 1.23.4 works fine for me), or possibly an issue with how BeerSpigot reloads plugins (I don't have a copy to test with)

**Comment by RogerPlaysMC** [comment]
We were using pex 1.23.4 when the issue started, and switched to the most recent luckperms a short time ago, but the problem persisted. 

Not sure on the vault portion, we do have it installed and on the latest version. 

As far as another plugin hijacking the commands, we are running an alias plugin where we replace /chc ach with /sc. I could check to see if that is causing the interference and code my own alias plugin if that’s the case.

**Comment by kangarko** [comment]
@jascotty2

**Comment by RogerPlaysMC** [comment]
Just to chime in again on this, it is not happening to the 1.12.2 server on our network, so it seems to be limited to 1.8.8.

**Comment by kangarko** [comment]
I apology that it takes so long. LuckPerms has a debug option, can you please turn it on and post the console or in-game spam when the permissions are checked for, when the problem happens?

**Comment by RogerPlaysMC** [comment]
Hopefully we’ll have results for you tonight.

**Comment by RogerPlaysMC** [comment]
Debugging was turned on. It showed the player user group upon login. When /chc was used, the error "I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error." is presented to the client, nothing but the command to the console.
`12.12 01:44:41 [Server] INFO [LuckPerms] Processing pre-login for 99350003-c7f2-49ac-8ac3-85590d5b6f2b - Brick_Master_Raj
12.12 01:44:41 [Server] INFO UUID of player Brick_Master_Raj is 99350003-c7f2-49ac-8ac3-85590d5b6f2b
12.12 01:44:41 [Server] INFO [LuckPerms] Processing login for 99350003-c7f2-49ac-8ac3-85590d5b6f2b - Brick_Master_Raj
12.12 01:44:41 [Connect] User Brick_Master_Raj, IP XXX.X.X.XXXX
12.12 01:44:41 [Multicraft] Brick_Master_Raj ran command Message of the Day
12.12 01:44:41 [Server] INFO [LuckPerms] [VAULT-PERMS] #userGetPrimaryGroup: brick_master_raj - cannon - dev
12.12 01:44:52 [Server] INFO Brick_Master_Raj issued server command: /sc Test
12.12 01:45:03 [Server] INFO Brick_Master_Raj issued server command: /chc ach Hello?
12.12 01:45:53 [Server] INFO Brick_Master_Raj issued server command: /lp user Brick_Master_Raj INFO
12.12 01:46:17 [Server] INFO Brick_Master_Raj issued server command: /chc`
So no issues with the permissions were reported by LuckPerms. Upon reloading ChatControlPro:
`12.12 01:53:19 [Server] INFO *-----------------------------------------------*
12.12 01:53:19 [Server] INFO Reloading plugin ChatControl v7.10.6
12.12 01:53:19 [Server] INFO *-----------------------------------------------*
12.12 01:53:19 [Server] INFO [DiscordSRV] API listener me.kangarko.chatcontrol.final. .COm2 unsubscribed
12.12 01:53:19 [Server] INFO 43 global, 15 chat, 4 command, 2 packet and 1 book rule(s) found
12.12 01:53:19 [Server] INFO Hooked into: DiscordSRV
12.12 01:53:19 [Server] INFO [DiscordSRV] API listener me.kangarko.chatcontrol.final. .COm2 subscribed (1 methods)
12.12 01:53:19 [Server] INFO Chat formatting may interfere with WorldGuard. If so, please change Listener_Priority.FORMATTER to HIGH to fix it.
12.12 01:53:19 [Server] INFO Formatter listening at normal priority
12.12 01:53:19 [Server] INFO BungeeCords enabled. See www.spigotmc.org/resources/13079
12.12 01:53:19 [Server] INFO Configuration reloaded successfully.
12.12 01:53:44 [Server] INFO Brick_Master_Raj issued server command: /chc ach Test
12.12 01:53:44 [Server] INFO [STAFF][Brick_Master_Raj]: Test `

**Comment by kangarko** [comment]
Hey, apology for the big delay. We are not able to solve this problem, as it is unclear where it comes from. As a last resort you can try editing your plugin.yml inside ChatControl (you will have to do this each time you update) to add LuckPerms plugin into this line:

![a](b)

As a compensation for delay and not solving this I am offering you 1 premium plugin for free for a lifetime, just PM me on Spigot with your nickname.
